### ISSUE TITLE
Feature Request: Add debounce method

### ISSUE THREAD

**Issue by c4spar** [denoland/deno_std#1008]
This is a feature request for adding a debounce function to the async module.

I always use a `debounce` function along with the `Deno.watchFs` method and I have seen it in other projects as well.
So I think this is a useful function that could be added to `deno/std`.

I have already opened a PR with a first version of how the module could look like (#1006).
I added it to the `async` module rn, but i'm not sure if that's the best place.

Proposed typings:
```ts
declare interface DebouncedFunction<T extends Array<unknown>> {
  /** Calls the function with a delay. */
  (...args: T): void;
  /** Clears the debounce timeout without calling the debounced function. */
  clear(): void;
  /** Clears the debounce timeout with calling the debounced function immediately. */
  flush(): void;
  /** Returns a boolean wether a debounce call is pending or not. */
  readonly pending: boolean;
}

declare function debounce<T extends Array<any>>(
  func: (this: DebouncedFunction<T>, ...args: T) => void,
  wait: number,
): DebouncedFunction<T>;
```
Usage example:
```ts
import { debounce } from "https://deno.land/std/async/debounce.ts";

const log: DebouncedFunction<[string]> = debounce(
  (param: string) => console.log(param),
  200,
);

log("foo");
log("bar");
log("baz");
// wait 200ms ...
// output: baz
```

**Comment by wperron** [comment]
This seems based off of the [debounce package on npm](https://www.npmjs.com/package/debounce) -- I think this is reasonable. I'm wondering if we should change `T extends Array<any>` for `Iterable<T>` instead. @lucacasonato wdyt?

**Comment by c4spar** [comment]
yep, its based on the debounce package with the pending property from lodash/debounce:
* debounce: https://github.com/component/debounce/blob/master/index.js
* lodash/debounce: https://github.com/lodash/lodash/blob/master/debounce.js

**Comment by c4spar** [comment]
@wperron `Iterable<T>` doesn't work with rest parameters: `A rest parameter must be of an array type.`

**Comment by kt3k** [comment]
I'm in favor of adding this to std. `std/async` sounds ok to me because debounce is usually used in the context of async programming.

About typings, `DefinitelyTyped` of lodash defines T as `T extends (...args: any) => any` and uses the returned type `(...args: Parameters<T>): ReturnType<T> | undefined;`. ref: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/0b133919d9f992221836a7318a0353a1e9a9e5b3/types/lodash/common/function.d.ts#L418

I think this definition is cleverer than the poposed one because it supports any shape of functions as input.

**Comment by c4spar** [comment]
@kt3k I used the typings you suggested in my first implementation, but then i removed the ReturnType to keep it simpler and without ReturnType it was also simpler to use just the parameters instead of the entire function as `T`, but if we want to have the ReturnType i can add it again 👍

**Comment by ebebbington** [comment]
I think this would be useful, in my case I had to create my own debounce method (thanks to @caspervonb) when watching files (because of vscode sending multiple events):

```ts
public static debounce(context: string, fn: () => Promise<void>) {
    if (watchTimeouts[context]) {
      delete watchTimeouts[context];
      clearTimeout(watchTimeouts[context]);
    }
    watchTimeouts[context] = setTimeout(function () {
      fn();
    }, 100);
  }
  
 for await (const event of watcher) {
      const paths = event.paths;
      if (event.kind !== "modify" || paths[0].endsWith(".js")) {
        continue;
      }
      const path = Deno.build.os === "windows"
        ? relativeWin(".", paths[0])
        : paths[0];
      debounce(path, async () => {
      })
}
```

**Comment by kt3k** [comment]
@c4sper Ah I misunderstood the proposed type definition. I first thought `T extends Array<any>` doesn't cover the tuple types, but it seems supporting tuples. So the proposed definition now looks just fine to me.

**Comment by c4spar** [comment]
great, what about the namings?

* **clear()**: this method is called `clear` in the `debounce` package and `cancel` in `lodash/debounce`. i chose the `clear` method because it is similar to `clearTimeout`.
* **Debounce\<T>**: Lodash named this interface `DebouncedFunc`. Another name could be `Debounced` or `DebouncedFn`.

Lodash also has a `leading` and a `trailing` option. By default only `trailing` is enabled.
If `leading` is enabled instead of `trailing` and the debounced function is called multiple times, only the first call is executed instead of the last one (it's basicly an inverted debounce function):

```ts
const log: Debounce<[string]> = debounce((param: string) => console.log(param), 200, {
  leading: true,
  trailing: false,
});

log("foo"); // output: foo
log("bar"); // no output
log("baz"); // no output
// wait 200ms...
log("beep"); // output: beep
```

If both `leading` and `trailing` are enabled, the first and the last call are executed:

```ts
const log: Debounce<[string]> = debounce((param: string) => console.log(param), 200, {
  leading: true,
  trailing: true,
});

log("foo"); // output: foo
log("bar"); // no output
log("baz"); // output postponed...
// wait 200ms... output: baz
log("beep"); // output: beep
```

Do we want to have this `leading` and `trailing` functionality?
If we only need the `trailing` option, we could also create two different methods for it. A `debounce` method that calls the func on the trailing edge and a `throttle` method that calls the func on the leading edge.
If you are in favor of us having a `throttle` method as well, I can open a second PR!

**Comment by wperron** [comment]
>   clear(): this method is called clear in the debounce package and cancel in lodash/debounce. i chose the clear method because it is similar to clearTimeout.
    Debounce<T>: Lodash named this interface DebouncedFunc. Another name could be Debounced or DebouncedFn.

`clear` is fine imo, either `DebouncedFunc`, `DebouncedFn` or `Debounced` would be nice, I think it's an improvement over `Debounce<T>`.

I think for now we can keep the function signature simple with only the `func` and `wait` parameters, using `trailing` as our default behavior as I think that's what most people will expect. We can always add this third option bag parameter later down the road.

**Comment by c4spar** [comment]
I was just looking through the project to see if we have some conventions on how we name function types.

It seems that for properties and variables we mostly use `fn` as naming convention. For types and interfaces we mostly use the convention `FooFunction`.

| File                      | Types                                |
| ------------------------- | ------------------------------------ |
| `testing/bench.ts`        | `BenchmarkFunction`                  |
| `datetime/tokenizer.ts`   | `TestFunction`, `CallbackFunction`   |
| `encoding/_yaml/parse.ts` | `CbFunction`                         |
| `log/handlers.ts`         | `FormatterFunction`                  |
| `node/events.ts`          | `GenericFunction`, `WrappedFunction` |
| `node/module.ts`          | `RequireFunction`                    |
| `examples/xeval.ts`       | `XevalFunc`                          |

So, i think we should go with `DebouncedFunction` to be consistent.

**Comment by wperron** [comment]
That sounds great, let's go with that! thanks for the due diligence on this
