### ISSUE TITLE
base64url decoder allows decoding base64

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno_std#1011]
The encoding/base64url.ts decoder allows decoding base64 (not base64url) encoded strings.

![image](https://user-images.githubusercontent.com/7829205/124811921-4ce89780-df63-11eb-9f26-931d49b6edd1.png)

The third case should error with the same error as the first case.

std@0.100.0 & deno 1.11.2 (release, x86_64-unknown-linux-gnu)

**Comment by TotallyNotChase** [comment]
I'd like to take this on if it isn't already being worked on. Should there be an extra check to make sure the input is valid base64url?

Also is the call to padding function necessary? Isn't this already handled by `atob`?
