### ISSUE TITLE
fs/mod.ts requires --unstable, even when only stable features are used

### ISSUE THREAD

**Issue by Nemo64** [denoland/deno_std#1015]
If you import `https://deno.land/std@0.100.0/fs/mod.ts`,
you get
```
error: TS2339 [ERROR]: Property 'utime' does not exist on type 'typeof Deno'. 'Deno.utime' is an unstable API. Did you forget to run with the '--unstable' flag?
    await Deno.utime(dest, statInfo.atime, statInfo.mtime);
               ~~~~~
    at https://deno.land/std@0.100.0/fs/copy.ts:96:16

TS2339 [ERROR]: Property 'utimeSync' does not exist on type 'typeof Deno'. 'Deno.utimeSync' is an unstable API. Did you forget to run with the '--unstable' flag?
    Deno.utimeSync(dest, statInfo.atime, statInfo.mtime);
         ~~~~~~~~~
    at https://deno.land/std@0.100.0/fs/copy.ts:111:10
[...]
```

The readme *does mention that* `fs` contains unstable api's, but not all of them are unstable.

Especially utilities like `ensureDir` and `expandGlob` use only stable functions and are really useful.

As a workaround, you can import those source files directly:
```ts
import {ensureDir} from "https://deno.land/std@0.100.0/fs/ensure_dir.ts"; // importing fs/mod.ts requires --unstable
import {expandGlob} from "https://deno.land/std@0.100.0/fs/expand_glob.ts"; // importing fs/mod.ts requires --unstable
```

But that isn't too obvious and I consider the source file location a private implementation detail (is it?).

While it is definitely a good error when you actually using those api's, they make you jump to the `--unstable` flag.

**Some ideas**

- A bc-breaking solution would be to have a `mod_unstable.ts` that includes all modules that are potentially unstable.
- I assume it isn't possible to tell the typescript compiler to ignore such errors on unused functions?
- Document the workaround? Or have a `mod_stable.ts`?

All of those aren't really good imo.

**Desktop (please complete the following information):**

- OS: Mac OS 11.4 (20F71)

```
deno 1.11.3 (release, x86_64-apple-darwin)
v8 9.1.269.35
typescript 4.3.2
```

**Comment by kt3k** [comment]
`mod_unstable.ts` sounds reasonable to me

**Comment by bartlomieju** [comment]
Closing in favor of https://github.com/denoland/deno_std/issues/1539
