### ISSUE TITLE
Coverage is not reported during CI

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno_std#1030]
Most likely the repository is uploading stale coverage report.

https://github.com/denoland/deno_std/blob/cb39391f02977d1c78a1772b2c68520a7671f96e/.github/workflows/ci.yml#L33-L34

There's no `--coverage` specified when running tests, so subsequent command that generates coverage report most likely uses already cached files from `./cov` directory.

**Comment by caspervonb** [comment]
Looks like this re-enabling was only partially done https://github.com/denoland/deno_std/pull/984
