### ISSUE TITLE
Formatting dates in the ISO 8601 standard

### ISSUE THREAD

**Issue by komyg** [denoland/deno_std#1039]
### Context

I think we are missing a formatting function on the `datetime` module that takes in a `Date` and returns it formatted in the ISO 8601 standard. 

Currently, the developers can format dates like this using the existing API, but I think that there is an advantage in having a specific function for this, because this way, the developer doesn't have to remember how to put the format together.

Furthermore, this format is very common when serializing objects to JSON in order to transmit them to and from an API.

### Proposed Solution

Create a new formatting function that will be responsible for this:

```ts
// Options type
type DateISOOptions = {
  format?: 'date' | 'date-and-time'; // Default value is: 'date-and-time'
}

// Function signature
function formatISO(date: Date, options?: DateISOOptions): string;

// Usage examples
const date = new Date(2019, 8, 18, 19, 0, 52);
const dateOnly = formatISO(date, { format: 'date' }); // 2019-09-18
const dateAndTime = formatISO(date); // 2019-09-18T19:00:52Z
```

### Alternatives
The same could be achieved by using the current API. But the developer would need to remember the format, and he could make mistakes.

```ts
const date = new Date(2019, 8, 18, 19, 0, 52);
const dateOnly = format('yyyy-MM-dd'); // 2019-09-18
```

### Important
I would like to also help by implementing this feature, if you think that it is valid.

**Comment by kitsonk** [comment]
We do not duplicate features already present in JavaScript/ECMAScript.  How is [Date.prototype.toISOString()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString) not sufficient?

**Comment by komyg** [comment]
Sorry, I forgot that standard Javascript already had that.

I am closing this issue.
