### ISSUE TITLE
asserts: False positives on Set/non-Set equality

### ISSUE THREAD

**Issue by thunderk** [denoland/deno_std#1044]
**Describe the bug**

Equality assertion in *testing* is wrongly true, when comparing a Set with another type of object.

**To Reproduce**

In REPL:
```typescript
> const {equal} = await import("./testing/asserts.ts");
> equal(new Set([1]), {});
true
```

**System**

Tested on std@0.78.0, std@0.97.0 and std@0.101.0.

deno 1.12.0 (release, x86_64-unknown-linux-gnu)
v8 9.2.230.14
typescript 4.3.2

**Comment by bartlomieju** [comment]
Should be fixed by #1000

**Comment by gtramontina** [comment]
FYI, #1000 is now merged.

**Comment by thunderk** [comment]
I confirm that it fixes this issue too, thanks!
