### ISSUE TITLE
[Feature Request] Add `findLastIndex` function to std/collections

### ISSUE THREAD

**Issue by kawarimidoll** [denoland/deno_std#1060]
`Array` has finding functions, `find()` and `findIndex()`.
`find()` returns the element, and `findIndex()` returns the index.

- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/findindex

Now, we have `findLast()` in std/collections, this returns the element.

- https://deno.land/std/collections/find_last.ts

So, how about add `findLastIndex()` ?
It is almost same as `findLast()`, but returns the index of the last found element.

```ts
import { Predicate } from "./types.ts";

export function findLastIndex<T>(
  array: Array<T>,
  predicate: Predicate<T>,
): number {
  for (let i = array.length - 1; i >= 0; i -= 1) {
    const element = array[i];

    if (predicate(element)) {
      return i;
    }
  }

  return -1;
}
```

**Comment by kt3k** [comment]
Because we already have findLast in std/collections, this proposal makes sense to me.

This can be implemented in V8 in some future https://github.com/tc39/proposal-array-find-from-last https://chromium-review.googlesource.com/c/v8/v8/+/3037160 . If that happens, then let's deprecate it.
