### ISSUE TITLE
Change color of log.info / Give ability to change or disable log colors

### ISSUE THREAD

**Issue by Jelledb** [denoland/deno_std#1077]
**Is your feature request related to a problem? Please describe.**
Logging `INFO` messages in PowerShell are not visible as the blue background of PowerShell interferes with the blue messages that `log.info(...)` puts in the console.

**Describe the solution you'd like**
Either turn the color off, change the color, or give devs the ability to change it.

**Comment by zhangyuannie** [comment]
See https://github.com/denoland/deno_std/discussions/740

The log module will be deprecated soon and users are not advised to use that.

**Comment by Jelledb** [comment]
> See #740
> 
> The log module will be deprecated soon and users are not advised to use that.

Ok, so what is the alternative? Native `console.log`? Or will there be a replacement?

**Comment by lucacasonato** [comment]
We already have native `console.log`.

**Comment by zhangyuannie** [comment]
> Ok, so what is the alternative? Native `console.log`? Or will there be a replacement?

You can create a custom logger wrapper easily and replace/expand it in the future as needs arise:
```ts
// logger.ts
export function info(...args: unknown[]) {
  console.info(Date.now(), ...args)
}

export function error(...args: unknown[]) {
  console.error(Date.now(), ...args)
}

// ...
```
`std` will likely not have a recommended logger in the near future.

**Comment by grian32** [comment]
There are quite a few simple loggers out in the wild aswell if you dont want to writer your own.

**Comment by LionC** [comment]
We are also working on an alternative log proposal right now, there is an open PR with some discussion.

**Comment by Jelledb** [comment]
We went ahead and went back to "roots" by relying on console.debug, console.error, etc. Have a look [here](https://github.com/meshcloud/collie-cli/pull/103/files#diff-7bc1140e724e284ae22084e1172568baa8d151063d02c75ed1d8805fa7796acaR4) if you're interested what we did.

**Comment by bartlomieju** [comment]
Can this issue be closed now @Jelledb?

**Comment by Jelledb** [comment]
> Can this issue be closed now @Jelledb?

Sure thing
