### ISSUE TITLE
httpServer.close() not working correctly with slow Reader responses

### ISSUE THREAD

**Issue by jakajancar** [denoland/deno_std#1089]
This is the example from the website, with 2 modifications:

 1. `s.close()` is scheduled after 5 seconds
 2. The response body is a slow `Reader`

```
import { serve } from "https://deno.land/std@0.60.0/http/server.ts";
const s = serve({ port: 8000 });
console.log("http://localhost:8000/");
setTimeout(() => { s.close() }, 5000)
for await (const req of s) {
  req.respond({ body: {
    // Drips an 'x' every second
    async read(p: Uint8Array): Promise<number | null> {
        await new Promise(resolve => setTimeout(resolve, 1000))
        p.set([120])
        return 1
    }
  } });
}
```

Assuming you make an HTTP request in the first 5s, the connection will be closed immediately after close is called, but the loop will "notice" this a decade later, when the buffer fills and a write fails.

I _think_ `Server` should be tracking `ServerRequests`, not only their `Conn`'s, and on `server.close()` also fulfill `req.done` with a "server closed" error.

**Comment by bartlomieju** [comment]
`std/http` implementation was rewritten to leverage native HTTP bindings available in Deno (`Deno.serveHttp`). This error should no longer occur. I'm going to tentatively close this issue, please let me know if the problem persists.
