### ISSUE TITLE
make deno bytes example code work in browser

### ISSUE THREAD

**Issue by ry** [denoland/deno_std#1090]
This example code:
```ts
import { findLastIndex } from "https://deno.land/std/bytes/mod.ts";

console.log(findLastIndex(
  new Uint8Array([0, 1, 2, 0, 1, 2, 0, 1, 3]),
  new Uint8Array([0, 1, 2])
));
```
ought to be usable in the browser. 

- [ ] We need deno.land to support automatic type-stripping https://deno.land/std/bytes/mod.ts -> https://deno.land/std/bytes/mod.js https://github.com/denoland/deno_website2/issues/356
- [ ] mime type for https://deno.land/std/bytes/mod.js needs to be application/javascript https://github.com/denoland/deno_website2/issues/358

**Comment by axetroy** [comment]
But the browser does not support Typescript

Either do a browser's Typescript runtime, then compile typescript to javascript

So I think the lower cost is compiled, not a runtime

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <link rel="icon" href="/favicon.ico" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Example</title>
    <div id="app"></div>
    <script type="module">
      import { findLastIndex } from "https://deno.land/std/bytes/mod.ts?js";

      console.log(findLastIndex(
        new Uint8Array([0, 1, 2, 0, 1, 2, 0, 1, 3]),
        new Uint8Array([0, 1, 2])
      ));
    </script>
  </body>
</html>
```

add the flag `?js` to the URL to tell the server, compile to javascript then response back to browser

or server checkout the `User-Agent` header, detect wheather the client is Browser, Then decide whether to return javascript or typescript

**Comment by UltiRequiem** [comment]
> add the flag `?js` to the URL to tell the server, compile to javascript then response back to browser

This sounds nice, any update?

**Comment by crowlKats** [comment]
@UltiRequiem https://github.com/denoland/dotland/pull/1902

**Comment by iuioiua** [comment]
@kt3k, serving files using the `?js` flag isn't yet supported, according to [https://github.com/denoland/dotland/pull/1902](https://github.com/denoland/dotland/pull/1902). However, technically, [this module is browser compatible](https://github.com/denoland/deno_std/blob/d7cd0080b8aa8a2df315edb220f919f4b88c4086/bytes/mod.ts#L2), so this issue might be able to be closed.

**Comment by kt3k** [comment]
Right, dynamic ts-js compilation is tracked in https://github.com/denoland/dotland/pull/1902. This can be closed as a std issue.

**Comment by mreinstein** [comment]
> dynamic ts->js compilation is tracked in https://github.com/denoland/dotland/pull/1902.

So said differently 1902 is a duplicate of this issue (1090) right?

**Comment by kt3k** [comment]
@mreinstein 
This is earlier one, but there's nothing actionable in this repo (deno_std) because `bytes` module seems already browser compatible.

If you're interested in this topic further, please subscribe https://github.com/denoland/dotland/issues/1728 or https://github.com/denoland/dotland/pull/1902 (These issues are in dotland repo, where ts->js compilation is more relevant.

**Comment by mreinstein** [comment]
> bytes module seems already browser compatible

Maybe I just don't understand @ry intent when he filed this ticket but I understood it to mean "it should be possible to import https://deno.land/std/bytes/mod.ts in a browser". The fact that the module itself _should_ work in a browser but can't actually be requested and used...that isn't solving the actual purpose of this ticket.
