### ISSUE TITLE
std/log buffer cut lines

### ISSUE THREAD

**Issue by dgpgdev** [denoland/deno_std#1093]
Hi, I don't know if this is the correct behavior, but the log line is cut because the buffer size exceeds as you can see below.
```
{"ts":"2021-06-25T08:36:39.648Z","level":"ERROR","data":"{\"error\":true,\"msg\":\"error\"}"}
{"ts":"2021-06-25T08:36:40.147Z","level":"ERROR","data":"{\"error\":true,\"msg\":\"error\"}"}
{"ts":"2021-06-25T08:36:40.647Z","level":"ERROR","data
```
And when the buffer is full again here is the result. Previous line not completed and the new lines append.
```
{"ts":"2021-06-25T08:18:02.857Z","level":"ERROR","data":"{\"error\":true,\{"ts":"2021-06-25T08:18:17.500Z","level":"ERROR","data":"{\"error\":true,\"msg\":\"error0\"}"}
```

Deno code 
```ts
await log.setup({
  handlers: {
    console: new log.handlers.ConsoleHandler('INFO'),
    file: new log.handlers.RotatingFileHandler('INFO', {
      filename: `./logs/log.log`,
      maxBytes: 5 * 1024 * 1024,
      maxBackupCount: 5,
      formatter: rec => JSON.stringify({ ts: rec.datetime, level: rec.levelName, data: rec.msg }),
    }),
  },
  loggers: {
    default: {
      level: 'INFO',
      handlers: ['console', 'file'],
    },
  },
})

const Logger = log.getLogger()

setInterval(() => Logger.error({ error: true, msg: 'error' }), 500)

```

**Comment by lmx-Hexagram** [comment]
Hello, I am working on this issue and now I can't reproduction this issue.
I use the code provide by @dgpgdev and tried with std version `80, 117, 119`, but nothing special happened.
Also I read the source code of `std/log` and `std/io/buffer`, I don't think this issue will happen. 

So can @dgpgdev  provide deeper information about this issue? Or I will think this issue need to be closed.

**Comment by dgpgdev** [comment]
hi, still the same behavior with std@0.119.0
 as you can see here [screen](https://imgur.com/a/8J3Ptkp) after restart process the last line was cutted and the next line append

**Comment by lmx-Hexagram** [comment]
Do you cancel progress via ctrl+c？

**Comment by lmx-Hexagram** [comment]
> hi, still the same behavior with std@0.119.0
> as you can see here [screen](https://imgur.com/a/8J3Ptkp) after restart process the last line was cutted and the next line append

ok, I success reproduct this issue. I am working on it.
