### ISSUE TITLE
feat(collections/sortBy): make the `sortBy()` of Date a stable sort

### ISSUE THREAD

**Issue by ayame113** [denoland/deno_std#1096]
**Is your feature request related to a problem? Please describe.**

`sortBy()` is not a stable sort only when sorting by date. (Because `new Date("April 1, 2021")!==new Date("April 1, 2021")`)

```ts
sortBy([
  { id: 1, date: "February 1, 2022" },
  { id: 2, date: "December 17, 1995" },
  { id: 3, date: "June 12, 2012" },
  { id: 4, date: "December 17, 1995" },
  { id: 5, date: "June 12, 2012" },
], (it) => new Date(it.date))

/*
current result:
[
  { id: 4, date: "December 17, 1995" },
  { id: 2, date: "December 17, 1995" },
  { id: 5, date: "June 12, 2012" },
  { id: 3, date: "June 12, 2012" },
  { id: 1, date: "February 1, 2022" },
]
*/
```

How about making the date sort a stable sort and documenting that `sortBy()` is a stable sort?

**Additional context**

It is documented that `Array.prototype.sort` is a stable sort.(https://github.com/tc39/ecma262/pull/1340)

edit: I opened a pull request. (https://github.com/denoland/deno_std/pull/1097)

**Comment by kt3k** [comment]
Right. I overlooked this aspect in #1091. Thanks for catching this.
