### ISSUE TITLE
The http server does not respect "connection: close" and "connection: keep-alive" in headers

### ISSUE THREAD

**Issue by deepu105** [denoland/deno_std#1112]
The HTTP server does not seem to respect `Connection` settings in header. Try the below for example code with apachebench

```
import {
  listenAndServe,
  ServerRequest,
} from "https://deno.land/std/http/server.ts";

let count = 0;

listenAndServe(
  { hostname: "0.0.0.0", port: 8080 },
  async (req: ServerRequest) => {
    count++;
    // add 2 second delay to every 10th request
    if (count % 10 === 0) {
      console.log("Adding delay. Count: ", count);
      await sleep(2000);
    }
    // read html file
    const body = await Deno.readTextFile("./hello.html"); // use any HTML file
    const res = {
      status: 200,
      body,
      headers: new Headers(),
    };
    res.headers.set("Connection", "keep-alive");
    req.respond(res);
  }
);

function sleep(ms: number) {
  return new Promise((resolve) => {
    setTimeout(resolve, ms);
  });
}
```

Now run `ab -c 100 -n 10000 http://127.0.0.1:8080/` and it will fail, whereas `ab -k -c 100 -n 10000 http://127.0.0.1:8080/` works. So seems like `keep-alive` in the header is not respected. Similar code works fine in NodeJS without having to explicitly set `-k` flag in Apachebench request

Similar issue was closed for being stale earlier denoland/deno#5355 5355

**Comment by bartlomieju** [comment]
I'm going to tentatively close this issue since `http` module migrated to using native HTTP bindings with `Deno.serveHttp()` API and the problem should no longer manifest itself.
