### ISSUE TITLE
addr defaults to "0.0.0.0"

### ISSUE THREAD

**Issue by nhrones** [denoland/deno_std#1165]
**Describe the bug** 
In server.ts, the function serve() unconditionally returns addr "0.0.0.0"
This is incorrect for Windows and shows up in many Deno code examples and libs.

**Expected behavior** 
Should return "127.0.0.1" on Windows

OS: Windows 10

**Additional context** 

deno_std/http/server.ts  line# 265
```js
export function _parseAddrFromStr(addr: string): HTTPOptions {
  let url: URL;
  try {
    //HACK add this line to return a correct default addr
    const defaultAddr = (Deno.build.os === "windows") ? "127.0.0.1" : "0.0.0.0";
    const host = addr.startsWith(":") ? `${defaultAddr}${addr}` : addr;
    url = new URL(`http://${host}`);
  }
```

**Comment by cmorten** [comment]
Guessing this was written following precedent set by Node (REF: https://github.com/nodejs/node/blob/master/lib/net.js#L126, https://nodejs.org/docs/latest-v10.x/api/net.html#net_server_listen_port_host_backlog_callback) and golang (_I_ believe this is what golang is doing, but find tracing through the stack of the net package tough going - happy to be corrected!)?

Be curious to know why the meta-address was chosen over the loopback address given windows caveats?

For consistency I wonder if opting for loopback only on windows, and all network interfaces otherwise is a good choice? Would it be better to use the same default across all OS (whichever default _is_ chosen).

**Comment by nhrones** [comment]
@cmorten  I was under the impression that RY had a reason to default to '0.0.0.0' . That is why I suggested conditioning default based on build.os.   Also thanks for all the work on sever.ts.

**Comment by cmorten** [comment]
Doesn’t seem to be much history to it - REF: https://github.com/denoland/deno/pull/6698.

Not a windows user - is the issue that serving from `0.0.0.0` doesn’t work at all, or that requesting the `0.0.0.0` meta-address from a client doesn’t resolve, but if hit `localhost` or `127.0.0.1` in the request it still works?

**Comment by MyIsaak** [comment]
Hi guys. I've submitted a PR fixing this issue here: https://github.com/denoland/deno_std/pull/1178

**Comment by nhrones** [comment]
@cmorten  requesting the 0.0.0.0 meta-address from a Windows client doesn’t resolve. but, if hit localhost or 127.0.0.1 in the request it still works.  This is a source of confusion for many new Deno users on Windows as many libs and examples console.log('server running on http://0.0.0.0:8080').  Console messages with an address can be 'ctrl+clicked'  to run the example, but 0.0.0.0 will error in Windows 'ERR_ADDRESS_INVALID'

**Comment by cmorten** [comment]
Ok so `0.0.0.0` is working as intended on windows, it is more of an education piece / user error, accentuated by log statements which folks are inclined to copy and paste leading to confusion?

I would be more inclined to either:

1. Leave as-is but improve documentation + encourage userland authors to log statements aimed at entry level users (e.g. swap out `0.0.0.0` for `localhost`).
2. Move all OS to loopback on `127.0.0.1` and if folks want to listen to all net interfaces they can manually pass `0.0.0.0` as the host in the address argument - again probably adding documentation to explain this to users.

Problem with (1) is that can foresee folks not reading docs, and expecting _all_ framework authors to make life easier is unreasonable. If the feel is that what most people want and expect _is_ `localhost` for the default, then perhaps it should be that for everyone.

The issue of having something different for windows vs all other OS is yet another gotcha that you have to be careful to document. I suspect most folks would expect their Deno server framework of choice / compiled Deno app to work the same no matter the OS (though perhaps a tall ask!) - and having the proposed half and half wouldn’t be that, for windows it would _only_ be listening on `localhost` and elsewhere on all network interfaces, including _but not limited to_ `localhost`…

**Comment by nhrones** [comment]
@cmorten This was my original view, but I was informed that this was discussed in the past, and a top level consensus was to use '0.0.0.0' instead of loopback '127.0.0.1'.  I don't know the reason, but Ryan was involved in choice?

**Comment by cmorten** [comment]
Related:
- https://github.com/denoland/deno/issues/11424
- https://github.com/denoland/deno/issues/10762#issuecomment-851392906
- https://github.com/denoland/deno/issues/5144
- https://github.com/denoland/deno/pull/5203

I believe the bottom two are likely the discussion + PR involving @ry that you are referring to? Given this has already had some thought on it, I wonder if it really does need changing?

The fact that it has arisen again _is_ likely an indicator that we need better documentation for users.

**Comment by MyIsaak** [comment]
> Ok so 0.0.0.0 is working as intended on windows, it is more of an education piece / user error, accentuated by log statements which folks are inclined to copy and paste leading to confusion?

0.0.0.0 **does not work** on Windows. At least not for me. Only with the workaround I presented in the PR will it work.

**Comment by cmorten** [comment]
@MyIsaak ah, getting muddled then… so serving from `0.0.0.0` and then requesting `127.0.0.1` isn’t working on windows?

**Comment by MyIsaak** [comment]
That should work, but requesting `0.0.0.0` from a browser doesn't work in Windows, whereas on Mac and Linux it does. If we were to follow the spec [RFC5435](https://datatracker.ietf.org/doc/html/rfc5735#section-3), a request to `0.0.0.0` should normally go to `127.0.0.1`, however Windows has a different opinion and doesn't resolve it.

But let's steer away from the spec and think about it in practical terms. When a developer binds to 8080 without specifying the hostname, the obvious default is the his machine (i.e. `127.0.0.1`) or?

Therefore just replacing `0.0.0.0` with `127.0.0.1` like you mentioned in (2) to me sounds like a good idea.

**Comment by kt3k** [comment]
I agree with Craig. This looks like a problem of the logged message of the server program, and not a problem of actual bound address.

I think we shouldn't change the default binding address as this decision was intentional. ref: https://github.com/denoland/deno/issues/5144

**Comment by nhrones** [comment]
@kt3k I would agree that the problem is actually the logged messages in many downstream apps/libs.  I've recently seen many of them corrected to log 'http://localhost:xxxx'.  Perhaps a lint to suggest localhost this would help.
Since I opened this issue, should I close it here?

**Comment by treysis** [comment]
Keep in mind that on many systems, including Windows, `localhost` also resolves to `::1`. Right now, I only know of Ubuntu that doesn't resolve localhost to ::1, but instead uses `ip6-localhost`.
