### ISSUE TITLE
[Umbrella] `collections` APIs

### ISSUE THREAD

**Issue by LionC** [denoland/deno_std#1173]
# `collections`

This is an umbrella issue for the `collections` module, which has landed in `std` with [this initial PR](https://github.com/denoland/deno_std/pull/993) and a lot of new contributions since. The goal of this issue is to give an overview about functions that have alreayd been implemented, are being worked on and have not been started yet.

For more details on the idea behind the module, check out its [Readme](https://github.com/denoland/deno_std/blob/main/collections/README.md) and [contribution guide](https://github.com/denoland/deno_std/blob/main/collections/CONTRIBUTING.md). For more details on the history of the module and its proposed signatures, see [the original proposal PR](https://github.com/denoland/deno_std/pull/978).

**If you want to implement one of the missing functions, please open a separate PR** for it and keep discussion in that PR. Please read the [contribution guide](https://github.com/denoland/deno_std/blob/main/collections/CONTRIBUTING.md) and make sure to keep the checklist in mind before opening your PR / marking it ready for review.

If you want to add onto or discuss the list, please do that here.

## Unstarted / Suggestions

None right now

## In Progress

* [ ] aggregateGroups #1553 
* ~filterNotNullish~ #1168
* ~filterValuesNotNullish~ #1186 
* ~without~ #1074

## Done

* [x]  associateBy #1071 
* [x]  associateWith #1213 
* [x]  chunk #993 
* [x]  deepMerge #1075 
* [x]  distinct #993
* [x]  distinctBy #993
* [x]  dropLastWhile #1193 
* [x]  dropWhile #1185 
* [x]  filterEntries #993
* [x]  filterKeys #993
* [x]  filterValues #993
* [x]  findLast #993
* [x]  findLastIndex #1062 
* [x]  firstNotNullishOf #1167
* [x]  groupBy #993
* [x]  includesValue #1184 
* [x]  intersect #993
* [x]  joinToString #1223 
* [x]  mapEntries #993
* [x]  mapKeys #993
* [x]  mapNotNullish #1103 
* [x]  mapValues #993
* [x]  maxBy #1156 
* [x]  maxOf #1144 
* [x]  maxWith #1170 
* [x]  minBy #1157 
* [x]  minOf #1164  
* [x]  minWith #1169 
* [x]  partition #993
* [x]  permutations #993
* [x]  reduceGroups #1187 
* [x]  runningReduce #1226 
* [x]  sample #1212 
* [x]  single #1166 
* [x]  sortBy #1069
* [x]  sumOf #1108 
* [x]  takeLastWhile #1179 
* [x]  takeWhile #1175 
* [x]  union #993
* [x]  unzip #993
* [x]  windowed #1191 
* [x]  withoutAll #1100 
* [x]  zip [initial PR](https://github.com/denoland/deno_std/pull/993)

**Comment by kt3k** [comment]
Note: we sometimes drop the items from proposal when the implementation is too trivial.

This Luca's comment describes the reasoning behind it well.
https://github.com/denoland/deno_std/pull/1168#pullrequestreview-740705017

**Comment by LionC** [comment]
> Note: we sometimes drop the items from proposal when the implementation is too trivial.
> 
> This Luca's comment describes the reasoning behind it well.
> [#1168 (review)](https://github.com/denoland/deno_std/pull/1168#pullrequestreview-740705017)

Yes, I will continue to keep them in the list ~striked out~ as seen above.

**Comment by LionC** [comment]
As we approach being pretty much API complete compared to the Kotlin package that inspired this (and removing the ones that we have deemed not fitting for JS right now), I would like to propose **three last functions** to complete the modules API for now. All three are taken mostly directly from `kotlin/std/collections` and `lodash`.

Comments welcome, I will add them to the list above soon :-)

## `associateWith`

```ts
/**
* Builds a new Record using the given array as keys and choosing a value for each
* key using the given selector.
*/
export function associateWith<T>(array: readonly string[], selector: (key: string) => T): Record<string, T>
```

Missing sister function to the already implemented `associateBy`, used if you have an array of keys that you need to transform to a record.

## `joinToString`

```ts
export type JoinToStringOptions = { separator?: string, prefix?: string, suffix?: string }
/**
* Transforms the elements in the given array to strings using the given selector. Joins
* the produced strings into one using the given separator and applying the given prefix
* and suffix to the whole string afterwards. Returns the resulting string.
*/
export function joinToString<T>(
    array: readonly T[],
    selector: (el: T) => string,
    {
        separator = ", ",
        prefix = "",
        suffix = "",
    }: JoinToStringOptions = {},
): string
```

This is straight up a more efficient version of use cases around `.map().join()` chains (and some postprocessing). I talked briefly about this on Discord before and some though it to bee too specific, but in my experience this happens quite a lot (`.join()` follows `.map()` more often than not in boring business applications) and we even have four `.map().join()` calls in non-test code in `std` itself (in `std/http` among others).

This also adds convenience to the process by allowing for an optional prefix or suffix. Kotlin also adds the option to truncate by only iterating an optional set number of elements before stopping and adding an optional truncation string. Seemed specific to me, but they also reject things they think to be too narrow, so I am unsure. Input would be welcome.

## `sample`

```ts
/**
* Selects an element randomly from the given array and returns it.
*/
export function sample<T>(array: readonly T[]): T | undefined
```

Useful for all kinds of random cases like random quotes, websites, task distribution logic etc. Even though we have an (in-place) shuffle function in JS, there is no way to just get a random element. Shuffling to get one is really inefficient and the probably correct way to do it with `Math.random` is something people need to look up and get wrong with off-by-one errors all the time.

**Comment by LionC** [comment]
I added the above function to the list and will shamelessly ping the recent contributors, maybe someone wants do implement one of them :-) CC @grian32 @majidsajadi @ayame113 @getspooky

**Comment by getspooky** [comment]
@LionC good , i will look into `associateWith` function.

**Comment by majidsajadi** [comment]
so I take `sample` and `joinToString`.  @LionC @getspooky

**Comment by getspooky** [comment]
@LionC can you please confirm this example: 
```ts
const users = [
   { id: 'a2e', userName: 'Anna' },
   { id: '5f8', userName: 'Arnold' },
   { id: 'd2c', userName: 'Kim' },
]
const usersByLength = associateWith(users, it => it.userName.length)
assertEquals(usersById, {
  '4': { id: 'a2e', userName: 'Anna' },
  '6': { id: '5f8', userName: 'Arnold' },
  '3': { id: 'd2c', userName: 'Kim' },
})
```

**Comment by LionC** [comment]
> @LionC can you please confirm this example:
> 
> ```ts
> const users = [
>    { id: 'a2e', userName: 'Anna' },
>    { id: '5f8', userName: 'Arnold' },
>    { id: 'd2c', userName: 'Kim' },
> ]
> const usersByLength = associateWith(users, it => it.userName.length)
> assertEquals(usersByLength, {
>   '4': { id: 'a2e', userName: 'Anna' },
>   '6': { id: '5f8', userName: 'Arnold' },
>   '3': { id: 'd2c', userName: 'Kim' },
> })
> ```

That is `associateBy` - we already have that in the module :-)

A correct example would be:

```ts
const names = [ 'Kim', 'Lara', 'Jonathan' ]
const namesToLength = associateWith(names, it => it.length)

assertEquals(namesToLength, {
    'Kim': 3,
    'Lara': 4,
    'Jonathan': 8,
})
```

**Comment by bartlomieju** [comment]
@LionC great work on seeing this proposal through in full! Also thanks to @getspooky, @majidsajadi, @grian32, @ayame113 and other contributors for help implementing all the APIs. This module is a very valuable addition to the standard library!
