### ISSUE TITLE
Make CI Tests not run if `lint` or `_wasm_crypto/` doesnt pass

### ISSUE THREAD

**Issue by grian32** [denoland/deno_std#1180]
Doesn't make much sense to run the tests if `lint` or `_wasm_crypto/` doesn't pass because those are the shortest CI tasks other than CLA  and you cant merge unless CI is passing.

**Comment by bartlomieju** [comment]
If either of those steps fails the rest are cancelled automatically. 

Your suggestion would make CI script more complicated and would actually increase CI runtime if everything passes, I'm happy with how CI works now so let's keep it simple.

**Comment by grian32** [comment]
> If either of those steps fails the rest are cancelled automatically.
> 
> Your suggestion would make CI script more complicated and would actually increase CI runtime if everything passes, I'm happy with how CI works now so let's keep it simple.

That's fair enough, thanks for the response.
