### ISSUE TITLE
suggestion: use primordials

### ISSUE THREAD

**Issue by cmorten** [denoland/deno_std#1217]
**Is your feature request related to a problem? Please describe.** A clear and
concise description of what the problem is.

The std lib currently (mostly) uses builtin globals straight from the environment. This means that they are vulnerable to overwrites which can cause unexpected behaviours / security issues.

REF:
- https://github.com/denoland/deno/issues/6040
- https://github.com/denoland/deno/pull/6552

**Describe the solution you'd like** A clear and concise description of what you
want to happen.

Following precedent set in Node's std library and Deno core, consider introduce a primordials module to std which can be used, either through import or as a global.

REF:
- https://github.com/nodejs/node/blob/master/lib/internal/per_context/primordials.js
- https://github.com/nodejs/node/blob/master/typings/primordials.d.ts
- https://github.com/denoland/deno/blob/main/core/00_primordials.js

**Describe alternatives you've considered** A clear and concise description of
any alternative solutions or features you've considered.

- Not using primordials - subject to issues stated above
- "Localised" primordials - each module handcrafts handling of globals it needs rather than from a centralised place

**Additional context** Add any other context or screenshots about the feature
request here.

REF:
- https://github.com/denoland/deno/issues/7407
- https://github.com/denoland/deno/issues/10756
- https://github.com/denoland/deno/issues/11224

**Comment by nayeemrmn** [comment]
-1. As I've said in other contexts I think std should be treated as a model user space library. Since it is technically in user space (not built-in unlike Node std), it makes for a good opportunity to have something like that. So IMO we shouldn't do it in std unless we think any serious userland project should.

**Comment by bartlomieju** [comment]
I agree with Nayeem. Other factor is that "primordials" are not public code, and we definitely don't want to expose it in any way.

**Comment by cmorten** [comment]
Cool thanks both for opinions! Seen references in code saying that maybe we should, but no issue (that I could find) to that effect!

This can stand as a reference for anyone else that is curious to this end 😄

Closing as “won’t do” given above justification.
