### ISSUE TITLE
Testing module compatibility

### ISSUE THREAD

**Issue by 43081j** [denoland/deno_std#122]
At the minute we don't really seem to follow node's assertion interfaces or anyone else's.

Is there any reference as to what convention was followed or was it thought up just for deno?

It may be worth rewriting the testing module to adhere to node's assertion module and be entirely compatible.

Basically current implementation:

```ts
assertEqual(actual, expected, msg);
assert(equal(actual, expected), msg);
```

Node implementation:

```ts
assert.equal(actual, expected, msg);
```

So:
* `assertEqual` doesn't seem to be needed, only for setting a nice message (deepEqual and equal would do this themselves)
* `equal` does a deep equality check for us but in node does an `Object.is` alone (as `deepEqual` exists for the former)
* An `AssertionError` is thrown rather than an `Error` in node
* Negated functions exist in node such as `notEqual`

**Comment by kitsonk** [comment]
Personally I would rather take queues from [Chai assert](https://www.chaijs.com/api/assert/) personally.

The behaviour of `assertEqual()` and `equal()` is already established, both in all of `std` but also the core of Deno.  There is a lot of tests that depend upon that deep comparison behaviour.

I don't think we should be pedantic about following anyone else's behaviour.  We can take queues and patterns from others.  The benefit of TypeScript and JSDoc is that the APIs can be self documenting if there is any confusion.

**Comment by 43081j** [comment]
I don't think it is about being pedantic and following other behaviours for that reason, but rather that these implementations are well established and known. Any difference in behaviour will lead to confusion as nobody is starting 'new' with deno, they will have used one of the widely used assertion libraries beforehand.

`equal` really shouldn't do a deep equality check and restricting it to that just because it would mean many changes seems a little unfortunate/backwards. It would be worth the effort to have a clean API.

Even if we take chai as an example to work from, it too has different behaviour and is closer to what node implements.

The lack of an assertion exception is a huge one, too, as you can already see repetition in the recent PR for 'error logging'. There should be one source of assertion messages which we can keep very clean.

I think all i listed still applies even if you follow chai, other than the naming convention and strictness.

**Comment by 43081j** [comment]
The reason for `equal` being simple (value equality check, usually) is that we can then have a `deepEqual` for when we want recursive equality checks. Leaving `equal` to do a deep check seems fine as long as we then have a `strictEqual` or similar, for when we _don't_ want deep equality (which would be `Object.is` pretty much).

I agree with your `rejects` idea, too, but it could be argued that both should be supported in that case. If dealing with promises directly, it sounds logical to have `rejects` and `resolves`, but if dealing with async functions, it sounds logical to have `throwsAsync` and `returnsAsync`. Really depends on what context you're in.

Anyhow, i'm happy to open a few issues separately about these things but the idea of this issue in particular was to identify what those are.
