### ISSUE TITLE
[collections] Make browser-compatible

### ISSUE THREAD

**Issue by jsejcksn** [denoland/deno_std#1273]
I just cloned the `main` branch of this repo and did a quick grep for `Deno` in the `collections` directory: I didn't see any results that weren't copyright comments or references to `Deno.test` in tests.

Is there any reason why the modules in /collections can't be made to be [browser compatible](https://deno.land/manual/contributing/style_guide#document-and-maintain-browser-compatibility)?

/cc @LionC

**Comment by LionC** [comment]
Hey. The module is browser compatible, just not marked yet. I did not know that this is a thing when I started and didnt find the time to do it afterwards yet :-)

So you are absolutely right!

**Comment by majidsajadi** [comment]
@LionC I can send a PR to fix this.

**Comment by jsejcksn** [comment]
@majidsajadi Go for it; I haven't started working on it yet.

**Comment by kt3k** [comment]
addressed by #1285
