### ISSUE TITLE
Proposal: Add `deno.config.ts` for custom advanced behavior of Deno

### ISSUE THREAD

**Issue by getspooky** [denoland/deno_std#1281]
For custom advanced behavior of `Deno`, you can create a `deno.config.ts` in the root of your project directory.
This file will allow us to :
- Add environment variables
- Set custom HTTP headers for an incoming request path
- Disabling ETag generation
- Disabling x-powered-by
- Disabling HTTP Keep-Alive

**Comment by lucacasonato** [comment]
Deno does not do the above (no etag generation, no x-powered-by).
