### ISSUE TITLE
http/cookie Docs Are Incorrect

### ISSUE THREAD

**Issue by ebebbington** [denoland/deno_std#1291]
**Describe the bug**

https://deno.land/std@0.107.0/http#setcookie and delCookie

In the readme, it mentions `setCookie(headers, cookie)`, but the method may have changed recently as the actual signature is `setCookie({ headers?: Headers }, cookie: Cookie)`, eg `setCookie({ headers: new Headers() }, cookie)`

This also applies to delCookie

**To Reproduce**

1. Follow the example in the readme

**Expected behavior**

The code in the readme should work

**Desktop**

- OS: Windows
- Version 10

```
deno 1.14.0 (release, x86_64-pc-windows-msvc)
v8 9.4.146.15
typescript 4.4.2
```

**Additional context** Add any other context about the problem here.

**Comment by satyarohith** [comment]
@ebebbington, the signature didn’t change as per https://deno.land/std@0.107.0/http/cookie.ts#L191

And the example in the readme is working as expected for me. Can you paste the error you're encountering?
```ts
import {
  Cookie,
  setCookie,
} from "https://deno.land/std@0.107.0/http/cookie.ts";

const headers = new Headers();
const cookie: Cookie = { name: "Space", value: "Cat" };
setCookie(headers, cookie);

const cookieHeader = headers.get("set-cookie");
console.log(cookieHeader); // Space=Cat
```

**Comment by ebebbington** [comment]
Nevermind, i was using std 0.101.0, but sure i was using the latest, apologies and closing as resolved
