### ISSUE TITLE
Make std/ws compatible with std/http

### ISSUE THREAD

**Issue by talentlessguy** [denoland/deno_std#1294]
**Is your feature request related to a problem? Please describe.**

At the moment `std/ws` relies on legacy `std/http` which doesn't use native HTTP API and therefore is incompatible with the new `std/http` API (request object doesn't have buf readers and writers as `ServerRequest` does)

**Describe the solution you'd like**

Adjust `std/ws` to work with the latest `std/http` API

**Describe alternatives you've considered**

There are none at the moment

**Additional context** 

https://github.com/timonson/gentle_rpc/issues/9

**Comment by crowlKats** [comment]
> Adjust `std/ws` to work with the latest `std/http` API

`std/ws` is an own implementation of the websocket spec. we most definitively should not keep it around for various obvious reasons, and as planned when native ws server was being worked on, should be removed (#1292)

**Comment by talentlessguy** [comment]
oh alright.. closing then
