### ISSUE TITLE
std/fs: `walk` not found error is not `Deno.errors.NotFound`

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno_std#1310]
If you pass a path to `walk` that does not exist on the fs, the returned promise rejects with an `Error`, not a `Deno.errors.NotFound`.

**Comment by getspooky** [comment]
I tried to reproduce the bug but it return `Deno.errors.NotFound`
```ts
import { walk } from "https://deno.land/std@0.108.0/fs/mod.ts";

try {
  for await (const entry of walk("./deno")) {
    console.log(entry.path);
  }
} catch (error) {
  console.log(error instanceof Deno.errors.NotFound);
}
```
The result: 
```
true
```

My configuration: 
```
deno 1.14.0 (release, x86_64-unknown-linux-gnu)
v8 9.4.146.15
typescript 4.4.2
```

**Comment by iuioiua** [comment]
I got the same as @getspooky. Is this still an issue?

**Comment by kt3k** [comment]
Seems like not an issue. Let's close

**Comment by mikeatbuilder** [comment]
@lucacasonato @kt3k there's a related TODO in the fresh code here just FYI:
https://github.com/denoland/fresh/blob/b12867a5823a338b318b14f1b6e399e61064dce9/src/server/context.ts#L249

**Comment by kt3k** [comment]
@mikeatbuilder Thanks for the input. Sounds interesting. I think we should try to remove that workaround in fresh as this was a non issue

**Comment by lucacasonato** [comment]
@kt3k Have you tried on Linux. This may be fine on macOS, but it's still broken on Linux.

**Comment by kt3k** [comment]
Ok. I'll take a look

**Comment by kt3k** [comment]
It still seems NotFound in ubuntu

```shellsession
ubuntu@ip-172-31-255-98:~$ ls
main.js
ubuntu@ip-172-31-255-98:~$ cat main.js 
import { walk } from "https://deno.land/std@0.153.0/fs/mod.ts";

try {
  for await (const entry of walk("./deno")) {
    console.log(entry.path);
  }
} catch (error) {
  console.log(error instanceof Deno.errors.NotFound);
}

ubuntu@ip-172-31-255-98:~$ deno -V
deno 1.25.0
ubuntu@ip-172-31-255-98:~$ deno run -A main.js 
true
ubuntu@ip-172-31-255-98:~$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04 LTS"
```

**Comment by kt3k** [comment]
If I put a file of the same name of walk entrypoint, then I get `Error: Not a directory (os error 20), readdir './deno'`. This might be the actual problem in the above line in fresh?

**Comment by iuioiua** [comment]
Is this still an issue on Linux?

**Comment by ayame113** [comment]
#3054 changed the types of errors thrown. This problem may no longer exist?
(And I feel like https://github.com/denoland/fresh/pull/1078 can be merged.)

**Comment by iuioiua** [comment]
https://github.com/denoland/fresh/pull/1078 is failing on all platforms. The PR only removes the workaround that pertains to this issue.
