### ISSUE TITLE
std/node/process: Implement process events

### ISSUE THREAD

**Issue by talentlessguy** [denoland/deno_std#1313]
Related: #1312

**Is your feature request related to a problem? Please describe.**

When trying to import solc-bin WASM bindings I get an "Not Implemented" error that comes from `process.on`.

**Describe the solution you'd like**

Would be cool for Deno if process events were implemented so lots of Node.js and WASM libraries will work.

**Describe alternatives you've considered**

```ts
import process from 'https://esm.sh/process/browser.js'

// @ts-ignore
globalThis.process = process
```

**Additional context** Add any other context or screenshots about the feature
request here.

https://github.com/ethereum/solc-bin

**Comment by bartlomieju** [comment]
This is already shimmed; not all events are supported but the API no longer throws an error. I'm going to close this issue, please open a new one if you encounter a concrete problem with the `process.on`.
