### ISSUE TITLE
Tracking unstable APIs used in std

### ISSUE THREAD

**Issue by kt3k** [denoland/deno_std#1316]
std/node
- Deno.utime
- Deno.utimeSync
- Deno.futime
- Deno.futimeSync
- Deno.consoleSize
- Deno.systemMemoryInfo
- Deno.loadavg
- Deno.osRelease

std/signal
- Deno.Signal
- Deno.signal
- Deno.kill (test)

**Comment by bartlomieju** [comment]
@kt3k is this issue in any way actionable? It seems to already be stale due to changes in `Deno.Signal` and `Deno.kill` APIs.

**Comment by kt3k** [comment]
Right, this isn't very much actionable. Closing
