### ISSUE TITLE
Do not use Deno.env.get with `=${resolvedDevice}` in path/win32.ts

### ISSUE THREAD

**Issue by dsherret** [denoland/deno_std#1341]
The code is doing the following (which throws an error because Deno doesn't allow `=` in env var names):

https://github.com/denoland/deno_std/blob/9436e51cf6d3c60b53329bb97efc1046f5436d83/path/win32.ts#L57

But we shouldn't do this because it doesn't work in powershell. For example, where this "works" in node, in command prompt:

```batch
C:\Users\david>node -e "console.log(process.env['=C:']);"
C:\Users\david
```

But then in powershell:

```powershell
>node -e "console.log(process.env['=C:']);"
undefined
```

This is because `=C:` is specific to command prompt (cmd.exe). Read more: https://devblogs.microsoft.com/oldnewthing/20100506-00/?p=14133

Relates to https://github.com/denoland/deno/issues/12305

Edit: well, looks like either backticks within backticks doesn't work in github issues titles or I don't know what I'm doing.

**Comment by kt3k** [comment]
That technique (`process.env['=C:']`) seems to have started from this commit in Node.js https://github.com/nodejs/node/commit/d91bc7cb0977b058750183199906590d95003fc0

cc @piscisaureus
Do you know the better way to do this?

**Comment by kt3k** [comment]
After reading the above article carefully

> Win32 does not have the concept of a separate current directory for each drive, but the command processor wanted to preserve the old MS-DOS behavior because people were accustomed to it (and batch files relied upon it). The solution was to store this “per-drive current directory” in the environment, using a weird-o environment variable name so it wouldn’t conflict with normal environment variables.

Per-drive cwd doesn't seem a proper OS concept. So I guess the fix might be just deleting `Deno.env.get('=${resolvedDevice}')` from std?

**Comment by guybedford** [comment]
I'm brushing up against a similar issue to this in Node.js compat workflows in https://github.com/denoland/deno_std/issues/2665 that iterate the entire `process.env` where `=C:` is set.
