### ISSUE TITLE
Gauging interest for collections module

### ISSUE THREAD

**Issue by daniel-levin** [denoland/deno_std#135]
Hi all,

I am interested in implementing generic collections if there is a desire for it. Things like maps, sets, etc. Is this a goal for this library?

**Comment by keroxp** [comment]
@daniel-levin [Map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map) and [Set](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set) are available on `deno` global context. These are generically typed. Do you plan to implement another version of collections?

**Comment by hayd** [comment]
DefaultDict (Map), Counter, OrderedDict, Heapq, Deque seem useful.

Are there also useful prototypes that could be added to Map/Set?
