### ISSUE TITLE
std assertThrows is acting like assertThrowsError

### ISSUE THREAD

**Issue by mathiasrw** [denoland/deno_std#1362]
I just started building everything in Deno - even when node is the target (after a bundle and some creative imports). Absolutely love it. 

I found something that seems odd to me in std / assert. I would like to make a PR for it, but first I would like to hear if there is a (good) reason it is currently implemented like this. 

The `assertThrows` as described in `https://deno.land/manual/testing/assertions` is documented as if it asserts that "something" is being thrown. Yet 

```
Deno.test('Naming is hard',()=>{
	assertThrows(()=>{
		throw "msg"
	})
})
```

returns `AssertionError: A non-Error object was thrown.`. You will have to return a proper `Error` to get a pass

```
Deno.test('Naming is hard',()=>{
	assertThrows(()=>{
		throw Error("msg")
	})
})
````

On [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/throw) the throw statement is defined as

![image](https://user-images.githubusercontent.com/1063454/136461227-96de8336-db6e-41d2-8352-6fe24d3daa32.png)

It seems odd to *demand* a thrown exception is of a specific type (`Error`) when the name `assertThrows` indicates that it is testing **if** something is thrown. 

**I suggest that the current behaviour gets renamed to `assertThrowsError` and `assertThrows` is changed to disregard what type is thrown (also it's async sibling).** 

Let me know if there is some hidden knowledge or good reasons for the current behaviour. And if that is the case I'm happy to make a PR to the docs repo to explain it better to the next dev coming along this path of the world of Deno.  

I do understand that it is a breaking change, but better to sort out consistency early than carrying confusion into the future... right? If not, maybe a way forward would be to add `assertThrowsException` to verify that an exception _was_ thrown but disregard the type.

**Comment by kt3k** [comment]
I think it's ok to allow non-Error thing thrown from the function as it's allowed by the language.

I'm not sure we need `assertThrowsError`. We can assert that with the call `assertThrows(fn, Error)`.

> We assert that it's an error because it's ergonomic for the callback overload to be able to assume that:

Maybe we can check that only when errorCallback is specified, or we can change the errorCallback signature to `(e: unknown) => unknown`

**Comment by mathiasrw** [comment]
> We can assert that with the call assertThrows(fn, Error).

That is a much better solution. We should be able to provide null as second parameter so we can reach the 3rd parameter to set `msgIncludes`.

**Comment by kt3k** [comment]
@mathiasrw Have you initialized git-submodules?

```
git submodule update --init
```

**Comment by KyleJune** [comment]
> @KyleJune 
> > How about changing assertThrows and assertRejects to only assert that their was an exception thrown or rejected? If those functions were changed to take an optional expectation, these functions could be used for asserting specific exceptions or that their was an exception.
> 
> I'm in favor of this change
> 
> > Having it return the unknown exception would allow us to make additional assertions on the exception if they are more complex than a simple comparison.
> 
> We had discussion about this, and decided we don't make `assert` functions return values. ref: https://github.com/denoland/deno_std/pull/1219#issuecomment-916630738 ref: https://github.com/denoland/deno_std/pull/1052#discussion_r674510375
> 
> So I think we should keep the return type void here

In that case and for backwards compatibility, I think we should keep the current call signature so that their is a shorthand way to make assertions about exceptions being errors(common case), but if user provides a callback instead use it instead of assertError so that users can make their own assertions about the exception.

Currently when a callback is passed it asserts the exception is an error and optionally asserts that error has a msg before calling the callback. Since my suggestion is not doing error assertions when passing an assertion callback, I believe the last optional msg arg should be deprecated.

I believe assertError should be exposed for if users want to use the callback signature of assertThrows or assertRejects but still want to make the error assertions on it or on error.cause. I would also remove the optional callback signature from my current assertError implementation since the error would be a variable where it would be used.

**Comment by mathiasrw** [comment]
Ok. Jumping out of this. Would love to see the change, but not sure I can lift the adjustments mentioned.

**Comment by mathiasrw** [comment]
@KyleJune Ahh, got it. Ill keep an eye on your PR and have a go at this one after the PR has been merged.

**Comment by bartlomieju** [comment]
I think https://github.com/denoland/deno_std/pull/1376 solves the issue presented here in the limit. I'm going to close the issue for now, please feel free to comment if the solution is not satisfactory.

**Comment by kt3k** [comment]
I think this issue is still valid. From my understanding, what this issue suggests is removing the below 3 lines from `assertThrows`:

https://github.com/denoland/deno_std/blob/6212e9021f7533f106558721909315cf8639de0a/testing/asserts.ts#L682-L684
