### ISSUE TITLE
Add example of using fast-check in Deno.test()

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno_std#1368]
Similar to https://github.com/denoland/deno_std/blob/main/testing/sinon_example.ts and https://github.com/denoland/deno_std/blob/main/testing/chai_example.ts we should add an example of using [`fast-check`](https://github.com/dubzzz/fast-check) in tests

Reference: https://gist.github.com/cdoremus/52eb1b617ba3113ddf251904d2b05ddc

**Comment by standvpmnt** [comment]
@lucacasonato I have created a PR for this, please let me know if this serves the purpose here or let me know if any changes are required. PR #1413
