### ISSUE TITLE
`crypto.subtle.digest` when bundled for browser

### ISSUE THREAD

**Issue by roj1512** [denoland/deno_std#1371]
**Describe the bug**

`crypto.subtle.digest` can not be used from browser when bundled with `deno bundle`.

**Steps to Reproduce**

1. Create `mod.ts`:
```ts
import { crypto } from "https://deno.land/std@0.110.0/crypto/mod.ts";
crypto.subtle.digest("SHA-1", new TextEncoder().encode('data'));
```

2. `$ deno bundle mod.ts mod.js`

3. Create `index.html`;
```html
<script type="module" src="./mod.js"></script>
```

5. Start a server to serve `index.html`, open from a browser and see the console.

**Expected behavior**

Hmm, maybe it should work? :)

**Environment**

- OS: Pop!_OS 21.04
- deno version: 1.14.3
- std version: 0.110.0

**Comment by iuioiua** [comment]
Hi @roj1512, I just tried the following and it worked.
```ts
import { crypto } from "https://deno.land/std@0.152.0/crypto/mod.ts";
await crypto.subtle.digest("SHA-1", new TextEncoder().encode('data'));
```
Are you still experiencing this issue?

**Comment by roj1512** [comment]
Seems fine now. Thanks, @iuioiua!
