### ISSUE TITLE
`readLines` does not work for lines longer than 4095 bytes

### ISSUE THREAD

**Issue by masnagam** [denoland/deno_std#1373]
**Describe the bug**

`readLines` does not work for lines longer than 4095 bytes.

**Steps to Reproduce**

The following command works properly:

```sh
# `bash -c 'printf "=%.s" {0..4094}' | wc -c` shows 4095
bash -c 'printf "=%.s" {0..4094}' | deno run line_length.js  # shows 4095
```

However, the following command does not work properly:

```sh
# `bash -c 'printf "=%.s" {0..4095}' | wc -c` shows 4096
bash -c 'printf "=%.s" {0..4095}' | deno run line_length.js
```

line_length.js:

```js
import { readLines } from 'https://deno.land/std@0.110.0/io/mod.ts';
for await (let line of readLines(Deno.stdin)) {
  console.log(line.length);
}
```

In the reproduction steps above, `Deno.stdin` is used as the reader, but the same situation occurs with a `File`.

**Expected behavior**

`readLines` should work for lines longer than 4095 bytes.

If the current behavior is a limitation, `readLines` should throw an exception to inform developers about the limitation.  And the limitation should be mentioned in documents or code comments for functions/methods affected with the limitation.

At least, Python3 works fine:

```python
import sys
for line in sys.stdin:
  print(len(line))
```

**Environment**

- OS: Arch Linux (on VirtualBox 6.1.26 r145957 running on macOS 11.6)
- deno version: 1.14.2
- std version: 0.110.0

**Comment by kt3k** [comment]
This should be fixed by #1377 

We're going to release the fix as 0.112.0 on around the next Tuesday.

Thank you for reporting with the minimal examples 👍
