### ISSUE TITLE
Several `io/util` functions are "deprecated" but provide no information

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno_std#1391]
We have several functions that are deprecated in `/io/util.ts` but there is no documentation on how to resolve the deprecation, making it confusing to user using intelligent IDEs.

In addition, things like `Deno.readAll` are deprecated, but the information with the deprecation points users as using the `/io/util.ts` which are also deprecated.  For example:

```md
@deprecated Use readAllSync from https://deno.land/std/io/util.ts instead. Deno.readAllSync will be removed in Deno 2.0.
```

This should all be cleared up.

**Comment by kt3k** [comment]
@kitsonk Thank you for pointing this! I'll work on this
