### ISSUE TITLE
Handler function in HTTP

### ISSUE THREAD

**Issue by MichailVestnik** [denoland/deno_std#1392]
Hi! 

I love Deno for its rich standard library and many features are out of the box. (watch, bundler...). But it lacks a very useful feature.

# Feature

Golang has a very handy feature to handle requests with a function in the standart net/http package.

```go
package main

import (
    "io"
    "log"
    "net/http"
)

func main() {
    h1 := func(w http.ResponseWriter, _ *http.Request) {
        io.WriteString(w, "Hello from a HandleFunc #1!\n")
    }
    h2 := func(w http.ResponseWriter, _ *http.Request) {
        io.WriteString(w, "Hello from a HandleFunc #2!\n")
    }

    http.HandleFunc("/", h1)
    http.HandleFunc("/endpoint", h2)

    log.Fatal(http.ListenAndServe(":8080", nil))
}
```
Example: https://pkg.go.dev/net/http#HandleFunc

In **Deno**, such a feature would be very useful in the http package.

A hypothetical example:

```js
import { handler, listenAndServe } from "https://deno.land/std@0.112.0/http/server.ts";

const h1 = async (req, res) => {
    // do something
}

const h2 = async (req, res) => {
    // do something
}

handler('/' h1)
handler('/endpoint', h2)

listenAndServe(":8000")

```

Спасибо!

**Comment by bartlomieju** [comment]
@MichailVestnik thank you for suggestion, as pointed out by @LionC we already supported `Handler`. I'm going to close this issue, please feel free to open another one for the routing (unless @LionC will open a PR before that ;) )

**Comment by LionC** [comment]
> @MichailVestnik thank you for suggestion, as pointed out by @LionC we already supported `Handler`. I'm going to close this issue, please feel free to open another one for the routing (unless @LionC will open a PR before that ;) )

Finished implementation of the PR and its docs today - will do a last re-read if the (elaborate) docs tomorrow night and post. Fleshing it out took longer than expected^^
