### ISSUE TITLE
Check license headers in CI

### ISSUE THREAD

**Issue by kt3k** [denoland/deno_std#1415]

**Comment by lowlighter** [comment]
Is the aim of this to check the presence of "Copyright Deno authors, MIT license" at the beginning of each code file ?

**Comment by kt3k** [comment]
yes, and probably we can use this tool https://github.com/kt3k/deno_license_checker

**Comment by bartlomieju** [comment]
I'm in favor, maybe we could vendor `deno_license_checker` in `_tools/` directory?
