### ISSUE TITLE
Hashing string with sha-384 always returns an empty ArrayBuffer

### ISSUE THREAD

**Issue by herkulessi** [denoland/deno_std#1445]
**Describe the bug**
When hashing something with sha-384, the await subtle.digest("sha-384", stringToHash) alway results in an empty ArrayBuffer.
**Steps to Reproduce**

1. Create a file with the example usage from [std@0.112.0/crypto](https://deno.land/std@0.112.0/crypto#usage)
2. Replace the `"hello world"` string with `new TextEncoder().encode("hello world")` (because the function does not take strings anymore)
3. Run the Script

**Expected behavior**

Something like
```
Check file:///PathToFile/cryptoTest.ts
Uint8Array(48) [
  253, 189, 142, 117, 166, 127,  41, 247,   1,
  164, 224,  64,  56,  94,  46,  35, 152,  99,
    3, 234,  16,  35, 146,  17, 175, 144, 127,
  203, 184,  53, 120, 179, 228,  23, 203, 113,
  206, 100, 110, 253,   8,  25, 221, 140,   8,
  141, 225, 189
]
Uint8Array(32) [
  215,  73, 129, 239, 167,  10,  12,
  136,  11, 141, 140,  25, 133, 208,
  117, 219, 203, 246, 121, 185, 154,
   95, 153,  20, 229, 170, 249, 107,
  131,  26, 158,  36
]
```
instead of 
```
Check file:///PathToFile/cryptoTest.ts
ArrayBuffer {}
Uint8Array(32) [
  215,  73, 129, 239, 167,  10,  12,
  136,  11, 141, 140,  25, 133, 208,
  117, 219, 203, 246, 121, 185, 154,
   95, 153,  20, 229, 170, 249, 107,
  131,  26, 158,  36
]
```
**Environment**

- OS: Windows 11 (AMD64) as well as Debian (aarch64)
- deno version: `1.15.2 (release, x86_64-pc-windows-msvc)` as well as `1.15.2 (debug, aarch64-unknown-linux-gnu)`
- std version: both 0.112.0 (Most recent one at  time of posting) and the main branch of this repo ([Last Commit before my testing](https://github.com/denoland/deno_std/commit/fb35d703472c8d38ea816a165e78f417cdf62dc9))

**Comment by lmx-Hexagram** [comment]
I try to work on this issue and finally I find out that `console.log(sthArrayBufferLike)` will always display `ArrayBuffer {}`
But in browser, Edge prints `ArrayBuffer(48)` and Safari the same `ArrayBuffer {byteLength: 48}`.

I think I can fix this problem. 
First I will modify the README of `std/crypto` and change the example from directly print ArrayBuffer to UInt8Array.
Secondly I will work on make `console.log(sthArrayBufferLike` in Deno work the same as browser.

**Comment by lmx-Hexagram** [comment]
Here is the evidence.

In Safari
<img width="351" alt="image" src="https://user-images.githubusercontent.com/52130356/147852403-1361f9d8-93e7-4d9f-820f-d493725899bc.png">

In Edge
<img width="363" alt="image" src="https://user-images.githubusercontent.com/52130356/147852392-08d95eae-7c8c-4fd9-9b79-c1ff18a68d99.png">

In Deno
<img width="344" alt="image" src="https://user-images.githubusercontent.com/52130356/147852461-61cde1fb-841c-4add-a42a-0160ab06dcf2.png">

Code 
```ts
let arrayBuffer = await crypto.subtle.digest(
  "SHA-384",
  new TextEncoder().encode("hello world"),
)
console.log(arrayBuffer)
```

**Comment by littledivy** [comment]
@lmx-Hexagram This is not an issue with `std/crypto`. Deno's console implementation chose not print the `byteLength` for `ArrayBuffer`s. You can get the underlying bytes by putting into a view (a TypedArray)

Anyways, https://github.com/denoland/deno_std/pull/1515 already fixed the original issue by always returning an ArrayBuffer (in accordance with WebCrypto).

**Comment by lmx-Hexagram** [comment]
Well, I think I understand what you mean, but I will keep my PR open. Because example will print `ArrayBuffer {}` to console, It will confuse some people like me.
