### ISSUE TITLE
Set up bot that automatically requests review

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno_std#1472]
We should have a bot that automatically requests a review from one of maintainers for PRs.

In the beginning it could assign either me or @kt3k

**Comment by lowlighter** [comment]
You could maybe use a [code owner file](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners#about-code-owners) to make GitHub automatically assign a reviewer depending on your areas of expertise ?

**Comment by bartlomieju** [comment]
@lowlighter it's a great idea! PRs are welcome.
