### ISSUE TITLE
node: CJS loader shouldn't require full read access.

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno_std#1495]
Currently, trying to use CJS loader you get following error:
```
error: Uncaught Error: CJS loader requires --allow-read.
      throw new Error("CJS loader requires --allow-read.");
            ^
```
It's not strictly required to have full disk read access, the loader should work perfectly fine with access to the current directory.

CC @kt3k

**Comment by kt3k** [comment]
I agree that the error message can be improved, but the required range of read permission may vary depending on the dependencies of the script.

For example, you can require scripts from the parent directory (`require("../foo.js")`). Also if bare require (like `require('foo')`) doesn't find module in `./node_modules`, then it tries to look up `../node_modules`, `../../node_modules`, etc. Those require the read permission of parent directories.

**Comment by kitsonk** [comment]
Why not use `Deno.permissions.query()`?

**Comment by bartlomieju** [comment]
> I agree that the error message can be improved, but the required range of read permission may vary depending on the dependencies of the script.
> 
> For example, you can require scripts from the parent directory (`require("../foo.js")`). Also if bare require (like `require('foo')`) doesn't find module in `./node_modules`, then it tries to look up `../node_modules`, `../../node_modules`, etc. Those require the read permission of parent directories.

That's correct, but it's not the most popular path - which is sniffing in the current directory. I believe that we should require to have read access to `./` and then use @kitsonk's suggesting and query for additional permissions

**Comment by bartlomieju** [comment]
I just tried to see if this solution is feasible and there's a hiccup. APIs that are `stat`ing file system are all synchronous, while `Deno.permission.request` is an async API. There's not much room for work arounds here as the APIs are ported from Node (eg. `Module._findPath`). Without synchronous permissions API we might not be able to handle that.

**Comment by bartlomieju** [comment]
Discussed this offline with @ry, jumping to adding sync permissions API is not a good idea. We should change the error message in such a way that doesn't suggest completely opening the sandbox for read operation, so maybe something like:
```
CJS loader requires read permissions. If packages are installed locally try passing --allow-read=node_modules/ flag.
```

**Comment by kt3k** [comment]
I believe this is fixed now as we handle CJS in internal Rust code instead of std.
