### ISSUE TITLE
node: add fs.read, fs.readSync, fs.write, fs.writeSync APIs

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno_std#1496]
These APIs are needed by ESLint and TSC

- https://nodejs.org/api/fs.html#fsreadfd-buffer-offset-length-position-callback
- https://nodejs.org/api/fs.html#fsreadsyncfd-buffer-offset-length-position
- https://nodejs.org/api/fs.html#fswritefd-buffer-offset-length-position-callback
- https://nodejs.org/api/fs.html#fswritesyncfd-buffer-offset-length-position

**Comment by getspooky** [comment]
I will start working on `fs.read`, `fs.readSync`, `fs.write`, `fs.writeSync` APIs

**Comment by bartlomieju** [comment]
@getspooky great! Feel free to open separate PRs for each API if it will help.

**Comment by talentlessguy** [comment]
All of the functions have been implemented in `std/node` so this can be closed
