### ISSUE TITLE
Idea: Include pretty_bytes in std/fmt

### ISSUE THREAD

**Issue by kt3k** [denoland/deno_std#1535]
https://github.com/kt3k/pretty_bytes (which is ported from [sindresorhus/pretty-bytes](https://github.com/sindresorhus/pretty-bytes))

**Comment by LionC** [comment]
As that is often needed in CLI applications, I am all for it

**Comment by bartlomieju** [comment]
I'm also in favor, let's do it

**Comment by MierenManz** [comment]
is anyone going to make a pr for this issue? cuz I don't mind making a pr for this later today.

**Comment by bartlomieju** [comment]
@MierenManz please do
