### ISSUE TITLE
std/fs/mod.ts depends on unstable APIs

### ISSUE THREAD

**Issue by ry** [denoland/deno_std#1539]

**Comment by ah-yu** [comment]
seems unstable api `Deno.utime(sync)` is used in `copyFile(sync)/copySymLink(sync)`

**Comment by kt3k** [comment]
There is a plan for deprecating `utime` in favor of `utimes` (or `utimens`) https://github.com/denoland/deno/issues/8634. That's probably the reason why utime is not stabilized yet.

I think the correct steps to resolve this issue would be:
1. implement Deno.utimes (or Deno.utimens)
2. replace the `utime` usage with `utimes` in std/fs
3. stabilize Deno.utimes

**Comment by ry** [comment]
I don't think `std/fs/mod.ts` is useful. It implies many dependencies. I would be in favor removing it entirely. 

The steps listed in https://github.com/denoland/deno_std/issues/1539#issuecomment-964803551 are good for updating `std/fs/copy.ts` to not use utime.
