### ISSUE TITLE
implement std/node/zlib on top of CompressionStream (maybe?)

### ISSUE THREAD

**Issue by ry** [denoland/deno_std#1541]

**Comment by majidsajadi** [comment]
is there any plan to add `compress` module to `deno_std`? like  `compress` module in `golang`?

if we want to add `compress` module I guess it's a better approach to implement the std module and then implement `node/zlib` base on the implemented module.

**Comment by jimmywarting** [comment]
I think NodeJS should be the one that has to adapt to more web standards instead, they have recently got support for web streams and CompressionStream

**Comment by kt3k** [comment]
The current plan is to implement it directly with ops https://github.com/denoland/deno/pull/18291
