### ISSUE TITLE
Remove legacy HTTP server in Deno 1.17

### ISSUE THREAD

**Issue by vwkd** [denoland/deno_std#1549]
Currently there are two HTTP server after #1128 introduced a legacy HTTP server. I think having two options is confusing and complicates documentation and manual. This is the only part of Deno I know of that has a "legacy" thing.

Is there a good reason why people can not use a previous version of std instead? Isn't this case why there are versions in the first place?

**Comment by bartlomieju** [comment]
Let's do it in tandem with #1549
