### ISSUE TITLE
vm.runInThisContext

### ISSUE THREAD

**Issue by apowers313** [denoland/deno_std#1569]
**Is your feature request related to a problem? Please describe.**

I would like to create a [Jupyter](https://jupyter.org/) [kernel](https://jupyter.readthedocs.io/en/latest/projects/kernels.html) for Deno. The [IJavascript](https://github.com/n-riesco/ijavascript) uses node’s [vm.runInThisContext](https://nodejs.org/api/vm.html#scriptruninthiscontextoptions) which isn’t polyfilled and Deno’s std library doesn’t seem to have an equivalent.

**Describe the solution you'd like**

A polyfill for `runInThisContext` or a Deno native API for compiling a string as TS / JS and executing it. 

Happy to jump in and write code if someone can point me in the right direction.

**Comment by bartlomieju** [comment]
@apowers313 thanks! The easiest way would be to use `Deno.core.evalContext`, but then we'd have to ignore all options present in the Node API: https://nodejs.org/api/vm.html#scriptruninthiscontextoptions Supporting any of the options would require some work in `deno` itself, so if you don't have immediate need for them then `Deno.core.evalContext` should be sufficient.

Example of API usage in `node/module.ts` module:
https://github.com/denoland/deno_std/blob/d9996552325115b78a47c6299f0fff6958a75280/node/module.ts#L1257-L1264

**Comment by apowers313** [comment]
Thanks, that's what I needed -- I really appreciate the help.

I'm going to try to use pure Deno rather than porting over the IJavascript kernel, so I won't be needing `vm.runInThisContext` after all.

**Comment by bartlomieju** [comment]
@apowers313 sounds good, I'm very much interested in running Jupyter with Deno so feel free to open issues if you hit any hiccups
