### ISSUE TITLE
node/streams implementation is broken

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno_std#1578]
I've hit multiple issues with implementation of "streams" in `std/node` while working on https://github.com/denoland/deno_std/pull/1554, eg `highWatermark` argument is ignored, `this._read()` in `Readable doesn't handle promises.

Turns out there are more issue with it like swallowed errors which causes Node test suite not to fail when it should:
```
deno run -A --unstable -r --no-check node/_tools/require.ts /Users/biwanczuk/dev/deno_std/node/_tools/suites/parallel/test-stream2-pipe-error-handling.js
Uncaught RangeError: The argument 'size' is invalid. Received NaN
```
(this is actually the same problem as in https://github.com/denoland/deno_std/issues/1577 stemming from #1482)

We should probably rewrite streams implementation completely to be as close to the upstream source as possible.

CC @Soremwar

**Comment by Soremwar** [comment]
Even when using the `nextTick` polyfill for the browser I'm hitting multiple failed tests trying to tackle this, most of them related to stream events not executing the amount of times they are suppossed to

It now seems to me a correct-ish `nextTick` implementation is a requirement for this

**Comment by bartlomieju** [comment]
@Soremwar thanks for letting me know, I'll try to tackle that tomorrow, nonetheless let's open the PR ASAP so we can coordinate the work.

**Comment by bartlomieju** [comment]
Done in #1634
