### ISSUE TITLE
ci: Generate lcov step causes type checking

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno_std#1581]
This seems strange to me that generating coverage via `deno coverage` command causes type checking of all files. This needs to be investigated.

**Comment by bartlomieju** [comment]
@caspervonb is this expected?

**Comment by caspervonb** [comment]
Side effect of loading, fixed it in the reverted refactor iirc. Not desirable.

**Comment by kt3k** [comment]
fixed by https://github.com/denoland/deno/issues/13161
