### ISSUE TITLE
Make prettier usable from other repositories.

### ISSUE THREAD

**Issue by kt3k** [denoland/deno_std#159]
```console
deno --allow-run --allow-write https://deno.land/x/prettier/main.ts
```

The command like the above should format the source code in any repository.

**Comment by kt3k** [comment]
I want to clarify these points before starting to work:
- What options should it support?
- Should it support non git repository? (probably yes)
- Should it support config files which the original prettier CLI has? (like .prettierrc.json, .prettierignore)
- Which languages should it format by default? (maybe ts, js, and md?)

**Comment by hayd** [comment]
I don't think you necessarily need to support any of these in a first pass.

Perhaps allowing files to be specified if you pass them explicitly.

`deno format.ts mod1.ts mod2.ts`

**Comment by ry** [comment]
@kt3k this would be super useful and a minimal version that @hayd described would be great for a first pass.
