### ISSUE TITLE
node: process.binding(...)

### ISSUE THREAD

**Issue by kt3k** [denoland/deno_std#1630]
Some npm modules depend on `process.binding(<module>)` ex. https://github.com/anseki/readline-sync/blob/202fe647300645c2727b4c4c9314d44703a67233/lib/readline-sync.js#L19

We need to shim these to run those npm modules.

**Comment by kt3k** [comment]
The tool [nps](https://www.npmjs.com/package/nps) (used in mocha repo) errors at `process.binding('wrap_tty').TTY`. The same module also uses `process.binding('fs')`, `process.binding('constants')`

```shellsession
$ deno run --compat --unstable -A node_modules/.bin/nps
error: Uncaught (in promise) TypeError: process.binding is not a function
  TTY = process.binding('tty_wrap').TTY,
                ^
    at Object.<anonymous> (file:///Users/kt3k/oss/mocha/node_modules/readline-sync/lib/readline-sync.js:19:17)
```

**Comment by bartlomieju** [comment]
`process.bindings('fs')` is also required to run `npm`.
