### ISSUE TITLE
node: Reenable test for "net" module

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno_std#1635]
Following tests were disabled when landing #1634 and need to be reenabled

- "test-net-access-byteswritten.js",
- "test-net-after-close.js",
- "test-net-allow-half-open.js",
- "test-net-better-error-messages-listen.js",
- "test-net-better-error-messages-port-hostname.js",
- "test-net-bind-twice.js",
- "test-net-buffersize.js",
- "test-net-bytes-stats.js",
- "test-net-bytes-written-large.js",
- "test-net-can-reset-timeout.js",
- "test-net-connect-after-destroy.js",
- "test-net-connect-buffer.js",
- "test-net-connect-buffer2.js",
- "test-net-connect-call-socket-connect.js",
- "test-net-connect-destroy.js",
- "test-net-connect-immediate-destroy.js",
- "test-net-connect-immediate-finish.js",
- "test-net-connect-no-arg.js",
- "test-net-connect-options-port.js",
- "test-net-dns-custom-lookup.js",
- "test-net-dns-error.js",
- "test-net-dns-lookup-skip.js",
- "test-net-dns-lookup.js",
- "test-net-end-close.js",
- "test-net-end-destroyed.js",
- "test-net-end-without-connect.js",
- "test-net-isip.js",
- "test-net-isipv4.js",
- "test-net-isipv6.js",
- "test-net-listen-after-destroying-stdin.js",
- "test-net-listen-close-server-callback-is-not-function.js",
- "test-net-listen-close-server.js",
- "test-net-listen-error.js",
- "test-net-listen-invalid-port.js",
- "test-net-listening.js",
- "test-net-local-address-port.js",
- "test-net-localerror.js",
- "test-net-normalize-args.js",
- "test-net-options-lookup.js",
- "test-net-pause-resume-connecting.js",
- "test-net-server-call-listen-multiple-times.js",
- "test-net-server-close.js",
- "test-net-server-listen-options-signal.js",
- "test-net-server-listen-options.js",
- "test-net-server-listen-remove-callback.js",
- "test-net-server-max-connections.js",
- "test-net-server-options.js",
- "test-net-server-pause-on-connect.js",
- "test-net-server-try-ports.js",
- "test-net-socket-connect-without-cb.js",
- "test-net-socket-connecting.js",
- "test-net-socket-destroy-send.js",
- "test-net-socket-destroy-twice.js",
- "test-net-socket-end-before-connect.js",
- "test-net-socket-no-halfopen-enforcer.js",
- "test-net-socket-ready-without-cb.js",
- "test-net-socket-write-error.js",
- "test-net-sync-cork.js",
- "test-net-timeout-no-handle.js",
- "test-net-writable.js",
- "test-net-write-after-end-nt.js",
- "test-net-write-arguments.js",
- "test-net-write-connect-write.js",
- "test-net-write-fully-async-buffer.js",
- "test-net-write-fully-async-hex-string.js",

**Comment by cmorten** [comment]
Looking into this as part of https://github.com/denoland/deno_std/pull/2146

@bartlomieju have you made any headway / have any pointers as to what is causing the tests to hang? (No worries if not!)

**Comment by cmorten** [comment]
Been trying to triage the issue using the `test-net-buffersize.js` test from Node.

Side by side comparison (easier to spot divergence):

![Screenshot 2022-04-24 at 11 26 48](https://user-images.githubusercontent.com/11313985/164972199-61c7397a-0c97-44a7-8f6a-3977a247351e.png)
![Screenshot 2022-04-24 at 11 26 56](https://user-images.githubusercontent.com/11313985/164972203-27805368-2460-4aad-a40f-c7c8e8265d3c.png)

Differences in logs:

- `Socket.prototype._final` isn't being called in Deno, but is with Node following `afterConnect`.
    - The subsequent `afterShutdown` isn't called
- `readableAddChunk` log for Node has all 9 characters in it's buffer, Deno only has 1
- Deno seems to hang after the `flow` log line, whereas Node continues into another `readableAddChunk` cycle, hits the EOF and the shutdown process commences

Not sure it's exactly clear just yet what gone awry, but certainly feels like the interplay between `Socket` and `Duplex` (well the `Writable` and `Readable`) has become mismatched since the rewrite in https://github.com/denoland/deno_std/pull/1634
---

Deno debug logs:

```console
$ NODE_DEBUG=* deno test  -A node/_tools/test.ts -- test-net-buffersize.js
NET 7481: 'setupListenHandle' null 0 4 0 undefined
NET 7481: 'setupListenHandle: create a handle'
NET 7481: 'bind to' '::'
NET 7481: 'createConnection' [ { port: 59653 }, null, [Symbol(normalizedArgs)]: true ]
NET 7481: 'pipe' false undefined
NET 7481: 'connect: find host' 'localhost'
NET 7481: 'connect: dns options' { family: undefined, hints: 64 }
NET 7481: 'onconnection'
STREAM 7481: 'read' 0
STREAM 7481: 'need readable' false
STREAM 7481: 'length less than watermark' true
STREAM 7481: 'do read'
NET 7481: '_read'
NET 7481: 'Socket._handle.readStart'
STREAM 7481: 'on readable' 0 true
NET 7481: 'afterConnect'
STREAM 7481: 'read' 0
STREAM 7481: 'need readable' false
STREAM 7481: 'length less than watermark' true
STREAM 7481: 'do read'
NET 7481: '_read'
NET 7481: 'Socket._handle.readStart'
STREAM 7481: 'readableAddChunk' <Buffer 61>
STREAM 7481: 'emitReadable' true false
STREAM 7481: 'emitReadable' false
STREAM 7481: 'emitReadable_' false 1 false
STREAM 7481: 'read' undefined
STREAM 7481: 'need readable' false
STREAM 7481: 'length less than watermark' true
STREAM 7481: 'do read'
NET 7481: '_read'
STREAM 7481: 'flow' false

// ... then hangs - only way get these logs is by throwing an error on timeout! 😅 
```

Node debug logs:

```console
$ NODE_DEBUG=* node ./test/parallel/test-net-buffersize.js
NET 7079: setupListenHandle null 0 4 0 undefined
NET 7079: setupListenHandle: create a handle
NET 7079: bind to ::
NET 7079: createConnection [ { port: 59630 }, null, [Symbol(normalizedArgs)]: true ]
NET 7079: pipe false undefined
NET 7079: connect: find host localhost
NET 7079: connect: dns options { family: undefined, hints: 1024 }
NET 7079: onconnection
STREAM 7079: read 0
STREAM 7079: need readable false
STREAM 7079: length less than watermark true
STREAM 7079: do read
NET 7079: _read
NET 7079: Socket._handle.readStart
STREAM 7079: on readable 0 true
NET 7079: afterConnect
NET 7079: _final: not ended, call shutdown()
STREAM 7079: read 0
STREAM 7079: need readable false
STREAM 7079: length less than watermark true
STREAM 7079: do read
NET 7079: _read
NET 7079: Socket._handle.readStart
NET 7079: afterShutdown destroyed=false ReadableState {
  objectMode: false,
  highWaterMark: 16384,
  buffer: BufferList { head: null, tail: null, length: 0 },
  length: 0,
  pipes: [],
  flowing: null,
  ended: false,
  endEmitted: false,
  reading: true,
  constructed: true,
  sync: false,
  needReadable: true,
  emittedReadable: false,
  readableListening: false,
  resumeScheduled: false,
  errorEmitted: false,
  emitClose: false,
  autoDestroy: true,
  destroyed: false,
  errored: null,
  closed: false,
  closeEmitted: false,
  defaultEncoding: 'utf8',
  awaitDrainWriters: null,
  multiAwaitDrain: false,
  readingMore: false,
  dataEmitted: false,
  decoder: null,
  encoding: null,
  [Symbol(kPaused)]: null
}
STREAM 7079: readableAddChunk <Buffer 61 61 61 61 61 61 61 61 61>
STREAM 7079: emitReadable true false
STREAM 7079: emitReadable false
STREAM 7079: emitReadable_ false 9 false
STREAM 7079: read undefined
STREAM 7079: need readable false
STREAM 7079: length less than watermark true
STREAM 7079: do read
NET 7079: _read
STREAM 7079: flow false
STREAM 7079: readableAddChunk null
STREAM 7079: onEofChunk
STREAM 7079: emitReadable_ false 0 true
STREAM 7079: read undefined
STREAM 7079: endReadable false
STREAM 7079: flow false
STREAM 7079: read 0
STREAM 7079: endReadable false
STREAM 7079: endReadableNT false 0
NET 7079: SERVER _emitCloseIfDrained
NET 7079: SERVER handle? false   connections? 1
STREAM 7079: endReadableNT true 0
NET 7079: _final: not ended, call shutdown()
NET 7079: afterShutdown destroyed=false ReadableState {
  objectMode: false,
  highWaterMark: 16384,
  buffer: BufferList { head: null, tail: null, length: 0 },
  length: 0,
  pipes: [],
  flowing: false,
  ended: true,
  endEmitted: true,
  reading: false,
  constructed: true,
  sync: false,
  needReadable: false,
  emittedReadable: false,
  readableListening: true,
  resumeScheduled: false,
  errorEmitted: false,
  emitClose: false,
  autoDestroy: true,
  destroyed: false,
  errored: null,
  closed: false,
  closeEmitted: false,
  defaultEncoding: 'utf8',
  awaitDrainWriters: null,
  multiAwaitDrain: false,
  readingMore: false,
  dataEmitted: true,
  decoder: null,
  encoding: null,
  [Symbol(kPaused)]: null
}
NET 7079: destroy
NET 7079: close
NET 7079: close handle
NET 7079: has server
NET 7079: SERVER _emitCloseIfDrained
NET 7079: SERVER: emit close
NET 7079: emit close
STREAM 7079: readableAddChunk null
STREAM 7079: onEofChunk
STREAM 7079: emitReadable_ false 0 true
STREAM 7079: flow null
STREAM 7079: read 0
STREAM 7079: endReadable false
STREAM 7079: endReadableNT false 0
NET 7079: destroy
NET 7079: close
NET 7079: close handle
NET 7079: emit close
```

**Comment by cmorten** [comment]
Update on the above issue - resolved by implementing `LibuvStreamWrap.prototype.writev`. Curious that the `notImplemented(...)` error was getting swallowed...

**Comment by kt3k** [comment]
Some are enabled now, and some are not yet. Let's track the remainings in `tools/node_compat/TODO.md`

ref. https://github.com/denoland/deno/pull/18290/files#diff-66a13180ca921c746469f8f0bf6ec0cafab925839d65fdca6379866c4bb7be40
