### ISSUE TITLE
fetch doesn’t handle try/catch when http2 request fails 

### ISSUE THREAD

**Issue by ralyodio** [denoland/deno_std#1639]
any ideas how to fix this in pooledMap? I wrapped my entire fetch request with Try catch and it still crashes

```
TypeError: error sending request for url (https://briskreader.com/api/1/fetch?url=https://www.scmp.com/news/hong-kong/law-and-crime/article/3157622/hong-kong-emergency-services-search-hiker-missing?utm_source=rss_feed): http2 error: connection error received: not a result of an error
    at async mainFetch (deno:ext/fetch/26_fetch.js:266:14)
error: Uncaught (in promise) AggregateError: Threw while mapping.
        new AggregateError(errors, "Threw while mapping."),
        ^
    at https://deno.land/std@0.115.1/async/pool.ts:63:9
```

this happens if my api goes down while I'm trying to send a request to it....if nginx doesnj't server a 200 then my script crashes

i'm using systemd and if i crash the api it restarts, but during that time my pooledMap crashes from my script.

i basically did `try { ... fetch() } catch(err) { return Promise.resolve() }`

doesnt' seem to work with pooledMap

**Comment by getspooky** [comment]
@ralyodio can you please specify deno version you are using ?

**Comment by chovyprognos** [comment]
```
$ deno --version  
deno 1.16.3 (release, x86_64-unknown-linux-gnu)
v8 9.7.106.5
typescript 4.4.2
```

**Comment by ralyodio** [comment]
Any update on this? Is it a bug?

**Comment by bartlomieju** [comment]
Please provide a full reproduction code, the code you pasted is not enough to debug the problem.

**Comment by ralyodio** [comment]
http://sprunge.us/TQ93n4

**Comment by ralyodio** [comment]
I also get this error sometimes:

`TypeError: Fetch failed: Maximum number of redirects (20) reached`

try/catch is ignored

**Comment by ralyodio** [comment]
So I guess my fetch pattern sucked and doesn't do what I thought it did.

I replaced:
```
cons res = await fetch(url).catch(console.error);
```

with a real try/catch:

```
try {
  cons res = await fetch(url);
  if (res.ok) {
    body = await res.text();
 }
} catch(err) {
   console.error(err);
return Promise.resolve();
}

```

and now it doesn't crash.
