### ISSUE TITLE
http: Remove Go-style address/port strings

### ISSUE THREAD

**Issue by ry** [denoland/deno_std#1642]
Early on in the lifetime of Deno, we used strings like `":8000"` to declare a server listening on localhost at port 8000. However long ago Deno's internal APIs no longer parse these strings. See for example [`Deno.ListenOptions`](https://doc.deno.land/builtin/stable#Deno.ListenOptions). 

However in std/http/server.ts and elsewhere we still accept strings of this form or use them internally. [`_parseAddrFromStr`](https://github.com/denoland/deno_std/blob/1767fa0990acd58dea139aab65a5deadbdf3eeff/http/server.ts#L43-L87) should be removed, and probably the necessary changes to do that would be enough.

**Comment by jonasgrunert** [comment]
If no one has taken on it yet I would give it a try. I guess the option should be replaced by a seperate Port as a number and a host  as a string?

**Comment by lucacasonato** [comment]
@jonasgrunert Exactly.
