### ISSUE TITLE
"_tools/format.js" cheks over 32k files

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno_std#1645]
```
❯ ./_tools/format.js
Checked 32520 files
```

Something is wrong in format script, it should have to check so many files.

CC @kt3k

**Comment by kt3k** [comment]
I guess you might have `cov` directory created, which is specified in test command in ci.yml

**Comment by bartlomieju** [comment]
> I guess you might have `cov` directory created, which is specified in test command in ci.yml

Yes, I just spotted it, and indeed I got `cov/` directory.
