### ISSUE TITLE
log: add an option to the logger to use "stderr" for warnings and higher

### ISSUE THREAD

**Issue by pasha-bolokhov** [denoland/deno_std#1668]
Add an option so that the ConsoleHandler writes non–success messages to "stderr" rather than "stdout"

Both Node and, in prospect, Deno are being used for "shell scripting" purposes. Quite often one needs to redirect the standard output of a program/script, in which case errors sent via the existing log implementation may be lost or gone unnoticed. Standard Unix behaviour is that errors (and other messages indicating a problem) go to standard error.

### Solution
The solution is quite trivial: add an option to the logger config so that the `ConsoleHandler` could write warnings, errors and critical errors to "stderr", while debug and info would still go to "stdout"

### Testing
Testing is non–trivial though. Would perhaps need to make the test function `Deno.run()` another Deno script (where the actual test will reside), while capturing its "stdout" and "stderr" and comparing with what is expected

As a side note — currently there are no tests of `ConsoleHandler` at all

### Alternatives:
* I would rather have it as the default behaviour, but this would be a breaking change, so requesting a config option
* Another, more flexible solution would be — to let the user explicitly choose which levels should go to the standard error and which stay in the standard output

**Comment by LionC** [comment]
There are refactor PRs open right now which solve this issue
