### ISSUE TITLE
Node: importing esm files.

### ISSUE THREAD

**Issue by jespertheend** [denoland/deno_std#1671]
**Is your feature request related to a problem? Please describe.**

I'm trying to `createRequire` an existing module from npm. But the module uses esm and it seems like this isn't supported right now?
`Uncaught Error: Importing ESM module`
I could `import` the module directly, but the module imports some other npm dependencies itself, which now fails because those aren't prefixed with `/` or `./` or `../`.

**Describe the solution you'd like**

I'd like for `createRequire` to support esm imports. Either via an extra flag, or perhaps a different approach could be to use an api similar to dynamic imports, with the only difference being it resolving files similar to node.

**Describe alternatives you've considered**

I suppose it would be possible to transpile the existing module to cjs, but it's not ideal.

**Comment by bartlomieju** [comment]
You need to use `--compat` flag when running `deno`. It will enable Node resolution. See more details at https://deno.land/manual@v1.16.3/npm_nodejs/compatibility_mode

**Comment by jespertheend** [comment]
Am I correct in that `--compat` breaks support for url imports?
When I run a script containing an `"https://deno.land/std@0.117.0/fs/mod.ts"` import with `--compat --unstable` I get
```
[ERR_UNSUPPORTED_ESM_URL_SCHEME] Only file and data URLS are supported by the default ESM loader. Received protocol 'https'
```
I'd like to gradually move to deno so I was hoping to use both deno and node apis at the same time.

**Comment by bartlomieju** [comment]
@jespertheend --compat mode supports URL imports too. Which version of Deno are you using? Make sure to use the latest available.

**Comment by jespertheend** [comment]
Ah sorry my bad, upgrading deno fixed it.
