### ISSUE TITLE
node: add fs.access

### ISSUE THREAD

**Issue by kt3k** [denoland/deno_std#1684]
fs.access is needed for running ava in node compat mode. ref: https://github.com/denoland/deno/issues/12999

I'll work on this issue soon.

**Comment by bartlomieju** [comment]
FYI this was "polyfilled" in https://github.com/denoland/deno_std/pull/1435/files#diff-19b278ec062f6f86c9408dbce2b7679686494a721c1b0ceec13bc613a13f5f6d
