### ISSUE TITLE
Typo in bytes/equals.ts

### ISSUE THREAD

**Issue by nable-denis-gulin** [denoland/deno_std#1721]
typo `equalsNaive` => `equalsNative`
(I'm not able to find any code related with `equalsNaive` in WWW, so only DENO has this typo)

**Expected behavior**

`equalsNative` exported function name

**Environment**

any

- OS: any
- deno version: latest
- std version: latest

**Comment by getspooky** [comment]
can you please provide full example ?

**Comment by q1qgames** [comment]
If I'm not mistaken this is a reference to the brute force check loop in equalsNaive being a "naive implementation" of the check (as opposed to the equalsSimd function which is much more performant etc.).

So while I'm not the author, I doubt it is a typo.

**Comment by kt3k** [comment]
`naive` here means that it simply compares every byte of 2 arrays, without using SIMD technique. So this is intended, ref: https://github.com/denoland/deno_std/pull/1349

Thank you for reporting anyway
