### ISSUE TITLE
node: environment variables can contain non-string values

### ISSUE THREAD

**Issue by tjni** [denoland/deno_std#1725]
Node.js can accept environment variable values that are string, numeric, or boolean. On the other hand, Deno requires those values to be strings.

**Steps to Reproduce**

```js
// script.js

const child_process = require("child_process");

child_process.spawn("sh", [ "-c", "echo 'Hello'" ], {
    env: { N: 1 },
    stdio: [ "inherit", "inherit", "inherit" ],
});
```
```
> node script.js
Hello
```
```
> deno run --compat --unstable --allow-net --allow-read --allow-run script.js
Check https://deno.land/std@0.118.0/node/global.ts
Check https://deno.land/std@0.118.0/node/global.ts
Check https://deno.land/std@0.118.0/node/global.ts
Check https://deno.land/std@0.118.0/node/module.ts
error: Uncaught TypeError: Error parsing args: serde_v8 error: ExpectedString
      this.#process = Deno.run({
                           ^
    at Object.opSync (deno:core/01_core.js:149:12)
    at opRun (deno:runtime/js/40_process.js:27:17)
    at Object.run (deno:runtime/js/40_process.js:114:17)
    at new ChildProcess (https://deno.land/std@0.118.0/node/internal/child_process.ts:123:28)
```

**Expected behavior**

I expect the script to work in Deno when using the Node compatibility layer. The [process.env documentation](https://nodejs.org/api/process.html#processenv) says:

> Assigning a property on process.env will implicitly convert the value to a string. This behavior is deprecated. Future versions of Node.js may throw an error when the value is not a string, number, or boolean.

I think this means that Node.js in the future might no longer perform this implicit conversion and continue to allow string, number, or boolean values.

Could the compatibility layer coerce all of the values it receives to strings prior to passing them on to Deno? If this sounds reasonable, I can provide a PR.

**Environment**

- OS: Arch Linux
- deno version: 1.17.0
- std version: 0.118.0

**Comment by kt3k** [comment]
Good catch! Thanks

PRs are very welcome
