### ISSUE TITLE
async/delay DelayOptions should take an unref boolean

### ISSUE THREAD

**Issue by Sembiance** [denoland/deno_std#1730]
With the new `Deno.unrefTimer` support in Deno v1.17, the `DelayOptions` interface for `async/delay.ts` should support a new `boolean` field `unref`

When `unref` is set to `true`, the id of the internal `setTimeout` should be automatically unreffed with `Deno.unrefTimer(i)`

Thus a call like this:
```javascript
await delay(1000, {unref : true});
```
wouldn't prevent Deno from exiting.

**Comment by bartlomieju** [comment]
I think this is reasonable, @kt3k are you in favor?

**Comment by kt3k** [comment]
I'm in favor.

**Comment by getspooky** [comment]
Good idea.

**Comment by iuioiua** [comment]
@kt3k, doing this will break browser compatibility unless a Deno namespace check is done. If that’s ok, I’m happy to work on this feature.

**Comment by kt3k** [comment]
@iuioiua 
> doing this will break browser compatibility unless a Deno namespace check is done.

Right, let's check Deno namespace and keep the browser compatibility.

**Comment by iuioiua** [comment]
@kt3k, I believe this issue can be closed.
