### ISSUE TITLE
streams.readableStreamFromReader should create a byte stream

### ISSUE THREAD

**Issue by matthewleon** [denoland/deno_std#1739]
The code below fails with `Cannot use a BYOB reader with a non-byte stream`.  This feels like a bug. A `ReadableStream` created from an arbitrary `Reader` seems, if anything, like a canonical example of a "byte stream," no?

```typescript
const f = await Deno.open(
  "../matroska-test-files/test_files/test1.mkv",
);
const s = streams.readableStreamFromReader(f);
s.getReader({ mode: "byob" });
```

**Comment by crowlKats** [comment]
Doing this isnt necessary anymore given that Deno.File (and other `Reader`s) now provide a readablestream that is a byob stream
