### ISSUE TITLE
test: `serveDirectory TLS` and `serveDirIndex TLS` are flaky

### ISSUE THREAD

**Issue by kt3k** [denoland/deno_std#1750]

**Comment by kt3k** [comment]
Doesn't seem flaky now (no failures in recent ~20 main CI runs)

**Comment by kt3k** [comment]
https://github.com/denoland/deno_std/runs/6555001761?check_suite_focus=true

**Comment by kt3k** [comment]
It's really strange to see this flakiness. We check the child process prints `Listening` to stdout. So the child process should be ready for serving http requests, but `Deno.connectTls` call still see the `connection refused` error sometimes.

**Comment by iuioiua** [comment]
I believe these tests are no longer flaky since we no longer depend on opening a new process for each test. Closing for now.
