### ISSUE TITLE
Incomplete documentation for running tests

### ISSUE THREAD

**Issue by kevincennis** [denoland/deno_std#1754]
**Describe the bug**

Right now, the README file says you should be able to run `deno test --unstable --allow-all`, but that actually fails with:

```
error: Uncaught TypeError: error sending request for url (https://localhost:4505/): error trying to connect: invalid peer certificate contents: invalid peer certificate: UnknownIssuer
    at async mainFetch (deno:ext/fetch/26_fetch.js:259:14)
```

I'm not 100% sure what the best option is here. Seems the docs could be updated to include the same environment variable as the `ci.yml` action:

```
NODE_EXTRA_CA_CERTS=http/testdata/tls/RootCA.pem deno test --unstable --allow-all
```

But that seems a bit cumbersome. 

**Steps to Reproduce**

```
deno test --unstable --allow-all
```

or, much more quickly

```
deno test --unstable --allow-all  node/https_test.ts
```

**Expected behavior**

Tests pass

**Environment**

- OS: MacOS 11.6
- deno version: 1.17.1
- std version: 0.119.0

**Comment by kevincennis** [comment]
I'd be super happy to open a PR for this – just need a little guidance on what the best path to remediation is. Seems like there oughta be a better option that adding that environment variable to the test command.

**Comment by kt3k** [comment]
Thank you for reporting. I'll fix it
