### ISSUE TITLE
node: enable http-client tests

### ISSUE THREAD

**Issue by kt3k** [denoland/deno_std#1755]
These tests are disabled in #1751. We should enable these again:

- [ ] `test-http-agent-close.js`
- [ ] `test-http-agent-getname.js`
- [ ] `test-http-agent-timeout-option.js`
- [ ] `test-http-client-abort-event.js`
- [ ] `test-http-client-abort-no-agent.js`
- [ ] `test-http-client-abort-unix-socket.js`
- [ ] `test-http-client-abort3.js`
- [ ] `test-http-client-agent-abort-close-event.js`
- [ ] `test-http-client-close-event.js`
- [ ] `test-http-client-default-headers-exist.js`
- [ ] `test-http-client-defaults.js`
- [ ] `test-http-client-get-url.js`
- [ ] `test-http-client-headers-host-array.js`
- [ ] `test-http-client-invalid-path.js`
- [ ] `test-http-client-read-in-error.js`
- [ ] `test-http-client-reject-cr-no-lf.js`
- [ ] `test-http-client-reject-unexpected-agent.js`
- [ ] `test-http-client-res-destroyed.js`
- [ ] `test-http-client-set-timeout.js`
- [ ] `test-http-client-timeout-agent.js`
- [ ] `test-http-client-timeout-event.js`
- [ ] `test-http-client-timeout-on-connect.js`
- [ ] `test-http-client-timeout-option-with-agent.js`
- [ ] `test-http-client-timeout-option.js`
- [ ] `test-http-client-unescaped-path.js`

**Comment by iuioiua** [comment]
These tests are listed [here](https://github.com/denoland/deno_std/blob/main/node/_tools/TODO.md). Is this issue still required?

**Comment by kt3k** [comment]
Let's close. Thanks for the ping!
