### ISSUE TITLE
node: fs.readdir doesn't handle error correctly when the directory doesn't exist

### ISSUE THREAD

**Issue by kt3k** [denoland/deno_std#1756]
```js
import { readdir } from "https://deno.land/std@0.119.0/node/fs.ts";
readdir("xyz", (err) => {
  console.log("error");
});
```
This script should print "error" and exit normally, but it errors with uncaught error.

**Comment by bartlomieju** [comment]
The problematic code is here:
https://github.com/denoland/deno_std/blob/6bbfc8f48cfdcdcf007773d7b03c8b3a0543c658/node/_fs/_fs_watch.ts#L5-L38

Both of these helper functions only use handlers if promise resolves successfuly, neither can handle errors raised from the iterators.

**Comment by kt3k** [comment]
Thanks for the input. I'll work on this
