### ISSUE TITLE
assertEquals' diff: does not show actual values compared from getters

### ISSUE THREAD

**Issue by mfulton26** [denoland/deno_std#1767]
**Describe the bug**

The diff printed whenever `assertEquals` fails does not include the actual values compared from enumerable properties implemented using [getters](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/get).

**Steps to Reproduce**

1. Create a test file with following contents:

	  ```ts
	  import { assertEquals } from "https://deno.land/std@0.119.0/testing/asserts.ts";
	  
	  Deno.test("example", () => {
	    assertEquals(
	      Object.defineProperty({}, "a", {
	        enumerable: true,
	        get() {
	          return 1;
	        },
	      }),
	      Object.defineProperty({}, "a", {
	        enumerable: true,
	        get() {
	          return 2;
	        },
	      })
	    );
	  });
	  ```
2. Run the test with `deno test`
3. Observe the diff printed and how there is no meaningful indicator of what wasn't equal:
	```console
	      [Diff] Actual / Expected
	  
	  
	      {
	        a: [Getter],
	      }
	```

**Expected behavior**

A diff printed showing the values that were compared and determined to not be equal. e.g.:

```console
    [Diff] Actual / Expected


    {
-     a: 1,
+     a: 2,
    }
```

or if it is important to show that the values were acquired via getters then something like the following might be printed:

```console
    [Diff] Actual / Expected


    {
-     a: <Getter> 1,
+     a: <Getter> 2,
    }
```

**Environment**

- OS: MacOS 12.0.1
- deno version: 1.17.1 (release, x86_64-apple-darwin)
- std version: 0.119.0

**Remarks**

This might be similar to https://github.com/denoland/deno_std/issues/1020 in that it relies on `Deno.inspect` upstream and that if it were to expose the actual values then `assertEquals'`s diff should work but it is unclear to me if `Deno.inspect` should go as far as calling getters or not. A getter could return a completely different value from call-to-call so my instincts tell me that the onus probably lies with the `assert` module to keep track of the values actually compared to provide in a meaningful diff and not done separately as that could cause the diff to show a different value than what was actually used during the assertion.

**Comment by cuobiezi** [comment]
@kt3k Please refer 2509
