### ISSUE TITLE
Make `file_server.ts` less verbose

### ISSUE THREAD

**Issue by jespertheend** [denoland/deno_std#1768]
**Is your feature request related to a problem? Please describe.**

When hosting a site (for development) that is making a lot of requests, the console is spammed with tons of messages for every request. I really don't need to know about every request, and if a request fails I can see that from the browser inspector.

**Describe the solution you'd like**

Either disable logging for requests by default and add a `--verbose` option. Or leave it enabled by default and have an option for disabling it.

**Describe alternatives you've considered**

Wrapping the server with a `Deno.run()` call with `stdout: "null"`. But this also hides the "HTTP server listening on" message.

**Comment by erfanium** [comment]
It's better to use `console.debug` for request logging and user can easily disable debug logs
