### ISSUE TITLE
log doens't flush until rotation

### ISSUE THREAD

**Issue by ledmirage** [denoland/deno_std#1770]
**Describe the bug**

I found that when using rotation file logger, the log lines do not get written until rotated

i check the source code, i believe adding a this._buf.flush() can help
i manually insert this code into my cache copy of handles.ts and the issue is resolved

```
diff --git a/deno_dir/deps/https/deno.land/90768477dce560ddc619a11c8c635dffd0f79b45c1b486396a839bf12bb261f6 b/deno_dir/deps/https/deno.land/90768477dce560ddc619a11c8c635dffd0f79b45c1b486396a839bf12bb261f6
index 68bcc86..f9f4a76 100644
--- a/deno_dir/deps/https/deno.land/90768477dce560ddc619a11c8c635dffd0f79b45c1b486396a839bf12bb261f6
+++ b/deno_dir/deps/https/deno.land/90768477dce560ddc619a11c8c635dffd0f79b45c1b486396a839bf12bb261f6
@@ -215,6 +215,7 @@ export class RotatingFileHandler extends FileHandler {
    }

  this._buf.writeSync(this._encoder.encode(msg + "\n"));
+    this._buf.flush();
       this.#currentFileSize += msgByteLength;
   }
```

However i am not sure if this WAD (works as designed) in the first place, eg for better IO efficiency, so only writing when it hits the size threshold ?

**Steps to Reproduce**

I followed the sample code from this guide:
https://medium.com/deno-the-complete-reference/using-logger-in-deno-44c5b2372bf3

**Expected behavior**

When logging new msg, it should be written to file immediately.

**Environment**

- OS: Windows 10
- deno version:  $ deno --version
deno 1.17.1 (release, x86_64-pc-windows-msvc)
v8 9.7.106.15
typescript 4.5.2
- std version: 0.119.0

**Comment by lmx-Hexagram** [comment]
I don't think this is a bug. Deal to PR [#6014](https://github.com/denoland/deno/pull/6014) write log to buffer and only flush it when needed will get better performance.
So flush before rotate is an expected behavior and you can use log level that higher than ERROR which will immediately flush.

**Comment by lmx-Hexagram** [comment]
Well, one more thing, you can use 
```ts
Logger.handlers.forEach(handler => {
  if (handler instanceof log.handlers.FileHandler) {
    handler.flush()
  }
});
```
to force flush the log from buffer to file.
But it seems a little bit hack.

**Comment by ledmirage** [comment]
> 

That what i tho, which is why I mentioned I am not sure if this is actually expected behavior for better IO efficient. I can close this issue.
However in case I want to write a custom handler, is there documentation on how to do that? as I might want to log using syslog protocol as well.

**Comment by lmx-Hexagram** [comment]
https://deno.land/std@0.119.0/log#custom-handlers

Maybe this link will help you. You can `extends` exist handler in std to custom handler.

In fact, in the source code every handler is `extends` from `BaseHandler`
