### ISSUE TITLE
make fs work in browser

### ISSUE THREAD

**Issue by elycheikhsmail** [denoland/deno_std#1772]
In browser we don't have files like in linux/window but we can simulate files in  indexed db in browser like made in capacitor.
use cases :
- x/sqlite will work in browser
-  make js/ts code more stable  written for deno when used for browser
- ..

**Comment by jimmywarting** [comment]
I wish for for more stuff other than fs to also work in browsers
it would be good/useful if you could provide a compiled version of your ts file as vanilla javascript also along side.
even wishes for deno to be able to load a js file so it don't have to waste any time to compile ts to js in the first place

**Comment by elycheikhsmail** [comment]
> I wish for for more stuff other than fs to also work in browsers it would be good/useful if you could provide a compiled version of your ts file as vanilla javascript also along side. even wishes for deno to be able to load a js file so it don't have to waste any time to compile ts to js in the first place

I think what you need a special browser : let's say deno-browser I mean by deno-browser a browser that have full access to deno api and deno cli, this will be useful for frontend dev and test but we still need build step because "normal browser" don't understand ts, and deno transform ts to js (under the hood) on the fly befor run it

**Comment by lino-levan** [comment]
ref: https://github.com/denoland/dotland/issues/1728

On another note though, the [filesystem api](https://developer.mozilla.org/en-US/docs/Web/API/FileSystem) has been dropped for a while so I see no chance of this issue ever really being implemented.

Thoughts @bartlomieju?

**Comment by elycheikhsmail** [comment]
when npm complete no need for this
