### ISSUE TITLE
Deprecate and remove std/mime/multipart

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno_std#1778]
We have `FormData` that has all the same functionality as std/mime/multipart as far as I can tell.

Let's deprecate this module for 1.18, and remove it for 1.19.

**Comment by jd1378** [comment]
How do we handle multipart on server side with `FormData` ?
Currently I use `MultipartReader` from std/mime/multipart to get the form data sent by a client. so how is this done with `FormData` if we remove this module ?

**Comment by lucacasonato** [comment]
You call `Request.form` on the incoming request. This will give you a `Promise<FormData>`

**Comment by jd1378** [comment]
It was `request.formData`, and it worked nicely, and It's a lot cleaner now, thanks !

**Comment by kt3k** [comment]
I think we should still deprecate on the next version and remove it one minor version later

**Comment by ry** [comment]
How do you write multipart data using FormData?

**Comment by lucacasonato** [comment]
> @ry How do you write multipart data using FormData?

```js
const form = new FormData();
form.set("foo", "bar");
const req = new Request("https://google.com", { body: form });
```

**Comment by 0f-0b** [comment]
> How to parse form-data when I have a boundary string and multipart string/buffer？

Create a `Response` object with the `content-type` header set to `` `multipart/form-data; boundary=${yourBoundaryString}` ``, and call its `formData` method. `formData` returns a promise that either fulfills with a parsed `FormData` object or rejects with a `TypeError`.
