### ISSUE TITLE
Consider adding "testing/expect.ts" module

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno_std#1779]
Jest is arguably the most popular testing framework for Node ecosystem at the moment. It uses [`expect`](https://jestjs.io/docs/expect) style assertions, which seems to [be very popular](https://www.npmjs.com/package/expect) way of exercising tests too. 

I was prompted to consider it by a [recent issue in `vitest`](https://github.com/vitest-dev/vitest/issues/43) (which seems to be somewhat compatible with Jest.

To be clear: I prefer to write tests using `testing/asserts.ts`, but we shouldn't limit ourselves to only a single style, if the other is also very popular (> 8mm weekly downloads) then we should consider adding it too.

**Comment by getspooky** [comment]
Good suggestion, but I believe it would be better to create a separate library rather than include it in deno std.

**Comment by bartlomieju** [comment]
@getspooky is there a reason why you would prefer it as a third party lib? The whole idea is to have it in `deno_std` so it's easy to discover and could be used reliably.

**Comment by kt3k** [comment]
I like the idea. This makes the migration of existing libraries from node to deno very much easier.

**Comment by getspooky** [comment]
@bartlomieju can you please list of functions will be supported ?

**Comment by standvpmnt** [comment]
I might not be understanding the full context here but, could someone instead just add the expect package from jest into their project instead, by adding something like [expect package from skypack](https://www.skypack.dev/view/expect) ?

**Comment by bartlomieju** [comment]
> I might not be understanding the full context here but, could someone instead just add the expect package from jest into their project instead, by adding something like [expect package from skypack](https://www.skypack.dev/view/expect) ?

Yes, that would be equivalent (if the library indeed works with Deno), however we would like to make sure that this library is guaranteed to work with Deno and tested as part of our CI pipeline. I haven't tested this URL so can't say if it would just work.

> @bartlomieju could you please specify list of functions will be supported ?

Ideally we would support all APIs listed in the link from the first comment, but this list is a good start.

**Comment by standvpmnt** [comment]
Yes, simply importing it doesn't work in deno I suppose because of some module and dependency resolution.

**Comment by bartlomieju** [comment]
> Yes, simply importing it doesn't work in deno I suppose because of some module and dependency resolution.

Right, so ideally we'd have first-class support by having this module in `deno_std`, so users can safely rely on it for crucial part of project which is test code.

**Comment by standvpmnt** [comment]
Makes sense. From looking around, I found that there is a 3rd party package that some people in the community were working on with similar objectives [deno.land/x/expect](https://deno.land/x/expect@v0.2.9) could we try reaching out to them and explore any possibilities of bringing that into standard library?

**Comment by TomokiMiyauci** [comment]
I have previously created a module [unitest/expect](https://github.com/TomokiMiyauci/unitest/tree/main/expect).

With the significant enhancements to the testing environment since 1.21.0, it would be nice if this module could also be provided as a standard.

I hope my work will be of some help.

**Comment by bartlomieju** [comment]
@TomokiMiyauci your module looks very interesting, but it looks like it only provides single `expect` function. I was aiming for a module that would provide the same API as in Jest: https://jestjs.io/docs/expect

**Comment by TomokiMiyauci** [comment]
@bartlomieju 
Since the API consists of pure functions only, except for throwing Error, some APIs were not implemented.

- APIs related to snapshots
- `expect.assertions`
- `expect.hasAssertions`

And in the interest on composability, some APIs were cut out as functions.

- `expect.extend` -> `extendExpect`

Also, so-called asymmetric matchers (like `expect.anything`) are in [expect/dummy](https://github.com/TomokiMiyauci/unitest/tree/main/dummy).

**Comment by bartlomieju** [comment]
@TomokiMiyauci I see; I think we don't need all of the APIs in the first iteration. Could you possibly list which APIs are supported in your library?

**Comment by TomokiMiyauci** [comment]
@bartlomieju 
Note that there is no guarantee of equivalence with `jest`.

unitest/expect API

- [expect.toBe](https://github.com/TomokiMiyauci/unitest/tree/main/matcher/to_be.ts)
- [expect.toEqual](https://github.com/TomokiMiyauci/unitest/tree/main/matcher/to_equal.ts)
- [expect.toBeFalsy](https://github.com/TomokiMiyauci/unitest/tree/main/matcher/to_be_falsy.ts)
- [expect.toBeTruthy](https://github.com/TomokiMiyauci/unitest/tree/main/matcher/to_be_truthy.ts)
- [expect.toBeDefined](https://github.com/TomokiMiyauci/unitest/tree/main/matcher/to_be_defined.ts)
- [expect.toBeUndefined](https://github.com/TomokiMiyauci/unitest/tree/main/matcher/to_be_undefined.ts)
- [expect.toBeNull](https://github.com/TomokiMiyauci/unitest/tree/main/matcher/to_be_null.ts)
- [expect.toBeNaN](https://github.com/TomokiMiyauci/unitest/tree/main/matcher/to_be_na_n.ts)
- [expect.toBeInstanceOf](https://github.com/TomokiMiyauci/unitest/tree/main/matcher/to_be_instance_of.ts)
- [expect.toBeGreaterThan](https://github.com/TomokiMiyauci/unitest/tree/main/matcher/to_be_greater_than.ts)
- [expect.toBeGreaterThanOrEqual](https://github.com/TomokiMiyauci/unitest/tree/main/matcher/to_be_greater_than_or_equal.ts)
- [expect.toBeLessThan](https://github.com/TomokiMiyauci/unitest/tree/main/matcher/to_be_less_than.ts)
- [expect.toBeCloseTo](https://github.com/TomokiMiyauci/unitest/tree/main/matcher/to_be_close_to.ts)
- [expect.toBeLessThanOrEqual](https://github.com/TomokiMiyauci/unitest/tree/main/matcher/to_be_less_than_or_equal.ts)
- [expect.toHaveLength](https://github.com/TomokiMiyauci/unitest/tree/main/matcher/to_have_length.ts)
- [expect.toHaveBeenCalled](https://github.com/TomokiMiyauci/unitest/tree/main/matcher/to_have_been_called.ts)
- [expect.toHaveBeenCalledTimes](https://github.com/TomokiMiyauci/unitest/tree/main/matcher/to_have_been_called_times.ts)
- [expect.toHaveBeenCalledWith](https://github.com/TomokiMiyauci/unitest/tree/main/matcher/to_have_been_called_with.ts)
- [expect.toHaveBeenLastCalledWith](https://github.com/TomokiMiyauci/unitest/tree/main/matcher/to_have_been_last_called_with.ts)
- [expect.toHaveBeenNthCalledWith](https://github.com/TomokiMiyauci/unitest/tree/main/matcher/to_have_been_nth_called_with.ts)
- [expect.toHaveReturned](https://github.com/TomokiMiyauci/unitest/tree/main/matcher/to_have_returned.ts)
- [expect.toHaveReturnedTimes](https://github.com/TomokiMiyauci/unitest/tree/main/matcher/to_have_returned_times.ts)
- [expect.toHaveReturnedWith](https://github.com/TomokiMiyauci/unitest/tree/main/matcher/to_have_returned_with.ts)
- [expect.toHaveLastReturnedWith](https://github.com/TomokiMiyauci/unitest/tree/main/matcher/to_have_last_returned_with.ts)
- [expect.toHaveNthReturnedWith](https://github.com/TomokiMiyauci/unitest/tree/main/matcher/to_have_nth_returned_with.ts)
- [expect.toHaveProperty](https://github.com/TomokiMiyauci/unitest/tree/main/matcher/to_have_property.ts)
- [expect.toMatchObject](https://github.com/TomokiMiyauci/unitest/tree/main/matcher/to_match_object.ts)
- [expect.toMatch](https://github.com/TomokiMiyauci/unitest/tree/main/matcher/to_match.ts)
- [expect.toContain](https://github.com/TomokiMiyauci/unitest/tree/main/matcher/to_contain.ts)
- [expect.toContainEqual](https://github.com/TomokiMiyauci/unitest/tree/main/matcher/to_contain_equal.ts)
- [expect.toThrow](https://github.com/TomokiMiyauci/unitest/tree/main/matcher/to_throw.ts)
- [.not](https://github.com/TomokiMiyauci/unitest/blob/main/modifier/not.ts)
- [.resolves](https://github.com/TomokiMiyauci/unitest/blob/main/modifier/resolves.ts)
- [.rejects](https://github.com/TomokiMiyauci/unitest/blob/main/modifier/rejects.ts)

As Function

- `expect.anything` -> [anything](https://github.com/TomokiMiyauci/unitest/blob/main/dummy/anything.ts)
- `expect.any` -> [any](https://github.com/TomokiMiyauci/unitest/blob/main/dummy/any.ts)
- `expect.arrayContaining` -> [arrayContaining](https://github.com/TomokiMiyauci/unitest/blob/main/dummy/array_containing.ts)
- `expect.stringContaining` -> [stringContaining](https://github.com/TomokiMiyauci/unitest/blob/main/dummy/string_containing.ts)
- `expect.stringMatching` -> [stringMatching](https://github.com/TomokiMiyauci/unitest/blob/main/dummy/string_matching.ts)
- `expect.extend` -> [extendExpect](https://github.com/TomokiMiyauci/unitest/blob/main/expect/expect.ts)

**Comment by bartlomieju** [comment]
@TomokiMiyauci looks awesome! I'd be more than happy to include it in the deno_std if you wanted to upstream it.

**Comment by bartlomieju** [comment]
@TomokiMiyauci should I expect a PR from you adding this API?

**Comment by TomokiMiyauci** [comment]
@bartlomieju 
I intend to issue a PR, but before I do, there is something that should be clarified.

unitest internal implementation is very different from jest. Therefore, I'm not sure if the community will like it.

Specifically, the following points are very different:

- Proxy

  It does not take a class-based approach like jest. unitest emphasizes composability, and by default, there is none. I know that deno/std does not meta-programming. https://deno.land/manual/contributing/style_guide#meta-programming-is-discouraged-including-the-use-of-proxy

- Error message

  The jest matcher depends on `not`. (The use of the `not` property can be checked via `this`.)
Therefore, most matchers have error messages for `not`.
unitest does not treat `not` specially. It only adds `[not]` to the error message.

As you aim for a jest-like API, do you plan to provide jest-like messages as well?

**Comment by bartlomieju** [comment]
> Proxy

> It does not take a class-based approach like jest. unitest emphasizes composability, and by default, there is none. I know that deno/std does not meta-programming. https://deno.land/manual/contributing/style_guide#meta-programming-is-discouraged-including-the-use-of-proxy

We can make exceptions to that rule, and it seems like this is one of these situations where we should.

> As you aim for a jest-like API, do you plan to provide jest-like messages as well?

I aimed for Jest-like API, I don't particularly care if errors messages are the same.

**Comment by TomokiMiyauci** [comment]
@bartlomieju 
I am not sure if it should be a jest like class base implementation or a unitest like Proxy implementation.
jest's `expect` is a mix of matchers (e.g. `toBe`), modifiers (e.g. `not`, `rejects` ), dummy objects (e.g. `anything`), and even `assertions`.

Since unitest/expect is overly concerned with bundle size, only matchers and modifiers are configurable. Also, the dummy object is a pure function, and no `assertions` are implemented.

If the API is to be exactly the same as jest, a class-based approach would be better. Any opinions on this point?

**Comment by kt3k** [comment]
@TomokiMiyauci Can you give us more specific examples which show the differences of jest and unitest?

We generally don't try to make it 100% compatible with existing libraries (in this case jest) in std. So subtle difference is just fine in my view.

**Comment by bartlomieju** [comment]
I agree, the high level goal is to have similar API to what Jest provides. I'd also be fine with an implementation that is a direct port of what `vitest` has (linked in the first comment).

**Comment by TomokiMiyauci** [comment]
@kt3k 
The biggest difference is the presence of ambient(interface).

jest defines [interface](https://github.com/facebook/jest/blob/main/packages/expect/src/types.ts#L125) for matchers, etc.

The matcher interface is almost the same in jest and unitest. For example `toBe`:

```ts
declare function toBe(actual: unknown, expected: unknown) {}
```

Matchers are defined as pure functions. (although jest depends on `this`).
Since ``actual`` is actually passed internally, the first argument, ``actual``, must be removed as the actual type definition.

jest overrides the type definition by interface. unitest resolves this with generics.

Because of this difference, jest cannot separate interface from implementation and has many defaults.
On the other hand, because the type definition is modified by generics, there is a limitation that comments cannot appear in the intellisense.

---

One way to address this would be to change the matcher interface. Perhaps this is simpler.

```ts
function toBe(expected: unknown) {
  // this.actual
}
```

**Comment by TomokiMiyauci** [comment]
@kt3k Thanks for the response.

I will start working on the pull request. It may possibly be different from the current `unitest` implementation.

**Comment by kt3k** [comment]
@TomokiMiyauci Have you made any progress on this? Is there anything we can help on it?

**Comment by timreichen** [comment]
Just saw this issue.
I am not sure about implementing this in deno std.
This is a framework and std should be as unopinionated as possible, on which 3rd party libs can build upon. As stated this is a more of a framework, in which case I think is better suited for /x. There is can also be guaranteed to work with deno

**Comment by TomokiMiyauci** [comment]
@kt3k 
When I learned that npm will be supported in Deno, I questioned the need for this module and left it out. Sorry about that.

Do you think this module is still necessary even after npm is fully supported?

**Comment by kt3k** [comment]
@TomokiMiyauci 
Yes, I think we still need this because Deno-first implementation is better than jest or chai via `npm:` specifier in several ways (less dependencies, less downloads, better typings, etc).

`npm:` feature is mainly for compatibility to existing apps/libraries, and we generally don't recommend the usage of `npm:` to new projects.

**Comment by TomokiMiyauci** [comment]
@kt3k I understand.

I do not know if I will be able to do this work this week.

If it is urgent, someone can do it for me.

**Comment by TomokiMiyauci** [comment]
I am currently redesigning the internal interface of expect.
The type definition complexity of unitest's expect was not good, so I am designing it to be as simple as possible.

Hopefully, I may be able to submit a Draft PR in the near future.

You can check this work in progress.
https://github.com/TomokiMiyauci/expect.js

**Comment by bartlomieju** [comment]
This was recently discussed during the CLI meeting prompted by discussion between @marvinhagemeister and myself. We are still very much interested in bringing this functionality to the standard library. 

Marvin do you have any suggestion which library should we base it on?

**Comment by Sorikairox** [comment]
@bartlomieju what about "simply" making something compatible with Jest and Vitest, based on the list provided [on the ticket  you linked in your first message](https://github.com/vitest-dev/vitest/issues/43)

Would ease migration from Node to Deno project, and based on something that many devs are used to ?

- [ ] [expect(value)](https://jestjs.io/docs/expect#expectvalue)
- [ ]  [expect.extend(matchers)](https://jestjs.io/docs/expect#expectextendmatchers)
- [ ]  [expect.anything()](https://jestjs.io/docs/expect#expectanything)
- [ ]  [expect.any(constructor)](https://jestjs.io/docs/expect#expectanyconstructor)
- [ ]  [expect.arrayContaining(array)](https://jestjs.io/docs/expect#expectarraycontainingarray)
- [ ]  [expect.assertions(number)](https://jestjs.io/docs/expect#expectassertionsnumber)
- [ ]  [expect.hasAssertions()](https://jestjs.io/docs/expect#expecthasassertions)
- [ ]  [expect.not.arrayContaining(array)](https://jestjs.io/docs/expect#expectnotarraycontainingarray)
- [ ]  [expect.not.objectContaining(object)](https://jestjs.io/docs/expect#expectnotobjectcontainingobject)
- [ ]  [expect.not.stringContaining(string)](https://jestjs.io/docs/expect#expectnotstringcontainingstring)
- [ ]  [expect.not.stringMatching(string | regexp)](https://jestjs.io/docs/expect#expectnotstringmatchingstring--regexp)
- [ ]  [expect.objectContaining(object)](https://jestjs.io/docs/expect#expectobjectcontainingobject)
- [ ]  [expect.stringContaining(string)](https://jestjs.io/docs/expect#expectstringcontainingstring)
- [ ]  [expect.stringMatching(string | regexp)](https://jestjs.io/docs/expect#expectstringmatchingstring--regexp)
- [ ]  [.not](https://jestjs.io/docs/expect#not)
- [ ]  [.resolves](https://jestjs.io/docs/expect#resolves)
- [ ]  [.rejects](https://jestjs.io/docs/expect#rejects)
- [ ]  [.toBe(value)](https://jestjs.io/docs/expect#tobevalue)
- [ ]  [.toHaveBeenCalled() - sinon](https://jestjs.io/docs/expect#tohavebeencalled---sinon)
- [ ]  [.toHaveBeenCalledTimes(number)](https://jestjs.io/docs/expect#tohavebeencalledtimesnumber)
- [ ]  [.toHaveBeenCalledWith(arg1, arg2, ...)](https://jestjs.io/docs/expect#tohavebeencalledwitharg1-arg2-)
- [ ]  [.toHaveBeenLastCalledWith(arg1, arg2, ...)](https://jestjs.io/docs/expect#tohavebeenlastcalledwitharg1-arg2-)
- [ ]  [.toHaveBeenNthCalledWith(nthCall, arg1, arg2, ....)](https://jestjs.io/docs/expect#tohavebeennthcalledwithnthcall-arg1-arg2-)
- [ ]  [.toHaveReturned()](https://jestjs.io/docs/expect#tohavereturned)
- [ ]  [.toHaveReturnedTimes(number)](https://jestjs.io/docs/expect#tohavereturnedtimesnumber)
- [ ]  [.toHaveReturnedWith(value)](https://jestjs.io/docs/expect#tohavereturnedwithvalue)
- [ ]  [.toHaveLastReturnedWith(value)](https://jestjs.io/docs/expect#tohavelastreturnedwithvalue)
- [ ]  [.toHaveNthReturnedWith(nthCall, value)](https://jestjs.io/docs/expect#tohaventhreturnedwithnthcall-value)
- [ ]  [.toHaveLength(number)](https://jestjs.io/docs/expect#tohavelengthnumber)
- [ ]  [.toHaveProperty(keyPath, value?)](https://jestjs.io/docs/expect#tohavepropertykeypath-value?)
- [ ]  [.toBeCloseTo(number, numDigits?)](https://jestjs.io/docs/expect#tobeclosetonumber-numdigits?)
- [ ]  [.toBeDefined()](https://jestjs.io/docs/expect#tobedefined)
- [ ]  [.toBeFalsy()](https://jestjs.io/docs/expect#tobefalsy)
- [ ]  [.toBeGreaterThan(number | bigint)](https://jestjs.io/docs/expect#tobegreaterthannumber--bigint)
- [ ]  [.toBeGreaterThanOrEqual(number | bigint)](https://jestjs.io/docs/expect#tobegreaterthanorequalnumber--bigint)
- [ ]  [.toBeLessThan(number | bigint)](https://jestjs.io/docs/expect#tobelessthannumber--bigint)
- [ ]  [.toBeLessThanOrEqual(number | bigint)](https://jestjs.io/docs/expect#tobelessthanorequalnumber--bigint)
- [ ]  [.toBeInstanceOf(Class)](https://jestjs.io/docs/expect#tobeinstanceofclass)
- [ ]  [.toBeNull()](https://jestjs.io/docs/expect#tobenull)
- [ ]  [.toBeTruthy()](https://jestjs.io/docs/expect#tobetruthy)
- [ ]  [.toBeUndefined()](https://jestjs.io/docs/expect#tobeundefined)
- [ ]  [.toBeNaN()](https://jestjs.io/docs/expect#tobenan)
- [ ]  [.toContain(item)](https://jestjs.io/docs/expect#tocontainitem)
- [ ]  [.toContainEqual(item)](https://jestjs.io/docs/expect#tocontainequalitem)
- [ ]  [.toEqual(value)](https://jestjs.io/docs/expect#toequalvalue)
- [ ]  [.toMatch(regexp | string)](https://jestjs.io/docs/expect#tomatchregexp--string)
- [ ]  [.toMatchObject(object)](https://jestjs.io/docs/expect#tomatchobjectobject)
- [ ]  [.toMatchSnapshot(propertyMatchers?, hint?)](https://jestjs.io/docs/expect#tomatchsnapshotpropertymatchers?-hint?)
- [ ]  [.toMatchInlineSnapshot(propertyMatchers?, inlineSnapshot)](https://jestjs.io/docs/expect#tomatchinlinesnapshotpropertymatchers?-inlinesnapshot)
- [ ]  [.toStrictEqual(value)](https://jestjs.io/docs/expect#tostrictequalvalue)
- [ ]  [.toThrow(error?)](https://jestjs.io/docs/expect#tothrowerror?)

**Comment by bartlomieju** [comment]
@Sorikairox seems like a good starting point! Is it something you're interested in implementing?

**Comment by Sorikairox** [comment]
@bartlomieju oh yeah, definitely ! I have a long weekend ahead thanks to Monday being a holiday, perfect timing

**Comment by iuioiua** [comment]
The two main reasons for adding this to the standard library are that it's familiar and a Deno-first implementation. `std/assert` is versatile, relatively straightforward and seems to incur enough maintenance as it is. Having another module with so much overlap with `std/assert` when `expect` is accessible via NPM specifiers doesn't seem worth the added complexity. I'm -1 on adding this to the standard library.

**Comment by iuioiua** [comment]
Anything remaining for this, @kt3k? Can this be closed?

**Comment by kt3k** [comment]
Yes, let's close!

By the way, there are some unsupported matchers/features, and they are documented in `@module` doc of `std/expect` https://github.com/denoland/deno_std/blob/bc540fbf075cfeab235d7ffd96086b9fa13604d5/expect/mod.ts#L21

Let's revisit them when these features are requested by the users.
