### ISSUE TITLE
[debuglog] Error: Unexpected Identifier/Deno not defined when bundled

### ISSUE THREAD

**Issue by quaos** [denoland/deno_std#1785]
**Describe the bug**

I have a React app which previously worked, but after updating Deno and std to latest version, the app fails to start with error message: `Uncaught SyntaxError: Unexpected identifier` in the bundled JS.

_NOTE: I tried to reproduce the issue in my another small, public repo. But it produces `Uncaught ReferenceError: Deno is not defined` instead_

Digging deeper, it is these lines:
```js
if (Deno.permissions) { // <---- Deno is not defined
    state = (await Deno.permissions.query({ // <---- Uncaught SyntaxError: Unexpected identifier
        name: "env",
        variable: "NODE_DEBUG"
    })).state;
}
if (state === "granted") {
    initializeDebugEnv(Deno.env.get("NODE_DEBUG") ?? "");
} else {
    initializeDebugEnv("");
}
```

which is deep in my dependencies tree: `pixi.js@6.2.1 -> ... -> @pixi/utils@6.2.1 -> ... -> std@0.119.0/node/util.ts ->  std@0.119.0/node/_util/_debuglog.ts`

**Steps to Reproduce**

* Pull this repo: https://github.com/quaos/deno-react-minimal-frontend , and check out branch:  `test-std-119`
* Bundle the app: `yarn build` or `npm run build`
* Run the app in browser: `yarn start` or `npm start`
* You'll see the white page with errors in the console

**Expected behavior**

The app should render.

**Environment**

- OS: MacOS 10.14.6 (18G103)
- deno version: 1.17.0 (release, x86_64-apple-darwin)
- v8 version: 9.7.106.15
- typescript version: 4.5.2
- std version: 0.119.0
- Browser: Chrome version 96.0.4664.93 (Official Build) (x86_64)

**Comment by treethought** [comment]
experiencing the same issue

**Comment by kt3k** [comment]
@quaos You import `std/node/querystring.ts` [here](https://github.com/quaos/deno-react-minimal-frontend/blob/test-std-119/src/deps/std.ts#L4), which introduces the dependency to `std@0.119.0/node/_util/_debuglog.ts` and that causes the above error.

`std/node` is not for browsers. You shouldn't import from `std/node` in client side script. For `querystring.encode`, you can use [URLSearchParams](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams) to encode object to query strings.

Note: I couldn't find `pixi.js` dependency in your branch.

**Comment by quaos** [comment]
> @quaos You import `std/node/querystring.ts` [here](https://github.com/quaos/deno-react-minimal-frontend/blob/test-std-119/src/deps/std.ts#L4), which introduces the dependency to `std@0.119.0/node/_util/_debuglog.ts` and that causes the above error.
> 
> `std/node` is not for browsers. You shouldn't import from `std/node` in client side script. For `querystring.encode`, you can use [URLSearchParams](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams) to encode object to query strings.
> 
> Note: I couldn't find `pixi.js` dependency in your branch.

Thanks. This is just a test repo/branch that I used to try and reproduce this behaviour, and I didn't add `pixijs` to it. 

So that might be an issue in `@pixi/utils` itself that include Node's libs. Supposed I should open the issue there instead.
