### ISSUE TITLE
walk() fails on socket

### ISSUE THREAD

**Issue by clemens-tolboom** [denoland/deno_std#1789]
**Describe the bug**

Running `walk('/Users/clemens')` does not check for sockets.

> DEBUG RS - deno_runtime::ops::fs:1168 - op_read_dir_async /Users/clemens/.docker/run/docker.sock
> error: Uncaught (in promise) Error: Not a directory (os error 20), readdir '/Users/clemens/.docker/run/docker.sock' for path "/Users/clemens/.docker/run/docker.sock"

MacOS says
```
file /Users/clemens/.docker/run/docker.sock
/Users/clemens/.docker/run/docker.sock: socket
```

**Steps to Reproduce**

On MacOS run

```typescript
import { walk } from "https://deno.land/std@0.120.0/fs/walk.ts";

for await (const entry of walk('/Users/clemens')) {
    console.log(entry.path,entry.isFile);
}
```

The checks in https://github.com/denoland/deno/blob/d44011a69e0674acfa9c59bd7ad7f0523eb61d42/runtime/ops/fs.rs#L1178 seems logic. What is wrong?

**Expected behavior**

Happy scanner the whole tree

**Environment**

- MacOS 11.6.2
- deno 1.17.1 (release, x86_64-apple-darwin)
- v8 9.7.106.15
- typescript 4.5.2
- std@0.120.0

**Comment by clemens-tolboom** [comment]
FWIW I tried to create a socket like using python but my default python is broken. Using `mkfifo` seems not to work either.

```typescript
testWalk(
  async (d: string) => {
    d = '/tmp/ugly-test';
    await Deno.mkdir(d + "/a/b", { recursive: true });
    console.log('python3');
    // Deno.run({cmd:['python3', '-c', `"import socket as s; sock = s.socket(s.AF_UNIX); sock.bind('${d}/a/b/somesocket')"`],})
    Deno.run({cmd:['mkfifo', `${d}/a/b/mkfifo`]})
  },
  async function subDirWithSocket() {
    assertReady(3);
    const arr = await walkArray("a");
    console.log(arr);
    assertEquals(arr, ["a", "a/b"]);
  }
);
```

(my2cents)

**Comment by clemens-tolboom** [comment]
I can reduce the test by

```zsh
mkdir /tmp/ugly-test
mkfifo /tmp/ugly-test/fifo
```
then run
```typescript
import { walk } from "https://deno.land/std@0.120.0/fs/walk.ts";

for await (const entry of walk('/tmp/ugly-test')) {
    console.log(entry.path,entry.isFile);
}
```

**Comment by bnoordhuis** [comment]
#1792 - I opted to filter them out. Please weigh in on the PR if that works for you.
