### ISSUE TITLE
Discussion: asserts

### ISSUE THREAD

**Issue by ry** [denoland/deno_std#179]
In testing we originally had two methods `assert` and `assertEqual`

but at some point I (somewhat thoughtlessly) suggested that we mirror the Node API. So we have things like `assert.equal` as well as `assertEqual`.

What do people think? I kinda like `assertEqual` as it's less to type and I imagine the tab completion is better in VS Code.

Obviously we should do one or the other but not both.

(Related: I'd really like to have https://github.com/bokuweb/deno-pretty-assert in core... cc @bokuweb)

**Comment by sh7dm** [comment]
With `assert.equal` we can make more `assert.*` functions and keep in clean

**Comment by bokuweb** [comment]
> With `assert.equal` we can make more `assert.*` functions and keep in clean

I think so too.

> Related: I'd really like to have https://github.com/bokuweb/deno-pretty-assert in core...

I'm glad to hear that :) I'll add it  to the core at any time if you're OK ;)

**Comment by kitsonk** [comment]
From a VSCode code completion perspective, I am not sure either way provides a distinct advantage.  What assert looks like:

![assert](https://user-images.githubusercontent.com/1282577/52520051-c3144180-2cb8-11e9-904c-969e65560caa.gif)

The one advantage, for `assert` is that you only have a single import to have the full API.  As you are authoring tests, sometimes you don't realise you need `assert.throws` or whatever until you are trundling along.

As far as good diffing like there is in https://github.com/bokuweb/deno-pretty-assert, I am +1 for that.  Ideally that would be baked into an `AssertionError` which took an actual and an expected as the constructor and set the message with the diff text.

**Comment by keroxp** [comment]
+1 for `assertXXX`.
Exported object can be changed after importing even if it is declared as const.

```a.ts
import {assert} from "./testing/mod.ts";
assert["equal"] = (a,b) => {
  if (a === b) throw Error("😎");
};
```
```b.ts
import "a.ts"
import {assert, runTests, test} from "./testing/mod.ts";

test(function aa() {
  assert.equal(1,1); // throw "😎"
});

setTimeout(runTests,0)
```

**Comment by thysultan** [comment]
@keroxp `Object.defineProperty` can make the property non-writable/configurable but being able to monkey patch can be considered a plus in some cases.

There's also the option of:

```js
import * as assert from 'assert'

assert.equal(...)
```

**Comment by kitsonk** [comment]
The only problem with the namespace import it you lose the root `assert()` as a function.

As pointed out though if mutating `assert` really concerns people, which I don't think it should, then the function can be frozen.

**Comment by j-f1** [comment]
Could be exported both ways: each function as a named export, and the `assert` function with all its properties as the default export.

**Comment by kitsonk** [comment]
I think we should pick one way and stick with it.  It is the DRY principle.  I like the all in one assert because it is the model I have been most used to, but I see it as an either/or, and wouldn't lose too much sleep if we went to individual functions.

**Comment by hayd** [comment]
#227 seems to be resolution of this discussion... ?

**Comment by zekth** [comment]
You're right

**Comment by ry** [comment]
Ok, enough discussion. 

I'm going to remove the node-style assert object and go with a better API more familiar to gtest people.

Asserts will be moved out of testing/mod.ts and people will import from testing/assert.ts.

The first part of this work will be done in #227
