### ISSUE TITLE
node:  Move `/path` into `/node` and improve compatibility with node

### ISSUE THREAD

**Issue by wafuwafu13** [denoland/deno_std#1813]
#### 1. Move `/path` into `/node`

now, `path` is implemented in [deno_std/path](https://github.com/denoland/deno_std/tree/main/path) and  [deno_std/node/path](https://github.com/denoland/deno_std/tree/main/node/path) import this.
API provided by `deno_std/path` is almost the same as [node](https://nodejs.org/api/path.html) so move API implemented in `deno_std/path` into `deno_std/node/path`.

#### 2. improve compatibility with node

[Enable more native node tests](https://github.com/denoland/deno_std/issues/911) about `path`.

https://github.com/denoland/deno_std/pull/1812 is blocked by [Uncaught ReferenceError](https://github.com/denoland/deno_std/runs/4773774105?check_suite_focus=true).

It may be caused by [circular imports](https://github.com/denoland/deno_std/issues/1609):
`import { ERR_INVALID_ARG_TYPE } from "../node/_errors.ts";` and use `ERR_INVALID_ARG_TYPE` in `path/_util.ts`

**Comment by wafuwafu13** [comment]
I'll start with `1. Move /path into /node`.

**Comment by kitsonk** [comment]
No.  We would be unwilling to accept that breaking change, especially without further discussion.

**Comment by lucacasonato** [comment]
I am strictly opposed to moving `/path` into `/node`.

**Comment by kt3k** [comment]
Probably we should copy the contents of `std/path` into `std/node/path` first, and modify them to improve the compatibility further

**Comment by wafuwafu13** [comment]
I agree.

**Comment by wafuwafu13** [comment]
finish https://github.com/denoland/deno_std/pull/1879
