### ISSUE TITLE
feat(testing): add compile-time type equal/assignable assert functions

### ISSUE THREAD

**Issue by sno2** [denoland/deno_std#1824]
**Is your feature request related to a problem? Please describe.**

When you are creating very hacky and complex TypeScript types, it is a necessity to add tests. However, it can be hard to figure out how to correctly test your types. This new API would give people an easy way to test their TypeScript types and also give the standard library a way to test certain features that have been discussed which would have complex TypeScript types (e.g. string url parsing at compile-time, url route params parsing).

**Describe the solution you'd like**

I would like to have two new API functions that would throw compile-time errors if the given requirements are not met.  Here is my implementation:

```ts
const asserterLockSymbol = Symbol();
const asserterGenericLockSymbol1 = Symbol();
const asserterGenericLockSymbol2 = Symbol();

type AreEqualTypes<T, F> = [T] extends [F] ? [F] extends [T] ? true : false
  : false;

type AssertEqualTypeLock<T, F> = true extends AreEqualTypes<T, F> ? []
  : [typeof asserterLockSymbol];

/** Asserts at compile-time that `T` is equal to `F`. */

export function assertEqualTypes<
  T = typeof asserterGenericLockSymbol1,
  F = typeof asserterGenericLockSymbol2,
>(
  ..._asserterLock: AssertEqualTypeLock<T, F>
) {}

assertEqualTypes<true, false>();
assertEqualTypes<true, true>();
assertEqualTypes<true, boolean>();
assertEqualTypes<true, any>();
assertEqualTypes<true, never>();
assertEqualTypes<true, unknown>();
assertEqualTypes<0, number>();
assertEqualTypes<number, number>();

type AssertInequalTypeLock<T, F> = false extends AreEqualTypes<T, F> ? []
  : [typeof asserterLockSymbol];

/** Asserts at compile-time that `T` is not equal to `F`.  */
export function assertInequalTypes<
  T = typeof asserterGenericLockSymbol1,
  F = typeof asserterGenericLockSymbol2,
>(
  ..._asserterLock: AssertInequalTypeLock<T, F>
) {}

assertInequalTypes<true, false>();
assertInequalTypes<true, true>();
assertInequalTypes<true, boolean>();
assertInequalTypes<true, any>();
assertInequalTypes<true, never>();
assertInequalTypes<true, unknown>();
assertInequalTypes<0, number>();
assertInequalTypes<number, number>();

type IsAssignable<T, F> = [T] extends [F] ? true : false;

type AssertAssignableTypeLock<T, F> = true extends IsAssignable<T, F> ? []
  : [typeof asserterLockSymbol];

/** Asserts at compile-time if `T` is assignable to `F`. */
export function assertAssignableType<
  T = typeof asserterGenericLockSymbol1,
  F = typeof asserterGenericLockSymbol2,
>(..._asserterLock: AssertAssignableTypeLock<T, F>) {
}

assertAssignableType<true, false>();
assertAssignableType<true, true>();
assertAssignableType<true, boolean>();
assertAssignableType<true, any>();
assertAssignableType<true, never>();
assertAssignableType<true, unknown>();
assertAssignableType<0, number>();
assertAssignableType<number, number>();


type AssertNotAssignableLock<T, F> = false extends IsAssignable<T, F> ? []
  : [typeof asserterLockSymbol];

/** Asserts at compile-time if `T` is not assignable to `F`. */
export function assertNotAssignableType<
  T = typeof asserterGenericLockSymbol1,
  F = typeof asserterGenericLockSymbol2,
>(..._asserterLock: AssertNotAssignableLock<T, F>) {
}

assertNotAssignableType<true, false>();
assertNotAssignableType<true, true>();
assertNotAssignableType<true, boolean>();
assertNotAssignableType<true, any>();
assertNotAssignableType<true, never>();
assertNotAssignableType<true, unknown>();
assertNotAssignableType<0, number>();
assertNotAssignableType<number, number>();
```

[TypeScript Playground Link](https://www.typescriptlang.org/play?#code/MYewdgzgLgBAhhCBTATlVAZEwDWBlATwFsAjEAGxgF4ZDSKAKASgG4AoUSWBZNVAcSRhUAS2BZcdMuQCM1WsWnN2naPESp0KQcJRiJ+RRQBM8qY1Zs2UAgAckMAIIokAUQCOAVzjkAKnaQIAB5fABoYADEAPnkAbV8AXRgkAA90MAATCBhYiKSAfhy85LShLJzEmEKoFE8HAC4YADMfZDYYGEaW8mR2awCnDTQPbz8AgxDw6PkaupL08uc3Lx9-e2CwyJjC2IT2zpybexAm9V4tA3NyBL6AegAqe8Hz7LhYUCJbEXIkAFooEREBxQAAWbxgAANfBCYCJskgVpQoCBIREIQA6GD3W5WVK2EBoZqeMDAAHgM6aEarALBfa+GYBE4UvjaISicTYQz0WShfYRBnHU48TQCNl6DmSIzkYy8qIMfboxUAfWFLIMjUcQygVLG9gmm2ibCYMAA3gBfKyq7WItaBIKzJDhbrIOWWK0623BB3hB2u9jum00+21R0wMgUJBwMB+tgB0ae4N1cJRggxuPU9aJ0PCABuqDTWo9Qe9MGJODAIAA7tHlLHC4HMwAGcJgTykfO19O6u2t9soFttkgdyz9ezPTQASWEDaQ+qmMRozocqQW2SWRczBu2OT2HUasSOSCZVswnKuNysDyempe8HeIE+3z+AKBMFB4KhMLhMArsARozfFEITRTEsRxPECVgJpiVJERyStKd-wzO06QFI8hS1UVdH0M8pRkXkOn5GhD2PTDWWwiUuWkGU2DlBVlRPFB1XHNBEJnOctiNU0LTrc42PjYsQydVokALPjpwEzMS19TstX45CvSEsMQAjKMxMnCSFKzZMwFTWTxKQ7tFKTH8kDzFB1NYzSjO00swHLKsazdOTrITZsf0HYd-RcwyE17Id+w8vsY1HBwJwgG8RAAczAOASB+SYtjiSoVzKbJcgKN8QwOJc+kPFioEimK4p+W0OOmYjstSzJsnCorYvipBEumHZdwOA9GQw85T0lbkLzYK8Ctee9Hx+f5AQcERTk-WFXkQaKGp+QDUQxMC2AgwloJJMkwGZQr5uKxrbSCVDiM6vasPZS48IIyI0NI7ryKu3DuRouVFXRFUyOYm9NHqkqkDKzlmqiY0TTYHirX+o6AlspdLP2iAFoB47pJDBHodK2GS3DH41P0v6DsWwHsaUlMMaJlHSZM3MvN4wmkcOrH7FsssK2rCnGeJ473P8umocpmGWb5wKRZC0KCoAORARHkca8qF2aET5jSmA6sFhKtyqHd9n3EiupFJiXukfrBt+tBhpgD4vjGl9Jum6FZp-GWzjlpbkRWzFsXWlJ8U2mCdr26XZaZkmWdOt9zsYnRnt66R8L5e6DZZGPxWu17ZQYD6vsen6tWDzHZ2BrcwYhy185lwvUaU+GCbQAuNbDpq0bqBGG65qmWZxlS8ac7zznbt2m9s8m66gQfQ+rmmzP5iuQ+56nQzZxy28rxueYHYKx4nhfhc80X95jIA)

**Describe alternatives you've considered**

- I am not completely sure about the algorithm I used for what I call "equal". This definitely should be debated as some people think that `any !== __` which IMO doesn't make sense as `any` is everything.  In the current implementation, `any` would be equal and assignable to anything.

**Comment by sno2** [comment]
Honestly, it might be better to remove the negating methods (`assertInequalTypes` and `assertNotAssignableType`). If you're asserting something, then should most likely say what you want it to be or check the values of properties. Otherwise, you're opening yourself up to more errors.

**Comment by kt3k** [comment]
I like the idea, and there was also a similar proposal https://github.com/denoland/deno_std/discussions/1115

cc @jeremyBanks

**Comment by lino-levan** [comment]
@kt3k I missed this when https://github.com/denoland/deno_std/pull/2864 got merged. Should this still be open? I feel like `std/testing/types.ts` does a good job of resolving this issue.

**Comment by kt3k** [comment]
I think #2864 solved this issue. Closing

Create a new issue if `testing/types` isn't sufficient for your use case @sno2
