### ISSUE TITLE
std/node/streams does not work in Deno Deploy anymore

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno_std#1825]
**Describe the bug**

std/node/streams does not work in Deploy.

**Steps to Reproduce**

Do the following in Deno Deploy:

```js
import "https://deno.land/std@0.119.0/node/internal/streams/readable.js";
```

This breaks because it expects that `Deno.stdout` and `Deno.stderr` are present. It does not make sense that these exports are in this module anyway. This should be in process, not in streams.

The relevant code is here: https://deno.land/std@0.119.0/node/internal/streams/readable.js#L1451-L1452

**Expected behavior**

I should be able to successfully import this module, even if I can not make use of the stdin and stderr exports.

**Environment**

Deno Deploy

**Comment by lucacasonato** [comment]
Stdin has the same issue, just in a different file: https://deno.land/std@0.119.0/node/_process/streams.ts

**Comment by vorticalbox** [comment]
does anyone know when this will be released? my app still has this error
