### ISSUE TITLE
Include mocha polyfill to std

### ISSUE THREAD

**Issue by kt3k** [denoland/deno_std#1831]
Include the [Mocha polyfill](https://gist.github.com/lucacasonato/54c03bb267074aaa9b32415dbfb25522) to std (with further compatible APIs such as `it.skip`, `decribe.skip`, `timeout`, `retries`.

Inclusion of it makes it easier for existing libraries to migrate from node to deno.

**Comment by kt3k** [comment]
similar issue https://github.com/denoland/deno_std/issues/931

**Comment by nayeemrmn** [comment]
#1389

**Comment by vwkd** [comment]
Is there a precedence to include polyfills for third party modules in the std library? It starts with a single one, and ends with the whole NPM library. How to decide including Mocha but not XYZ? Amounts of users, or subjective need of maintainers?

Why should this be included in std library? Why can’t this be published as a third party module in the x library?

**Comment by kt3k** [comment]
> Is there a precedence to include polyfills for third party modules in the std library?

`flags` is based on minimist. `encoding/yaml` is based on js-yaml. `std/fmt/bytes` is based on pretty-bytes npm module. We selectively borrow from npm modules when those make sense.

> Why can’t this be published as a third party module in the x library?

A 3rd party module might be a possibility, but if it's available in std, the users can rely on that module more confidently.

BTW what I suggest is not a complete polyfill of the entire mocha APIs, but similar set of APIs such as `describe`, `it`, `beforeEach`, `afterEach`. (Probably the issue title was wrong)

**Comment by kt3k** [comment]
but having thought about this again, I now feel it's better to start as a 3rd party module.
