### ISSUE TITLE
Changed behavior in: std/encoding/csv.ts 

### ISSUE THREAD

**Issue by cfjello** [denoland/deno_std#1840]
I have observed a changed behavior when using **deno 1.18.0** and  _'https://deno.land/std/encoding/csv.ts'_:

I'm am not sure if this is a bug or just some type related fallout.

### Steps to reproduce
Here is some working code using _std@0.82.0/encoding/csv.ts_:

```
// import { parse as parseCsv } from 'https://deno.land/std/encoding/csv.ts';

 import {
    parse as parseCsv
  } from 'https://deno.land/std@0.82.0/encoding/csv.ts'


const content = await parseCsv(await Deno.readTextFile('csvTestItems.csv'), {
  skipFirstRow: true,
  parse: (e: any): unknown => {
    return { item: e.Name, quantity: e.Quantity, pricePerItem: `$${e.Price.toLocaleString('en-US')}`, isExpensive: e.Price >= 3000 };
  },
});

console.log(content);
```
This compiles and runs without problems:

`deno run -A --unstable  csvTest.ts`

If you switch the import statement to the one at the very top in order use the newer _csv.ts_ version:

`import { parse as parseCsv } from 'https://deno.land/std/encoding/csv.ts';`

you get the following Typescript error:

> Check file:///C:/Work/GHCN-DAILY/csvTest.ts
> error: TS2769 [ERROR]: No overload matches this call.
>   The last overload gave the following error.
>     Argument of type '{ skipFirstRow: true; parse: (e: any) => unknown; }' is not assignable to parameter of type 'ParseOptions'.
>       Object literal may only specify known properties, and 'parse' does not exist in type 'ParseOptions'.
>   parse: (e: any): unknown => {
>   ^
>     at file:///C:/Work/GHCN-DAILY/csvTest.ts:11:3
> 
> TS2771 [ERROR]:     The last overload is declared here.
>     export async function parse(
>                           ~~~~~
>         at https://deno.land/std@0.122.0/encoding/csv.ts:387:23
>

**Comment by kt3k** [comment]
We changed `parse` behavior at `v0.122.0` (PR: https://github.com/denoland/deno_std/pull/1724)

We change the return type of `parse()` depending on the given options, and also removed the `.parse` option (because `.parse` option can be rewritten as `.map(parse)` call to the result).

If you don't have time to update the script, please use the pinned version below <= v0.121.0. If you can update the script, please try the script like the below:

```ts
import { 
  parse as parseCsv,
} from "https://deno.land/std@0.122.0/encoding/csv.ts";

const content = (await parseCsv(await Deno.readTextFile("csvTestItems.csv"), { 
  skipFirstRow: true,
})).map((e: any) => { 
  return { item: e.Name, quantity: e.Quantity, pricePerItem: `$${e.Price.toLocaleString("en-US")}`, isExpensive: e.Price >= 3000 };
});

console.log(content);
```

**Comment by cfjello** [comment]
I will update - thanks for the quick reply!

**Comment by kt3k** [comment]
The informations about breaking changes are available at the release page of each version, for example, https://github.com/denoland/deno_std/releases/tag/0.122.0
