### ISSUE TITLE
node: process.exit should accept string as parameter

### ISSUE THREAD

**Issue by kt3k** [denoland/deno_std#1845]
Currently `process.exit` in std/node only accepts number or undefined as the argument, but it should also accept string type.

https://github.com/denoland/deno_std/blob/2b84a2be4a4d912ed65467962fd767a31e09e5f3/node/process.ts#L58

**Comment by Nautigsam** [comment]
I take this.

**Comment by bartlomieju** [comment]
@Nautigsam please do!
