### ISSUE TITLE
http(server): Infer discriminated addresses in ConnInfo (e.g. based on listen options)

### ISSUE THREAD

**Issue by jsejcksn** [denoland/deno_std#1884]
For an example and demonstration (and the motivation for the creation of this issue) see https://stackoverflow.com/a/71011282/438273

---

When using APIs from `deno.land/x/std/http/server.ts` which create a server, ergonomics and type-safety would be improved by providing a narrowed version of [`ConnInfo`](https://doc.deno.land/https://deno.land/std@0.125.0/http/server.ts/~/ConnInfo) (which is inferred from any supplied listen options that might influence it, else the default `transport` method).

As an example: in the case of using the [`serve`](https://doc.deno.land/https://deno.land/std@0.125.0/http/server.ts/~/serve) function — narrowing [`ConnInfo`](https://doc.deno.land/https://deno.land/std@0.125.0/http/server.ts/~/ConnInfo) (second parameter in the [`Handler`](https://doc.deno.land/https://deno.land/std@0.125.0/http/server.ts/~/Handler) callback parameter in [`serve`](https://doc.deno.land/https://deno.land/std@0.125.0/http/server.ts/~/serve)) to discriminate [`Deno.NetAddr`](https://doc.deno.land/deno/stable@v1.18.2/~/Deno.NetAddr) by default instead of [`Deno.Addr`](https://doc.deno.land/deno/stable@v1.18.2/~/Deno.Addr) (for both `connInfo.localAddr` and `connInfo.remoteAddr`) since [it only actually listens on TCP](https://deno.land/std@0.125.0/http/server.ts#L184).

Implementing this will prevent the need for every user to discriminate the union in order to access the network address information during request events.

This will require some new generic type parameters. (If minimizing breaking changes is important, default parameters could be included to preserve the current behavior of having the ability to use the existing types without generics.)

**Comment by jsejcksn** [comment]
[`Deno.TcpConn`](https://github.com/denoland/deno/pull/13714) just landed in unstable. Will that make this easier to implement?

**Comment by jsejcksn** [comment]
This issue persists as of [`std@0.193.0`](https://deno.land/std@0.193.0/http/server.ts?s=ConnInfo), but it appears that in Deno version `1.35.0`, this has been addressed in the `Deno.serve` API:

- [`Deno.serve`](https://deno.land/api@v1.35.0?s=Deno.serve)
- [`Deno.ServeHandler`](https://deno.land/api@v1.35.0?s=Deno.ServeHandler)
- [`Deno.ServeHandlerInfo`](https://deno.land/api@v1.35.0?s=Deno.ServeHandlerInfo)
- [`Deno.NetAddr`](https://deno.land/api@v1.35.0?s=Deno.NetAddr)

```ts
function serve(handler: ServeHandler): Server;
```

```ts
type ServeHandler = (
  request: Request,
  info: ServeHandlerInfo,
) => Response | Promise<Response>;
```

```ts
interface ServeHandlerInfo {
  remoteAddr: Deno.NetAddr;
}
```

```ts
interface NetAddr {
  transport: "tcp" | "udp";
  hostname: string;
  port: number;
}
```

...although it appears that `localAddr` is missing in the `ConnInfo` equivalent object: `ServeHandlerInfo`

**Comment by lino-levan** [comment]
Is `localAddr` useful to have? Do you have a usecase in mind?

**Comment by jsejcksn** [comment]
> Is `localAddr` useful to have? Do you have a usecase in mind?

@lino-levan I don't have one to present here, but it is the mechanism that allows for writing generic middleware which can use the server's address information. I think about deployments with dynamic address information that needs to be used (e.g. in logging).

**Comment by lino-levan** [comment]
Ah middleware is a good usecase. Is there an issue open on the deno core repo?

**Comment by jsejcksn** [comment]
> Ah middleware is a good usecase. Is there an issue open on the deno core repo?

@lino-levan I don't know — I haven't searched.

This issue is about `std`, and while I'm trying to stay on topic, I thought it was useful to include a bit of cross-context for all readers.

**Comment by kt3k** [comment]
Can this issue be closed now as we deprecated `serve` and `serveTls` in `std/http`?

**Comment by jsejcksn** [comment]
> Can this issue be closed now as we deprecated `serve` and `serveTls` in `std/http`?

@kt3k Yes, I think so.

**Comment by jsejcksn** [comment]
> Ah middleware is a good usecase. Is there an issue open on the deno core repo?

@lino-levan Did you open an issue about [this](https://github.com/denoland/deno_std/issues/1884#issuecomment-1632617048)?

**Comment by lino-levan** [comment]
I didn't, no.
