### ISSUE TITLE
Running "deno run -A _tools/format.js" from main branch is failing

### ISSUE THREAD

**Issue by brodriguez-eb** [denoland/deno_std#1889]
**Describe the bug**
Running "deno run -A _tools/format.js" from main branch is failing.

<img width="636" alt="Screen Shot 2022-02-07 at 7 04 55 PM" src="https://user-images.githubusercontent.com/83300615/152887103-51a61216-3185-4069-88ef-b9b4fc457a6c.png">

**Steps to Reproduce**
1. Clone main branch
2. Execute:
```
deno run -A _tools/format.js
```
**Expected behavior**
It should not fail.

**Environment**
- OS: MacOS 12.0.1
- deno version: 1.18.2 (release, x86_64-apple-darwin)
- std version: main

**Comment by crowlKats** [comment]
https://github.com/denoland/deno_std/blob/d0ffe846446e7ffa32c643e22af3fb31b334381d/_tools/format.js#L1
The command should be run with `--no-check`
