### ISSUE TITLE
Add fs.walk

### ISSUE THREAD

**Issue by hayd** [denoland/deno_std#189]
A basic implementation:
```ts
import { FileInfo, readDirSync } from "deno";

function *walk(dir: string): IterableIterator<FileInfo> {
  const ls = readDirSync(dir);
  for (const f of ls) {
    if (f.isSymlink()) {
      // TODO add followlinks option
    } else if (f.isFile()) {
      yield f;
    } else {
      yield *walk(f.path);
    }
  }
}
```

Should this go in fs/walk.ts or should there be some other directory structure?
The current org of fs is a little strange.

Also, what other functions ought to be in fs? [glob](https://github.com/hayd/deno-globrex)?

**Comment by ry** [comment]
Yes please.
We have something that can be adapted easily:
https://github.com/denoland/deno/blob/1e5e091cb074896c7550b1b6f802582f12629048/tools/util.ts#L10-L41

**Comment by hayd** [comment]
I'll do this. I prefer the IterableIterator<FileInfo> return type, but can support all those options.

**Comment by ry** [comment]
@hayd Thanks! It'd be great to also get a follow up commit to make `deno/tools/util.ts` use the new `fs.walk()`.

**Comment by hayd** [comment]
@ry `deno/tools/util.ts` doesn't exist in master!
(Note: All functions are unnecessary in it, with walk+execPath.)
