### ISSUE TITLE
compat: some specific npm modules can't be installed with yarn

### ISSUE THREAD

**Issue by kt3k** [denoland/deno_std#1896]
`nopt@1.0.10` can't be installed with yarn in node compat mode.

```
$ yarn add nopt@1  
Not implemented: process.on("unhandledRejection")
Not implemented: process.on("rejectionHandled")
yarn add v1.22.17
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/nopt/-/nopt-1.0.10.tgz: incorrect header check".
```

`nopt@latest` doesn't have this problem

- `mongo@0.1.0` (not mongodb) has the same issue

**Comment by lino-levan** [comment]
Should this issue still be open?

> nopt@1.0.10 can't be installed with yarn in node compat mode.

Maybe I didn't understand node compatibility mode (when it still existed as `--compat`) but I don't even know what this means.

**Comment by kt3k** [comment]
This is no longer relevant. Thanks for the ping. @lino-levan 

Also nopt seems working fine with `npm:` specifier. The below works:

```ts
import * as nopt from "npm:nopt@1.0.10";
console.log(nopt);
```
