### ISSUE TITLE
feature(flags): Add generic type to `parse()`

### ISSUE THREAD

**Issue by 4513ECHO** [denoland/deno_std#1898]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

The `parse()` function return `Args` type. This interface's keys types except `-` are `any` type. So, I suggent using generic type. Like this:

```typescript
export function parse<T extends Args>(
  args: string[],
  {
    "--": doubleDash = false,
    alias = {},
    boolean = false,
    default: defaults = {},
    stopEarly = false,
    string = [],
    unknown = (i: string): unknown => i,
  }: ArgParsingOptions = {},
): T
```

**Describe alternatives you've considered**

**Comment by c4spar** [comment]
i can work on it. i have already a partialy working virsion.

**Comment by bartlomieju** [comment]
@c4spar sounds good 👍 looking forward to PR
