### ISSUE TITLE
node: providing timers in commonjs wrapper conflicts with the declaration of timers in modules

### ISSUE THREAD

**Issue by kt3k** [denoland/deno_std#1901]
If an npm module has the following line:

```
const { setInterval } = require('node:timers');
```

This throws a SyntaxError: `error: Uncaught SyntaxError: Identifier 'setInterval' has already been declared`

**Comment by kt3k** [comment]
This happens with requiring `discord.js@13` https://github.com/discordjs/discord.js/blob/988a51b7641f8b33cc9387664605ddc02134859d/src/rest/RESTManager.js#L3

**Comment by bartlomieju** [comment]
> Maybe we should surround the commonjs modules with 2 wrapper functions?
> 
> ```js
> (function (exports, require, module, __filename, setTimeout, clearTimeout, setInterval, clearInterval) {
>   (function (exports, require, module, __filename, __dirname) {
>     // ... cjs module source code
>   })(exports, require, module, __filename, __dirname);
> });
> ```

This will completely break the source map support
