### ISSUE TITLE
TS2578 [ERROR]: Unused '@ts-expect-error' directive.

### ISSUE THREAD

**Issue by idanran** [denoland/deno_std#1908]
**Describe the bug**
TS2578 [ERROR]: Unused '@ts-expect-error' directive.
      // @ts-expect-error Using `call` seem to be interfering with the overload for write
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://deno.land/std@0.122.0/node/net.ts:504:7

**Steps to Reproduce**
1. Create a file with the contents ...
2. Create a script with the contents ...
3. Execute the command ...
4. See error

**Expected behavior**
No error reporting
<!-- A clear and concise description of what you expected to happen. -->

**Environment**

<!-- please complete the following information -->

- OS: Windows11
- deno version: 1.18.2
- std version: 0.125.0

**Comment by bartlomieju** [comment]
This error comes from `std@0.122.0/node` so it's probably coming from one of your dependencies. Try upgrading it.

**Comment by idanran** [comment]
> This error comes from so it's probably coming from one of your dependencies. Try upgrading it.`std@0.122.0/node`

This may be https://deno.land/std/node/http.ts import.

**Comment by bartlomieju** [comment]
> > This error comes from so it's probably coming from one of your dependencies. Try upgrading it.`std@0.122.0/node`
> 
> This may be https://deno.land/std/node/http.ts import.

All `std` code always uses a single version (ie. it's not possible that `std@0.125.0` uses code from `std@0.122.0`). Make sure you always use pinned version of your imports, otherwise you might have cached sources for previous versions.

**Comment by idanran** [comment]
> > > 此错误来自，因此它可能来自您的某个依赖项。尝试升级它。`std@0.122.0/node`
> > 
> > 
> > 这可能是[导入 https://deno.land/std/node/http.ts](https://deno.land/std/node/http.ts)。
> 
> 所有代码始终使用单个版本（即不可能使用 来自 的代码）。请确保始终使用固定版本的导入，否则你可能具有以前版本的缓存源。`std``std@0.125.0``std@0.122.0`



> > > This error comes from so it's probably coming from one of your dependencies. Try upgrading it.`std@0.122.0/node`
> > 
> > 
> > This may be https://deno.land/std/node/http.ts import.
> 
> All `std` code always uses a single version (ie. it's not possible that `std@0.125.0` uses code from `std@0.122.0`). Make sure you always use pinned version of your imports, otherwise you might have cached sources for previous versions.

import { Agent } from 'https://deno.land/std@0.125.0/node/http.ts'

**Comment by idanran** [comment]
> > > This error comes from so it's probably coming from one of your dependencies. Try upgrading it.`std@0.122.0/node`
> > 
> > 
> > This may be https://deno.land/std/node/http.ts import.
> 
> All code always uses a single version (ie. it's not possible that uses code from ). Make sure you always use pinned version of your imports, otherwise you might have cached sources for previous versions.`std``std@0.125.0``std@0.122.0`

I have import it like this, and the problem still exists.

**Comment by bartlomieju** [comment]
> > > > This error comes from so it's probably coming from one of your dependencies. Try upgrading it.`std@0.122.0/node`
> > > 
> > > 
> > > This may be https://deno.land/std/node/http.ts import.
> > 
> > 
> > All code always uses a single version (ie. it's not possible that uses code from ). Make sure you always use pinned version of your imports, otherwise you might have cached sources for previous versions.`` std``std@0.125.0``std@0.122.0 ``
> 
> I have import it like this, and the problem still exists.

Correct, you are using unversioned import, most likely you used it first when `deno_std` was at version 0.122.0 and now it is cached with this version. Change the import to use latest version or use `--reload` flag to pull the latest version (but you'll be subject to the same problem in the future).

**Comment by bartlomieju** [comment]
No, `@latest` is not supported. Use explicitly pinned version.

**Comment by idanran** [comment]
> No, `@latest` is not supported. Use explicitly pinned version.

I executed "--reload" and the version changed to 0.125.0, but the problem still exists.

**Comment by bartlomieju** [comment]
Do you use a custom `tsconfig.json`? I can execute this import statement just fine on latest Deno:
```
// test.ts
import { Agent } from 'https://deno.land/std@0.125.0/node/http.ts'
```

```
❯ deno run test.ts
Check file:///Users/ib/dev/deno/test.ts

```

**Comment by idanran** [comment]
> Do you use a custom `tsconfig.json`? I can execute this import statement just fine on latest Deno:
> ```
> // test.ts
> import { Agent } from 'https://deno.land/std@0.125.0/node/http.ts'
> ```
> 
> ```
> ❯ deno run test.ts
> Check file:///Users/ib/dev/deno/test.ts
> 
> ```

I modified tsconfig.json to turn off strict mode. The component reporting the error could also have been import by another component.

**Comment by idanran** [comment]
> Then you can use `--no-check=remote` to skip type checking remote dependencies. I'm going to close this issue as it is not a problem with `deno_std`.
> 
> If you need more help, I suggest to join Deno's Discord and ask in #help channel - you should be able to get help faster.

Thanks
