### ISSUE TITLE
TS2300 [ERROR]: Duplicate identifier 'Buffer'.

### ISSUE THREAD

**Issue by idanran** [denoland/deno_std#1913]
**Describe the bug**
TS2300 [ERROR]: Duplicate identifier 'Buffer'.
  type Buffer = bufferModule;
       ~~~~~~
    at https://deno.land/std@0.125.0/node/global.ts:26:8

    'Buffer' was also declared here.
    declare class Buffer extends Uint8Array {
                  ~~~~~~
        at https://cdn.esm.sh/v66/node.ns.d.ts:16:15

**Steps to Reproduce**

**Expected behavior**

**Environment**

- OS: Windows11
- deno version: 1.18.2
- std version: 0.125.0

**Comment by lucacasonato** [comment]
This looks like a bug with esm.sh, not with `std`.
