### ISSUE TITLE
TS2769 [ERROR]: No overload matches this call.

### ISSUE THREAD

**Issue by idanran** [denoland/deno_std#1915]
**Describe the bug**
TS2769 [ERROR]: No overload matches this call.
  Overload 1 of 2, '(data: Uint8Array, encoding: TextEncodings): string', gave the following error.
    Argument of type 'Encodings' is not assignable to parameter of type 'TextEncodings'.
      Type '"binary"' is not assignable to type 'TextEncodings'.  Overload 2 of 2, '(data: Uint8Array, encoding: "binary"): Buffer', gave the following error.
    Argument of type 'Encodings' is not assignable to parameter of type '"binary"'.
      Type '"ascii"' is not assignable to type '"binary"'.
  const buffer = maybeDecode(data, encoding);
                                   ~~~~~~~~
    at https://deno.land/std@0.125.0/node/_fs/_fs_readFile.ts:95:36

**Steps to Reproduce**

<!--
Example
1. Create a file with the contents ...
2. Create a script with the contents ...
3. Execute the command ...
4. See error
-->

**Expected behavior**

<!-- A clear and concise description of what you expected to happen. -->

**Environment**

<!-- please complete the following information -->

- OS: Windows11
- deno version: 1.18.2
- std version: 0.125.0

**Comment by iuioiua** [comment]
Hi @idanran, are you still having this issue? If so, could you please share the exact snippet?

**Comment by idanran** [comment]
> Hi @idanran, are you still having this issue? If so, could you please share the exact snippet?

I don't have any, thank you!
