### ISSUE TITLE
TS2709 [ERROR]: Cannot use namespace 'Server' as a type.

### ISSUE THREAD

**Issue by idanran** [denoland/deno_std#1920]
**Describe the bug**
```
TS2709 [ERROR]: Cannot use namespace 'Server' as a type.
    _httpServer?: Server
```

**Steps to Reproduce**
```
import { Server, createServer, IncomingMessageForServer as IncomingMessage } from 'https://deno.land/std@0.125.0/node/http.ts'
import { App, Context, Schema } from 'https://esm.sh/@koishijs/core'
import WebSocket from 'https://esm.sh/ws'

declare module 'https://esm.sh/@koishijs/core' {
  interface App {
    _httpServer?: Server
    _wsServer?: WebSocket.Server
  }

  namespace App {
    interface Config extends Config.Network {}

    namespace Config {
      interface Static {
        Network: Schema<Network>
      }

      interface Network {
        host?: string
        port?: number
        selfUrl?: string
      }
    }
  }
}
```

**Expected behavior**

**Environment**

- OS: Windows11
- deno version: 1.18.2
- std version: 0.125.0

**Comment by iuioiua** [comment]
Hi @idanran, I just successfully ran your snippet without issue.
```
deno 1.24.3 (release, aarch64-apple-darwin)
v8 10.4.132.20
typescript 4.7.4
```

**Comment by lts20050703** [comment]
Hey @idanran please check what you're trying to import
```
Uncaught SyntaxError: The requested module '/v92/@satorijs/core@1.0.11/deno/core.js' does not provide an export named 'Message'
    at async <anonymous>:2:37
```
<details><summary>Full output</summary>
<pre>
PowerShell 7.3.0-preview.7
PS C:\Users\lts20> deno
Deno 1.24.2
exit using ctrl+d or close()
> import { Server, createServer, IncomingMessageForServer as IncomingMessage } from 'https://deno.land/std@0.125.0/node/http.ts'
Download https://deno.land/std@0.125.0/node/http.ts
Download https://deno.land/std@0.125.0/_deno_unstable.ts
Download https://deno.land/std@0.125.0/http/http_status.ts
Download https://deno.land/std@0.125.0/node/_core.ts
Download https://deno.land/std@0.125.0/node/_http_agent.js
Download https://deno.land/std@0.125.0/node/_http_outgoing.ts
Download https://deno.land/std@0.125.0/node/_next_tick.ts
Download https://deno.land/std@0.125.0/node/buffer.ts
Download https://deno.land/std@0.125.0/node/events.ts
Download https://deno.land/std@0.125.0/node/internal/errors.ts
Download https://deno.land/std@0.125.0/node/internal/url.ts
Download https://deno.land/std@0.125.0/node/internal/validators.js
Download https://deno.land/std@0.125.0/node/net.ts
Download https://deno.land/std@0.125.0/node/stream.ts
Download https://deno.land/std@0.125.0/node/_events.js
Download https://deno.land/std@0.125.0/node/_events.d.ts
Download https://deno.land/std@0.125.0/node/_stream.js
Download https://deno.land/std@0.125.0/node/_stream.d.ts
Download https://deno.land/std@0.125.0/node/_buffer.js
Download https://deno.land/std@0.125.0/node/_buffer.d.ts
Download https://deno.land/std@0.125.0/node/_fixed_queue.ts
Download https://deno.land/std@0.125.0/node/_process/exiting.ts
Download https://deno.land/std@0.125.0/node/internal/error_codes.ts
Download https://deno.land/std@0.125.0/node/internal/hide_stack_frames.ts
Download https://deno.land/std@0.125.0/node/internal/util/types.ts
Download https://deno.land/std@0.125.0/node/url.ts
Download https://deno.land/std@0.125.0/node/async_hooks.ts
Download https://deno.land/std@0.125.0/node/internal/async_hooks.ts
Download https://deno.land/std@0.125.0/node/internal/util.js
Download https://deno.land/std@0.125.0/node/internal/util/debuglog.ts
Download https://deno.land/std@0.125.0/node/internal/streams/_utils.ts
Download https://deno.land/std@0.125.0/node/internal/streams/add-abort-signal.js
Download https://deno.land/std@0.125.0/node/internal/streams/compose.js
Download https://deno.land/std@0.125.0/node/internal/streams/destroy.js
Download https://deno.land/std@0.125.0/node/internal/streams/duplex.js
Download https://deno.land/std@0.125.0/node/internal/streams/end-of-stream.js
Download https://deno.land/std@0.125.0/node/internal/streams/legacy.js
Download https://deno.land/std@0.125.0/node/internal/streams/passthrough.js
Download https://deno.land/std@0.125.0/node/internal/streams/pipeline.js
Download https://deno.land/std@0.125.0/node/internal/streams/readable.js
Download https://deno.land/std@0.125.0/node/internal/streams/transform.js
Download https://deno.land/std@0.125.0/node/internal/streams/utils.js
Download https://deno.land/std@0.125.0/node/internal/streams/writable.js
Download https://deno.land/std@0.125.0/node/stream/promises.js
Download https://deno.land/std@0.125.0/node/_http_common.ts
Download https://deno.land/std@0.125.0/node/internal/assert.js
Download https://deno.land/std@0.125.0/node/internal/http.ts
Download https://deno.land/std@0.125.0/node/internal/streams/state.js
Download https://deno.land/std@0.125.0/_util/assert.ts
Download https://deno.land/std@0.125.0/_util/os.ts
Download https://deno.land/std@0.125.0/node/_async_hooks.ts
Download https://deno.land/std@0.125.0/node/_global.d.ts
Download https://deno.land/std@0.125.0/node/_util/_debuglog.ts
Download https://deno.land/std@0.125.0/node/_utils.ts
Download https://deno.land/std@0.125.0/node/dns.ts
Download https://deno.land/std@0.125.0/node/internal/dtrace.ts
Download https://deno.land/std@0.125.0/node/internal/net.ts
Download https://deno.land/std@0.125.0/node/internal/stream_base_commons.ts
Download https://deno.land/std@0.125.0/node/internal/timers.js
Download https://deno.land/std@0.125.0/node/internal_binding/pipe_wrap.ts
Download https://deno.land/std@0.125.0/node/internal_binding/stream_wrap.ts
Download https://deno.land/std@0.125.0/node/internal_binding/tcp_wrap.ts
Download https://deno.land/std@0.125.0/node/internal_binding/util.ts
Download https://deno.land/std@0.125.0/node/internal_binding/uv.ts
Download https://deno.land/std@0.125.0/node/internal/util/inspect.js
Download https://deno.land/std@0.125.0/node/internal_binding/types.ts
Download https://deno.land/std@0.125.0/node/_process/process.ts
Download https://deno.land/std@0.125.0/node/_process/stdio.js
Download https://deno.land/std@0.125.0/encoding/base64.ts
Download https://deno.land/std@0.125.0/encoding/base64url.ts
Download https://deno.land/std@0.125.0/node/internal/buffer.js
Download https://deno.land/std@0.125.0/node/internal_binding/_utils.ts
Download https://deno.land/std@0.125.0/node/internal_binding/buffer.ts
Download https://deno.land/std@0.125.0/node/internal_binding/async_wrap.ts
Download https://deno.land/std@0.125.0/node/internal/blob.js
Download https://deno.land/std@0.125.0/node/internal/streams/from.js
Download https://deno.land/std@0.125.0/node/timers.ts
Download https://deno.land/std@0.125.0/fmt/printf.ts
Download https://deno.land/std@0.125.0/node/internal_binding/symbols.ts
Download https://deno.land/std@0.125.0/async/mod.ts
Download https://deno.land/std@0.125.0/streams/conversion.ts
Download https://deno.land/std@0.125.0/testing/asserts.ts
Download https://deno.land/std@0.125.0/node/string_decoder.ts
Download https://deno.land/std@0.125.0/node/internal/streams/buffer_list.js
Download https://deno.land/std@0.125.0/node/internal_binding/connection_wrap.ts
Download https://deno.land/std@0.125.0/node/internal_binding/node_file.ts
Download https://deno.land/std@0.125.0/io/util.ts
Download https://deno.land/std@0.125.0/node/internal_binding/handle_wrap.ts
Download https://deno.land/std@0.125.0/node/internal_binding/_libuv_winerror.ts
Download https://deno.land/std@0.125.0/node/internal_binding/constants.ts
Download https://deno.land/std@0.125.0/path/_constants.ts
Download https://deno.land/std@0.125.0/node/internal/idna.ts
Download https://deno.land/std@0.125.0/node/internal/querystring.ts
Download https://deno.land/std@0.125.0/node/path.ts
Download https://deno.land/std@0.125.0/node/querystring.ts
Download https://deno.land/std@0.125.0/node/process.ts
Download https://deno.land/std@0.125.0/node/util.ts
Download https://deno.land/std@0.125.0/node/_dns/_utils.ts
Download https://deno.land/std@0.125.0/node/internal_binding/cares_wrap.ts
Download https://deno.land/std@0.125.0/bytes/mod.ts
Download https://deno.land/std@0.125.0/node/internal_binding/_node.ts
Download https://deno.land/std@0.125.0/async/deadline.ts
Download https://deno.land/std@0.125.0/async/debounce.ts
Download https://deno.land/std@0.125.0/async/deferred.ts
Download https://deno.land/std@0.125.0/async/delay.ts
Download https://deno.land/std@0.125.0/async/mux_async_iterator.ts
Download https://deno.land/std@0.125.0/async/pool.ts
Download https://deno.land/std@0.125.0/async/tee.ts
Download https://deno.land/std@0.125.0/io/buffer.ts
Download https://deno.land/std@0.125.0/io/files.ts
Download https://deno.land/std@0.125.0/io/types.d.ts
Download https://deno.land/std@0.125.0/path/mod.ts
Download https://deno.land/std@0.125.0/node/internal_binding/_winerror.ts
Download https://deno.land/std@0.125.0/node/internal_binding/string_decoder.ts
Download https://deno.land/std@0.125.0/node/_util/_util_callbackify.ts
Download https://deno.land/std@0.125.0/node/internal/util/comparisons.ts
Download https://deno.land/std@0.125.0/node/util/types.js
Download https://deno.land/std@0.125.0/bytes/equals.ts
Download https://deno.land/std@0.125.0/node/_options.ts
Download https://deno.land/std@0.125.0/fmt/colors.ts
Download https://deno.land/std@0.125.0/testing/_diff.ts
Download https://deno.land/std@0.125.0/node/_process/streams.js
Download https://deno.land/std@0.125.0/node/internal_binding/mod.ts
Download https://deno.land/std@0.125.0/path/_interface.ts
Download https://deno.land/std@0.125.0/path/common.ts
Download https://deno.land/std@0.125.0/path/glob.ts
Download https://deno.land/std@0.125.0/path/posix.ts
Download https://deno.land/std@0.125.0/path/separator.ts
Download https://deno.land/std@0.125.0/path/win32.ts
Download https://deno.land/std@0.125.0/bytes/bytes_list.ts
Download https://deno.land/std@0.125.0/node/internal_binding/node_options.ts
Download https://deno.land/std@0.125.0/node/internal_binding/config.ts
Download https://deno.land/std@0.125.0/node/internal_binding/contextify.ts
Download https://deno.land/std@0.125.0/node/internal_binding/credentials.ts
Download https://deno.land/std@0.125.0/node/internal_binding/crypto.ts
Download https://deno.land/std@0.125.0/node/internal_binding/errors.ts
Download https://deno.land/std@0.125.0/node/internal_binding/fs.ts
Download https://deno.land/std@0.125.0/node/internal_binding/fs_dir.ts
Download https://deno.land/std@0.125.0/node/internal_binding/fs_event_wrap.ts
Download https://deno.land/std@0.125.0/node/internal_binding/heap_utils.ts
Download https://deno.land/std@0.125.0/node/internal_binding/http_parser.ts
Download https://deno.land/std@0.125.0/node/internal_binding/icu.ts
Download https://deno.land/std@0.125.0/node/internal_binding/inspector.ts
Download https://deno.land/std@0.125.0/node/internal_binding/js_stream.ts
Download https://deno.land/std@0.125.0/node/internal_binding/messaging.ts
Download https://deno.land/std@0.125.0/node/internal_binding/module_wrap.ts
Download https://deno.land/std@0.125.0/node/internal_binding/native_module.ts
Download https://deno.land/std@0.125.0/node/internal_binding/natives.ts
Download https://deno.land/std@0.125.0/node/internal_binding/options.ts
Download https://deno.land/std@0.125.0/node/internal_binding/os.ts
Download https://deno.land/std@0.125.0/node/internal_binding/performance.ts
Download https://deno.land/std@0.125.0/node/internal_binding/process_methods.ts
Download https://deno.land/std@0.125.0/node/internal_binding/report.ts
Download https://deno.land/std@0.125.0/node/internal_binding/serdes.ts
Download https://deno.land/std@0.125.0/node/internal_binding/signal_wrap.ts
Download https://deno.land/std@0.125.0/node/internal_binding/spawn_sync.ts
Download https://deno.land/std@0.125.0/node/internal_binding/task_queue.ts
Download https://deno.land/std@0.125.0/node/internal_binding/timers.ts
Download https://deno.land/std@0.125.0/node/internal_binding/tls_wrap.ts
Download https://deno.land/std@0.125.0/node/internal_binding/trace_events.ts
Download https://deno.land/std@0.125.0/node/internal_binding/tty_wrap.ts
Download https://deno.land/std@0.125.0/node/internal_binding/udp_wrap.ts
Download https://deno.land/std@0.125.0/node/internal_binding/url.ts
Download https://deno.land/std@0.125.0/node/internal_binding/v8.ts
Download https://deno.land/std@0.125.0/node/internal_binding/worker.ts
Download https://deno.land/std@0.125.0/node/internal_binding/zlib.ts
Download https://deno.land/std@0.125.0/flags/mod.ts
Download https://deno.land/std@0.125.0/path/_util.ts
undefined
> import { App, Context, Schema } from 'https://esm.sh/@koishijs/core'
Download https://esm.sh/@koishijs/core
Download https://esm.sh/@koishijs/core@4.8.6
Download https://esm.sh/v92/@koishijs/core@4.8.6/deno/core.js
Download https://esm.sh/v92/@koishijs/core@4.8.6/lib/index.d.ts
Download https://esm.sh/v92/@koishijs/utils@6.1.0/deno/utils.js
Download https://esm.sh/v92/@satorijs/core@1.0.11/deno/core.js
Download https://esm.sh/v92/cordis@2.1.1/deno/cordis.js
Download https://esm.sh/v92/minato@1.2.4/deno/minato.js
Download https://esm.sh/v92/cosmokit@1.2.1/deno/cosmokit.js
Download https://esm.sh/v92/ns-require@1.1.4/deno/ns-require.js
Download https://esm.sh/v92/@satorijs/message@1.0.1/deno/message.js
Download https://esm.sh/v92/inaba@1.1.1/deno/inaba.js
Download https://esm.sh/v92/reggol@1.1.0/deno/reggol.js
Download https://esm.sh/v92/schemastery@3.5.3/deno/schemastery.js
Download https://esm.sh/v92/@koishijs/core@4.8.6/package.json
Download https://esm.sh/v92/@koishijs/utils@6.1.0/lib/index.d.ts
Download https://esm.sh/v92/cordis@2.1.1/lib/index.d.ts
Download https://esm.sh/v92/minato@1.2.4/lib/index.d.ts
Download https://esm.sh/v92/cosmokit@1.2.1/lib/index.d.ts
Download https://esm.sh/v92/@types/mocha@9.1.1/index.d.ts
Download https://esm.sh/v92/inaba@1.1.1/lib/index.d.ts
Download https://esm.sh/v92/reggol@1.1.0/index.d.ts
Download https://esm.sh/v92/schemastery@3.5.3/lib/index.d.ts
Download https://esm.sh/v92/supports-color@8.1.1/deno/supports-color.js
Uncaught SyntaxError: The requested module '/v92/@satorijs/core@1.0.11/deno/core.js' does not provide an export named 'Message'
    at async <anonymous>:2:37
> import WebSocket from 'https://esm.sh/ws'
Download https://esm.sh/ws
Download https://esm.sh/ws@8.8.1
Download https://esm.sh/v91/ws@8.8.1/deno/ws.js
Download https://esm.sh/v91/@types/ws@^8/index.d.ts
Download https://esm.sh/v91/@types/ws@8.5.3/index.d.ts
Download https://esm.sh/v91/@types/node@16.11.45/zlib.d.ts
undefined
>
undefined
> declare module 'https://esm.sh/@koishijs/core' {
interface App {
_httpServer?: Server
_wsServer?: WebSocket.Server
}

namespace App {
interface Config extends Config.Network {}

namespace Config {
interface Static {
Network: Schema<Network>
}

interface Network {
host?: string
port?: number
selfUrl?: string
}
}
}
}
undefined
</pre>
</details>

**Comment by idanran** [comment]
@iuioiua @lts20050703 Thanks!
