### ISSUE TITLE
[fs] Uncaught (in promise) NotFound (os error 2), stat '..\plugin'

### ISSUE THREAD

**Issue by idanran** [denoland/deno_std#1930]
**Describe the bug**
`[fs] Uncaught (in promise) NotFound (os error 2), stat '..\plugin'`

**Steps to Reproduce**
site/
├── plugin
└──└── test.js
└── lib
└──└── core.js

lib/core.js: 
```
for await (const entry of walk("../plugin")) {
  console.log(entry.path);
}
```

**Expected behavior**

**Environment**

- OS: Windows11
- deno version: 1.18.2
- std version: 0.125.0

**Comment by lucacasonato** [comment]
Can you also log `Deno.cwd()` before you do the walk? Is your working directory `site/` or `site/lib/core.js`? File paths are relative to your working directory, not the JS file you call an API from.

**Comment by idanran** [comment]
> 在散步之前，您也可以记录下来吗？您的工作目录是还是 ？文件路径是相对于工作目录的，而不是相对于从中调用 API 的 JS 文件。`Deno.cwd()``site/``site/lib/core.js`

Thanks, `Deno.cwd()` solved my problem.
