### ISSUE TITLE
Avoid top-level-await in dotenv/load.ts

### ISSUE THREAD

**Issue by ayame113** [denoland/deno_std#1957]
Since the top level await is in `dotenv/load.ts`, `load.ts` runs asynchronously. Therefore, another file that is imported cannot use the environment variables that dotenv loads. (See example.)

```
# .env
CONFIG="hello"
```

```ts
// main.ts
import "https://deno.land/std@0.127.0/dotenv/load.ts";
import "./b.ts";
```

```ts
// b.ts
console.log(Deno.env.get("CONFIG")); //=> undefined (!?)
```

This is inconvenient when we want to manage environment variables used in external modules with dotenv. I think we need to replace the function used in load.ts with a synchronous function.

I'm the one who introduced this to dotenv for deno deploy compatibility (https://github.com/pietvanzoen/deno-dotenv/pull/55), but now I think this choice was wrong. For deno deploy compatibility, I think you should use try-catch and ignore `readFileSync is not a function`.
https://github.com/denoland/deno_std/blob/3cb1f799801fe0470e4d87ea14e70800ba06bfd3/dotenv/mod.ts#L106-L113

**Comment by kt3k** [comment]
Sounds like a good idea. Let's change it to readFileSync.

> For deno deploy compatibility, I think you should use try-catch and ignore readFileSync is not a function.

How about doing `typeof` check for this, something like `if (typeof Deno.readFileSync == "function")`? I think this is even type safe for Deno Deploy environment.

**Comment by bartlomieju** [comment]
Why not provide both sync and async version?

**Comment by kt3k** [comment]
The main module (`dotenv/mod.ts`) already provides `config` and `configSync`. I think what @ayame113 suggests is that we should use sync API in side effect version of API (`import "https://deno.land/std@0.127.0/dotenv/load.ts"`)
