### ISSUE TITLE
Standard Library 'fmt' returning "Bad Gateway" 

### ISSUE THREAD

**Issue by wiremoons** [denoland/deno_std#1969]
**Issue**

When attempting to view the 'fmt' documentation here:  https://deno.land/std@0.127.0/fmt

The following error is returned:
```
502: Bad Gateway (DEPLOYMENT_FAILED)

The deployment failed while serving the request.
```

**Steps to Reproduce**

Visit the URL: https://deno.land/std@0.127.0/fmt

**Expected behavior**

Be able to view the documentation for `fmt`  in the Deno Standard Library.

**Environment**

- OS: [e.g. Ubuntu 20.04, MacOS 11]
```
ProductName:	macOS
ProductVersion:	12.2.1
BuildVersion:	21D62
```
- deno version:
```
deno 1.19.1 (release, aarch64-apple-darwin)
v8 9.9.115.7
typescript 4.5.2
```
- std version:
```
std@0.127.0
```

**Comment by zhong-yiyu** [comment]
In addition, not just 0.127.0 version has this issue, https://deno.land/std@0.126.0/fmt and multiple previous versions all return `502: Bad Gateway (DEPLOYMENT_FAILED)`.

**Comment by crowlKats** [comment]
Yes, in the linked issue (denoland/dotland#2031) investigation has revealed that its an issue with an upstream module we added in the rewrite

**Comment by kitsonk** [comment]
The root issue is denoland/dotland#2031 and needs to be resolved there, so closing here.
