### ISSUE TITLE
Speed up testing and benching

### ISSUE THREAD

**Issue by chiefbiiko** [denoland/deno_std#198]
Currently `testing` and `benching` do `await`s in a loop in `runTests`/`runBenchmarks` 🐌
I got a `Promise.all` refactor for `benching`. Think the same should be done for `testing`.
Does not require any API changes.

**Comment by ry** [comment]
I don't think our tests in core are such that they can be run in parallel... It would be cool to have this as an option tho.

**Comment by zekth** [comment]
I think this can be closed due to all the evolutions done to Bench and testing. No?
