### ISSUE TITLE
`createRequire` `FsFile` errors starting in 0.127.0

### ISSUE THREAD

**Issue by SheetJSDev** [denoland/deno_std#1992]
**Describe the bug**

error: TS2551 [ERROR]: Property 'FsFile' does not exist on type 'typeof Deno'. Did you mean 'File'?

**Steps to Reproduce**

```bash
$ for std in 0.12{6..8}.0; do echo "$std"; deno eval 'import { createRequire } from "https://deno.land/std@'$std'/node/module.ts";'; done
```

**Expected behavior**

No errors

**Environment**

- OS: MacOS Monterey
- deno version: 1.18.2 (release, x86_64-apple-darwin)
- std version: affects 0.127.0 and 0.128.0

**Comment by crowlKats** [comment]
You need to update your deno, the latest version is 1.19.2

**Comment by SheetJSDev** [comment]
Updating deno resolved the issue.
