### ISSUE TITLE
Does Deno need a QueryString module?

### ISSUE THREAD

**Issue by jbreckmckye** [denoland/deno_std#200]
It's common in Node and JavaScript applications to store simple state in URL query strings. But manually parsing and serialising query strings is a pain. In Node-land, packages like e.g. [qs](https://github.com/ljharb/qs) are very popular.

My question:

1. Is this functionality worth bringing into a Deno standard library?
2. If so, what behaviours, capabilities and interface(s) would be most desirable and ergonomic?

**Comment by bartlomieju** [comment]
Deno has built in [`URLSearchParams`](https://github.com/denoland/deno/blob/master/js/url_search_params.ts). I used it to parse DSN and worked pretty well.

**Comment by jbreckmckye** [comment]
Ah, didn't realise it had URLSearchParams! That's great news.
