### ISSUE TITLE
Return 404 from serveFile when resource is not found

### ISSUE THREAD

**Issue by cknight** [denoland/deno_std#2005]
When using the [serveFile](https://deno.land/std/http/file_server.ts) function like so:

```typescript
import { serve } from "https://deno.land/std@0.128.0/http/server.ts";
import { serveFile } from "https://deno.land/std@0.128.0/http/file_server.ts";

serve(async (req: Request) => await serveFile(req, `${Deno.cwd()}` + new URL(req.url).pathname));
```
this successfully returns content requested.  However, if the requested resource doesn't exist, the `serveFile` code returns 500 internal server error.  Instead it would ideally return a 404.

As an added thought, accepting a custom response handler for 404 and 500 responses would be nice.

**Comment by iuioiua** [comment]
This throws `Deno.errors.NotFound`, which I'd expect to be the intended behaviour, leaving the error handling to be left up to the request handler. For example:
```ts
serve(async (req: Request) => {
  try {
    return await serveFile(req, `${Deno.cwd()}` + new URL(req.url).pathname);
  } catch (error) {
    if (error instanceof Deno.errors.NotFound) {
      return new Response(null, { status: 404 });
    }
    return new Response(null, { status: 500 });
  }
});
```
Perhaps, a small explainer in the docs might help clarify not found behaviour. @bartlomieju, do you agree? If so, I'll do it.

**Comment by bartlomieju** [comment]
Yes, that makes sense

**Comment by kt3k** [comment]
I discussed this with @timonson a while before and we observed that `serveFile` already returns error `Response` object for some irregular cases (e.g. `416 Range Not Satisfiable`, `304 Not Modified`). So I think the current behavior is not consistent about error handling.

I think the special handling of the case `if (error instanceof Deno.errors.NotFound)` in `serve` is wrong and we should make this return 404 `Response` object.

What do you think? @iuioiua @bartlomieju

**Comment by iuioiua** [comment]
Yeah, I agree.
