### ISSUE TITLE
Downloading https://deno.land/x/util/deferred.ts... NOT FOUND

### ISSUE THREAD

**Issue by linweiwei123** [denoland/deno_std#201]
Downloading https://deno.land/x/util/deferred.ts... NOT FOUND

**Comment by zhmushan** [comment]
https://github.com/denoland/registry/pull/54

**Comment by syumai** [comment]
@linweiwei123 https://deno.land/x/std/http/server.ts
Can be used for this purpose as a workaround.

**Comment by keroxp** [comment]
@linweiwei123 Thank you for report. Currently modules under https://deno.land/x/ was fully managed by denoland/registry. And While reviewing #188, we haven't got unified opinion about having `util` module set on deno_std. So `util` namespace under `x` won't be registered for a while. Use `//x/std/util/deferred.ts` instead. But that url may be gone after discussion.

**Comment by bartlomieju** [comment]
I think this is stale now. Can we close it @ry?

**Comment by ry** [comment]
Thanks
