### ISSUE TITLE
compat: child_process.execFileSync

### ISSUE THREAD

**Issue by kt3k** [denoland/deno_std#2011]
part of #2010

We need to shim `child_process.execFileSync` to `esbuild` and `remix` run with node compat mode.

**Comment by crowlKats** [comment]
Yea, I think that would be the best way to achieve this. Should be fairly simple to add as well

**Comment by bartlomieju** [comment]
> Yea, I think that would be the best way to achieve this. Should be fairly simple to add as well

How so? I think we will need a completely separate implementation that uses sync API from `std` instead of using `tokio`.

**Comment by iuioiua** [comment]
`execSync` has been implemented in #2689.

**Comment by cjihrig** [comment]
Closing this, as the API was added in https://github.com/denoland/deno_std/pull/2699.
