### ISSUE TITLE
compat: postinstall fails for some modules during `npm install`

### ISSUE THREAD

**Issue by kt3k** [denoland/deno_std#2013]
When the npm module has `postinstall` script in package.json, then `npm install` with compat mode stops with errors.

Known npm modules which cause this error:
- `es5-ext`
- `core-js-pure`

**Comment by bartlomieju** [comment]
Right... `postinstall` script. We need to find some sane solution for that.

**Comment by kt3k** [comment]
`es5-ext` has `node -e \"try{require('./_postinstall')}catch(e){}\"` in `postinstall`
https://github.com/medikoo/es5-ext/blob/406507807f96aa092ee252ab5fe759fc0dd4b778/package.json#L115

and that command passed to `child_process.spawn`.

`core-js-pure` also has the same postinstall script https://github.com/zloirock/core-js/blob/6eb66ebbcd9c50a8f337c87992076b51a4beecec/packages/core-js-pure/package.json#L55

**Comment by kt3k** [comment]
dirty solution could be parsing the input at the beginning of `child_process.spawn`, and change the behavior if the input is `node` command with `-e` option...

**Comment by kt3k** [comment]
- `_postinstall.js` script in ex5-ext https://github.com/medikoo/es5-ext/blob/edf9fbac6c0d72a6192de7e0fbfb022eb34c3ac7/_postinstall.js
- `postinstall.js` script in core-js https://github.com/zloirock/core-js/blob/master/packages/core-js/postinstall.js

These scripts seem technically irrelevant to make them working (political messages and donation requests). Maybe ignoring these postinstall scripts by hard coding would be a possible option

**Comment by kt3k** [comment]
postinstall issue is tracked in https://github.com/denoland/deno/issues/16164
