### ISSUE TITLE
Feature request: Should the API of the fs module support URL strings?

### ISSUE THREAD

**Issue by ayame113** [denoland/deno_std#2017]
Currently, functions in the fs module only accept path strings as arguments.
https://doc.deno.land/https://deno.land/std@0.128.0/fs/mod.ts

As with Deno's built-in filesystem API, it would be nice to accept file URLs as well as strings (eg `ensureFile()`).

Related to https://github.com/denoland/deno/issues/8579 .

**Comment by kt3k** [comment]
I like the idea. This makes fs APIs of Deno namespace and std/fs more consistent.

Is there any concern about this?

**Comment by iuioiua** [comment]
I'm happy to give this a crack 🤙🏾

**Comment by kt3k** [comment]
@iuioiua Thanks!
