### ISSUE TITLE
compat: CallSite.prototype.getFileName needs to return an absolute path instead of `file://` scheme URL in compat mode

### ISSUE THREAD

**Issue by kt3k** [denoland/deno_std#2026]
`get-caller-file` (33M weekly downloads) do the below:

```js
const oldPrepareStackTrace = Error.prepareStackTrace;
Error.prepareStackTrace = (_, stack)  => stack;
const stack = new Error().stack;
Error.prepareStackTrace = oldPrepareStackTrace;
return stack[2].getFileName()
```

Here `getFileName()` returns the callers absolute path in node, but it returns `file://` scheme url in compat mode. We need to change this to absolute path in compat mode to support modules which depends on this feature.

**Comment by bartlomieju** [comment]
So I think we might want to close this issue? @kt3k wdyt?
