### ISSUE TITLE
testing/asserts : `assertFalse`

### ISSUE THREAD

**Issue by UltiRequiem** [denoland/deno_std#2045]
**Is your feature request related to a problem? Please describe.**

Currently, the testing module lacks a method to check if a value is False.

**Describe the solution you'd like**

```ts
export function assertFalse(expr: unknown, msg = ""): asserts expr is false {
  if (expr) {
    throw new AssertionError(msg);
  }
}
```
**Describe alternatives you've considered**

```ts
Deno.test("Text with letter is not numeric.", () => {
  assertEquals(isNumber("hello"), false);
  assert(isNumber("hello") === false);
  assert(!isNumber("hello"));
});
```

With the solution shown before we could 

```ts
Deno.test("Text with letter is not numeric.", () => {
  assertFalse(isNumber("hello"));
});
```

Which I think is a lot more readable. Similar to 👇🏽 
https://jestjs.io/docs/expect#tobefalsy
https://github.com/avajs/ava/blob/main/docs/03-assertions.md#falseactual-message

**Comment by getspooky** [comment]
@UltiRequiem you can use `assert` or `assertEquals` so no need to add `assertFalse`

**Comment by UltiRequiem** [comment]
> @UltiRequiem you can use `assert` or `assertEquals` so no need to add `assertFalse`

I already listed both options on `Describe alternatives you've considered`.

Despite that, an `assertFalse` function would upgrade readability and other libraries include it.

**Comment by UltiRequiem** [comment]
Another library that has something similar is Ava.

https://github.com/avajs/ava/blob/main/docs/03-assertions.md#falseactual-message

**Comment by kt3k** [comment]
This looks too trivial to include in std to me.

Is there any supportive opinions to this other than the above?

**Comment by UltiRequiem** [comment]
> This looks too trivial to include in std to me.
> 
> Is there any supportive opinions to this other than the above?

I think the two strongest points are readability, and that other frameworks have it.

But I understand if it is not wanted here 😆

**Comment by bcheidemann** [comment]
I don't have a strong opinion if this should be implemented or not.

However, it should be `assertNot` in my opinion to match the existing convention set by other assertions e.g. `assertEquals()` vs `assertNotEquals()`.

**Comment by bcheidemann** [comment]
@bartlomieju @kt3k can we make a call yet on if we want to include this or not? The reasons for including it seem valid to me and I know I (and many other developers) would use it even though it is trivial 😉

**Comment by bartlomieju** [comment]
If there's prior art for such assertion I'm willing to squint my eyes and accept it.

**Comment by kt3k** [comment]
Researched other languages and libraries. Some languages seem intentionally avoiding including it (Node, Ruby, Rust, etc), but many languages/libraries seem having `assertFalse` or similar. Interestingly I couldn't find any example of `assertNot`, which I personally think is worth considering.

### Libs/Languages which have something similar to `assertFalse`
- JUnit (Java) has `assertTrue` and `assertFalse` https://junit.org/junit5/docs/5.0.1/api/org/junit/jupiter/api/Assertions.html#assertFalse-boolean-
- QUnit (JUnit clone in javascript) has `assert.true` and `assert.false` https://api.qunitjs.com/assert/false/
- Kotlin has `assert` and `assertFalse` https://kotlinlang.org/api/latest/kotlin.test/kotlin.test/assert-false.html
- Python unittest has `assertTrue` and `assertFalse` https://docs.python.org/3/library/unittest.html#unittest.TestCase.assertFalse
- Golang testify has `assert.True` and `assert.False` https://pkg.go.dev/github.com/stretchr/testify/assert#False
- PHPUnit has `assertTrue` and `assertFalse` https://phpunit.readthedocs.io/en/9.5/assertions.html

###  Libs/Languages which don't have something similar to `assertFalse`
- Node.js has `assert()` and doesn't have negative version https://nodejs.org/api/assert.html
- Ruby has `assert` and doesn't have negative version https://docs.ruby-lang.org/en/2.1.0/Test/Unit/Assertions.html
- Rust has `assert!` and doesn't have negative version https://doc.rust-lang.org/std/macro.assert.html
- OCaml's OUnit has `assert_bool` (similar to assert_true) and doesn't have negative version https://gildor478.github.io/ounit/ounit2/OUnit2/index.html#val-assert_bool

**Comment by bcheidemann** [comment]
@kt3k That's very interesting 🤔 seems like a fairly even split.

I think `assertFalse` makes sense for many of the other languages mentioned because they have much narrower definitions of what it means to be falsy.

In JS I think it is misleading because `assertFalse(""); assertFalse(0); assertFalse(null); assertFalse(undefined); assertFalse(NaN);` would all pass.

I suggested `assertNot` because it fits the pattern for inverse assertions in `deno_std` but I think `assertFalsy` would also make sense. This would match [Jest](https://jestjs.io/docs/expect#tobefalsy) which has `expect.toBeFalsy`.

I think Jest also has `toBeTrue` and `toBeFalse` but these match only the literal values `true` and `false`.

**Comment by bartlomieju** [comment]
@kt3k since there are more examples of support for this feature I think we can add it.

**Comment by UltiRequiem** [comment]
Closing because the feature was merged.
