### ISSUE TITLE
responsiveness callback for serve (std/http/server.ts)

### ISSUE THREAD

**Issue by LuizzAugusto** [denoland/deno_std#2047]
Hey. I suggest responsiveness callback for serve like `serve(req, handler, onResponsive)`, I think it will make test easier

**Comment by crowlKats** [comment]
I am not sure i understand what you mean

**Comment by LuizzAugusto** [comment]
> I am not sure i understand what you mean

i'm trying to create a serverController (for a rest api), but it's hard to sync the test with the fetch and the server. I'm thinking in use some callback, so I can use await server.init(). The code is comething like `import { createFakeBrowser } from "./createFakeBrowser.js"
import { createServer } from "./createServer.js"
import { assert } from "./deps/for_test/asserts.js"

Deno.test({ name: "createServer", fn: async function () {
  const port = 3007
  const server = createServer({ port })
  server.init()
  const fakeBrowser = createFakeBrowser({ port })
  const res = await fakeBrowser.init()
  const htmlText = await res.text()
  const HTML_TEXT = 
      "<!DOCTYPE html>"
    + "\n<html lang=\"en\">"
    + "\n<head>"
    + "\n  <meta charset=\"UTF-8\">"
    + "\n  <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">"
    + "\n  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">"
    + "\n  <title>Teste</title>"
    + "\n  <link rel=\"stylesheet\" type=\"text/css\" href=\"./immutable.css\"></link>"
    + "\n  <link rel=\"stylesheet\" type=\"text/css\" href=\"./global.css\"></link>"
    + "\n</head>"
    + "\n<body>"
    + "\n  <script type=\"module\" src=\"./script.js\"></script>"
    + "\n</body>"
    + "\n</html>"
  assert(htmlText, HTML_TEXT)
  server.stop()
}})
`

**Comment by iuioiua** [comment]
Hi @LuizzAugusto, are you after the `onListen` param in [http/serve](https://deno.land/std/http/server.ts?s=serve)?

**Comment by iuioiua** [comment]
@kt3k, I believe this can be closed.
