### ISSUE TITLE
Path class similar to Rust's PathBuf

### ISSUE THREAD

**Issue by ry** [denoland/deno_std#2072]
I've come to love Rust's `PathBuf` and `Path` abstractions. Is anyone interested in doing a class in std that works like these?

https://doc.rust-lang.org/stable/std/path/struct.PathBuf.html
https://doc.rust-lang.org/stable/std/path/struct.Path.html

I'm not sure how exactly this should look - but here's some example code of what I have in mind...

Example:
```ts
import { Path } from "https://deno.land/std/path/mod.ts";
import { assert } from "https://deno.land/std/testing/assert.ts";

const p = new Path("/Users/ry/src/deno/README.md");
for (let a in p.ancestors()) {
  assert(a.exists());
}
```

- You should be very familiar with the Rust `PathBuf` and `Path` abstractions if you undertake this.
- This should work on Windows.

**Comment by nayeemrmn** [comment]
Duplicate of #678. We need to consider the fact that Rust's `PathBuf` and `Path` are built-in and how a non-native `Path` type would fragment APIs across the ecosystem which accept paths.

**Comment by lucacasonato** [comment]
I agree with @nayeemrmn here. I am not sure I am in favour of a new `Path` wrapper class. Paths should be represented as strings, and path methods should be functions IMO.

**Comment by ry** [comment]
Closed in favor of https://github.com/denoland/deno_std/issues/678
