### ISSUE TITLE
`std/node` should avoid TLA

### ISSUE THREAD

**Issue by nayeemrmn** [denoland/deno_std#2097]
See https://github.com/denoland/deno/issues/14243. Imagine side-effect-importing some polyfill from esm.sh at your application entrypoint. That polyfill was built for Deno to import things from `std/node`. If it is asynchronously evaluated, you will get an undesired dependency evaluation order and the conventional `import "https://cdn.esm.sh/reflect-metadata?deno"` at your application entrypoint might not suffice.

In this case there is a single easily fixed culprit: https://github.com/denoland/deno_std/blob/8824ae1ef3e53a6531b464f9add1eb40a60b9d64/node/internal/util/debuglog.ts#L108-L113

cc @shivam-tripathi

**Comment by rivy** [comment]
@nayeemrmn , could this be changed back to a gate using synchronous calls now that synchronous permission functions have been [added/merged](https://github.com/denoland/deno/pull/17019)?

It would preserve synchronous import order (and continue to avoid top-level-await [TLA]) but avoid undesired prompt UI when including std modules (see discussion at <https://github.com/denoland/deno/issues/13730>).

Adding a gate with the new sync permission calls could be used to solve <https://github.com/denoland/deno_std/issues/2507>.

**Comment by kt3k** [comment]
It's worked here https://github.com/denoland/deno_std/pull/3132, but now blocked by Deploy compatibility

**Comment by rivy** [comment]
@kt3k , the noted PR (#3132) is now closed as "stale". Was it resurrected somewhere else?

**Comment by kt3k** [comment]
`std/node` has been moved to Deno CLI ( https://github.com/denoland/deno/tree/main/ext/node/polyfills ), and this is non issue for deno_std now.
