### ISSUE TITLE
Deprecate and remove "testing/bench.ts" module

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno_std#2103]
Not that `deno bench` subcommand is available I think we should deprecate and eventually remove `testing/bench.ts` module.

While the module is certainly useful I strongly believe we should encourage use of `Deno.bench()` API and add functionality to it if some is missing.

Let's deprecate it in Deno v1.21 release and remove in Deno v1.22

CC @littleof

**Comment by bartlomieju** [comment]
Let's keep this issue open, until the module is removed.

**Comment by jsejcksn** [comment]
> Let's deprecate it in Deno v1.21 release and remove in Deno v1.22

In [Deno v`1.20.6` / std v`0.135.0`](https://github.com/denoland/dotland/blob/46462c8a3c3ca830d49dfa110f26d3231231d334/versions.json#L195): [`Deno.bench()`](https://doc.deno.land/deno/unstable@v1.20.6/~/Deno.bench) and the [benchmarking API](https://deno.land/manual@v1.20.6/tools/benchmarker) are [not currently available](https://doc.deno.land/deno/stable@v1.20.6/~/Deno.bench) as stable features, yet `std/testing/bench` [was deprecated in the same release](https://github.com/denoland/deno_std/releases/tag/0.135.0#:~:text=BREAKING(testing/bench)%3A%20deprecate%20testing/bench%20module). What is being suggested in place of that module in stable usage? If there's no alternative, shouldn't the deprecation have taken place _after_ all the new benchmarking features are moved into stable?

**Comment by bartlomieju** [comment]
> > Let's deprecate it in Deno v1.21 release and remove in Deno v1.22
> 
> In [Deno v`1.20.6` / std v`0.135.0`](https://github.com/denoland/dotland/blob/46462c8a3c3ca830d49dfa110f26d3231231d334/versions.json#L195): [`Deno.bench()`](https://doc.deno.land/deno/unstable@v1.20.6/~/Deno.bench) and the [benchmarking API](https://deno.land/manual@v1.20.6/tools/benchmarker) are [not currently available](https://doc.deno.land/deno/stable@v1.20.6/~/Deno.bench) as stable features, yet `std/testing/bench` [was deprecated in the same release](https://github.com/denoland/deno_std/releases/tag/0.135.0#:~:text=BREAKING(testing/bench)%3A%20deprecate%20testing/bench%20module).
> 
> 1. What is being suggested in place of that module in stable usage? If there's no alternative, shouldn't the deprecation have taken place _after_ all the new benchmarking features are moved into stable?

You should use `Deno.bench()` API, hopefully we'll stabilize it in Deno v1.22. `deno_std` is at 0.135.0 so it's still unstable, giving a few weeks of deprecation notice seems enough to migrate to the new API. Alternatively you can stay on previous versions of `deno_std` for `testing/bench` imports.

> 2. The promised return value of [`runBenchmarks`](https://doc.deno.land/https://deno.land/std@0.135.0/testing/bench.ts/~/runBenchmarks) included an array of [`BenchmarkResult`](https://doc.deno.land/https://deno.land/std@0.135.0/testing/bench.ts/~/BenchmarkResult)s, which could be serialized into JSON and stored for further external analysis. I didn't see anything like that in the new benchmarking API. How can I get the granular benchmark result data serialized as JSON?

We'll add JSON output from `deno bench` subcommand before stabilization.

**Comment by jsejcksn** [comment]
> You should use `Deno.bench()` API, hopefully we'll stabilize it in Deno v1.22

@bartlomieju I interpret that you're suggesting this is the only alternative.

Although I understand the current scenario, I want to point out that using a TypeScript module which is "unstable" according to [semver](https://semver.org/) is very different than running Deno itself in unstable mode. I can independently evaluate the code in the module and use it without adopting the rest of the `std` library if it is deemed to be acceptable, but I can't opt into **only** the benchmarking API without also enabling **all** of the other unstable features of Deno.

**Comment by iuioiua** [comment]
@kt3k, I believe this issue can be closed. `std/testing/bench` was deprecated and then removed in #2714.
