### ISSUE TITLE
crypto: add fnv1a hash

### ISSUE THREAD

**Issue by littledivy** [denoland/deno_std#2122]
Like the one in `std/hash` https://github.com/denoland/deno_std/blob/main/hash/_fnv

**Comment by luk3skyw4lker** [comment]
I can take this one. I'll take a look at the algorithm today and create an implementation.

**Comment by luk3skyw4lker** [comment]
It seems like they're already implemented. There are two classes being exported of the module and one is the fnv algorithm and the other is the fnv-a

**Comment by luk3skyw4lker** [comment]
Why the need for them to be at the crypto module? Is it because it's internal? I didn't fully understand the need for it.

**Comment by KyleJune** [comment]
It's because hash module is deprecated. They are going to delete the whole hash folder. Instead of deleting fnv that can't be replaced with WebCrypto and std/crypto, I think they are just going to just move it to std/crypto folder instead of keeping this folder with just fnv algorithms in it.

**Comment by luk3skyw4lker** [comment]
Dang! That totally slipped through me, I'm sorry!

I'll do the work of implementing the algorithms then, thanks for the heads up!

**Comment by luk3skyw4lker** [comment]
In that case, wouldn't be the case to migrate all of the hashing algorithms to the crypto module? Or I am wrong?

**Comment by KyleJune** [comment]
I think all the other ones in that directory can be done by WebCrypto or std/crypto. fnv is a non cryptographic hash, which is why it currently doesn't have a replacement. I'm not sure about internal discussions at Deno on this task, but I think the fnv implementation in hash could just be moved to std/crypto instead of re-implementing it.

**Comment by luk3skyw4lker** [comment]
I'm checking with the maintainers about the internals, thanks for your tips!

**Comment by littledivy** [comment]
Yup `std/hash` is deprecated so we need this in `std/crypto`. You can simply copy over the algorithm from `std/hash/_fnv` to expose this API:

```typescript
import { crypto } from "https://deno.land/std/crypto/mod.ts";

// 32bit
await crypto.subtle.digest("fnv32", new TextEncoder().encode("deno")); // 0x6e, 0xd5, 0xa7, 0xa9
await crypto.subtle.digest("fnv32a", new TextEncoder().encode("deno")); // 0x8e, 0xf6, 0x47, 0x11

// 64bit
await crypto.subtle.digest("fnv64", new TextEncoder().encode("deno")); // 0x14, 0xed, 0xb2, 0x7e, 0xec, 0xda, 0xad, 0xc9
await crypto.subtle.digest("fnv64a", new TextEncoder().encode("deno")); // 0xa5, 0xd9, 0xfb, 0x67, 0x42, 0x6e, 0x48, 0xb1
```

The streaming implementation can also be simplified to a simple function, like the one used in `std/http/file_server.ts` https://github.com/denoland/deno_std/blob/main/http/file_server.ts#L183

**Comment by luk3skyw4lker** [comment]
Yeah, I was thinking about placing a function just like the one from `std/http/file_server.ts` at the mod.ts file of the crypto module. But then I took a deeper look at the module implementation and saw that most of the algorithms are placed in the `_wasm_crypto` module which is in Rust.

In that case, should I do the Typescript implementation or follow the pattern and implement them in Rust? (I'm almost sure that the Rust implementation should be the option)

**Comment by littledivy** [comment]
> In that case, should I do the Typescript implementation or follow the pattern and implement them in Rust?

Typescript. The algorithm is fairly trivial and possibly more performant than WASM (calling into WASM each iteration is not cheap)

**Comment by luk3skyw4lker** [comment]
Right! Thanks for the answers, I'll try to make a PR today.

**Comment by kt3k** [comment]
done in #2200
