### ISSUE TITLE
test(snapshot): do not commit wrong snapshot

### ISSUE THREAD

**Issue by kt3k** [denoland/deno_std#2128]
ref #2039

Currently we intentionally commit some wrong snapshots in `testing/__snapshot__` to test `assertSnapshot`, and that means we can't use `--update` option for updating that snapshot. We need to somehow fix this to avoid the maintenance difficulties

**Comment by bcheidemann** [comment]
@kt3k This is fixed in https://github.com/denoland/deno_std/pull/2179 😊
