### ISSUE TITLE
test(snapshot): use `Deno.makeTempDir` instead of custom tmp directory

### ISSUE THREAD

**Issue by kt3k** [denoland/deno_std#2129]
ref #2039

and also let's remove tmp directory at assertion failures.

**Comment by bcheidemann** [comment]
@kt3k I think we can sidestep this issue.

Currently spawning new instances of `deno test` adds 5+ seconds which is not ideal.

If we implement something similar to [my suggestion](https://github.com/denoland/deno_std/issues/2135#issuecomment-1107438487) in #2135 I think we can test the behaviour of updating and asserting a mismatched snapshot without needing to spawn new instances of `deno test`.

What do you think?

**Comment by bartlomieju** [comment]
FYI I'm still unable to run all tests locally, the "update" test is failing. We should fix this situation ASAP.

**Comment by bcheidemann** [comment]
> FYI I'm still unable to run all tests locally, the "update" test is failing. We should fix this situation ASAP.

That's not ideal 🤔

The update test will basically be completely re-written as part of #2135 so hopefully this should fix it.

By the way, this test passes locally for me but the `http/file_server_test.ts` fails on `file_server file responses includes correct etag`:

```
-   5810a8f4
+   W/5810a8f4
```

**Comment by kt3k** [comment]
@bartlomieju 
> FYI I'm still unable to run all tests locally

What error do you see? 

@bcheidemann 
> By the way, this test passes locally for me but the http/file_server_test.ts fails on file_server file responses includes correct etag:

That should be fixed by upgrading to canary version: `deno upgrade --canary`

**Comment by bartlomieju** [comment]
> @bartlomieju
> 
> > FYI I'm still unable to run all tests locally
> 
> What error do you see?

Scratch that, it no longer happens after upgrading to latest stable release. I guess I had hit some flake.

**Comment by bcheidemann** [comment]
@bartlomieju @kt3k This is fixed in https://github.com/denoland/deno_std/pull/2179 👍
