### ISSUE TITLE
Implement strict mode in `std`

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno_std#213]
Deno runs in non-strict mode, in the Deno core though, we enforce strict mode.  I think we should enforce that for `std`.  I am seeing a lot of code in here that is not compliant with strict mode, which allows a lot of unsafe assignments around `null` and `undefined` as well as quite a few other violations which make the code unsound.

We also have quite a few linting violations too, which we catch in core, which are not being caught in our code review, like unused variables, `let`s where no reassignment occurs, etc...

My opinion is we need to find a way to enforce these as part of the CI process before it gets too far out of hand.

**Comment by ry** [comment]
Yes - we need TSLint here.

**Comment by kitsonk** [comment]
Actually, ESLint.  See denoland/deno#1824... TSLint is moving itself into ESLint.

**Comment by bartlomieju** [comment]
With ESLing in CI pipeline can we close this issue?

**Comment by kitsonk** [comment]
No, this is more than that.  Now that `tsconfig.json` is support on the CLI, we would want to change the CI to run Deno in strict mode in addition to linting.  I haven't tried it yet, but I suspect it will throw out a huge amount of errors.

**Comment by bartlomieju** [comment]
Thanks for comment @kitsonk, I'll look into it
