### ISSUE TITLE
Improvements to the "assertSnapshot" API

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno_std#2135]
Just noticing this now; sad to see opinionated magic around where snapshots are saved (a `__snapshots__` dir) instead of the `assertSnapshot` function just accepting 2 arguments; the actual value being asserted, and a file URL / string path to the snapshot file. That way just by reading argument intellisense it's predictable (and customisable) where the snapshots end up, and the snapshot can be held in the correct type of file for the data (`.json`, `.html`, `.css`, etc.) for syntax highlighting and such when directly viewing the snapshot file in an editor.

The simpler design also means a simpler implementation to write and maintain.

Here is an example of the (IMO) ideal `assertSnapshot` API in action on npm:

- https://www.npmjs.com/package/snapshot-assertion
- https://github.com/jaydenseric/snapshot-assertion
- https://github.com/jaydenseric/snapshot-assertion/blob/5b7f7425a231081e8f97b58765be6a789cf72696/assertSnapshot.mjs#L40-L77

Note the optional third argument `assertion` that accepts an assertion function for comparing the actual text with the snapshot file text, in case you want to use your own custom one for a special kind of diff or something:

https://github.com/jaydenseric/snapshot-assertion/blob/5b7f7425a231081e8f97b58765be6a789cf72696/assertSnapshot.mjs#L16-L19

_Originally posted by @jaydenseric in https://github.com/denoland/deno_std/issues/2039#issuecomment-1104689896_

**Comment by bcheidemann** [comment]
As suggested by @kt3k in [this comment](https://github.com/denoland/deno_std/pull/2039#issuecomment-1104699940) we could overload the `assertSnapshot` function.

When I was working on the implementation, this is something I considered because we could have avoided #2128 but I didn't want to over complicate/rush the implementation for first pass because we wanted to release this feature with Deno v1.21.

Anyway, this would be my preferred API though there are of course other options:

```ts
type SnapshotMode = 'update' | 'assert''

type SnapshotOptions<T> = {
  mode: SnapshotMode;
  snapshotDir?: string;
  serializer?: (actual: T) => string;
  // --snip--
  msg?: string;
}

async function assertSnapshot<T>(
  t: Deno.TestContext,
  actual: T,
  options: SnapshotOptions<T>,
): Promise<void>;
async function assertSnapshot(
  context: Deno.TestContext,
  actual: unknown,
  msg?: string,
): Promise<void>;
async function assertSnapshot<T>(
  context: Deno.TestContext,
  actual: T,
  msg?: string,
): Promise<void>;
async function assertSnapshot(t: Deno.TestContext, actual: unknown, msgOrOpts?: string | SnapshotOptions<unknown>): Promise<void> {
  // --snip--
}
```

What do you think @jaydenseric @bartlomieju ?

I'd love to raise a PR for this 😊

**Comment by bcheidemann** [comment]
Btw this would enable us to close both #2128 and #2129 😁

**Comment by kt3k** [comment]
@bcheidemann 
Thanks for suggesting the API design!

> type SnapshotOptions<T> = {

Overloading with options object looks good to me, but the properties of `SnapshotOptions` look a little verbose to me:

The example in https://github.com/jaydenseric/snapshot-assertion#examples will be like:

```ts
await assertSnapshot(t, await response.json(), {
  snapshotDir: "snapshots",
  snapshotName: "todo.json",
});
```

Because it's already the options for `assertSnapshot`, `snapshot` part in property name looks redundant to me. Also the separation of `Dir` and `Name` doesn't make much sense to me. How about providing just `path` option?

```ts
await assertSnapshot(t, await response.json(), { path: "snapshots/todo.json" });
```

> I'd love to raise a PR for this 😊

That's very welcome!

**Comment by bcheidemann** [comment]
@kt3k Thanks for the feedback!

> Because it's already the options for assertSnapshot, snapshot part in property name looks redundant to me. Also the separation of Dir and Name doesn't make much sense to me. How about providing just path option?

On reflection, I completely agree! 😁

> That's very welcome!

Great! I'll get started!

**Comment by bcheidemann** [comment]
@kt3k On... third thought?... would you object to a `dir` option? 😄

I think this makes sense because if all you care about is the snapshot directory then it's cleaner to write:

```ts
await assertSnapshot(t, actual, { path: '.snapshots' });
```

than 

```ts
await assertSnapshot(t, actual, { path: '.snapshots/my_test.ts' });
```

This has the added benefit that if you rename the test file, you don't need to make any manual alterations.

**Comment by bartlomieju** [comment]
`dir` seems fine. Other suggestions looks fine too. Looking forward to PRs.

**Comment by bartlomieju** [comment]
One more thing I'd love to see is an alternative serializer provided as an exported function - the serializer should match using wildcards, ie. we want to assert the shape of the object but certain values don't need to match exactly. This is useful if there are dates/time measurements.

**Comment by bcheidemann** [comment]
> One more thing I'd love to see is an alternative serializer provided as an exported function - the serializer should match using wildcards, ie. we want to assert the shape of the object but certain values don't need to match exactly. This is useful if there are dates/time measurements.

I really like this idea! Jest has the following:

```ts
test('Wildcard', () => {
    expect({
        time: Date.now(),
    }).toMatchSnapshot({
        time: expect.any(Number),
    });
});
```

```js
exports[`Wildcard 1`] = `
Object {
  "time": Any<Number>,
}
`;
```

But this doesn't work for many use cases 🤔

I'll put some thought into this later but I wonder if it should be a separate PR? It could be very powerful if done right and I'd want to give it the attention it deserves.

Thoughts? @bartlomieju @kt3k

**Comment by kt3k** [comment]
> On... third thought?... would you object to a dir option? 😄

Ok. `dir` seems fine to me now. Let's have both `path` and `dir`.

> I'll put some thought into this later but I wonder if it should be a separate PR? It could be very powerful if done right and I'd want to give it the attention it deserves.

Separate PR sounds good to me 👍

**Comment by kt3k** [comment]
Wildcard matching is powerful and desirable feature (We already needed something like this in our test cases. [ref](https://github.com/denoland/deno_std/blob/3b7aca1842a697daee7833310ff1bb9c049c73ea/testing/snapshot_test.ts#L106-L109)).

FYI Deno CLI uses the format like [this](https://github.com/denoland/deno/blob/d2c80aa26f30cfc3d614ff313a8dfe4c2c534cd1/cli/tests/testdata/022_info_flag_script.out) (The matcher is implemented by ourselves)

**Comment by bartlomieju** [comment]
> Wildcard matching is powerful and desirable feature (We already needed something like this in our test cases. [ref](https://github.com/denoland/deno_std/blob/3b7aca1842a697daee7833310ff1bb9c049c73ea/testing/snapshot_test.ts#L106-L109)).
> 
> FYI Deno CLI uses the format like [this](https://github.com/denoland/deno/blob/d2c80aa26f30cfc3d614ff313a8dfe4c2c534cd1/cli/tests/testdata/022_info_flag_script.out) (The matcher is implemented by ourselves)

Yeah, a copy of what CLI does (`[WILDCARD]`) would cover most cases I can think of.
