### ISSUE TITLE
assertSnapshot crops long texts

### ISSUE THREAD

**Issue by oscarotero** [denoland/deno_std#2140]
**Describe the bug**

I want to use assertSnapshot to test the pages generated by [Lume](https://github.com/lumeland/lume), but just noticed that values with long content (more than 115 characters) are cropped so I cannot test the whole page content. 

**Steps to Reproduce**

1. Create a file with the contents:
```js
import {assertSnapshot} from "https://deno.land/std@0.136.0/testing/snapshot.ts";

Deno.test("Testing a page", async (t) => {
  await assertSnapshot(t, {
    title: "Testing a page",
    content: `
    <h1>Testing a page</h1>
    <p>This is a test</p>
    <ul>
      <li>1</li>
      <li>2</li>
      <li>3</li>
      <li>4</li>
    </ul>
    `
  })
});
```

2. Run the test with `deno test --allow-read --allow-write test.ts -- --update`
3. Open the file `__snapshots__/test.ts.snap` and you can see the `content` key with the value cropped.

```js
export const snapshot = {};

snapshot[`Testing a page 1`] = `
{
  content: "\\n    <h1>Testing a page</h1>\\n    <p>This is a test</p>\\n    <ul>\\n      <li>1</li>\\n      <li>2</li>\\n  ...",
  title: "Testing a page",
}
`;
```

**Expected behavior**

The `content` key should contain the entire original string

**Environment**

- OS: MacOS 12
- deno version: 1.21.0
- std version: 0.136.0

**Comment by oscarotero** [comment]
Note that if the content passed to the snapshot is a string, it will be saved entirely. So a workaround for this is using `JSON.stringify` to pass the content:

```ts
import {assertSnapshot} from "https://deno.land/std@0.136.0/testing/snapshot.ts";

Deno.test("Testing a page", async (t) => {
  await assertSnapshot(t, JSON.stringify({
    title: "Testing a page",
    content: `
    <h1>Testing a page</h1>
    <p>This is a test</p>
    <ul>
      <li>1</li>
      <li>2</li>
      <li>3</li>
      <li>4</li>
    </ul>
    `
  }))
});
```

**Comment by bartlomieju** [comment]
CC @bcheidemann

**Comment by bcheidemann** [comment]
@bartlomieju on it 👍
