### ISSUE TITLE
`assertSnapshot` adds commas to empty arrays

### ISSUE THREAD

**Issue by GJZwiers** [denoland/deno_std#2144]
**Describe the bug**

When passing an object to assertSnapshot, commas are added inside empty arrays, causing the snapshot test to fail

**Steps to Reproduce**

test file (simplified):
```ts
import { assertSnapshot } from "https://deno.land/std@0.136.0/testing/snapshot.ts";

Deno.test("isSnapshotMatch", async (test) => {
  const config = {
    fmt: {
      files: {
        exclude: [],
        include: []
      },
      options: {},
    },
  };
  await assertSnapshot(test, config);
});

```

snap file:

```
export const snapshot = {};

snapshot[`isSnapshotMatch 1`] = `
{
  fmt: {
    files: {
      exclude: [],
      include: []
    },
    options: {},
  },
}
`;
```

output:

```
running 1 test from ./snapshot.test.ts
isSnapshotMatch ... FAILED (17ms)

failures:

./snapshot.test.ts > isSnapshotMatch
AssertionError: Snapshot does not match:


    [Diff] Actual / Expected


    {
      fmt: {
        files: {
-         exclude: [
-           ,
-         ],
-         include: [
-           ,
-         ],
+         exclude: [],
+         include: []
        },
        options: {},
      },
    }

    throw new AssertionError(message);
          ^
    at assertSnapshot (https://deno.land/std@0.136.0/testing/snapshot.ts:138:11)
    at async file:///C:/Users/GJZwiers/repos/deno-init/snapshot.test.ts:13:3

failures:

        ./snapshot.test.ts
        isSnapshotMatch

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out (41ms)
```

**Expected behavior**

There should not be commas inside the empty arrays

**Environment**

- OS: Windows 10
- deno version: 1.21.0
- std version: 0.136.0

**Comment by bartlomieju** [comment]
CC @bcheidemann

**Comment by bcheidemann** [comment]
@bartlomieju on it 👍

**Comment by bcheidemann** [comment]
@GJZwiers

I have raised a PR to address this.

In the meantime, the recommended way to create a new snapshot is to run `deno test -- --update` after you've written the test. This will avoid this error as it will create the snapshot file with the extra commas and you can then run `deno test` as you normally would - the tests should pass.

When the fix ships, you will need to run `deno test -- --update` again.

Hope that helps 😊
