### ISSUE TITLE
Test task fails on main branch

### ISSUE THREAD

**Issue by Duelsik** [denoland/deno_std#2149]
`deno task test` results in

```
./http/file_server_test.ts > file_server file responses includes correct etag
AssertionError: Values are not equal:

    [Diff] Actual / Expected

-   66d52b1a
+   W/66d52b1a
```

- OS: Arch 5.17.x
- deno version: 1.21.0
- std version: main branch, last local commit that I see `3b7aca1842a697daee7833310ff1bb9c049c73ea`

**Comment by bartlomieju** [comment]
I'm actually having the same error locally. CC @littledivy could you take a look?

**Comment by littledivy** [comment]
It's expected, the tests pass on canary. https://github.com/denoland/deno_std/pull/2133 introduced the change because of the auto compression for HTTP bodies.

**Comment by Duelsik** [comment]
It makes sense, thank you.
