### ISSUE TITLE
assertStrictEquals could use a better comparation

### ISSUE THREAD

**Issue by orl0** [denoland/deno_std#2151]
**Is your feature request related to a problem? Please describe.**

`assertStrictEquals()` inherits the problem of strict equality operator (`===`), exactly the `===` operator treats the number values `-0` and `+0` as equal and `Number.NaN`/`NaN` as not equal.

This behavior doesn't seems for me to be expected when testing.

Expression `assertStrictEquals(func(), NaN)` shouldn't throw if `func` returns `NaN`

**Describe the solution you'd like**

Replace strict equality operator (`===`) with `Object.is` method [(MDN)](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/is).

like
```js
  if (actual === expected) {
    return;
  }
```
to
```js
  if (Object.is(actual, expected)) {
    return;
  }
```

**Comment by cjihrig** [comment]
+1 to this. In my experience, this is generally the behavior that people want. This is also how Node's `assert` module works.

Alternatively, we could add new `assertIs()` and `assertIsNot()` if people wanted to leave `assertStrictEquals()` as is.

What do you think @bartlomieju? I'd be interested in working on this.

**Comment by bartlomieju** [comment]
> +1 to this. In my experience, this is generally the behavior that people want. This is also how Node's `assert` module works.
> 
> Alternatively, we could add new `assertIs()` and `assertIsNot()` if people wanted to leave `assertStrictEquals()` as is.
> 
> What do you think @bartlomieju? I'd be interested in working on this.

I agree, sounds like a reasonable change.
