### ISSUE TITLE
server duplicate requests

### ISSUE THREAD

**Issue by 7flash** [denoland/deno_std#2155]
**Describe the bug**

It duplicates all incoming requests

**Steps to Reproduce**

1. Create a file server.ts with the contents

```
import { serve } from "https://deno.land/std@0.136.0/http/server.ts";

let counter = 0;

const handler = async (req: Request) => {
    console.log('new request')

    const body = {
        counter: ++counter,
    }

    return new Response(JSON.stringify(body), { status: 200 });
}

await serve(handler, { port: 9191 });
```

2. Start the process

```
deno run --allow-net server.ts
```

3. Open http://localhost:9191 in browser and refresh page again

**Expected behavior**

It's expected to have counter equal to 1, 2, 3...
but instead it shows 1,3,5,7...
also "new request" appears in the console twice on each refresh

**Environment**

deno 1.20.6 (release, x86_64-unknown-linux-gnu)
v8 10.0.139.6
typescript 4.6.2

**Comment by littledivy** [comment]
Your browser is sending 2 requests when you visit `http://localhost:9191/` (one to `/` and another to `/favicon.ico`). If you `curl` the endpoint you can see the counter increment normally.

**Comment by 7flash** [comment]
> Your browser is sending 2 requests when you visit `http://localhost:9191/` (one to `/` and another to `/favicon.ico`). If you `curl` the endpoint you can see the counter increment normally.

Thx makes sense
