### ISSUE TITLE
Improve JSDoc to improve doc.deno.land

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno_std#2163]
https://doc.deno.land/ now has an "index" page for complex libraries like std (see: https://doc.deno.land/https://deno.land/std). Currently the inline documentation generated is lacking in a lot of key ways.  Specifically the doc.deno.land generator will take the first paragraph of a JSDoc block and display it as the summary on the index page.  For modules, the first paragraph of a `@module` JSDoc block will be used and if a folder contains a `mod.ts` and there is a `@module` JSDoc block, the first paragraph will become a description of the folder.

So we need to increase the inline documentation (as well as make sure it is accurate) in order to make the std library more discoverable and usable.

For a few examples of what would work, see: https://github.com/denoland/deno_std/pull/2162

**Comment by iuioiua** [comment]
Also, https://deno.land/std doesn't display summaries in the index section seemingly for directories that do not contain a `mod.ts` file. For example, the `/archive` summary is displayed in https://doc.deno.land/https://deno.land/std, but not https://deno.land/std.

**Comment by iuioiua** [comment]
I'm happy to work on this.

For modules, like `/archive`, shall we add a `mod.ts` to just point to the other files to fix the above mentioned issue? Or, is there a good reason to omit `mod.ts` files?

**Comment by kitsonk** [comment]
No, we don't want to introduce `mod.ts` (default modules) where they don't exist currently.  There is this issue to resolve the current challenge: https://github.com/denoland/dotland/issues/2331

We have added `@module` everywhere in `std`, so really what needs to be worked on is improving that documentation, providing good examples where applicable as well as improving the JSDoc across `std`.

**Comment by iuioiua** [comment]
Cool, I'll see where I can help!

**Comment by crowlKats** [comment]
I would say this has been achieved, so closing
