### ISSUE TITLE
http/server: disable startup message behavior for `serve` fn

### ISSUE THREAD

**Issue by jsejcksn** [denoland/deno_std#2186]
**Is your feature request related to a problem? Please describe.**

Recently, a controversial PR #1641 was merged (see feedback in the PR for details), which changed the exported function [`serve`](https://github.com/denoland/deno_std/blob/0.137.0/http/server.ts#L525-L568), causing it to write to `stdout` when invoked (via a call to `console.log`). The content that is written is an English-localized message including information about the origin on which the server is listening. There is currently no way to disable this behavior, and it is not desirable in many cases.

It [was suggested](https://github.com/denoland/deno_std/pull/1641#issuecomment-981103163) to use the `listenAndServe` function as an alternative to avoid the behavior, but since [that function is deprecated](https://github.com/denoland/deno_std/blob/0.137.0/http/server.ts#L630), the suggestion is a non-option.

**Describe the solution you'd like**

I think this PR should be reverted. Alternatively, a new property should be added to the options argument which controls this newly introduced behavior and **defaults to not writing a startup message**, making the behavior opt-in.

**Related thoughts**

Here are a some things which I think should be considered and weren't discussed in the PR:

- What if the user of the function doesn't read or write English and would prefer a startup message in their own language?

- What if the function is being called by another process which is parsing `stdout`, and it introduces unnecessary new complexity by writing this message? The person would need to refactor their parser to accommodate for this behavior.

- `serve` could be invoked in an environment where calling `console.log` will throw an exception.

- What if the user simply does not want anything written to `stdout` as a side-effect of using the function?

**Comment by timonson** [comment]
With regards to *reverting this PR*: I think you are underestimating how many times this would force people to write this exact line of code. I wouldn't be surprised if it would end up in the millions.

**Comment by masx200** [comment]
I think we can add an optional callback function onlisten to the options parameter to allow the user to customize the startup message.

**Comment by jsejcksn** [comment]
> With regards to _reverting this PR_: I think you are underestimating how many times this would force people to write this exact line of code. I wouldn't be surprised if it would end up in the millions.

> I think we can add an optional callback function `onlisten` to the `options` parameter to allow the user to customize the startup message.

The simplest option (least thinking/typing) from a user perspective would be something like `{ startupMessage?: boolean }` with a default of `false`, making it simple for anyone who wants the startup message behavior to enable it like this: `serve(handler, { startupMessage: true })`.

An alternative option (in the spirit of [the message from @masx200](https://github.com/denoland/deno_std/issues/2186#issuecomment-1120095079)) would be for `serve` from [`std/http/server.ts`](https://deno.land/std@0.138.0/http/server.ts) to emit a `"listen"` event (for example, like [Oak's](https://deno.land/x/oak@v10.5.1/application.ts#L213)) and optionally accept an event listener callback at an options property (such as `onlisten`). Then it could also export a function specifically for the purpose of the startup message behavior with a signature matching the "listen" event listener callback. For example:

```ts
import { logStartupMessage, serve } from "https://deno.land/std@STD_VERSION/http/server.ts";

await serve(() => new Response("Hello, world"), { onlisten: logStartupMessage });

```

Both reduce the boilerplate, solving the original problem for those who want the message, while simultaneously fixing the problem introduced in the PR by making unnecessary side-effects opt-in.

**Comment by kt3k** [comment]
@jsejcksn 
I'm in favor of adding `onlisten` (or maybe `onListen`?) option, but I don't think the logging behavior should be opt-in as we (especially core team) want to keep the default logging behavior.

Which do you see more reasonable:
- We have `serve` and `listenAndServe` and `serve` logs the massage by default.
- We have only `serve` and it has `onListen` option and it logs the message by default.

**Comment by AnInternetTroll** [comment]
> We have only serve and it has onListen option and it logs the message by default.

:+1:

**Comment by jsejcksn** [comment]
> @jsejcksn I'm in favor of adding `onlisten` (or maybe `onListen`?) option, but I don't think the logging behavior should be opt-in as we (especially core team) want to keep the default logging behavior.
> 
> Which do you see more reasonable:
> 
> * We have `serve` and `listenAndServe` and `serve` logs the massage by default.
> * We have only `serve` and it has `onListen` option and it logs the message by default.

Hi @kt3k:

It's not clear to me how your listed suggestions relate to the topic of this issue, which is about using the `serve` function without the side-effect behavior of writing a startup message to `stdout`. In your second suggestion:

> We have only `serve` and it has `onListen` option and it logs the message by default.

Are you implying that providing some kind of value to the `onListen` property will prevent `serve` from logging the startup message? Can you clarify this, please?

Also, I'm curious to hear your thoughts about the bulleted list items in my original message. None of those things were discussed before the related PR was merged, and I think they are important considerations. I'd really like to hear the core team's position on each of those.

**Comment by kt3k** [comment]
@jsejcksn 
> Are you implying that providing some kind of value to the onListen property will prevent serve from logging the startup message? Can you clarify this, please?

Yes, in my second suggestion, I meant that `onListen` has the default value which is something like `onListen: () => console.log("Listening ...")`, and you can replace that value (behavior) with your own implementation.

> - What if the user of the function doesn't read or write English and would prefer a startup message in their own language?

So this can be done like `serve(handler, { onListen: () => console.log("...localized message...") }` (with my second suggestion)

> - What if the function is being called by another process which is parsing stdout, and it introduces unnecessary new complexity by writing this message? The person would need to refactor their parser to accommodate for this behavior.
> - serve could be invoked in an environment where calling console.log will throw an exception.
> - What if the user simply does not want anything written to stdout as a side-effect of using the function?

I think passing `onListen: () => {}` (or maybe `onListen: null`?) works around the above situations.

**Comment by jsejcksn** [comment]
@kt3k Thanks for clarifying how it relates.

In your example you don't show a parameter for the hypothetical `onListen` callback function, but I think having a value like Oak's [`ApplicationListenEvent`](https://deno.land/x/oak@v10.5.1/application.ts#L213) with relevant properties like:

```ts
{
  hostname: string;
  port: number;
  secure: boolean;
}
```

will be quite helpful in creating localized messages or doing any other work in response to the server's startup. Do you agree?

Here's an example:

```ts
type ListenEvent = {
  hostname: string;
  port: number;
  secure: boolean;
};

function logMessage ({ hostname, port, secure }: ListenEvent) {
  const url = new URL(`http${secure ? 's' : ''}://${hostname}:${port}/`);
  console.log(`Listening at ${url.href}`);
}

serve(handler, { onListen: logMessage });
```

Also, I think it will be very useful to document the ability to silence the startup message by using `undefined` for the `onListen` property, both in the [`std/http` readme](https://deno.land/std@0.139.0/http/README.md) and in the inline JSDoc for the `serve` function.

**Comment by vwkd** [comment]
> With regards to _reverting this PR_: I think you are underestimating how many times this would force people to write this exact line of code. I wouldn't be surprised if it would end up in the millions.

Well, you suggest that 1. you are forced to document where a server is listening, and 2. this documentation needs to specifically be logging to console. Both aren’t true. You could not document it. Or you could document it in any way you prefer, like a JSDoc comments, a normal comment, a README, logging to console, etc. pp.

Though it seems the maintainers also share the belief that for running a server logging to console is The Right Thing which is unfortunate.
