### ISSUE TITLE
Add MessagePack's encode and decode

### ISSUE THREAD

**Issue by idanran** [denoland/deno_std#2194]
**Is your feature request related to a problem? Please describe.**

encode or decode MessagePack

**Describe the solution you'd like**

```js
import { encode, decode } from "https://deno.land/std/encoding/magpack.ts";

const object = {
  nil: null,
  integer: 1,
  float: Math.PI,
  string: "Hello, world!",
  binary: Uint8Array.from([1, 2, 3]),
  array: [10, 20, 30],
  map: { foo: "bar" },
  timestampExt: new Date(),
};

const encoded= encode(object);
const object = decode(encoded);
```

**Describe alternatives you've considered**

**Comment by lino-levan** [comment]
This would be pretty huge for https://github.com/socketio/socket.io-deno/issues/7. It looks like https://deno.land/x/msgpackr@v1.7.0 does exist, but have this be part of std would be really nice. Does this make sense to go in encoding?

**Comment by kt3k** [comment]
It'd be also worth considering using rust implementation via wasm

**Comment by lino-levan** [comment]
Could be a pretty huge selling point over /x/msgpackr... I don't plan on picking this up right now, but I might get back to it in a few ~weeks-months if no one else picks this up.

**Comment by idanran** [comment]
...

**Comment by lino-levan** [comment]
@iuioiua I know recently you've been against wasm modules in std. Thoughts on this one?

**Comment by iuioiua** [comment]
I was previously against a Wasm implementation of `std/encoding/varint`. The number of moving parts required to operate and maintain it was disproportionally large compared to the issue it solved. It was easily solvable using only TypeScript.

On the other hand, the Wasm implementation of `std/crypto` makes sense as it's perhaps not easily solvable using only TypeScript and robust Rust implementations for algorithms already exist.

I'm unfamiliar with MessagePack. Either way, I'd urge any possible implementor to consider whether a Wasm implementation is worth the added complexity or can be done well enough with just TypeScript, which would be far simpler.

**Comment by lino-levan** [comment]
> On the other hand, the Wasm implementation of `std/crypto` makes sense as it's perhaps not easily solvable using only TypeScript and robust Rust implementations for algorithms already exist.

IMO the main advantage of `std/crypto` using wasm is perf, with the implementation itself being secondary. MessagePack is an interesting case because it's not immediately obvious whether performance or simplicity is more valuable. MessagePack as a format is supposed to be a "more performant + smaller JSON with more types". I think we might want a typescript implementation to start and move over to WASM if we see it as limiting.

**Comment by idanran** [comment]
> > On the other hand, the Wasm implementation of `std/crypto` makes sense as it's perhaps not easily solvable using only TypeScript and robust Rust implementations for algorithms already exist.
> 
> IMO the main advantage of `std/crypto` using wasm is perf, with the implementation itself being secondary. MessagePack is an interesting case because it's not immediately obvious whether performance or simplicity is more valuable. MessagePack as a format is supposed to be a "more performant + smaller JSON with more types". I think we might want a typescript implementation to start and move over to WASM if we see it as limiting.

👍👍

**Comment by lino-levan** [comment]
Just finished the decode implementation and writing some tests. Will open a PR with both encode + decode later today.
