### ISSUE TITLE
http/server.ts : The attribute `secure` should be added to interface `ConnInfo`   to indicate whether it is a `tls` connection.

### ISSUE THREAD

**Issue by masx200** [denoland/deno_std#2196]
**Is your feature request related to a problem? Please describe.**

http/server.ts : The attribute `secure` should be added to interface `ConnInfo`   to indicate whether it is a `tls` connection.

**Describe the solution you'd like**

```ts
export interface ConnInfo {
  /** The local address of the connection. */
  readonly localAddr: Deno.Addr;
  /** The remote address of the connection. */
  readonly remoteAddr: Deno.Addr;

readonly secure: boolean;

}
```
**Describe alternatives you've considered**

**Comment by lucacasonato** [comment]
You can already get this info from the request URL.
```ts
const url = new URL(req.url);
const isSecure = url.protocol == "https:";
```
