### ISSUE TITLE
Port more remaining responsewrite tests from Go

### ISSUE THREAD

**Issue by ry** [denoland/deno_std#22]
https://github.com/golang/go/blob/master/src/net/http/responsewrite_test.go#L19
https://github.com/denoland/deno_net/blob/master/http_test.ts

**Comment by bartlomieju** [comment]
I'm working on this

**Comment by bartlomieju** [comment]
@ry I'm starting this 3rd time, please comment on desired approach. There are significant differences with Go's implementation, mainly explicitly setting protocol version, as well as content length of the body. Those differences drive specific test cases. Do we want to adapt that approach or just generally emulate Go's test cases?
