### ISSUE TITLE
test failed in http/file_server_test.ts error: Uncaught TypeError: Must be a file URL.

### ISSUE THREAD

**Issue by masx200** [denoland/deno_std#2206]
**Describe the bug**

test failed in http/file_server_test.ts error: Uncaught TypeError: Must be a file URL.

**Steps to Reproduce**
```
deno test -A https://deno.land/std@0.138.0/http/file_server_test.ts
Download https://deno.land/std@0.138.0/http/file_server_test.ts
Download https://deno.land/std@0.138.0/textproto/mod.ts
Check https://deno.land/std@0.138.0/http/file_server_test.ts

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out (37ms)

error: Uncaught TypeError: Must be a file URL.
    throw new TypeError("Must be a file URL.");
          ^
    at fromFileUrl (https://deno.land/std@0.138.0/path/win32.ts:968:11)
    at https://deno.land/std@0.138.0/http/file_server_test.ts:28:27
```

**Expected behavior**
no errors

**Environment**

v8 10.0.139.17
typescript 4.6.2
- OS: Microsoft Windows [版本 10.0.19044.1682]
- deno version:deno 1.21.2 (release, x86_64-pc-windows-msvc)
- std version:0.138.0

**Comment by kt3k** [comment]
That test file isn't meant to be run with `https://` scheme. Please check out the repository and run it like:

```
deno test -A http/file_server_test.ts
```

**Comment by kt3k** [comment]
Or do you have any reason to run it via `https://` scheme?
