### ISSUE TITLE
error conditional response in http/file_server.ts

### ISSUE THREAD

**Issue by masx200** [denoland/deno_std#2207]
**Describe the bug**

error conditional response in http/file_server.ts

`If-None-Match: W/3ff580a0`

`etag: W/3ff580a0`

expect response status to be 304

**Steps to Reproduce**
start server
```
deno run -A https://deno.land/std@0.138.0/http/file_server.ts
```

request
```
GET /desktop.ini HTTP/1.1
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Accept-Encoding: gzip, deflate, br
Accept-Language: zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6
Cache-Control: max-age=0
Connection: keep-alive
DNT: 1
Host: localhost:4507
If-Modified-Since: Wed, 09 Feb 2022 11:23:53 GMT
If-None-Match: W/3ff580a0
Referer: http://localhost:4507/
Sec-Fetch-Dest: document
Sec-Fetch-Mode: navigate
Sec-Fetch-Site: same-origin
Sec-Fetch-User: ?1
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36 Edg/101.0.1210.39
sec-ch-ua: " Not A;Brand";v="99", "Chromium";v="101", "Microsoft Edge";v="101"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Windows"
```
response
```
HTTP/1.1 200 OK
accept-ranges: bytes
etag: W/3ff580a0
content-type: text/plain
date: Tue, 10 May 2022 05:28:16 GMT
last-modified: Wed, 09 Feb 2022 11:23:53 GMT
server: deno
access-control-allow-origin: *
access-control-allow-headers: Origin, X-Requested-With, Content-Type, Accept, Range
vary: Accept-Encoding
content-encoding: gzip
transfer-encoding: chunked
```
**Expected behavior**

expect response status to be 304

**Environment**

v8 10.0.139.17
typescript 4.6.2

OS: Microsoft Windows [版本 10.0.19044.1682]
deno version:deno 1.21.2 (release, x86_64-pc-windows-msvc)
std version:0.138.0

desktop.ini
```


[.ShellClassInfo]
LocalizedResourceName=@%SystemRoot%\system32\shell32.dll,-21770
IconResource=%SystemRoot%\system32\imageres.dll,-112
IconFile=%SystemRoot%\system32\shell32.dll
IconIndex=-235

```

**Comment by kt3k** [comment]
Seems like it's caused by https://github.com/denoland/deno_std/pull/2133

When deno does the body compression, etag becomes the form of `W/<etag>` and the matching of `If-None-Match` doesn't work anymore.

**Comment by masx200** [comment]
> 似乎是由 #2133 引起的
> 
> 当 deno 进行身体压缩时，etag 就变成了形式，而匹配不再起作用。`W/<etag>``If-None-Match`

https://unpkg.com/browse/fresh@0.5.2/index.js

```js
 if (match === etag || match === 'W/' + etag || 'W/' + match === etag) {
```

According to the code of the `fresh` module, this is no problem.

**Comment by kt3k** [comment]
Let's do something similar

**Comment by cuobiezi** [comment]
@masx200 Hi  Masx,  Is for Directory of your request demo ?  Seem the file_server.ts didn't care Http Catch for Directory request, only care files request,seem it is correct. Need to refer  /** RFC 7232, 4.1 */ .

**Comment by masx200** [comment]
[cuobiezi](https://github.com/cuobiezi)

request demo is for file.
