### ISSUE TITLE
Proposal: Web stream based jsonlines parser

### ISSUE THREAD

**Issue by ayame113** [denoland/deno_std#2208]
Would you like to add stream based [jsonlines](https://jsonlines.org/) parser as suggested in discord?

https://discord.com/channels/684898665143206084/712010403302866974/972924800852951040

```
{"some":"thing"}
{"foo":17,"bar":false,"quux":true}
{"may":{"include":"nested","objects":["and","arrays"]}}
```

```ts
import { JSONLinesParseStream } from "...";

const { body } = await fetch("...");
const readable = body!
  .pipeThrough(new TextDecoderStream())
  .pipeThrough(new JSONLinesParseStream());
for await (const data of readable) {
  console.log(data);
}
```

Implementations can be copied from https://deno.land/x/jsonlines@v1.1.0.

**Comment by ayame113** [comment]
My another suggestion is to add `transformStreamFromGeneratorFunction`, a utility function used [inside jsonlines modules](https://deno.land/x/jsonlines@v1.1.0/mod.ts#L86), to the strams module.

```ts
import {
  readableStreamFromIterable,
  transformStreamFromGeneratorFunction
} from "...";

const reader = readableStreamFromIterable([0, 1, 2])
  .pipeThrough(transformStreamFromGeneratorFunction(async function* (src) {
    for await (const chunk of src) {
      yield chunk * 100;
    }
  }));

for await (const chunk of reader) {
  console.log(chunk);
}
// output: 0, 100, 200
```

**Comment by crowlKats** [comment]
I am in favour of this, though unsure about the latter.

**Comment by bartlomieju** [comment]
The name is very long, maybe `generatorToStream`?

**Comment by kt3k** [comment]
I'm in favor of having this in std.

It seems that there's also a spec called NDJSON, which seems having a little bit more formal document https://github.com/ndjson/ndjson-spec, http://dataprotocols.org/ndjson/ Maybe better to also consider this as module name?

(Elasticsearch, for example, seems using ndjson for it https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-bulk.html

**Comment by ayame113** [comment]
> The name is very long, maybe `generatorToStream`?

I think it's good 👍

**Comment by kt3k** [comment]
> The parser can also parse the [json text sequence](https://datatracker.ietf.org/doc/html/rfc7464), passing options as arguments. My module also includes a [Concatenated JSON](https://en.wikipedia.org/wiki/JSON_streaming#Concatenated_JSON) parser.
So the module name may need to be a comprehensive name. For example, encoding/json/stream.ts? (Like encoding/csv/stream.ts)

hmm interesting. I didn't know JSON Text Sequence and Concatenated JSON, but it sounds good idea to support both. `encoding/json/stream.ts` sounds good to me 👍
