### ISSUE TITLE
Add GraphQL Server

### ISSUE THREAD

**Issue by idanran** [denoland/deno_std#2211]
**Is your feature request related to a problem? Please describe.**

Build GraphQL API

**Describe the solution you'd like**

[https://graphql.org/](https://graphql.org/)

```js
import { graphql, buildSchema } from ’https://deno.land/std/graphql/mod.ts‘

const schema = buildSchema(`
  type Query {
    hello: String
  }
`);

const root = { hello: () => 'Hello world!' };

graphql(schema, '{ hello }', root).then((response) => {
  console.log(response);
});
```

**Describe alternatives you've considered**

**Comment by prettykool** [comment]
Any reason why [x/gql](https://deno.land/x/gql@1.1.1) isn't sufficient?

**Comment by kitsonk** [comment]
While GraphQL is popular, it does really feel outside of the scope to include a server implementation in std.  While GraphQL is a protocol, a server becomes quite complex, as it needs to provide integrations to back end services and then becomes how much scope would there be.  My opinion is that it is much better served by the community, like [x/gql](https://deno.land/x/gql) mentioned above.

**Comment by idanran** [comment]
> While GraphQL is popular, it does really feel outside of the scope to include a server implementation in std.  While GraphQL is a protocol, a server becomes quite complex, as it needs to provide integrations to back end services and then becomes how much scope would there be.  My opinion is that it is much better served by the community, like [x/gql](https://deno.land/x/gql) mentioned above.

The library above has not been maintained for some time.

**Comment by iuioiua** [comment]
[x/gql](https://deno.land/x/gql) appears to be maintained well enough, and there only seems to be a small amount of support for it to exist within std.

Any thoughts, @kt3k?

**Comment by iuioiua** [comment]
To be clear, this seems outside of the scope of the Standard Library. I'm -1 on this, and others are as well. Again, [x/gql](https://deno.land/x/gql) looks good to use.

**Comment by kt3k** [comment]
Ok. Let's close for now.
