### ISSUE TITLE
testing/snapshot: "assertSnapshot" should have a way to set options in a persistent way

### ISSUE THREAD

**Issue by bcheidemann** [denoland/deno_std#2214]
**Is your feature request related to a problem? Please describe.**

Currently, if I want to set some options for each snapshot in a file, I need to pass these options to each call of `assertSnapshot`. For example:

```ts
Deno.test("example", async (t) => {
  assertSnapshot(t, "first", { dir: "__snaps__" });
  assertSnapshot(t, "second", { dir: "__snaps__" });
  assertSnapshot(t, "third", { dir: "__snaps__" });
  assertSnapshot(t, "fourth", { dir: "__snaps__" });
});
```

This makes tests harder to read.

**Describe the solution you'd like**

Ideally, it would be possible to do something like this:

```ts
assertSnapshot.setOptions({ dir: "__snaps__" });

Deno.test("example", async (t) => {
  assertSnapshot(t, "first");
  assertSnapshot(t, "second");
  assertSnapshot(t, "third");
  assertSnapshot(t, "fourth");
});
```

EDIT: On further consideration, I am actually leading slightly towards Option 2 below but would still be happy if this (or both) were implemented.

**Describe alternatives you've considered**

#### Option 1 - Wrapper Function

It is already possible to wrap assert snapshot like this:

```ts
async function assertSnapshotWithDefaultOpts<T>(
  t: Deno.TestContext,
  actual: T,
  options: SnapshotOptions<T>,
): Promise<void>;
export async function assertSnapshotWithDefaultOpts<T>(
  context: Deno.TestContext,
  actual: T,
  message?: string,
): Promise<void>;
export async function assertSnapshotWithDefaultOpts(
  context: Deno.TestContext,
  actual: unknown,
  msgOrOpts?: string | SnapshotOptions<unknown>,
): Promise<void> {
  await assertSnapshot(t, actual, {
    dir: "__snaps__",
    ...(typeof msgOrOpts === "object" ? msgOrOpts : { msg: msgOrOpts }),
  });
}

Deno.test("example", async (t) => {
  assertSnapshotWithDefaultOpts(t, "first");
  assertSnapshotWithDefaultOpts(t, "second");
  assertSnapshotWithDefaultOpts(t, "third");
  assertSnapshotWithDefaultOpts(t, "fourth");
});
```

However, this is unnecessarily verbose in my opinion.

#### Option 2 - Curried Function

A function (e.g. "createAssertSnapshot") could be exposed from `testing/snapshot.ts`.

```ts
const assertSnapshot = createAssertSnapshot({ /* options */ });

Deno.test("example", async (t) => {
  assertSnapshot(t, "first");
  assertSnapshot(t, "second");
  assertSnapshot(t, "third");
  assertSnapshot(t, "fourth");
});
```

This has the advantage that you could create different assertions and export them from a test utility file. For example,

```ts
export const assertSnapshotStr = createAssertSnapshot<string>({
  serializer: (actual: string) => /* --snip-- */,
});
export const assertSnapshotReactNode = createAssertSnapshot<React.ReactNode>({
  serializer: (actual: React.ReactNode) => /* --snip-- */,
  dir: "__components__",
});
```

**Comment by bcheidemann** [comment]
@bartlomieju @kt3k If you agree this would be a useful addition, I'd be happy to raise a PR for either or both proposals 👍

**Comment by kt3k** [comment]
@bcheidemann 
Thanks for the proposal! The idea makes sense and looks useful to me.

> EDIT: On further consideration, I am actually leading slightly towards Option 2 below but would still be happy if this (or both) were implemented.

I agree with you. Curried function looks clearer than global settings API. Global settings API apparently simple, but I guess it might cause confusion when it called from multiple places. So I'd suggest we should add only Curried function design.

**Comment by bcheidemann** [comment]
> @bcheidemann Thanks for the proposal! The idea makes sense and looks useful to me.
> 
> > EDIT: On further consideration, I am actually leading slightly towards Option 2 below but would still be happy if this (or both) were implemented.
> 
> I agree with you. Curried function looks clearer than global settings API. Global settings API apparently simple, but I guess it might cause confusion when it called from multiple places. So I'd suggest we should add only Curried function design.

Great! I will raise a PR 🙂
