### ISSUE TITLE
Include /x/redis as /std/redis

### ISSUE THREAD

**Issue by kt3k** [denoland/deno_std#2224]
There seem strong demands/needs of redis client in the community. We should have one in std

ref: https://deno.land/x/redis

ref: https://news.ycombinator.com/item?id=31333025

External dependencies of /x/redis:
- lodash-es/shuffle
- lodash-es/sample
- lodash-es/uniqBy
- cluster-key-slot

**Comment by erfanium** [comment]
what makes `redis` different from mysql, postgres, mongodb, elasticsearch,... ? They are all popular. we can't just include `redis` driver in std and ignore the rest.

**Comment by kt3k** [comment]
@erfanium 
We chose to try migrating `redis` (and `sqlite`) first because they have comparatively less external dependencies. (Also the maintainer welcomes the transition in case of redis)

We haven't decided on other drivers. We might take different path for other drivers depending on their situations

**Comment by piscisaureus** [comment]
I'm -1 on this. This is out of scope for std.

> There seem strong demands/needs of redis client in the community.

If there is no community provided driver for an important database like redis, we can consider starting the effort.
But I still think they should be separate projects. The discoverability issue can be fixed with improved search.

**Comment by iuioiua** [comment]
> I'm -1 on this. This is out of scope for std.

I agree. I think we should close this issue.
