### ISSUE TITLE
async/pool: `pooledMap` results are not in the order of iterable element argument

### ISSUE THREAD

**Issue by sntran** [denoland/deno_std#2236]
**Describe the bug**

When `async/pool` [was introduced](https://github.com/denoland/deno/pull/6898), it was expected to be like `Promise.all(array.map(async () => {...}))`. However, while `Promise.all` returns values are in order of the Promises passed, the returned values of `pooledMap` are not in the same order of the argument iterable.

Also, the name `map`, at least to me, is always an 1 to 1 association.

**Steps to Reproduce**

`deno run` the following snippet:

```ts
import { pooledMap } from "https://deno.land/std@0.139.0/async/mod.ts";

function getRandomInt(min: number, max: number): number {
  min = Math.ceil(min);
  max = Math.floor(max);
  return Math.floor(Math.random() * (max - min) + min); //The maximum is exclusive and the minimum is inclusive
}

const results = pooledMap(
  2,
  [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
  (i) => new Promise((r) => setTimeout(() => r(i), getRandomInt(5, 20) * 100)),
);

for await (const value of results) {
  console.log(value);
}
```

**Expected behavior**

The returned value should be `[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]`

**Actual behaviour**

The resulting array is out of order.

**Environment**

- OS: Mac 12.3
- deno version: 1.21.0
- std version: 0.139

**Comment by Sorikairox** [comment]
I'm taking this, but if someone is already on it no problem (at least I would have learned how this work internally)
