### ISSUE TITLE
path/glob: `globToRegExp` does not return valid RegExp

### ISSUE THREAD

**Issue by sntran** [denoland/deno_std#2262]
**Describe the bug**

`globToRegExp` does not escape `/` character correctly when handling `*` in the glob. It generates `[^/]*`, which is not a valid RegExp since the `/` must be escaped.

**Steps to Reproduce**

`deno run` the following snippet:

```ts
import { isGlob, globToRegExp } from "https://deno.land/std@0.140.0/path/glob.ts";
import { assert, assertEquals } from "https://deno.land/std@0.140.0/testing/asserts.ts";

Deno.test("glob", t => {
  const glob = "foobar.part*.rar";
  assert(isGlob(glob));

  assertEquals(globToRegExp(glob), /^foobar\.part[^\/]*\.rar\/*$/);
})

```

**Expected behavior**

The test passes

**Actual behaviour**

The test fails with the following error:

```
error: AssertionError: Values are not equal:


    [Diff] Actual / Expected


-   /^foobar\.part[^/]*\.rar\/*$/
+   /^foobar\.part[^\/]*\.rar\/*$/
```

**Environment**

- OS: Mac 12.3
- deno version: 1.22.0
- std version: 0.140

**Comment by nayeemrmn** [comment]
The slash doesn't need to be escaped in a character range. `/` specifically needs to be escaped when written in a `/.../` JS regexp literal unless it occurs in a `[...]` range. If it wasn't escaped where it needed to be, there would be a syntax error in the lib and it couldn't be returned in a regexp object.

**Comment by sntran** [comment]
That was I was thinking, but turned out I was checking under a Regex engine other than JS one. Sorry for opening an invalid issue.
