### ISSUE TITLE
Add sleepSync helper function

### ISSUE THREAD

**Issue by dsherret** [denoland/deno_std#2268]
Since `Deno.sleepSync` is going to be removed, it would be useful to provide a helper function that uses `Atomics.wait` in deno_std.

- https://github.com/denoland/deno/pull/14719
- https://github.com/denoland/deno/issues/14708#issuecomment-1135707599

**Comment by MKRhere** [comment]
Could use the same implementation from [here](https://github.com/denoland/node_deno_shims/blob/ee4710f96270ba0ed4ceb6f939078404a50fd294/packages/shim-deno/src/deno/stable/functions/sleepSync.ts), which makes it possible to remove it from [both](https://github.com/denoland/node_deno_shims/blob/ee4710f96270ba0ed4ceb6f939078404a50fd294/packages/shim-deno/src/deno/stable/functions/sleepSync.ts) [instances](https://github.com/denoland/node_deno_shims/blob/107791c84edd29b0ea208ad664cec0429e570107/packages/shim-deno/src/deno/unstable/main.ts#L62-L67=) and [the subsequent failing tests](https://github.com/denoland/node_deno_shims/blob/dd07cf3942af8e42b44c499cd121997ed21795d7/packages/shim-deno/tools/run_tests.mjs#L100-L102=) from shims

**Comment by iuioiua** [comment]
Hi @dsherret, to clarify, would you still like to see this added to the repo?

**Comment by lino-levan** [comment]
@dsherret any updates on this? I'm personally against it being added but I think there should be an official decision on this.

**Comment by dsherret** [comment]
I think people can just add the code above to their projects if they really need this... it's super rare that someone would.
