### ISSUE TITLE
`serve` swallows errors when `Response` object body has been consumed already

### ISSUE THREAD

**Issue by aslilac** [denoland/deno_std#2270]
**Describe the bug**

**Steps to Reproduce**

```typescript
await serve(async (req: Request) => {
	const res = await handler(req);
	// Consumes the body! Deno won't be able to read it afterwards!
	console.log("%c <= ", "color: magenta", res.status, await res.text());
	return res;
});
```

**Expected behavior**

Should see some error output that the `Request` object didn't have any body content available to reply with

**Environment**

- OS: [e.g. Ubuntu 20.04, MacOS 11] macOS 12
- deno version: 1.22.0
- std version: 0.140.0

**Comment by iuioiua** [comment]
Hi @aslilac, just clarifying. Are you saying that `handler` somehow consumes `req.body` but calling `req.text()` thereafter doesn’t throw?

**Comment by iuioiua** [comment]
Sorry @aslilac, I didn't read the title. @kt3k, this should be an easy fix - something like:
```ts
  if (res.body instanceof ReadableStream && res.bodyUsed) {
    throw new Error("Response body has already been consumed.");
  }
```
Are there any cases where this check is not desirable? If not, I'll submit the PR.

**Comment by kt3k** [comment]
sounds worth trying to me.
