### ISSUE TITLE
YAML support

### ISSUE THREAD

**Issue by zekth** [denoland/deno_std#231]
As yaml is more and more used everywhere i think it's a nice feature to have in the deno_std.

We can port [js-yaml](https://github.com/nodeca/js-yaml) or [yaml-js](https://github.com/jeremyfa/yaml.js) for example.

Your thoughts?

**Comment by hayd** [comment]
I think [toml](https://github.com/toml-lang/toml) is more popular in the rust community.

Personally I find yaml very brittle...

**Comment by j-f1** [comment]
I’d suggest making a [TOML](https://github.com/toml-lang/toml) parser instead, since YAML is [extremely complex](https://yaml.org/spec/1.2/spec.html). For reference, a quick print-to-PDF yielded an 82-page-long spec for YAML and an 11-page-long spec for TOML (A4 size).

**Comment by zekth** [comment]
I don't like Yaml neither but i have to often use it that's why i'm asking for this. TOML is good too.

If everyone is ok for TOML let's close this one and open one for TOML.

@kevinkassimo  what do you think?

**Comment by ry** [comment]
I'm happy to have both in deno_std

**Comment by kevinkassimo** [comment]
@zekth Why not both? ;)

**Comment by keroxp** [comment]
FYI: https://github.com/nekobato/deno-xml-parser

**Comment by zekth** [comment]
> FYI: https://github.com/nekobato/deno-xml-parser

Nice, would be nice to consider adding it to std. Also having the `.toString()` would be great.
