### ISSUE TITLE
bug(std/_tools): 3rd party import

### ISSUE THREAD

**Issue by timreichen** [denoland/deno_std#2320]
**Is your feature request related to a problem? Please describe.**
`std/_tools/check_circular_deps.ts` is importing a 3rd party mod. std should never import from somewhere other than std.
https://github.com/denoland/deno_std/blob/bcc57478422645cba01b9c75d34938e17ba8a383/_tools/check_circular_deps.ts#L3

**Describe the solution you'd like**
Either remove the tool or have deno_graph be included into std.

**Describe alternatives you've considered**

**Comment by nayeemrmn** [comment]
I think tools not transitively imported by any public module are exempt. Otherwise imported github actions wouldn't be allowed, the only difference is that these are written in Deno/TS.

**Comment by kt3k** [comment]
I agree with Nayeem. Scripts under `_tools/` should be an exception of that rule
