### ISSUE TITLE
Frontmatter parser

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno_std#2333]
It'd be nice to include a front matter parser in std. I always need one in various projects, and considering we already have a yaml parser this should be a trivial addition.

@littledivy wrote up a simple parser a few months ago for an internal project. Maybe we can contribute that one into std?

**Comment by bartlomieju** [comment]
Already done by @kt3k in https://deno.land/x/frontmatter@v0.1.4 

Sounds fine to include it in std
