### ISSUE TITLE
bytes: equalSimd is misleading

### ISSUE THREAD

**Issue by littledivy** [denoland/deno_std#2334]
V8 does not do auto-vectorization. The function should be named `equal32bit`

**Comment by mrkldshv** [comment]
Should we copy `equalsSimd`, rename it to `equals32bit` and deprecate `equalsSimd`?

**Comment by kt3k** [comment]
`equalsSimd` is marked as `@private`, so I believe `equalsSimd` is not part of public API. So I think it's ok to just rename it.

**Comment by mrkldshv** [comment]
Oh yeah, I've missed that it's private. I'll rename it and submit PR.
