### ISSUE TITLE
bug(flags): boolean flag doesn't equal assigned value

### ISSUE THREAD

**Issue by timreichen** [denoland/deno_std#2341]
**Describe the bug**
A flag which is set as a boolean shouldn't be parsed as a boolean if it has a value assigned with the equals sign as described:
> options.boolean - a boolean, string or array of strings to always treat as booleans. if true will treat all double hyphenated arguments without equal signs as boolean (e.g. affects --foo, not -f or --foo=bar).

**Steps to Reproduce**
```ts
import { parse } from "https://deno.land/std@0.143.0/flags/mod.ts";
const args = parse(["--reload=value"], { boolean: ["reload"] });
```
parse returns `{ _:[], reload: true }`

**Expected behavior**
parse should return `{ _:[], reload: "value" }`

**Environment**

- OS: MacOS 12.4
- deno version: 1.22.0
- std version: 0.143.0

**Comment by sigmaSd** [comment]
Maybe this check https://github.com/denoland/deno_std/blob/main/flags/mod.ts#L310 should just be removed and always run `setArg(key, value, arg)` instead?

**Comment by c4spar** [comment]
The returned result is correct here because `--foo=bar` is only parsed as `string` if `boolean` is set to `true`, but in your example it is set to `["verbose"]`, which explicitly marks `verbose` as a boolean argument.

> a boolean, string or array of strings to **always treat as booleans**.

> **if true** will treat all double hyphenated arguments without equal signs as boolean (e.g. affects --foo, not -f or --foo=bar).

But i noticed the value for short flags is wrong:

```ts
import { parse } from "https://deno.land/std@0.143.0/flags/mod.ts";

const args = parse(["-r=value"], { boolean: ["r"] });

const args = parse(["-r=value"], {
  boolean: ["reload"],
  alias: { reload: ["r"] },
});
```

both returns `{ _:[], reload: "value" }`

**Expected behavior**
both should return `{ _:[], reload: true }`

**Comment by timreichen** [comment]
> I think the returned result is correct here because --reload=value is only parsed as string if boolean is set to true, but in your example it is set to ["reload"], which explicitly marks reload as a boolean argument.

**Comment by timreichen** [comment]
Stale
