### ISSUE TITLE
[prettier] Styling option support

### ISSUE THREAD

**Issue by kt3k** [denoland/deno_std#236]
The original prettier cli has the following styling options:

[js/ts styles]
- --print-width <int> Default: 80
- --tab-width <int> Default: 2
- --use-tabs Default: false
- --no-semi Default: true
- --single-quote Default: false
- --trailing-comma <none|es5|all> Default: none
- --no-bracket-spacing Default: true
- --arrow-parens <avoid|always> Default: avoid
- --end-of-line <auto|lf|crlf|cr> Default: auto

[md styles]
- --prose-wrap <always|never|preserve> Default: preserve

How about adding these options to `//prettier/main.ts`?

**Comment by kt3k** [comment]
BTW prettier has the following non-js/ts rule options as well.

[html styles]
- --html-whitespace-sensitivity <css|strict|ignore> Default: css

[jsx styles]
- --jsx-single-quote Default: false
- --jsx-bracket-same-line Default: false

But I think these are out of scope of deno_std

**Comment by j-f1** [comment]
IMO the deno maintainers should pick a set of options they prefer for Deno and not allow configuration so all Deno code will be consistent.

**Comment by zekth** [comment]
As @kitsonk mentionned on Gitter.
```
we just use the (prettier) defaults
```
Also `html` and `jsx` are out of scope yes.

**Comment by ry** [comment]
Certainly "deno --fmt" will be opinionated and have defaults - and I don't think we should worry about exposing configuration there yet. 

However at an API level, it seems reasonable for the deno_std prettier module to support these options
