### ISSUE TITLE
refactor(collections): rename RBTree and BSTree

### ISSUE THREAD

**Issue by timreichen** [denoland/deno_std#2364]
**Is your feature request related to a problem? Please describe.**
The names `RBTree` and `BSTree` are not really consistent with any naming scheme, it should be either the full acronym or the full name, not a mix.

**Describe the solution you'd like**
Use the full name and rename `RBTree` to `RedBlackTree` and `BSTree` to `BinarySearchTree`. Deprecate the two old names.

**Describe alternatives you've considered**

**Comment by bartlomieju** [comment]
Seems reasonable, PRs are welcome

**Comment by timreichen** [comment]
I came across this: https://github.com/denoland/deno_std/blob/5c26306183d0a57f4ae1f4264201b7956526aa01/collections/bs_node.ts#L4
Shouldn't a type be uppercase? If yes, I would rename it in the same PR.

**Comment by timreichen** [comment]
https://github.com/denoland/deno_std/pull/2400
