### ISSUE TITLE
Include missing dotenv key(s) in MissingEnvVarsError

### ISSUE THREAD

**Issue by coloursofnoise** [denoland/deno_std#2366]
**Is your feature request related to a problem? Please describe.**
When loading config from a dotenv file using `config({safe:true})` it can be desirable to add an additional fallback if a key is missing, such as prompting for input from the cmdline.  
Being able to check which keys were not defined by catching `MissingEnvVarsError` would make this more reliable.

**Describe the solution you'd like**
Missing dotenv keys included as a field in `MissingEnvVarsError`.

**Describe alternatives you've considered**
- Hard-coding the required keys
- Reading the `.env.example` file separately to retrieve the required keys
- Attempting to parse the keys from the error message

**Comment by bartlomieju** [comment]
Sounds reasonable, PRs are welcome
