### ISSUE TITLE
Decouple test runner (testing/mod.ts) from the asserts (testing/asserts.ts)

### ISSUE THREAD

**Issue by ry** [denoland/deno_std#237]
That is, remove this:
https://github.com/denoland/deno_std/blob/c734e3234322cea5298a887373fe4ad1591d7c97/testing/mod.ts#L5-L65

This will require updating a lot of call sites across deno_std ... I apologize in advance for the API instability.

cc @zekth @piscisaureus

**Comment by zekth** [comment]
I can handle this :feelsgood:

**Comment by zekth** [comment]
This can be closed.

**Comment by ry** [comment]
thx
