### ISSUE TITLE
WASI: Implement sock_accept() for snapshot1

### ISSUE THREAD

**Issue by sinclairzx81** [denoland/deno_std#2377]
Hi, was wondering if `https://deno.land/std@0.144.0/wasi` could implement the `sock_accept` function on the current preview1 snapshot. I note that this function was included in the WASI snapshot a little while ago (see https://github.com/WebAssembly/WASI/pull/458), but would be quite good to see implemented in Deno (effectively allowing Deno to host network processes implemented in WASM).

Would this be possible?

**Comment by bartlomieju** [comment]
CC @cjihrig

**Comment by cjihrig** [comment]
I think it makes sense to support this.

**Comment by cjihrig** [comment]
There was a bunch of discussion about this today in Discord starting from roughly [here](https://discord.com/channels/684898665143206084/684898665151594506/989832448554700810). This may be blocked on not wanting an op in core for performing `accept()`.

**Comment by iuioiua** [comment]
Closing this, as `std/wasi` is now deprecated. If you still need to use WASI in Deno, use [wasmer-js](https://github.com/wasmerio/wasmer-js) instead.
