### ISSUE TITLE
Please do a Deno existence check in io/buffer.ts BufReader.readline

### ISSUE THREAD

**Issue by johnspurlock** [denoland/deno_std#2391]
I'd like to use std streams in the browser, and the only reference to the Deno ns after bundling is this reference:

https://github.com/denoland/deno_std/blob/09e24d81ce0bacebe81b3c9f683a6ecf9263fc12/io/buffer.ts#L499

Mind doing an existence check here to make sure it runs in the browser?

Thanks,
\- John

**Comment by bartlomieju** [comment]
PRs are welcome

**Comment by johnspurlock** [comment]
@crowlKats I'm actually bundling std streams, and the only reference to buffer is the one I pointed out above, seems like it could be elided if the Deno ns is not present with no issues, unless I'm missing something

Can inspect the bundle output here: https://bundle.deno.dev/https://deno.land/std@0.145.0/streams/mod.ts

**Comment by iuioiua** [comment]
@bartlomieju, is the streams module meant to be web compatible? One would think so. However, there doesn't appear to be any explicit mention of that being the case. If so, the checks mentioned above within the streams module might make sense.

**Comment by iuioiua** [comment]
Actually, it looks as though the block in question can be deleted anyway.

https://github.com/denoland/deno_std/blob/36fa687ecc30b4a69d6bb498afc501cb06bc20d0/io/buffer.ts#L499-L501

The following block takes care of that same condition.

https://github.com/denoland/deno_std/blob/36fa687ecc30b4a69d6bb498afc501cb06bc20d0/io/buffer.ts#L513-L515

This might fix the issue at hand.

**Comment by johnspurlock** [comment]
Thank you!!
