### ISSUE TITLE
Separate logging information from presentation

### ISSUE THREAD

**Issue by Symbitic** [denoland/deno_std#2398]
**Is your feature request related to a problem? Please describe.**

One problem with the log module of the standard library is that it isn't scalable across module boundaries. Different modules may implement a different logging style (no color, different prefixes, etc). This makes it difficult for applications to present a consistent experience and discourages modules from emitting useful debug information.

I think it would be beneficial to separate the logging information from the presentation, thus delegating if/how to print messages to users. A command-line app may wish to print nothing but info messages and fatal errors, while a server app may want to print complex and formatted messages (including verbose debug messages).

**Describe the solution you'd like.**

I've been working on a port from the Qt C++ messaging framework. It's specifically designed to scale to hundreds (if not thousands of modules). By using categorized logging, applications have full control over which messages should be printed, and (if necessary), how to print them.

**Describe alternatives you've considered.**

I considered modifying the `log` module, but this would require breaking changes. The logging module may be used as a way of presenting messages from this module.

**Comment by iuioiua** [comment]
Closing this for the same reason as #2399. Thank you for your suggestion, either way. If there are any sentiments still for this, we can re-open this issue.
