### ISSUE TITLE
node: events.setMaxListeners()

### ISSUE THREAD

**Issue by dahlia** [denoland/deno_std#2402]
**Is your feature request related to a problem? Please describe.**

Node.js introduced [`events.setMaxListeners()` function](https://nodejs.org/dist/latest-v18.x/docs/api/events.html#eventssetmaxlistenersn-eventtargets) since v15.4.0, but deno_std's node compatibility layer lacks this API.  Some existing libraries depending on this API does not work on Deno.

**Describe the solution you'd like**

It would be great if deno_std's node compatibility layer also provides the same name of function.

**Describe alternatives you've considered**

**Comment by geofmureithi** [comment]
@kt3k I want to get into Deno (I have prior Rust and Node experience), Can I take this one?

**Comment by kt3k** [comment]
@geofmureithi yes, please!

**Comment by geofmureithi** [comment]
Looking at the `main` branch, there is this method.
https://github.com/denoland/deno_std/blob/main/node/_events.mjs#L141
@dahlia Am I missing something?

**Comment by dahlia** [comment]
@geofmureithi Node.js provides [module-level `setMaxListeners()` function][1] besides [`EventEmitter.setMaxListeners()` method][2].  Currently deno_std/node only provides the latter.

[1]: https://nodejs.org/dist/latest-v18.x/docs/api/events.html#eventssetmaxlistenersn-eventtargets
[2]: https://nodejs.org/dist/latest-v18.x/docs/api/events.html#emittersetmaxlistenersn

**Comment by geofmureithi** [comment]
Let me make an attempt before the end of the week and see how it goes.
