### ISSUE TITLE
refactor: replace RBTree usage with RedBlackTree

### ISSUE THREAD

**Issue by kt3k** [denoland/deno_std#2404]
We renamed RBTree to RedBlackTree in #2400. We also need to update the usage of them in std.

ex. https://github.com/denoland/deno_std/blob/883fe0f40105f39a5084863f07894670c9d56792/testing/time.ts

**Comment by luk3skyw4lker** [comment]
I'm gonna take this one!

**Comment by bartlomieju** [comment]
I believe this was already done in #2400
