### ISSUE TITLE
'ErrorOptions' is not defined

### ISSUE THREAD

**Issue by WoHal** [denoland/deno_std#2423]
https://github.com/denoland/deno_std/blob/b6118875be9ce83f2392e8b82e42e3e5bbcc66f6/http/http_errors.ts#L99

**Comment by kitsonk** [comment]
What makes you think it isn't defined?

It defined in `lib.es2022.error.d.ts` which is globally scoped and built into current versions of Deno.

**Comment by WoHal** [comment]
Sorry about that. I'm using Deno v1.17.2 which was installed by brew by default, but deno_std is the newest.
