### ISSUE TITLE
In `/archive/tar.ts`, export `TarEntry` as a type

### ISSUE THREAD

**Issue by binyamin** [denoland/deno_std#2425]
**Is your feature request related to a problem? Please describe.**

In the docs for the tar module, [the `Untar.extract()` method](https://doc.deno.land/https://deno.land/std@0.147.0/archive/tar.ts/~/Untar#extract) doesn't fully document its return type. It returns a promise containing `TarEntry`, which is not exported as a type.

**Describe the solution you'd like**

Export the `TarEntry` class as a type.

**Describe alternatives you've considered**

`TarEntry` is both a class and an interface. It may work to just export the interface, but I'm not sure.

**Comment by cuobiezi** [comment]
please refer #2429
