### ISSUE TITLE
(node/crypto): `crypto.timingSafeEqual` is not a function

### ISSUE THREAD

**Issue by yeskunall** [denoland/deno_std#2436]
**Describe the bug**

I tried to use `timingSafeEqual` from Node.js’ Crypto API, expecting it to be available based on #1333, but I get the following error:

```sh
Uncaught TypeError: crypto.timingSafeEqual is not a function
```

**Steps to Reproduce**

```sh
$ deno
> crypto.timingSafeEqual()
Uncaught TypeError: crypto.timingSafeEqual is not a function
    at <anonymous>:2:8
```

**Expected behavior**

```sh
$ deno
> crypto.timingSafeEqual()
Uncaught:
[TypeError: The "buf1" argument must be an instance of ArrayBuffer, Buffer, TypedArray, or DataView.] {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

In #2263 the unimplemented methods were stubbed out. However, in the same PR, the implementation for `timingSafeEqual` was simply moved ([node/_crypto/timingSafeEqual.ts → node/internal_binding/_timingSafeEqual.ts](https://github.com/denoland/deno_std/pull/2263/files#diff-5dbdd2ed5aa33320717e3240744aa09d1d47f4352ed50770caf95a62c6a5e67a)), implying it should be available.

Does that mean the function is simply not available in `deno_std` (stable) yet? Anything (blatantly obvious, even?) I’m missing out? Thanks for the help in advance! 💖

**Environment**

- OS: macOS 12.1
- deno version: `v1.23.3`
- std version: `v0.147.0`

**Comment by SimonRask** [comment]
I think you forgot to run the REPL in compat mode. I got the following:
```bash
$ deno repl --compat --unstable
Deno 1.23.3
exit using ctrl+d or close()
> crypto.timingSafeEqual()
Uncaught TypeError: Cannot read properties of undefined (reading 'byteLength')
    at Object.timingSafeEqual (https://deno.land/std@0.147.0/node/internal_binding/_timingSafeEqual.ts:14:9)
    at <anonymous>:2:8
```

**Comment by yeskunall** [comment]
Ah, looks I need to RTM better. FWIW, here’s where I should have been looking: [Deno Manual > Interoperating with Node and NPM > Node compatibility mode](https://deno.land/manual@v1.23.3/node/compatibility_mode#node-compatibility-mode).

I’ll be closing this now. Thank you @SimonRask and @kt3k!

**Comment by stefnotch** [comment]
Relevant PR for future readers
https://github.com/denoland/deno_std/pull/2503
