### ISSUE TITLE
Don't unnecessarily request to read environment variable

### ISSUE THREAD

**Issue by timfish** [denoland/deno_std#2446]
My library uses some npm dependencies from esm.sh but this causes the user to be prompted for access to the environment due to this code:

https://github.com/denoland/deno_std/blob/8b34f7363501d17b059ab65575b985902ef190ba/node/internal/util/debuglog.ts#L106-L115

It looks like this file is included via `https://deno.land/std@0.148.0/node/process.ts` which esm.sh is injecting because the npm module checks for the existence of `process` to detect node.js.

Since the code falls back to an empty string, would it not be better if it the environment variable was only read if permissions were already granted?

**Comment by iuioiua** [comment]
@timfish, I also attempted this in #2519. However, top-level `await` needs to be avoided in `std/node`.
> We can't use top-level-await in std/node to keep the loading of node/global.ts synchronous. - @kt3k

**Comment by kt3k** [comment]
Right, we can't use top-level-await in `std/node` for compatibility issues.

One option to solve this might be, in my view, to introduce `Deno.permissions.querySync` in Deno CLI, and use that before `Deno.env.get("NODE_DEBUG")` call.

**Comment by iuioiua** [comment]
I like the sound of that 👀. It help with other similar situations.

**Comment by kt3k** [comment]
Deno doesn't ask env permission for accessing `NODE_DEBUG` (ref: https://github.com/denoland/deno/pull/15893)
