### ISSUE TITLE
feature request: base58 encoding

### ISSUE THREAD

**Issue by harrysolovay** [denoland/deno_std#2447]
The [base58 encoding scheme](https://tools.ietf.org/id/draft-msporny-base58-01.html) has become quite popular for a number of use cases. Any thoughts on including a standard implementation in this lib?

**Comment by crowlKats** [comment]
I think it makes sense

**Comment by luk3skyw4lker** [comment]
Also taking this one!

**Comment by mtmulch1** [comment]
Hello, is anyone currently working on this? New around these parts. Correct me if I am wrong and someone else is working on the issue still.

I did not see a standard implementation of Go to port over. 
https://github.com/denoland/deno_std/tree/main/encoding    is the correct location for adding the exported deno stand library functionality of the encoding and test files placed in the same directory?

**Comment by luk3skyw4lker** [comment]
I am currently working on this issue still but this would be the right directory to add the implementation files.

**Comment by harrysolovay** [comment]
Hi @luk3skyw4lker, wondering if there are any updates on this front? It seems others (@mtmulch1) may be interested in implementing this as well.

**Comment by mtmulch1** [comment]
I found another issue in this repository this one is all yours.

**Comment by luk3skyw4lker** [comment]
Hello @harrysolovay 

I'm still finishing the work, there are still some details but I'm planning to open a PR this weekend to finish it

**Comment by luk3skyw4lker** [comment]
BTW, sorry to take so long!

**Comment by harrysolovay** [comment]
@luk3skyw4lker I appreciate you taking on this work –– thank you!

**Comment by luk3skyw4lker** [comment]
Hi everyone! It weren't able for me to open a PR last weekend, but I'm still working on the issue. During the week I keep tangled at work and usually am not able to work here or provide updates, I mostly do the work at weekends, I think that this weekend I'll be able to surely open the PR

**Comment by kt3k** [comment]
implemented in #2539

**Comment by harrysolovay** [comment]
@luk3skyw4lker thank you so much for seeing this through. Very excited to use this.

**Comment by luk3skyw4lker** [comment]
@harrysolovay you're welcome! If there is any bug you can open an issue and tag me already
