### ISSUE TITLE
feature: crypto.timingSafeEqual

### ISSUE THREAD

**Issue by NotFounds** [denoland/deno_std#2449]
**Is your feature request related to a problem? Please describe.**

Comparing two sequences has a risk for [timing attack](https://en.wikipedia.org/wiki/Timing_attack). Nodejs has a function [`crypto.timingSafeEqual`](https://nodejs.org/docs/latest-v18.x/api/crypto.html#cryptotimingsafeequala-b) to compare two sequence constant time. And [`deno_std/node/crypto`] is also supporting it.

Has deno_std already implemented this or an equivalent function? I think it would be good to implement it in deno_std. 

**Describe the solution you'd like**

Implement `crypto.timingSafeEqual(a, b)`.
- a: `Buffer | DataView | ArrayBuffer | string`
- b: `Buffer | DataView | ArrayBuffer | string`

⚠️ Nodejs's `timingSafeEqual` does not support the string type, but there are many cases when you may want to use string.

**Describe alternatives you've considered**

Use `deno_std/node/crypto` or third-party lib.

**Comment by luk3skyw4lker** [comment]
But in the Node.js case the function is implemented natively as C++ code. You're suggesting that we do a Typescript version of it?

**Comment by kitsonk** [comment]
This already exists in std. https://deno.land/std@0.152.0/crypto/mod.ts?s=StdSubtleCrypto#method_timingSafeEqual_2
