### ISSUE TITLE
http/http_errors: Optional headers argument

### ISSUE THREAD

**Issue by timonson** [denoland/deno_std#2451]
The class `HttpError` doesn't have a `headers` property. I would suggest that an optional `headers` property and argument for `createHttpError`  might be useful for cases like `Unauthorized, 401` where a `WWW-Authenticate` header would be required.

@kitsonk would you agree to this?

Thanks!

**Comment by kitsonk** [comment]
Could you give a better example of how you expect it work?

**Comment by timonson** [comment]
Maybe something like this https://github.com/denoland/deno_std/pull/2462 ?
