### ISSUE TITLE
readerFromStreamReader potentially dropping the last value returned from a ReadableStreamDefaultReader?

### ISSUE THREAD

**Issue by jmandel** [denoland/deno_std#2455]
Looking at the conversion at:

https://github.com/denoland/deno_std/blob/86c7d8ad4505ee61ca992e8c08159905e8bd8c61/streams/conversion.ts#L85-L88

Isn't it possible that within the `if (res.done)` branch, `res.value` contains one final chunk of data that's being ignored by this conversion routine? My question is just based on the type definition for `res`, which would be  a `ReadableStreamReadDoneResult<Uint8Array>`, and therefore could optionally contain a `value`:

```
interface ReadableStreamReadDoneResult <T> {
done: true;
value?: T;
}
```

**Comment by 0f-0b** [comment]
As per the [standard](https://streams.spec.whatwg.org/#default-reader-read), `value` will always be `undefined` when `done` is `true`. The type definition in `lib.deno_web.d.ts` seems misleading here.

**Comment by jmandel** [comment]
Thanks for the quick response. I'll close this and open a separate issue on `lib.deno_web.d.ts`.
