### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno_std#2483]
`README.md` should be updated. 

- "Releases" section is a bit lacking in explanation why different versioning
- "How to use" needs to be reworded, it's often coming up in comments that devs don't use "deno_std" because it's still unstable.
We should better communicate information about stability and inform that even if there's a breaking change users can use specific modules with pinned version of previously released `deno_std`
- Contributing section needs a refresh

**Comment by iuioiua** [comment]
@bartlomieju, I think we can close this issue now. WDYT?

**Comment by bartlomieju** [comment]
Sounds good 👍
