### ISSUE TITLE
testing/mock.ts: Allow stubbing non existent instance methods

### ISSUE THREAD

**Issue by jespertheend** [denoland/deno_std#2486]
**Is your feature request related to a problem? Please describe.**

When writing unit tests, I often run into issues when importing an entire dependency. That's why I usually create a minimal version of the dependency that only implements a few methods required for the test to work.
I then cast the mock object to the original object, so that it can still be passed in existing apis.
When using `stub()` on these (cast) objects, I'm not getting any type errors, but at run time an error is thrown:
```
property is not an instance method
```

This often leads me to using patterns like
```js
mockObject.mockFunction = () => {}
stub(mockObject, "mockFunction", () => {});
```

In cases where the function is expected to return a value, this is even more tedious because I have to either `@ts-ignore`, cast, or actually return an object with the correct type in the first function. At that point I might as well not use `stub()` at all and just assign the function directly.

**Describe the solution you'd like**

Allow stubbing methods when they don't exist, and don't throw the following error when a property is `undefined`:
https://github.com/denoland/deno_std/blob/3ea3c9fad88575bf1ff373e2bb9ebcea05d391a2/testing/mock.ts#L386-L388

**Describe alternatives you've considered**

- The alternative described above works for now.
- Not using `stub()` and assigning the function directly also works, but this doesn't benefit from autocompletion, which `stub()` does have.

**Comment by jespertheend** [comment]
@KyleJune do you see any immediate issues with this? Removing that error doesn't cause any tests to fail, but maybe I'm missing something obvious.

**Comment by jespertheend** [comment]
> Does the mockObject's interface have a mockFunction on it

Yeah it does, but only by way of casting. A minimal example would be something like

```js
import {stub} from "https://deno.land/std@0.150.0/testing/mock.ts";

class TheRealClass {
	theMethod(num: number): boolean {
		return true;
	}

	someOtherMethod() {
		return true;
	}
}

class TheStubClass {
	
	// theMethod() not implemented
	
	someOtherMethod() {
		return true;
	}
}

function createStubClass() {
	const instance = new TheStubClass();
	const castInstance = instance as TheRealClass;
	return {
		instance,
		castInstance,
	}
}

const {castInstance} = createStubClass();
stub(castInstance, "theMethod");
```

In this case `createStubClass()` is a function that is shared between multiple tests, not all tests need `theMethod()` so it isn't implemented by default. This causes the `stub()` call at the last line to fail. But since the `castInstance` has the type `TheRealClass`, no type errors are generated in this case. Unless `"theMethod"` is misspelled yeah.

> The change would need to include test coverage for the restore behavior.

Yeah I figured, I reckon simply removing the thrown error isn't enough and it will probably cause some other errors where the object is expected to have a function. I'll try to get something working later today.

> I believe spying should still require the method to exist.

I think that would make sense, there won't be a need to spy on non existent functions anyway.

**Comment by jespertheend** [comment]
Seems like restoring already works out of the box :D
I've opened #2487

**Comment by kt3k** [comment]
@jespertheend 
> const castInstance = instance as TheRealClass;

Why not just provide empty `theMethod` implementation here instead of type casting?

This change to `stub` seems to make it confusing to me.

**Comment by jespertheend** [comment]
Adding an empty method implementation will cause a type error when casting `instance as TheRealClass`.
This can be worked around by casting like `instance as unknown as TheRealClass`. But makes all the other methods of the stub class less type safe.
Another workaround is to make the `theMethod` return either a valid type, or some value cast as a valid type. In the example above I'd probably go that route, but if the required return value is more complex than just a boolean, this gets pretty tedious. Especially if you end up `stub()`ing it again without ever using the empty method.

Another option would be to not use `stub()` at all and simply implement the stub method in `TheStubClass` directly, but this doesn't benefit from autocompletion. And in general I think it makes more sense if the implementation lived close to the test that depends on it. Otherwise you'd end up with a large stub class where every method is intended for a different test.

**Comment by kt3k** [comment]
> Another workaround is to make the theMethod return either a valid type, or some value cast as a valid type. In the example above I'd probably go that route, but if the required return value is more complex than just a boolean, this gets pretty tedious.

I guess `return {} as any` works for any return type, doesn't it?

I didn't know that `instance as TheRealClass` in the above example doesn't cause type error, but it feels very strange as it's actually not type safe at all.. 🤔

**Comment by jespertheend** [comment]
> I guess `return {} as any` works for any return type, doesn't it?

Ah yeah, that should do it!

> but it feels very strange as it's actually not type safe at all

Yeah it's definitely not ideal. I keep running into runtime errors and then it turns out some method of a mock class isn't implemented. Ideally I would not have to create a mock class at all, so I can just use the real thing and stub a few of its methods. But when doing this I often run into issues where a class constructor requires the dom or some network functionality. And afaik constructors can't easily be stubbed.

Anyway, I thought the thrown error was unnecessary since `stub()` is working fine even if no method exists yet. But if you feel like this change seems confusing I can probably cast my way around this.

**Comment by kt3k** [comment]
Ok. Let's try it
