### ISSUE TITLE
XML support

### ISSUE THREAD

**Issue by iugo** [denoland/deno_std#2488]
XML is common. It would be nice if the standard library could support XML to JS and some JS to XML.

**Is your feature request related to a problem? Please describe.**

Just like: https://github.com/denoland/deno_std/issues/231, https://github.com/denoland/deno_std/issues/431

**Describe the solution you'd like**

https://www.npmjs.com/package/xml2js

**Describe alternatives you've considered**

**Comment by crowlKats** [comment]
There is #2471, however it seems a bit questionable whether it will be part of std

**Comment by tjosepo** [comment]
While this might not be the answer you're looking for, most DOM parsers are able to parse XML as well:

```js
import { DOMParser } from "https://esm.sh/linkedom@0.14.14";

const xml = `
  <note>
    <to>Tove</to>
    <from>Jani</from>
    <heading>Reminder</heading>
    <body>Don't forget me this weekend!</body>
  </note>
`;

const document = new DOMParser().parseFromString(xml, "text/xml");
const to = document.querySelector("to").innerText;
const from = document.querySelector("from").innerText;
console.log("To: " + to + ", from: " + from); // => "To: Tove, from: Jani"
```

**Comment by lino-levan** [comment]
I feel like there should be a decision made by either the core team or the community on whether or not XML parsing should be in std. My sense is that it is overly complicated and there are already /x/ libraries for it, but I'm curious to hear from not just myself.

**Comment by iuioiua** [comment]
I'm -1 on this. I don't see a benefit of a implementation in std if existing third party modules work great. I've used a couple of them before.

**Comment by cjihrig** [comment]
@iuioiua do you have a few that you'd like to recommend here? I know I'm personally not super excited at the thought of maintaining an XML library unless absolutely necessary 😄

**Comment by iuioiua** [comment]
I've used and recommend:
1. [xml2js](https://deno.land/x/xml2js) - converts xml to a straightforward and easy to work with JS object.
2. [xml](https://deno.land/x/xml) - probably more extensive and mimics the familiar JSON API (`parse` and `stringify`)

**Comment by cjihrig** [comment]
I'm going to close this out based on the feedback in https://github.com/denoland/deno_std/pull/2471, as well as the availability of third party modules.
