### ISSUE TITLE
Use AssertionError in testing/asserts

### ISSUE THREAD

**Issue by ry** [denoland/deno_std#249]

**Comment by bartlomieju** [comment]
Reference of last try: https://github.com/denoland/deno_std/pull/209/files/509735750813a2191790d06a9f0d9a26953f274a#diff-21d94e5c829319e0d4c4acd5e1cc2bd3

**Comment by zekth** [comment]
Maybe an addition to AssertionError would be:
```ts
export class AssertionError extends Error {
  constructor(message: string,assertType:string, actual:unknown,expected:unknown) {
    super(message);
    this.name = "AssertionError";
    this.actual = actual;
    this.expected = expected;
    this.assertType = assertType;
  }
}
```

By then, then render in the prompt and console would be in the AssertionError classe instead of each assert. Ex;
```ts
export function assertMatch(
  actual: string,
  expected: RegExp,
  msg?: string
): void {
  if (!expected.test(actual)) {
    const ex = new AssertionError(msg,'assertMatch',actual,expected)
    ex.render(); // call console.error and more. Like writing results in a file for example for CI reports
    throw ex;
  }
}
```

Thoughts?

**Comment by bartlomieju** [comment]
@zekth lets not reinvent the wheel, you could override `toString()` method.

**Comment by zekth** [comment]
Fair point. For the rest, seems fine?

**Comment by bartlomieju** [comment]
`AssertionError` is now used in `testing/asserts.ts` so I guess this issue can be closed
