### ISSUE TITLE
docs: remove types in jsdoc @param directive

### ISSUE THREAD

**Issue by kt3k** [denoland/deno_std#2493]
We sometimes write jsdoc `@param` directive like the below:
```
@param {string} name Name of cookie
```

But, this should be:
```
@param name Name of cookie
```
as we use typescript.

**Comment by iuioiua** [comment]
Easy. I’m happy to do this! 🤙🏾

**Comment by iuioiua** [comment]
Should we also do the same for the `@return` directive?

**Comment by kt3k** [comment]
> Should we also do the same for the @return directive?

I think so!
