### ISSUE TITLE
docs: change example for `readableStreamFromReader` and `writableStreamFromWriter`

### ISSUE THREAD

**Issue by erfanium** [denoland/deno_std#2505]
Currently doc examples suggests using `readableStreamFromReader` and `writableStreamFromWriter` to get a `readableStream` or `writeableStream` from a `FsFile` which is not required anymore after https://github.com/denoland/deno/pull/13615

bad docs: 
- https://deno.land/std@0.151.0/streams/mod.ts?s=readableStreamFromReader

**Comment by crowlKats** [comment]
Things can still just be a `Deno.Reader` or `Deno.Writer`, as one can just create an object with the required functions, so having `readableStreamFromReader` & `writableStreamFromWriter` still makes sense.

**Comment by erfanium** [comment]
@crowlKats Yeah, I'm now changing this issue to improve docs, because docs are still suggests readableStreamFromReader to read from FsFile

**Comment by lino-levan** [comment]
@kt3k with this being deprecated, we can probably close this issue.

**Comment by kt3k** [comment]
Thanks for the ping.

Closing as these APIs have been deprecated in #3640
