### ISSUE TITLE
ci: `Generate lcov` step fails on CI

### ISSUE THREAD

**Issue by kt3k** [denoland/deno_std#2517]
Recently `Generate lcov` step started failing on CI.

It was successful at e5d48464bf8a6bc6ea49d8e5054c7fb957fb66c7 (16 hours ago). I guess something has been changed in CLI canary

**Comment by kt3k** [comment]
https://github.com/denoland/deno/pull/15459 might be related

**Comment by kt3k** [comment]
tested with the canary versions `e4a5f9952f404e10f1b577b1477b89b155092b67` and `c3b04683c55fef8929e83429ec17b7a6898c6048`.

`c3b04683c55fef8929e83429ec17b7a6898c6048` (denoland/deno#15459) seems to have started this behavior

**Comment by disjukr** [comment]
It seems fixed in https://github.com/denoland/deno/pull/15467
