### ISSUE TITLE
dotenv forces apps to grant access to all env vars, possibly allowing attackers to read Envs not consumed by the app on purpose

### ISSUE THREAD

**Issue by mechanoid** [denoland/deno_std#2534]
### Discussed in https://github.com/denoland/deno_std/discussions/2533

<div type='discussions-op-text'>

<sup>Originally posted by **mechanoid** August 19, 2022</sup>
At first let me say how great it is, that dotenv is now part of the STD. 

I was wondering though, why it uses `Deno.env.toObject()` to parse all env variables, without ability to restrict which Env vars are of interest for the app/library.

This leaves no choice but to run the script with a global `--allow-env` possibly allowing an attacker to access all env vars provided to the apps host. 

I think the `dotenv.config()` method (as well as `dotenv/load()`) should be able to take a list of ENV var names and restrict the lookup to those. This would allow to provide a more restricted access to only a subset of the Envs with `--allow-env=SOME_VAR,...`) </div>

**Comment by kt3k** [comment]
closed in #2544.

@mechanoid Thank you for your suggestion!

**Comment by mechanoid** [comment]
Very welcome!
