### ISSUE TITLE
compat: `parallel/test-stream-writable-final-destroy.js` is broken

### ISSUE THREAD

**Issue by kt3k** [denoland/deno_std#2542]
https://github.com/denoland/deno/pull/15522 seems to have broken `parallel/test-stream-writable-final-destroy.js` compat test case.

You can check it with the below steps:
```sh
deno upgrade --canary --version e96933bc163fd81a276cbc169b17f76724a5ac33
deno task node:test -- parallel/test-stream-writable-final-destroy.js   
deno upgrade --canary --version 97954003cc87b664768918173e8d00f6df35e04f
deno task node:test -- parallel/test-stream-writable-final-destroy.js   
```

**Comment by nayeemrmn** [comment]
I suppose this was an already broken test, there were failed assertions within the callback passed to `queueMicrotask()` which were swallowed previously.

**Comment by kt3k** [comment]
Ah, makes sense. It was just a false negative

**Comment by kt3k** [comment]
Let's track in `tools/node_compat/TODO.md` in denoland/deno repo.
