### ISSUE TITLE
Feature request: Webstream-based parser for CSV with headers

### ISSUE THREAD

**Issue by ayame113** [denoland/deno_std#2559]
I think we need a way to parse a CSV with headers while streaming the file contents.
For example something like this:

```ts
Deno.openSync("path/to/csv").readable
  .pipeThrough(new CSVStream({ header: true }))
  .pipeTo(...)
```

Previously this was possible via the Deno.reader interface. Since the csv.ts parse function has become synchronous, there is no way to do this anymore. ( #2491 )

I think we need a new method based on Web Streams instead of the Deno.reader interface used previously.

### prior art

[csv-string](https://www.npmjs.com/package/csv-string), a CSV parser for Node.js, can parse a csv with headers and convert it to an array of objects.

```ts
const CSV = require('csv-string');
const parsedCsv = CSV.parse('a,b,c\n1,2,3\n4,5,6', { output: 'objects' });
console.log(parsedCsv);
// [
//   { a: '1', b: '2', c: '3' },
//   { a: '4', b: '5', c: '6' }
// ]
```

The [python standard library](https://docs.python.org/3/library/csv.html#csv.DictReader) also supports this.

```py
import csv
with open('names.csv', newline='') as csvfile:
  reader = csv.DictReader(csvfile)
  for row in reader:
    print(row['first_name'], row['last_name'])
```

related: https://github.com/denoland/deno_std/issues/2291

**Comment by luk3skyw4lker** [comment]
I have an open PR that makes it possible to parse csv files with no headers. I'll make it work with the new stringify version this weekend, it's in #2168

**Comment by lino-levan** [comment]
@luk3skyw4lker any updates?

**Comment by luk3skyw4lker** [comment]
@lino-levan the PR is already merged, @kt3k @bartlomieju is this issue solved with the mentioned PR?

**Comment by ayame113** [comment]
There are currently two types of CSV parsers/stringify: WebStream-based and non-stream (converting strings).
As of today, it should look like this:

||string based|web stream based|
|--|--|---|
|**stringify**|<ul><li>`encoding/csv.ts`</li><li>Can handle CSV with headers</li></ul>|N/A|
|**parse**|<ul><li>`encoding/csv.ts`</li><li>Can handle CSV with headers</li></ul>|<ul><li>`encoding/csv/stream.ts`</li><li>**Cannot** handle CSV with headers</li></ul>|

What I'm proposing is to allow webstream based parsers to parse CSV with headers.
So I think this issue should still be left open.
