### ISSUE TITLE
Testing: mock functions

### ISSUE THREAD

**Issue by sh7dm** [denoland/deno_std#256]
Mock functions like [in Jest](https://jestjs.io/docs/en/mock-functions.html)

**Comment by zekth** [comment]
The mock / stubing func is a huge and complicated task. It might be better to have it in a separate module

**Comment by ry** [comment]
@sh7dm Can you give an example of what you'd like to be able to do? I'm certainly not going to port all of Jest over - so let's consider this case by case. What is the functionality, specifically, you want?

**Comment by sh7dm** [comment]
E.g. I want to make sure callback or other function has been called 2 times, or w/ specific args. Maybe even some **SIMPLE** hack implementation for it, e.g. if mocking important internal function

**Comment by zekth** [comment]
for example:
```javascript
test(function testConnection() {
  global.fetch = jest.fn().mockImplementation(() => {
    var p = new Promise((resolve) => {
      resolve({
        ok: true,
        status: 200
      })
    })
    return p
  })
  let r = myfunctionUsingAjax();
  assert(global.fetch.haveBeenCalled());
  assert(r===whatever)
});
```

By this way you ensure the response of the usage of the function. But if we do this way we have also to mock imports like this: https://jestjs.io/docs/en/es6-class-mocks

**Comment by kt3k** [comment]
How about the testdouble.js as a candidate of mocking library? This seems more simple, and not coupled to any framework.
https://github.com/testdouble/testdouble.js/

**Comment by j-f1** [comment]
Looks like it requires porting since it doesn’t use extensions in its imports.

**Comment by zekth** [comment]
> Looks like it requires porting since it doesn’t use extensions in its imports.

so quibble also has to be ported too i guess? https://github.com/testdouble/quibble
This would be nice to add to `Denolib` as it's tied to `lodash` and `quibble` and the `deno_std` is dependency free?
