### ISSUE TITLE
is `Promise.All` a typo or a thing?

### ISSUE THREAD

**Issue by ydcjeff** [denoland/deno_std#2566]
I just tested Vite to run in Deno and faced `Promise.All` is not a function. Since I am not sure this is a bug, I am opening a blank issue. I have found that in many places on the codebase.

https://github.com/denoland/deno_std/blob/fa6c014902d834203914afa9a77d83c69c60c228/node/internal/streams/writable.mjs#L937

https://github.com/denoland/deno_std/blob/3ea3c9fad88575bf1ff373e2bb9ebcea05d391a2/node/internal/streams/duplex.mjs#L201

https://github.com/denoland/deno_std/blob/3ea3c9fad88575bf1ff373e2bb9ebcea05d391a2/node/internal/streams/duplex.mjs#L293

**Comment by iuioiua** [comment]
Wow. Interesting find! I'll look into this.

**Comment by iuioiua** [comment]
Oh, and yeah, that's certainly a typo.
