### ISSUE TITLE
http:add alpnProtocol to ConnInfo

### ISSUE THREAD

**Issue by masx200** [denoland/deno_std#2572]
**Is your feature request related to a problem? Please describe.**
https://github.com/denoland/deno_std/blob/36fa687ecc30b4a69d6bb498afc501cb06bc20d0/http/server.ts#L20

http:add alpnProtocol to ConnInfo

**Describe the solution you'd like**
```ts
export type ConnInfo = Readonly<{
    /** The local address of the connection. */
    readonly localAddr: Deno.Addr;
    /** The remote address of the connection. */
    readonly remoteAddr: Deno.Addr;
    alpnProtocol: string | null;
}>;
```

**Describe alternatives you've considered**

Support http2 to prepare ahead of time in the future.

**Comment by lino-levan** [comment]
With `std/http/server.ts` essentially being deprecated (with `ConnInfo` being part of that), I don't think this issue makes much sense anymore. Thoughts @kt3k?

**Comment by kt3k** [comment]
Agree. Let's close.
