### ISSUE TITLE
assertion diff for "Expected" is barely readable

### ISSUE THREAD

**Issue by littledivy** [denoland/deno_std#2575]
Bg green on white text makes it very hard to read anything. It should have some contrast. 

https://github.com/denoland/deno_std/blob/fa6c014902d834203914afa9a77d83c69c60c228/testing/_diff.ts#L383

![image](https://user-images.githubusercontent.com/34997667/187204710-1acc9f7f-9807-419f-962e-47dac78c14e4.png)

**Comment by lucacasonato** [comment]
Agreed. Black on green seems much better.
