### ISSUE TITLE
suggestions(CI): minor changes and updates

### ISSUE THREAD

**Issue by iuioiua** [denoland/deno_std#2577]
I have a few suggestions that could be made to the current workflows, mostly as a matter of maintenance. I'm happy to implement.
1. Upgrade to `actions/checkout@v3` ([changelog](https://github.com/actions/checkout/blob/main/CHANGELOG.md))
2. Upgrade to `denoland/setup-deno@v1` to ensure the latest `v1` version is being used ([changes](https://github.com/denoland/setup-deno/releases)) and to use the latest stable Deno version by default
3. Move `Check circular dependencies` and `Check License headers` steps within the `lint` routine to the Deno task runner. This enables devs to do these checks on their machines before submitting PRs.

**Comment by bartlomieju** [comment]
> Upgrade to actions/checkout@v3 ([changelog](https://github.com/actions/checkout/blob/main/CHANGELOG.md))

👍 

- Upgrade to denoland/setup-deno@v1 to ensure the latest v1 version is being used ([changes](https://github.com/denoland/setup-deno/releases)) and to use the latest stable Deno version by default

We want to test `deno_std` against latest canary. Ideally we could run tests against latest stable and canary to catch up more regressions (if a CI pipeline was kicked off after CI passes in `deno` repo that would be even better).

> Move Check circular dependencies and Check License headers steps within the lint routine to the Deno task runner. This enables devs to do these checks on their machines before submitting PRs.

Makes sense 👍 

Thanks for looking into this!

**Comment by iuioiua** [comment]
> We want to test `deno_std` against latest canary. Ideally we could run tests against latest stable and canary to catch up more regressions (if a CI pipeline was kicked off after CI passes in `deno` repo that would be even better).

Sorry, to clarify, I was initially referring to just the `version_bump` workflow. Nevertheless, adding latest stable to the testing matrix will make the footprint of CI workflows bigger. I'm happy to implement this but just checking, are you sure you'd like this done?

**Comment by kt3k** [comment]
resolved in #2578 #2579 #2580. Thanks @iuioiua for the PRs!
