### ISSUE TITLE
bug(async): `delay` is not browser compatible

### ISSUE THREAD

**Issue by iuioiua** [denoland/deno_std#2598]
[async/delay.ts](https://github.com/denoland/deno_std/blob/5a3206d6eb96a693b90c3c64c5106dc41ccfbae4/async/delay.ts) is not browser compatible. However, it has the header claiming that it is. Reason being is the use of `Deno.unrefTimer()` for the `persistent` option (which I added 😅).
What is the best way to fix such an issue?
1. Somehow check for the existence of the `Deno` namespace and function?
2. Remove the `// This module is browser compatible.` header?
3. Revert the blocking functionality to restore browser compatibility?

**Comment by kt3k** [comment]
No.1 looks an ideal approach to me

BTW it's concerning that our CI doesn't catch this situation...

**Comment by iuioiua** [comment]
What’s the usual method of doing so?

**Comment by kt3k** [comment]
I think the code like the below should work on both Deno and non-Deno runtimes.

```ts
if (typeof Deno !== "undefined") {
  // deno specific code
} else {
  // handle non deno environment
}
```

**Comment by iuioiua** [comment]
> I think the code like the below should work on both Deno and non-Deno runtimes.
> 
> ```ts
> if (typeof Deno !== "undefined") {
>   // deno specific code
> } else {
>   // handle non deno environment
> }
> ```

Yeah, one would think that'd be the answer but it throws in the browser. The solution ended up being a `try`/`catch` as you see in the PR.

> BTW it's concerning that our CI doesn't catch this situation...

I believe this is due to the current way `deno task test:browser` works, namely `browser-compat.tsconfig.json`. `Deno` namespace not being defined is causing an issue. I don't know what the solution is but the `// @ts-nocheck Bypass static errors for missing --unstable.` header appears to be a workaround.

**Comment by 0f-0b** [comment]
> Yeah, one would think that'd be the answer but it throws in the browser. The solution ended up being a `try`/`catch` as you see in the PR.

What did it throw? I tested the code below in a browser and it logs the message to the console without throwing an error.

```ts
if (typeof Deno !== "undefined") {
  unrefTimer(i);
} else {
  console.error(
    "Persistent option is only available within the Deno runtime.",
  );
}
```

**Comment by iuioiua** [comment]
It threw `ReferenceError`. However, I tried a comparison which I incorrectly thought would be equivalent:
```ts
if (!persistent && Deno) {
  Deno.unrefTimer(i);
} else {
  // false case
}
```
I should've tried the recommended method exactly first. `typeof Deno === "undefined"` works fine.
