### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'writeSync')

### ISSUE THREAD

**Issue by medamin25** [denoland/deno_std#2605]
**Describe the bug**
I get error `TypeError: Cannot read properties of undefined (reading 'writeSync')`
when using `printf` from https://deno.land/std@0.154.0/fmt/printf.ts

**Steps to Reproduce**

1. Create a **Deno Deploy** sample project at https://dash.deno.com/projects with the contents ...
```typescript
import { serve } from "https://deno.land/std@0.154.0/http/server.ts"
import { printf } from "https://deno.land/std@0.154.0/fmt/printf.ts"

serve((req: Request) => {
    const str = "Hello World"
    printf("%s\n",str)
    return new Response(str)
})
```
2. Ensure project type is **Typescript**
3. Click **Save & Depoy** button
4. See Error
```log
europe-west8isolate start time: 1.97 ms

Listening on http://localhost:80/

TypeError: Cannot read properties of undefined (reading 'writeSync')
    at printf (https://deno.land/std@0.154.0/fmt/printf.ts:703:17)
    at Server.<anonymous> (file:///src/main.ts:5:5)
    at Server.#respond (https://deno.land/std@0.154.0/http/server.ts:219:43)
    at Server.#serveHttp (https://deno.land/std@0.154.0/http/server.ts:253:26)
```
**Expected behavior**

- variable `str` get printed to console

**Environment**

- OS: [Deno Deploy](https://deno.com/deploy)
- deno version: https://deno.com/deploy
- std version: `std@0.154.0`

**Comment by medamin25** [comment]
- Also the same error occurred with `sprintf`
- Error persist with both project type **typescript** and **javascript**

**Comment by iuioiua** [comment]
Hi @medamin25, `printf()` calls `Deno.stdout.writeSync()`, which appears to not be supported on Deno Deploy (check the [API reference](https://deno.com/deploy/docs/runtime-api)).

@kt3k, would it be worth changing `printf()` to use `console.log()` instead? I'm not sure what advantage `Deno.stdout` offers in this context and believe compatibility might be more important.

**Comment by iuioiua** [comment]
Actually, I realise the purpose of `printf()` is to take care of the rounding of numbers. If you just want to print format plain strings, you're better of using:
```ts
const str = "Hello World";
console.log("%s\n", str);
```


> Hi @medamin25, `printf()` calls `Deno.stdout.writeSync()`, which appears to not be supported on Deno Deploy (check the [API reference](https://deno.com/deploy/docs/runtime-api)).
> 
> @kt3k, would it be worth changing `printf()` to use `console.log()` instead? I'm not sure what advantage `Deno.stdout` offers in this context and believe compatibility might be more important.

Ignore this.

**Comment by medamin25** [comment]
ok thank you

**Comment by iuioiua** [comment]
@kt3k, I believe this can be closed.
