### ISSUE TITLE
suggestion: deprecate `std/textproto`

### ISSUE THREAD

**Issue by iuioiua** [denoland/deno_std#2609]
AFAIK, `std/textproto` has been made obsolete by [`Deno.serveHttp()`](https://doc.deno.land/deno/stable/~/Deno.serveHttp) and [`Deno.serve()`](https://doc.deno.land/deno/unstable/~/Deno.serve) (unstable). Plus, the standard library also has other better tools for working with line-by-line, text-based data.

**Comment by iuioiua** [comment]
@kt3k and @bartlomieju, what do you guys think?

**Comment by kt3k** [comment]
The suggestion makes sense to me. We don't have a usage of `TextProtoReader` anymore since https://github.com/denoland/deno_std/pull/1648 . Also we've been moving to ReadableStream-based design everywhere. I agree we probably don't use `TextProtoReader` for anything in the future.

**Comment by kt3k** [comment]
We found that `std/textproto` has relatively high number of download count even today (according to the access log). We are now investigating the count by version number to make sure that heavily used versions are only old versions

**Comment by iuioiua** [comment]
> We found that `std/textproto` has relatively high number of download count even today (according to the access log). We are now investigating the count by version number to make sure that heavily used versions are only old versions

Alright! No worries.

**Comment by kt3k** [comment]
We discussed this internally, and we are in favor of deprecation.

Thank you for your suggestion! @iuioiua
