### ISSUE TITLE
implement fs-extra api for fs modules

### ISSUE THREAD

**Issue by axetroy** [denoland/deno_std#261]
[fs-extra](https://github.com/jprichardson/node-fs-extra) is a useful tool to process file. most of `node` library depends on it.

suffice to say that it is very useful.

I am going to implement it with `deno`.

- [x] readFileStr #276
- [x] writeFileStr #340 
- [x] copy #278
- [x] emptyDir #263
- [x] ensureFile #264
- [x] ensureDir #264
- [x] ensureLink #353
- [x] ensureSymlink #268
- [x] move #266
- [ ] ~remove #275~
- [x] exists #260
- [x] readJson #269
- [x] writeJson #271

**Comment by zekth** [comment]
Another idea would be to add rimraf function? like `rm -rf` ?

**Comment by shisama** [comment]
> Another idea would be to add rimraf function? like rm -rf ?

Is it `await Deno.remove("/path/to/dir", {recursive: true});` ?

https://deno.land/typedoc/index.html#remove

**Comment by zekth** [comment]
You're right my bad

**Comment by axetroy** [comment]
I think we should add this API alias to `Deno.remove` avoid to switch between `Deno` and `fs` API

```typescript
fs.remove(); // same with Deno.remove()
```

**Comment by zekth** [comment]
Add in the task list : Write the readme.MD of the module.

Would you want me to write it?

**Comment by axetroy** [comment]
@zekth ok, you do it

**Comment by GrosSacASac** [comment]
Hi please consider adding safe delete (move to trash-bin)

**Comment by zekth** [comment]
> Hi please consider adding safe delete (move to trash-bin)

I think move to trash bin may have it's place in another repository instead of being into the std lib.

**Comment by zekth** [comment]
Adding this for readfilestr ref: https://github.com/denoland/deno_std/pull/276

**Comment by lisniuse** [comment]
I think that shortcuts like fs-extra should be placed in a non-standard library.

**Comment by axetroy** [comment]
@GrosSacASac
sorry for late response.

**move to trash** have third party dependence. it should add to std.
