### ISSUE TITLE
`deno test` create incorrect order snapshot object

### ISSUE THREAD

**Issue by loynoir** [denoland/deno_std#2612]
```ts
import { assertSnapshot } from "https://deno.land/std@0.152.0/testing/snapshot.ts";

Deno.test('reproduce', async (t) => {
  assertSnapshot(t, { type: 'foobar', start: 0, end: 42 })
})
```

### Reproduce
```ts
$ deno test -A -- --update
```

### Actual
```sh
$ cat __snapshots__/ast_test.ts.snap
export const snapshot = {};

snapshot[`reproduce 1`] = `
{
  end: 42,
  start: 0,
  type: "foobar",
}
`;
```

### Expected
```sh
$ cat __snapshots__/ast_test.ts.snap
export const snapshot = {};

snapshot[`reproduce 1`] = `
{
  type: "foobar",
  start: 0,
  end: 42,
}
`;
```

**Comment by kt3k** [comment]
The keys are intentionally sorted in serialized format https://github.com/denoland/deno_std/blob/9c6ffb8c21cdc6d48010c944cbfde815be5c9273/testing/snapshot.ts#L71

**Comment by loynoir** [comment]
> The keys are intentionally sorted in serialized format
> 
> https://github.com/denoland/deno_std/blob/9c6ffb8c21cdc6d48010c944cbfde815be5c9273/testing/snapshot.ts#L71

I think snapshot kind of refers to WYSIWYG, what-you-see-is-what-you-get.

AFAIK, `deno_std/testing/snapshot` is the only snapshot implement which sort object, different from other assert library implement.

Thus, I think it's a bad design.

**Comment by kitsonk** [comment]
Incorrect, Jest sorts snapshots alphabetically, to make them stable: https://github.com/facebook/jest/issues/3936 and is the standard in this space. It is not a poor design decision. Unstable snapshots would be.

Closing, as it is standard to sort keys in snapshot objects.
