### ISSUE TITLE
add defer feature of Golang for testing

### ISSUE THREAD

**Issue by axetroy** [denoland/deno_std#262]
`defer` in Golang is easy is useful especially in the test.

eg.

```go
func TestSomething(t *testing.T) {
	filename := "test.go"
	CreateFile(filename)

	defer func() {
		RemoveFile(filename)
	}
}
```

do the same thing in `Deno`

```typescript
test(async ({ defer }) => {
  const filename = 'test.go';
  await CreateFile(filename);
  defer(async () => {
    await RemoveFile(filename);
  });
});
```

I wrote a library before. [https://github.com/axetroy/godefer](https://github.com/axetroy/godefer)

**Comment by zekth** [comment]
So defer is simply an helper for : 
```ts
 await new Promise(res => {
    await RemoveFile(filename);
    res();
  });
```
Right?

**Comment by axetroy** [comment]
@zekth
Not at all. @ry should know that.

here is the example

```typescript
test(async ({ defer }) => {
  console.log("do first job");

  defer(async () => {
    console.log("1");
  });

  console.log("do second job");

  defer(async () => {
    console.log("2");
  });

  console.log("do third job");

  defer(async () => {
    console.log("3");
  });

  console.log("do done.");
});

// print out
// do first job
// do second job
// do third job
// 3
// 2
// 1
```

**Comment by zekth** [comment]
I get it. Using the same defer behaviour LIFO after all the sync code has been executed.

**Comment by j-f1** [comment]
Maybe call it `cleanup()`?

**Comment by ry** [comment]
I don’t like the idea because it needs to be called in a special context to work. (Unless I’m missing something?) It’s impossible to implement the general semantics that Go has.

**Comment by axetroy** [comment]
@ry
In fact, we only need to create a context containing the defer function when execute each test function.

After the test function is executed (regardless of reject or resolve), then the `defer` queue is executed one by one.

This is achievable.

and it can be `No side effects`, `No breaking API`

Looking back, it can also add hooks like `after`

```typescript
test(({ defer, after }) => {
  after(() => {
    console.log('do the job after this test finish');
  });
});
```

**Comment by ry** [comment]
@axetroy But it only works in test, and the name suggests it can work elsewhere... If we could implement this generally, I'd be all for it - but I think that would be impossible without a compilation pass.

**Comment by kitsonk** [comment]
I am not sure about the semantics of Go, but Promises are already scheduled out of turn in JavaScript as a microtask. So all this would be is a function that would reschedule at the end of the current queue before the next macrotask. That should be implementable just in the runtime by creating a new Promise.

**Comment by ry** [comment]
In Go, the deferred function is executed before the function returns to caller, but after the body of the function is executed.

I haven't really thought thru how to implement this, but it seems not possible... If @axetroy has a way to do this in general, I'd be all for adding it. (It's super useful and a very nice feature.) But if it's restricted to `test()` callbacks, I think we should not do it.

**Comment by kitsonk** [comment]
> I haven't really thought thru how to implement this, but it seems not possible...

One way, if there is a compelling use case, would be that the `test` function would always pass a function named `deferred(cb: () => void | Promise<void>)` which could then could schedule/drain the deferreds before the test function returns, as @axetroy indicates.  Usage would be something like this:

```ts
test(function testSomething({ defer }) {
  defer(() => console.log("b"));
  console.log("a");
});
```

Anything throwing in there would be attributed to the test function.  No magic, just "standard" JavaScript.

**Comment by axetroy** [comment]
After I finish this, I will create a PR.

**Comment by axetroy** [comment]
@ry I have implemented this feature.

try it out

save as `defer.ts` file

```bash
deno defer.ts
```

```typescript
type DeferFunc = () => Promise<void>;
type Defer = (fn: DeferFunc) => Promise<void>;

interface Context {
  defer: Defer;
}

type func<T> = (context: Context) => Promise<T>;

function deferify<T>(fn: func<T>) {
  return async function(): Promise<T> {
    const defers: DeferFunc[] = [];
    const context: Context = {
      async defer(fn) {
        defers.push(fn);
        return;
      },
    };
    const result = await fn(context);

    while (defers.length) {
      const deferFn = defers.pop();
      if (deferFn) {
        try {
          await deferFn();
        } catch {}
      }
    }

    return result;
  };
}

deferify(async function testFn({ defer }) {
  console.log('do first job');

  defer(async () => {
    console.log('1');
  });

  console.log('do second job');

  defer(async () => {
    console.log('2');
  });

  console.log('do third job');

  defer(async () => {
    console.log('3');
  });

  console.log('job done.');
})();
```

**Comment by ry** [comment]
@axetroy Sorry - it's a bit too non-standard for me. Please submit it to https://github.com/denoland/registry
