### ISSUE TITLE
Tracking issue: Node 18 compat layer updates

### ISSUE THREAD

**Issue by cjihrig** [denoland/deno_std#2631]
This issue is about updating the Node compatibility layer test suite to Node 18 as it enters LTS in October 2022.

- https://github.com/denoland/deno_std/pull/2585 has already been opened and finishes most of the work. This is a big PR that touches a lot of files. It would be good to get it merged so that it doesn't go stale.
- `parallel/test-fs-rm.js` fails on Windows because `child_process.execSync()` is not implemented.
- `parallel/test-webcrypto-sign-verify.js` fails because Ed25519 and Ed448 are not supported yet. These are planned to be added to Deno in https://github.com/denoland/deno/pull/14119.

I have discussed this plan offline with @bartlomieju. The plan is to merge #2585, with `test-fs-rm.js` and `test-webcrypto-sign-verify.js` not updated (so they pass). Then we can work on adding the missing APIs.

**Comment by cjihrig** [comment]
`child_process.execSync()` is being added in https://github.com/denoland/deno_std/pull/2689. Unfortunately, the test still fails on Windows in CI.

```
Node.js compatibility "parallel\test-fs-rm.js" => ./node/_tools/test.ts:45:8
error: AssertionError: Failed assertion: '\"git --version\"' is not recognized as an internal or external command,
operable program or batch file.
'\"git init\"' is not recognized as an internal or external command,
operable program or batch file.
'\"git init\"' is not recognized as an internal or external command,
operable program or batch file.
'\"git init\"' is not recognized as an internal or external command,
operable program or batch file.
The filename, directory name, or volume label syntax is incorrect.
'\"icacls C:\actions-runner\work\deno_std\deno_std\node\_tools\test\.tmp.0\rm-10 /remove:d \"everyone\"\"' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by kt3k** [comment]
Done in https://github.com/denoland/deno_std/pull/2585 and https://github.com/denoland/deno_std/pull/2814

Thanks @cjihrig !
