### ISSUE TITLE
node: need a way to spawn process.execPath with no deno specific flags

### ISSUE THREAD

**Issue by cjihrig** [denoland/deno_std#2674]
**Describe the bug**
Many Node.js tests spawn the node executable in a child process. This is separate from `child_process.fork()`. As an example, see [this test](https://github.com/nodejs/node/blob/96f072231d88ed3ed4a5422f2e37485b59f39e4d/test/parallel/test-child-process-spawnsync-env.js). The problem in that test is that in Deno's compat mode, the `spawnSync()` call needs to be updated to pass in necessary Deno CLI flags (`-A`, `--unstable`, etc.).

For users, this is a problem because they can't run existing Node code as is. For us, it's also a problem because by modifying the Node tests, we lose the ability to automatically upgrade them to newer versions of Node.

A few ideas on how to approach this:
- In the compat code, detect when we are spawning the current executable and set an environment variable that allows Deno to start up properly with no CLI flags. This would require changes in core.
- In the compat code, detect when we are spawning the current executable and add the CLI flags. This could be done in std alone, but might have some edge cases.

**Steps to Reproduce**

Spawn `process.execPath` in Node compat mode without changing any of the CLI flags.

**Expected behavior**

Node compat code runs without modifications.

**Environment**

- OS: all
- deno version: 1.25.3
- std version: 0.156.0

**Comment by kt3k** [comment]
> In the compat code, detect when we are spawning the current executable and set an environment variable that allows Deno to start up properly with no CLI flags. This would require changes in core.
In the compat code, detect when we are spawning the current executable and add the CLI flags. This could be done in std alone, but might have some edge cases.

The first solution might be ideal, but sounds adding lot of complexity to CLI entrypoint.

I think we should try the 2nd solution first and see how many cases it can cover.

cc @bartlomieju what do you think?

**Comment by cmoog** [comment]
I also encountered this here: https://github.com/denoland/deno/issues/15836

**Comment by bartlomieju** [comment]
> > In the compat code, detect when we are spawning the current executable and set an environment variable that allows Deno to start up properly with no CLI flags. This would require changes in core.
> > In the compat code, detect when we are spawning the current executable and add the CLI flags. This could be done in std alone, but might have some edge cases.
> 
> The first solution might be ideal, but sounds adding lot of complexity to CLI entrypoint.
> 
> I think we should try the 2nd solution first and see how many cases it can cover.
> 
> cc @bartlomieju what do you think?

I agree with that, we should go with 2nd solution for now.

**Comment by cjihrig** [comment]
I created an initial version of the CLI argument mapper (option 2) in #2688. The CI is passing, but I personally think that option 1 is the better solution in the long term due to the many edge cases in option 2.

We also need a way to spawn a Deno child process with `require()` available. See `node/_tools/test/parallel/test-child-process-spawnsync-env.js` as an example of why we need that.

**Comment by cjihrig** [comment]
Discussed this internally today. The plan is to land https://github.com/denoland/deno_std/pull/2688 and begin working on a Node argument parser in Deno. Once that is ready, the mapping logic in #2688 can be ripped back out.

**Comment by lino-levan** [comment]
Compat mode no longer exists, is this still relevant? #2688 landed a while ago and I haven't seen a lot of movement on this issue.
