### ISSUE TITLE
CSV Streams

### ISSUE THREAD

**Issue by tracker1** [denoland/deno_std#2685]
Similar to handling JSON streams, would be nice to have a stream processor for CSV that emitted a record at a time.

The main difference, is that the CSV handler would need to do it's own line ending detection for emitting a record.

Ideally, would be nice to have both an async and a sync version... to support `for of` and `for await of` patterns... where the blocking/sync version would yeild better performance, and the async version would allow for a service that might be doing other things to operate more consistently.

**Comment by tracker1** [comment]
Appears to be there, or at least a work in progress...

https://github.com/denoland/deno_std/blob/main/encoding/csv/stream.ts

Feel free to close if no desire to have both sync and async interfaces.

**Comment by kt3k** [comment]
Async iterable interface is available like the below example:

```js
import { CsvStream } from "https://deno.land/std@0.156.0/encoding/csv/stream.ts";
const file = await Deno.open("csv.txt");
for await (const a of file.readable.pipeThrough(new TextDecoderStream()).pipeThrough(new CsvStream())) {
  console.log(a);
}
```

Synchronous iterable API is currently not available (as far as I understand). I'm not sure sync iterable API is desired to be added to std.

**Comment by crowlKats** [comment]
since we are rather going towards web streams over deno streams, a sync version wont be possible as web streams are async, so will close this (and dont see too much need for a sync version either).
