### ISSUE TITLE
Leaking async operation after closing server

### ISSUE THREAD

**Issue by KhaledSakr** [denoland/deno_std#2717]
While working on a test case involving a simple std/http server I encountered the following error:
```
error: AssertionError: Test case is leaking async ops.

 - 1 async operation to sleep for a duration was started in this test, but never completed. This is often caused by not cancelling a `setTimeout` or `setInterval` call. The operation was started here:
    at Object.opAsync (deno:core/01_core.js:177:42)
    at runAfterTimeout (deno:ext/web/02_timers.js:220:31)
    at initializeTimer (deno:ext/web/02_timers.js:186:5)
    at setTimeout (deno:ext/web/02_timers.js:323:12)
    at https://deno.land/std@0.158.0/async/delay.ts:25:15
    at new Promise (<anonymous>)
    at delay (https://deno.land/std@0.158.0/async/delay.ts:16:10)
    at Server.#accept (https://deno.land/std@0.158.0/http/server.ts:387:17)
    at async Server.serve (https://deno.land/std@0.158.0/http/server.ts:134:14)
    at async Server.listenAndServe (https://deno.land/std@0.158.0/http/server.ts:187:12)
```

This can be reproduced using the following code snippet:
```ts
import { Server } from "https://deno.land/std@0.158.0/http/server.ts";

Deno.test("Reproduce leaking test case", async () => {
  const handler = () => {
    return new Response("Test", { status: 200 });
  };
  const port = 4000;
  const server = new Server({ port, handler });
  server.listenAndServe();
  await fetch("http://localhost:" + port, { method: "GET" });
  server.close();
});
```

It seems to be related to the backoff here: https://deno.land/std@0.158.0/http/server.ts?source=#L387. Should this timer be cleared when closing the server?

**Comment by kt3k** [comment]
The server doesn't immediately clear all resources after `server.close()` called. You need to wait the returned value of `server.listenAndServe()` call.

You also need to consume the response body of `fetch()`.

```ts
import { Server } from "https://deno.land/std@0.158.0/http/server.ts";

Deno.test("Reproduce leaking test case", async () => {
  const handler = () => {
    return new Response("Test", { status: 200 });
  };
  const port = 4000;
  const server = new Server({ port, handler });
  const p = server.listenAndServe();
  const resp = await fetch("http://localhost:" + port, { method: "GET" });
  await resp.arrayBuffer();
  server.close();
  await p;
});
```

**Comment by KhaledSakr** [comment]
The [documentation](https://deno.land/std@0.158.0/http/server.ts?s=Server#method_close_0)  states that `close()` **immediately** closes the server listeners and associated HTTP connections though. If that's the case and no new connections can be accepted anyway because of the check in https://deno.land/std@0.158.0/http/server.ts?source=#L358, then what would be the reason for the dangling timer?

**Comment by cjihrig** [comment]
I think we should update `close()` to return a `Promise` that resolves once everything is cleaned up, and update the docs accordingly.

**Comment by KhaledSakr** [comment]
I wonder if checking if the server is closed before starting the backoff would solve the issue without introducing other problems. I created a PR to try it out here: https://github.com/denoland/deno_std/pull/2732
