### ISSUE TITLE
discuss: all test file's name should end with _test.ts

### ISSUE THREAD

**Issue by axetroy** [denoland/deno_std#273]
In order to maintain the uniformity of the project style, the test file should end with `_test.ts`

This also helps the `third-party library` to detect whether it is a test file.

Other `test-tools/plugins/extensions` will definitely appear in the future.

So should files like this be renamed?

https://github.com/denoland/deno_std/blob/master/ws/test.ts
https://github.com/denoland/deno_std/blob/master/textproto/test.ts
https://github.com/denoland/deno_std/blob/master/testing/test.ts
https://github.com/denoland/deno_std/blob/master/testing/test.ts
https://github.com/denoland/deno_std/blob/master/media_types/test.ts
https://github.com/denoland/deno_std/blob/master/log/test.ts
...

Make it a de facto standard

Avoid naming confusion like the `nodejs` community

**Comment by j-f1** [comment]
Perhaps `mod_test.ts`?

**Comment by zekth** [comment]
There was a discussion about it: https://github.com/denoland/deno_std/issues/130
`test.ts` is the test file of the module itself

**Comment by axetroy** [comment]
@zekth Already confirmed?

@j-f1 I prefer to `{entry file}_test.ts`. It seems that the `entry file` is not be `mod.ts`

**Comment by zekth** [comment]
Updated the style_guide for this.
ref: https://github.com/denoland/deno/pull/1918/files

But there was no mention of the module test file. 

May be better to continue this discussion on: https://github.com/denoland/deno_std/issues/130

**Comment by hayd** [comment]
I think the regex /(test|.+_test).ts/ is reasonable.

I don't think there's a huge point in talking about this until https://github.com/denoland/deno_std/issues/193

**Comment by axetroy** [comment]
It seems that this is not an urgent matter, so close it.
