### ISSUE TITLE
WASI: Make the module, browser compatible

### ISSUE THREAD

**Issue by cdecompilador** [denoland/deno_std#2745]
If `wasmer-js` could do it, making something similar with deno should be possible, right?

**Comment by cjihrig** [comment]
Since the WASI module is already written in TypeScript, I think shims for the `Deno` are the only missing piece for browser compatibility, right?

**Comment by cdecompilador** [comment]
I've been looking at the code and it would require some rethinking of the API to make the needed calls to Deno just at the user side, for example while initializing the `Context` it sets by default the `stdin`, `stdout` and `stderr` to actual descriptors, when this ones could be abstacted to a ByteStream or something similar, also the `ContextConfig` handles the filesystem in a very native oriented way, it would mean a lot of changes from what I can see.

I just wanted to open this so future work on wasi has browser compatibility in mind, since its possible and something that in my oppinion is going to be used a lot on the near future

**Comment by iuioiua** [comment]
Closing this as `std/wasi` is now deprecated. If you still need to use WASI in Deno, use [wasmer-js](https://github.com/wasmerio/wasmer-js) instead.
