### ISSUE TITLE
suggestion: detect relative imports within code examples

### ISSUE THREAD

**Issue by iuioiua** [denoland/deno_std#2772]
#2762 replaced relative imports within code examples with absolute imports. As @ayame113 pointed out, this allows examples within the documentation to be copied and pasted.

Having a tool that can detect and warn the user when a relative import within a code example would prevent this undesired from happening again. I think something similar to #2613 by @timreichen would do the trick.

**Comment by ayame113** [comment]
I think it is good. For reference, the regex I used to find the relative imports from within the docs are `\*.*from.*"\.` and `\*.*import.*"\.`.

**Comment by iuioiua** [comment]
This has been implemented in #2820.
