### ISSUE TITLE
bug(flags): all boolean arguments included in alias are not set to false by default

### ISSUE THREAD

**Issue by sant123** [denoland/deno_std#2778]
**Describe the bug**
When setting an alias and if one of the alias are included in the boolean argument, all arguments inside the alias should have their value to false.

![image](https://user-images.githubusercontent.com/7959437/195964205-cbca51ea-ac71-4ef8-8a0f-118a61f26712.png)

**Steps to Reproduce**

```ts
import { parse } from 'https://deno.land/std@0.159.0/flags/mod.ts';

const options = parse(Deno.args, {
  boolean: ['h'],
  alias: {
    h: "help"
  },
});
console.log(options);
```

**Expected behavior**

`options.h` and `options.help` should be false.

Also the type-checking is trying to guarantee the values are boolean:

![image](https://user-images.githubusercontent.com/7959437/195964238-269d60dd-6f8d-488e-8729-55d298b7d809.png)

**Environment**

- OS: Fedora 36
- deno version: 1.26.1
- std version: 0.159.0

**Comment by kt3k** [comment]
cc @c4spar

**Comment by c4spar** [comment]
I'll take a look at it.
