### ISSUE TITLE
Don't require `--unstable` for `Deno.getUid()` and `Deno.getGid()`

### ISSUE THREAD

**Issue by martin-braun** [denoland/deno_std#2791]
`Deno.getUid()` and `Deno.getGid()` should just return `null` on Windows systems, but not require the `--unstable` keyword, so they can be used in `deno_std` for permission checks that are only necessary on POSIX systems.

This issue blocks #2785

Context:

Windows will raise a `Deno.errors.PermissionDenied` when calling `Deno.stat` on a directory/file that the user cannot read. However, on POSIX systems `Deno.stat` will success nonetheless. To avoid opening the file when trying to verify permissions, one could compare `Deno.getUid()` and `Deno.getGid()` to `FileInfo.uid` and `FileInfo.gid` to validate ownership of a given directory/file to further validate permissions by parsing `FileInfo.mode` accordantly.

`FileInfo.mode` returns `null` and `Deno.chmod` is not working on Windows, but those APIs requires no `--unstable` flag. So should `Deno.getUid()` and `Deno.getGid()` in my opinion.

**Comment by iuioiua** [comment]
This is an issue for the main repo and not `deno_std`.

**Comment by cjihrig** [comment]
FYI - https://github.com/denoland/deno/pull/16424 (the APIs were renamed to `uid()` and `gid()` in the last release)
