### ISSUE TITLE
Env file loading with empty value is broken since 0.147

### ISSUE THREAD

**Issue by acrodrig** [denoland/deno_std#2798]
**Describe the bug**

It is not possible to load `.env` files with empty values since version 0.147. It used to work until version 0.146.

**Steps to Reproduce**

Assume the following `.env` file:

```env
A="foo"
B="bar"
C=""
```

And `test.ts` below:

```typescript
// Any version after 0.147 will break all the way up to 0.160
import "https://deno.land/std@0.160.0/dotenv/load.ts";
console.log(Deno.env.get("A"));
```

It breaks as shown here:

```
$ deno run -A test.ts 
error: Uncaught TypeError: Cannot read properties of undefined (reading 'trim')
      : unquoted.trim();
                 ^
    at parse (https://deno.land/std@0.147.0/dotenv/mod.ts:55:18)
    at parseFile (https://deno.land/std@0.147.0/dotenv/mod.ts:138:12)
    at configSync (https://deno.land/std@0.147.0/dotenv/mod.ts:79:16)
    at https://deno.land/std@0.147.0/dotenv/load.ts:11:3
```

**Expected behavior**

When changing version to 0.146:

```typescript
import "https://deno.land/std@0.146.0/dotenv/load.ts";
console.log(Deno.env.get("A"));
```

Output is as shown:

```
$ deno run -A test.ts 
foo
```

**Environment**

- OS: Mac OS 12.6
- deno version: 1.26.2
- std version: 0.147 to 0.160

**Comment by lino-levan** [comment]
This was fixed in #2819. Should we close this issue now, or wait until a new std version is published?

**Comment by cjihrig** [comment]
Yes, this can be closed.

**Comment by acrodrig** [comment]
Thanks.
