### ISSUE TITLE
http/serveDir: Returns wrong (because encoded) `href` values inside the html table

### ISSUE THREAD

**Issue by timonson** [denoland/deno_std#2806]
The function `serveDir` with the option `showDirListing: true` returns a HTML `table` with incorrect hyperlinks if the filenames contain **url-unsafe** characters. 

For example, the `href` value of the file `shadow@v1.1.1/css.js` becomes `shadow%40v1.1.1/css.js` in the returned HTML code. After clicking on the link, `serveDir` will return a `404`. 

deno 1.26.2 (release, x86_64-unknown-linux-gnu)
v8 10.7.193.16
typescript 4.8.3
std 0.160.0

**Comment by iuioiua** [comment]
This worked fine for me using `deno run --allow-net --allow-read https://deno.land/std@0.161.0/http/file_server.ts`. No 404s here.
<img width="1470" alt="image" src="https://user-images.githubusercontent.com/29347852/198877988-9d82adc7-e6d1-4677-94b8-cdb0d7c6fc67.png">

**Comment by lino-levan** [comment]
I'm not getting any 404s on std 0.160.0 or 0.161.0. Was this a bug with Deno (I'm using 1.27.0)? It seems resolved regardless of what the root cause was.

**Comment by timonson** [comment]
This doesn't contradict anything I said

**Comment by timonson** [comment]
OK, I messed up the routing on my end, but it seems that non-ASCII characters in URLs, percent-encoded or not, are safe now according to spec: https://stackoverflow.com/a/3705601/12222244
