### ISSUE TITLE
suggestion: retry algorithms

### ISSUE THREAD

**Issue by iuioiua** [denoland/deno_std#2829]
I like the idea of having a retry function with a BYO algorithm. A common use case is initiating a TCP connection for a database or service. My idea is to have both the retry function and a few popular algorithms, perhaps in `std/async/retry.ts`. Example:
```ts
const conn = await retry(
  async () => await Deno.connect({ port: 6379 }),
  exponentialBackoff({
    multiplier: 2,
    maxInterval: 5000,
    minInterval: 500,
  }),
);
```
This function would retry until the algorithm reaches its retry limit and then reject.

I'd like to work on this, if it sounds like a good idea.

**Comment by kt3k** [comment]
The idea looks good to me.

I found 3 npm modules which implement similar features (these all have >1M weekly downloads):
- https://www.npmjs.com/package/retry
- https://www.npmjs.com/package/async-retry
- https://www.npmjs.com/package/p-retry

They all seem supporting only exponential backoff. Maybe we can follow that design? (Is there any useful algorithm other than exponential backoff?)

**Comment by lino-levan** [comment]
I would really like to see `expontentialBackoff` built into the module in std. It seems to me that the only other function that would be useful other than exponential backoff is linear backoff (but that could be accomplished with `multiplier: 1`)

**Comment by lino-levan** [comment]
@iuioiua If you don't want to pick this up, I'd love to do a PR on this

**Comment by iuioiua** [comment]
> @iuioiua If you don't want to pick this up, I'd love to do a PR on this

Feel free to take it! 👍🏾
