### ISSUE TITLE
lodash like functions

### ISSUE THREAD

**Issue by zekth** [denoland/deno_std#283]
[Lodash](https://github.com/lodash/lodash) has done the past few years a lot of helpers / polyfills for the Js community. ES / Typescript have lot of those polyfills now but some usefull are missing. I think it would be revelant to add `collection`, `array` modules for example with those functions:

**collection:**
- [groupBy](https://lodash.com/docs/4.17.11#groupBy)
- [keyBy](https://lodash.com/docs/4.17.11#keyBy)
- [orderBy](https://lodash.com/docs/4.17.11#orderBy)

**array:**
- [intersection](https://lodash.com/docs/4.17.11#intersection)
- [union](https://lodash.com/docs/4.17.11#union)
- [uniq](https://lodash.com/docs/4.17.11#uniq)
- [difference](https://lodash.com/docs/4.17.11#difference)

Note: Feel free to purpose more functions

**Comment by bartlomieju** [comment]
You can use lodash with Deno so it looks like reinventing the wheel

**Comment by zekth** [comment]
In a sense yes, i agree. But it's not the only library to do it, that's why i suggest those funcs to be integrated; as its really usefull and i think it has its place in ES / TS and not in a third party.

**Comment by axetroy** [comment]
agree with @bartlomieju.

we should not reinvent the wheel.

`Lodash` is a great library, but it can still run in `deno`

**Comment by zekth** [comment]
Seems legit. Closing it.
