### ISSUE TITLE
Axios-like wrapper on top of fetch

### ISSUE THREAD

**Issue by sh7dm** [denoland/deno_std#284]
Will work on it by myself, issue is just for feedback

**Comment by zekth** [comment]
What's the advantage of having axios if fetch is already supported?

**Comment by sh7dm** [comment]
@zekth e.g. migrating Axios apps

**Comment by zekth** [comment]
> @zekth e.g. migrating Axios apps

It's maybe more revelant to have it in `deno_axios` no?

**Comment by bartlomieju** [comment]
> > @zekth e.g. migrating Axios apps
> 
> It's maybe more revelant to have it in `deno_axios` no?

Definitely yes.

**Comment by axetroy** [comment]
`axios` base on `XMLHTTP` in browser. but `deno` does not support it.

it means some methods like `onUploadProgress` and `onDownloadProgress` can not be implemented.

If we need to make an HTTP library like `axios`. Then it should not be called `axios`

Maybe it should be the sub-module of `http`

```typescript
import * as http from 'https://deno.land/x/std/http/client/mod.ts';

const instance = http.create({ base: 'http://localhost:8080' })

http.get('/')
instance.get('/')
...
```

**Comment by kevinkassimo** [comment]
I'm actually thinking about whether we should add `XMLHttpRequest` and client side `WebSocket` to core, both of which are very important web APIs (even just for historical reasons). It should be possible to just do a reverse polyfill using `fetch` for `XMLHttpRequest`,

**Comment by sh7dm** [comment]
@kevinkassimo please say me when you want to implement XHR and WS, I'd like to participate

**Comment by kevinkassimo** [comment]
@sh7dm I'll probably wait for feedback from @ry first on this

**Comment by ry** [comment]
XMLHttpRequest is really old..  I'm not against adding it necessarily but I would wait until someone has an actual use case rather than adding it preemptively.

**Comment by kitsonk** [comment]
Also, it has a lot of really bad behaviours that would need to be replicated to be compatible. Again something that would likely be better addressed with a shim for targeted code to make it functional than something that is part of Deno.
