### ISSUE TITLE
`npm:tmp-promise@3.0.3` doesn't work when use `--trace-ops`

### ISSUE THREAD

**Issue by loynoir** [denoland/deno_std#2841]
**Describe the bug**

`npm:tmp-promise@3.0.3` doesn't work

**Steps to Reproduce**

reproduce.test.ts
```ts
import { file } from 'npm:tmp-promise@3.0.3'

Deno.test('foobar', async () => {
  const { path, cleanup } = await file()
  console.log(path)
  await cleanup()
})
```
```sh
$ deno test --trace-ops -A --unstable reproduce.test.ts 
running 1 test from ./reproduce.test.ts
foobar ...
Uncaught error from ./reproduce.test.ts FAILED
foobar ... cancelled (0ms)

 ERRORS 

./reproduce.test.ts (uncaught error)
error: NotFound: No such file or directory (os error 2), stat '/tmp/tmp-xxx-xxx'
This error was not caught from a test and caused the test runner to fail on the referenced module.
It most likely originated from a dangling promise, event/timeout handler or top-level code.

 FAILURES 

./reproduce.test.ts (uncaught error)
```

**Expected behavior**

No Error.

**Environment**

- OS: [e.g. Ubuntu 20.04, MacOS 11]
- deno version:
- std version:

```
$ deno --version
deno 1.27.1 (release, x86_64-unknown-linux-gnu)
v8 10.8.168.4
typescript 4.8.3
```

### Additional
I add `--trace-ops` because deno complain leak resource, seems like this issue is behind that issue.

**Comment by dhardtke** [comment]
Same issue just using `Deno.makeTempDir()`:

```typescript
import { fs, path } from "../../../deps.ts";

Deno.test("My test", async (t) => {
    const tmpDir = await Deno.makeTempDir();
    const thumbnailDir = path.join(tmpDir, "subdir");
    await fs.ensureDir(thumbnailDir);
});
```

-->

> ./tests/issue.test.ts (uncaught error)
> error: (in promise) NotFound: The system cannot find the file specified. (os error 2), stat 'C:\Users\user\AppData\Local\Temp\67c2eca6\subdir'
> This error was not caught from a test and caused the test runner to fail on the referenced module.
> It most likely originated from a dangling promise, event/timeout handler or top-level code.

**Comment by iuioiua** [comment]
Both code snippets in this issue now work (tested on macOS with Deno v1.37.1). @loynoir and @dhardtke, are you still encountering these issues? If not, we can close this issue.
