### ISSUE TITLE
suggestion: remove `_util/assert_type.ts`

### ISSUE THREAD

**Issue by iuioiua** [denoland/deno_std#2877]
I've only had a chance to have a quick look at this. `flags/test.ts` is the only file in the codebase using `_util/assert_type.ts`. Is this file needed?

**Comment by kt3k** [comment]
When we land https://github.com/denoland/deno_std/pull/2864, we can replace the usage of `_util/assert_type.ts` with `testing/types.ts` (`testing/types.ts` is superset of `_util/assert_type.ts`)

**Comment by iuioiua** [comment]
Is it worth just doing so in that PR?

**Comment by kt3k** [comment]
Maybe let's do this separately

**Comment by iuioiua** [comment]
@lino-levan, perhaps you'd be good to do this? I say it because you've been playing with the new API. What do you think?

**Comment by lino-levan** [comment]
When #2864 lands, I think that makes a lot of sense. Currently blocked on some community discussion + a few reviews from core team.

**Comment by lino-levan** [comment]
#2864 landed, let me try my hand at doing this.
