### ISSUE TITLE
suggestion: use `Deno.Command` API

### ISSUE THREAD

**Issue by iuioiua** [denoland/deno_std#2885]
It just came out with Deno 1.28. Is it stable enough for use within the standard library?

If so, I'm happy to do it.

**Comment by iuioiua** [comment]
> It just came out with Deno 1.28. Is it stable enough for use within the standard library?
> 
> 
> 
> If so, I'm happy to do it.

Actually, I'll just do it.

**Comment by iuioiua** [comment]
Completed in #2886.

**Comment by crowlKats** [comment]
its not done as usages of `Deno.spawnChild` werent changed

**Comment by iuioiua** [comment]
Oh, right. I'll get that done too.
