### ISSUE TITLE
TypeScript error with `WriteStream`

### ISSUE THREAD

**Issue by roj1512** [denoland/deno_std#2891]
**Describe the bug**

Described in the title.

**Steps to Reproduce**

```ts
import { WriteStream } from "https://deno.land/std@0.164.0/node/fs.ts";

if (something instanceof WriteStream) {
  something.path // ts error
}
```

**Expected behavior**

Should behave like /std@0.155.0/node/fs.ts.

**Environment**

N/A

**Comment by kt3k** [comment]
Probably https://github.com/denoland/deno_std/commit/be2493378d02d7360a72e80e3d19cd56dff5346d introduced this behavior.

cc @PolarETech

**Comment by PolarETech** [comment]
Hi,

It also reproduces in deno_std 0.156.0, so I think #2634 is the trigger. We need a way to resolve this issue without causing a recurrence of #2548.

I would like to investigate, but unfortunately will not have enough time for a while and therefore it is difficult for me to submit a PR soon. If someone would like to take on this, I would welcome it.

**Comment by PolarETech** [comment]
I have considered and this case seems to be the following situation.

- To make the type guard with `instanseof` work well, the type of `WriteStream/ReadStream` must be provided as a class
- To solve #2548, the implementation of `WriteStream/ReadStream` needs to be function style

One solution would be to keep the implementation in the function style and provide the type definition in a separate .d.ts file.
In other words, make them the same as the state of the Node implementation and type definition.

https://github.com/nodejs/node/blob/main/lib/internal/fs/streams.js#L307
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/node/fs.d.ts#L409

It seems that the .d.ts file can be created soon, but if I should modify the existing "node/internal/fs/streams.ts" file to a "streams.mjs", I would appreciate a little time to work on it.

If there are more appropriate solutions, I would be glad to hear them.

**Comment by kt3k** [comment]
> One solution would be to keep the implementation in the function style and provide the type definition in a separate .d.ts file.
In other words, make them the same as the state of the Node implementation and type definition.

This sounds good to me. Thanks for the idea!

**Comment by PolarETech** [comment]
I have submitted a PR that fixes this issue in the way I had suggested. I have verified the TS error does not occur and also verified #2548 does not reoccur.
