### ISSUE TITLE
`Buffer` does not work in browsers

### ISSUE THREAD

**Issue by roj1512** [denoland/deno_std#2894]
**Describe the bug**

[`Buffer`](https://deno.land/std@0.164.0/node/buffer.ts) does not work in browsers because it tries to use `Deno.build` in its initialization.

**Steps to Reproduce**

1.

```ts
import "https://deno.land/std@0.164.0/node/buffer.ts";
```

2.

```shell
deno bundle main.ts main.js
```

3.

```html
<script type="module" src="./main.js"></script>
```

**Expected behavior**

It works if we assign a fake `Deno` to `globalThis`. It should work by default without the need of doing this.

**Environment**

N/A

**Comment by schwarzkopfb** [comment]
I cannot reproduce the error with the latest Deno CLI in Chrome 107.0.5304.87.

In the generated output `Deno.build.os` occurs only once and is wrapped into an `if` condition which guarantees that it shouldn't break. That line is coming from [here](https://github.com/denoland/deno_std/blob/main/_util/os.ts#L9) btw.

<img width="431" alt="Screenshot 2022-11-16 at 10 07 19" src="https://user-images.githubusercontent.com/1900242/202138476-b3efbfa1-ca9d-4fb5-86db-4ab5f3e6a4bd.png">

Also, my test code:
```ts
import { Buffer } from "https://deno.land/std@0.164.0/node/buffer.ts";
const buf = Buffer.from("hello world", "utf8");
console.log(buf.toString("hex"));
```

Works as expected for me:
<img width="639" alt="Screenshot 2022-11-16 at 10 19 15" src="https://user-images.githubusercontent.com/1900242/202140209-64abdcf3-9f28-47b3-aee8-115e624ae447.png">

@roj1512  which Deno version did you use for bundling and in which browser & version did you test it?

**Comment by roj1512** [comment]
Hmm, I use 1.28.0, 0.164.0, and Chrome. The problem might not be in buffer then, but I'll look more into it.

**Comment by roj1512** [comment]
Fixed.

The problem was not related to `Buffer` at all. It was because of importing std/node/net.ts. I fixed it by not including that in the bundle.

Thanks for participating, @schwarzkopfb!
