### ISSUE TITLE
suggestion: Add supports-color to the standard library

### ISSUE THREAD

**Issue by lino-levan** [denoland/deno_std#2895]
## Problem
- Currently, it is not trivial to make CLI tools with color in deno (at least using the std), because it is unclear whether or not the terminal has access to color (and if it does, how many of them).
- This is something I've run into [at CookieDB](https://github.com/cookiedb/CookieDB/issues/5), and it's a real struggle. In a true-color terminal running `cookie start` looks like the top demo below. If it's not supported, it looks like the middle demo below.
- The current workaround to make it not completely unusable is either disable color entirely, disable it through a flag, or enable color through a flag (this is done in the bottom demo below).

## Solutions
I see three main possible solutions:

- A: Add a module / new method in `std/fmt` (either in `std/fmt/color` or maybe a new file `std/fmt/supports_color`) that allows for the client to do the check themselves, and handle it however they want
- B: Do the same as above BUT when the client tries to use a color method in a non-color terminal have it do nothing
- C: Do the same thing as the first one BUT the client can configure what the fallback behavior will look like if color is not supported

A very simple demo of the two options in my mind.
```typescript
// Option A
import { rgb24, supportsColor } from "https://deno.land/std/fmt/color.ts";

if(supportsColor.stderr.has16m) {
    console.log(rgb24("Hello, World!", {
        r: 41,
        g: 42,
        b: 43,
    }));
} else {
    console.log("Hello, World!");
}

// Option B
import { colors } from "https://deno.land/std/fmt/color.ts";

console.log(rgb24("Hello, World!", { // behind the scenes, this does nothing if true-color is not supported
    r: 41,
    g: 42,
    b: 43,
 }));
 
// Option C
// ??? - I don't know what this API would look like
```

## Related Images

true-color demo
<img width="454" alt="Screenshot 2022-11-15 at 3 56 43 PM" src="https://user-images.githubusercontent.com/11367844/202049890-9b58bd15-584e-4433-8b2d-d74d0366c9ba.png">

non true-color demo
<img width="469" alt="Screenshot 2022-11-15 at 3 57 48 PM" src="https://user-images.githubusercontent.com/11367844/202049900-cc778b83-193a-4d38-b464-79db1cd5dc0e.png">

workaround demo
<img width="460" alt="Screenshot 2022-11-15 at 3 59 05 PM" src="https://user-images.githubusercontent.com/11367844/202050115-25dbbad4-3905-4e47-b3d3-bb1b51f0066b.png">

ref: https://github.com/denoland/deno_std/issues/2602

**Comment by lino-levan** [comment]
@iuioiua do you have a preference on which of the api options makes the most sense. I'm leaning towards option A, and might make a draft PR at some point soon to start a discussion on it. I'm wondering if you have a strong opinion on this.

**Comment by iuioiua** [comment]
Having both options, A and B, sounds like a good idea. Doing nothing if colour isn't supported is a great default that would cover most cases. But also having `supportsColour` functionality, which returns a boolean, can provide extra control if needed. I feel as though option C may not be worth the complexity.

**Comment by lino-levan** [comment]
I've been thinking about this a little bit.

@kt3k would it be okay to copy and modify [chalk's support-color](https://github.com/chalk/supports-color/blob/main/index.js) for this as a PR?

**Comment by lino-levan** [comment]
Closing this as "too much of a hack to fit in std".
