### ISSUE TITLE
Web sockets.

### ISSUE THREAD

**Issue by ry** [denoland/deno_std#29]

**Comment by keroxp** [comment]
https://github.com/keroxp/deno-ws

Hi, I created an experimental websocket server with deno.
I hope this is useful for you.

Thanks.

**Comment by ry** [comment]
@keroxp How well is it working? Can you give us a status update? What are the major missing features? Would you be open to including that in deno_std?

**Comment by keroxp** [comment]
@ry I opened PR for websocket. Please review it!

**Comment by keroxp** [comment]
@ry Can be closed?

**Comment by ry** [comment]
yes thanks

https://github.com/denoland/deno_std/tree/57c9176b19bf4f4580466e088c249cbe9b145119/ws
