### ISSUE TITLE
No overload matches in csv parse with Buffer

### ISSUE THREAD

**Issue by djamelbencherif** [denoland/deno_std#2905]
Hi, 
an idea of ​​the problem with a readTextFile it works but with a buffer it blocks the overload of the function does not work 😱

 import { parse as csvParser } from "https://deno.land/std@0.163.0/encoding/csv.ts";

await csvParser(new BufReader(file), {
    skipFirstRow: true,
    comment: "#",
  });

**Comment by dsherret** [comment]
@djamelbencherif it looks like this function takes a string and not a BufReader?

https://deno.land/std@0.163.0/encoding/csv.ts?s=parse
