### ISSUE TITLE
Node version prepended with extra v

### ISSUE THREAD

**Issue by SarahGreyWolf** [denoland/deno_std#2906]
**Describe the bug**
Was experimenting with seeing if homebridge could be ran with deno and ran into an assertion error of 
```
error: Uncaught AssertionError: The cipher 'chacha20-poly1305' is not supported with your current running nodejs version vv16.17.0. At least a nodejs version of v10.17.0 (excluding v11.0 and v11.1) is required!
```
Wherever this assertion is happening seems to be receiving a version with an extra v prepended to it (vv16.17.0 instead of v16.17.0).
Unsure if this is possibly a core issue or not but thought I should try here

**Steps to Reproduce**
1. deno run -A npm:homebridge
2. Receive above error

**Expected behavior**
The version in the error (if still occurs) should be `v16.17.0` instead of `vv16.17.0`.
**Environment**

- OS: Windows 10
- deno version: 1.28.1
- std version: 0.165.0

**Comment by iuioiua** [comment]
I'll take a look at this one.

**Comment by SarahGreyWolf** [comment]
So I did some experimenting myself with docker, this may not actually be a deno issue at all, it seems that the error message in general is appending the extra v.
I got this from running it in a docker container with an older version of Node.
```
AssertionError [ERR_ASSERTION]: The cipher 'chacha20-poly1305' is not supported with your current running nodejs version vv8.9.3. At least a nodejs version of v10.17.0 (excluding v11.0 and v11.1) is required!
```

**Comment by SarahGreyWolf** [comment]
Yeah it's a string formatting issue with one of the libraries that homebridge uses and not caused by deno, the assertion in general is just a lack of support for that cipher in deno so this can be closed.
Sorry for the confusion 😅

**Comment by iuioiua** [comment]
> Yeah it's a string formatting issue with one of the libraries that homebridge uses and not caused by deno, the assertion in general is just a lack of support for that cipher in deno so this can be closed.
> Sorry for the confusion 😅

That'd make sense!
