### ISSUE TITLE
`normalize` doesn't remove *all* `.` and `..` segments

### ISSUE THREAD

**Issue by jflatow** [denoland/deno_std#2918]
**Describe the bug**

The documentation says `normalize` resolves `..` and `.` segments, but these can remain in the output if they are the *only* components of the resulting path. Probably the documentation should point this out, if it is intended.

**Steps to Reproduce**

e.g. `normalize('.')` results in `.` and `normalize('..')` results in `..`

**Comment by cjihrig** [comment]
@jflatow would you like to update the docs?

**Comment by jflatow** [comment]
> @jflatow would you like to update the docs?

Can you point me to the source?

**Comment by iuioiua** [comment]
`normalize` lives in `path/posix.ts` and `path/win32.ts`.

**Comment by jflatow** [comment]
> `normalize` lives in `path/posix.ts` and `path/win32.ts`.

The docs are split between those files?

**Comment by iuioiua** [comment]
Yes, `normalize` works differently internally on POSIX systems than on Windows systems.

I'm not sure what platform you're issue is regarding, but I'm guessing you're looking to modify the JSDocs for one or both functions.

**Comment by cjihrig** [comment]
Documented in https://github.com/denoland/deno_std/pull/2946
