### ISSUE TITLE
Upgrade from deno 1.26.2 to 1.28.1 breaks node imports

### ISSUE THREAD

**Issue by BearLemma** [denoland/deno_std#2920]
Hello guys, we use Deno in https://github.com/chiselstrike/chiselstrike and recently when I did an upgrade of the deno we use to version `v1.28.1` (`v1.27.*` had the same problem), I got an error in one of our tests that tries to import node modules. The test is very simple, the only thing it does is:

`import * as module from "https://deno.land/std@0.165.0/node/module.ts";`

And the error I get is:

```
0: Could not compile TypeScript
1: Compilation failed:
    https://deno.land/std@0.165.0/node/readline/promises.ts:89:11 - error TS7053: Element implicitly has an 'any' type because expression of type 'unique symbol' can't be used to index type 'Interface'.
      Property '["../internal/readline/interface.mjs".kQuestionCancel]' does not exist on type 'Interface'.

    89           this[kQuestionCancel]();
                ~~~~~~~~~~~~~~~~~~~~~
    https://deno.land/std@0.165.0/node/readline/promises.ts:99:7 - error TS7053: Element implicitly has an 'any' type because expression of type 'unique symbol' can't be used to index type 'Interface'.
      Property '["../internal/readline/interface.mjs".kQuestion]' does not exist on type 'Interface'.

    99       this[kQuestion](query, cb);
            ~~~~~~~~~~~~~~~
```

The Vanilla Deno is fine with the import so I presume the error must be somewhere on our side, but after hours of trying things I'm still unable to figure it out. Originally I thought this might be some TypeScript version missmatch, but I've synced everything to match deno's version of TypeScript and we are using the `0.165.0` version of `deno_std`.

Can you guys think of anything that might help me out? Any suggestions would be greatly appreciated.

**Comment by kt3k** [comment]
What command do you use for type checking? Do you use `--remote` option for type checking?

We currently don't recommend type checking of the remote modules because those type errors are often not resolvable from the users' side

**Comment by kt3k** [comment]
Closing as we don't provide `std/node` from std anymore. (Node compat layer is now builtin to Deno CLI). Thanks for your report anyway
