### ISSUE TITLE
node: Get rid of Top-Level Await in "node/worker_threads.ts"

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno_std#2921]
I'm trying to bundle "std/node/module_all.ts" into a single file, so it could be easily embedded into Deno, but I found one file that uses TLA that makes it harder to bundle:
https://github.com/denoland/deno_std/blob/5e5309ecb42a8ce3d1f82437e7f8995bc8aa290e/node/worker_threads.ts#L178

Ideally we could remove it this TLA and keep the module working the same.

**Comment by cjihrig** [comment]
@bartlomieju would something like this work? `deno task node:test` passes locally for me with this change.

```diff
diff --git a/node/worker_threads.ts b/node/worker_threads.ts
index db525562..f5eedc82 100644
--- a/node/worker_threads.ts
+++ b/node/worker_threads.ts
@@ -175,10 +175,12 @@ if (!isMainThread) {
     notImplemented("parentPort.removeAllListeners");
 
   // Receive startup message
-  [{ threadId, workerData, environmentData }] = await once(
-    parentPort,
-    "message",
-  );
+  (async function() {
+    [{ threadId, workerData, environmentData }] = await once(
+      parentPort,
+      "message",
+    );
+  })()
 
   // alias
   parentPort.addEventListener("offline", () => {
```

**Comment by bartlomieju** [comment]
@cjihrig yes, it appears this solves the problem!

**Comment by kt3k** [comment]
Is this a still blocker of bundling work?

**Comment by bartlomieju** [comment]
@kt3k I believe it still is

**Comment by kt3k** [comment]
worker_thread is now disabled in `ext/node`

**Comment by vixalien** [comment]
@kt3k this is a bummer. it prevents some node wasm modules from working.

**Comment by vixalien** [comment]
(ffmpeg-wasm) specifically
