### ISSUE TITLE
Add `ByteLineStream` transform stream

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno_std#2942]
Same as `TextLineStream`, except that it operates on `Uint8Array` streams rather than `string` streams.

Also see https://github.com/denoland/deno/issues/16523

**Comment by crowlKats** [comment]
we used to have this, however for reasons i cant remember, we removed it.

**Comment by iuioiua** [comment]
Could `DelimiterStream("\r\n")` or `DelimiterStream("\n")` from `streams/delimiter.ts` be what you're after?

**Comment by lucacasonato** [comment]
I guess so :D
