### ISSUE TITLE
Can't use puppeteers' stealth plugin in deno

### ISSUE THREAD

**Issue by ralyodio** [denoland/deno_std#2943]
https://discord.com/channels/684898665143206084/1045472556221734983

The issue is that npm's ws lib (and thus all consumers) doesn't work client-side, because deno's node-compat impl of http/https clients don't handle upgrades / emit upgrade-events

With the sub-issue that http/https uses fetch, which might use h2 for https whereas node's https module only supports/assumes h1

Though in your specific case, you probably only need http/h1 so that h2 mixup isn't an issue per se, since puppeteer should handshake over http locally

**Comment by kt3k** [comment]
missing upgrade event handling is being tracked in https://github.com/denoland/deno/issues/17846
