### ISSUE TITLE
testing/asserts - Handle `__proto__` property

### ISSUE THREAD

**Issue by dsherret** [denoland/deno_std#2954]
We might have a readonly `__proto__` property in Deno (https://github.com/denoland/deno/pull/16775) and it seems like `assertEquals` does not handle it.

See here for more details: https://github.com/denoland/dnt/issues/235

**Comment by schwarzkopfb** [comment]
https://github.com/denoland/dnt/issues/235#issuecomment-1331510064

**Comment by kt3k** [comment]
The root issue in the use case in dnt seems resolved by adding `NODE_OPTIONS='--disable-proto=delete'` in dnt execution (which removes `__proto__` in Node.js and make Deno test cases work similarly in Node.js). ref: https://github.com/KnorpelSenf/oson/commit/0fe5862fbb67181b902c5f2b1d50979079f0a369

I think we can recommend the above as the solution to this problem.

**Comment by KnorpelSenf** [comment]
> I think we can recommend the above as the solution to this problem.

Yes.

I originally reported https://github.com/denoland/dnt/issues/235 and I can confirm that https://github.com/KnorpelSenf/oson/commit/0fe5862fbb67181b902c5f2b1d50979079f0a369 works well.

**Comment by kt3k** [comment]
@KnorpelSenf Thanks for the confirmation!
