### ISSUE TITLE
suggestion: automatically add copyright header to files missing one

### ISSUE THREAD

**Issue by iuioiua** [denoland/deno_std#2959]
Currently, the licence check tool prints the list of files missing a copyright header and throws an error. It'd be cool if the tool could instead insert the copyright at the top of the file as defined by the `COPYRIGHT` constant. It should be easy to implement.

The tool is located at `_tools/check_licence.ts` and is run using `deno task lint:licence-headers`.

**Comment by lino-levan** [comment]
This makes sense to me. Wondering if there's a reason this hasn't been done before? I feel like there might be a legal reason?

**Comment by schwarzkopfb** [comment]
also auto-updating the year to present would be great

**Comment by timreichen** [comment]
I like the idea, but I think checking and inserting headers should be two separate tasks.
`set:licence-headers` or `fmt:licence-headers` to insert and update headers and
`lint:licence-headers` to check headers.

**Comment by iuioiua** [comment]
I don't really see the advantage of having two separate tasks. Having both in one can be as simple as:
```ts
...
if (!content.includes(COPYRIGHT)) {
  insertCopyright();
}
...
```

**Comment by schwarzkopfb** [comment]
another approach could be having the same script, but considering a `--fix` flag (like eslint and friends do)

**Comment by timreichen** [comment]
The reason is because one might want to lint without changing anything (as are two separate tasks in `deno fmt` and `deno lint`).
If for example a malformed header is existent, there is no way of finding it and the tool will just prepend without a warning.

**Comment by timreichen** [comment]
> another approach could be having the same script, but considering a `--fix` flag (like eslint and friends do)

Would advise against turning it into a cli tool
But why not have two separate tasks that share a code base?
