### ISSUE TITLE
suggestion(collections): replace `withoutAll` with `difference`

### ISSUE THREAD

**Issue by iuioiua** [denoland/deno_std#2971]
Is there a `difference` function in the `std/collections` module like the one in `dotenv/util.ts`? If not, should there be? I think so.

**Comment by iuioiua** [comment]
I realise `collections/withoutAll` has similar functionality, except that it just compares one array to a number of others. I think a more general function, `difference`, should replace `withoutAll`, and only return elements in the given arrays that aren't duplicated. That'd be the 3rd counterpart to the commonly known `union` and `intersect` that are already present in `std/collections`.

**Comment by ayame113** [comment]
FYI, [Set.prototype.difference](https://github.com/tc39/proposal-set-methods#proposal) is now Stage 3. I don't know when it will be available for Deno though.

**Comment by iuioiua** [comment]
> FYI, [Set.prototype.difference](https://github.com/tc39/proposal-set-methods#proposal) is now Stage 3. I don't know when it will be available for Deno though.

Interesting... So is `.intersection`, `.union` and `.symmetricDifference` 👀

**Comment by iuioiua** [comment]
Closing as [Set.prototype.difference](https://github.com/tc39/proposal-set-methods#proposal) is now Stage 3.
