### ISSUE TITLE
getSetCookies should support maxage<0

### ISSUE THREAD

**Issue by powerpuffpenguin** [denoland/deno_std#2973]
**Describe the bug**

In set-cookie, 'maxage<0' or 'expires' expires mean that the cookie should be deleted, but getSetCookies behaves inconsistently for them. getSetCookies does not return cookies when 'maxage < 0' and returns cookies when 'expires' expires

**Steps to Reproduce**

```
let headers = new Headers({
  "set-cookie": "Space=Cat; Secure; HttpOnly; Max-Age=-1",
});
console.log(getSetCookies(headers));
headers = new Headers({
  "set-cookie":
    "Space=Cat; Secure; HttpOnly; Max-Age=2; Domain=deno.land; Path=/; " +
    "Expires=Fri, 07 Jan 1983 15:32:00 GMT",
});
console.log(getSetCookies(headers));
```

**Expected behavior**

When 'maxage<0' or 'expires' expires, getSetCookies should either return both cookies or none.

If you consider that the cookiejar implementation needs to delete expired cookies, you should also return cookies when 'maxage<0', so that cookiejar can share the getSetCookies function. It should be up to cookiejar to determine whether the cookie expires and whether it needs to be set to the send header

**Environment**

```
export * from "https://deno.land/std@0.167.0/http/cookie.ts";
```
```
$ deno --version
deno 1.28.2 (release, x86_64-unknown-linux-gnu)
v8 10.9.194.1
typescript 4.8.3
```

**Comment by sant123** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie

### Max-Age=<number> Optional

Indicates the number of seconds until the cookie expires. A zero or negative number will expire the cookie immediately. If both Expires and Max-Age are set, Max-Age has precedence.

**Comment by sant123** [comment]
However found this RFC https://www.ietf.org/rfc/rfc2109.txt

### Max-Age=delta-seconds
      Optional.  The Max-Age attribute defines the lifetime of the
      cookie, in seconds.  The delta-seconds value is a decimal non-
      negative integer.  After delta-seconds seconds elapse, the client
      should discard the cookie.  A value of zero means the cookie
      should be discarded immediately.

**Comment by sant123** [comment]
And superseded by https://datatracker.ietf.org/doc/html/rfc6265#page-20

### The Max-Age Attribute
      If delta-seconds is less than or equal to zero (0), let expiry-time
      be the earliest representable date and time.  Otherwise, let the
      expiry-time be the current date and time plus delta-seconds seconds.

**Comment by sant123** [comment]
https://github.com/mdn/content/pull/6706

**Comment by powerpuffpenguin** [comment]
I am very confused and not sure how the standard is defined, but I have encountered a situation where the server returned -1, so I think supporting maxage<0 is better compatible with more servers.

Now I'm not sure whether the deno standard library should support maxage < 0, so I refer to the golang standard library to rewrite the cookie processing function to solve my own problem. [readSetCookies](https://github.com/powerpuffpenguin/deno-go-http/blob/main/deno/internal/cookie.ts#L257)
