### ISSUE TITLE
node: `process` doesn't export `hrtime`

### ISSUE THREAD

**Issue by juanfra684** [denoland/deno_std#2976]
**Describe the bug**

Looks like `process.hrtime` is implemented but not exported.

**Steps to Reproduce**

```plain
$ deno run npm:netlify-cli help         
error: Uncaught SyntaxError: The requested module 'process' does not provide an export named 'hrtime'
    at <anonymous> (file:///home/user/cache/deno/npm/registry.npmjs.org/@netlify/build/28.4.5/lib/time/measure.js:1:450)
```

The code in the node package: `import { hrtime } from 'process';`.

**Environment**

- OS: Linux
- deno version: 1.28.3
- std version: 0.167

I've an additional question. Are you interested in this kind of reports about the cli node applications or should I just wait until the node support is more complete?.

**Comment by bartlomieju** [comment]
> I've an additional question. Are you interested in this kind of reports about the cli node applications or should I just wait until the node support is more complete?.

Yes, of course, these are very helpful to allows us to cover more API surface.
