### ISSUE TITLE
http: Server.listenAndServeTls is missing `transport` from `addrs`

### ISSUE THREAD

**Issue by jespertheend** [denoland/deno_std#2984]
**Describe the bug**
When hosting a tls server, it's `addrs` property is missing the `transport: "tcp"` from its addresses.

**Steps to Reproduce**
1. Create `main.ts`:

```ts
import {Server} from "https://deno.land/std@0.167.0/http/server.ts";

const certPath = "./cert.crt";
const keyPath = "./key.key";

const tlsServer = new Server({
	port: 8080,
	handler: () => new Response("ok"),
});
tlsServer.listenAndServeTls(certPath, keyPath);
console.log("tls addrs:", tlsServer.addrs);

const server = new Server({
	port: 8081,
	handler: () => new Response("ok"),
});
server.listenAndServe();
console.log("plaintext addrs:", server.addrs);
```

2. Download [`cert.crt` and `key.key`](https://github.com/denoland/deno_std/files/10166005/certs.zip) and place them next to `main.ts`
3. Run `deno run -A main.ts`

**Expected behavior**
It logs
```
tls addrs: [ { hostname: "0.0.0.0", port: 8080, transport: "tcp" } ]
plaintext addrs: [ { hostname: "0.0.0.0", port: 8081, transport: "tcp" } ]
```

**Actual behaviour**
`transport: "tcp"` is missing from the tls version

**Environment**

- OS: `Ubuntu 22.04.1 LTS`
- deno version: `1.28.3`
- std version: `0.167.0`

**Comment by iuioiua** [comment]
I think this can be closed as `std/http/server.ts` is now deprecated in favour of `Deno.serve()`.

**Comment by lino-levan** [comment]
@kt3k please close when you get the chance!
