### ISSUE TITLE
Internal module's filename starts with underscore 

### ISSUE THREAD

**Issue by axetroy** [denoland/deno_std#299]
`http/http_bench.ts` is not an importable module.

https://github.com/denoland/deno_std/blob/e5a493e9e8df80abec51c06958dea755e19c40fd/http/http_bench.ts#L1-L15

similar to this `testing/main.ts`

https://github.com/denoland/deno_std/blob/e5a493e9e8df80abec51c06958dea755e19c40fd/testing/main.ts#L1-L3

We don't want users to import into their projects. they should not be exposed

```typescript
// bad usage
import * as testing from 'https://deno.land/x/std/testing/main.ts';
import * as bench from 'https://deno.land/x/std/http/http_bench.ts';
```

follow the `style guide`.

but if I rename this file, I don't know what effect it will have.

> If a filename starts with underscore, do not link to it: \_foo.ts
> Sometimes there maybe situations where an internal module is necessary but its API is not meant to be stable or linked to. In this case prefix it with an underscore. By convention, only files in its own directory should import it.

**Comment by zekth** [comment]
Added to this it may be a good idea to directly disable import with file starting with an underscore in deno if not sibling. Your thoughts? It's a bit strict but could be nice.
