### ISSUE TITLE
bug: std/flags parse loses typing when collect and string are defined

### ISSUE THREAD

**Issue by lino-levan** [denoland/deno_std#3012]
**Describe the bug**

Under some conditions, `parse` loses all of the magic typing which is kind of awful. Specifically, this occurs when `collect` AND `string` (or `boolean`) are defined.

**Steps to Reproduce**

1. Make a file like below
```typescript
const parsed = parse(Deno.args, {
  string: ["header"],
  collect: ["header"],
  alias: {
    h: "header"
  }
})
```
2. Run it with arguments `--header test --header 2` to prove that this is valid and it works
3. See that `parsed` is now of `unknown` type

**Expected behavior**

`parsed` should get the same magic typing it does in other cases in this case.

**Environment**

- OS: MacOS 11
- deno version: 1.29.1
- std version: 0.158.0

**Comment by lino-levan** [comment]
This is a blocker to https://github.com/denoland/deno_std/pull/2977 unless we are okay with making the code pretty ugly.

**Comment by kt3k** [comment]
@c4spar Could you take a look?

**Comment by c4spar** [comment]
I will have a look.
