### ISSUE TITLE
add `webgpu` folder for various WebGPU related utilities

### ISSUE THREAD

**Issue by crowlKats** [denoland/deno_std#3036]
This should then also move utilities from https://github.com/denoland/webgpu-examples

**Comment by WingZer0o** [comment]
Are you solely referring to https://github.com/denoland/webgpu-examples/blob/main/utils.ts in moving over utilities from `webgpu-examples`?

Below is what is being loaded from `deps.ts` in `utils.ts`.

```typescript
export * as gmath from "https://deno.land/x/gmath@0.1.11/mod.ts";
export * as png from "https://deno.land/x/pngs@0.1.1/mod.ts";
```
Do you mind if I take a shot at this one?

**Comment by crowlKats** [comment]
@WingZer0o I already started working on this a few days ago (forgot to link the PR), but yes, it would mainly be about moving those utilities (+ others that currently arent there; they are mainly ports from the wgpu crate that has these extras built-in). any reliance on dependencies should either be made more generic, or deleted.
I dont have too much time to work on that PR, and adding tests can be quite tricky, but feel free to open PRs towards my fork if you want to work on it
