### ISSUE TITLE
`assertEquals` shows an incorrect diff

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno_std#3039]
**Describe the bug**

The diff shown by `assertEquals` is not correct if the number of newlines differs in the left and right hand side of the assertion, and if there are repeated lines in the left hand side.

**Steps to Reproduce**

```
import { assertEquals } from "https://deno.land/std@0.170.0/testing/asserts.ts";

assertEquals("bar\nHello\nbar\nWorld1", "Hello2\nWorld");
```

results in the following output:

```
error: Uncaught AssertionError: Values are not equal:


    [Diff] Actual / Expected


-   bar\n
-   Hello\n
-   bar\n
-   World1
+   Hello2\n
+   World


  throw new AssertionError(message);
        ^
    at assertEquals (https://deno.land/std@0.170.0/testing/asserts.ts:190:9)
    at file:///mnt/artemis/Projects/github.com/denoland/deno_std/assert.ts:3:1
```

**Expected behavior**

The diff should look like this:

```
error: Uncaught AssertionError: Values are not equal:


    [Diff] Actual / Expected


-   bar\n
-   Hello\n
-   bar\n
-   World1
+   Hello2\n
+   World


  throw new AssertionError(message);
        ^
    at assertEquals (https://deno.land/std@0.170.0/testing/asserts.ts:190:9)
    at file:///mnt/artemis/Projects/github.com/denoland/deno_std/assert.ts:3:1
```
**Environment**

- OS: Ubuntu 20.04
- deno version: 1.29.1
- std version: 0.170.0

**Comment by lucacasonato** [comment]
Possibly the same as #2949

**Comment by kt3k** [comment]
The issue seems to have started from #948 (v0.100.0, the output is different from the current version, but still wrong)

v0.99.0 doesn't have this problem (though multiline strings are displayed less nicely)

```js
import { assertEquals } from "https://deno.land/std@0.99.0/testing/asserts.ts";

assertEquals("bar\nHello\nbar\nWorld1", "Hello2\nWorld");
```

```shellsession
$ deno run c.js 
error: Uncaught AssertionError: Values are not equal:


    [Diff] Actual / Expected


-   "bar\nHello\nbar\nWorld1"
+   "Hello2\nWorld"
```

cc @lowlighter

**Comment by kamilogorek** [comment]
The problem here lies in the fact that all new lines are escaped in `diffstr` function, which tokenizes strings into multiple lines. Eg. with:

```ts
import { assertEquals } from "https://deno.land/std@0.166.0/testing/asserts.ts";
assertEquals("Hello there!\n", "fetched it");
```

It'll be transformed into:
```
[ "Hello there!\\n\n", "\n" ]
[ "fetched it\n" ]
```

and then add/remove lines loop breaks, here:

```ts
if (tokens.some(({ type, value }) =>type === DiffType.common && value.trim().length)) {
  break;
}
```

as `"fetched it\n"` will be compared to `"\n"`, yielding tokens:

```
[
  { type: "removed", value: "fetched" },
  { type: "removed", value: " " },
  { type: "removed", value: "it" },
  { type: "common", value: "\n" }
]
```

effectively printing only `+ \n` as a diff result.

Tbh. I also could not understand why there's an additional newline after escaping, and `git blame` didn't help much. Any ideas?

```
tokenize(`${unescape(A)}\n`),
tokenize(`${unescape(B)}\n`),
```
