### ISSUE TITLE
[Discussion] Testing

### ISSUE THREAD

**Issue by zekth** [denoland/deno_std#306]
I have some concerns about testing. At the moment everytime we encounter a failing test it exit without testing all the tests cases. This is due to:
https://github.com/denoland/deno_std/blob/master/testing/mod.ts#L12

**EDIT**: Merged in #307

Which is not mutable. Do we add it as a parameter for the `runTests()` method? I personnaly prefer to have a total report of failing tests instead of debugging them one by one.

Also for readability i would purpose to change the prompt from:
```
test [TOML] CRLF ... ok
test [TOML] Boolean ... ok
test [TOML] Integer ... ok
test [TOML] Float ... FAILED
```
to
```
OK   [TOML] CRLF
OK   [TOML] Boolean
OK   [TOML] Integer
FAIL [TOML] Float
```

This makes it easier to read and also easier to parse, like used in the gitlab CI for coverage and so on. Ref: https://docs.gitlab.com/ee/user/project/pipelines/settings.html#test-coverage-parsing

**Comment by ry** [comment]
You may submit a PR to turn off exitOnFail.

**Comment by bartlomieju** [comment]
This was done in #307?

**Comment by zekth** [comment]
> This was done in #307?

Yes
