### ISSUE TITLE
basename cant work correctly

### ISSUE THREAD

**Issue by familyboat** [denoland/deno_std#3063]
**Describe the bug**
the result of posix.basename('aaaa/bbb////', 'a/bbb') is 'bbb////'. the trailing directory separator should be removed.

**Steps to Reproduce**
```js
import { posix } from "https://deno.land/std@0.170.0/path/mod.ts";

console.log(posix.basename('aaaa/bbb////', 'a/bbb')) // bbb////
```
**Expected behavior**

the trailing directory separator should be removed.

**Environment**

- OS: [MSYS_NT-10.0-19044]
- deno version:1.28.3
- std version: 0.170.0

**Comment by kamilogorek** [comment]
Notes:
- it works fine without suffix from 2nd argument
- it's also broken in the exact same way in the latest node `path.basename`
- unix `basename` works correctly

**Comment by kt3k** [comment]
https://github.com/denoland/deno_std/pull/3068#issuecomment-1367869543

**Comment by familyboat** [comment]
I want to explain why i issued this bug. But my English is poor. Because i wanted to use   `basename` in my project, so i checked the relevant code, and found https://github.com/denoland/deno_std/blob/1aa78c207e2aa492916a4d97dba2f74a3a52c959/path/posix.ts#L302 would cause buggy behavior in some case. So i issued this bug.
I had a solution for this bug, but i was not confident about my solution. Maybe it's a ugly solution.
I found this pr https://github.com/denoland/deno_std/pull/3068 dont correct this bug completely. Then i searched the manual page of the unix `basename`, [unix basename manual page](https://man7.org/linux/man-pages/man1/basename.1.html), and executed this command in shell, `basename /// bbb`, the result is `/`. But i thought the result would be `''`. 
So this is my thought on this bug, maybe i could make a pr😄.

**Comment by kamilogorek** [comment]
This issue (trimming trailing directories) will be impossible to fix without either:

a) changing how `parse` works - always trim trailing slashes, just as `basename` and `dirname` works in `coreutils`, this makes it impossible to reassure that `path.format(path.parse(some)) === some`
b) making `parse` and `basename` not symmetrical, where `parse(some).base !== path.basename(some)` and `parse(some).dir !== path.dir(some)`

Reasoning:
```js
path.parse("/home/user/somedir//file.zip")
// {
//   root: '',
//   dir: '"/home/user/somedir/',
//   base: 'file.zip"',
//   ext: '.zip"',
//   name: 'file'
// }
```

```shell
dirname "/home/user/somedir//file.zip"
# /home/user/somedir
```
