### ISSUE TITLE
suggestion(datetime): `difference()` changes

### ISSUE THREAD

**Issue by iuioiua** [denoland/deno_std#3086]
1. Deprecate `DifferenceOptions`, as it provides needless customisation. Deprecating it would simplify the function by just returning the values for all units, which is computationally cheap.
2. Return `0` instead of `undefined` for units for relevant cases. It makes more sense to do so intuitively, IMO.

**Comment by kt3k** [comment]
I don't recommend we should work on `datetime` difference further because Temporal is now actively developed in V8 and it seems having a good diff calculation support (zonedDateTime.until and zonedDateTime.since ref: https://tc39.es/proposal-temporal/docs/zoneddatetime.html#until )
