### ISSUE TITLE
std: fs/expand_glob.ts: expandGlob broken from 2c7274741ca669c3ee125623657e4f37e39408a0

### ISSUE THREAD

**Issue by cscheid** [denoland/deno_std#3099]
The commit [2c7274741ca669c3ee125623657e4f37e39408a0](https://github.com/denoland/deno_std/commit/2c7274741ca669c3ee125623657e4f37e39408a0) seemingly broke `**` expansion in expandGlob, in 0.161.0.

Repro:

```
$ mkdir repro
$ cd repro
$ mkdir -p foo/bar
$ touch 1
$ touch foo/1
$ touch foo/bar/1
$ deno
Deno 1.28.1
exit using ctrl+d, ctrl+c, or close()
> import { expandGlobSync } from "https://deno.land/std@0.160.0/fs/mod.ts";

undefined
> console.log([...await expandGlobSync("**/1")].length);
3
undefined
>
$ deno
Deno 1.28.1
exit using ctrl+d, ctrl+c, or close()
> import { expandGlobSync } from "https://deno.land/std@0.161.0/fs/mod.ts";

undefined
> console.log([...await expandGlobSync("**/1")].length);
2
undefined
>
```

**Comment by cscheid** [comment]
@bartlomieju I apologize for posting to the wrong repo; I thought for a second you were tracking everything over there. It's possible I missed a duplicate here as well, then.

**Comment by kamilogorek** [comment]
The `globstar` is not enabled by default for `expandGlob` and `expandGlobSync`, which means that to retain the same behavior between `0.160` and `0.161` you need to call it as `expandGlobSync("**/1", { globstar: true })`

**Comment by cscheid** [comment]
Thanks for the followup. Still, the [documentation itself states that the default behavior should be that of `globstar: true`](https://deno.land/std@0.172.0/path/mod.ts?s=GlobOptions):

<img width="850" alt="image" src="https://user-images.githubusercontent.com/285675/212555753-52b6408c-fa76-4179-9566-e6eb4fb43455.png">

As a couple of minor followup points, I'll also say that the release notes do not indicate behavior change: https://github.com/denoland/deno_std/releases/tag/0.161.0, and neither do the [PR](https://github.com/denoland/deno_std/pull/2779) or the [issue](https://github.com/denoland/deno_std/issues/2571).

**Comment by kamilogorek** [comment]
You are looking at `path` module, not `fs`, but because one inherits from other, I agree that it should be in sync. Filled a PR for that.
