### ISSUE TITLE
require should support npm

### ISSUE THREAD

**Issue by DreamZhou** [denoland/deno_std#3121]
```
import { default as caniuseLite} from "npm:caniuse-lite@^1.0.30001445"
import { createRequire } from "https://deno.land/std@0.173.0/node/module.ts";

const require = createRequire(import.meta.url);

// should support npm like this
const AD = require("npm:caniuse-lite@^1.0.30001445/data/regions/AD.js");

const region = caniuseLite.region(AD);
```

**Comment by lino-levan** [comment]
I'm curious on what the use case is for this. This seems very complex for relatively little gain.

**Comment by DreamZhou** [comment]
`caniuse-lite` have region data in data/regions dir. but don't export in its main file

in Node can do this


```
// from https://github.com/browserslist/browserslist/blob/main/node.js
try {
        compressed = require('caniuse-lite/data/regions/' + code + '.js')
      } catch (e) {
        throw new BrowserslistError("Unknown region name `" + code + "`.")
      }
```
sorry for my poor english

**Comment by lino-levan** [comment]
If you're writing the code for Deno, why not use a [dynamic import](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/import) instead? `require()` already works for node modules by default, so just leave out the npm specifier and it should work.

**Comment by kt3k** [comment]
You can do the below:

```
import * as AD from "npm:caniuse-lite@^1.0.30001445/data/regions/AD.js";
console.log(AD);
```

I think `require` should be Node.js compatible and it doesn't support Deno specific `npm:` urls (It also doesn't support http urls).
