### ISSUE TITLE
add string case utilities 

### ISSUE THREAD

**Issue by andrewbrey** [denoland/deno_std#3125]
Today, there are no string case utilities in the `std lib`, but one need only look around to `npm` briefly to see that there is a healthy appetite for shared modules to handle the complexities of converting strings between different cases:

- [case](https://www.npmjs.com/package/case) (~500k weekly downloads)
- [case-anything](https://www.npmjs.com/package/case-anything) (~90k weekly downloads)
- [pascalccase](https://www.npmjs.com/package/pascalcase) (~16M weekly downloads)
- [camel-case](https://www.npmjs.com/package/camel-case) (~16M weekly downloads)
- [lodash.camelcase](https://www.npmjs.com/package/lodash.camelcase) (~8M weekly downloads)
- [lodash.deburr](https://www.npmjs.com/package/lodash.deburr) (~1M weekly downloads)

> Note that `lodash` has _lots_ of string utilities that would be excellent to have "official" std lib support for

Some of these examples are "general" string case conversion modules, and others are for a specific case conversion (and in the case of `lodash.deburr` it is a module for removing diacritical marks from Latin character sets to make the case conversions more reliable).

I myself incorporate `case` via `npm:` specifiers in my largest Deno project because having access to a well tested and well implemented module to convert a string to:

- upper (UPPER CASE)
- lower (lower case)
- title (Title Case)
- snake (snake_case)
- pascal (PascalCase)
- camel (camelCase)
- kebab (kebab-case)
- constant (CONSTANT_CASE)

which handles the edge cases around diacritical marks, weird spacing, etc is very helpful.

I saw https://github.com/denoland/deno_std/pull/3124 which attempts to establish a `strings` module category for the `std lib`, so these are related requests, though neither depends on the other.

Thank you for considering, and thank you for Deno (and the excellent `std lib`)!

**Comment by naltun** [comment]
@andrewbrey do you see this being part of an existing module or something new?

**Comment by andrewbrey** [comment]
> do you see this being part of an existing module or something new?

That's not something I have an opinion on - I mentioned the related PR because it's attempting to establish a `strings` top-level folder in the stdlib, where I could see the outcome of _this feature request_ living, but I could also see _this feature request_ tucking neatly within the existing `fmt` top-level folder as well.

**Comment by iuioiua** [comment]
This has been mostly completed in #4082. Functions for more casing will be handled in new issues. Thank you for the suggestions and contributions.

**Comment by guy-borderless** [comment]
Was just reaching for a CONSTANT_CASE function and realized it doesn't exist. Needed to dynamically generate an env variable name. I think this should be added.

**Comment by kt3k** [comment]
Is CONSTANT_CASE the common name? I found one usage in https://www.npmjs.com/package/change-case, but wikipedia and MDN seem referencing it is SCREAMING_SNAKE_CASE https://en.wikipedia.org/wiki/Snake_case https://developer.mozilla.org/en-US/docs/Glossary/Snake_case

**Comment by guy-borderless** [comment]
> Is CONSTANT_CASE the common name? I found one usage in https://www.npmjs.com/package/change-case, but wikipedia and MDN seem referencing it is SCREAMING_SNAKE_CASE https://en.wikipedia.org/wiki/Snake_case https://developer.mozilla.org/en-US/docs/Glossary/Snake_case

I think CONSTANT is the most common and understandable for devs. However IMHO no problem to export a symbol with different names when it's different names exist. But I think if you need one, constantCase is more common than SCREAMING_SNAKE_CASE. CAPITAL_SNAKE_CASE is maybe a more literal name, regardless of what's common.

**Comment by guy-borderless** [comment]
Anyway, I don't mind that much. Hope it gets added.

**Comment by BlackAsLight** [comment]
> Was just reaching for a CONSTANT_CASE function and realized it doesn't exist. Needed to dynamically generate an env variable name. I think this should be added. 

What is your use case for a dynamic env variable? This sounds like a similar thing situation to wanting dynamic variable names.

**Comment by guy-borderless** [comment]
> > Was just reaching for a CONSTANT_CASE function and realized it doesn't exist. Needed to dynamically generate an env variable name. I think this should be added.
> 
> What is your use case for a dynamic env variable? This sounds like a similar thing situation to wanting dynamic variable names.


the scenario is using a convention for env var names.

**Comment by iuioiua** [comment]
Good idea. A PR would be welcome. `CONSTANT_CASE` makes sense to me, and I'd expect most devs to understand it. Also, it's shorter. As long as the name makes sense 🤷🏾‍♂️
