### ISSUE TITLE
file_server different path open results unexpectedly so large

### ISSUE THREAD

**Issue by dong-lufei** [denoland/deno_std#3141]
deno install -A --root "D:\scoop_user_apps\apps\deno" https://deno.land/std/http/file_server.ts

file_server .

If the current path is in E:\test\ws, the result of executing the above command is

```
Index of home /
Mode | Size | Name

(unknown mode)		chat-go/

```

If the current path is in E:\test, the result of executing the above command is
```
选择器

div-sub
```
If the current path is in `E:\`, the result of executing the above command is
```
Internal Server Error
```

**Comment by ayame113** [comment]
I can reproduce this. When I ran the file server in the root directory, I got an error like below.

```
The process cannot access the file because it is being used by another process. (os error 32): stat 'C:\/DumpStack.log.tmp'
```
