### ISSUE TITLE
Feature request: use `DENO_DEPLOYMENT_ID` as Etag in fileserver.ts

### ISSUE THREAD

**Issue by ayame113** [denoland/deno_std#3182]
Currently etags are not supported when using `http/file_server.ts` within deno deploy. (ref: https://github.com/denoland/deploy_feedback/issues/334)
This is because deno deploy does not support file modification timestamps.

Until deno deploy supports file timestamps, how about having the etag value fall back to `DENO_DEPLOYMENT_ID` if timestamps aren't available?

(Since the `DENO_DEPLOYMENT_ID` changes with each new deployment, I thought I could just use it as the etag value.)

**Comment by kt3k** [comment]
This makes sense to me

@lucacasonato Do you have any concern to this?

**Comment by kt3k** [comment]
Note: Etags are used per resource. It's ok to share the same etag across different paths.

- https://stackoverflow.com/questions/34846016/is-it-ok-for-several-paths-to-share-the-same-etag
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/ETag
