### ISSUE TITLE
Path module has both `sep` and `SEP` exports, which are the same

### ISSUE THREAD

**Issue by dsherret** [denoland/deno_std#3194]
```
> import * as path from "https://deno.land/std@0.177.0/path/mod.ts";
undefined
> path.sep
"\\"
> path.SEP
"\\"
```

Is this intentional? Maybe they should be consolidated?

**Comment by kalisjoshua** [comment]
Looking at this, the "fix" seems to be pretty straightforward but the concern might be that removing functionality after so long might be problematic. Using `git blame` it appears that this has been in existence for 2 years at this point.

I've never contributed before so I am completely new to the protocol for deprecating "features".

**Comment by kt3k** [comment]
We usually first put `@deprecate` jsdoc tag to the APIs to deprecate, and then remove them like 5 minor versions later. (Examples: https://github.com/denoland/deno_std/blob/934cb11a7e41e262dcd12be88e5a757e985359e7/http/util.ts#L9 https://github.com/denoland/deno_std/blob/934cb11a7e41e262dcd12be88e5a757e985359e7/csv/stream.ts#L5

In `std/path` there's also `SEP_PATTERN` exported. So I think we should keep `SEP` and deprecate `sep`. What do you think?

**Comment by iuioiua** [comment]
> We usually first put `@deprecate` jsdoc tag to the APIs to deprecate, and then remove them like 5 minor versions later.

Nit: @kt3k, most deprecations have been removed 3 minor versions later.

> So I think we should keep `SEP` and deprecate `sep`. What do you think?

I agree.

**Comment by timreichen** [comment]
Is uppercase instead of camelcase for constants a common design pattern in std? If so, why?
It says in the [style guide naming convention](https://deno.com/manual@v1.32.5/references/contributing/style_guide#naming-convention)  to always use camel or pascal case and specifically to avoid uppercase (for acronyms). Isn't that a breach of that convention?

**Comment by kt3k** [comment]
@timreichen Sounds a good point. I created an issue for it #3331

@kalisjoshua Node compatibility can be worth considering, but I don't think it's absolutely necessary as Deno now provides `node:path` as builtin module.

**Comment by kalisjoshua** [comment]
Good point @kt3k.

I created a PR for review and continued discussion on specifics. I'm happy to help in any way that I can. I'm just trying to get my fingers into the code and make improvements where I can.
