### ISSUE TITLE
Erroneous HTTP/2 responses to range requests with std/http's `serveFile`

### ISSUE THREAD

**Issue by ayuusweetfish** [denoland/deno_std#3198]
As title suggests; here is a playground: https://dash.deno.com/playground/weak-duck-73. Ordinary requests correctly receive a 200, but a range request results in the following:
```plain
$ curl -v -H "Range: bytes=0-10" https://weak-duck-73.deno.dev
(—— snip ——)
> GET / HTTP/2
> Host: weak-duck-73.deno.dev
> user-agent: curl/7.77.0
> accept: */*
> range: bytes=0-10
>
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* Connection state changed (MAX_CONCURRENT_STREAMS == 4294967295)!
* HTTP/2 stream 0 was not closed cleanly: PROTOCOL_ERROR (err 1)
* stopped the pause stream!
* Connection #0 to host weak-duck-73.deno.dev left intact
curl: (92) HTTP/2 stream 0 was not closed cleanly: PROTOCOL_ERROR (err 1)
```

I am not familiar with the details of HTTP/2 or TLS, but I suspect this is an issue with the interaction between both the Deploy platform and the library implementation because:
- I do not reproduce the issue on localhost (HTTP/1.1 connections) and my own remote setup (Nginx proxying incoming HTTP/2 TLSv1.2 requests to its localhost by HTTP/1.1);
- A modified `serveFile` implementation clears the problem, see below.

Details: the `serveFile` function pipes a file using its `FsFile.readable` stream (https://deno.land/std@0.168.0/http/file_server.ts?source#L192); this stream is not truncated and relies on the lower level to stop piping at the right position by inspecting `Content-Length`/`Content-Range` headers. I modified the function to pipe the file's stream through a custom `TransformStream` that truncates it, after which the 206 response is correctly constructed.

Thanks in advance for looking into this, and wish you a merry Christmas! 🎄

**Comment by ayuusweetfish** [comment]
Yes, the issue seems to persist with the newest std (0.177.0), see https://dash.deno.com/playground/expensive-donkey-81.

I also attached a stripped-down version of my own implementation, which uses a custom `TransformStream` to truncate the `ReadableStream`. Please refer to the playground source for details. Here is a comparison:

```sh
curl -v -H "Range: bytes=0-10" https://expensive-donkey-81.deno.dev/std   # either hangs, or PROTOCOL_ERROR
curl -v -H "Range: bytes=0-10" https://expensive-donkey-81.deno.dev/trunc # prints "import { se"
```

**Comment by ayame113** [comment]
This issue seems to be fixed. `serveFile` is still not returning a response with the correct length, but presumably deno deploy's server checks the `Content-Length` header and automatically truncates the response body correctly.

However, should we fix `serveFile` to return the correct length response to avoid the same problem in the future? (In that case we can use `LimitedBytesTransformStream`)
I'll leave it up to the core team to decide whether to keep this issue open.
