### ISSUE TITLE
[Documentation] Typedoc

### ISSUE THREAD

**Issue by zekth** [denoland/deno_std#321]
After @hayd mentionned it on Gitter i gave a try to [TypeDoc](https://typedoc.org/) on the `deno_std`. We have 2 problems for the moment:

- The resolution of the modules : `An import path cannot end with a '.ts' extension. Consider importing '../testing/asserts' instead.` Someone has an idea to make the module resolution work?
- The Deno style guide is not compliant with TSdoc style guide, especially the example part. **EDIT**: typo in the example @bartlomieju fixed it.

related: https://github.com/denoland/deno_std/issues/208

**Comment by bartlomieju** [comment]
@zekth check out denoland/deno#2043, I believe you need to add 2 spaces in the example and it will render properly

**Comment by zekth** [comment]
@bartlomieju right, one space was missing my bad. Will fix it. Editing the issue.

**Comment by hayd** [comment]
Is there a way to use tsconfig & declarations so that typedoc will work OOTB?

**Comment by zekth** [comment]
> Is there a way to use tsconfig & declarations so that typedoc will work OOTB?

I'll try it we may need to inject a special tsconfig for the generation step but it could work.

**Comment by zekth** [comment]
At the moment the Typedoc version is 0.14.2 and it embeds typescript 3.2.4. This does not compile our code.
The next release 0.15.0 embeds typescript 3.3.X which is still behind us.

We'll still have to wait for the auto Documentation of the API.

**Comment by hayd** [comment]
Is matching ts version with deno a hard requirement?

**Comment by zekth** [comment]
> Is matching ts version with deno a hard requirement?

Problem is the code does not compile in the Typedoc env 😢

**Comment by axetroy** [comment]
we can add a plugin for `typescript`.

try this https://github.com/justjavac/typescript-deno-plugin

**Comment by zekth** [comment]
Even with the plugin i still got compilation error. I can run it with this command :  
`typedoc  --exclude "flags/examples.ts,**/testdata/**,examples/**,**/*+(test).ts" --ignore
CompilerErrors --tsconfig ./tsconfig.json ./`

if you want to try just use : `npm install -g typedoc` 
and add this to the compiler options in the tsconfig: 
```
  "typedocOptions": {
      "mode": "modules",
      "out": "docs"
  }
```
But i'm not pretty happy with the result, especially with the title part. eg:
![2019-05-19 17_34_2s](https://user-images.githubusercontent.com/6959636/57984494-99f41180-7a5c-11e9-88d6-b4df9ff31de3.png)

Also if we use an auto documentation, maybe the `example` files may become useless no?

**Comment by ry** [comment]
I'm all for getting typedoc working, but FYI I have larger plans for documentation that will not involve typedoc.

**Comment by zekth** [comment]
> I'm all for getting typedoc working, but FYI I have larger plans for documentation that will not involve typedoc.

If it's ok for you @ry i can write down the CI scripts to generate the `/docs`. Also maybe some theming to fit the colors of `deno.land` website could be good.
