### ISSUE TITLE
[encoding/csv] [feat. req.] Make posible to use RegExp separator

### ISSUE THREAD

**Issue by devingfx** [denoland/deno_std#3224]
**Is your feature request related to a problem? Please describe.**

I was enable to parse some bad formed TSV using the csv parser because the file contains `\t` separators on some lines and `\s`separator  on some lines. 

**Describe the solution you'd like**

If we could set the separator option to a more complex RegExp, it will solve a lot of side case problems.

`{ separator: /\t|\s*/ }`

**Describe alternatives you've considered**

I end up parsing it manually...
`const tsv = content.split(/\n/).map( l=> l.split(/\t|\s*/) )`

Loosing the ability to use stream api etc... that this module offer.

**Comment by timreichen** [comment]
I think we should not alter the module to provide a solution for badly formatted content and therefore this is not an csv issue imo.
Why not just fix the content before parsing?
```ts
const content = badlyFormattedContent.replaceAll(/\s+/, "\t")
```

**Comment by devingfx** [comment]
This is an addition, not an "altering", it's an opt-in option, people using a unique char separator won't loose anything and it will still work...

The goal is to permit to use this module for parsing a lot more format than just CSV or TSV in fact, some data models are similarly "separated values" but with more complex separators or rules.

> Why not just fix the content before parsing?

I my case it's not possible because sevaral processes (which I can't alter) use the same file to store data with different separators...
It works and other processes are not complaining about giving them a regexp ;)

**Comment by sigmaSd** [comment]
>I my case it's not possible because several processes (which I can't alter) use the same file to store data with different separators...

That doesn't change anything, instead csv.parse(regex) you do read()->transform(regex,toSameDelimiter)->csv.parse(delimiter)

And this is just not csv, what you're describing is more like another format, maybe it should be called csvWithRegex

**Comment by iuioiua** [comment]
I agree with the other opinions made here. This doesn't seem like a reasonable change to make to our implementation. Instead, pre-process your file before handling with `std/csv`. Thank you to those with suggestions.
