### ISSUE TITLE
Can't send mail with SMTP in deno supabase edge function

### ISSUE THREAD

**Issue by filippo-brigati** [denoland/deno_std#3227]
Hi, I'm trying to import the "SMTP deno" package into a supabase edge function, but it keeps giving me import errors such as

```
worker thread panicked TypeError: Cannot read properties of undefined (reading 'UnexpectedEof')
    at https://deno.land/std@0.81.0/io/bufio.ts:22:51
```
 
I also tried to use the denomailer library, also by deno, but I still get the same type of errors.

This is the code

```
import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { SmtpClient } from "https://deno.land/x/smtp/mod.ts";

const client = new SmtpClient();

serve(async (req) => {
  const connectConfig: any = {
    hostname: "SMTP",
    port: 465,
    username: "USERNAME",
    password: "PASSWORD",
  };
  await client.connectTLS(connectConfig);

  await client.send({
    from: "FROM",
    to: "TO",
    subject: "Welcome!",
    content: "Hi!",
  });

  await client.close();

  return new Response(JSON.stringify(data), {
    headers: { "Content-Type": "application/json" },
  });
});
```

**Comment by lucsoft** [comment]
use denomailer 
std@81 is so old that its broken
the problem im facing that denomailer is also kinda broken
and then i tried esm.sh/nodemailer but this also kinda broken

current state of deno smtp => somewhat broken

**Comment by kt3k** [comment]
@filippo-brigati Do you run the above script in Deno Deploy? (SMTP ports are disabled in Deploy)

**Comment by filippo-brigati** [comment]
> @filippo-brigati Do you run the above script in Deno Deploy? (SMTP ports are disabled in Deploy)

yes, i tried using SMTP and not Denomailer but it still doesn't work, now i'm moving everything to a microservice in node

**Comment by filippo-brigati** [comment]
> Having the same problem… what could explain this issue ?

Deno automatically blocks the ports for sending emails, if you don't want to have problems I suggest you to use nodeJS and nodemailer

**Comment by lucsoft** [comment]
you can just enable the port? Networking in general if off by default.

btw i made a tiny port of emailjs to deno https://github.com/lucsoft/emailjs. using directly npm:emailjs has really scuffed typings

**Comment by lucsoft** [comment]
> I think you have to pay to activate them

what its just an `deno run -A test.ts` if you want to enable everything.

Do you mean Deno Deploy by any chance?

**Comment by filippo-brigati** [comment]
> > I think you have to pay to activate them
> 
> what its just an `deno run -A test.ts` if you want to enable everything.
> 
> Do you mean Deno Deploy by any chance?

yes, I used Deno Deploy
