### ISSUE TITLE
allow disabling gzip in http

### ISSUE THREAD

**Issue by jtoppine** [denoland/deno_std#3231]
**Is your feature request related to a problem? Please describe.**

Apparently the std http server implementation automagically applies gzip compression for some responses. (I'm guessing for responses that look like highly compressible text files).

While this might be desireable behaviour in most cases, there are some problems:

- it is hard to debug and test custom server logic under development when the http layer forcibly rewrites (some) responses. 
- it rewrites the etag header, which makes it hard to implement a proper etag-based caching strategy where 304 Not modified response is sent when applicable 
- acting on an deno-generated etag appropriately is hard/impossible without regenerating and re-encoding a response on the server only to see if the client already has a fresh enough cached copy
- it might possibly interfere with server-side caching strategies where already gzipped responses are stored on the server (although I think there might already be a safety mechanism where already compressed responses are not recompressed).
- value of gzip encoding is debatable anyway, where in many applications network latency, cache strategy and other factors are way more important than the minor bandwidth savings that come from compressing files in transit. typically the big files are media files or other types that don't compress well.

**Describe the solution you'd like**

While I personally think http compression should be opt-in and disabled by default. I would be happy to have at least a config option to disable it.

**Comment by jtoppine** [comment]
Update: Just realized, it appears ETag is not exactly rewritten for gzipped responses - instead, it is prefixed with a weak validation specifier W/. The actual identifier part of etag is left as is. Which feels like exactly correct behaviour, and makes the problem less severe / easy to work around.

I think the issue still stands; ability to disable the compression would be nice.

**Comment by ayame113** [comment]
Response auto-compression is implemented in Deno CLI, not std. Also, the option to disable gzip doesn't seem to exist on purpose. (https://github.com/denoland/deno/pull/13769#issuecomment-1058710480)

**Comment by kt3k** [comment]
related https://github.com/denoland/deno/issues/13830

**Comment by iuioiua** [comment]
I think this issue should be closed, as this is a concern with the runtime, not the Standard Library.

**Comment by kt3k** [comment]
Yeah, this is Deno CLI issue, not a std issue. Please track this in https://github.com/denoland/deno/issues/13830

Closing
