### ISSUE TITLE
http/server.ts: Using `serve()` with the `--watch` flag results in an "Address already in use" error.

### ISSUE THREAD

**Issue by npg418** [denoland/deno_std#3249]
**Describe the bug**
When I use the serve function in http/server.ts and run it with the --watch flag in deno run, I get an "Address already in use" error on the second and subsequent re-runs.

**Steps to Reproduce**
1
```ts
import { serve } from 'https://deno.land/std@0.179.0/http/server.ts'

await serve(_ => new Response('Response!'), {
    onListen({ hostname, port }) {
        console.log(`Server started at http://${hostname}:${port}/`)
    }
})
```

2
Run: `deno run --watch --allow-net <filename>`

3

First run
```
Watcher Process started.
Server started at http://0.0.0.0:8000/
```
Subsequent runs
```
Watcher File change detected! Restarting!
error: Uncaught (in promise) AddrInUse: Address already in use (os error 98)
    const listener = Deno.listen({
                          ^
    at Object.listen (ext:deno_net/01_net.js:356:39)
    at Server.listenAndServe (https://deno.land/std@0.179.0/http/server.ts:182:27)
    at serve (https://deno.land/std@0.179.0/http/server.ts:604:20)
    at file://<path to file>:3:7
Watcher Process finished. Restarting on file change...
```

**Expected behavior**

I want it to work fine with the --watch flag.

**Environment**

- OS: Windows 11 Pro 22H2, Ubuntu 20.04.5 LTS(WSL2)
- deno version: 1.31.2 (release, x86_64-pc-windows-msvc), 1.31.2 (release, x86_64-unknown-linux-gnu)
- std version: 0.179.0, 0.179.0

I found [this](https://github.com/denoland/deno/issues/16699#issuecomment-1465009559) solution, but it would be better to incorporate it into the serve function.

**Comment by bartlomieju** [comment]
This has already been fixed in https://github.com/denoland/deno/commit/224cff7a2f1de9cc821c34ccac63cc9e4ef17531 and will be released in Deno 1.31.3 this week
