### ISSUE TITLE
CSVStream: support outputting to a writable stream

### ISSUE THREAD

**Issue by mfulton26** [denoland/deno_std#3258]
**Is your feature request related to a problem? Please describe.**

I like to use `CSVStream` for reading CSV files. I want to also stream my output but today `CSVStream` only supports readables and not writables.

**Describe the solution you'd like**

A way to use `CSVStream` (or a similar class) with `TextEncoderStream` to pipe to a writable (e.g. to `Deno.stdout.writable`).

**Describe alternatives you've considered**

forking the code in "https://deno.land/std@0.180.0/csv/mod.ts" for `stringify` to accept a "write" callback so that a different destination other than an in-memory string can be supplied (`data: DataItem[]` would also have to be changed to `data: Iterable<DataItem>`)

**Comment by uki00a** [comment]
I think it would be useful to have two different streams like [std/json](https://deno.land/std@0.180.0/json):

* Rename exsiting `CSVStream` to `CSVParseStream`
* Add `CSVStringifyStream` to support outputting to a writable stream
