### ISSUE TITLE
base58.decode missing first byte

### ISSUE THREAD

**Issue by kratico** [denoland/deno_std#3272]
**Describe the bug**

`base58.decode("HNZata7iMYWmk5RvZRTiAsSDhV8366zq2YGb3tLH5Upf74F")` is missing the first byte in the decoded `Uint8Array`

**Steps to Reproduce**

```
❯ deno
Deno 1.31.3
exit using ctrl+d, ctrl+c, or close()
REPL is running with all permissions allowed.
To specify permissions, run `deno repl` with allow flags.
> import * as base58 from "https://deno.land/std@0.180.0/encoding/base58.ts"
undefined
> base58.decode("HNZata7iMYWmk5RvZRTiAsSDhV8366zq2YGb3tLH5Upf74F")
Uint8Array(34) [
  212, 53, 147, 199,  21, 253, 211,  28,
   97, 20,  26, 189,   4, 169, 159, 214,
  130, 44, 133,  88, 133,  76, 205, 227,
  154, 86, 132, 231, 165, 109, 162, 125,
  137, 84
]
> import * as b58c from "npm:noble-base58check"
undefined
> await b58c.decodePlain("HNZata7iMYWmk5RvZRTiAsSDhV8366zq2YGb3tLH5Upf74F")
Uint8Array(35) [
    2, 212, 53, 147, 199,  21, 253, 211,
   28,  97, 20,  26, 189,   4, 169, 159,
  214, 130, 44, 133,  88, 133,  76, 205,
  227, 154, 86, 132, 231, 165, 109, 162,
  125, 137, 84
]
```

**Expected behavior**

Decode all the base58 encoded bytes.

**Environment**

- OS: MacOS 11
- deno version: 1.31.3
- std version: 0.180.0

**Comment by kt3k** [comment]
@kratico Thanks for the report. Also confirmed `npm:noble-base58check`'s decode result matches with `btcsuite/btcutil`'s [base58](https://pkg.go.dev/github.com/btcsuite/btcutil/base58) module's result. This looks a bug on our side.
