### ISSUE TITLE
add jwt module in std

### ISSUE THREAD

**Issue by elycheikhsmail** [denoland/deno_std#3290]
in most web app we need to manipulate jwt for users auth, I think it will be good idea to have a module in std, this will make deno dev and js dev in generale more productive, since the will be reviewed by deno team and maintened for long time.

**Comment by denizdogan** [comment]
What's wrong with just using [jose](https://deno.land/x/jose@v4.14.4)? It supports pretty much every JS runtime out there, with a unified API. A deno_std alternative would not be more reviewed than that.

**Comment by PodaruDragos** [comment]
Some time has passed, maybe now it will be considered to add it to the std ?
Maybe someone from the std team can shed some light on this.

**Comment by iuioiua** [comment]
I agree with not adding this to the Standard Library. `jose` is a great module and reasonably-maintained. I don't see much of a benefit to the community to absorbing or competing the module. WDYT, @kt3k?

**Comment by kt3k** [comment]
I agree. `x/jose` looks well maintained and also Deno support looks documented well https://deno.land/x/jose@v5.1.3

Please re-open this issue or create a new one if anyone finds issue in `x/jose`
