### ISSUE TITLE
Add isUTCLeap function

### ISSUE THREAD

**Issue by RyanClementsHax** [denoland/deno_std#3294]
**Is your feature request related to a problem? Please describe.**

The difference between [Date.prototype.getFullYear](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getFullYear) and [Date.prototype.getUTCFullYear](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getUTCFullYear) can be surprising for those working with the [isLeap](https://deno.land/std@0.102.0/datetime/mod.ts?s=isLeap) which depends upon the former to determine the year when passed a `Date` object.

This means that `isLeap('2000-01-01')` returns true if you live east of GMT, but false if you live west of GMT.

**Describe the solution you'd like**

A function named `isUTCLeap` that works the same as `isLeap` but returns whether the date given to it is a leap year converted to UTC time.

This means that `isUTCLeap('2000-01-01')` always returns true.

I'm not picky on the name, but I chose `isUTCLeap` instead of `isLeapUTC` to keep with the naming conventions of `getFullYear` and `getUTCFullYear`.

**Describe alternatives you've considered**

I thought of adding a parameter to the `isLeap` function, but it seemed more idiomatic to make a new function for this.

**Side note**

This fixes the assertions in `is_leap_test.ts` where some would fail on machines set to GMT-<anything> time. I'm ok with just fixing the tests to not assert against edge cases like this, but I also figured that this would be a handy, and easy feature to add so I just went ahead and did the work.

**Comment by kt3k** [comment]
closed by #3295
