### ISSUE TITLE
http/file_server: Occasional wrong error when port is already in use

### ISSUE THREAD

**Issue by nicolo-ribaudo** [denoland/deno_std#3320]
**Describe the bug**

When the port is already in use, `file_server` occasionally fails with the wrong error.

**Steps to Reproduce**

1. Run `file_server .` in a folder
2. Run `file_server .` in a separate folder, multiple times until the error reproduces (usually <5 is enough, if it doesn't happen wait a minute and try again)

**Expected behavior**

Since both the servers are trying to listen on port 4507, the second one correctly fails.

Usually it fails with this error:
```
➜ file_server .
error: Uncaught (in promise) AddrInUse: Address already in use (os error 48)
    const listener = Deno.listen({
                          ^
    at Object.listen (ext:deno_net/01_net.js:414:39)
    at Server.listenAndServe (https://deno.land/std@0.182.0/http/server.ts:182:27)
    at serve (https://deno.land/std@0.182.0/http/server.ts:604:20)
    at main (https://deno.land/std@0.182.0/http/file_server.ts:663:5)
    at https://deno.land/std@0.182.0/http/file_server.ts:697:3
```

However, sometimes it fails with this other unhelpful error:
```
➜ file_server .
error: Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'port')
  port = (server.addrs[0] as Deno.NetAddr).port;
                                           ^
    at serve (https://deno.land/std@0.182.0/http/server.ts:606:44)
    at main (https://deno.land/std@0.182.0/http/file_server.ts:663:5)
    at https://deno.land/std@0.182.0/http/file_server.ts:697:3
```

**Environment**

- OS: macOS 13.3
- deno version: 1.32.4
- std version: 0.182.0

**Comment by lucacasonato** [comment]
Bug is related to us not waiting for `server.listenAndServe` to actually start serving.

We should probably call `Deno.listen` directly and then call `server.serve` instead of `server.listenAndServer`.

**Comment by tetraphobia** [comment]
I think this can be solved by just `await`ing the call to `server.listenAndServe`. It's effectively the same fix you described, just with less reused code.

**Comment by tetraphobia** [comment]
Turns out I'm wrong, that causes the file_server to hang.
