### ISSUE TITLE
Separate out generic modules that are compatible with other environments (browsers, node, etc)?

### ISSUE THREAD

**Issue by tlrobinson** [denoland/deno_std#333]
Some of the modules in `deno_std` could potentially work in other environments such as browsers (basically anything that doesn't use `Deno` object?) As I understand it from @ry's [recent talk](https://www.youtube.com/watch?v=z6JRlx5NC9E), Deno aims to be compatible with browsers where possible.

Is there any interest in separating out the generic modules into a repository (`denoland/std`?) that can be used by alternative environments such as browsers, and building a more comprehensive TypeScript/JavaScript standard library? I feel like there could be an opportunity here to benefit both Deno and the wider JS/TS communities.

I think the modules would still be written in TypeScript, but compiled versions (both ES and CommonJS modules) would also be published for compatibility with browsers, Node, etc.

Running the test suite in a few different environments would be critical (probably Deno, Node, and a browser).

Thoughts?

**Comment by ry** [comment]
Yes - I’ve been wanting to establish browser tests in deno_std for applicable modules. In particular our test runner previously was used in browsers (but likely has drifted out of conformance lately as we don’t have browser tests currently). I think the first step would be establishing browser CI for just the testing framework and then slowly expand it to cover more modules. Any help in this area would be very welcome.

**Comment by zekth** [comment]
@ry to test in the browser we can run the code in a chrome headless browser by using [puppeteer](https://github.com/GoogleChrome/puppeteer) for example.
If we want to use more browser the easier solution is to setup a [selenium](https://www.seleniumhq.org/) environment. If needed i'm used to work with both.

**Comment by ry** [comment]
I think puppeteer would work for a first pass - in the future we can worry about exact conformance if necessary.

**Comment by zekth** [comment]
Adding the `npm install puppeteer` in the init script and write the spec files. I can give it a try. Also i think it's not really related to make it run on all platforms because it's browser related and not environment related. I can give it a try.

**Comment by tlrobinson** [comment]
Any reason not to also run the test suite in Node?

**Comment by ry** [comment]
@tlrobinson if someone wants to do that - sure. I think browser support would be the first goal.

@zekth sounds good but we should also have the ability to run the browser tests locally.

**Comment by zekth** [comment]
@ry i'll provide a way to do it no worries.

**Comment by zekth** [comment]
Also `Node` and `browser tests` can use the same asserts has they will use the same transpiled code (using `tsc -m es6` right?). Will work on `compatibilityTest` function
