### ISSUE TITLE
Should we export UPPER_CASE_SNAKE_CASE items?

### ISSUE THREAD

**Issue by kt3k** [denoland/deno_std#3331]
Currently we export the below UPPER_CASE_SNAKE_CASE items as public APIs of deno_std:

- `async` - `ERROR_WHILE_MAPPING_MESSAGE`
- `csv` - `ERR_BARE_QUOTE`, `ERR_FIELD_COUNT`, `ERR_INVALID_DELIM`, `ERR_QUOTE`
- `datetime` - `SECOND`, `MINUTE`, `HOUR`, `DAY`, `WEEK`
- `fs` - `EOL`
- `http` - `STATUS_TEXT`
- `path` - `SEP`, `SEP_PATTERN`
- `semver` - `SEMVER_SPEC_VERSION`
- `uuid` - `NIL_UUID`
- `yaml` - `CORE_SCHEMA`, `DEFAULT_SCHEMA`, `EXTENDED_SCHEMA`, `FAILSAFE_SCHEMA`, `JSON_SCHEMA`
- `version.ts` - `VERSION`

but as pointed by @timreichen (in https://github.com/denoland/deno_std/issues/3194#issuecomment-1521338295 ), the current naming convention says:

https://deno.com/manual@v1.32.5/references/contributing/style_guide#naming-convention

> Naming convention
Always use camel or pascal case. Some Web APIs use uppercase acronyms (JSON, URL, URL.createObjectURL() etc.). Deno does not follow this convention and also uses camel or pascal case.

I think we should do either of the below:
- Keep these items as is and update the convention
- Rename these APIs to camelCase (or PascalCase)

**Comment by iuioiua** [comment]
I'm in favour of updating the convention.

**Comment by timreichen** [comment]
I can't see any gain with uppercase names, so I'd vote in favour of camel case. It is also consistent with the current convention.

**Comment by lino-levan** [comment]
I don't feel strongly either way. I would personally either keep them the same or move them to PascalCase.

**Comment by nayeemrmn** [comment]
Upper snake case is used for constants in vanilla APIs:
```ts
Number.EPSILON
Number.MAX_SAFE_INTEGER
Number.MIN_SAFE_INTEGER
```
Let's update the style guide and go with it.

**Comment by nayeemrmn** [comment]
> It is also consistent with the current convention.

@timreichen Also the deliberate use of upper snake case in std predates that section of the style guide https://github.com/denoland/manual/pull/343 :-) it was just missed in the authoring and review.

**Comment by tetraphobia** [comment]
I would vote in favor of updating the convention. Upper snake case makes sense for what's being exported, and updating the style guide to reflect that seems like the easiest route. That said, if you do settle on renaming the APIs, camel case feels more appropriate than pascal case.

**Comment by jsejcksn** [comment]
Here are some links to summaries of readability studies on Wikipedia (incl. citations):

- https://en.wikipedia.org/wiki/All_caps#Readability
- https://en.wikipedia.org/wiki/Camel_case#Readability_studies

**Comment by frou** [comment]
There wasn't much conflict with the original wording of the style guide anyway, because it was talking about acronyms/initialisms, which things like MINUTE, VERSION etc aren't.

But obviously it's good that the style guide was elaborated on, to avoid confusion.
