### ISSUE TITLE
Align serve, serveTls, and serveListener signatures with `Deno.serve`

### ISSUE THREAD

**Issue by dsherret** [denoland/deno_std#3338]
We should align these functions in http with `Deno.serve`'s signature.

https://github.com/denoland/deno/blob/main/cli/tsc/dts/lib.deno.unstable.d.ts

**Comment by kt3k** [comment]
How about just deprecating `serve` and `serveTls` after stabilizing `Deno.serve`?

ref. https://github.com/denoland/deno/pull/19141

**Comment by lino-levan** [comment]
Agree with @kt3k on this one. We should move people towards `Deno.serve`.

**Comment by dsherret** [comment]
Yeah, going to close this.
