### ISSUE TITLE
discuss:  cookie 

### ISSUE THREAD

**Issue by runnerSnail** [denoland/deno_std#334]
### node use cookie
`req.headers.cookie && req.headers.cookie.split(';').forEach(function (Cookie) {
        var parts = Cookie.split('=');
        Cookies[parts[0].trim()] = (parts[1] || '').trim();
    });
`
### How does deno read the cookie ？

**Comment by zekth** [comment]
At the moment there is no helper to get cookies. You can access it by using req.headers.get("cookie") and parse it.

Will work on a helper for this.
