### ISSUE TITLE
[async/pooledMap] res.readable[Symbol.asyncIterator] is not a function in most browsers

### ISSUE THREAD

**Issue by sntran** [denoland/deno_std#3348]
**Describe the bug**

When trying to use `async/pooledMap` in Chrome, I encountered that error. Testing with other browsers, only Firefox does not raise the error.

When the error occurs, the iteratorFn still runs, but we can't iterate the results.

Understandingly, this is on the browser vendors to implement `asyncIterator` for `ReadableStream`, but if there is another way to handle that in `async/pooledMap`, that would be great!

The relevant bugs are here:

Chromium: https://bugs.chromium.org/p/chromium/issues/detail?id=929585
Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1525852
WebKit: https://bugs.webkit.org/show_bug.cgi?id=194379

**Steps to Reproduce**

The easiest way is to use `async/pooledMap` in a Fresh island. It's hard to provide a standalone example. The example from `async/pooledMap` documentation is sufficient:

```ts
import { pooledMap } from "https://deno.land/std@0.185.0/async/pool.ts";

const results = pooledMap(
  2,
  [1, 2, 3],
  (i) => new Promise((r) => setTimeout(() => r(i), 1000)),
);

for await (const value of results) {
  // ...
}
```

**Expected behavior**

Should not see error, and the result can be iterated

**Environment**

- OS: Mac OS 13.2.1
- deno version: 1.32.4
- std version: 0.185
- Browsers: Chrome 112

**Comment by jsejcksn** [comment]
@sntran This is expected since [`async/pool.ts`](https://github.com/denoland/deno_std/blob/0.185.0/async/pool.ts) is not currently [marked as browser-compatible](https://deno.com/manual@v1.33.1/references/contributing/style_guide#document-and-maintain-browser-compatibility).

Are you requesting for it to be refactored to be compatible? I don't think that would be too difficult... something like this would do it:

[TS Playground]()

```diff
-  return res.readable[Symbol.asyncIterator]();
+  return Symbol.asyncIterator in res.readable &&
+    typeof res.readable[Symbol.asyncIterator] === "function"
+    ? (res.readable[Symbol.asyncIterator] as () => AsyncIterableIterator<R>)()
+    : (async function* () {
+      const reader = res.readable.getReader();
+      while (true) {
+        const { done, value } = await reader.read();
+        if (done) break;
+        yield value;
+      }
+      reader.releaseLock();
+   })();
```

If this is desired, I can create a PR. Perhaps an abstraction for the code above already even exists somewhere in `std`.

Thoughts, anyone?

cc @kt3k

**Comment by iuioiua** [comment]
> @sntran This is expected since [`async/pool.ts`](https://github.com/denoland/deno_std/blob/0.185.0/async/pool.ts) is not currently [marked as browser-compatible](https://deno.com/manual@v1.33.1/references/contributing/style_guide#document-and-maintain-browser-compatibility).
> 
> Are you requesting for it to be refactored to be compatible? I don't think that would be too difficult... something like this would do it:
> 
> [TS Playground](https://www.typescriptlang.org/play?noUncheckedIndexedAccess=true&removeComments=true&target=99&jsx=4&exactOptionalPropertyTypes=true&inlineSourceMap=true&inlineSources=true&isolatedModules=true&noImplicitOverride=true&ssl=94&ssc=1&pln=106&pc=10#code/PTAEGEHsAcE8CcCWBzAFgF1AJgAwEYAOAWlywGZR1UBTUAEWoDtJQBDAVysngGcA6UAEEANsNBI06HuOo9q8AG7UAJgICyASQAqoYYgDGTOXwBQJ6gA9o3TPsiMemAKIAlFwHkXAfQDqACQ0AGScvNUEABXCNADkAcVCnAGVEwVinUABeUAAiLVR4agB3UELURGFaAFtWaGhERmQ+bIBuM2AAKnaTUHbQa0gK5TUaynhWBwAzbkrpBVZhdllQCfhISrZGUAAKVh5YRn0ASlBEdHlWACMKk8Z0FnHIKnk2PYPu3tPzq+oBPNp0MaTabSVgFUDKey0OwHdjwAq3YSwAA0JVOqDYoGqFlA0P0sPh+lg73B1Am9RUoAusEoND6kAGgUQlVOph6xI0Ew2oHkq3gJ2kVFWhU2KzWoAABp8xt8AGKMcUo5igRhFUbjHhTeDVdCIezSQrlMQXajIeqs3oiMR4uFMdCI7kWah4nUNNVArWsHV6thg+bCSCFCl3Zb1RA8dHjZSgRyG4mwRDUYTKCn2aPsfSGHj8IQTM58qielFPGQAKydXocbEq9mQNOo61BtGQnpoBSjkeJgoDmypdZOec93BuXPFgmQyAKzbOTjh3HF5uJAAFLKxKtAKsTxVv0LBoLJ9EhoOhiUzrPBMABvOkDFTDaCgAC+y1W62yGHQ0B4AC4QMnmHxhEjYBHGURcABJEi0OgvAANVcRINHcaJgF2fZ9GAfphD4KQWneYloUcGQeHYYQpEya9BjvLZiVAbAkRo0AAG08BRLAUTIABdeielo7ZEGODIAD5lVVcIXzDagti2eABOEuR0C0JlqEgTgpNk8Qtn4lE8BwXTDkObjekOVo2R4zU2EKVhTm2AjMDmBZaEgTkCmI0ieGOC8GJAUA+F84kH03Lc8J4xdoFBVcKMZZlMD+TFWAsJl2HWOx2FuUAnP7etpGNepa2gVZMzkKNcXxW1EXNUBQvChs4VYalYvqaBOB9MZqXM6palyiqqrGdYpUHeA5VAWKJlS-QK0oFh9D9ZYh2oJR4GpT51gy4tQVa81gHMKwbGWMaJsw28agAHi0FEXEE6jaMwqLTi-ZUkuNeBuJaur7o0AdvlO4SAB8hFefQPq+Cpvpe-q7kGxh7q2ZRPVYe6tHUsS1gk46Lvow57sEAGgelCpcYGtHhM82jvPAApPX+WlUIOTK8apz1+RkdBYRVKNRXWKgwz2g4K1ZHE9UwFzyJVYotEBDVpkSAFqFXY7keZOQifOy6Sd4mn9DdSWtSu3jrvuhXUfR7o9YF25VlEeQEYlzVKmlinKgYCYOFIqBzYGCp4GVk3aI8n3eIBak1dNs3COkLJWEs6zoBMkOzYBD35D4JgAEdFkWLZ3NjvWn2m9B9HRLZqD9uOTk5XXS9oepHHGQwMrHCcTUpmdeVAAAyNv-ZDn5KlkHhWGQWgMiyVwPG8fwghCMJIhieI1CSFI0i73iS9L+OLc95PZ3gIuXlAVKAGtmGFYzl9ogKQ4v3iHxeh9T9JsBpdBTB8sgQrcsymZnzFYtwe4E2dgA22OpYOodMCFCQHmciLk+AQNOJcCofBB7oB8JA+QWx768Vsg6J0nBcpY1qrAeW4klaH2PowQSwksiMQ4tnUYQdl7mUjlZTAWxsHLXSpydadVV4h2wfeLIhtjAuQGEoDB2EaCMDUpkYSf9IaaTOJUfSdC9beXcIwe0cCzjpU2MRDMfcBAchKLQcUWik5mIweKDEBQyzjQpK-RW1AXoh28gWcBhpuSMCjL-AcfNQA+FoBCRgABycB4xMBuNALAag6BDEODOKwKMFRMCnDPqAbyztyh9jGIYIsrAD4f3YAKFgxY84F0pP6fQB8SitloDNa08I7RElLt5SwuCXS1hLJAC4IJfSiADEGFgZJGBhgjF4tgohSzll1JWVcNY6yVDSd5aaPZaAFDPGcbxkBkGtn5iHMx8BYFoK2NATBfDBbcgNiQ6gx0yHdioX0CRTBpFCTSbRNpzouo8HXAYSSHy8END4PUZMFh3ATCLgZUAeBDhpLOabf5HS+BNXDBClRvFEDlwRV1CoDQqCgEElkG6TJTi8Ljsw6yQifg5L+Y6T5DQ4U52XlfVRYAfAsP3rcLJM0ayQA-vNW00hUCsCUH0AqfcVBFkkTif0cg+wHL2erKOmBKV8D9EXWlALkAMpKGgw5+gZWSThbnT05TQG0WwTybg4cmK0MYUONhFyXIkUwBlclyrrmqtEIkGJdoVDqvablfSoAzXovLk60ifAa4s3DlkbINjywqGyKS7u29+DItQNJWQzq+AUx4PYbV58mXL3lRYlV8bxoV1NqLIQ45JzN23kXVNKJR6eF8AEYIoQIhRDiAkZIqQnAGWXvpPgZSM0YJkcGu+dCr53wwbHbyBQWbwE2DAimsNviMUSLASoFwBiqpxr47gHE50m0XazUAW6d17o1gTCGw5V2y3XdcDu-sdx7gyg+xJCDqCbu3burCN7D3wA4pkYeORRq8xmdkf2AB+bYn6n0-svf+-daFb1Hr3uOoS-00OfXxkBomhwMH+2hhrHm40Zm9HHSG7Ba7nhZAQ9+pBMSXCPvQdq0o5RaBbABIsZNWCLlXiCU40A9lFiPnIm6mQiSk5rpPaXDF2xhPHAuBTA+aLaLxkTFGMT1A0XMt4nRw5BQKi7GoIEN+B95PXyI6fB8QA)
> 
> ```diff
> -  return res.readable[Symbol.asyncIterator]();
> +  return Symbol.asyncIterator in res.readable &&
> +    typeof res.readable[Symbol.asyncIterator] === "function"
> +    ? (res.readable[Symbol.asyncIterator] as () => AsyncIterableIterator<R>)()
> +    : (async function* () {
> +      const reader = res.readable.getReader();
> +      while (true) {
> +        const { done, value } = await reader.read();
> +        if (done) break;
> +        yield value;
> +      }
> +      reader.releaseLock();
> +   })();
> ```
> 
> If this is desired, I can create a PR. Perhaps an abstraction for the code above already even exists somewhere in `std`.
> 
> Thoughts, anyone?
> 
> cc @kt3k

+1
