### ISSUE TITLE
Should sort_by support descending order?

### ISSUE THREAD

**Issue by sant123** [denoland/deno_std#3397]
### Discussed in https://github.com/denoland/deno_std/discussions/3393

<div type='discussions-op-text'>

<sup>Originally posted by **sant123** May 22, 2023</sup>
Hi, I see that `collections/sortBy` function orders by ascending. Could it be possible to support descending? 

Also not sure if another overloading would be good or creating a new function for this.

Thanks.</div>

I can create a PR with a new function called `collections/sortByDesc`. Please let me know 🙏🏼

**Comment by kt3k** [comment]
Maybe let's add `{ order: "asc" | "desc" }` option?
