### ISSUE TITLE
TOML misses a lot of edge cases

### ISSUE THREAD

**Issue by Aplet123** [denoland/deno_std#3402]
There are a lot of edge cases that the current TOML parsing/stringifying code misses:

`toml.stringify({"": "a"})`:
Actual:
```toml
 = "a"
```
Expected:
```toml
"" = "a"
```
`toml.parse("a = [0.1]")`:
Actual:
```text
Uncaught Error: Parse error on line 1, column 6: Array is not closed
```
Expected:
```json
{"a":[0.1]}
```

`toml.stringify({"a":{"b":{}}})`:
Actual:
```text
(empty string)
```
Expected:
```toml
[a.b]

# or

a.b = {}
```

`toml.parse("a = {}")`:
Actual:
```text
Uncaught Error: Parse error on line 1, column 5: Invalid token after "{"
```
Expected:
```json
{"a": {}}
```

`toml.stringify({"a": [{"/": "b"}, "c"]})`:
Actual:
```toml
a = [{/ = "b"},"c"]
```
Expected:
```toml
a = [{"/" = "b"},"c"]
```

**Comment by ry** [comment]
Patches welcome!

**Comment by Aplet123** [comment]
@ry Unfortunately I'm much better at breaking parsers than making them so I'd appreciate if someone who's better than me at parsing could help out :)

**Comment by brianknight10** [comment]
Did #3403 resolve this issue, or is there more work to be done? I'd be willing to work on it if there is.

**Comment by Aplet123** [comment]
@brianknight10 #3403 fixes the 3 edge cases listed here relating to `toml.stringify`; the 2 cases relating to `toml.parse` are still unfixed as far as I know.
