### ISSUE TITLE
Suggestion: deprecate the `unzip` function in favor of the `zip` function

### ISSUE THREAD

**Issue by ayame113** [denoland/deno_std#3407]
**Is your feature request related to a problem? Please describe.**

The current `zip()` is upward compatible with `unzip()`. Both just transpose a 2D array.

```ts
import { zip } from "https://deno.land/std@0.189.0/collections/zip.ts";
import { unzip } from "https://deno.land/std@0.189.0/collections/unzip.ts";

const target = [[0, "a"], [1, "b"]];

const zipped = zip(...target);
console.log(zipped); // [ [ 0, 1 ], [ "a", "b" ] ]

const unzipped = unzip(target);
console.log(unzipped); // [ [ 0, 1 ], [ "a", "b" ] ]
```

**Describe the solution you'd like**

How about deprecating unzip in favor of zip?

**Describe alternatives you've considered**

The only difference between zip and unzip is that when they receive multiple arrays of different lengths, they align to the shortest or the longest.

```ts
import { zip } from "https://deno.land/std@0.189.0/collections/zip.ts";
import { unzip } from "https://deno.land/std@0.189.0/collections/unzip.ts";

const target = [[0, "a"], [1]];

const zipped = zip(...target);
console.log(zipped); // [ [ 0, 1 ] ]

const unzipped = unzip(target);
console.log(unzipped); // [ [ 0, 1 ], [ "a", undefined ] ]
```

In Python, [there is no unzip function](https://stackoverflow.com/questions/13635032/what-is-the-inverse-function-of-zip-in-python), but instead [there is a itertools.zip_longest function](https://docs.python.org/3/library/itertools.html#itertools.zip_longest). How about deprecating unzip, adding `zipLongest` and resolving #1203?

**Comment by denizdogan** [comment]
I think zip and unzip should be left separate even _if_ they'd end up pointing at the same function, because they are different conceptually. `zip(*zipped_list)` doesn't read "unzip" to me, and probably never will, having worked with Python for many years. I see no reason why deno_std would take any inspiration from Python of all languages.

**Comment by ayame113** [comment]
deno_std's `zip` function takes a variable length argument instead of two arguments. There is a big difference between `zip` and `unzip` when the `zip` function takes 2 arguments, but not much difference between them when the `zip` function takes 3 or more arguments. For this reason, I thought it would be possible to use Python's naming conventions.
That being said, I don't have a strong opinion on this either, so feel free to leave the unzip naming as is. Let's close this issue. 👍
