### ISSUE TITLE
bug: latest release marked as 0.177.1 (on deno.land)

### ISSUE THREAD

**Issue by Bellisario** [denoland/deno_std#3408]
**Describe the bug**

On https://deno.land/std the latest release is marked as 0.177.1, while we're on 0.189.0.

![bug](https://github.com/denoland/deno_std/assets/72039923/b50a783e-a604-41f6-bfdc-03036b985e87)

**Steps to Reproduce**

Go to https://deno.land/std and see that the latest release is marked as 0.177.1.

**Expected behavior**

The latest release should be 0.189.0.

**Environment**

The problem is on deno.land and not on my usage of the library.

**Comment by crowlKats** [comment]
The tags are in order of release date, and today a patch release was released for 0.177.1

**Comment by sigmaSd** [comment]
Can that be changed to be by semver comparison or is it not worth it ?

**Comment by sylc** [comment]
> Can that be changed to be by semver comparison or is it not worth it ?

+1 to changing to semver comparison . IMHO, it is unintuitive that the latest version is not the latest semver version. In this example, it seems that version `0.189.0` is a beta version and `0.177.1` should be preferred, which I don't think is the case.
