### ISSUE TITLE
Retry is unreliable

### ISSUE THREAD

**Issue by bodograumann** [denoland/deno_std#3425]
We are using a retry to handle the situation where a peer service is still starting up.
For this we want to have a reliable time that the retry will back-off at least.

So with the initial retry implementation, the default implementation should have yielded a reliable retry of `31s = 1s + 2s + 4s + 8s + 16s`.
Now with the jitter introduced this would effectively be halved.

There are several problems with this however:
1. The jitter is not properly documented for the retry function.
2. If unlucky there could be five times `0s` back-off.
3. The implementation is faulty and will actually back-off (Math.rand times) `1s + 1s + 2s + 4s + 8s` by default and thus unexpectedly yield an even lower back-off timespan.
4. Looking more closely at the implementation there is one useless wait delay after the last attempt. So actually the real retry time is only `8s = 1s + 1s + 2s + 4s`
    - fn()
    - wait 1s * Math.rand
    - ...
    - fn()
    - wait 8s * Math.rand
    - raise RetryError

**Steps to Reproduce**

```typescript
import { retry } from "https://deno.land/std@0.190.0/async/retry.ts";
async function retryTime() {
  let start = new Date().getTime();
  try {
    await retry(() => { throw new Error("Failed") });
  } catch(exc) {}
  let stop = new Date().getTime();
  return stop - start;
};
await Promise.all([retryTime(), retryTime(), retryTime(), retryTime(), retryTime(), retryTime(), retryTime()])
```

**Expected behavior**

The back-off should be at-least `minTimeout` for each step and thus result in a total retry duration of at least `minTimeout * maxAttempts`.
This should be apparent from the documentation, as well as what the expected mean and maximum retry durations will be.

**Environment**

- OS: Arch Linux
- deno version: 1.33.2
- std version: 0.190.0

**Comment by bodograumann** [comment]
Related discussions:
- https://github.com/denoland/deno_std/issues/3378#issuecomment-1546614806
- https://github.com/denoland/deno_std/pull/3379#issuecomment-1554031975

Not sure how best to solve the issue though. Maybe switch to decorelated or equal jitter functions?

**Comment by kt3k** [comment]
Maybe something like `randomBetween(minTimeout, Math.min(cap, base * 2 ** attempt))`?

**Comment by bodograumann** [comment]
> Maybe something like `randomBetween(minTimeout, Math.min(cap, base * 2 ** attempt))`?

That sounds good to me. I would look into creating a pull-request.

**Comment by bodograumann** [comment]
I have tried your proposal, @kt3k , but the guaranteed retry duration will only be `minTimeout * (maxAttempts - 1)`.
So if we also want a hard back-off with a low `minTimeout`, we need a high number for `maxAttempts`.
Possibly retrying often is still better than not retrying long enough, but I feel we can do better still.

How about this?
```typescript
const jitter = 0.2;
const exp = Math.min(cap/(1+jitter), base * multiplier ** attempt);
return exp*randomBetween(1-jitter, 1+jitter);
```
