### ISSUE TITLE
WebSocket only receiving every second event

### ISSUE THREAD

**Issue by drdreo** [denoland/deno_std#343]
I am playing around with a deno socket-based chat and have encountered that only every second sent event is received on the server. I haven't figured out yet why `for await (const ev of socket.receive())` would only trigger every second time.

I have checked the network requests, and the event is definitely being sent from the client but never received on the server. 

A demo repo: https://github.com/drdreo/deno-chat

**Comment by evbogue** [comment]
@drdreo I'm a little stumped here too. 

I tried a very simple app

```
import { serve } from "https://deno.land/x/http/server.ts";
import { acceptWebSocket, isWebSocketCloseEvent } from "https://deno.land/x/ws/mod.ts";

async function main() {
  console.log("WebSocket listening on 0.0.0.0:3000");

  for await (const req of serve("0.0.0.0:3000")) {
    console.log(req.url)
    if (req.url === '/ws') {
      (async () => {
        const sock = await acceptWebSocket(req)
        console.log(sock)
      })
    }
  }
}

main();
```

And it stops printing `req.url` on the 7th request from the client.

**Comment by drdreo** [comment]
The server `serve()` works fine for me. Tested your code as well and no problems having >7 requests.

**Comment by drdreo** [comment]
Seems to be fixed already.
