### ISSUE TITLE
(async/retry): what the argument maxAttempts of retry function does mean indeed? All attempts or all attempts except first attempt?

### ISSUE THREAD

**Issue by familyboat** [denoland/deno_std#3433]
According to this line https://github.com/denoland/deno_std/blob/1ec581bf7e1c0ac6fc9a6c61d6e9603d628a0c1f/async/retry.ts#LL19C7-L19C35 (this line is introduced in https://github.com/denoland/deno_std/pull/3427, which is introduced in version 191 of std), I am confused about the meaning of the argument `maxAttempts`. I think number of retry attempts means attempts except first attempt, which is not a retry attempt. 
```ts
import { retry } from "https://deno.land/std@0.191.0/async/mod.ts";

let count = 0

function panic() {
  if (!count) {
    console.log('It is just an attempt.');
  } else {
    console.log(`It is ${count}th retry attempt.`);
  }
  count++;
  throw new Error()
}

// the argument maxAttempts is 5 by default.
retry(
  panic
)
```
The result is
```ts
It is just an attempt.
It is 1th retry attempt.
It is 2th retry attempt.
It is 3th retry attempt.
It is 4th retry attempt.
error: Uncaught (in promise) RetryError: Exceeded max retry count (5)
        throw new RetryError(error, options.maxAttempts);
              ^
    at retry (https://deno.land/std@0.191.0/async/retry.ts:104:15)   
Caused by: Error
    at panic (file:///D:/familyblue/codebase/deno_std/test.ts:12:9)  
    at retry (https://deno.land/std@0.191.0/async/retry.ts:101:20) 
```

**Comment by kt3k** [comment]
We changed that interpretation in https://github.com/denoland/deno_std/pull/3427/files , but it might have been wrong regarding the error message `RetryError: Exceeded max retry count (5)` (as the retry only happens 4 times)

@bodograumann What do you think?

**Comment by bodograumann** [comment]
True, I opted to implement in number of attempts, not number of retries.
The error message might have to be adjusted still. Let me look into that.

**Comment by kt3k** [comment]
I now think the doc was clear about `maxAttemps` being max 'retry' attempts (`The maximum amount of retries until failure.`), and #3427 was unintentional breaking change instead of a fix. Can you restore the previous behavior of `maxAttemps` handling?

**Comment by bodograumann** [comment]
The previous behaviour was actually doing `maxAttempts` attempts, then waiting one more time and *not* doing another retry.
If we want to increase it by `+1` that would be ok with me, but then it shouldn't be called `maxAttempts`, but `maxRetries`.

**Comment by familyboat** [comment]
> The previous behaviour was actually doing `maxAttempts` attempts, then waiting one more time and _not_ doing another retry. If we want to increase it by `+1` that would be ok with me, but then it shouldn't be called `maxAttempts`, but `maxRetries`.

What you @bodograumann say about `maxAttempts` is true. You @kt3k can switch the version of deno_std to 189 where retry function is the previous behaviour, then you will find that the result of above code does not change.

**Comment by kt3k** [comment]
@bodograumann @familyboat Ah, ok. Thanks for your comments. Now I confirmed #3427 didn't change the attempt counts (retry number). Sorry for my confused comment..

**Comment by familyboat** [comment]
@kt3k ，I am sorry too. https://github.com/denoland/deno_std/pull/3427 is introduced in version 191 of std. But i can confirm https://github.com/denoland/deno_std/pull/3427 does not change the behaviour of `maxAttempts`.
