### ISSUE TITLE
`assertThrows` doesn't throw if error message strings differ

### ISSUE THREAD

**Issue by vwkd** [denoland/deno_std#3448]
**Describe the bug**

The first overload `assertThrows(fn: () => unknown, msg?: string): unknown` incorrectly doesn't throw if the error message strings differ.

The second overload which includes a `ErrorClass: new (...args: any[]) => [E]` does correctly throw.

**Steps to Reproduce**

```ts
import { assertThrows } from "https://deno.land/std@0.191.0/testing/asserts.ts"

assertThrows(() => { throw new Error("foo") }, "bar");
//

assertThrows(() => { throw new Error("foo") }, Error, "bar");
// Uncaught AssertionError: Expected error message to include "bar", but got "foo".
```

**Expected behavior**

```ts
import { assertThrows } from "https://deno.land/std@0.191.0/testing/asserts.ts"

assertThrows(() => { throw new Error("foo") }, "bar");
// Uncaught AssertionError: Expected error message to include "bar", but got "foo".

assertThrows(() => { throw new Error("foo") }, Error, "bar");
// Uncaught AssertionError: Expected error message to include "bar", but got "foo".
```

**Environment**

- OS: macOS 12.6.6
- deno version: 1.34.1
- std version: 0.191.0

**Comment by vwkd** [comment]
Oh, the `msg?: string` argument is only a custom message, not the expected message string. Only the second overload allows to check the expected message string in the `msgIncludes?: string` argument.

Related: https://github.com/denoland/deno_std/pull/3253

**Comment by JoakimCh** [comment]
As of 0.203.0 this is still broken!
```
assertThrows<E extends Error = Error>(
  fn: () => unknown,
  ErrorClass: new (...args: any[]) => E
  msgIncludes?: string,
  msg?: string,
): E
```
[As documented here](https://deno.land/std@0.203.0/testing/asserts.ts?s=assertThrows) will not check if `msgIncludes` is included even when calling it with `ErrorClass`, `msgIncludes` and `msg`.

So please reopen.

**Comment by JoakimCh** [comment]
Still doesn't work even when given two strings and an error class.
