### ISSUE TITLE
`fs.walk()` throws on broken symlinks

### ISSUE THREAD

**Issue by joehillen** [denoland/deno_std#3452]
**Describe the bug**

When using [walk()](https://github.com/joehillen/deno_std/blob/main/fs/walk.ts#L81) with `followSymlinks` set to true
and there is a symlink that points to a destination that does not exist; the function will throw an error.

It's not possible to handle this error as a user because the error is thrown in
the `for await` loop deep in the recursive call stack.

**Steps to Reproduce**

On a Unix system, create a symlink that points to a non-existing destination:

```bash
mkdir /tmp/link-test
cd /tmp/link-test
ln -s /tmp/non-existing-dir/ link
```

Then run the following code:

```ts
import { walk } from "https://deno.land/std@0.192.0/fs/walk.ts";

walk("/tmp/link-test", { followSymlinks: true })
  .then((files) => {
    console.log(files);
  });
```

The following exception will be thrown:

```txt
error: Uncaught (in promise) WalkError: No such file or directory (os error 2): realpath '/tmp/link-test/link' for path "/tmp/link-test"
  return new WalkError(err, root);
         ^
    at wrapErrorWithPath (https://deno.land/std@0.192.0/fs/walk.ts:48:10)
    at walk (https://deno.land/std@0.192.0/fs/walk.ts:134:11)
    at eventLoopTick (ext:core/01_core.js:182:11)
    at async file:///tmp/link-test.ts:3:18
Caused by: NotFound: No such file or directory (os error 2): realpath '/tmp/link-test/link'
    at async walk (https://deno.land/std@0.192.0/fs/walk.ts:112:16)
    at async file:///tmp/link-test.ts:3:18
```

**Expected behavior**

I don't think it's useful to throw when trying to `walk()` a broken link, as there is nothing the caller can do to handle it when it happens.

The simplest solution would be to catch and ignore the `NotFound` exception
when calling `realpath()` on a symlink.

**Environment**

- OS: Arch Linux
- deno version: 1.34.1
- std version: 0.192.0

**Comment by kt3k** [comment]
> It's not possible to handle this error as a user because the error is thrown in
the for await loop deep in the recursive call stack.

The error can be caught by surrounding the for-await loop with a try-catch block. The below code catches `WalkError` if there's a broken symlink:

```js
import { walk } from "jsr:@std/fs@^0";
const includeSymlinks = true;
const followSymlinks = true;
try {
  for await (const item of walk("foo", { includeSymlinks, followSymlinks })) {
    console.log(item);
  }
} catch (e) {
  console.log(e);
}
```

Because we now have `includeSymlinks` option, the broken symlinks can be handled better like the below structure:

```js
import { walk } from "jsr:@std/fs";

const includeSymlinks = true;
const followSymlinks = false;
for await (const item of walk("foo", { includeSymlinks, followSymlinks })) {
  console.log(item);
  try {
    if (item.isSymlink) {
      await Deno.stat(item.path);
    }   
  } catch (e) {
    if (e instanceof Deno.errors.NotFound) {
      // handle broken symlink
      console.log(e);
    }   
  }
}
```

This script handles each broken link separately. That means it has more granular control to broken symlinks. So I think we don't need to ignore broken symlinks with `followSymlinks: true`.
