### ISSUE TITLE
Moving the `examples` directory

### ISSUE THREAD

**Issue by not-my-profile** [denoland/deno_std#3463]
The `examples` directory currently resides directly next to the directories containing the public API and uses the same naming convention as the other directories containing the public API. Likewise it is also [listed in the documentation](https://deno.land/std@0.192.0?doc) next to the public APIs.

I think it would make sense to move `examples` to e.g. `_examples` to clarify that it's not actually part of the standard library (and I think the `_` prefix would also result in the directory being excluded from the documentation page).

**Comment by lino-levan** [comment]
I personally am of the opinion that there should be no examples in the std repo, and we should move everything to [denobyexample](https://examples.deno.land) or the [examples in the manual](https://deno.com/manual/examples).

**Comment by not-my-profile** [comment]
Right that would also address my concern of the directory looking like it belongs to the API.
