### ISSUE TITLE
Investigate performance of "serveDir" API

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno_std#3473]
According to results from https://github.com/Im-Beast/http_benchmarks `serveDir` API is very slow with both `std/http` server as well as `Deno.serve()` API:

![image (2)](https://github.com/denoland/deno_std/assets/13602871/d006227c-45f3-4371-a6de-8a6b32643ff7)

It's very worring that there's a huge variance between "mean" and "max" throughput.

We should get to the bottom of the problem and fix it.

**Comment by littledivy** [comment]
This is just bad benchmarking. 

- The `serveDir` benchmarks have the console logging turned on but not in other benchmarks.

- Response size is not the same. Eg: Hono does not send Etag, Last-Modified headers. With Etag, caches can be more efficient in the real world.

Headers from serveDir:
```
< HTTP/1.1 200 OK
< accept-ranges: bytes
< content-length: 32
< content-type: text/plain; charset=UTF-8
< date: Fri, 07 Jul 2023 12:39:54 GMT
< etag: W/"20-DhqgH1oexd6q3/5FlHmFalbZvhP"
< last-modified: Fri, 07 Jul 2023 12:39:53 GMT
< server: deno
< vary: Accept-Encoding
```

Headers from Hono:
```
< HTTP/1.1 200 OK
< content-type: text/plain; charset=utf-8
< vary: Accept-Encoding
< content-length: 32
< date: Fri, 07 Jul 2023 12:53:23 GMT
```
- Functionality differs. Eg: Hono does not support byte ranges.

There are potential improvements that can be made to std's serveDir but this is not the right benchmark for that.

**Comment by iuioiua** [comment]
I agree that these benchmarks aren't entirely fair. Either way, what ideas did you have to improve the performance of `serveDir()`? The ideas of others are also welcome.

**Comment by iuioiua** [comment]
These benchmarks have now been reworked to be categorised by the headers each framework responds with, making it fairer. See https://github.com/Im-Beast/http_benchmarks/blob/main/results/file_server/README.md.
