### ISSUE TITLE
Undocumented breaking change between v0.172.0 and v0.173.0

### ISSUE THREAD

**Issue by jaydenseric** [denoland/deno_std#3481]
This module used to exist:

https://deno.land/std@0.172.0/streams/conversion.ts

Now it doesn't:

https://deno.land/std@0.173.0/streams/conversion.ts

Yet this major breaking change is not documented in the v0.173.0 release notes:

https://github.com/denoland/deno_std/releases/tag/0.173.0

**Comment by kt3k** [comment]
We tagged that commit `chore` https://github.com/denoland/deno_std/pull/3107 and that didn't show up in release note.

I agree this should appear in release note.

**Comment by kt3k** [comment]
Added `BREAKING(streams, archive): remove deprecated exports (#3107)` entry in https://github.com/denoland/deno_std/releases/tag/0.173.0

Also changed the PR title of #3107 

Thanks for your report @jaydenseric
