### ISSUE TITLE
Deprecate `readableStreamFromIterable` in favor of `ReadableStream.from`

### ISSUE THREAD

**Issue by ayame113** [denoland/deno_std#3484]
Since `ReadableStream.from` was introduced in https://github.com/denoland/deno/pull/19446, I think we can remove `readableStreamFromIterable` instead.

Note: It seems that there is no type definition for `ReadableStream.from` as of v1.35.0, but it seems to have been added later at https://github.com/denoland/deno/pull/19438.
https://github.com/denoland/deno/blame/1edc8693bfc4b75e3bb61fc8dc531bdf569b332d/ext/web/lib.deno_web.d.ts#L808

**Comment by kt3k** [comment]
good point

**Comment by jollytoad** [comment]
Can the std lib `readableStreamFromIterable` remain in the std lib until it's commonly implemented in browsers though? ...

https://caniuse.com/?search=ReadableStream.from

I just blindly updated my code, some of which I bundle up and ship within a ServiceWorker, and just hit the problem that `ReadableStream.from` isn't implemented in most browsers yet.
