### ISSUE TITLE
Move `/flags/mod.ts` to `/flags.ts`

### ISSUE THREAD

**Issue by boywithkeyboard** [denoland/deno_std#3493]
Wouldn't it make sense to move `/flags/mod.ts` to `/flags.ts`? The directory contains only two files: the mod.ts one and a test file.

Related to #3445.

**Comment by lino-levan** [comment]
I'm strongly against introducing top-level files into std. I've never seen this precedent before and this feels like it will clutter up the repository.

**Comment by ry** [comment]
No top level modules - it interferes with future design directions
