### ISSUE TITLE
Deno's HTTP server doesn't use "best compression option" (Brotli) for some browsers

### ISSUE THREAD

**Issue by marc-barry** [denoland/deno_std#3503]
**Describe the bug**

This copies the issue as reported in https://github.com/denoland/deno/issues/19690. In that particular issue I was recommended to move to `Deno.serve` and that the bug was in fact in `deno_std` (https://github.com/denoland/deno/issues/19690#issuecomment-1625427658). Thus, I'm basically copying the text from the aforementioned issue below.

We have opted to implement a proxy with Deno and Oak to replace some legacy NGINX configurations. We have observed that depending on the order of the `Accept-Encoding` header, Deno doesn't always select the most optimal `Content-Encoding` option. There is no way within the server itself to set a preference.

The default `Accept-Encoding` headers for Google Chrome are `Accept-Encoding: gzip, deflate, br` and when requests are made to the Deno HTTP server for compressible content it will prefer `gzip`. It has been shown and through our own evidence that Brotli can result in significantly smaller content sizes and thus when present with the above option we'd prefer to have the `Content-Encoding` be `br`. The `Accept-Encoding` by browsers isn't easily changeable by users and thus we need to find a way to select the most optimal for our use case on the server side. It is our understanding that Firefox, Brave and quite possibly a few others use the same value of `Accept-Encoding: gzip, deflate, br` for their request headers.

When using https://chrome.google.com/webstore/detail/modheader-modify-http-hea/idgpnmonknjnojddfkpgkljpfnnfcklj on Google Chrome and setting the request header to `Accept-Encoding: br, gzip, deflate` then Deno responds with `Content-Encoding: br`. This leads me to believe it is purely an ordering situation when selecting the compression for the content.

Ideally, we'd be able to set `br` as the preferred, if present in `Accept-Encoding` header. I did attempt to modify the header on the request to see if I could dynamically do that in the handler but the request headers are immutable.

Is it possible to tell Deno to prefer `br` over `gzip` when both are present regardless of order? I cannot seem to find a way to do so. Below is the version of Deno I'm using with a minimal code example to illustrate what I'm reporting.

**Steps to Reproduce**

```console
deno --version
deno 1.34.3 (release, aarch64-apple-darwin)
v8 11.5.150.2
typescript 5.0.4
```

```typescript
import { serve } from "https://deno.land/std@0.192.0/http/server.ts";

const port = 3000;

const handler = (request: Request): Response => {
  const body = `User-Agent: ${
    request.headers.get("user-agent") ?? "Unknown"
  }\nAccept-Encoding: ${request.headers.get("accept-encoding") ?? "Unknown"}`;

  return new Response(body, { status: 200 });
};

console.log(`HTTP webserver running. Access it at: http://localhost:3000/`);
await serve(handler, { port });
```

```console
deno run --allow-net webserver.ts
HTTP webserver running. Access it at: http://localhost:3000/
Listening on http://localhost:3000/
```

Then simply test with different browsers for output which will look like the following:
```console
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
Accept-Encoding: br, gzip, deflate
```

In Google Chrome you can leverage the **Network** tab in the **Developer Tools** to see the response headers and confirm the `Content-Encoding` values.

**Expected behavior**

If `br` is included in `Accept-Encoding` that it would be preferred over `gzip`.

**Environment**

- OS: macOS 13.4.1 (c) (22F770820d)
- deno version: 1.34.3 and higher
- std version: 0.192.0 and higher

**Comment by lino-levan** [comment]
`serve` is deprecated. I'd highly recommend moving to `Deno.serve`.

**Comment by marc-barry** [comment]
> `serve` is deprecated. I'd highly recommend moving to `Deno.serve`.

There is no deprecation notice under https://deno.land/std@0.195.0/http/mod.ts?s=serve. Where are deprecation notices posted for this repo?

**Comment by lino-levan** [comment]
Ah sorry, I should have stated that `serve` is deprecated in the next release (`0.196.0`). It will be dropped when we hit `1.0.0`.

**Comment by marc-barry** [comment]
> Ah sorry, I should have stated that `serve` is deprecated in the next release (`0.196.0`). It will be dropped when we hit `1.0.0`.

Ahh. I see. Thanks for the context. We have already moved to `Deno.serve`. So 👍.
