### ISSUE TITLE
Repo: use commitizen

### ISSUE THREAD

**Issue by sh7dm** [denoland/deno_std#351]
Not an issue, but I think it'll be better if we use commitizen for commit messages, it'll be easier to understand commit messages. Created issue to know your opinion.

**Comment by zekth** [comment]
I think it's more revelant to add this to this issue : https://github.com/denoland/deno/issues/2075

As the guideline may be the same for the whole project.

**Comment by ry** [comment]
I had never heard of commitzen before, but I'm glad to finally understand why everyone is prefixing their commits with "feat:" and whatnot.

I can't say I'm a big fan of this style, and I don't want to introduce a dependency on some random node utility program.

I would rather follow Go's commit message style guide. "feat" and "bug" are not the most important thing I need to know, but rather what part of the code base they are touching. Additionally "feat" and "bug" and "refactor" are very often not mutually exclusive.

https://github.com/golang/go/wiki/CommitMessage
https://golang.org/doc/contribute.html#commit_messages

I'd love to adapt these guides for Deno's style guide.

**Comment by axetroy** [comment]
In fact, the introduction of commitizen does not require any cost.

Just install the app for Github.

https://github.com/tlvince/validate-commit-msg-bot

Unfortunately, this project is not maintained, but it is enough

**Comment by zekth** [comment]
"this project is not maintained" so i don't think it's good to use it

**Comment by sh7dm** [comment]
2nd one is a nice idea

**Comment by axetroy** [comment]
It seems that ry has installed the `commitlint-bot`.

This issue not can be closed
