### ISSUE TITLE
`std/testing/bdd.ts` `sanitizeXXX` should be able to not at top level

### ISSUE THREAD

**Issue by loynoir** [denoland/deno_std#3512]
**Describe the bug**

**Steps to Reproduce**

`std/testing/bdd.ts` describe it  `sanitizeXXX` not working.

```ts
import { describe, it } from 'https://deno.land/std@0.196.0/testing/bdd.ts'

describe('reproduce', () => {
  it('reproduce', { sanitizeOps: false, sanitizeResources: false }, async () => {
    setTimeout(() => {}, 100)
  })
})
```

```txt
...
reproduce ...
  reproduce ... ok (0ms)
reproduce ... FAILED (12ms)

 ERRORS 

reproduce => https://deno.land/std@0.196.0/testing/_test_suite.ts:191:10
error: Leaking async ops:
  - 1 async operation to sleep for a duration was started in this test, but never completed. This is often caused by not cancelling a `setTimeout` or `setInterval` call.
To get more details where ops were leaked, run again with --trace-ops flag.

 FAILURES 

reproduce => https://deno.land/std@0.196.0/testing/_test_suite.ts:191:10

FAILED | 0 passed (1 step) | 1 failed (42ms)

error: Test failed
```

**Expected behavior**

```ts
import { describe, it } from 'https://deno.land/std@0.196.0/testing/bdd.ts'

Deno.test('reproduce', { sanitizeOps: false, sanitizeResources: false }, async () => {
  setTimeout(() => {}, 100)
})
```

```txt
...
reproduce ... ok (0ms)

ok | 1 passed | 0 failed (98ms)
```

**Environment**

- OS: [e.g. Ubuntu 20.04, MacOS 11]
- deno version: 1.35.3
- std version: 0.196.0

### Related

https://github.com/denoland/deno/issues/20021

**Comment by kt3k** [comment]
cc @KyleJune

**Comment by KyleJune** [comment]
`describe` and `it` are just thin wrappers around `Deno.test` and `t.step`. They work the same way. Your `Deno.test` example is not equivalent. I believe if you put a step inside that, with the sanitize options disabled only on the inner step, you would have the same issue of the inner test step passing but the top level test failing. That's because you are leaking async ops for the top level test that still has sanitization enabled. It's just less clear in your example because the group and the inner test step have the same name.

If you want to disable sanitization for the test group, add the options to your `describe` call so that it will pass them to `Deno.test` when registering the group of tests.

**Comment by loynoir** [comment]
Verified 

```ts
import { describe, it } from "https://deno.land/std@0.197.0/testing/bdd.ts";

Deno;

describe("reproduce", { sanitizeOps: false, sanitizeResources: false }, () => {
  it("reproduce", async () => {
    setTimeout(() => {}, 100);
  });
});
```

```txt
running 1 test from ./reproduce.ts
reproduce ...
  reproduce ... ok (0ms)
reproduce ... ok (1ms)

ok | 1 passed (1 step) | 0 failed (20ms)
```

**Comment by loynoir** [comment]
But in below code, typescript `ItArgs` allow `sanitizeXXX`.

So, the types is wrong.

```ts
import { describe, it } from "https://deno.land/std@0.197.0/testing/bdd.ts";

Deno;

describe("reproduce", () => {
  it(
    "reproduce",
    { sanitizeOps: false, sanitizeResources: false },
    async () => {
      setTimeout(() => {}, 100);
    }
  );
});
```

**Comment by KyleJune** [comment]
`it` args are right. The test case passed when you disabled sanitation on it in your first example on this issue. Notice that it says the step passed. It would have failed too if you didn't disable sanitation on it.

**Comment by loynoir** [comment]
@KyleJune 

> `it` args are right.

Confusing.

Below code

```ts
import { describe, it } from 'https://deno.land/std@0.196.0/testing/bdd.ts'

describe('reproduce', () => {
  it('reproduce', { sanitizeOps: false, sanitizeResources: false }, async () => {
    setTimeout(() => {}, 100)
  })
})
```

Will lead to 

```txt
...
reproduce ...
  reproduce ... ok (0ms)
reproduce ... FAILED (12ms)

 ERRORS 

reproduce => https://deno.land/std@0.196.0/testing/_test_suite.ts:191:10
error: Leaking async ops:
  - 1 async operation to sleep for a duration was started in this test, but never completed. This is often caused by not cancelling a `setTimeout` or `setInterval` call.
To get more details where ops were leaked, run again with --trace-ops flag.

 FAILURES 

reproduce => https://deno.land/std@0.196.0/testing/_test_suite.ts:191:10

FAILED | 0 passed (1 step) | 1 failed (42ms)

error: Test failed
```

Given

- `it` implement using types, which tell user can disable `sanitizeXXX` thru ItArgs options.

So, there is two and only two situation, right?

1. The types is correct, but the implement is wrong.

2. The implement is correct, but the types is wrong.

**Comment by KyleJune** [comment]
It did what you configured it to do. See the test output, it says the test case passed. If you remove those options, both the group and the individual test case would fail.

**Comment by loynoir** [comment]
I got you.

- When `it` `sanitizeOps: true`, `it` FAILED, and `describe` FAILED, and `deno test` `test failed`

- When `it` `sanitizeOps: false`, `it` OK, and `describe` FAILED, and `deno test` `test failed`

The only benefit situation seems to be

```ts
import { describe, it } from "https://deno.land/std@0.197.0/testing/bdd.ts";

describe("reproduce", { sanitizeOps: false, sanitizeResources: false }, () => {
  it("reproduce", { sanitizeOps: true, sanitizeResources: true }, async () => {
    setTimeout(() => {}, 100);
  });

  it("reproduce", async () => {
    setTimeout(() => {}, 100);
  });
});
```

```txt
running 1 test from ./reproduce.ts
reproduce ...
  reproduce ... FAILED (11ms)
  reproduce ... ok (0ms)
reproduce ... FAILED (due to 1 failed step) (13ms)

 ERRORS 

reproduce ... reproduce => https://deno.land/std@0.197.0/testing/_test_suite.ts:323:15
error: Leaking async ops:
  - 1 async operation to sleep for a duration was started in this test, but never completed. This is often caused by not cancelling a `setTimeout` or `setInterval` call.
To get more details where ops were leaked, run again with --trace-ops flag.

 FAILURES 

reproduce ... reproduce => https://deno.land/std@0.197.0/testing/_test_suite.ts:323:15

FAILED | 0 passed (1 step) | 1 failed (1 step) (70ms)

error: Test failed
```

Still think it is a confusing design.

In conclusion, if anyone meet this confusing situation, use

```ts
describe("reproduce", { sanitizeOps: false, sanitizeResources: false }, () => {})
```

**Comment by loynoir** [comment]
No, I still think this is bad design.

The `sanitizeXXX: false` must at top level.

```ts
import { describe, it } from 'https://deno.land/std@0.197.0/testing/bdd.ts'

describe('reproduce', { sanitizeOps: false, sanitizeResources: false }, () => {
  describe('reproduce', () => {
    describe('reproduce', () => {
      it('reproduce', async () => {
        setTimeout(() => {}, 100)
      })
    })
  })
})
```

**Comment by KyleJune** [comment]
It's not bad design. You disable it at the level you want it disabled. The sanitize feature is useful and I think it makes sense for it to be enabled by default unless specifically disabled.

**Comment by loynoir** [comment]
Anyway, I workaround with `Deno.test` like below.

```ts
    const options2 = {
      ignore: ctx.find((x) => x.options.ignore === true)?.options.ignore ?? false,

      sanitizeOps: ctx.findLast((x) => x.options.sanitizeOps !== undefined)?.options.sanitizeOps ?? true,
      sanitizeResources:
        ctx.findLast((x) => x.options.sanitizeResources !== undefined)?.options.sanitizeResources ?? true,
      sanitizeExit: ctx.findLast((x) => x.options.sanitizeExit !== undefined)?.options.sanitizeExit ?? true
    }
```

**Comment by loynoir** [comment]
With workaround

```ts
describe('reproduce', () => {
  describe('reproduce', { sanitizeOps: false, sanitizeResources: false }, () => {
    describe('reproduce', () => {
      it('reproduce', async () => {
        setTimeout(() => {}, 100)
      })
    })
  })
})

describe('reproduce', () => {
  describe('reproduce', () => {
    describe('reproduce', () => {
      it('reproduce', { sanitizeOps: false, sanitizeResources: false }, async () => {
        setTimeout(() => {}, 100)
      })
    })
  })
})
```

**Comment by iuioiua** [comment]
So `sanitizeXXX` options do not do anything for `it()`. Is this correct?

**Comment by KyleJune** [comment]
> So `sanitizeXXX` options do not do anything for `it()`. Is this correct?

The sanitize options do. When not set on `it` or any of it's parent `describe` groupings, the default would be inherited which is true. If you set the sanitize option on `it`, that option would only apply to that individual test case. If you set the sanitize option on `describe`, it will become the default for all test cases nested in it.

The inheritance of these options work exactly the same as it does in `Deno.test` and `t.step` since internally, all bdd does is translate `describe`/`it` calls into `Deno.test` and `t.step` calls.

**Comment by iuioiua** [comment]
Ok, that makes sense. Thank you for the explanation. Perhaps an explanation like that could be added to [the documentation](https://github.com/denoland/deno_std/blob/830d3878ae88c9eb52ef944cc8dd592c8db8a5c8/testing/bdd.ts#L49-L60) to prevent any future confusion. Is that something you'd be happy and willing to do, @KyleJune?

**Comment by KyleJune** [comment]
I think this issue can just be closed. In my original comment I mentioned they work the same. The linked documentation also says that they work the same. The confusion appears to have just been that describe is a test group and test groups have sanitation applied to them just like `Deno.test` which is clearly stated in it's options.

https://github.com/denoland/deno_std/issues/3512#issuecomment-1666814047

**Comment by KyleJune** [comment]
If you think the wording should be changed, it should also be updated for `Deno.TestDefinition`. I just copied the option descriptions from that since the options behave the same for describe/it.

**Comment by iuioiua** [comment]
Ok. Fair points. I agree. I'm closing this for now. I'll look into further elaborating sanitization options in `Deno.TestDefinition`, if needed. Thanks for your help, @KyleJune.

**Comment by kt3k** [comment]
I think this is an issue of CLI (`testing/bdd.ts` doesn't do anything special about sanitization, but only pass settings to `Deno.test` and `t.step`).

I agree this behavior is confusing, but this should be addressed in Deno CLI instead of std. Let's continue discussing in CLI repo https://github.com/denoland/deno/issues/21307
