### ISSUE TITLE
Add std/url with URL utilities

### ISSUE THREAD

**Issue by ry** [denoland/deno_std#3515]
Should have similar functionality to path: parent, basename, ext

but operate on JS native URL objects

**Comment by lino-levan** [comment]
Good to know that my analysis was not completely off-base 😅

**Comment by tr1ckydev** [comment]
`<URL>.toString()` allows itself to be used in std/path.
```ts
import { parse } from "https://deno.land/std/path/mod.ts";

const url = new URL("https://deno.land/std@0.197.0/console/mod.ts");

console.log(parse(url.toString()));
```

**Comment by kt3k** [comment]
@tr1ckydev If the platform is windows, `std/path` doesn't work for urls.
```js
import { join } from "https://deno.land/std/path/win32.ts";
const url = new URL("https://deno.land/std@0.197.0/console/mod.ts");
console.log(join(url.toString(), "foo")); // => https:\deno.land\std@0.197.0\console\mod.ts\foo
```

**Comment by tr1ckydev** [comment]
Ahh, I see. Is `std/url` being currently worked upon or I can work on it and send a pr?

**Comment by kt3k** [comment]
I don't think anybody started working on it. Which APIs are you planning to implement? Could you share the API designs first?

**Comment by tr1ckydev** [comment]
I have tried to keep the API design similar to std/path with only difference being the input for the functions are `string | URL`.
Currently I have implemented `basename`, `dirname`, `extname`, `join`, `normalize`, `parse`, `format`, `sep`.
Only `relative` and `resolve` is pending.

**Comment by lino-levan** [comment]
You should be able to copy most if not all of the code from the `posixX` family of `std/path`. I would make sure to test edgecases though. Does implementing `sep` make any sense for URLs? What about `format`?

IMO, the only useful utilities would be `xname`, `resolve`, and maybe `normalize`. I'm not sure about `parse`. I think we should definitely NOT implement `relative` as we should be encouraging people to use the base `URL` class:

```ts
const url = new URL("../fr", "https://test.com/en-us")
```

As for `join`, as far as I can tell, the only difference between `join` and `resolve` is whether the path has to be absolute or not. For URLs, the path has to be absolute, so I would recommend either changing the behavior of `join` to `resolve` (to keep the name) or potentially just not including `join` at all in favor of `resolve`.

**Comment by tr1ckydev** [comment]
> You should be able to copy most if not all of the code from the posixX family of std/path. I would make sure to test edgecases though.

Yes, I am using posix functions from `std/path`.

> Does implementing sep make any sense for URLs?

Here's something to say. I have implemented `sep` as a function that can break `https://github.com/denoland/deno_std` to `[ "https://github.com", "denoland", "deno_std" ]` and `SEP` is a const of value `"/"`

> What about format?

`format` just takes `Partial<ParsedPath>` as input and joins them.
`parse` parses the url into `ParsedPath`.

> I think we should definitely NOT implement relative as we should be encouraging people to use the base URL class:

Agreed.

> so I would recommend either changing the behavior of join to resolve (to keep the name) or potentially just not including join at all in favor of resolve.

How about `resolve` being an alias for `join` or vice-versa?

**Comment by lino-levan** [comment]
> Here's something to say. I have implemented sep as a function that can break https://github.com/denoland/deno_std to [ "https://github.com", "denoland", "deno_std" ] and SEP is a const of value "/"

Is there a usecase for this? I feel like we should be pretty conservative about what we include in std.

> format just takes Partial<ParsedPath> as input and joins them.
parse parses the url into ParsedPath.

Again, see above.

> How about resolve being an alias for join or vice-versa?

Pretty strongly against this. I think `resolve` is unclear enough already. I think `join` should be fine.

**Comment by tr1ckydev** [comment]
> Is there a usecase for this? I feel like we should be pretty conservative about what we include in std.

Okay, I get it. Then they can be omitted.

> Pretty strongly against this. I think resolve is unclear enough already. I think join should be fine.

Sounds great. I will be keeping join only then.

**Comment by jollytoad** [comment]
I really like the idea of this module, as I often use the posix path fns for this, but having these use the existing path modules (v0.198.0) introduces unnecessary overhead from the windows implementations.

I've proposed a modification of the path modules structure that could alleviate this... https://github.com/denoland/deno_std/discussions/3553
