### ISSUE TITLE
WebSocket: socket.io alternative

### ISSUE THREAD

**Issue by sh7dm** [denoland/deno_std#352]
It'll be nice to have something like SocketIO for deno. Maybe std module or userland repo. I'd like to work on it with somebody's help.

**Comment by marcinkumorek** [comment]
Deno has a core WS implementation so I think it'd be a better idea to create deno dedicated WS library. Unless there is a plan to extend current WS module functionality.

Either way I can lend a hand during the development :)

**Comment by krnik** [comment]
Deno has a core std module WS implementation so I think it's a better idea to create deno dedicated WS library.
Unless there is a plan or need to extend current WS module functionality.

Either way I can lend a hand during the development :)

**Comment by sh7dm** [comment]
@krnik it's awesome! We can start the project after other people say if they need this!

**Comment by bartlomieju** [comment]
This is outside of standard library scope, as pointed by @krnik a dedicated library would be better suited for this issue.

CC @ry I think we can close this one
