### ISSUE TITLE
Log handler setup function is inconsistent

### ISSUE THREAD

**Issue by ross-weir** [denoland/deno_std#3538]
**Is your feature request related to a problem? Please describe.**

When creating logger handlers some of the handler setup functions are `sync` while others are `async`.

For example, I have a function that creates a logger for my modules like so:

```ts
export function createLogger(
  config: ErgomaticConfig,
  name: string,
): Logger {
  const logHandlers = [];
  const level = config.logLevel;
  const fileHandler = new handlers.FileHandler(level, {
    filename: join(logsDir(), "file.log"),
  });

  fileHandler.setup();

  logHandlers.push(
    new handlers.ConsoleHandler(level, {
      formatter,
    }),
    fileHandler,
  );

  return new Logger(name, level, {
    handlers: logHandlers,
  });
}
```

That I was using in the constructor of my modules:

```ts
class Module {
  constructor() {
    this.logger = createLogger(...)
  }
}
```

I decided I wanted to move over to [`RotatingFileHandler`](https://deno.land/std@0.198.0/log/handlers.ts?s=RotatingFileHandler) for log file rotation. My previous setup no longer works because `RotatingFileHandler.setup` is async whereas `FileHandler.setup` is sync, so this requires me to refactor all my classes if I want to use it.

**Describe the solution you'd like**

Make the API consistent for log handlers, either all async or all sync.

IMO there could have been `setup` & `setupSync` like other Deno APIs but this probably can't be changed while preserving backwards compatibility.

Alternatively add a `SyncRotatingFileHandler` that can be used in `sync` contexts

**Comment by ross-weir** [comment]
Looking into this a bit it looks like `RotatingFileHandler.setup` being async might be an oversight, it appears the `log.setup` method was made sync a while ago https://github.com/denoland/deno_std/commit/ebeecacd61b8829f52fc6ae947c76a2d7daeda2e

Additionally all the documentation still has the `setup` function as `async`: https://github.com/denoland/deno_std/blob/159060b15c3f384bb9497b816b877eaf4f97a0d8/log/mod.ts#L67

**Comment by lino-levan** [comment]
Seems like a reasonable change. I'll pick it up.
