### ISSUE TITLE
timingSafeEqual is provided from 2 places

### ISSUE THREAD

**Issue by kt3k** [denoland/deno_std#3541]
ref https://github.com/denoland/deno_std/pull/2503

`timingSafeEqual` is provided from 2 places:
- as a separate function from `crypto/timing_safe_equal.ts`
- as a method of subtle crypto extension from `crypto/crypto.ts`

Do we need to keep both?

**Comment by iuioiua** [comment]
I'd say that it should only be exported from `crypto/timing_safe_equal.ts` as [it doesn't seem apparent that `timingSafeEqual()` will be added to the Web Crypto API](https://github.com/w3c/webcrypto/issues/270).
