### ISSUE TITLE
Module fs is broken. 

### ISSUE THREAD

**Issue by AlvaroBernalG** [denoland/deno_std#358]
Hello good people of Denoland,

The module fs is throwing the following error : 

```shell
deno_std/fs/ensure_link.ts:42:30 - TS2693: 'PathType' only refers to a type, but is being used as a value here.

42 if (destFilePathType !== PathType.file) {
```

The reason why I think nobody realised that the module was failing is because "ensure_link_test.ts" is not imported into "test.ts".

```shell
deno: 0.3.8
v8: 7.4.238
typescript: 3.4.1
```

**Comment by zekth** [comment]
cc @axetroy
