### ISSUE TITLE
rename stripColor to stripAnsi

### ISSUE THREAD

**Issue by sigmaSd** [denoland/deno_std#3580]
In my opinion stripColor gives the wrong impression, there are many ansi sequences that are not colors

**Comment by lino-levan** [comment]
@iuioiua thoughts?

**Comment by iuioiua** [comment]
I agree

**Comment by kt3k** [comment]
How about `stripAnsiCode`?

**Comment by iuioiua** [comment]
> How about `stripAnsiCode`?

That sounds good too 👍🏾
