### ISSUE TITLE
OS-normalized EOL

### ISSUE THREAD

**Issue by Vandivier** [denoland/deno_std#3583]
In Node we have [os.EOL](https://nodejs.org/api/os.html#os_os_eol) which abstracts the OS.

In Deno we have [std/fs/eol](https://deno.land/std/fs/eol.ts) which is an os-invariant enumeration. The [docs for writeFile](https://deno.land/typedoc/index.html#writefile) and similar just use denormalized `\n`.

Is this a case where we can prefer the Node pattern over the Go pattern, or is there some other recommended way to do this sort of thing? I'm simply trying to write a file with line breaks.

**Comment by kt3k** [comment]
Let's have Node.js `os.EOL` equivalent in std.

Does anyone have any idea about where & how this would be exposed?

**Comment by kt3k** [comment]
Maybe something like:

```ts
type EOL = "\n" | "\r\n";
export const EOL = isWindows ? "\r\n" | "\n";
```

This is going to be a breaking change to `std/fs`, but I guess this is what most users expect.

**Comment by iuioiua** [comment]
@ayame113, would you know how to make the above snippet strongly typed?

**Comment by ayame113** [comment]
> @ayame113, would you know how to make the above snippet strongly typed?

I feel that specifying `as const` is sufficient here. Or are you thinking of stronger typing?

```ts
export const LF = "\n" as const;
export const CRLF = "\r\n" as const;
export const EOL = isWindows ? CRLF : LF;
```

**Comment by iuioiua** [comment]
Yep, actually, I think `as const` is best.

**Comment by iuioiua** [comment]
Implementing this would clash with the current `EOL` enum. My unorthodox suggestion would be to make a breaking change by removing the `EOL` enum and replacing it with the above implementation without a deprecation period. The transition for users would be so straightforward that it might be right to do it like this once. WDYT, @kt3k?

**Comment by kt3k** [comment]
Can we still do deprecation first? @iuioiua 

Steps:
- Deprecate existing EOL
- Wait 3 std minor versions (~3 weeks)
- Remove existing EOL
- Add new EOL
