### ISSUE TITLE
streams: add APIs from stream-consumers

### ISSUE THREAD

**Issue by kt3k** [denoland/deno_std#3587]
ref: https://github.com/jimmywarting/stream-consumers

These 4 APIs look very handy for handling readable streams. How about adding these to `std/streams`?

```js
import { arrayBuffer, blob, json, text } from 'stream-consumers'
```

**Comment by 0f-0b** [comment]
I don't think these functions provide much value. One can already write, for example, `new Response(readable).json()`, as [noted in the readme](https://github.com/jimmywarting/stream-consumers#alternative-native-methods). An async iterable or a Node.js `Readable` can first be converted with `ReadableStream.from`.

**Comment by kt3k** [comment]
> new Response(readable).json(), as [noted in the readme](https://github.com/jimmywarting/stream-consumers#alternative-native-methods).

That works, but as described in that readme, it feels still 'hack' and 'abuse' especially when you are not working on http server or client
