### ISSUE TITLE
Clean up platform specific APIs of `path` module

### ISSUE THREAD

**Issue by kt3k** [denoland/deno_std#3600]
We currently expose platform specific APIs like the below:

```js
import { posix, win32 } from "https://deno.land/std@0.200.0/path/mod.ts";
```

or
```js
import * as win32 from "https://deno.land/std@0.200.0/path/win32.ts";
import * as posix from "https://deno.land/std@0.200.0/path/posix.ts";
```

I think this has 2 problems:
- There's no way to import single implementation of platform specific API
- 'posix' and 'win32' keywords don't match the way we usually specify the platform name (i.e. it doesn't match to `Deno.build.os`)

One way to solve this is to implement #687

part of #3489

**Comment by lino-levan** [comment]
> 'posix' and 'win32' keywords don't match the way we usually specify the platform name

I'm in favor of renaming `win32.ts`->`windows.ts`. It's unclear to me what `posix.ts` could be renamed to while keeping it's semantic meaning.

> One way to solve this is to implement https://github.com/denoland/deno_std/issues/687

As I've mentioned before, I'm not quite sure how to go about implementing this. There are some APIs (`resolve` and friends) which don't fit well into adding an optional argument. Breaking changes would almost certainly be required.

**Comment by kt3k** [comment]
> There are some APIs (resolve and friends) which don't fit well into adding an optional argument.

Something like the below seems working. Does this help designing it?:

```ts
type OS = "windows" | "linux" | "darwin" | "freebsd";

function resolve(...args: string[]): string;
function resolve(...args: [...string[], { os: OS }]): string;
function resolve(...args: any[]): string {
    //
    return "...";
}

resolve("a", "b");
resolve("a", "b", { os: "windows" });
```

**Comment by lino-levan** [comment]
Ah, fair enough, I never really got the hang of overloading typescript functions :sweat_smile:. Seems like a reasonable and non-breaking change. I'll pick this up later today.

**Comment by jollytoad** [comment]
I made a suggestion for this here... https://github.com/denoland/deno_std/discussions/3553

Adding an os option is overkill and unnecessary.

**Comment by kt3k** [comment]
#3553 might be fine too. I'm curious what people think about these options.

**Comment by lino-levan** [comment]
Either way makes sense to me. The complexity is about the same either way.

**Comment by kt3k** [comment]
I now feel #3553 is better as it allows more granular imports. With os-argument proposal, platform-specific single operation is not importable. Also dynamic nature of os-argument doesn't look useful to me (I can't think of the case where dynamic os argument is absolutely necessary).

Also Os-argument proposal has tricky typing with `join` and `resolve` methods (See [this](https://github.com/denoland/deno_std/pull/3613/files#diff-95bbb1c6a6bdfa53b1a62e9abdfb612a7d1391b0af665c89ceb28eaf60818775R11-R14) for example). On the other hand, #3553 doesn't require any typing change and looks straightforward.

I'll work on implementing #3553

**Comment by jollytoad** [comment]
@kt3k I had a bash at this, let me push and share the branch so far, it's not complete, but after doing this I have concerns.

**Comment by jollytoad** [comment]
I'd not pushed this sooner as I had some concerns after doing it...

1. My main motivation for this split was so you could just remap the path modules to a specific OS using an import map.

For example:
```json
"imports": {
   "https://deno.land/std@0.xxx.0/path/": "https://deno.land/std@0.xxx.0/path/posix/"
}
```

I feel that remapping onto a subpath may be problematic, but I've not had chance to test this idea yet, maybe it'll be fine, I'm not sure yet!

Maybe if the sub-path is a problem, using a sibling structure would be better, eg: `".../path/": ".../path_posix/"`?

2. Despite feeling this is technically a better way to approach this problem, the overall outcome makes me feel somewhat uncomfortable, I can't quite put my finger on it.

3. glob doesn't fit neatly into the pattern as it already had an OS switch option ... but i've attempted to refactor this too.

**Comment by jollytoad** [comment]
Ah, I remember, my main concern about remapping... if you remap `/path/` to `/path/posix/` for example, then anything that uses `/path/posix/` directly may get mapped to `/path/posix/posix/`, which isn't ideal.

How would you feel about top level `/path_posix` & `/path_windows` & an internal dir for common modules (`/_internal/path` or `/_path_common` for example?)

**Comment by jollytoad** [comment]
I've raised an alternative PR #3650 to explore this option ^

**Comment by kt3k** [comment]
@jollytoad 
> I feel that remapping onto a subpath may be problematic

If there are overlapping import map keys, the most specific one has the effect (according to this https://github.com/WICG/import-maps/pull/113 )

I think the below should work.

```json
"imports": {
   "https://deno.land/std@0.xxx.0/path/posix/": "https://deno.land/std@0.xxx.0/path/posix/"
   "https://deno.land/std@0.xxx.0/path/windows/": "https://deno.land/std@0.xxx.0/path/windows/"
   "https://deno.land/std@0.xxx.0/path/": "https://deno.land/std@0.xxx.0/path/posix/"
}
```

**Comment by kt3k** [comment]
> glob doesn't fit neatly into the pattern as it already had an OS switch option ... but i've attempted to refactor this too. TBH, glob feels a little out of place to me being in path, it's a lot more complex than other fns, and provides multiple fns from it's module, feels like it should probably live in a top-level module of its own.

This sounds worth considering. It provides 4 APIs: `globToRegExp`, `isGlob`, `normalizeGlob`, `joinGlobs`. This might be better as top-level module.

Note: Python std lib has [glob](https://docs.python.org/3/library/glob.html) module independent of [os.path](https://docs.python.org/3/library/os.path.html). In Rust, [glob](https://docs.rs/glob/latest/glob/) is an independent crate. On the other hand, [Glob](https://pkg.go.dev/path/filepath#Glob) is a part of `path/filepath` in Go std lib.

**Comment by lino-levan** [comment]
> This sounds worth considering. It provides 4 APIs: `globToRegExp`, `isGlob`, `normalizeGlob`, `joinGlobs`. This might be better as top-level module.

I could also see it as part of the `path` module but split up into 4 files.

**Comment by kt3k** [comment]
I now have a question about `toNamespacedPath()`. This API is only meaningful on windows. I wonder if it's meaningful to provide `path/to_namespaced_path.ts` (platform independent version) and `path/posix/to_namespaced_path.ts`. What if we only provide `path/windows/to_namespaced_path.ts`?

**Comment by jollytoad** [comment]
I think the API should remain consistent between `/path`, `/path/posix`, & `/path/windows`, regardless of whether it a no-op in posix. Although tbh, i'm not sure under what circumstances you'd ever use `toNamespacedPath()` anyway ... it is something that should be used when writing cross-platform? I kind of defeats the point of the cross-platform `/path` if there is this one special case.

**Comment by lino-levan** [comment]
I'd love to get usage numbers on it, though I suspect that this would be impossible. I have never seen its use in the wild. I'd borderline be in favor of dropping it entirely.

**Comment by lino-levan** [comment]
With https://github.com/denoland/deno_std/pull/3649 landing, is there anything keeping this issue open? Just `toNamespacedPath`?

**Comment by kt3k** [comment]
@lino-levan I think we should also split glob related 4 APIs into their own files as you pointed. If you have time, could you work on that?

> Just `toNamespacedPath`?

I personally think `toNamespacedPath` is fine as the current state. Do you have any opinion on it?

**Comment by lino-levan** [comment]
> If you have time, could you work on that?

Sure, I'll open a PR.

> I personally think `toNamespacedPath` is fine as the current state. Do you have any opinion on it?

I've looked into why we've included it in the first place and it seems to be just to mirror node's `path` module. I think it's fine for that purpose.

**Comment by iuioiua** [comment]
What is the current status of this?

**Comment by lino-levan** [comment]
I'll go ahead and split up glob now. Sorry for the wait!
