### ISSUE TITLE
Clean up `front_matter` module

### ISSUE THREAD

**Issue by kt3k** [denoland/deno_std#3601]
`front_matter` module doesn't strictly follow the single-export pattern. We should clean it up and make it follow single-pattern strictly before stabilizing.

part of #3489

**Comment by JakeAve** [comment]
When you say single-export pattern, do you mean add the any, json, toml and yaml exports to the mod.ts?

```
export * as any from './any.ts'
export * as json from './json.ts'
export * as toml from './toml.ts'
export * as yaml from './yaml.ts'
```

**Comment by kt3k** [comment]
Single-export pattern means every API is implemented in its own file. In the case of `front_matter`, there are APIs like `createExtractor` and `test`, which are directly implemented in `mod.ts`, that breaks the pattern. We'd like to move them into its own file.

**Comment by kt3k** [comment]
I think we should also do the below to make the module comformant to single export pattern:
- deprecate default export from `any.ts`, `json.ts`, `yaml.ts`, and `toml.ts`
- deprecate `test` export from `any.ts`, `json.ts`, `yaml.ts`, and `toml.ts`
- deprecate `Format` type and use union type instead for format params
