### ISSUE TITLE
`encoding/hex` represents hexes as `Uint8Array`s

### ISSUE THREAD

**Issue by tjjfvi** [denoland/deno_std#3605]
The vast majority of the time I'm using hex encoding is because I need some binary data to be transformed to/from a string.

Currently, [`encoding/hex`](https://deno.land/std@0.200.0/encoding/hex.ts) has the following signatures:
```ts
function encode(src: Uint8Array): Uint8Array
function decode(src: Uint8Array): Uint8Array
```

If one needs to work with hex strings, thus, one needs to write:
```ts
hex = new TextDecoder().decode(encode(bytes))
bytes = decode(new TextEncoder().encode(hex))
```
This is rather verbose and inefficient.

Further more, this is inconsistent with [the](https://deno.land/std@0.200.0/encoding/ascii85.ts) [rest](https://deno.land/std@0.200.0/encoding/base32.ts) [of](https://deno.land/std@0.200.0/encoding/base58.ts) [the](https://deno.land/std@0.200.0/encoding/base64.ts) [modules](https://deno.land/std@0.200.0/encoding/base64url.ts) in `encoding/`.

(Given that hex is the only one that says it is a port of a Go equivalent, I suspect this is the reason for this discrepancy.)

I have consequently been using [a library](https://deno.land/x/hexes@v0.1.0) I published for hex encoding/decoding, but it would be great if these could be incorporated into std.

**Comment by itsajay1029** [comment]
I'd like to work on it if you can highlight the issue and how do I go around looking for the solution @tjjfvi

**Comment by tjjfvi** [comment]
@itsajay1029 The main question is whether to:
- introduce a breaking change to `encoding/hex` to change `encode`/`decode` to use `string`s
- add separate `encodeStr`/`decodeStr` methods

Which can only really be answered by the maintainers. (From #3617, it seems like their inclination would perhaps be the former.)

(As far as implementation goes, my implementations in [`hexes`](https://deno.land/x/hexes@v0.1.0) could be used as a starting point; a while back, a benchmarked a number of different implementations, and found those to be the fastest.)

**Comment by lino-levan** [comment]
@kt3k How do you think we should go about doing this?

**Comment by kt3k** [comment]
I'm in favor of the breaking change in this case.

As pointed by @tjjfvi, only `encoding/hex` seems deviating in types from other encoders and decoders. That feels confusing.

**Comment by lino-levan** [comment]
How should these breaking changes be done? Deprecation and then a breaking change after it would be removed?

**Comment by kt3k** [comment]
Ah, good point.

> Deprecation and then a breaking change after it would be removed?

I think that works

**Comment by kt3k** [comment]
> Perhaps as a broader part of https://github.com/denoland/deno_std/issues/3617, the encoding/foo.ts modules could be changed to export encodeFoo and decodeFoo, rather than just encode and decode. This would mean that encodeHex and decodeHex could be added to use strings whilst the old encode and decode methods are deprecated.

I'm open to that. I'm interested in the community's opinions/preferences

**Comment by lino-levan** [comment]
> This would mean that encodeHex and decodeHex could be added to use strings whilst the old encode and decode methods are deprecated.

I'm in favor of renaming `encode` and `decode` to something more specific. I think that makes a lot of sense, especially with re-exporting being a common pattern:

When importing from `deps.ts`, what does `encode` do? `encodeHex` would be a lot more clear.

**Comment by itsajay1029** [comment]
> To deprecate and then remove, one would ideally have an alternate name for the new functions, so that the new ones can be transitioned to as soon as the old ones are deprecated.
> 
> Perhaps as a broader part of #3617, the `encoding/foo.ts` modules could be changed to export `encodeFoo` and `decodeFoo`, rather than just `encode` and `decode`. This would mean that `encodeHex` and `decodeHex` could be added to use `string`s whilst the old `encode` and `decode` methods are deprecated.
> 
> I think this change would be beneficial in general, as it allows importing from multiple of the encoding libraries simultaneously, without renaming / using a namespace import (neither of which can be done with auto-import). Additionally, it would allow creating `encoding/mod.ts`.

Shall I try implementing this @tjjfvi ?

**Comment by tjjfvi** [comment]
@itsajay1029 If you'd like 🤷 (though the maintainers haven't confirmed that path yet)
