### ISSUE TITLE
`DelimiterStream` regression in 0.201.0, drops the first character of certain lines

### ISSUE THREAD

**Issue by johnspurlock** [denoland/deno_std#3609]
DelimiterStream drops the first character of certain lines starting in 0.201.0 - found due to data corruption in a production system, so I hope the Deno folks can fix this quickly before other Deno users' data is silently corrupted.

To repro, run the following minimal repro deno script, which compares the lines from v200 vs v201 of DelimiterStream.

Nothing should be printed, every line should be exactly the same in both versions.  But note that a few of the lines are missing the first char in v201, and it's not always deterministic between runs! 

Looks like this class was refactored in 201, maybe this can be included as a test going forward?

```ts
import { DelimiterStream as DelimiterStream200 } from 'https://deno.land/std@0.200.0/streams/delimiter_stream.ts';
import { DelimiterStream as DelimiterStream201 } from 'https://deno.land/std@0.201.0/streams/delimiter_stream.ts';

// collect lines from a large-ish text file using two different versions of DelimiterStream
const results: Record<string, string[]> = {};
const decoder = new TextDecoder();
const newline = new Uint8Array([ 10 ]);
for (const [ name, DelimiterStream ] of Object.entries({ DelimiterStream200, DelimiterStream201 })) {
    results[name] = [];
    const stream = (await fetch('https://raw.githubusercontent.com/publicsuffix/list/master/public_suffix_list.dat')).body!;
    const allChunks = stream.pipeThrough(new DelimiterStream(newline));
    for await (const chunk of allChunks) {
        const line = decoder.decode(chunk);
        results[name].push(line);
    }
}

// notice that 201 drops the first char of some lines, also not deterministic!
results.DelimiterStream200.forEach((line200, i) => {
    const line201 = results.DelimiterStream201[i];
    if (line200 !== line201) console.log(`line ${i + 1}: ${line200} -> ${line201}`);
});
```

- OS: MacOS Ventura 13.5.1 (22G90)
- deno version: deno 1.36.4 (release, aarch64-apple-darwin)
- std version: 0.201.0

**Comment by aapoalas** [comment]
Thank you for the report and reproduction, I'll take a look!
