### ISSUE TITLE
Clean up `encoding` module, part 2

### ISSUE THREAD

**Issue by kt3k** [denoland/deno_std#3617]
`encoding` module has the following encodings and corresponding decode and encode methods:

- ascii85
  - encode: Uint8Array -> string
  - decode: string -> Uint8Array
- base32
  - encode: Uint8Array -> string
  - decode: string -> Uint8Array
- base58
  - encode: ArrayBuffer | string -> string
  - decode: string -> Uint8Array
- base64
  - encode: ArrayBuffer | string -> string
  - decode: string -> Uint8Array
- base64url
  - encode: ArrayBuffer | string -> string
  - decode: string -> Uint8Array
- hex
  - encode: Uint8Array -> Uint8Array
  - decode: Uint8Array -> Uint8Array
- varint
  - encode: bigint | number -> [Uint8Array, number]
  - decode: Uint8Array -> [bigint, number]

Encodings except `varint` are similar in typing, but there are discrepancies (The case of `hex` is pointed in #3605). I think these 6 encodings should have the same typings, for example `encode: Uint8Array | ArrayBuffer | string -> string; decode: string -> Uint8Array`

part of #3489

**Comment by lino-levan** [comment]
@kt3k is this completed?

**Comment by kt3k** [comment]
@lino-levan Yeah, let's close this. Thanks for your contributions!
