### ISSUE TITLE
Proposal: deprecate `encode`/`decode`, instead introduce `encodeFoo/decodeFoo`

### ISSUE THREAD

**Issue by kt3k** [denoland/deno_std#3643]
Currently `encode` and `decode` methods in `std/encoding` have incompatible signatures:

For `encode`, there're 3 types: `Uint8Array -> Uint8Array` `Uint8Array -> string` `ArrayBuffer | string -> string`

For `decode`, there're 2 types: `string -> Uint8Array` `Uint8Array -> Uint8Array`

I think these should be aligned to the same type (The most possible candidate for that type would be `ArrayBuffer | Uint8Array | string -> string` for `encode` and `string -> Uint8Array` for `decode` in my view).

This transition can't be done without breaking changes. To avoid the confusion, I'd suggest we should deprecate all existing `encode`/`decode`, and add `encodeFoo`/`decodeFoo` (ex. `encodeBase64`/`decodeBase64`) instead.

cc @bartlomieju @ry @piscisaureus @lucacasonato

related #3605 #3617 #3489

**Comment by bartlomieju** [comment]
That makes sense to me 👍 unifying these types is a good idea

**Comment by lino-levan** [comment]
I'll open a PR. I'm going to avoid doing `encodeHex` in the PR because it requires a decent rewrite that deserves a PR to itself.

**Comment by lino-levan** [comment]
I'm going to submit this PR in an hour, but there are some APIs we probably want to revisit within encoding. I'll make a note of it in the pull request.
