### ISSUE TITLE
[http/server_sent_event] Missing ServerSentEventStreamTarget ReadableStream "open" event listener

### ISSUE THREAD

**Issue by adamatat** [denoland/deno_std#3645]
**Describe the bug**

There's a `close` event for when the readableStream closes, so it's strange and inconsistent that there isn't a corresponding `open` or `start` stream event.

Furthermore, `this.#bodyInit` is declared as a private property so the class can't be extended.  It has to be entirely duplicated to be usable.

** Context ***

I want to be able to send events to the client immediately after they connect, but it's not possible in a clean way due to the current limitations.

**Environment**

- std version: 0.195.0

**Comment by iuioiua** [comment]
Hi @adamatat, `ServerSentEvent()` has been deprecated in favour of `ServerSentEventStream()`. See [here](https://deno.land/std/http/mod.ts?s=ServerSentEventStream). Are you able to give that a try and let us know how it goes?

**Comment by iuioiua** [comment]
Closing this as `ServerSentEvent()` was deprecated and is now removed. Please use `ServerSentEventStream()` and open an issue if you run into any problems.
