### ISSUE TITLE
Discussion: enhance strings module

### ISSUE THREAD

**Issue by axetroy** [denoland/deno_std#367]
This issue discusses what modules should be included in strings.

Is it necessary to add some common methods to the strings module?

These methods may also be referenced by other std modules.

It's not copying similar `lodash`

It is a supplement to `ECMAScript` that makes up for the lack of manipulation of strings. Methods already in the specification should not add to the `strings` module.

- [ ] isString()
- [ ] camelCase()
- [ ] capitalize()
- [ ] escape()
      ...

**Comment by zekth** [comment]
Type checking like `isString()` is already in the polyfill of node : https://github.com/denolib/node/blob/master/util/main.ts

`escape()` is almost deprecated now and is replaced by `encodeURI()`

But i like the idea of all the casing manipulations:
- snakeCase()
- pascalCase()
- camelCase()
- kebabCase()

**Comment by axetroy** [comment]
@zekth

To be honest, I am not very optimistic about `node-polyfill`

It won't let the `node` modules run on `deno` and it take a lot of times.

**Comment by zekth** [comment]
Mixed feelings about node-polyfill

About casing just thoughts about something like:
- `validateCasing(value:string, type: caseType)`

**Comment by dshubhadeep** [comment]
@zekth Hi, I'm interested on working on the string functions. Please let me know which functions need to be implemented.

**Comment by zekth** [comment]
> @zekth Hi, I'm interested on working on the string functions. Please let me know which functions need to be implemented.

As discussed with Ryan it may be in another module. So i've started this one: https://github.com/zekth/deno-case-style

Maybe a word counting / parser could be a good repo addition. I don't know what @kevinkassimo thinks about adding them to denolib or not.

**Comment by dshubhadeep** [comment]
@zekth I can work on the word counter function, if you'd like

**Comment by dshubhadeep** [comment]
@zekth I have submitted a pull request. Please let me know if there are any changes to be made.

**Comment by mapleeit** [comment]
Purposing adding `truncate` for strings.

API may be like (coping from `lodash`): 

```js
truncate ([string=''], [options={}])
```

- `[string=''] (string)`: The string to truncate.
- `[options={}] (Object)`: The options object.
- `[options.length=30] (number)`: The maximum string length.
- `[options.omission='...'] (string)`: The string to indicate text is omitted.
- `[options.separator] (RegExp|string)`: The separator pattern to truncate to.
