### ISSUE TITLE
Deno.KV - Modernized TypeScript randomULID() Generator - Smaller and Optimized

### ISSUE THREAD

**Issue by suchislife801** [denoland/deno_std#3675]
I've finally finished these 2 scripts and they turned out so small I would like to propose them for Deno.KV.

 - Modernized ULID (Universally Unique Lexicographically Sortable Identifier) generator in Javascript.
 - Reduced size compared to examples on GitHub.
 - Code includes functions for encoding BigInt as Base32, decoding timestamps, and generating ULIDs.

As you can see, Monotonic fills the Set almost twice as fast from sheer uniqueness.

### 4 working examples listed in the Stack Exchange link below:

[Modernized Javascript randomULID() Generator - Smaller and Optimized](https://codereview.stackexchange.com/questions/287142/modernized-javascript-randomulid-generator-smaller-and-optimized)

For me, I was able to get to 10,000,000 iterations before Deno blows up up but still, NO collisions. In the post, I have set the collision test to 5,000,000 so as to not slow down the browser for anyone who clicks run for more than 10 seconds.

**Comment by kt3k** [comment]
@suchislife801 
We significantly reduced the API surface when adopting ULID to deno_std. See https://github.com/denoland/deno_std/pull/3582

Our version is much simpler than the reference implementation at https://github.com/ulid/javascript

Also we use `crypto.getRandomValues()` by default, and doesn't allow replacement. Cryptographic concern shouldn't apply to our implementation https://github.com/denoland/deno_std/blob/28840333898d71aaca58c44ef43506dfbde85157/ulid/_util.ts#L34

**Comment by suchislife801** [comment]
You version is not much simpler than what I've just posted. Not at all. I have read through it. You're using imports on a piece of code that needs 4 functions to run. Not to mention factory functions that create functions that need to import utilities that etc etc etc... Perhaps we do not share the same concept of simplicity and least moving parts.

**Comment by lino-levan** [comment]
The issue with not using the factory function in the case of us having a factory function is that we need to test the implementation. It's pretty hard to test with stubbing the randomness of the implementation. If you could show a proper way to test your proposed implementation that was simpler I'd love to take a look.

**Comment by suchislife801** [comment]
I guess I'm not following. **There is a collision test right below the same code I've just posted.** You can literally copy and pasted the code I've posted into a TypeScript file and start at 5_000_000 iterations.

**Comment by lino-levan** [comment]
Let's try to be respectful here. When I'm talking about testing, I am referring to unit testing. The code you posted, while cool, is definitely closer to "fuzzing" than "testing". Properly testing things like MULID requires more than just fuzzing, unfortunately. That being said, any reasonably correct ULID implementation will essentially never get a collision, so I see the value in testing that. If you would like, you could PR your collision test file into the `ulid` module.

**Comment by suchislife801** [comment]
Imma go ahead and pass. I'll create a repo, It's GitHub after all. Someone will eventually run into it which could paradoxically be faster.

**Comment by lino-levan** [comment]
Sure, thanks for opening an issue. I'd love to chat more if you are interested.

**Comment by suchislife801** [comment]
I am interested in deleting this entire issue but that is also not possible.
