### ISSUE TITLE
Potential license issue

### ISSUE THREAD

**Issue by proehlen** [denoland/deno_std#3684]
Hi, I notice that many, if not most, of the files in your project contain " All rights reserved. MIT license." in the header.

https://github.com/search?q=repo%3Adenoland%2Fdeno_std+%22All+rights+reserved.+MIT+license.%22&type=code

It's my understanding that the use of the phrase "All rights reserved" is, at best, redundant or, at worst, contradictory with the MIT license:

https://opensource.stackexchange.com/a/4403

https://g.co/bard/share/3e4c8688afbf

IANAL but the contradiction may induce reluctance to use your code while the license is seemingly ambiguous. Regardless of whether you decide to change it or not, thanks for considering this issue.

**Comment by ry** [comment]
The phrase “All rights reserved” traditionally signifies that we retain all rights provided under copyright law. This doesn’t negate or contradict the permissions granted by the MIT license. It emphasizes that, even as we grant permissions through the MIT license, our copyright is retained. In particular, we want the copyright header to persist in any forks or derivatives. Our primary goal is to ensure clarity and make the community feel comfortable using our code.
