### ISSUE TITLE
`serveDir` links are incorrect when `urlRoot` is set.

### ISSUE THREAD

**Issue by jespertheend** [denoland/deno_std#3690]
**Describe the bug**
The `urlRoot` option of `serveDir` doesn't seem to adjust the links when browsing folders using `showDirListing: true`.

**Steps to Reproduce**

1. Create `foo.js`:
```js
import { serveDir } from "https://deno.land/std@0.203.0/http/file_server.ts";

Deno.serve({ port: 8080 }, async (request, connInfo) => {
	return await serveDir(request, {
		showDirListing: true,
		urlRoot: "prefix",
	})
});
```
2. Run `deno run -A foo.js` from a folder with some files in it
3. Visit http://localhost:8080/prefix/
4. Click one of the links

**Expected behavior**

The clicked is either relative or includes the `/prefix/` in the url.

**Environment**

- OS: `macOS 14.0 (23A344)`
- deno version: `1.37.1`
- std version: `0.203.0`

**Comment by lino-levan** [comment]
Hm, good callout. Thanks for reporting.
