### ISSUE TITLE
proposal: replace `ServerSentEvent()` with `ServerSentEventStream()`

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno_std#3693]
**Is your feature request related to a problem? Please describe.**

I am suggesting we replace the `http/server_sent_events.ts` implementation to be a simple `TransformStream` that performs the encoding of SSEs to strings.

**Describe the solution you'd like**

Here is an example I just threw together with @kt3k about how this should work:

```ts
const sse_stream = new SSEStream();

sse_stream.writable.getWriter().write({
  data: "Hello World",
  id: "",
  delay: 213,
});

sse_stream.readable.getReader().read();
// data: "Hello World"\r\n
// id: ""
// delay: 213\r\n\r\n

const stream = new ReadableStream({
  start(controller) {
    setInterval(() => {
      controller.enqueue({ data: "Hello World", id: "", delay: 213 });
    }, 1000);
  },
});

const body = stream.pipeThrough(new SSEStream()).pipeThrough(new TextDecoderStream())
new Response(body, { headers: { "Content-Type": "text/event-stream" } })
```

**Comment by iuioiua** [comment]
@kt3k and I talked about this and love the idea. We want to deprecate the current `ServerSentEvent()` once this is implemented. PRs are welcome!

**Comment by jollytoad** [comment]
If it's any use, I wrote a fn a while ago to format an SSE from a similar plain object... https://github.com/jollytoad/deno_http_fns/blob/main/_experimental/sse.ts

**Comment by jollytoad** [comment]
btw, did you mean `retry` rather than `delay` in the example given? ... https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events#retry

**Comment by iuioiua** [comment]
Thanks! I've already started work on this, and most of what you suggest lines up! Thank you.
