### ISSUE TITLE
`[csv/csv_parse_stream] cancel CsvParseStream during iteration does not leak file` is flaky

### ISSUE THREAD

**Issue by kt3k** [denoland/deno_std#3694]
https://github.com/denoland/deno_std/actions/runs/6479639086/job/17593573910

**Comment by kt3k** [comment]
The test case added in this PR is flaky now https://github.com/denoland/deno_std/pull/2401

**Comment by iuioiua** [comment]
Any ideas on how this could be fixed, @crowlKats?
