### ISSUE TITLE
SemVer: Method returning boolean for validation

### ISSUE THREAD

**Issue by timonson** [denoland/deno_std#3707]
I used to use `semver.valid` to check if a string is a valid semver. Since the deprecation of the old library, is there a similar method which returns a boolean? I prefer Booleans compared to TypeErrors, what `semver.parse` throws.

If not, can we add one?

Thank you!

**Comment by lino-levan** [comment]
This seems logical to me. [`URL.canParse`](https://developer.mozilla.org/en-US/docs/Web/API/URL/canParse_static) is precedent that this sort of API makes sense.
