### ISSUE TITLE
suggestion: automatically delete branches once PR is merged

### ISSUE THREAD

**Issue by iuioiua** [denoland/deno_std#3714]
This helps keep the repo clean. @kt3k, please feel free to close this once actioned or if you disagree.

**Comment by kt3k** [comment]
Set the automatic deletion true in this repo. Thanks for the suggestion

<img width="638" alt="Screenshot 2023-10-24 at 12 46 51" src="https://github.com/denoland/deno_std/assets/613956/5e11b1f5-794f-45ec-accb-574ac54983ec">
