### ISSUE TITLE
Add accumulator buffer to /std/bytes

### ISSUE THREAD

**Issue by nhrones** [denoland/deno_std#3729]
Add accumulator buffer to std/bytes/
https://github.com/nhrones/msgPack/blob/main/accumulator.ts

Example usage:
I've replaced /std/bytes/concat with Accumulator in /std/msgpack/encode.ts
https://github.com/nhrones/msgPack/blob/main/encode.ts
The result was a significant increase in readability and performance.

I have several codecs where this accumulator is used: KvKeyCodec, KvValueCodec ... 
I'd love to see it as part of Deno std/bytes/.

**Comment by iuioiua** [comment]
I’ve taken a quick look at the implementation and I don’t believe it is more readable. The `concat()` is quite readable and performant already. I don’t think it is a suitable replacement. Either way, are you able to provide benchmark code and results?

**Comment by nhrones** [comment]
Yes it must have been a QUICK look.  I'm sorry you couldn't recognize the benefits.
Works great for me, just wanted to share.  I won't bother you any more.

**Comment by nhrones** [comment]
@iuioiua  By the way, The proposal was as an addition, not a replacement for the inefficient double loop concat.

**Comment by nhrones** [comment]
FYI
Accumulator test results -- Encoding a large object with 100,000 properties

Using original Deno /std/msgpack/encoder.ts/ with a repaired /std/bytes/concat/ --
concat -- final concat buffer size 1457439, number of Uint8Arrays 300001
concat encoder took 592 ms

Using refactored /std/msgpack/encoder.ts/ that's using my Accumulator.ts
accumulator - final accumulator size: 1474560, Encoded result size 1457439
accumulator encoder took 409 ms

I think we could call that a significant performance improvement! But then what do I know.  
Plus there's an array of 300,001 Uint8Array objects that we didn't have to instantiate and GC.
I wouldn't think Uint8Array objects are light weight!

**Comment by nhrones** [comment]
This proposal was my very first!  And will obviously by my last.  It's been quite embarrassing for me.
