### ISSUE TITLE
Zlib module

### ISSUE THREAD

**Issue by KluVerKamp** [denoland/deno_std#376]
Is there any plans to create a module to zip/unzip files and folder?

**Comment by axetroy** [comment]
`deno_std` refers to [golang std](https://golang.org/pkg/archive/) to achieve.

So this should be part of the plan.

- [ ] deno_std/archive
  - [ ] tar
  - [ ] zip

If you or someone else is interested, welcome PR.

**Comment by arcatdmz** [comment]
I have ported a simple JavaScript-based `tar` archiver to Deno during my effort to implement a web server.
https://github.com/arcatdmz/danoweb/blob/71bec75f7baea33fc320b09171a7bde4763037b6/server/tar.ts

There are multiple variations in `tar` format and it currently only supports USTAR but the other two popular formats (PAX and GNU). Still, could it be a small starting point? I could implement a bit more (e.g., Reader-based deflating method, GNU format support) and send a PR.

**Comment by barthuijgen** [comment]
For my project I need to parse a gzip compressed http response, but sadly I found absolutely no way to complete this task in Deno even when allowing hacky solutions, zip is not implemented and I could not spawn a child process to use a external program either.

The nodejs method would be `zlib.createGunzip()`

Seeing how you wish to port the go std, this would be the one: https://github.com/golang/go/tree/master/src/archive/zip

**Comment by arcatdmz** [comment]
I was working on the port of `pako` library which allows binary equal output as the famous `zlib` implementations, while it is still on its way.

Probably I can have some time to do the rest (provide an API on top of the `pako` port) by the end of this month, but if you are in a hurry, you can find a working prototype here in my fork:
https://github.com/arcatdmz/deno_std/blob/feat-archive-zip/archive/pako
