### ISSUE TITLE
Why is the `permissions` module deprecated?

### ISSUE THREAD

**Issue by RuiNtD** [denoland/deno_std#3776]
Hello. I use the grantOrThrow method from the permissions module in all my projects to streamline permission requesting. Why is this module being deprecated in favor of just using Deno.permissions, which doesn’t even have an equivalent method?

This isn’t very clean code:
```ts
if ((await Deno.permissions.request({ name: "read", path })).state !== "granted")
  throw "permission required";
if ((await Deno.permissions.request({ name: "write", path })).state !== "granted")
  throw "i literally need that permission to function";
```
...as opposed to using grantOrThrow:
```ts
await grantOrThrow({ name: "read", path }, { name: "write", path });
```

_Originally posted by @RuiNtD in https://github.com/denoland/deno_std/discussions/3775_

**Comment by iuioiua** [comment]
Hi @RuiNtD, we deprecated `std/permissions` because:
* It's a very thin wrapper around the Deno Permissions API and trivial to implement on one's own. As you mentioned, it seems you can probably just use something like this:
  ```ts
  export async function grantOrThrow(descriptor: Deno.PermissionDescriptor) {
    const { state } = await Deno.permissions.request(descriptor);
    if (state !== "granted") throw new Deno.errors.PermissionDenied(...message);
  }
  ```
* It appears to have near-zero usage within the Deno ecosystem.

If you're using this in all your projects, you may be unaware of the built-in `--no-prompt` flag, which throws if any required permission is not provided. You can find out about it [here](https://medium.com/deno-the-complete-reference/deno-nuggets-disable-permission-prompting-973b79c710c3).

**Comment by RuiNtD** [comment]
I don't want to throw if permissions aren't given ahead of time. I use this to prompt for whole folders to be written to, instead of writing each individual file.

**Comment by iuioiua** [comment]
I just want to emphasise my previous 2 points. Also, please keep in mind that `std/permissions` will still be available after its removal by using previous versions of the Standard Library.

**Comment by iuioiua** [comment]
@RuiNtD, IIUC, you can use the following function for your use case:
```ts
function grantOrThrowDir(path: string) {
  if (
    Deno.permissions.requestSync({ name: "read", path }).state !== "granted" ||
    Deno.permissions.requestSync({ name: "write", path }).state !== "granted"
  ) {
    throw new Deno.errors.PermissionDenied();
  }
}
```
Does that help?

**Comment by iuioiua** [comment]
Closing this now as I feel as though I've answered the question. Please feel free to re-open if you'd like to continue the discussion.

**Comment by nhrones** [comment]
@iuioiua `stick to your guns`, you're doing a great and thankless service cleaning up `deno-std`!   
By the way, Accumulator would have been a great, and performant fit in `/std/bytes/`!
