### ISSUE TITLE
Multiple header in response

### ISSUE THREAD

**Issue by zekth** [denoland/deno_std#379]
As mentionned in : https://github.com/denoland/deno_std/pull/359

We currently can't send multiple `Set-Cookie` header due to the usage of `Headers` (allow only 1 unique key) in `ServerResponse`. But RFC says the server can send multiple `Set-Cookie` headers. For example even github do this on `http://github.com/manifest.json: see:
```
Set-Cookie: user_session=rSECRETUSERSESSIONG__eUNGH1n; path=/; expires=Sat, 18 May 2019 14:46:58 -0000; secure; HttpOnly
Set-Cookie: __Host-user_session_same_site=FOFOFOFOFOFO-xLMEBcK1K3G__eUNGH1n; path=/; expires=Sat, 18 May 2019 14:46:58 -0000; secure; HttpOnly; SameSite=Strict
Set-Cookie: has_recent_activity=1; path=/; expires=Sat, 04 May 2019 15:46:58 -0000
```
RFC:
```
An origin server can include multiple
   Set-Cookie header fields in a single response.  The presence of a
   Cookie or a Set-Cookie header field does not preclude HTTP caches
   from storing and reusing a response.
```

So we may need to stop using `Headers` and write our own class for this.

**EDIT**: Seems like in golang it uses another function instead of direct http header handling for setCookie:
https://golang.org/pkg/net/http/#SetCookie

ref: https://tools.ietf.org/html/rfc6265#page-17
@ry your opinion on this?

**Comment by jamesseanwright** [comment]
I've just run into this problem today. Looking at the [`Headers` class](https://fetch.spec.whatwg.org/#headers-class) heading in the [`fetch` spec](https://fetch.spec.whatwg.org) reveals an interesting caveat:

> Unlike a header list, a Headers object cannot represent more than one `Set-Cookie` header. In a way this is problematic as unlike all other headers `Set-Cookie` headers cannot be combined, but since `Set-Cookie` headers are not exposed to client-side JavaScript this is deemed an acceptable compromise. Implementations could chose the more efficient Headers object representation even for a header list, as long as they also support an associated data structure for `Set-Cookie` headers. 

Looking at that last sentence, it seems that we'll somehow have to abstract or augment `Headers` and consume this in the HTTP module's [`writeResponse` function](https://github.com/denoland/deno_std/blob/master/http/server.ts#L60). I think it's a shame as this could prove a slippery slope towards adding custom logic for other headers, but judging by the spec and other implementations, this may be the only way.

Let me know if you'd like a hand implementing this. I've spent quite a bit of recent time playing with Deno and its standard HTTP module, so I'm somewhat familiar with its internals.
