### ISSUE TITLE
suggestion: deprecate `std/http/methods`

### ISSUE THREAD

**Issue by iuioiua** [denoland/deno_std#3792]
Does anyone use/need [`std/http/methods`](https://deno.land/std@0.206.0/http/method.ts)? If not, we should remove it.

**Comment by iuioiua** [comment]
I have yet to see any objections. I'll go ahead with creating a PR to do so.

**Comment by iuioiua** [comment]
Confirmed via analytics that this API is barely used. We're proceeding with the deprecation. Objections are still welcome.

**Comment by jollytoad** [comment]
I use the HttpMethod type in my request handling helper function... https://deno.land/x/http_fns@v0.0.27/method.ts?doc=&s=byMethod

which looks like this in usage:

```ts
byMethod({
    GET: (req) => ...
})
```

so having the HttpMethod enables suggestion for the method names in vscode, ideally I'd like to be able to define the method type as the union of common methods or string (eg: `type Method = "GET" | "POST" | string`, and have suggestions still but not limit the actual method string, but unfortunately this is just seen as a string when it comes to auto-complete suggestions :(

anyway, it's the not the end of the world, I can just duplicate this type, or fallback to string and forego the auto-complete.

**Comment by jollytoad** [comment]
I've actually found a better work-around for my issue now, by defining the common http methods as keys of an object type with a general catch all string keys, this gives me the autocomplete behaviour I wanted and without the excessive noise of the more obscure http methods.

**Comment by iuioiua** [comment]
Able to share a snippet? I'm curious.

**Comment by jollytoad** [comment]
```ts
/**
 * A record of method handlers for use with byMethod.
 * This type is designed to aid auto-completion of method names.
 */
export type MethodHandlers<A extends unknown[]> = Partial<
  MethodRecord<(request: Request, ...args: A) => Awaitable<Response | null>>
>;

type MethodRecord<T> = {
  DELETE: T;
  GET: T;
  HEAD: T;
  OPTIONS: T;
  PATCH: T;
  POST: T;
  PUT: T;
  [method: string]: T;
};

export function byMethod<A extends unknown[]>(
  handlers: MethodHandlers<
A>,
) { ...
```

method suggestions in vscode...

![method_autocomplete](https://github.com/denoland/deno_std/assets/71291/3c8c3682-ff45-4a95-8213-55c19dc202b2)
