### ISSUE TITLE
suggestion: centalise external dev dependencies

### ISSUE THREAD

**Issue by iuioiua** [denoland/deno_std#3795]
Having a `dev_deps.ts` or similar somewhere containing all the external development dependencies is a good idea. It'd allow us to manage/update these dependencies, even do it automatically. External dependencies will have to be audited to determine which approach is best.

**Comment by lino-levan** [comment]
I think it would be best to just put them in the `deno.jsonc`? No need for a `deps.ts` file I think.

**Comment by iuioiua** [comment]
Yep! That'd be better actually.
