### ISSUE TITLE
suggestion: move testing examples elsewhere

### ISSUE THREAD

**Issue by iuioiua** [denoland/deno_std#3822]
`std/testing` has a bunch of example code. E.g. `bdd_examples/` and `chai_example.ts`. Perhaps these should be moved elsewhere, like [denobyexample](https://examples.deno.land/) or [examples in the manual](https://deno.com/manual/examples), as suggested in #3463. This includes anything with an `_example` or `_examples` suffix in `std/testing`.

**Comment by lino-levan** [comment]
I'd be in favor of moving them to denobyexamples under a new category.

**Comment by iuioiua** [comment]
"Testing" category?

**Comment by lino-levan** [comment]
I think a testing category would make a lot of sense.

**Comment by iuioiua** [comment]
I'd be happy to take a look at any PRs in that repo 👍🏾

**Comment by karfau** [comment]
Do I understand correctly that the examples have been dropped from this repo before they have been recreated in the other repository?
Luckily the required information is preserved in https://github.com/denoland/denobyexample/issues/111 by pointing to the tree at a state that still contains the examples, but it makes those things really hard to find.

**Comment by iuioiua** [comment]
Yes, the example files were removed. However, the code snippets were also moved to relevant JSDocs within the `std/testing` sub-module. See [here](https://deno.land/std@0.208.0/testing/bdd.ts?doc=).
