### ISSUE TITLE
suggestion: add fatal handler to "log"

### ISSUE THREAD

**Issue by yuqingc** [denoland/deno_std#383]
Go's `log.Fatal()` crashes the current process with a non-zero code. I suppose we might as well add a similar handler like "crash"(or other ways), to opt-in crash our process with a non-zero code when there is a CRITICAL-level log(for example, log.critical or log.fatal).

**Comment by bartlomieju** [comment]
I can see usages for that, if there's enough interest we should consider adding `logger.fatal()` that has the highest priority and exits with non-zero code.
