### ISSUE TITLE
Proposal: Use `deprecate:` tag for deprecation commits

### ISSUE THREAD

**Issue by kt3k** [denoland/deno_std#3856]
We currently use `BREAKING:` tag for both 'deprecation' and 'removal' changes to make users more aware of these changes. However this is probably not correct because deprecation commits don't actually break the user's code.

I suggest we should use `deprecate:` tag for the deprecation commits to reflects the nature of change more accurately.

(Note: I choose `deprecate:` because none of conventional tags don't feel reflecting the nature of deprecation enough well)

cc @bartlomieju @iuioiua

**Comment by iuioiua** [comment]
I agree.

**Comment by lino-levan** [comment]
I'm surprised conventional commits don't have something for deprecated. I think this makes sense.

**Comment by iuioiua** [comment]
Closing as we're all in agreeance.
