### ISSUE TITLE
Export http listener

### ISSUE THREAD

**Issue by zhmushan** [denoland/deno_std#386]
In some case, we may need to close the listener manually.

**Comment by keroxp** [comment]
I agree, and have some opinion for it.

I think `AsyncIterableIterator` is not suitable for async event handler. There is no way to stop iteration while awaiting next promise, and `yield` generally blocks generator loop. It degrades concurrency of async handler in many cases. 

In fact, `await` was [remove](https://github.com/denoland/deno_std/blob/master/http/http_bench.ts#L11) from `http/http_bench.ts` .  This is fake benchmark. That means `serve` forces developers stop using await in loop. 

`AsyncIterableIterator` is suitable for serial executor of promises, not for concurrent handler.  While developing my HTTP server module [servest](https://github.com/keroxp/servest), I realized that just async callback is good enough for async event handler

Actually there is about 2.3x throughput difference between `serve()` style and `listenAndServe()` style. 

https://github.com/keroxp/servest/blob/master/benchmark/serve_bench.ts
```ts
for await (const req of serve(addr)) {
    try {
      await req.respond({status: 200, body});
    } catch (e) {

    }
  }
```
```
Running 30s test @ http://127.0.0.1:4500
  12 threads and 400 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    37.47ms    6.13ms  84.33ms   90.25%
    Req/Sec   841.49    101.64     1.33k    87.72%
  301704 requests in 30.04s, 14.39MB read
  Socket errors: connect 0, read 358, write 0, timeout 0
Requests/sec:  10043.13
Transfer/sec:    490.40KB
```

https://github.com/keroxp/servest/blob/master/benchmark/listen_and_serve_bench.ts
```ts
async function main(): Promise<void> {
  listenAndServe(addr, async req => {
    await req.respond({ status: 200, body });
  });
}
```

```
Running 30s test @ http://127.0.0.1:4500
  12 threads and 400 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    16.86ms   13.78ms 480.97ms   99.41%
    Req/Sec     1.99k   157.95     2.92k    92.78%
  713506 requests in 30.02s, 34.03MB read
  Socket errors: connect 0, read 342, write 0, timeout 0
Requests/sec:  23768.47
Transfer/sec:      1.13MB
```

I propose deprecating `serve()` and `ws.receive()` and let `listenAndServe()` style's API  be standard async handler

It is also easy to export listener like this.

```ts
export function listenAndServe(addr: string): ListenerLike
```

**Comment by ry** [comment]
@keroxp You're absolutely right. In `for await...of`, the `next()` method is not called until the previous promise has resolved. I am ashamed to not have recognized this before.

The consequence of this is that we must remove it from the HTTP interface.

**Comment by ry** [comment]
@keroxp While I agree with you, I do want to avoid having a callback that is triggered for each request. Generally you want to receive new requests as quickly as possible, but there are situations where a server becomes overloaded and should not try to get new requests. There should be some way of giving back pressure. With a callback API, back pressure is only achieved with additional methods (often called `pause()` in Node).

So the question is, should we just better document the behavior of for await in servers? Or should we use something like this:
```js
while (true) {
  let req = server.next();
  req.respond({ body });
}
```
At least with the explicit while loop, it's very clear that the user should not call await.

**Comment by j-f1** [comment]
Maybe something like

```ts
server.handleRequestsWith({ max: 5 }, req => { ... })
```

This would specify that up to 5 requests can be handled at once, with further requests being forced to wait until previous ones are finished.


Alternatively, maybe encouraging a `Worker`-based API?

```ts
server.startWorkers('./foo.ts', {
  max: 5, // defaults to the number of CPUs
  initWorker: worker => {
    worker.postMessage({ foo: 'bar' })
    worker.addEventListener('message', () => ...)
  }
})
```

This would automatically boot new workers as needed and potentially kill them if server load decreases. The `initWorker` function could be used to enable workers to share state.

**Comment by ry** [comment]
@j-f1 I think features like that should be left to frameworks.

Upon further thinking I think for-await loop is fine API. We should adjust the documentation to remind people not to await in the loop.

**Comment by sholladay** [comment]
> We should adjust the documentation to remind people not to await in the loop.

Oops. I think multiple frameworks are doing that.

Code like this, right?

https://github.com/sholladay/pogo/blob/e63ae6004b3ea4176e0c9918c351728727933202/main.js#L56

Looking at it with a fresh pair of eyes, I guess that is waiting until the first request is completely responded to before making any progress on a second request. We don't actually want to block the loop, though.

**Comment by ry** [comment]
```
        for await (const request of server) {
            await this._handleRequest(request);
        }
```
Yeah - that's bad. It's obvious once you think about it, but we're all still new to for-await, so I think a reminder in the docs would be the best approach.

**Comment by sholladay** [comment]
Yeah, agreed that documentation about `await` is important. I fixed the usage in pogo.

In terms of being able to close the listener, what are your thoughts? I'm not really sure how to implement a `server.stop()` method. I tried setting a boolean that `break`s out of the loop, but of course this means the server will keep listening until a new request comes in. And in fact, `break`ing out of the loop seems to do very little - deno keeps running regardless.

**Comment by Fenzland** [comment]
There are some better ways to use async iterator server:

### The worst
```javascript
for await ( const request of serve( host, ) )
{
	const response= await handle( request, );
	
	request.respond( response, );
}
```
In this case, we get, handle and respond request queuely.

### A little better
```javascript
for await ( const request of serve( host, ) )
	handle( request, ).then( response=> request.respond( response, ), );
```
In this case, we handle and respond request concurrently, but get request queuely.

### More better
```javascript
const MAX_CONCURRENCY= 1024;
let counter= 0;

const server= httpServer.serve( host, )[Symbol.asyncIterator]();

while( true )
{
	if( counter < MAX_CONCURRENCY )
		listen();
	else
		await timeout();
}

async function listen()
{
	++counter;
	
	const { value:request, }= await server.next();
	
	const response= await handle( request, );
	
	request.respond( response, );
	
	--counter;
}

```
In this case, we get, handle and respond request concurrently, and control the concurrency by a counter.
