### ISSUE TITLE
Run `deno doc --lint` on all exported files

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno_std#3878]
To ensure all files have sufficient documentation, we should run `deno doc --lint`. This will expose errors such as:

- missing JSDoc comments on exported symbols
  - ```
    Missing JSDoc comment.
        at file:///Users/lucacasonato/projects/github.com/denoland/deno_std/data_structures/binary_search_tree.ts:177:3
    ```
- symbols that are part of the public API, but not exposed
  - ```
    Type 'BinarySearchTree.prototype.rotateNode' references type 'Direction' which is not exported from a root module.`
    ```
- missing explicit typings on arguments / return types
  - ```
    Missing return type.
        at file:///Users/lucacasonato/projects/github.com/denoland/deno_std/data_structures/comparators.ts:5:1
    ```

**Comment by iuioiua** [comment]
Yep, for sure. It might also save a bit of time targeting any `mod.ts` files.

I think these points are best part of #3764 instead of a separate issue, as they refer to the same task.

**Comment by iuioiua** [comment]
I'm closing this in favor of #3878, which requires running `deno doc—-lint` on exported files.
