### ISSUE TITLE
Tests on Azure Pipelines (Mac) always fail

### ISSUE THREAD

**Issue by arcatdmz** [denoland/deno_std#389]
I believe these failures have nothing to do with the `deno_std` code. (In my local environment, calling `npm i functional-red-black-tree` before the actual tests resolved the issue.)

- https://dev.azure.com/denoland/deno_std/_build/results?buildId=1215
- https://dev.azure.com/denoland/deno_std/_build/results?buildId=1212

**Comment by zekth** [comment]
I have the same problem on one of my projects: https://travis-ci.org/zekth/deno-templates/jobs/531185589

not related to `deno_std` but `eslint`

**Comment by ry** [comment]
Fixed in https://github.com/denoland/deno_std/pull/390
