### ISSUE TITLE
suggestion(streams): deprecate `toArrayBuffer()`, `toBlob()`, `toJson()` and `toText()`

### ISSUE THREAD

**Issue by iuioiua** [denoland/deno_std#3894]
These functions can essentially be replaced as follows:
1. `toArrayBuffer(stream)` to `new Response(stream).arrayBuffer()`
2. `toBlob(stream)` to `new Response(stream).toBlob()`
3. `toJson(stream)` to `new Response(stream).json()`
4. `toText(stream)` to `new Response(stream).text()`

The main argument against using `Response` methods was it seems hacky. This argument doesn't justify duplicating functionality that comes for free, already built into the runtime, IMO. If our aim is to complement the Web API, we should remove these APIs.

**Comment by lino-levan** [comment]
One example right away that I found is:
```ts
const stringStream = ReadableStream.from(["hello", " deno ", "world"]);
await new Response(stringStream).text(); // throws!
```
which I feel is a reasonably common case (and is supported by the lib we ported these functions from).

**Comment by iuioiua** [comment]
That's a misuse of `Response` rather than a shortcoming. The correct use would just be:
```ts
const stringStream = ReadableStream.from(["hello", " deno ", "world"])
  .pipeThrough(new TextEncoderStream());
await new Response(stringStream).text();
```

**Comment by lino-levan** [comment]
`Response` just isn't meant to do this type of work. Here's another example that is impossible afaik to write using `new Response(thing).method();`:

```ts
const mixedStream = ReadableStream.from(["hello", Uint8Array.from([1, 2, 3, 4, 5]), "world", [1, 2, 3, 4, 5]]);
await new Response(stringStream).blob(); // throws!
```

**Comment by nhrones** [comment]
> `Response` just isn't meant to do this type of work. Here's another example that is impossible afaik to write using `new Response(thing).method();`:
> 
> ```ts
> const mixedStream = ReadableStream.from(["hello", Uint8Array.from([1, 2, 3, 4, 5]), "world", [1, 2, 3, 4, 5]]);
> await new Response(stringStream).blob(); // throws!
> ```

Did you mean  ` await new Response(mixedStream).blob(); // throws!`
Yes that also throws!

**Comment by lino-levan** [comment]
Ah sorry, you're right, let me edit that.

**Comment by iuioiua** [comment]
A stream of mixed types seems like an edge case, and I have yet to see one in testing code, let alone implementation code anywhere. Are you able to find any examples yourself? Catering to an edge case is not a good reason to have functionality within the Standard Library.

**Comment by nhrones** [comment]
I guess streaming a KvKey is not a good example?

**Comment by iuioiua** [comment]
Are you able to elaborate with a snippet?

**Comment by nhrones** [comment]
Nope!

**Comment by iuioiua** [comment]
> I guess streaming a KvKey is not a good example?

Sorry, I don't understand what you mean.

**Comment by nhrones** [comment]
I move a lot of KvKeys around in my RPC impls,  But I generally serialize first.  The example reminded me of a kv-multipart-key.

**Comment by lino-levan** [comment]
I don't feel super strongly, but I think it provides some value. If you think the cases I've presented do not warrant them existing, I would disagree but I wouldn't be offended if they were deprecated.

**Comment by kt3k** [comment]
I like to keep these methods.

> The main argument against using Response methods was it seems hacky.

I think that's enough good reason to provide these APIs. Newer users can be unaware of those hacky idioms.

**Comment by iuioiua** [comment]
After some thought, keeping these for newcomers may be the right move. Appreciate the feedback.
