### ISSUE TITLE
Logger implementation

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno_std#39]
I'm opening this issue to start discussion on vision for `logging` module.

Coming from Python world and being familiar with its library, my intent for Deno logging was to emulate [Python's approach](https://docs.python.org/3/library/logging.html#logging.Logger.log).

Its mechanism is based on:
- `loggers` - object to call to log something obviously
- `LogRecord` - contains timestamps and metadata about message logged by `logger`
- `handlers` - also known as `transports`. One `logger` may utilize multiple `handlers. Eg. console handler that print output to console, file handler that streams logs to file on disk.
- `filters` - predicates that interact with `LogRecords`, allowing for very granular control. Both `loggers` and `handlers` can have filters
- `formatters` - a function that given `LogRecord` instance returns output string

Loggers are accessed using `getLogger` function, so wherever in code you do `
const logger = logging.getLogger('myLogger');
`  you get the same instance.

[This page](https://docs.djangoproject.com/en/2.1/topics/logging/) gives a nice overview how to use it in action. 

One of more popular node's logging libraries [winston](https://github.com/winstonjs/winston) takes not so different approach.

I'm really interested what community expects.

**Comment by bartlomieju** [comment]
1. Agreed
2. IMHO Go's logging module is low level compared to Python's. Do we want to provide simpler solution in standard library and leave it to user libraries to provide more battery-included solution?
3. I think so, default logging level should display only error and critical messages, while `-D` set default log level to debug.

**Comment by djKooks** [comment]
@bartlomieju seems good!
Have one question...is `log.config` need `await`?

**Comment by bartlomieju** [comment]
Probably yes, I'm still trying to figure it out. But if you look for example at `deno.open` it's asynchronous, so making most of the handlers would be asynchronous operation. AFAIK you can't do asynchronous stuff in class constructor, so it might be rewritten to: `await new FileHandler().setup({ filename })`

**Comment by sh7dm** [comment]
I would like to work on file handler. OK?

**Comment by djKooks** [comment]
@bartlomieju please share to me how logger will be implemented when decided. I'll fix my PR by the guide if needed. Thanks for your work.

**Comment by bartlomieju** [comment]
@djKooks you can track progress in #51

**Comment by bartlomieju** [comment]
During chat conversation with @ry we concluded that logging methods should take only one argument `msg` and leave it to user to format message properly, eg. 
```ts
import * as deno from 'deno';
import * as log from 'https://deno.land/x/std/logging/index.ts';
const someNum = 100;
const someObj = { a: 1, b: 2 };
// instead of interpolation ...
log.info("Number: %n, object: %o", someNum, someObj);
// just use template strings
log.info(`Number: ${someNum}, object: ${deno.inspect(someObj)}`)
```
This minimizes the API that has to be implemented.


As for output format of each message, [Glog's style was proposed](https://github.com/google/glog/blob/0e4ce7c0c0f7cda7cc86017abd775cecf04074e0/src/glog/logging.h.in#L281) (also [here](https://medium.com/technical-tips/google-log-glog-output-format-7eb31b3f0ce5)). Note: we're not sure why leading bracket `[` is missing in glog's format. 

Proposed format:
```ts
[Lmmdd hh:mm:ss.uuuuuu threadid file:line] msg
```
where:
- `L` - level of message 
- `mmdd` - month and day
- `hh:mm:ss.uuuuuu` - timestamp
- `threadid` - PID of thread/process
- `file:line` - filename and line from where message originated. Not sure we can get that info currently.

Example line would look like this:
```
[D0301 10:04:23:43111 3451 main.ts:30] Some logged message
```

To be honest I'm not a big fan of this format, I'd prefer to output ISO date like this:
```
[D 2018-01-03 10:04:23:43111 pid:3451 main.ts:30] Some logged message
```

**Comment by hayd** [comment]
Would this be configurable?

**Comment by bartlomieju** [comment]
> Have you thought about how to extract "main.ts:30" ?

My initial idea was to leverage `Error.stack` but I'm concerned with performance, throwing error at each logged message can't be a good idea.

> > To be honest I'm not a big fan of this format

> Your proposed format is longer...

It is, but glog's format is hard to grep when you see it for first time, especially conjunction of log level and date. But I'm not sticking to it no matter what.

> > Would this be configurable?

> I'd rather we agree on one format...

That's fine for me, but it will bring a need for another logging libraries that allow to configure that.

**Comment by ry** [comment]
> My initial idea was to leverage Error.stack but I'm concerned with performance, throwing error at each logged message can't be a good idea.

Hm.. It's possible we could provide `__LINE__` as a preprocessed symbol in deno. For the filename we could use [import.meta](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import.meta) once https://github.com/denoland/deno/issues/975 lands.

**Comment by bartlomieju** [comment]
@ry one more comment on configurable format - tests would be much simpler if format could be manipulated, eg. date could be skipped. Otherwise we'd need some kind of wildcard matching?

**Comment by ry** [comment]
@bartlomieju true good point.

**Comment by bartlomieju** [comment]
After some consideration I think we might want to change `LogRecord` and signature of logging methods from:
```ts
export interface LogRecord {
  msg: string;
  args: any[];
  datetime: Date;
  level: number;
  levelName: string;
}

debug(msg: string, ...args: any[]) {
    return this._log(LogLevel.DEBUG, msg, ...args);
}
```
to:
```ts
type LogMetadata = {[key: string]: any};

export interface LogRecord {
  msg: string;
  metadata?: LogMetadata;
  datetime: Date;
  level: number;
  levelName: string;
}

debug(msg: string, metadata?: LogMetadata) {
    return this._log(LogLevel.DEBUG, msg, metadata);
}
```
this object would be placed in `LogRecord` and be later utilized in custom formatter. Simple but powerful IMHO.

**Comment by ry** [comment]
@bartlomieju That seems like more to type? Or maybe I misunderstand. Can you give some examples of invocation?

**Comment by bartlomieju** [comment]
Yeah after all it seems so. My initial idea was that `args` would be interpolated in `msg` (`msg % args`), but we already established that we don't want that.

We could keep `LogRecord.args` and allow to use that instead of metadata

**Comment by bartlomieju** [comment]
I reckon `log` implementation is good enough now we can close this.

**Comment by dandv** [comment]
For those who land here from a web search, what is the current status of `log`? https://jsr.io/@std/log ?

**Comment by kt3k** [comment]
`@std/log` is likely to be removed in the future. See the discussion in #6124

On the other hand, we are making OpenTelemery builtin to Deno runtime. See https://docs.deno.com/runtime/fundamentals/open_telemetry/

OpenTelemetry should cover the logging, monitoring, tracing of cloud software/application much better than `@std/log`
