### ISSUE TITLE
`std/http` menu is gone from the docs in 0.208.0?

### ISSUE THREAD

**Issue by Leokuma** [denoland/deno_std#3904]
https://deno.land/std@0.207.0/http/mod.ts
![image](https://github.com/denoland/deno_std/assets/9329952/2522d51e-1c53-4c0b-b705-88daac72afda)

-----------------------

https://deno.land/std@0.208.0/http/mod.ts
![image](https://github.com/denoland/deno_std/assets/9329952/a4fe4c30-6e56-46b0-869c-6de0abc1e82e)

**Environment**

- OS: Win11
- Firefox 120.0.1 64-bit

**Comment by iuioiua** [comment]
CC @crowlKats

**Comment by crowlKats** [comment]
This is fixed now
