### ISSUE TITLE
move `_format.ts` into root

### ISSUE THREAD

**Issue by scarf005** [denoland/deno_std#3912]
**Is your feature request related to a problem? Please describe.**

followup of https://github.com/denoland/deno_std/pull/3886#issuecomment-1835302006. currently `assert/_format.ts` and `expect/_format.ts` is identical but duplicated across modules.

**Describe the solution you'd like**

create private top-level module, `_format.ts` and `_format_test.ts`

**Describe alternatives you've considered**

- symlinks would probably not work on web.
- keep the status quo, however this increases cognitive complexity and makes it harder to sync both files.

**Comment by iuioiua** [comment]
Agreed. For context, we're in the process of preparing the Standard Library to be compatible with Deno's workspaces functionality. We had to copy this file as workspaces don't yet support internal utilities across sub-modules.

Either way, let's keep this open for when it does.

References:
* https://github.com/denoland/deno_std/issues/3880
* https://github.com/denoland/deno_std/pull/3884

**Comment by scarf005** [comment]
thanks for the context. should I open a draft PR, just in case?

**Comment by iuioiua** [comment]
Ah, perhaps not yet. @lucacasonato, could you please update this issue once the suggested functionality is supported?
