### ISSUE TITLE
Trim single function import dependencies

### ISSUE THREAD

**Issue by jtoppine** [denoland/deno_std#3915]
**Describe the bug**

We might wan't to take a look at the single function import dependency graphs to make sure no unnecessary dependencies are loaded, via util modules or such. 

For example `ensure_dir.ts` brings in 80 unique dependencies (102Kb). 

That's just to tell (in case of error) whether the target file is a file, directory or symlink. (`ensure_dir.ts` imports the very simple `getFileInfoType` function from `_util.ts` , and `_util.ts` imports a whole bunch of unneeded stuff ~80 dependencies total). This functionality could be achieved without any dependencies methinks.

ensureDir is just what I happened to notice, other functions around the std lib may have similar potential for "weight loss".

**Steps to Reproduce**

For example:
```
deno info https://deno.land/std@0.208.0/fs/ensure_dir.ts
```
You'll see a bunch of unnecessary stuff is imported.

I didn't go through all the files which might have such unnecessarily deep dependency graphs.

**Expected behavior**

Unneeded dependencies are not imported when using single function imports.

**Comment by iuioiua** [comment]
This can be improved by:
1. Importing directly from implementation files and not `mod.ts` files.
2. Breaking up internal utilities into separate files - one function per file.

For `std/fs`, I took care of the first one in #3916. The second one is still available as a contribution opportunity. PRs are welcome!
