### ISSUE TITLE
Consider porting path.swift 

### ISSUE THREAD

**Issue by ry** [denoland/deno_std#392]
https://github.com/mxcl/path.swift

Seems like a nice api

**Comment by zekth** [comment]
Looks nice but all the api?
Seems like you can chain a lot of `fs` features. Maybe porting it to another repo? Because `deno_std.path` is already used and may be misunderstanding.

**Comment by ry** [comment]
It doesn't need to be called "path". That said, I agree it would probably be better developed as an external repo... but if someone felt strongly about it, I would allow it here : )

**Comment by zekth** [comment]
I'll start a personnal repo. Let's see how is the interest of it in the futur.

**Comment by axetroy** [comment]
Although I think it is not a standard.

But maybe give it a try and we will see.

**Comment by zekth** [comment]
ref: https://github.com/zekth/deno-path-swift

**Comment by ry** [comment]
@zekth That's  not a very good name. 1) [it uses dashes instead of underscores ](https://deno.land/style_guide.html#forconsistencyuseunderscoresnotdashesinfilenames) 2) 'swift' in the name is confusing.

Better: deno_path2, deno_easypath, deno_fs2, ...

**Comment by zekth** [comment]
here we go: https://github.com/zekth/deno_easypath

**Comment by axetroy** [comment]
@zekth 

Here is the case.

Your code does not guarantee the order of execution

```typescript
await Path.home.join("foo").mkdir(). copy("bar")
```

we must rewrite like this:

```typescript
const doAction = Path.home.join("foo").mkdir(). copy("bar"); // It just push the action to the queue

await doAction(); // execute the actions in the queue
```

**Comment by zekth** [comment]
I've not spotted those kind of example when i first read the documentation. You're right.

Btw i think this is revelant to add also a Sync implementation.

**Comment by zekth** [comment]
Improved the API and the chaining:
https://github.com/zekth/deno_easypath

Also waiting for https://github.com/denoland/deno_std/pull/278 to land for copy and will work on LS to be as tied as path.swift.

Suggestions welcome.

Thanks to @bartlomieju for the contributing.

**Comment by ry** [comment]
@zekth Nice! Consider submitting it to the registry. 

Also, the "new EasyPath" seems kinda weird. Why not have a constructor function?
```ts
import { path } from "https://deno.land/x/easypath";

path()
  .join("foo")
  .join("bar.ts")
  .toString(); // output foo/bar.ts
```
