### ISSUE TITLE
Azure Pipelines escapes forward slashes

### ISSUE THREAD

**Issue by ry** [denoland/deno_std#395]
The output of the CI is difficult to read. Example: https://dev.azure.com/denoland/deno_std/_build/results?buildId=1232&view=logs&jobId=0da5d1d9-276d-5173-c4c4-9d4d4ed14fdb&taskId=b525c197-f769-5e52-d38a-e6301f5260f2&lineStart=1&lineEnd=14&colStart=1&colEnd=1

Apparently you can't copy&paste from the log either (another great feature, MSFT) so here's a screenshot instead:
<img width="1278" alt="Screen Shot 2019-05-13 at 9 49 42 AM" src="https://user-images.githubusercontent.com/80/57626753-90ead800-7564-11e9-83e4-9ad53477e252.png">

**Comment by zekth** [comment]
On deno_std with 0.4.0 there is no such issue:
https://dev.azure.com/denoland/deno_std/_build/results?buildId=1234

This may be related to deno 0.5.0

**Comment by bartlomieju** [comment]
Seems like escape codes are now properly rendered

<img width="548" alt="Zrzut ekranu 2019-07-30 o 11 43 03" src="https://user-images.githubusercontent.com/13602871/62119157-405f5d00-b2bf-11e9-8f3e-04a9a281f06d.png">

Copy/pasting is still not working 😆 but I guess we can close this issue now @ry?
