### ISSUE TITLE
Remove log Handler.formatter string type

### ISSUE THREAD

**Issue by timreichen** [denoland/deno_std#3973]
**Is your feature request related to a problem? Please describe.**

The `formatter` property of `Handler` in log takes either a `string` or a `FormatterFunction`. The string type should be removed as an option because it interpolates strings by using a regexp and replacing it with a record value with non-standard syntax which is not type-safe. If a variable is misspelled, it will lead to unintended behaviours, namely print `{variable}` without throwing an error.

**Describe the solution you'd like**

The problem is solved by removing string as a valid type for formatter.

**Comment by timreichen** [comment]
How can a single type be deprecated? The following code will deprecate the whole formatter property:
```ts
export interface HandlerOptions {
  /**
   * @deprecated (will be removed in 0.212.0) Use {@linkcode FormatterFunction} instead.
   */
  formatter?: string | FormatterFunction;
}
```

**Comment by iuioiua** [comment]
I think in this case, your suggestion might be the best solution. WDYT, @kt3k?

**Comment by timreichen** [comment]
@kt3k Do you know if it can be done? If not, deno should introduce type deprecation with jsdoc. This might not be the only case.

**Comment by iuioiua** [comment]
Tweak:
```ts
export interface HandlerOptions {
  /**
   * @deprecated (will be removed in 0.212.0) Use {@linkcode FormatterFunction} instead of a string.
   */
  formatter?: string | FormatterFunction;
}
```

**Comment by iuioiua** [comment]
Completed in #4032.
