### ISSUE TITLE
Remove or move ./types.d.ts

### ISSUE THREAD

**Issue by dsherret** [denoland/deno_std#3995]
The `./types.d.ts` file won't work with the new registry so we should remove it.

**Comment by iuioiua** [comment]
[/types.d.ts](https://github.com/denoland/deno_std/blob/main/types.d.ts) is already deprecated for this reason. Thanks for checking though!

**Comment by dsherret** [comment]
I see that now, thanks! The copy of deno_std I had was out of date.
