### ISSUE TITLE
Reconsider deprecation of `std/permissions`

### ISSUE THREAD

**Issue by kt3k** [denoland/deno_std#4006]
We deprecated `std/permissions` because of low usage count, but there was a feedback from the community that `std/permissions` is still useful. ref: https://github.com/denoland/deno_std/issues/3776

Do you think it's worth being kept in std?

**Comment by jsejcksn** [comment]
Code ref: https://github.com/denoland/deno_std/blob/0.210.0/permissions/mod.ts

**Comment by jsejcksn** [comment]
I can empathize with the sentiment of the original comment. I think we've all been in a position of using an established API and thought _"Well this isn't very ergonomic to work with — I'd prefer an abstraction."_

> Do you think it's worth being kept in std?

For me, the answer would be the same as the one to this question: In general, should `std` provide wrapper functions that offer API _x_ in the form of _y_ instead?

**Comment by iuioiua** [comment]
We'll be removing this package once the Standard Library moves to JSR. See #4575.
