### ISSUE TITLE
deprecation note for `assertEquals` is not displayed in IDE

### ISSUE THREAD

**Issue by kt3k** [denoland/deno_std#4027]
When I overlay the API doc of 'deprecated' assertEquals of `testing/asserts.ts`, the deprecation note for it (`(will be removed after 1.0.0) Import from {@link https://deno.land/std/assert/assert_equals.ts} instead`) is not displayed in IDE. (The user can't get the information about the replacement in IDE)

<img width="841" alt="Screenshot 2023-12-27 at 23 01 40" src="https://github.com/denoland/deno_std/assets/613956/3fb8c1de-d77e-443f-8aee-8e335dbad12c">

**Comment by iuioiua** [comment]
I tested locally and can reproduce the issue. It appears that deprecation notices on re-exports, like those done in `testing/asserts.ts`, aren't correctly displayed. However, deprecation notices display fine when one imports a dependency and then exports that as a constant.

Doesn't work:
```ts
export {
  /** @deprecated ... */
  foo
} from "./foo.ts";
```

Works:
```ts
import { foo as _foo } from "./foo.ts";

/** @deprecated ... */
export foo = _foo;
```

This appears to be a runtime or VSCode plugin issue. I'll open up a separate issue in the main repo shortly.

**Comment by reggi** [comment]
I'm seeing this too, when I go to the source code there is no `@deprecation` comment. Is this a false flag because of the re-export?

<img width="895" alt="Screenshot 2023-12-29 at 10 53 28 AM" src="https://github.com/denoland/deno_std/assets/296798/f55bc5e5-17ef-4d79-a848-3a1adfe41cb0">

**Comment by iuioiua** [comment]
@reggi, what you're seeing is expected behaviour.

This is the old, deprecation location for this function.
```ts
import { assertEquals } from "https://deno.land/std@0.210.0/testing/asserts.ts";
```

This is the new, updated location for this function.
```ts
import { assertEquals } from "https://deno.land/std@0.210.0/assert/mod.ts";
```

**Comment by kt3k** [comment]
@iuioiua 

```ts
import { foo as _foo } from "./foo.ts";

/** @deprecated ... */
export const foo = _foo;
```

This pattern still doesn't seem working to me.

<img width="1078" alt="Screenshot 2023-12-31 at 21 14 29" src="https://github.com/denoland/deno_std/assets/613956/6de23926-2391-465f-9097-bd42efa0d844">

**Comment by kt3k** [comment]
@dsherret Is there any easy/good way to avoid the omission of `@deprecation` note in IDE in this situation?

**Comment by iuioiua** [comment]
To clarify:
1. The deprecation notice shows **correctly** on the deprecated constant.

![image](https://github.com/denoland/deno_std/assets/29347852/69cedd92-4c52-4764-b8c0-b3e19cbecfe1)

2. The deprecation notice shows **correctly** on the imported function.

![image](https://github.com/denoland/deno_std/assets/29347852/520e0c4b-bafc-4aeb-83a8-1a308293cb3f)

3. When called, The deprecation notice shows **incorrectly** on the function.

![image](https://github.com/denoland/deno_std/assets/29347852/f35e2df3-4813-48a0-b2b3-3a3401488cd3)
