### ISSUE TITLE
import https://github.com/lucascaro/deno-uuid into deno_std

### ISSUE THREAD

**Issue by ry** [denoland/deno_std#403]
cc @lucascaro

**Comment by axetroy** [comment]
Will it be better to port [https://github.com/kelektiv/node-uuid](https://github.com/kelektiv/node-uuid) ?

It contains several versions of UUID and is stable.

**Comment by hayd** [comment]
Is the deno one based on this gist? https://gist.github.com/jed/982883#gistcomment-2661313

**Comment by lucascaro** [comment]
mine is pretty basic  and it only supports v4, porting  https://github.com/kelektiv/node-uuid would be a better option long term

**Comment by lucascaro** [comment]
on the flip side, porting https://github.com/kelektiv/node-uuid would require more work since there's a fair amount of re-writing needed.

**Comment by lucascaro** [comment]
> Looks like the deno one based on this gist? https://gist.github.com/jed/982883#gistcomment-2661313

yep

**Comment by zekth** [comment]
https://github.com/denoland/deno/pull/2327 would be revelant to use in `deno-uuid` no?

**Comment by lucascaro** [comment]
taking a stab at this right now, I'll do an initial import of my code but using an api inspired in node-uuid, so we can iterate on it.
