### ISSUE TITLE
tracking: enable `noUncheckedIndexedAccess`

### ISSUE THREAD

**Issue by iuioiua** [denoland/deno_std#4040]
## Background

The [`noUncheckedIndexedAccess` TSConfig option](https://www.typescriptlang.org/tsconfig#noUncheckedIndexedAccess) makes access objects safer and improves object inference. Enabling this option will improve the overall code quality of the Standard Library. This tracking issue aims to shine a new light on the functionality first brought up in #937.

## Objectives

Modify the sub-modules of the Standard Library such that the TypeScript checker has no problems. The list of applicable sub-modules includes:
- [x] _tools
- [x] archive
- [x] assert
- [x] async
- [x] bytes
- [x] cli
- [x] collections
- [x] console
- [x] crypto
- [x] csv
- [x] data_structures
- [x] dotenv
- [x] encoding
- [x] expect
- [x] fmt
- [x] front_matter
- [x] fs
- [x] html
- [x] http
- [x] ini
- [x] io
- [x] json
- [x] jsonc
- [x] log
- [x] media_types
- [x] path
- [x] semver
- [x] streams
- [x] testing
- [x] text
- [x] toml
- [x] ulid
- [x] uuid
- [x] url
- [x] webgpu
- [x] yaml

## How to contribute
This assumes that the [Contributing Guidelines](https://github.com/denoland/deno_std/blob/7a0294a7f434919c67a807187dcea7bd5fe4947c/.github/CONTRIBUTING.md) are being followed. Also, please read [this](https://github.com/denoland/deno_std/pull/4275#pullrequestreview-1861556153) before proceeding with one of these PRs.
1. Choose a sub-module or small set of sub-modules you'd like to work on.
2. Temporarily enable the option in the [Deno configuration file](https://github.com/denoland/deno_std/blob/7a0294a7f434919c67a807187dcea7bd5fe4947c/deno.json):
    ```diff
    // deno.json
    {
      "compilerOptions": {
      "strict": true,
      "useUnknownInCatchVariables": true,
      "noImplicitOverride": true,
    + "noUncheckedIndexedAccess": true
      },
    ...
    }
    ```
3. Make the necessary code modifications to your given sub-module(s) until the type-checker is happy. E.g. for `std/collections`:
    ```bash
    deno check collections/mod.ts
    ```
4. Revert the option in the Deno configuration file.
    ```diff
    // deno.json
    {
      "compilerOptions": {
      "strict": true,
      "useUnknownInCatchVariables": true,
      "noImplicitOverride": true,
    - "noUncheckedIndexedAccess": true
      },
    ...
    }
    ```
5. Submit the PR as per the Contributing Guidelines.

The option will be enabled globally once the appropriate adjustments have been made to the entire codebase.

## References
* #937
* #4039
* https://www.totaltypescript.com/tips/make-accessing-objects-safer-by-enabling-nouncheckedindexedaccess-in-tsconfig

**Comment by syhol** [comment]
The following seem to be free of issues:
- datetime
- msgpack
- net
- permissions
- regexp

The following are used by many other modules so appear frequently as noise when running `deno check [mod]/*.ts`:
- assert
- path
- streams
- encoding

The following have many issues and might take a bit more effort:
- encoding (79 issues, but also 17 from assert)
- cli (60 issues, but also 17 from assert)
- http (69 issues, but also 17 from assert, 54 from cli, 13 from testing, 13 from path, 19 from encoding)
- data_structures (270 issues, but also 17 from assert)

I'm going to have a bash at `assert` next as it as nearly every other submodule depends on it in the testing code.

**Comment by iuioiua** [comment]
Thanks, @syhol! I've updated the initial comment.

**Comment by syhol** [comment]
flags is all done now that cli has been resolved. This can be removed or checked off @iuioiua.

**Comment by iuioiua** [comment]
For those wanting to contribute to this issue, please first read [this](https://github.com/denoland/deno_std/pull/4275#pullrequestreview-1861556153) before submitting a PR.

**Comment by javihernant** [comment]
working on enabling `noUncheckedIndexedAccess` in semver

**Comment by javihernant** [comment]
`deno check` with toml/mod.ts path/mod.ts streams/mod.ts return a clear output. Does that mean this tracking issue is already completed?

**Comment by javihernant** [comment]
working on enabling noUncheckedIndexedAccess in path

**Comment by gabelluardo** [comment]
Working on `toml` module

**Comment by iuioiua** [comment]
For those wanting to contribute, I've updated the task list, as a few sub-modules have changed since the creation of this issue. Only a little more to go.

**Comment by syhol** [comment]
http was done by @gabelluardo on Feb 15th. I think you can check it off.

**Comment by iuioiua** [comment]
There are still missing parts in `http/unstable_signed_cookie.ts`.

**Comment by syhol** [comment]
> There are still missing parts in http/unstable_signed_cookie.ts.

I can't recreate it. @iuioiua is the issue on my side or yours? Could we get a third party to check?

<details>
  <summary>Terminal output from my local setup</summary>

```console
deno_std on  main [!] via 🦕 v1.41.1 
❯ git pull origin main
From https://github.com/denoland/deno_std
 * branch              main       -> FETCH_HEAD
Already up to date.

deno_std on  main [!] via 🦕 v1.41.1 
❯ git diff
diff --git a/deno.json b/deno.json
index 619ab66f..d2db1fcf 100644
--- a/deno.json
+++ b/deno.json
@@ -2,6 +2,7 @@
   "compilerOptions": {
     "strict": true,
     "useUnknownInCatchVariables": true,
+    "noUncheckedIndexedAccess": true,
     "noImplicitOverride": true
   },
   "imports": {

deno_std on  main [!] via 🦕 v1.41.1 
❯ deno check http/**/*.ts
Check file:///Users/simon.holloway/Code/syhol/deno_std/http/_mock_conn.ts
Check file:///Users/simon.holloway/Code/syhol/deno_std/http/_negotiation/common.ts
Check file:///Users/simon.holloway/Code/syhol/deno_std/http/_negotiation/encoding.ts
Check file:///Users/simon.holloway/Code/syhol/deno_std/http/_negotiation/language.ts
Check file:///Users/simon.holloway/Code/syhol/deno_std/http/_negotiation/media_type.ts
Check file:///Users/simon.holloway/Code/syhol/deno_std/http/cookie.ts
Check file:///Users/simon.holloway/Code/syhol/deno_std/http/cookie_test.ts
Check file:///Users/simon.holloway/Code/syhol/deno_std/http/etag.ts
Check file:///Users/simon.holloway/Code/syhol/deno_std/http/etag_test.ts
Check file:///Users/simon.holloway/Code/syhol/deno_std/http/file_server.ts
Check file:///Users/simon.holloway/Code/syhol/deno_std/http/file_server_test.ts
Check file:///Users/simon.holloway/Code/syhol/deno_std/http/mod.ts
Check file:///Users/simon.holloway/Code/syhol/deno_std/http/negotiation.ts
Check file:///Users/simon.holloway/Code/syhol/deno_std/http/negotiation_test.ts
Check file:///Users/simon.holloway/Code/syhol/deno_std/http/server.ts
Check file:///Users/simon.holloway/Code/syhol/deno_std/http/server_sent_event_stream.ts
Check file:///Users/simon.holloway/Code/syhol/deno_std/http/server_sent_event_stream_test.ts
Check file:///Users/simon.holloway/Code/syhol/deno_std/http/server_test.ts
Check file:///Users/simon.holloway/Code/syhol/deno_std/http/status.ts
Check file:///Users/simon.holloway/Code/syhol/deno_std/http/status_test.ts
Check file:///Users/simon.holloway/Code/syhol/deno_std/http/test.ts
Check file:///Users/simon.holloway/Code/syhol/deno_std/http/testdata/file_server_as_library.ts
Check file:///Users/simon.holloway/Code/syhol/deno_std/http/unstable_signed_cookie.ts
Check file:///Users/simon.holloway/Code/syhol/deno_std/http/unstable_signed_cookie_test.ts
Check file:///Users/simon.holloway/Code/syhol/deno_std/http/user_agent.ts
Check file:///Users/simon.holloway/Code/syhol/deno_std/http/user_agent_test.ts
```
</details>

<details>
  <summary>Command to run it inside a fresh checkout in a docker container</summary>
<br>

**Warning: Its a bit slow, takes about 3-4 minutes to run for my machine**

```bash
docker run -i --rm denoland/deno:1.41.1 bash << EOF
  apt-get update
  apt-get install git jq -y
  cd srv
  git clone https://github.com/denoland/deno_std
  cd deno_std

  git pull origin main
  jq '.compilerOptions += {"noUncheckedIndexedAccess": true}' deno.json > deno-new.json
  mv deno-new.json deno.json
  git diff
  find http -type f -name "*.ts" | xargs -n1 deno check && echo "Check Succeeded" || echo "Check Failed" 
EOF
```

**Comment by iuioiua** [comment]
Use `deno task test` instead of `deno check`. I submitted #4453 with the changes.

**Comment by syhol** [comment]
Ahh I see thanks.

**Comment by iuioiua** [comment]
I've just updated the list once more. We're now quite close to having this completed.
