### ISSUE TITLE
Fix EOF handling in //io and //ws

### ISSUE THREAD

**Issue by ry** [denoland/deno_std#405]
There are several methods I've discovered that do not handle EOF
- [ ] `ws.readFrame()`
- [ ] `ioutil.readShort()`
- [ ] `ioutil.readInt()`
- [ ] `ioutil.readLong()`

Probably the best way to handle this is to return null on EOF?

cc @keroxp

**Comment by bartlomieju** [comment]
These issues have been fixed in #527 

CC @ry
