### ISSUE TITLE
It doesn't support international encoding so well :(

### ISSUE THREAD

**Issue by dotku** [denoland/deno_std#4051]
**Describe the bug**

My web version is okay, however when I open on my mobile, it goes wrong encoding. I don't know why.

**Steps to Reproduce**

1. visit https://techfront-openai-proxy-001.deno.dev/ by browser, works
2. Mobile Visit

![WechatIMG80](https://github.com/denoland/deno_std/assets/1519232/2598623a-bd81-45dd-b814-97ef41dd19ad)

**Expected behavior**

Expected support correct encoding, eg Asian languages.

**Environment**

- OS: iOS
- deno version: (where I can find out?)
- std version:

target repository: https://github.com/dotku/techfront-openai-proxy

**Comment by iuioiua** [comment]
Please provide details on how this relates to the Standard Library.

**Comment by iuioiua** [comment]
Actually, I'll close this. Please feel free to re-open it once you provide details that help troubleshoot the issue, if it relates to this repo.

**Comment by dotku** [comment]
Here is my full code

```
import { serve } from "https://deno.land/std@0.181.0/http/server.ts";

const OPENAI_API_HOST = "api.openai.com";

serve(async (request) => {
  const url = new URL(request.url);

  if (url.pathname === "/") {
    return fetch(new URL("./Readme.md", import.meta.url));
  }

  url.host = OPENAI_API_HOST;
  return await fetch(url, request);
});
```

wonder if return ` return fetch(new URL("./Readme.md", import.meta.url));` could add encoding?1

**Comment by dotku** [comment]
@iuioiua I don't see there is option for reopen? Can you help me reopen the ticket?

**Comment by iuioiua** [comment]
Try these:
1. The Standard Libary's `serve()` is deprecated. Instead, use `Deno.serve()`.
2. Serve files using the Standard Library's [`serveFile()`](https://deno.land/std@0.210.0/http/file_server.ts?s=serveFile) to serve your README file.

**Comment by babiabeo** [comment]
Try this:

```ts
const OPENAI_API_HOST = "api.openai.com";

const decoder = new TextDecoder();

Deno.serve(async (request) => {
  const url = new URL(request.url);

  if (url.pathname === "/") {
    const file = await Deno.readFile(
      new URL("./Readme.md", import.meta.url)
    );

    return new Response(
      decoder.decode(file)
    );
  }

  url.host = OPENAI_API_HOST;
  return await fetch(url, request);
});
```

**Comment by iuioiua** [comment]
Hi @dotku, did the above suggestions fix the issue?

**Comment by NaitLee** [comment]
The web server should specify encoding of a plain text file in http header:
```
Content-Type: text/plain;charset=utf-8
```
so that clients could decode the file correctly.
(luckily your readme is not using gb2312 lol)

My suggestion would be:

```typescript
const OPENAI_API_HOST = "api.openai.com";

Deno.serve((request) => {
  const url = new URL(request.url);

  if (url.pathname === "/") {
    return fetch(new URL("./README.md", import.meta.url)).then((resp) => {
      return new Response(resp.body, {
        headers: { "Content-Type": "text/plain;charset=utf-8" },
      });
    });
  }

  url.host = OPENAI_API_HOST;
  return fetch(url, request);
});
```

deno_std’s [file_server](https://deno.land/std/http/file_server.ts) is smart enough to deal with `Content-Type` (it gives the more correct `text/markdown; charset=UTF-8`), so this is not a issue of deno_std.

**Comment by kt3k** [comment]
> **Steps to Reproduce**
> 
> 1. visit https://techfront-openai-proxy-001.deno.dev/ by browser, works
> 2. Mobile Visit

I visited the above with mobile device and it seems rendered correctly. Closing as fixed

![unnamed-1](https://github.com/denoland/deno_std/assets/613956/a30e04a4-f821-49fc-aef3-97bec931f684)
