### ISSUE TITLE
tracking: `std/path` improvements

### ISSUE THREAD

**Issue by iuioiua** [denoland/deno_std#4066]
This issue tracks possible improvements that can be made to the `std/path` sub-module. Ideas are welcome.

- [x] #4067
- [x] #4068
- [x] #4069
- [x] #4070
- [x] #4071
- [x] #4073

**Comment by lino-levan** [comment]
@iuioiua I think this issue should be closed?

**Comment by iuioiua** [comment]
Yep! Thanks. Please let me know if there are any other issues that be closed, if you come across them 🙂
