### ISSUE TITLE
suggestion(path): remove `posix.toNamespacedPath()`

### ISSUE THREAD

**Issue by iuioiua** [denoland/deno_std#4069]

**Comment by kt3k** [comment]
There was a feedback from @jollytoad that they like to see `std/path`, `std/path/windows`, and `std/path/posix` having the same export items. That was why we didn't remove `toNamespacedPath` from `std/path/posix`

**Comment by iuioiua** [comment]
I understand but disagree. It being consistent doesn't seem like a reasonable justification for having a no-op function.

**Comment by kt3k** [comment]
I still don't fully understand the benefit of `std/path`, `std/path/windows`, and `std/path/posix` having the same exports very well.

@jollytoad Could you elaborate on what can be achieved with it?

**Comment by jollytoad** [comment]
The idea was that you could remap `std/path` to `std/path/posix` using your import map when deploying to a known platform (such as Deploy), thus eliminating all windows modules and all of the default platform branching modules from your deployment.

**Comment by jollytoad** [comment]
It unfortunately doesn't work though, we really needed the platform specific modules to not be a sub-path of `std/path` as suggested in this previous PR... https://github.com/denoland/deno_std/pull/3650

**Comment by kt3k** [comment]
Mapping per file still works with current structure:

```json
{
  "imports": {
    "https://deno.land/std@0.211.0/path/mod.ts": "https://deno.land/std@0.211.0/path/posix/mod.ts"
  }
}
```

```js
import { basename } from "https://deno.land/std@0.211.0/path/mod.ts";
console.log(basename.toString());
```

**Comment by iuioiua** [comment]
Remapping seems like an edge case that doesn't justify having a function that does nothing but return its argument.

**Comment by kt3k** [comment]
If remapping like the above works, that could be a part of best practice for deploying to prod environment, I guess (You can remove some dependency for free).

Also keeping `posix.toNamespacedPath()` doesn't cost anything.

**Comment by iuioiua** [comment]
Yes. Keeping `posix.toNamespacedPath()` doesn't cost anything. But I still don't see a use case involving import mapping that would justify keeping a function that does nothing. Even if there was one, one can remove that function call, and their code works fine.

Either way, feel free to close this issue if you feel strongly enough about it. It's no big deal, either way.

**Comment by jollytoad** [comment]
@kt3k remapping the single mod.ts isn't effective, as other modules use the individual modules directly, for remapping to be truely effective you need to remap the folder (trailing /), but the fact that the target is a sub-path path complicates things (ie. path/ -> path/posix/), if it were a sibling (ie. path/ -> path_posix/) it would make the remapping simple and effective.

import maps allow a very simple and efficient static dependency injection mechanism, i find it a shame that it hasn't been embraced more by the Deno community (maybe I need to write a blog!)

I'd love to see it become a standard practice in the std lib wherever a implementation choice may occur, although it would require another round of reorganisation.

Here's a more concrete example of a simple Deno library I've created that utilises import mapping to chose an implementation of a simple storage interface, the choice being Deno.KV, web storage, filesystem etc... https://github.com/jollytoad/deno_storage_modules

**Comment by iuioiua** [comment]
Sticking to the subject, are we fine with removing `posix.toNamespacedPath()`?

**Comment by kt3k** [comment]
I'm not convinced. The benefit by getting rid of it feels too minimal or nothing.

And remapping of `std/path/*` to `std/path/<platform>/*` is still possible by listing all entries in `std/path/*` in import map

```json
{
  "imports": {
    "https://deno.land/std@0.211.0/path/mod.ts": "https://deno.land/std@0.211.0/path/posix/mod.ts",
    "https://deno.land/std@0.211.0/path/basename.ts": "https://deno.land/std@0.211.0/path/posix/basename.ts",
    "https://deno.land/std@0.211.0/path/common.ts": "https://deno.land/std@0.211.0/path/posix/common.ts",
    ...
  }
}
```

So this can be free perf improvement of any app when deployed to certain platform.

**Comment by iuioiua** [comment]
Ok. Closing.
