### ISSUE TITLE
why noLib: true is set in tsconfig.json?

### ISSUE THREAD

**Issue by keroxp** [denoland/deno_std#407]
<img width="571" alt="スクリーンショット 2019-05-15 2 39 12" src="https://user-images.githubusercontent.com/927286/57720533-fce05400-76bc-11e9-9683-7a239af7bfb5.png">

I'm using type definition file generated by `deno types > deno.d.ts` while developing. But  IDE shows many symbol errors as `noLib: true` is set in `tsconfig.json`. Why `noLib: true` is needed? Doesn't deno explicitly refer to `esnext` lib?

**Comment by kitsonk** [comment]
There was a change of behaviour in TypeScript 3.2 in regards to noLib and the tsconfig should be changed to remove that and be more like https://github.com/kitsonk/deno_example
