### ISSUE TITLE
suggestion(path): introduce `delimiter.ts` files

### ISSUE THREAD

**Issue by iuioiua** [denoland/deno_std#4070]
`path/mod.ts` exports a `delimiter` variable.
https://github.com/denoland/deno_std/blob/bd08c2b57d37f6443aa5f6a58dc5b3f5e981effc/path/mod.ts#L48-L50

This should be moved to a separate `path/delimiter.ts` file with a similar structure to `path/separator.ts`. `path/mod.ts` should then re-export from that `path/delimiter.ts` file.

**Comment by joehillen** [comment]
@iuioiua Can you add more details?

**Comment by iuioiua** [comment]
Sorry. See above.

**Comment by iuioiua** [comment]
Update: instead, let's introduce `constants.ts` files containing separators and delimiters.
