### ISSUE TITLE
suggestion(net): preferred port for getAvailablePort()

### ISSUE THREAD

**Issue by jollytoad** [denoland/deno_std#4080]
**Is your feature request related to a problem? Please describe.**

I run a lot of micro-servers locally in development, sometimes I want to supply a preferred port for each, but also would like to fallback on any available port if the preferred one is taken.

**Describe the solution you'd like**

I'd like to be able to supply a preferred port as a parameter to `getAvailablePort`, it would check this port is available and return it if so, otherwise it falls back to finding a random available port as it currently does.

```ts
const port = getAvailablePort(8000);
```

**Potential implementation**

```ts
export function getAvailablePort(preferredPort = 0): number {
  try {
    const listener = Deno.listen({ port: preferredPort });
    listener.close();
    return (listener.addr as Deno.NetAddr).port;
  } catch (e) {
    if (preferredPort !== 0 && e instanceof Deno.errors.AddrInUse) {
      return getAvailablePort();
    } else {
      throw e;
    }
  }
}
```

**Comment by iuioiua** [comment]
Cool idea. I'd happily take a look at a PR that implements this. WDYT, @kt3k?

**Comment by iuioiua** [comment]
I looked at #4151. The PR looks fine, but I wonder whether it might be more useful to instead have a different function that only checks whether a port is available. Say, an `isPortAvailable()`. Both functions could be used independently and, if needed, together.

A use case would include when the user must use a particular port and no other port. What do we think?

```ts
export function isPortAvailable(port: number): boolean {
  try {
    const listener = Deno.listen({ port });
    listener.close();
    return true;
  } catch (error) {
    if (error instanceof Deno.errors.AddrInUse) {
      return false;
    }
    throw error;
  }
}
```

**Comment by lino-levan** [comment]
I'm not sure. `getAvailablePort` already seems race-y and `isPortAvailable` even more so. Up to you. No strong feelings, just a minor concern.
