### ISSUE TITLE
suggestion(log): Logger `warn()` method instead of `warning()`

### ISSUE THREAD

**Issue by timreichen** [denoland/deno_std#4099]
Shouldn't the `warning()` method  in `Logger` be actually called `warn()` like in `console.warn()`? 

**Describe the solution you'd like**

I suggest deprecating `warning()` and rename it to `warn()` in order to align to `console`.

**Comment by joehillen** [comment]
Yes, please. This has tripped me up as well.

**Comment by iuioiua** [comment]
PRs are welcome.

**Comment by timreichen** [comment]
That begs the question if the `WARNING` log level should be `WARN` instead too.

**Comment by iuioiua** [comment]
Completed in #4117 and #4170. Thank you for the suggestion.
