### ISSUE TITLE
[discussion] Non-MIT License code in deno_std

### ISSUE THREAD

**Issue by arcatdmz** [denoland/deno_std#410]
With regards to #376, I've started to port `pako` to Deno, a JavaScript port of `zlib` library.
https://github.com/arcatdmz/deno_std/tree/feat-archive-zip/archive

What I've just noticed is that `zlib` is under zlib license, which looks pretty flexible and "free" but is definitely NOT the MIT License.
https://en.wikipedia.org/wiki/Zlib_License

Would it be okay to mix some code under a different license? I guess it's case-by-case basis and would love to hear if containing zlib-licensed code is OK.

**Comment by ry** [comment]
@arcatdmz zlib license looks fine and MIT compatible. But please highlight which files are under this license when you submit your code, and ensure they have the proper headers.

Thanks for raising this.
