### ISSUE TITLE
tracking: `std/log` improvements

### ISSUE THREAD

**Issue by iuioiua** [denoland/deno_std#4102]
This issue tracks possible improvements that can be made to the std/path sub-module. Ideas are welcome. It'd be good to also discuss the requirements of this sub-module.

- [x] #4099
- [x] #4103
- [x] #4174
- [x] #4175

**Comment by babiabeo** [comment]
@iuioiua I think this issue can be closed.

**Comment by iuioiua** [comment]
Yep! Thanks!
