### ISSUE TITLE
suggestion: deprecate `writableStrategy` and `readableStrategy` argument properties for `std/json` constructors

### ISSUE THREAD

**Issue by iuioiua** [denoland/deno_std#4113]
The `TransformStream`s in `std/json` are the only ones with `writableStrategy` and `readableStrategy` argument properties in their constructors. There are many other `TransformStream`s in the Standard Library, but none of them has these options, nor do they seem to need to. The `std/json` classes don't seem to be part of a special case either that justifies these properties. I think these options should be deprecated to trim needless moving parts.

**Comment by kt3k** [comment]
I feel these options can be useful when the users need to control the buffer amount at transform stream node (when downstream is slower than upstream).

@crowlKats @ayame113 What do you think?

**Comment by iuioiua** [comment]
Perhaps, but I've yet to see demand for such functionality. If so, we should do this for all other `TransformStream`s in the Standard Library.

**Comment by iuioiua** [comment]
What shall we do?
1. Remove all strategy options for stream implementations. I suspect zero-little demand for this functionality, so this one has my vote.
2. Ensure all streams have strategy options.

**Comment by kt3k** [comment]
Let's not decide right now, but let's keep this issue open for a while to see more thoughts/opinions

**Comment by iuioiua** [comment]
@ayame113 and @crowlKats, WDYT?

**Comment by crowlKats** [comment]
I am in favour
