### ISSUE TITLE
bug: deprecation notices aren't shown on `https://deno.land/std/testing/asserts.ts`

### ISSUE THREAD

**Issue by impactaky** [denoland/deno_std#4116]
**Describe the bug**

Deprecated isn't shown on https://deno.land/std/testing/asserts.ts 

**Steps to Reproduce**

Open https://deno.land/std/testing/asserts.ts 

**Expected behavior**

Show like following comments

 ```
@deprecated (will be removed after 1.0.0) Import from {@link https://deno.land/std/assert/mod.ts} instead.
```

- std version: 0.211.0

**Comment by impactaky** [comment]
https://github.com/denoland/deno_std/issues/4027 looks like the same type of problem

**Comment by iuioiua** [comment]
Interesting. This issue deals with the documentation website not correctly displaying deprecation notices. I get the feeling that the fix, in this particular case, is moving the deprecation notice to after the JSDoc description instead of before the description.

**Comment by crowlKats** [comment]
There are two issues I see:
- deprecated tags (or any tags for the matter of fact) need always be after the description/body, since tags are greedy, and have no delimiter besides another tag.
- the doc generation does not have support for deprecated *files* currently

**Comment by iuioiua** [comment]
> * the doc generation does not have support for deprecated _files_ currently

Are you talking about doc generation for the current website? If so, it appears as though it does: https://deno.land/std@0.211.0/io/mod.ts

Note: the deprecation tags for these APIs are _after_ the description.

**Comment by crowlKats** [comment]
> Are you talking about doc generation for the current website? If so, it appears as though it does: https://deno.land/std@0.211.0/io/mod.ts

those deprecated tags are gotten from the symbol definition jsdoc (ie https://deno.land/std@0.211.0/io/buf_reader.ts?source#L20)

**Comment by iuioiua** [comment]
> > Are you talking about doc generation for the current website? If so, it appears as though it does: https://deno.land/std@0.211.0/io/mod.ts
> 
> 
> 
> those deprecated tags are gotten from the symbol definition jsdoc (ie https://deno.land/std@0.211.0/io/buf_reader.ts?source#L20)

I see. Perhaps the fix is to define a deprecated function that calls the actual function. We can't re-export and deprecate. WDYT?

**Comment by babiabeo** [comment]
I noticed that those functions are using jsdoc from `assert/*.ts`, not from `testing/asserts.ts`, that why the deprecation notices aren't shown.

Example:

In `testing/asserts.ts`, `assert` function doesn't have `@example` tag

https://github.com/denoland/deno_std/blob/bd08c2b57d37f6443aa5f6a58dc5b3f5e981effc/testing/asserts.ts#L16-L22

But in the documentation website, we can see that it has an example (https://deno.land/std@0.211.0/testing/asserts.ts?doc=&s=assert).
