### ISSUE TITLE
suggestion: re-consider the deprecation of some IO-related APIs

### ISSUE THREAD

**Issue by iuioiua** [denoland/deno_std#4120]
`std/io` is being deprecated because the `Deno.Reader` interface and friends are being deprecated from the runtime. However, their `read()`, `write()`, and other methods on I/O-related APIs, such as `Deno.FsFile` and `Deno.Conn`, are here to stay. These methods staying around justify keeping some IO-related APIs within the Standard Library instead of deprecating them.

To keep the Standard Library and its maintenance lean, I suggest we keep APIs that allow converting `Reader`s and `Writer`s to streams. This will need some more review, but, at first glance, I think we should un-deprecate:
* `readAll()`
* `readableStreamFromReader()`
* `writeAll()`
* `writableStreamFromWriter()`

CC @bartlomieju, @piscisaureus and @kt3k

**Comment by kt3k** [comment]
This makes sense to me as Web Stream doesn't completely cover what Reader(Sync)/Writer(Sync) does.

**Comment by kt3k** [comment]
@ry What do you think?

**Comment by iuioiua** [comment]
I've created #4128 to see what this could look like.

**Comment by bartlomieju** [comment]
Discussed with the CLI team and everyone agrees that it makes sense to keep these APIs in `deno_std`.

**Comment by kt3k** [comment]
I often saw people find `BufReader` `BufWriter` useful (I haven't used them though). Maybe those are also worth re-introduced?

**Comment by iuioiua** [comment]
I think there's an argument for `Buffer`, which, IIUC, is more general-purpose with read and write capabilities.
