### ISSUE TITLE
https://deno.land/std/http/http_status.ts does't work (404 not found)

### ISSUE THREAD

**Issue by emrahcom** [denoland/deno_std#4136]
[https://deno.land/std/http/http_status.ts](https://deno.land/std/http/http_status.ts) which points [https://deno.land/std@0.211.0/http/http_status.ts](https://deno.land/std@0.211.0/http/http_status.ts) currently, doesn't respond. It thows `404 not found`

**Comment by syhol** [comment]
Looks like http_status.ts has been deprecated since version 0.205.0 on 2023-11-01. Try using https://deno.land/std@0.211.0/http/status.ts instead.
