### ISSUE TITLE
dotenv should read from the root .env file

### ISSUE THREAD

**Issue by muddlebee** [denoland/deno_std#4137]
**Describe the bug**
https://deno.land/std@0.211.0/dotenv/mod.ts
dotenv package should read from the root directory of deno project. 

**Steps to Reproduce**

.
├── README.md
├── examples
│   └── listen-new-blocks.ts
│   └── .env
└── index.ts

When .env places inside sub-directory above(examples folder) it works, but not in the root directory.

**Expected behavior**

should work from the root directory.

**Environment**
- OS: [e.g. Ubuntu 20.04,]
- deno version: latest
- std version: latest

**Comment by muddlebee** [comment]
I'm not sure about the root directory concept here like it was in node.js

**Comment by iuioiua** [comment]
Hi Anwesh, does using the in-built `--env` CLI argument work for your use case instead? Documentation [here](https://deno.com/blog/v1.38#deno-run---env).

**Comment by kt3k** [comment]
`load` looks up `.env` from current directory. I think you ran the script from `./examples/`

**Comment by muddlebee** [comment]
thank you @iuioiua @kt3k 

> `load` looks up `.env` from current directory. I think you ran the script from `./examples/`
yes looks like this is the case. I got little confused in deno following the node-js mindset. but in node 🤔 I guess it also works inside the sub-directories.
