### ISSUE TITLE
todo: use `using` keyword

### ISSUE THREAD

**Issue by iuioiua** [denoland/deno_std#4138]
[Explicit Resource Management was introduced in Deno 1.38](https://deno.com/blog/v1.38#using-with-deno-apis) to close resources when they go out of scope. The Standard Library has yet to fully take advantage of this functionality. To make the upgrade, one can do something like:
1. Find disposable class instances. I.e. classes that extend or implement `Disposable` or `AsyncDisposable`. This can be done by looking for `.close()` in the codebase.
2. Replace `const` declaration with `using` for `Disposable` instances and `await using` for `AsyncDisposable` instances and remove the cleanup method.
    ```diff
    - const file = await Deno.open("./my-path.txt");
    + using file = await Deno.open("./my-path.txt");
    ...
    - file.close();
    ```
3. Run `deno task test`. Any leaking resources will be shown here.

**Comment by muddlebee** [comment]
can pick this up 👀 fairly trivial going through the codebase

**Comment by iuioiua** [comment]
> can pick this up 👀 fairly trivial going through the codebase

Great to hear! Feel free to ping me if you need anything. I'm also on Discord.
