### ISSUE TITLE
test errors for createHttpClient() at  deno_std/http/server_test.ts

### ISSUE THREAD

**Issue by muddlebee** [denoland/deno_std#4155]
error: TS2322 [ERROR]: Type '"unix"' is not assignable to type '"tcp"'.
      using listener = Deno.listen({ path, transport: "unix" });
                                           ~~~~~~~~~
    at file:///home/anwesh/denoland/deno_std/fs/walk_test.ts:172:44

TS2322 [ERROR]: Type '"unix"' is not assignable to type '"tcp"'.
      using listener = Deno.listen({ path, transport: "unix" });
                                           ~~~~~~~~~
    at file:///home/anwesh/denoland/deno_std/fs/walk_test.ts:189:44

TS2339 [ERROR]: Property 'createHttpClient' does not exist on type 'typeof Deno'. 'Deno.createHttpClient' is an unstable API. Did you forget to run with the '--unstable' flag? If not, try changing the 'lib' compiler option to include 'deno.unstable' or add a triple-slash directive to the top of your entrypoint (main file): /// <reference lib="deno.unstable" />
  const client = Deno.createHttpClient({
                      ~~~~~~~~~~~~~~~~
    at file:///home/anwesh/denoland/deno_std/http/server_test.ts:1162:23

TS2353 [ERROR]: Object literal may only specify known properties, and 'client' does not exist in type 'RequestInit'.
  const resp1 = await fetch(url, { client });
                                   ~~~~~~
    at file:///home/anwesh/denoland/deno_std/http/server_test.ts:1165:36

TS2353 [ERROR]: Object literal may only specify known properties, and 'client' does not exist in type 'RequestInit'.
  const resp2 = await fetch(url, { client });
                                   ~~~~~~
    at file:///home/anwesh/denoland/deno_std/http/server_test.ts:1166:36

TS2353 [ERROR]: Object literal may only specify known properties, and 'client' does not exist in type 'RequestInit'.
    const resp3 = await fetch(url, { client });
                                     ~~~~~~
    at file:///home/anwesh/denoland/deno_std/http/server_test.ts:1169:38

TS2339 [ERROR]: Property 'createHttpClient' does not exist on type 'typeof Deno'. 'Deno.createHttpClient' is an unstable API. Did you forget to run with the '--unstable' flag? If not, try changing the 'lib' compiler option to include 'deno.unstable' or add a triple-slash directive to the top of your entrypoint (main file): /// <reference lib="deno.unstable" />
      const client = Deno.createHttpClient({ caCerts: [caCert] });
                          ~~~~~~~~~~~~~~~~
    at file:///home/anwesh/denoland/deno_std/http/server_test.ts:1567:27

TS2353 [ERROR]: Object literal may only specify known properties, and 'client' does not exist in type 'RequestInit'.
        await (await fetch(`https://localhost:${port}/`, { client }))
                                                           ~~~~~~
    at file:///home/anwesh/denoland/deno_std/http/server_test.ts:1569:60

TS2339 [ERROR]: Property 'createHttpClient' does not exist on type 'typeof Deno'. 'Deno.createHttpClient' is an unstable API. Did you forget to run with the '--unstable' flag? If not, try changing the 'lib' compiler option to include 'deno.unstable' or add a triple-slash directive to the top of your entrypoint (main file): /// <reference lib="deno.unstable" />
      const client = Deno.createHttpClient({ caCerts: [caCert] });
                          ~~~~~~~~~~~~~~~~
    at file:///home/anwesh/denoland/deno_std/http/server_test.ts:1591:27

TS2353 [ERROR]: Object literal may only specify known properties, and 'client' does not exist in type 'RequestInit'.
        await fetch(`https://localhost:${port}/`, { client })
                                                    ~~~~~~
    at file:///home/anwesh/denoland/deno_std/http/server_test.ts:1593:53

**Comment by muddlebee** [comment]
> Property 'createHttpClient' does not exist on type 'typeof Deno'. 'Deno.createHttpClient' is an unstable API. Did you forget to run with the '--unstable' flag? If not, try changing the 'lib' compiler option to include 'deno.unstable' or add a triple-slash directive to the top of your entrypoint (main file): /// <reference lib="deno.unstable" />deno-ts(2339)

I am getting this warning 🤔

**Comment by iuioiua** [comment]
It appears you're running tests using `deno test <source>` directly. Instead, use `deno task test <source>`. The `test` task includes the missing `--unstable` flag, which is required to enable some of the unstable functionality needed in the tests.

**Comment by iuioiua** [comment]
@muddlebee, please try the above and let me know how you go.

**Comment by muddlebee** [comment]
@iuioiua thank you for guidance. I ran the command and it is working fine. just getting 1 error 

```
 ERRORS 

serveDir() sets date header => ./http/file_server_test.ts:113:6
error: AssertionError: Expected actual: "1705232579000" to be close to "1704846355425": delta "386223575" is greater than "300000".
  throw new AssertionError(
        ^
    at assertAlmostEquals (file:///home/anwesh/denoland/deno_std/assert/assert_almost_equals.ts:36:9)
    at file:///home/anwesh/denoland/deno_std/http/file_server_test.ts:124:3

 FAILURES 

serveDir() sets date header => ./http/file_server_test.ts:113:6

FAILED | 1921 passed (2516 steps) | 1 failed | 13 ignored (50s)
```

**Comment by muddlebee** [comment]
for this one https://github.com/denoland/deno_std/blob/main/http/file_server_test.ts#L113

**Comment by iuioiua** [comment]
Hi @muddlebee, are you still encountering this issue? Please ensure you're running the latest version of the Deno runtime, and run `deno task test http/file_server_test.ts`.
