### ISSUE TITLE
suggestion: re-structure `std/log` to adhere to singe-export files

### ISSUE THREAD

**Issue by iuioiua** [denoland/deno_std#4174]
Each file should export only tightly-related symbols.

Background #2936

**Comment by kt3k** [comment]
We recently sometimes choose non single-export file pattern (e.g. `std/text/cases`). What is the criteria to follow the pattern or divert from the pattern? Can we create an objective rule about it?

**Comment by iuioiua** [comment]
I think it's reasonable to group multiple symbols in the same file if at least one of the following is true:
1. Their signatures and dependencies have near-total overlap. E.g. `std/text/cases`
2. The symbols are highly likely to be used in conjunction. E.g. encoding and decoding functions.

These criteria should justify cases with many symbols within a given file or just one.

I'd be happy to document this if this sounds reasonable.

**Comment by kt3k** [comment]
Ok. Let's document them in README

**Comment by eryue0220** [comment]
Can I have a tried for this one?

**Comment by iuioiua** [comment]
Sure! I believe the next step is to factor out `setup()` into its own style.

**Comment by iuioiua** [comment]
Completed in #4254.
