### ISSUE TITLE
bug(expect): The function signature of `toMatchObject` is incorrect

### ISSUE THREAD

**Issue by BlackGlory** [denoland/deno_std#4190]
**Describe the bug**
The current `toMatchObject` cannot pass an array of objects, although it actually works.
https://github.com/denoland/deno_std/blob/4fe6be730d581c196fde7f33cc85b5dde8892244/expect/expect.ts#L77

```ts
expect(result).toMatchObject([])
// Argument of type 'never[]' is not assignable to parameter of type 'Record<PropertyKey, unknown>'.
// Index signature for type 'string' is missing in type 'never[]'.deno-ts(2345)
```

**Expected behavior**

It should be
```ts
toMatchObject<E extends {} | any[]>(expected: E): R;
```
(https://github.com/DefinitelyTyped/DefinitelyTyped/blob/15024fd054cd63fa11739f178a166d7c836b248e/types/jest/index.d.ts#L1078)

or

```ts
toMatchObject(
  expected: Record<string, unknown> | Array<Record<string, unknown>>,
): R;
```
(https://github.com/jestjs/jest/blob/2178fa2183cb7cb2ac3e262388499bafd032ef03/packages/expect/src/types.ts#L298-L300)

**Environment**
- std version: 0.212.0

**Comment by kt3k** [comment]
Thanks for your report! Can you send a PR to fix it? (The both fixes of the above look fine to me)
