### ISSUE TITLE
Bring back examples folder

### ISSUE THREAD

**Issue by wesleycoder** [denoland/deno_std#4222]
**Is your feature request related to a problem? Please describe.**

Tried to run an example given on a [short YT video](https://youtube.com/shorts/YImgsJNmMcc?si=Z0dvtB1v8-K8jTY0) from the Deno channel:
```sh
deno run https://deno.land/std/examples/welcome.ts
```
And when trying to figure out why it didn't work I saw that since v0.199.x the examples folder was removed.

**Describe the solution you'd like**

I couldn't find why that is and decided to come here and suggest it could be brought back if it isn't a problem.
It's a useful resource for newcomers and to keep consistency with earlier tutorials for beginners.

**Describe alternatives you've considered**

I know we can specify the version on the url but newcomers may not understand that principle when trying the suggested commands.
```sh
deno run https://deno.land/std@0.198.0/examples/welcome.ts
```

**Comment by babiabeo** [comment]
The `examples` folder was removed because it is not actually part of standard library. However, you can still see similar examples on https://examples.deno.land/, all of which can also be run locally.

Ref: #3463, #3546

**Comment by wesleycoder** [comment]
Nice to know, I'll try referencing it on the old materials I know that point to the old examples so newbies can get to it.
BTW I like how the example list is organized now.

I'll be closing this issue, thanks
