### ISSUE TITLE
Strange behavior of the `assertRejects()` method.

### ISSUE THREAD

**Issue by vinc3re** [denoland/deno_std#4225]
Behavior of the `assertRejects()` method.

`assertRejects()` fails when a non-stubbed method is called before the stubbed
method.

Let's look at the following example:

```ts
// main.ts
export class MainClass {
  async mainFn(): Promise<void> {
    await this.foo();
    await this.bar();
  }

  foo(): Promise<string> {
    return Promise.resolve("foo");
  }

  bar(): Promise<string> {
    return Promise.resolve("bar");
  }
}
```

```ts
// main_test.ts
import { describe } from "https://deno.land/std@0.212.0/testing/bdd.ts";
import { stub } from "https://deno.land/std@0.212.0/testing/mock.ts";
import { assertRejects } from "https://deno.land/std@0.212.0/assert/mod.ts";
import { MainClass } from "./main.ts";

describe("unit test", () => {
  const mainObj = new MainClass();
  const barStub = stub(
    mainObj,
    "bar",
    () => new Promise((_, reject) => reject(new Error())),
  );

  assertRejects(() => mainObj.mainFn(), "yeah, bar() rejects with Error");
  barStub.restore();
});
```

execute: `deno test`

_output:_

```bash
Check file:///tmp/stdstub/main_test.ts
Uncaught error from ./main_test.ts FAILED

 ERRORS 

./main_test.ts (uncaught error)
error: (in promise) AssertionError: Expected function to reject: yeah, bar() rejects with Error
    throw new AssertionError(
          ^
    at assertRejects (https://deno.land/std@0.212.0/assert/assert_rejects.ts:101:11)
This error was not caught from a test and caused the test runner to fail on the referenced module.
It most likely originated from a dangling promise, event/timeout handler, or top-level code.

 FAILURES 

./main_test.ts (uncaught error)

FAILED | 0 passed | 1 failed (0ms)

error: Test failed
```

Note that `bar()` is stubbed to reject the promise with an error. However,
`bar()` only rejects with an error if `foo()` is not called:

```ts
// main.ts
export class MainClass {
  async mainFn(): Promise<void> {
    //await this.foo(); // <-- foo() is not called
    await this.bar();
  }
//rest of code...
```

execute: `deno test`

_output:_

```bash
Check file:///tmp/stdstub/main_test.ts
running 1 test from ./main_test.ts
unit test ... ok (1ms)

ok | 1 passed | 0 failed (4ms)
```

What am I doing wrong? Is this a bug in the `stub()` method, or what am I not
understanding?

---

Note, in reality, in my actual test, I want to ensure that no developer alters the function equivalent to `mainFn()` by adding a `try-catch` block that silences and does not propagate the exception thrown by `bar()` or `foo()`. In other words, I want to ensure that nobody does this:

```ts
export class MainClass {
  async mainFn(): Promise<void> {
    try {
      await this.foo();
      await this.bar();
    } catch (error) {}
  }
  //...
}
```

Hence the use of the `assertRejects()` method. However, I'm not sure if I'm doing this correctly or if there is a bug in the `stub()` method.

**Comment by vinc3re** [comment]
Incredibly enough, I was assisted by Deno AI Helper, and I simply lacked an await before `assertRejects()`.

**Comment by iuioiua** [comment]
> Incredibly enough, I was assisted by Deno AI Helper, and I simply lacked an await before `assertRejects()`.

Also, https://discord.com/channels/684898665143206084/775393009981849600/1198136396129505351 😛
