### ISSUE TITLE
[discussion] Do not use glob for prettier by default

### ISSUE THREAD

**Issue by axetroy** [denoland/deno_std#424]
Use glob if there should be a wildcard, otherwise, use a normal file path

Otherwise, it is difficult for `Prettier` to format a specific file.

eg. in `deno_std` directory.

### We want to format the `test.ts` file.

only this file, no one else.

```bash
deno run prettier/main.ts test.ts
```

### Does it look right?

No.

It will format all files under `deno_std` directory which match with `/test\.ts/g`.

It is difficult to specify a file to format.

### Solution

This is the solution I think:

1. Use glob when wildcards appear, Otherwise use path.

2. Don't walk the entire directory

https://github.com/denoland/deno_std/blob/47134db9f24de802bee560941584bbc32e75a9c3/prettier/main.ts#L245-L253

### BREAKING CHANGES

1. without `wildcards`, It will select the specified file instead of a matching file.

**Before**

```bash
> deno run prettier/main.ts test.ts

Formatting test.ts
Formatting fs/test.ts
Formatting fs/copy_test.ts
Formatting fs/empty_test.ts
...
```

**After**

```bash
> deno run prettier/main.ts test.ts
Formatting test.ts
```

In order to keep the original function unchanged, you should write like this

```bash
> deno run prettier/main.ts **/*test.ts
Formatting test.ts
Formatting fs/test.ts
Formatting fs/copy_test.ts
Formatting fs/empty_test.ts
...
```

**Comment by kt3k** [comment]
npm has `is-glob` module. This looks a more robust approach to me.

[source](https://github.com/micromatch/is-glob/blob/master/index.js), [test](https://github.com/micromatch/is-glob/blob/master/test.js)

**Comment by axetroy** [comment]
@kt3k yes. that's great.

Are you interested in porting it?

**Comment by kt3k** [comment]
@axetroy 
I'm interested in it, but I can't start it right now. If you can do it, I appreciate your help!

**Comment by dshubhadeep** [comment]
@axetroy I would like to work on it, if that's okay with you

**Comment by axetroy** [comment]
@dshubhadeep 
I appreciate your help.

expose a new function name `isGlob`

```typescript
export function isGlob (str: string): boolean {
 // do the staff
}
```

**Comment by dshubhadeep** [comment]
axetroy in which module should I add the function ? Btw the is-glob module also checks for extglob. Should that be added as well ?

**Comment by axetroy** [comment]
@dshubhadeep 
It should be added to `fs` module `glob.ts` file
