### ISSUE TITLE
`io` module is marked deprecated in API doc

### ISSUE THREAD

**Issue by babiabeo** [denoland/deno_std#4249]
**Describe the bug**

Visit https://deno.land/std@0.213.0/io/mod.ts

The `io` module is marked deprecated in API doc although there is no `@deprecated` tag in jsdoc in `mod.ts`.

![screenshot-1706619286174](https://github.com/denoland/deno_std/assets/95457148/c831d6b2-8b3b-4fc1-8353-246938c00041)

**Expected behavior**

It should not be marked deprecated as it was re-introduced in #4128.

**Environment**

N/A

**Comment by iuioiua** [comment]
I agree. The `@deprecated` tag should be removed, and its stability status should be updated in the README.

**Comment by babiabeo** [comment]
> I agree. The `@deprecated` tag should be removed, and its stability status should be updated in the README.

I think we should open an issue for updating modules' stability status.
