### ISSUE TITLE
bug(file_server):clicking filename/dirname makes url absolute path with a 404 code

### ISSUE THREAD

**Issue by yuqingc** [denoland/deno_std#425]
I ran the new file_server example with the --reload flag. There's a bug. When I click one of the file/dir name on the home page, the url becomes the absolute path of my OS, which leads to a 404 of that resource. In line 52 of file_server.ts, the absolute path is passed to the display function, making this error.

**Comment by yuqingc** [comment]
https://github.com/denoland/deno_std/blob/master/http/file_server.ts#L152

**Comment by yuqingc** [comment]
Modifying line 165 should work. I have tested. Should I open a PR for that?

From
```
fn,
```
to 
```
fn.replace(currentDir, ''),
```

**Comment by zekth** [comment]
Which version of Deno are you running? Cannot reproduce on 0.5.0
