### ISSUE TITLE
fmt: warn that `dim` function may not work for all terminals

### ISSUE THREAD

**Issue by scarf005** [denoland/deno_std#4296]
**Is your feature request related to a problem? Please describe.**

Terminals such as konsole do not support [`dim`](https://deno.land/std@0.215.0/fmt/colors.ts?s=dim). This may cause a11y issues when it is used to distinct information from regular text, as both will look identical. It may be prefferable to use [`gray`](https://deno.land/std@0.215.0/fmt/colors.ts?s=gray) instead in such situation.

context:

- https://github.com/lumeland/lume/pull/563#issuecomment-1913556672
- https://github.com/lumeland/lume/pull/563#issuecomment-1925705980

**Describe the solution you'd like**

It'd be helpful to add a warning in docstring that `dim` may not be supported across terminals (e.g konsole). I'm interested in opening a PR when it's accepted.

**Describe alternatives you've considered**

keep them as-is.

**Comment by iuioiua** [comment]
Fair reasoning! A PR would be welcome.
