### ISSUE TITLE
http/file_server: add unix socket option

### ISSUE THREAD

**Issue by vi117** [denoland/deno_std#4302]
[`Deno.serve`](https://deno.land/api@v1.40.4?s=Deno.serve) can serve request with unix sockets after deno 1.39.
Can we add the following option?

```
--unixsock <PATH>: serve request through unix socket
```

**Comment by iuioiua** [comment]
I think this is a reasonable addition. PRs and community feedback are welcome.

**Comment by kt3k** [comment]
I doubt there's use case of it. Why do we want to serve static files via unix socket?

**Comment by iuioiua** [comment]
I'll close this. I now realise this feature doesn't appear to have a use case. Please feel free to re-open if you disagree strongly.
