### ISSUE TITLE
todo(semver): add `parse_range_test.ts` file

### ISSUE THREAD

**Issue by iuioiua** [denoland/deno_std#4309]
This can be done by taking parts of the tests from [`semver/range_test.ts`](https://github.com/denoland/deno_std/blob/main/semver/range_test.ts) and repurposing them just for `parseRange()`.

**Comment by javihernant** [comment]
I'd like to work on this one

**Comment by javihernant** [comment]
Is `semver/range_test.ts` supposed to be `semver/parse_range_test.ts`?

**Comment by iuioiua** [comment]
Completed in #4345.
