### ISSUE TITLE
Adding csv to deno_std

### ISSUE THREAD

**Issue by zekth** [denoland/deno_std#431]
As we have TOML support this is revelant to have CSV.
In golang it's in the encoding csv package: https://golang.org/pkg/encoding/csv/

If we add csv to deno_std, would it be revelant to move TOML to `encoding/toml` ?

note: working on the CSV parser ATM

**Comment by ry** [comment]
All for it. And yes I think that move would be appropriate.

**Comment by zekth** [comment]
> All for it. And yes I think that move would be appropriate.

Will move toml when i'll push CSV so.

**Comment by axetroy** [comment]
How about existing encoding like `json`?

It already has a built-in API for `ECMAScript`, does it need to be added to `encoding` module?

**Comment by zekth** [comment]
@axetroy i don't think so, but XML would be cool too.

**Comment by zekth** [comment]
merged.
