### ISSUE TITLE
todo(semver): add `_shared_test.ts` file

### ISSUE THREAD

**Issue by iuioiua** [denoland/deno_std#4310]
Each exported symbol in [`semver/_shared.ts`](https://github.com/denoland/deno_std/blob/main/semver/_shared.ts) should at least have a simple accompanying test.

**Comment by kt3k** [comment]
I think we should avoid writing test cases for internal utils as far as possible (unless they are extremely complex (such as `assert/_diff.ts`))

**Comment by iuioiua** [comment]
I think we should. Internal utils are used under the hood of the public API symbols. Sometimes, if these internal utils are changed, they can affect public API in non-obvious ways, making troubleshooting difficult.

E.g. I recently tried removing the deprecated `Comparator.semver` property which caused a heap of `std/semver` tests to fail. I spent some time troubleshooting what the issue was but didn't get to the bottom of it. If there were tests for internal utils, the cause of the problem might've been more apparent.

Another reason is that such tests allow us to see the intended behaviour of such internal utils. WDYT?

**Comment by kt3k** [comment]
> Sometimes, if these internal utils are changed, they can affect public API in non-obvious ways, making troubleshooting difficult.

I think this falls in the category of 'very complex utils'. I'm in favor of writing test cases of such utils.

But I'm not in favor of requiring test cases for all internal utils by default. That generally slows down the development and maintenance of code base.

See also:
- https://softwareengineering.stackexchange.com/questions/380287/why-is-unit-testing-private-methods-considered-as-bad-practice
- https://stackoverflow.com/questions/105007/should-i-test-private-methods-or-only-public-ones

**Comment by iuioiua** [comment]
Ok. I understand.
