### ISSUE TITLE
Needs a way to distinguish breaking changes of stable modules and unstable modules in the release note

### ISSUE THREAD

**Issue by kt3k** [denoland/deno_std#4332]
We now have stability concept https://github.com/denoland/deno_std?tab=readme-ov-file#stability

Recently we've made a lot of breaking changes mainly in unstable modules (especially 'semver'). That might have given false feeling of instability of the entire standard library. I think we need a way to distinguish breaking changes in stable modules and unstable modules in the release note.

**Comment by iuioiua** [comment]
I suggest `BREAKING(unstable)` for unstable breaking changes and `BREAKING(stable)` for stable.

**Comment by babiabeo** [comment]
How about adding `stable` and `unstable` labels? I think `actions/labeler` can add them automatically based on the changed module.

**Comment by kt3k** [comment]
> How about adding stable and unstable labels? I think actions/labeler can add them automatically based on the changed module.

Sounds a good idea for indicating PRs unstable/stable

> I suggest BREAKING(unstable) for unstable breaking changes and BREAKING(stable) for stable.

This makes sense as CLI repo does `feat(unstable)` etc. Can we somehow also specify the affected module names?

**Comment by iuioiua** [comment]
Actually, how's `[unstable | stable] BREAKING(<scope>)`?

**Comment by kt3k** [comment]
So the actual commit message would look like: `[unstable] BREAKING(semver): remove Foo API`?

This looks good to me, but I'd prefer to omit `[stable]` if it's from stable module.

**Comment by iuioiua** [comment]
Yep, that sounds fine to me.

**Comment by kt3k** [comment]
Ok. Let's try this pattern for a while

> [unstable] BREAKING(semver): remove Foo API
