### ISSUE TITLE
[Streams] Add CSV separator setting on CsvParseStreamOptions documentation

### ISSUE THREAD

**Issue by pedropaulosuzuki** [denoland/deno_std#4353]
Hello everyone! How are you doing?

I use streams a lot, and being able to pipe decompressionStreams directly into CsvParseStreams are really useful. However, in many times, my files are tab-separated, semicolon-separated or even use some other file separator. I think it would be great to have custom separators on our parseStreams as well.

Currently CsvParseStream lacks a separator option (see <https://deno.land/std@0.216.0/csv/csv_parse_stream.ts?s=CsvParseStreamOptions>), while CsvStringifyStream already presents the option to include a custom separator (see <https://deno.land/std@0.216.0/csv/csv_stringify_stream.ts?s=CsvStringifyStreamOptions>), and so does regular parsing (not stream, see <https://deno.land/std@0.216.0/csv/parse.ts?source>).

I think it is a reasonable feature, if you have any concerns, please let me know! I think Deno STD would greatly benefit from that, mainly on corporate environments, that use the wildest CSVs known to mankind.

Thanks and best regards.

## Edit
When looking around, I found out that CsvParseStreamOptions actually supports a separator. But it wasn't clear to me when reading <https://deno.land/std@0.215.0/csv/csv_parse_stream.ts?s=CsvParseStreamOptions> because it didn't show the extended properties of ReadOptions, and the link to ReadOptions on that page is currently broken, and at my job we don't have an IDE, so I have to write everything in plaintext with no IDE autocomplete, which does not show additional inherited properties. I just found out from reading the source code directly and seeing where it was importing stuff.

I believe we just need to fix the docs to make it more clear then (at <https://deno.land/std@0.215.0/csv/csv_parse_stream.ts?s=CsvParseStreamOptions>). Changing the issue name.

**Comment by pedropaulosuzuki** [comment]
Considering <https://deno.land/std@0.215.0/csv/_io.ts?source>, I believe all of those properties could be listed in <https://deno.land/std@0.215.0/csv/csv_parse_stream.ts?s=CsvParseStreamOptions>, as CsvParseStreamOptions inherits from ReadOptions, which includes all of the below:

```ts
{
    separator?: string,
    comment?: string,
    trimLeadingSpace?: boolean,
    lazyQuotes?: boolean,
    fieldsPerRecord?: number
}
```

**Comment by kt3k** [comment]
Maybe this is a reasonable suggestion. Java's documentation pages, for example, usually list all properties including inherited ones.

Does anyone have any opinion on this?

**Comment by kt3k** [comment]
BTW this is doc website issue, or underlying doc tool issue. This can't be fixed in the standard library.

**Comment by jsejcksn** [comment]
> Maybe this is a reasonable suggestion. Java's documentation pages, for example, usually list all properties including inherited ones.
> 
> Does anyone have any opinion on this?

I'm against this. Expanding all inherited type information can become very difficult to digest, and is precisely the reason that TypeScript offers inheritable named aliases and interfaces to describe shapes. (As an extreme, but possible example: should an expansion be performed for a type which inherits recursively from 20–30 parents?) I think duplicating all fields adds noise, and that a hyperlink (generated from JSDoc) is sufficient — and the broken link definitely needs to be fixed.

**Comment by iuioiua** [comment]
I agree that linking to, rather than expanding, all inherited type information is sufficient. Either way, can you move this issue to the appropriate repo, @kt3k?

**Comment by kt3k** [comment]
Found the issue https://github.com/denoland/deno_doc/issues/136 , which seems suggesting the same thing. Please track this topic there
