### ISSUE TITLE
BufReader's interface is un-idiomatic javascript.

### ISSUE THREAD

**Issue by piscisaureus** [denoland/deno_std#436]
Currently `BufReader.readLine()`, `readSlice()`, `peek()` etc return a Promise resolving to a `[result, BufState]` tuple, where BufState is non-null if an error condition has occurred.

The exact definition of `BufState` is:

```ts
export type BufState =
  | null
  | "EOF"
  | "BufferFull"
  | "ShortWrite"
  | "NoProgress"
  | Error;
```
(Note that some of these BufState values aren't applicable to BufReaders; they're only applicable to BufWriters.)

This may be idiomatic in go (which doesn't have exceptions), but it's highly un-idiomatic in javascript.

I'd propose to change these interfaces as such:
* These functions return a `Promise<T | null>`
* On actual errors, the promise is rejected with an actual Error object.
* On EOF, the promise is resolved with null.
* Otherwise, the promise is resolved with just an Uint8Array or a string.
* The `BufState` type is made private or removed entirely.

cc @ry

**Comment by ry** [comment]
SGTM
