### ISSUE TITLE
link replacement of fs.ensureSymlink()

### ISSUE THREAD

**Issue by ryota2357** [denoland/deno_std#4363]
**Describe the bug**

I have two questions regarding the operation of invalid symlink files.
I thought it was a bug, but I apologize if it is a spec.

In the documentation, `ensureSymlink()` is:
> Ensures that the link exists, and points to a valid file.

When the link exists but the points are invalid, what should `ensureSymlink()` do?

**Steps to Reproduce**

Run the following script.

```ts
import * as fs from "https://deno.land/std@0.216.0/fs/mod.ts";
import * as path from "https://deno.land/std@0.216.0/path/mod.ts";

const cwd = Deno.cwd();

const originalAFile = path.join(cwd, "original_a.txt");
const originalBFile = path.join(cwd, "original_b.txt");
const linkFile = path.join(cwd, "linkfile.txt");

async function reproduce_replaceBroken() {
  await Deno.writeTextFile(originalAFile, "A");
  await Deno.writeTextFile(originalBFile, "B");

  await fs.ensureSymlink(originalAFile, linkFile);
  const expectA = await Deno.readTextFile(linkFile);
  console.log(expectA); // => A

  await Deno.remove(originalAFile);

  await fs.ensureSymlink(originalBFile, linkFile);
  const expectB = await Deno.readTextFile(linkFile); // cause error here.
  console.log(expectB);
}

async function cleanup() {
  await Deno.remove(originalAFile);
  await Deno.remove(originalBFile);
  await Deno.remove(linkFile);
}

await reproduce_replaceBroken();
// await cleanup();
```

**Expected behavior**

I firstly expected `linkFile` to be a valid link and it points to `originalBFile`, because I ensured that  'the link exists, and points to a valid file' with `fs.ensureSymlink(originalBFile, linkFile);`

However, I noticed that if `linkFile` is already a symlink file it does not replace to new link via the `ensureSymlink()` like the following scripts.

```ts
async function reproduce_replaceLink() {
  await Deno.writeTextFile(originalAFile, "A");
  await Deno.writeTextFile(originalBFile, "B");

  await fs.ensureSymlink(originalAFile, linkFile);
  const expectA = await Deno.readTextFile(linkFile);
  console.log(expectA); // => A

  await fs.ensureSymlink(originalBFile, linkFile);
  const expectB = await Deno.readTextFile(linkFile);
  console.log(expectB); // => A
}
```

Therefore, I do not know if this behavior is a bug or a specification.
Also, if this is a spec, I would like to see it mentioned in the documentation because I feel that the meaning of "valid" in the documentation is not clear.

**Environment**

- OS: MacOS 14.3.1
- deno version: 1.40.5
- std version: 0.216.0

**Comment by iuioiua** [comment]
This seems like expected behaviour. I wouldn't expect the function to check the file's existence that the symbolic link is pointing to. That being said, yes, using "valid" is misleading. I think we should remove that word and briefly clarify the behaviour outlined in this issue in the docs. WDYT, @kt3k?

**Comment by kt3k** [comment]
This looks an oversight to me.

> I wouldn't expect the function to check the file's existence that the symbolic link is pointing to.

The code checks if the target path exists, and throws if it doesn't. ref: https://deno.land/std@0.216.0/fs/ensure_symlink.ts?source=#L31

The below example throws, for example
```js
import { ensureSymlink } from "https://deno.land/std@0.216.0/fs/mod.ts";
await ensureSymlink("non-existent", "symlink");
```

I think we should check the symlink is actually pointing the given target file if `Deno.errors.AlreadyExists` is thrown

**Comment by iuioiua** [comment]
Ah, ok. Good point. Yes, I agree.
