### ISSUE TITLE
semver: deprecate `rangeMax` and `rangeMin`

### ISSUE THREAD

**Issue by kt3k** [denoland/deno_std#4365]
`rangeMax` and `rangeMin` were introduced in #3385, but these 2 APIs seem having critical design flaws. I suggest we should deprecate these 2 APIs.

1. In many cases, `rangeMax` returns invalid semvers.

`rangeMax(parseRange("<1.0.0"))` returns 0.∞.∞ (0.Infinity.Infinity).
`rangeMax(parseRange("<1.1.0"))` returns 1.0.∞ (1.0.Infinity).
`rangeMax(parseRange("<0.0.0"))` returns -∞.∞.∞ (-Infinity.Infinity.Infinity).

These values are non semvers. Exposing them are very confusing.

2. `rangeMax` ignores prerelease

`rangeMax(parseRange("<1.2.3-a"))` returns 1.2.2 ignoring prerelease version.

Because of this behavior, the example below returns `false`, which seems a bug, but there's no clear way to fix this.

```js
greaterThan(rangeMax(parseRange("<1.2.3-beta.20")), rangeMin(parseRange(">1.2.3-beta.10")))
```

3. rangeMin ignores prerelease version only when the given range doesn't include prerelease.

`rangeMin(parseRange(">1.2.3"))` return 1.2.4, but actually 1.2.4-0 is smaller than that (and bigger than 1.2.3). On the other hand, `rangeMin(parseRange(">1.2.3-a"))` returns the correct value 1.2.3-a.0, but the switching of the algorithm depending on the input value seems confusing and arbitrary.

---
Note: There's no concern about the compatibility to [`npm:semver`](https://github.com/npm/node-semver) because these APIs are invented by us in #3385.

**Comment by timreichen** [comment]
I agree, this seems very confusing.

Just a thought about 1. for the record:
Maybe this could  be fixed by using something like [MAX_SAFE_INTEGER ](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER) instead of Infinity. But this seems hacky.

**Comment by timreichen** [comment]
In we deprecate these two functions, there is no way to check anymore if a version is bigger/less than a range, because https://github.com/denoland/deno_std/issues/4273 relies on these two as an alternative. Any thoughts?

**Comment by kt3k** [comment]
That sounds a valid point. I think if we deprecate these 2 APIs, we need to re-implement `gtr` `ltr` equivalents without using `rangeMin` and `rangeMax`.

**Comment by iuioiua** [comment]
Can this now be closed?
