### ISSUE TITLE
Log: debug level logs not showing

### ISSUE THREAD

**Issue by danikane** [denoland/deno_std#4383]
**Describe the bug**
Hi, I'm having troubles getting the debug level logs.
https://deno.land/std@0.217.0/log/mod.ts

**Steps to Reproduce**
https://codesandbox.io/p/devbox/zen-fog-qt6kq3?file=%2Findex.ts%3A14%2C1

log.setup as per the docs:
![image](https://github.com/denoland/deno_std/assets/18037666/30cf940e-6ba1-420c-937e-7d34f0890a0c)

**Expected behavior**

A `debug` level message should appear in the console.

**Environment**

- OS: Ubuntu WSL on Windows 10
- deno version: 1.41.0
- std version: 0.217.0

I'm checking through the `log` module code, but I can't put my finger on a possible culprit.

Thanks in advance!

**Comment by javihernant** [comment]
I'm taking a look at this

**Comment by javihernant** [comment]
After some research I have found the issue. It is not a bug. In your code you are not configuring `loggers` which basically means Deno is using the default config. That is, loggers (log.debug(), log.info(), log.warn(), ...) will print only if they are of level `INFO` (20) or above. `log.debug()` has a lower level (10), so it doesn't print. If you want it to print you'll need to set a `DEBUG` level:
```ts
setup({
  handlers: {
    default: new ConsoleHandler("DEBUG"),
  },
  loggers: {
    default: {
      level: "DEBUG",
      handlers: ["default"],
    },
  },
});
```

**Comment by danikane** [comment]
Thanks!
