### ISSUE TITLE
The OS Signals Async iterator example is broken because `std/signal` was removed

### ISSUE THREAD

**Issue by mjz19910** [denoland/deno_std#4389]
**Describe the bug**

**Steps to Reproduce**

1. View [Async iterator example](https://docs.deno.com/runtime/tutorials/os_signals#async-iterator-example)
2. Attempt to run that example
3. `error: Module not found "https://deno.land/std/signal/mod.ts".`

**Environment**

- OS: N/A
- deno version: deno 1.41.0
- std version: >= 0.212.0

**Comment by iuioiua** [comment]
Perhaps that example should just be removed.
