### ISSUE TITLE
proposal(front_matter): fix file names and exports

### ISSUE THREAD

**Issue by timreichen** [denoland/deno_std#4398]
**Is your feature request related to a problem? Please describe.**

front_matters `any.ts` file does not export `any()` but `extract()`. Also, `json.ts`, `toml.ts` and `yaml.ts` all export a function called `extract()`. `mod.ts` on the other hand doesn't re-export any of these.

**Describe the solution you'd like**

I propose to do the following changes to have them behave more like other std implementations:
- rename `any.ts` to `extract.ts`
- rename `json.ts` to `extract_json.ts` and `extract()` to `extractJson()`
- rename `toml.ts` to `extract_toml.ts` and `extract()` to `extractToml()`
- rename `yaml.ts` to `extract_yaml.ts` and `extract()` to `extractYaml()`

**Describe alternatives you've considered**

Leave as is.

**Comment by iuioiua** [comment]
+1

**Comment by timreichen** [comment]
@iuioiua I wonder now, if `parse*()` would make more sense, because the frontmatter data is not just extracted but parsed as well.

**Comment by iuioiua** [comment]
Yeah, maybe. Other opinions are welcome.

**Comment by gabelluardo** [comment]
+1 for `parse` I think it's more correct and intuitive

**Comment by iuioiua** [comment]
I've thought about this further, and `parse()` might be as equally misleading as `extract()`, as the function extracts and then parses the front matter metadata. So perhaps the function names should be something like `extractAndParseJson()`, etc. I'm happy to hear other opinions.

**Comment by iuioiua** [comment]
Yeah, I've changed my mind yet again - `extract` if fine with me.

**Comment by timreichen** [comment]
This would also open the door for `stringify()` and `insert()` at a later point to reverse the process.

**Comment by iuioiua** [comment]
I like that idea, but imagine that others wouldn't due to the disruption. Happy to hear other thoughts.

**Comment by kt3k** [comment]
> This would also open the door for stringify() and insert() at a later point to reverse the process.

I've never seen such needs for front-matter. front-matter is not a general data exchange format, but for annotating documents (typically blog posts) with some metadata.

Generating front-matter from program doesn't make much sense to me.

**Comment by timreichen** [comment]
> > This would also open the door for stringify() and insert() at a later point to reverse the process.
> 
> I've never seen such needs for front-matter. front-matter is not a general data exchange format, but for annotating documents (typically blog posts) with some metadata.
> 
> Generating front-matter from program doesn't make much sense to me.

There is definitely a need for such functionality (https://www.npmjs.com/package/gray-matter has over 1.3m d/w and provides `stringify()` as well).

That aside, there is still a problem with the name, because `extract` is not descriptive enough that the data also is parsed imo. The Parsing aspect seems more prominent to me.

**Comment by iuioiua** [comment]
> That aside, there is still a problem with the name, because `extract` is not descriptive enough that the data also is parsed imo. The Parsing aspect seems more prominent to me.

This is true. `extract` doesn't convey that parsing is also happening.

**Comment by kt3k** [comment]
> This is true. extract doesn't convey that parsing is also happening.

I don't think so. It's implied by `front-matter` which is always parsed. No front-matter tool only extracts front-matter as string, but they also parse it.

**Comment by kt3k** [comment]
I can find many usages of the phrase 'extract front-matter':
- https://docs.rs/extract-frontmatter/latest/extract_frontmatter/
- https://github.com/mrzmmr/remark-extract-frontmatter
- https://github.com/jxson/front-matter

**Comment by iuioiua** [comment]
Regardless of what other packages do, it's not obvious that `extract` implies parsing takes place. Nevertheless, if other packages do use `extract`, then it's likely fine for us to do. I'll close this now as it seems clear that there's not enough consensus for us to proceed with these changes. Either way, thanks for the suggestion, Tim!
