### ISSUE TITLE
proposal(std): standardise JSDoc tag usage

### ISSUE THREAD

**Issue by timreichen** [denoland/deno_std#4408]
**Is your feature request related to a problem? Please describe.**

Observations:

There seem to be multiple formats how jsdocs are written in std. Here three examples:
- `@return`, `@returns`, plain text: `Returns ...`
- `@param` is sometimes present, sometimes missing
- `@private` is sometimes present, sometimes missing

There are invalid tags used:
- `@note`
- `@remarks`

**Describe the solution you'd like**

I think std would benefit in having a fixed guideline which tags are used and which are omitted.

**Describe alternatives you've considered**

Leave as is.

**Comment by timreichen** [comment]
Example of possible solution: https://github.com/denoland/deno_std/pull/4409

**Comment by iuioiua** [comment]
I agree that we JSDocs should be standardised. My thoughts:
1. Use `@returns`. Having `Returns...` in a description is fine too.
2. Always use `@param`.
3. There's no need to use `@private`.
4. Remove the use of invalid tags.
Either way, yes, a guideline of some sort is needed.

**Comment by timreichen** [comment]
How shall we go forward? Could you work out such a guide line?

**Comment by iuioiua** [comment]
I'll write and publish a guideline of some form. I'll let you know once there's something to look at.

**Comment by iuioiua** [comment]
The JSDoc guidelines have been published. See https://github.com/denoland/deno_std/blob/main/.github/CONTRIBUTING.md#documentation. Please feel free to open a new issue for any feedback, and I'd be happy to push #4409. Thank you for the suggestion.
