### ISSUE TITLE
ws module broken

### ISSUE THREAD

**Issue by MarkTiedemann** [denoland/deno_std#441]
https://github.com/denoland/deno_std/pull/430 removed the `conn` property from `ServerRequest` "because it's not used anymore". However, this property is still used in `acceptWebSocket` (see: https://github.com/denoland/deno_std/blob/master/ws/mod.ts#L368). So the `ws` module is broken now.

**Comment by ry** [comment]
Oops. And apparently not tested well.

**Comment by ry** [comment]
We should consider 
https://golang.org/pkg/net/http/#Hijacker
https://github.com/golang/net/blob/f3200d17e092c607f615320ecaad13d87ad9a2b3/websocket/server.go#L73

**Comment by irustm** [comment]
Tell me, please, what have you decided on this issue?

**Comment by josephrocca** [comment]
Not sure it's related to this, but when I try to run the WebSocket demo code in the readme:
```
error: Uncaught SyntaxError: The requested module 'https://deno.land/std/ws/mod.ts' does not provide an export named 'WebSocket'
```

**Comment by irustm** [comment]
waiting..  release deno_std 🙏
