### ISSUE TITLE
Log FileHandler chokes at messages > 4096

### ISSUE THREAD

**Issue by dvv** [denoland/deno_std#4411]
**Describe the bug**
With #4021 it is not possible to rely on std logger.

**Steps to Reproduce**
[see here](https://github.com/denoland/deno_std/pull/4021#issuecomment-1968338173)

**Expected behavior**

Proper sinking of (rather) large messages.

**Environment**

- OS: [ArchLinux]
- deno version: 1.40.4
- std version: 0.217.0

**Comment by kt3k** [comment]
cc @syhol Can you take a look?

**Comment by syhol** [comment]
Sure. I'll spend some time on it this evening

**Comment by syhol** [comment]
Resolved by https://github.com/denoland/deno_std/pull/4415 this should be safe to close.

**Comment by dvv** [comment]
Thanks!
