### ISSUE TITLE
Publish older versions of std to jsr

### ISSUE THREAD

**Issue by kt3k** [denoland/deno_std#4417]
We've published `std@0.210.0` and above versions to jsr, but it's probably useful to publish older version to it to support the migration to jsr better.

**Comment by iuioiua** [comment]
It's important to note the amount of work that's been put into the Standard Library to get it into a form ready for JSR. Much work would have to be done to get just one version of `std` ready for JSR, let alone many.

If the Standard Library aims to improve as time goes on, publishing older versions to JSR means publishing versions that are inferior to the latest version. Older versions will live on peacefully in https://deno.land/std for those who still depend on them for the foreseeable future.

**Comment by kt3k** [comment]
Published 0.198.0 and above for now.
