### ISSUE TITLE
feature request: grapheme-cluster-aware string operations

### ISSUE THREAD

**Issue by kisaragi-hiu** [denoland/deno_std#4425]
**Is your feature request related to a problem? Please describe.**

JavaScript strings are, roughly, sequences of UTF-16 bytes. Due to surrogate pairs, iterating or accessing strings with `str[index]` does not produce codepoints as expected. Thankfully, modern JS has `str.at(index)` for getting individual codepoints as well as string iterator providing individual codepoints, not bytes.

If a programmer wants to iterate through grapheme clusters, though, they're out of luck. Unlike Swift, where grapheme clusters are the basis of its Characters, there are only a few not-quite-maintained sometimes-out-of-date packages providing support for this. From what I can tell:

- There is [@editablejs/breaker](https://www.npmjs.com/package/@editablejs/breaker) (Unicode 14) and the lineage of [grapheme-breaker](https://www.npmjs.com/package/grapheme-breaker).
- There is also [@stdlib/string-split-grapheme-clusters](https://stdlib.io/docs/api/latest/@stdlib/string/split-grapheme-clusters) which seems to be CJS only
- And there is also [split-graphemes](https://github.com/nota/split-graphemes)

This situation is fragmented and not well-maintained. Right now people just do the obvious thing and slowly learning about codepoints and grapheme clusters as they run into edge cases in production. For example, here's [Bluesky developers realizing they're treating #️⃣ on its own as a hashtag as it's `#` plus some more codepoints](https://bsky.app/profile/pfrazee.com/post/3kmjlcds4ie2q). If they had grapheme-wide startsWith this might've been prevented.

**Describe the solution you'd like**

It would be helpful if Deno's standard library includes this useful part of Unicode.

I wish there are grapheme cluster-wise split, indexing, length, perhaps even startsWith, endsWith and matching functions. These might go into /text or possibly even a /string module.

**Describe alternatives you've considered**

This should perhaps be part of the language, but having grapheme-aware string operations in std is still useful now.

**Comment by 0f-0b** [comment]
[It is already part of the language](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Intl/Segmenter).

**Comment by kisaragi-hiu** [comment]
🤦  I should not be opening issues at 3 AM, sorry.
