### ISSUE TITLE
functions in bytes should not be prefixed with "bytes"

### ISSUE THREAD

**Issue by ry** [denoland/deno_std#447]
EG `bytesFindIndex()` ... it should be `findIndex()`
https://github.com/denoland/deno_std/blob/bd46d60ded3197d93a52ede92eba7302df9b4713/bytes/bytes.ts#L5

**Comment by axetroy** [comment]
I will do this.

By the way

Is this directory structure a bit strange? eg `bytes/bytes.ts`

```typescript
import { repeat } from 'https://deno.land/x/bytes/bytes.ts';
```

Should it be reconstituted like this

```typescript
import { repeat } from 'https://deno.land/x/bytes/mod.ts';
```

**Comment by ry** [comment]
> Should it be reconstituted like this

Sure. Also strings/strings.ts
