### ISSUE TITLE
Unknown export '.' for @std/fmt@0.219.1

### ISSUE THREAD

**Issue by vicary** [denoland/deno_std#4480]
**Describe the bug**
When importing `jsr:@std/fmt@0.219.1` I got the following error message:
```
Uncaught TypeError: Unknown export '.' for '@std/fmt@0.219.1'.
  Specifier: jsr:@std/fmt
  Package exports:
 * ./bytes
 * ./colors
 * ./duration
 * ./printf
    at async <anonymous>:1:22
```

**Steps to Reproduce**

1. `deno eval 'import "jsr:@std/fmt@0.219.1"'`

**Expected behavior**

After importing and caching `@std/fmt`, the process exists without any outputs.

**Environment**

- OS: macOS 14.4
- deno version: 1.41.2
- std version: 0.219.1

**Comment by kt3k** [comment]
Currently there's no module level exports for `std/fmt`. You need to use one of:
- `jsr:@std/fmt@0.219.1/bytes`
- `jsr:@std/fmt@0.219.1/colors`
- `jsr:@std/fmt@0.219.1/duration`
- `jsr:@std/fmt@0.219.1/printf`

**Comment by vicary** [comment]
@kt3k it is not immediately obvious with the error message, but thanks for the reply!

**Comment by kt3k** [comment]
Thanks for the feedback. I agree that it's a bit difficult to understand what the error message means. I created an issue about it in Deno CLI repo https://github.com/denoland/deno/issues/22896
