### ISSUE TITLE
suggestion: deprecate `std/encoding/varint`

### ISSUE THREAD

**Issue by iuioiua** [denoland/deno_std#4502]
According to [a GitHub search](https://github.com/search?q=encoding%2Fvarint.ts+AND+NOT+is%3Afork+language%3ATypeScript&type=code&l=TypeScript), the functions in `std/encoding/varint` aren't used anywhere in any meaningful way. I suggest we deprecate and remove `std/encoding/varint`.

**Comment by kt3k** [comment]
@MierenManz Do you know any usage of this module?

**Comment by MierenManz** [comment]
I have some private modules using this functionality. But other than that none that I know of

**Comment by iuioiua** [comment]
Perhaps a 3rd party module might be more fitting then 🙂

**Comment by iuioiua** [comment]
I discussed this with @MierenManz and @kt3k, and we've decided not to deprecate `std/encoding/varint`. It has use cases in sending data over networks and encoding Wasm modules. While it may not be used much at present, it still seems valuable enough to keep around. Thanks for filling us in, Skye.
