### ISSUE TITLE
Add CI stages that use DENO_FUTURE=1

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno_std#4517]
Add a duplicate set of CI stages that run against `canary` version that specify `DENO_FUTURE=1` env var for all `deno` subcommands.

This will help us future-proof and get ready for Deno 2 release.

**Comment by iuioiua** [comment]
I'll get this done soon. Though, [this line](https://github.com/denoland/deno_std/blob/ca6b06b9701f981d7280e0b52047f0ada8fa12b0/webgpu/_test_util.ts#L39) will cause issues once https://github.com/denoland/deno/pull/23095 is merged. Last I heard, Divy was doing some GC work that might mitigate the need for this cleanup logic.

**Comment by bartlomieju** [comment]
Maybe @crowlKats will have an answer how we can fix that?

**Comment by kt3k** [comment]
Maybe we can workaround this for now like the below?

```js
if (Deno.resources) {
  ...
}
```
