### ISSUE TITLE
The web doc of `std@0.220.1/path` downloads the .ts files instead of showing documentation

### ISSUE THREAD

**Issue by LoKy-dev** [denoland/deno_std#4529]
I don't know whether should i post this here on in [deno_doc](https://github.com/denoland/deno_doc), feel free to correct me.

**Describe the bug**
When heading to the doc of the standard library in deno.land in the latest version [0.220.1](https://deno.land/std@0.220.1?doc) and the [path](https://deno.land/std@0.220.1/path/mod.ts) module is clicked to view the documentation, the typescript file is downloaded instead.
When rolling back to [0.220.0](https://deno.land/std@0.220.0?doc) you can see the desired behaviour.

This issue seems to exist only on the path module

https://github.com/denoland/deno_std/assets/71527839/46a20af1-eb3d-4c29-9386-8c1341214918

**Steps to Reproduce**
- Go to [deno.land/std@0.220.1?doc](https://deno.land/std@0.220.1?doc)
- Click on the path module

**Expected behavior**
Open the doc

**Comment by iuioiua** [comment]
Wow, what a strange bug. I wasn't able to reproduce it on Chrome or Safari. Could you please clear your cache and try again?

**Comment by LoKy-dev** [comment]
The issue solved itself on it's own without clearing the cache, i guess it was a fluke from my browser.

If someone is interested to go deeper i was using the Arc Browser `v1.35.0 (47750)` and this was my user agent:
```
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36
```
