### ISSUE TITLE
web doc for `std@0.221.0/collections` missing

### ISSUE THREAD

**Issue by scarf005** [denoland/deno_std#4532]
**Describe the bug**

![image](https://github.com/denoland/deno_std/assets/54838975/462a4cc4-ac11-4d2a-be40-ace9bdd75c51)

**Steps to Reproduce**

1. visit https://deno.land/std@0.221.0/collections/mod.ts
2. the docs are unavailable.
3. visit https://deno.land/std@0.220.1/collections/mod.ts
4. the docs are available.
5. clearing cache does not help.

**Expected behavior**

docs are available regardless of version.

**Environment**

ubuntu 23.10, firefox 125.0b4

**Comment by iuioiua** [comment]
I'm unable to reproduce this. Are you still seeing the issue?

**Comment by scarf005** [comment]
![image](https://github.com/denoland/deno_std/assets/54838975/03d1ab99-1873-4366-90a2-6650a497f732)

it works now. maybe cache issue?

**Comment by iuioiua** [comment]
Yeah, maybe. Either way, thanks for letting us know.
