### ISSUE TITLE
Proposal: Migrate to JSR-oriented codebase

### ISSUE THREAD

**Issue by kt3k** [denoland/deno_std#4544]
We currently [convert](https://github.com/denoland/deno_std/blob/e9a8db202d0b7ba0287f3c09b975bc3b1c21ff0e/_tools/convert_to_workspace.ts) the existing codebase to JSR oriented codebase and publish the exactly the same thing to both [JSR](https://jsr.io/@std) and https://deno.land/std. However this prevents us from doing split versioning of each submodule, and that is the blocker for [stabilization of std](https://github.com/denoland/deno_std/issues/3489) (We don't stabilize the entire standard libary, but we plan to stabilize it module by module gradually).

I think we should migrate to JSR-oriented code base in the near future, but there are some implications by doing that:
- We don't update deno.land/std actively anymore (except security fixes). New features go to `jsr.io/@std`.
  - This is because if we start the split versioning with JSR oriented codebase, it's difficult to convert it back to single-versioned std.
- The releases of CLI and STD are decoupled. CLI release and STD release happen independently.

I personally think we are fine with the above conditions, but does anyone have concerns or objections to it?

related #4600

**Comment by iuioiua** [comment]
As you say, the sooner we make this move, the sooner we can stabilise the Standard Library, and that would be great for everyone. I'm very much for this.

To me, workspaces support in both JSR and the Deno runtime are sufficiently established for the change. I haven't had any issues with workspaces functionality so far. However, others may disagree.

CC @ry and @rbetts

**Comment by iuioiua** [comment]
The following PRs must be merged right before the JSR cutover:
- [ ] #4642 
- [ ] #4643 
- [ ] #4644

**Comment by kt3k** [comment]
> We plan to do this migration right after Deno CLI 1.43 release (which is scheduled on 4/24).

JSR cutover didn't happen yet because CLI 1.43 release was postponed to the next week because of performance issue
