### ISSUE TITLE
csv - parse takes undefined opt

### ISSUE THREAD

**Issue by dsherret** [denoland/deno_std#4545]
Kind of confusing that the `opt` parameter here is `opt?: undefined`:

https://github.com/denoland/deno_std/blob/74fc8ff920991c4c79fa4c7647d855e5780db64c/csv/parse.ts#L326

...shouldn't that just not exist given the other overloads?

**Comment by fdemir** [comment]
Should we remove the opt?: undefined from this overload?

**Comment by dsherret** [comment]
Yeah, I think it should just be `export function parse(input: string): string[][];`

**Comment by Wencho8** [comment]
I can work on this. Removing the extra comments and the opt parameter.

**Comment by iuioiua** [comment]
Completed in #4598

**Comment by dandv** [comment]
Not sure what the status of this is, but I'm giving Deno a first try with a simple task: manipulate a CSV. Trying to figure out the parameters for `parse` in WebStorm is tricky, because the options object doesn't seem to be documented (only `input` is), but is used in the example:

![image](https://github.com/denoland/deno_std/assets/33569/afa4de9e-ad96-4f95-81d8-23680483e90a)

I'm using jsr:@std/csv@^0.224.1.

**Comment by BlackAsLight** [comment]
> Not sure what the status of this is, but I'm giving Deno a first try with a simple task: manipulate a CSV. Trying to figure out the parameters for `parse` in WebStorm is tricky, because the options object doesn't seem to be documented (only `input` is), but is used in the example:
> 
> ![image](https://private-user-images.githubusercontent.com/33569/333771034-afa4de9e-ad96-4f95-81d8-23680483e90a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2OTgwOTQsIm5iZiI6MTcxNjY5Nzc5NCwicGF0aCI6Ii8zMzU2OS8zMzM3NzEwMzQtYWZhNGRlOWUtYWQ5Ni00Zjk1LTgxZDgtMjM2ODA0ODNlOTBhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI2VDA0Mjk1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQzNjVkNDY0YzFhMmM1ZTQ1OGE2MjgyNDNkYWMzYzc2YWE4MzFkNTU5YWZhZGFiNmJkMWI3YzJhZWU1N2MyNGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.D7K4S23AkIPtu36QCE3YCa1M4nfQxWyEwQJphh42XVY)
> 
> I'm using jsr:@std/csv@^0.224.1.

Looking at the [documentation](https://jsr.io/@std/csv/doc/~/parse), parse has two overloads, with `opt` being a generic type that extends [`ParseOptions`](https://jsr.io/@std/csv/doc/~/ParseOptions). Why `opt` isn't a `Partial<ParseOptions>` is unknown to me.

**Comment by iuioiua** [comment]
Re-opening this issue. It's weird that `parse()` is generic and could be cleaned up and documented better.
