### ISSUE TITLE
0.222.0 introduced breaking std/log behavior

### ISSUE THREAD

**Issue by roj1512** [denoland/deno_std#4571]
The following example:

https://deno.land/std@0.222.0/log/mod.ts#example_0

Used to output to the console in 0.221.0, but no more since 0.222.0.

**Comment by roj1512** [comment]
This commit introduced the issue: https://github.com/denoland/deno_std/commit/42df58a2331f6c028d71a2082809583793ee2442

**Comment by kt3k** [comment]
@roj1512 Thanks for your quick report!

**Comment by babiabeo** [comment]
https://github.com/denoland/deno_std/blob/42df58a2331f6c028d71a2082809583793ee2442/log/console_handler.ts#L59-L61

I think this change caused the `log` method to not be called from `BaseHandler.handle()`, which in turn resulted in no output to the console.

**Comment by iuioiua** [comment]
This was fixed in the latest 0.220.1 release.
