### ISSUE TITLE
suggestion: add hexdump format for `ArrayBuffer`

### ISSUE THREAD

**Issue by halvardssm** [denoland/deno_std#4583]
**Is your feature request related to a problem? Please describe.**

It would be a good addition to the standard library to have an ArrayBuffer to hexdump formatted. There is a value in having this in the std as it reduces the use of third party libraries, as well as providing potential debugging or utility benefits for internal and external code.

I could create a PR for this, but would want input on where to place it.

**Describe the solution you'd like**

Add a hexdump formatted in the standard library. At a glance, potential locations could be `fmt` or `bytes`.

The function signature could be in the form of:

```ts
function hexdump(buffer: ArrayBufferView): string
```

The output would have this format:

```
00000000  30 31 32 33 34 35 36 37  38 39 41 42 43 44 45 46  |0123456789ABCDEF|
00000010  0a 2f 2a 20 2a 2a 2a 2a  2a 2a 2a 2a 2a 2a 2a 2a  |./* ************|
00000020  2a 2a 2a 2a 2a 2a 2a 2a  2a 2a 2a 2a 2a 2a 2a 2a  |****************|
```

**Describe alternatives you've considered**

- Keep using 3rd party libraries

**Comment by iuioiua** [comment]
Like [`encodeHex()`](https://jsr.io/@std/encoding/doc/hex/~/encodeHex)?

**Comment by halvardssm** [comment]
Not really, that function only encodes to hex, it does not create a format for debugging as above.

**Comment by kt3k** [comment]
> Keep using 3rd party libraries

Which 3rd party libs do you use now?

**Comment by halvardssm** [comment]
None at the moment. I didn't find one I wanted to use since I wanted to keep 3rd party deps to a minimum, so I just created my own. 

Here are some that I considered:

- https://www.npmjs.com/package/hexy
- https://deno.land/x/bytes_formater@v1.4.0

**Comment by kt3k** [comment]
Maybe let's start with a minimal set of options.

> `00000000  30 31 32 33 34 35 36 37  38 39 41 42 43 44 45 46  |0123456789ABCDEF|`

I think the use of vertical bar can be confusing. How about following the output format of `hexy`?

> `function hexdump(buffer: ArrayBufferView): string`

Probably we should also support `ArrayBuffer` input? Some of Web APIs (such as Web Crypto API) return `ArrayBuffer` instead of `ArrayBufferView`

**Comment by halvardssm** [comment]
I chose the vertical bars since they align with the output from the `hexdump` command, and honestly I like it more than the `hexy` format. 

```
➜  dev echo "Hello World" > hdfile
➜  dev hexdump -C hdfile          
00000000  48 65 6c 6c 6f 20 57 6f  72 6c 64 0a              |Hello World.|
```

Good idea, lets support both. Any other interface we should also support?

**Comment by halvardssm** [comment]
Can I create a PR, or is there still room for discussion regarding the function?

**Comment by iuioiua** [comment]
It seems unlikely that the average Standard Library consumer would ever need this. I'm not for having this in the Standard Library, but I think it'd be a great fit for a third-party module.

**Comment by kt3k** [comment]
Golang has `Dump` in `encoding/hex` which does almost the same thing. https://pkg.go.dev/encoding/hex#Dump

**Comment by iuioiua** [comment]
We discussed this internally and thought such an API would be best in a third-party module rather than the Standard Library. Either way, thank you for the suggestion, @halvardssm! Let us know if you end up publishing 🙂
