### ISSUE TITLE
todo: split `toml/test.ts` into separate files

### ISSUE THREAD

**Issue by iuioiua** [denoland/deno_std#4593]
[`toml/test.ts`](https://github.com/denoland/deno_std/blob/2584aa7d5cd79f447cf474b18df74a3ea38c738a/toml/test.ts) has tests for both `toml.parse()` and `toml.stringify()`. These tests should instead exist within `toml/parse_test.ts` and `toml/stringify_tests.ts` files.

Note: There is already a `toml/parse_test.ts` file. After the split, one should ensure that there are no duplicate tests within `toml/parse_tests`.

**Comment by Wencho8** [comment]
Hello! i would like to handle this one!. Could you assign this issue to me?

**Comment by elizasorber** [comment]
Hi, @iuioiua ! I'm a college student looking to make my first contribution. Can I work on this issue?

**Comment by iuioiua** [comment]
@elizasorber, yep! Feel free to let me know if you need any assistance 🙂
