### ISSUE TITLE
[http/file_server] Show local network IP

### ISSUE THREAD

**Issue by nicolo-ribaudo** [denoland/deno_std#4597]
**Is your feature request related to a problem? Please describe.**

When developing with a local file server, it's often useful to be able to connect to it from other devices (for example, to test how a website looks on mobile). `file_server ./path` only gives me the localhost address, and I have to check in ifconfig to find my IP address:

```
➜ file_server .
Listening on http://localhost:4507/
```

**Describe the solution you'd like**

Vercel's `server` prints this output:
```
➜ npx serve .
(node:30004) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)

   ┌────────────────────────────────────────────┐
   │                                            │
   │   Serving!                                 │
   │                                            │
   │   - Local:    http://localhost:3000        │
   │   - Network:  http://192.168.178.40:3000   │
   │                                            │
   │   Copied local address to clipboard!       │
   │                                            │
   └────────────────────────────────────────────┘
```

It's be great if `file_server` showed the "Network" IP too.

**Describe alternatives you've considered**

**Comment by iuioiua** [comment]
This is a valid use case. However, finding and printing the network address of the current machine seems out of scope for `std/http/file_server`. The reason is that network interfaces vary across machines and OSs. Instead, I think we should provide an example in the documentation that shows how [`Deno.networkInterfaces()`](https://deno.land/api?s=Deno.networkInterfaces) can be used with `Deno.serve()`'s [`onListen()`](https://deno.land/api?s=Deno.ServeOptions#prop_onListen) option to print the current machine's network address.

**Comment by lucacasonato** [comment]
@iuioiua Many other file serving tools do this. For example `serve` and `vite dev` both print the local network interface when starting up. I think we should also do this in when running `deno run -A jsr:@std/http/file_server`. It's a very trivial change for us, and it improves user experience. I think we should do it.

**Comment by iuioiua** [comment]
Okay, fair points. Would it be worth making this default `onListen()` behaviour for `Deno.serve()` instead?

**Comment by lucacasonato** [comment]
No, I don't think so. This is particularly useful when running a development server like is common with the file_server tool

**Comment by kt3k** [comment]
Now the core team seems strongly against this addition..

**Comment by nicolo-ribaudo** [comment]
Oh, that's unfortunate. I have been using this since it was released, and it has been incredibly useful when developing across multiple devices (mostly for testing on mobile).

**Comment by iuioiua** [comment]
To elaborate, the core team is against having this be included in default behavior, as it requires the user to use the `--allow-sys` permission flag. #5540 aims to improve the situation by making this behavior easily opt-in.
