### ISSUE TITLE
proposal: stabilize `std/bytes`

### ISSUE THREAD

**Issue by iuioiua** [denoland/deno_std#4629]
This is the first proposal to stabilize a package within the Standard Library, so let's aim to improve the process. This process depends on first fully transferring the Standard Library to [JSR](https://jsr.io/). This issue is meant for tracking and discussing making the package stable.

Requirements:

- [x] 100% documented, passing deno doc --lint checks and adhering to the [documentation guidelines](https://github.com/denoland/deno_std/blob/main/.github/CONTRIBUTING.md#documentation).
- [x] Maximum possible test coverage
- [x] No open issues or pull requests that might lead to breaking changes. For example, issues that suggest new non-breaking features are fine to exist at stabilization.
- [x] Release `1.0.0-rc.1`, approved by 2 members of the internal team.
- [ ] Feedback month (May 7 - June 7)
- [ ] (Scheduled June 7) Stabilization

Blockers:

- [x] #3603

**Comment by kt3k** [comment]
the stabilization process follows these steps https://github.com/denoland/deno_std/issues/4661
