### ISSUE TITLE
proposal: publish release candidate before stabilization

### ISSUE THREAD

**Issue by kt3k** [denoland/deno_std#4661]
I'd suggest the below steps for the package stabilization process:

- We publish 1.0.0-rc.1 (release candidate 1) after 2 maintainers approved it.
- We announce to the community and the core team that we publish 1.0 after 1 month.
  - (For the core team, add calendar entry of the stabilization date)
- Wait 1 month for feedbacks.
- Handle feedbacks, if any.
- If there's no issue after pre-defined amount of time, we publish 1.0
  - If there's unresolved issue remaining, we move the stabilization date forward or cancel it (depending on the situation).

**Comment by iuioiua** [comment]
Great idea. I'm in support. Though, I'd still like to have at least one other core team member be part of this whole process.

**Comment by iuioiua** [comment]
@kt3k, can you please document this process in https://github.com/denoland/deno_std/blob/main/README.md#stabilization ?
