### ISSUE TITLE
Unnecessary JSR Exports Across Packages

### ISSUE THREAD

**Issue by aarvinr** [denoland/deno_std#4663]
**Describe the bug**

A large portion (possibly all) of the `@std/` JSR packages unnecessarily export multiple files, even though all exports are re-exported in `./mod.ts`. For example, as shown in `@std/cli`:

deno.json
```json
{
  "name": "@std/cli",
  "version": "0.224.0",
  "exports": {
    ".": "./mod.ts",
    "./parse-args": "./parse_args.ts",
    "./prompt-secret": "./prompt_secret.ts",
    "./spinner": "./spinner.ts",
    "./unicode-width": "./unicode_width.ts"
  }
}
```

./mod.ts
```ts
export * from "./parse_args.ts";
export * from "./prompt_secret.ts";
export * from "./spinner.ts";
export * from "./unicode_width.ts";
```

**Steps to Reproduce**

N/A

**Expected behavior**

Only the export for the primary `./mod.ts` file should be present.

```json
{
  "name": "@std/cli",
  "version": "0.224.0",
  "exports": {
    ".": "./mod.ts",
-   "./parse-args": "./parse_args.ts",
-   "./prompt-secret": "./prompt_secret.ts",
-   "./spinner": "./spinner.ts",
-   "./unicode-width": "./unicode_width.ts"
  }
}
```

**Environment**

- OS: N/A
- deno version: N/A
- std version: 0.224.0

**Comment by andrewthauer** [comment]
This is on purpose I believe. It allows a consumer of the library to only import a subset of the package for usage. This can have a decent performance benefit by only importing code that is required. I personally don't see any downsides to this only upsides.

**Comment by aarvinr** [comment]
> This is on purpose I believe. It allows a consumer of the library to only import a subset of the package for usage (if desired). This can have a decent performance benefit by only importing code that is required. I personally don't see any downsides to this only upsides.

Oh OK, didn't think about that but I guess it makes sense.
