### ISSUE TITLE
suggestion: move `std/fmt/colors` to `std/cli/styles`

### ISSUE THREAD

**Issue by iuioiua** [denoland/deno_std#4676]
I suggest moving/renaming `std/fmt/colors` to `std/cli/styles` for the following reasons:
1. The module contains functionality for more than just colors. I.e. `italic()` and `bold()`. Hence, the rename to `styles`.
2. The module's functionality is only concerned with console output. Hence, the move to `std/cli`.
This new name would make far more sense than it currently does and be much more accurate.

This is a continuation of the conversation happening in #4326.

**Comment by andrewthauer** [comment]
What about `std/cli/ansi` instead?

**Comment by iuioiua** [comment]
> What about `std/cli/ansi` instead? 

We think `std/cli/styles` would be better. See https://github.com/denoland/deno_std/issues/4326#issuecomment-2092015391
