### ISSUE TITLE
[feature request(collections)] add `invert`

### ISSUE THREAD

**Issue by scarf005** [denoland/deno_std#4686]
**Is your feature request related to a problem? Please describe.**

introduce `invert` and `invertBy` function similar to [lodash](https://lodash.com/docs/4.17.15#invert).

**Describe the solution you'd like**

```ts
/**
 * @example
 * ```ts
 * invert({ a: 1, b: 2 }) // { 1: 'a', 2: 'b' }
 * invert({ a: 1, b: 1, c: 1 }) // { 1: 'c' }
 * ```
 */
export function invert<K extends keyof never, V extends keyof never>(
  obj: Record<K, V>
): Record<V, K> {
  return Object.fromEntries(Object.entries(obj).map(([key, value]) => [value, key]))
}

```

**Describe alternatives you've considered**

keeping it as-is, but it's often useful to invert keys and values of object (similar to how `mapKeys` and `mapValues` are used a lot)

**Comment by iuioiua** [comment]
Can you please provide some use cases?

**Comment by iuioiua** [comment]
Those are good reasons. +1 from me.

**Comment by iuioiua** [comment]
Completed in #4710.
