### ISSUE TITLE
Wanted: installer

### ISSUE THREAD

**Issue by ry** [denoland/deno_std#471]
```
deno run -A https://deno.land/std/installer/install.ts
```
a program which installs itself into your $PATH. It will walk your $PATH, find a writable directory, writing a new shell script into it called `$PATH/deno_install`

The shell script will look like this:
```sh
#!/bin/sh
deno run -A https://deno.land/std/installer/bin.ts $@
```
So now people can run this:
```
deno_install file_server https://deno.land/std/http/file_server.ts --allow-write --allow-net
```
This will create a new executable shell script called `$PATH/file_server`, which would have the following contents:
```sh
#!/bin/sh
deno run --allow-write --allow-net https://deno.land/std/http/file_server.ts $@
```

**Comment by bartlomieju** [comment]
This is super useful! I'll work on that

**Comment by zaynv** [comment]
It would be cool if this could just be a part of the `deno` program itself since subcommands are used now maybe something like 

```
deno install file_server https://deno.land/std/http/file_server.ts --allow-write --allow-net
```

**Comment by bartlomieju** [comment]
@zaynv this will most likely happen after we land it here. I shall have prototype before end of weekend

**Comment by bartlomieju** [comment]
It looks like [denoget](https://github.com/syumai/denoget) already does most of the stuff described in the issue. 

Maybe we could import it into std and change some things (no need for wget and update directory selection).

CC @syumai @ry

**Comment by bartlomieju** [comment]
> a program which installs itself into your $PATH. It will walk your $PATH, find a writable directory, writing a new shell script into it called `$PATH/deno_install`

Should we select first writeable dir? How about keeping it all in one place and using `~/.deno/bin` for that purpose? 

Also we should take a moment to figure out how to go about updating and/or reloading of installed scripts

**Comment by ry** [comment]
~/.deno/bin sounds good to me

**Comment by syumai** [comment]
Thanks @bartlomieju !
I think what [denoget](https://github.com/syumai/denoget) does is almost same as @ry says.

Usage of denoget:

```
denoget https://deno.land/std/http/file_server.ts
```

This command creates files below:

1.)
path: ~/.deno/denoget/src/file_server.ts
content: `import 'https://deno.land/std/http/file_server.ts';`

2.)
path: ~/.deno/denoget/bin/file_server (shell script)
content: `deno --allow-all /Users/syumai/.deno/denoget/src/denoget.ts $@`

If you add ~/.deno/denoget/bin into $PATH, you can execute file_server directly.

The reason why denoget uses wget is to read shebang of target script.
denoget adds launch options like --allow-net --allow-write to generated shell script.
To determine which options to add, denoget reads shebang of target script like this:

[example script](https://github.com/syumai/denoget/blob/master/denoget.ts)
```ts
#!/usr/bin/env deno --allow-all
```

deno's fetch doesn't support redirect, so I couldn't read shebang from script using redirect server like `deno.land/x`.

I'm okay to remove this feature if I would add denoget into std.

**Comment by syumai** [comment]
In Go's way,
* `go get <script>` installs script.
* `go get -u <script>` updates and installs script.

These behaviors may be helpful to decide command name ;)
* `deno get / install <script>`
* `deno get / install -r <script>` // This flag has consistency with deno's original refreshing option.

**Comment by ry** [comment]
Let’s just call it “deno install” for now. I think “deno fetch” and “deno get” are confusing next to each other.

**Comment by bartlomieju** [comment]
> This command creates files below:
> 
> 1.)
> path: ~/.deno/denoget/src/file_server.ts
content: import 'https://deno.land/std/http/file_server.ts';
> 
> 2.)
> path: ~/.deno/denoget/bin/file_server (shell script)
> content: deno --allow-all /Users/syumai/.deno/denoget/src/denoget.ts $@

I think 1) can be skipped and included directly in 2)

> If you add ~/.deno/denoget/bin into $PATH, you can execute file_server directly.

We can automate it

> The reason why denoget uses wget is to read shebang of target script.
denoget adds launch options like --allow-net --allow-write to generated shell script.
> To determine which options to add, denoget reads shebang of target script like this:

Can you elaborate? Won't `fetch` allow to read content of file after redirects?

Re: installation `deno install`, `deno install --update` and `deno uninstall` should handle what we need :+1:

@syumai let's get PR going and iterate in there, I'll help out

**Comment by syumai** [comment]
> I think 1) can be skipped and included directly in 2)

Yes, this can be

```
content: deno --allow-net https://deno.land/std/http/file_server.ts $@
```

directly.

> Can you elaborate? Won't fetch allow to read content of file after redirects?

Maybe what I should try is to implement feature of this TODO comment.
https://github.com/denoland/deno/blob/master/js/fetch.ts#L246

> @syumai let's get PR going and iterate in there, I'll help out

Thanks! I'm going to start doing it this week ;)

What I'm going to do:
1. Fix redirect of deno fetch
2. Create PR to add `installer` to std (based on denoget)
Is this ok? If it is, I start doing it. @bartlomieju

**Comment by bartlomieju** [comment]
Sure, you can start with `installer` to get the ball rolling and we'll figure out fetch in the meantime

**Comment by syumai** [comment]
OK, then I create a PR to std first.

**Comment by syumai** [comment]
@bartlomieju @ry I created a PR 🙏 
https://github.com/denoland/deno_std/pull/488
