### ISSUE TITLE
assertStrictEquals(-0, +0) should not throw

### ISSUE THREAD

**Issue by rherrmann** [denoland/deno_std#4714]
**Describe the Bug**
According to the _[Strict Equality Comparison Algorithm](https://262.ecma-international.org/6.0/#sec-strict-equality-comparison)_ of the Javascript standard, -0 and +0 are considered equal.

Assuming that `assertStrictEquals` is meant to assert equality in the sense of `actual === expected`, it should not throw when passing -0 and +0 for `actual` and `expected`.

**Steps to Reproduce**
```ts
import { assert, assertStrictEquals } from "https://deno.land/std@0.224.0/assert/mod.ts";

assert(-0 === +0); // passes
assertStrictEquals(-0, +0); // fails
```
**Expected Behavior**
`assertStrictEquals(-0, +0)` should not throw.

**Environment**
- OS: macOS
- deno version: 1.43.2
- std version: 0.224

**Comment by kt3k** [comment]
Note: In Node.js, +0 and -0 are not equal with `assert.strictEqual` assertion. I'm not sure the suggested behavior is expected

**Comment by iuioiua** [comment]
That's a fair point. Should we adhere to ECMA's definition of strict equality (`===`) or mimic Node's implementation, which uses [`Object.is()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/is)?

**Comment by kt3k** [comment]
Jest and Vitest also follow what Node.js does. The below examples throw in jest and vitest:

Jest
```ts
expect(+0).toStrictEqual(-0);
```

Vitest
```ts
import { expect, test } from 'vitest'
expect(+0).toStrictEqual(-0);
```

**Comment by iuioiua** [comment]
Ok. I'll revert and instead add a note explaining the behavior.

**Comment by iuioiua** [comment]
> fix(assert): handle `assertStrictEquals(-0, +0)` correctly #4715

See #4718
