### ISSUE TITLE
proposal: stabilize `std/assert`

### ISSUE THREAD

**Issue by iuioiua** [denoland/deno_std#4717]
Requirements:

- [x] 100% documented, passing deno doc --lint checks and adhering to the [documentation guidelines](https://github.com/denoland/deno_std/blob/main/.github/CONTRIBUTING.md#documentation).
- [x] Maximum possible test coverage
- [x] No open issues or pull requests that might lead to breaking changes. For example, issues that suggest new non-breaking features are fine to exist at stabilization.
- [x] Publish `1.0.0-rc.1`
- [ ] Wait 1 month for feedbacks
- [ ] Publish `1.0.0`

Blockers:
- [x] #4716
- [ ] #3771
- [x] #3513

Towards #4600

**Comment by kt3k** [comment]
I don't think #3771 is a blocker as it's a bug, not a design issue.
