### ISSUE TITLE
proposal: stabilize `std/internal`

### ISSUE THREAD

**Issue by iuioiua** [denoland/deno_std#4739]
Requirements:

- [x] 100% documented, passing deno doc --lint checks and adhering to the [documentation guidelines](https://github.com/denoland/deno_std/blob/main/.github/CONTRIBUTING.md#documentation).
- [x] Maximum possible test coverage

This is to unblock dependents from being stabilized, so we're skipping 1.0.0-rc.1 and going straight to 1.0.0.

Towards #4600

**Comment by timreichen** [comment]
Std/internal has `diff()` and `diffstr()`. Is there a reason why they are abbreviated and not written out?

**Comment by iuioiua** [comment]
What a "diff" is is common knowledge. I don't think anyone's had any issues understanding it, nor do I think anyone will. If we do, we can reconsider, but it's fine.

**Comment by timreichen** [comment]
> What a "diff" is is common knowledge. I don't think anyone's had any issues understanding it, nor do I think anyone will. If we do, we can reconsider, but it's fine.

Ok, but there are `datetime/difference.ts` and `semver/difference.ts` which are written out, and commonly WebApis do not use abbreviations (`Set.prototype.difference()`, `Set.prototype.symmetricDifference()`). Just thinking about consistency across multiple modules and apis.
