### ISSUE TITLE
Add crypto module

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno_std#48]
SHA1 is required for #29

**Comment by hayd** [comment]
I think the way to do this is including webcrypto via gn in main deno.

**Comment by sh7dm** [comment]
I'll try to make simple sha1 hash function in TS.

**Comment by hayd** [comment]
See e.g. https://github.com/keroxp/deno-ws/blob/master/crypt.ts

**Comment by 89z** [comment]
https://github.com/denoland/deno/issues/1891
https://github.com/denoland/deno/issues/2372
https://github.com/denoland/deno/issues/6712
https://github.com/denoland/deno/issues/8006

https://github.com/denoland/deno_std/issues/48
