### ISSUE TITLE
multiple entrypoint doesn't make sense for `regexp`, and `jsonc`

### ISSUE THREAD

**Issue by kt3k** [denoland/deno_std#4802]
These ~~3~~ 2 packages only have single API, but have multiple entrypoint `.` and `<API_name>`. Having 2 entrypoint doesn't make much sense to them.

**Comment by iuioiua** [comment]
I believe that's for the likely event that APIs are added to these packages—we don't need to factor out the existing APIs into separate files, as they're already there. However, I see your point, too.

**Comment by kt3k** [comment]
We decided to keep the current structure as is. This structure makes the future contribution easier.
