### ISSUE TITLE
proposal: drop `archive`, `datetime`, `log`, and `webgpu` from the first stabilization targets

### ISSUE THREAD

**Issue by kt3k** [denoland/deno_std#4804]
I suggest we drop these 4 from the first stabilization targets.

- `archive` should be stabilized after Web Stream API support
- It is likely that most of `datetime` APIs will be deprecated after Temporal is available. We should consider the stabilization after that
- There seem no design consensus on `log`
- WebGPU APIs are unstable in CLI. It doesn't make sense to stabilize `std/webgpu` in std.

**Comment by iuioiua** [comment]
I agree that we should remove them from the list for now in #4600, but document the reasoning.

**Comment by iuioiua** [comment]
Actually, few thoughts.
- Arguably, the Streams API support in `@std/archive` should be a non-breaking feature. Meaning it might be fine to stabilize asynchronously.
How long will it be before the Temporal API is widespread enough to justify its removal from the Standard Library?
- I still wonder about the fundamental idea(s) of `@std/log`. I see the use of file logs, but not much else outside of that.
- We should clarify that `@std/webgpu` will be stabilized after the WebGPU API is stabilized. It's more a matter of when.

**Comment by timreichen** [comment]
I think there is some functionality that Temporal doesn't replace, for example parsing localized formats: https://tc39.es/proposal-temporal/docs/strings.html#why-doesnt-temporal-support-parsing-localized-formats-like-mmddyy

So I am not sure if `datetime` can and should be removed once Temporal usage is established.

**Comment by kt3k** [comment]
> Arguably, the Streams API support in @std/archive should be a non-breaking feature. Meaning it might be fine to stabilize asynchronously.

Don't `TarStream` and `UntarStream` (suggested in #4548) overlap with the existing `Tar` and `Untar`? I'm not sure stabilizing both make sense

**Comment by iuioiua** [comment]
@kt3k, are you suggesting that we replace `Tar` and `Untar` with `TarStream` and `UntarStream`, respectively?

**Comment by kt3k** [comment]
I think that was an original plan

**Comment by iuioiua** [comment]
Sounds good.
