### ISSUE TITLE
bug: `DeadlineError` calls `super("Deadline")` in constructor

### ISSUE THREAD

**Issue by iuioiua** [denoland/deno_std#4822]
This means the `error.message` property is just "Deadline". That does not provide any insight into why the error was thrown. A second parameter which would provide information on how, and after how long, the deadline was met.

**Comment by kt3k** [comment]
Closing as `DeadlineError` is now replaced with `DOMException` (TimeoutError) https://github.com/denoland/deno_std/pull/5058
