### ISSUE TITLE
assertStrContains and assertArrayContains

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno_std#484]
IMO, Both of these should be better aligned to current ES and shouldn't be seperate functions, but the same overloaded function. Also the array variant should allow a single item to be searched, versus only matching on an array:

```ts
function assertIncludes(actual: string, expected: string, msg?: string): void;
function assertIncludes(actual: unknown[], expected: unknown | unknown[], msg?: string): void;
function assertIncludes(
  actual: string | unknown[],
  expected: string | unknown | unknown[],
  msg?: string
): void {
 // ...
}
```

**Comment by thefliik** [comment]
#491 may (?) be another approach to this same issue.

**Comment by zekth** [comment]
Agree for the renaming.

About the separates functions i've focus on the Jest implementations, see: https://jestjs.io/docs/en/expect.html

I don't think it's better to have it just one function. It's more a philosophy question than a technical one.

**Comment by thefliik** [comment]
In a test, I could see value in being more explicit. Is it possible for someone to think they were testing an array, but actually a string gets passed and the test still passes? Typescript reduces the likelihood of this, but I imagine it could still be possible with some poorly typed code.

**Comment by kitsonk** [comment]
> Is it possible for someone to think they were testing an array, but actually a string gets passed and the test still passes?

No.  Both the left and right would have to be strings.  Or the left would have to be an array containing strings and the right would be a string which is actually contained in wholly as a value in the left.  You would have to a) not be using TypeScript and b) make some really really big logic errors.  So why encumber everyone for what is a really odd and unlikely edge case?

**Comment by thefliik** [comment]
> You would have to a) not be using TypeScript and b) make some really really big logic errors

Well that's an exaggeration. Many people and libraries make use of `any`, which could easily eliminate the type safety and prevent the error from being noticed. Alternatively, someone could be make use of a javascript library that had inaccurate typings made for it. In short, someone could make a mistake.

> So why encumber everyone for what is a really odd and unlikely edge case

I guess the central difference between us is the benefit this change provides. I was actually liking the suggestion originally, until I saw `@zekth's` comment. To me, it's such a minor difference that any potential downside seems non-worthwhile. But clearly you're bothered by the current setup more so I can see why the scale tips differently for you.

Anyway, there is precedent for your suggestion: https://www.chaijs.com/api/bdd/#method_include. As `@zekth` said, it's probably more a philosophical question than a practical one.
