### ISSUE TITLE
More fetch-like http server interface?

### ISSUE THREAD

**Issue by mrkurt** [denoland/deno_std#485]
I'd like to submit a PR to make the http server more fetch like. The biggest gap right now is the `url` property, `ServerRequest` just gives the pathname + querystring, `Request` is the full URL including protocol and hostname.

I'm guessing there are more fiddly differences, but so I'd like to fix that ^^ plus whatever else doesn't match. Is that a reasonable change?

**Comment by ry** [comment]
SGTM
