### ISSUE TITLE
Reconsider the default port number of @std/http/file-server

### ISSUE THREAD

**Issue by kt3k** [denoland/deno_std#4853]
Is the default port number (`4507`) of http/file-server reasonable?

How about making this number something easier to remember, such as `3000`, `4500`, etc?

---

Note: the default port number initially was `4500` (https://github.com/denoland/deno_std/commit/c5cc6959705c310f4f7a864d77aae54171707c04#diff-106086daad2313990285a9c61085eeb5995d479127db151e613f84ea709450c8R4 ) and it's been changed to `4507` at this commit (https://github.com/denoland/deno_std/commit/c8da66cb747abf8ace1a32624a0057a25039579e#diff-ec9b316c0036849e29e9b20463b071c9bb75f638f05b31a78bcd7bc29bc471bcR40 ). There seems no particular reason provided for that change.

**Comment by ry** [comment]
The file-server should use Deno.serve, which defines the default port.
