### ISSUE TITLE
stabilize `std/encoding`

### ISSUE THREAD

**Issue by kt3k** [denoland/deno_std#4856]
part of #4600 

- [x] fully documented
- [x] fully tested https://app.codecov.io/gh/denoland/deno_std/tree/main/encoding
- [x] no ongoing breaking change discussion
- [x] 1.0.0-rc.1 #4858
- [ ] wait 1 month
- [ ] 1.0.0 (stabilization)

---
related issues:
- https://github.com/denoland/deno_std/issues/3462

**Comment by iuioiua** [comment]
It'd make sense to call it `Base64Encoder` if it were a class, but it's a pure function. Hence, the current name, which starts with the corresponding verb, `encodeBase64()`. The same is true for the other functions.
