### ISSUE TITLE
The page on deno.land/std doesn’t state that it is no longer published there

### ISSUE THREAD

**Issue by roj1512** [denoland/deno_std#4859]
https://deno.land/std@0.224.0

There, it only says that it is _also_ available on JSR, not that it is _only_ available on JSR.

**Comment by iuioiua** [comment]
The last version published to https://deno.land/std is 0.224.0, available both there and on JSR. So, the statement is true. However, we should also convey that future versions are exclusively on JSR. I think we should add an obvious banner to https://deno.land/std conveying that message. WDYT, @kt3k?

**Comment by kt3k** [comment]
Now we show the warning message in the /std/ module overview page

https://deno.land/std@0.224.0

<img width="1360" alt="Screenshot 2024-05-29 at 12 05 56" src="https://github.com/denoland/deno_std/assets/613956/02b0d63b-8eef-4a41-9b48-0f9b82fdbf08">
