### ISSUE TITLE
to-do: investigate the viability of `formatter` option for `assertEquals()`

### ISSUE THREAD

**Issue by iuioiua** [denoland/deno_std#4891]
We need to decide whether this option is to be kept before achieving stabilization. See [documentation](https://jsr.io/@std/assert/doc/~/assertEquals).

One clear point against it is that it's a fourth argument for `assertEquals()`, which goes against the Deno Style Guide of having two arguments and a third option argument, max (see https://docs.deno.com/runtime/manual/references/contributing/style_guide#exported-functions-max-2-args-put-the-rest-into-an-options-object). If we are to keep it, we should merge `msg` and `formatter` into a third options argument.

**Comment by kt3k** [comment]
Looks like introduced in #3563 , but I don't remember well why this was needed.

I think we should remove that option. We didn't get any feedback about this option. I think nobody uses it.
