### ISSUE TITLE
suggestion: factor out optional arguments into options object for `assertRejects()`, `assertThrows()` and `aasertIsError()`

### ISSUE THREAD

**Issue by iuioiua** [denoland/deno_std#4892]
[`assertThrows()`](https://jsr.io/@std/assert/doc/~/assertThrows), [`assertRejects()`](https://jsr.io/@std/assert/doc/~/assertRejects) and [`assertIsError()`](https://jsr.io/@std/assert/doc/~/assertIsError) have up to 4 arguments each, which goes against the Deno Style Guide of having 2 arguments and a 3rd option argument, max (see [here](https://docs.deno.com/runtime/manual/references/contributing/style_guide#exported-functions-max-2-args-put-the-rest-into-an-options-object)). I think this is a very reasonable guideline to follow. More importantly, I think it makes these functions more complex to implement and use.

I suggest a breaking change that consolidates the second argument, onwards, into a single option. What this would look like, for `assertRejects()`, at least, is going from this:
```ts
async function assertRejects<E extends Error = Error>(
  fn: () => PromiseLike<unknown>,
  errorClassOrMsg?:
    // deno-lint-ignore no-explicit-any
    | (new (...args: any[]) => E)
    | string,
  msgIncludesOrMsg?: string,
  msg?: string,
): Promise<E | Error | unknown>
```

To maybe something like this:
```ts
interface AssertRejectsOptions<E> {
  // deno-lint-ignore no-explicit-any
  errorClass?: (new (...args: any[]) => E);
  msgIncludes?: string;
  msg?: string;
}

async function assertRejects<E extends Error = Error>(
  fn: () => PromiseLike<unknown>,
  options: AssertRejectsOptions<E> = {},
): Promise<E>
```

... And the similar for `assertThrows()` and `assertIsError()`.

Doing so would remove the need for overloads and logic handling arguments with multiple purposes. Overall, it'd make the functions easier to understand, maintain, and use and justify the breaking change.

**Comment by kt3k** [comment]
I think this is fine as it is. We didn't get any usability feedback/complaint about this. Also similar pattern is used in assertThrows in Node.js ( https://nodejs.org/api/assert.html#assertthrowsfn-error-message ). I think people are used to this pattern.

**Comment by Leokuma** [comment]
I'm strongly in favor of this. Keeping this aligned with Node would mean keeping it disaligned with Deno.

The current signature is confusing. The order of the arguments change from overload to overload. Even the official Node examples don't look very readable to me. The proposed option object makes the function call more readable and eliminates the cognitive effort to recognize and use that overloading pattern. 

Maybe we could eliminate the `msgIncludes` option as well:

```ts
interface AssertRejectsOptions<E> {
  // deno-lint-ignore no-explicit-any
  errorClass?: (new (...args: any[]) => E);
  msg?: string | RegExp;
}
```

**Comment by iuioiua** [comment]
> I think this is fine as it is. We didn't get any usability feedback/complaint about this. Also similar pattern is used in assertThrows in Node.js ( https://nodejs.org/api/assert.html#assertthrowsfn-error-message ). I think people are used to this pattern.

There are plenty of examples of us improving APIs without first requiring feedback or complaints.

> Maybe we could eliminate the `msgIncludes` option as well:

No, that's a useful option and it's used in other APIs within `@std/assert`.

**Comment by kt3k** [comment]
```ts
async function assertRejects<E extends Error = Error>(
  fn: () => PromiseLike<unknown>,
  options: AssertRejectsOptions<E> = {},
): Promise<E | Error | unknown>
```

In this suggested signature, return type being `Promise<E | Error | unknown>` is not great. It used to be `Promise<E>` for the 2nd overload, which was more useful.

**Comment by iuioiua** [comment]
Fair point. I've tweaked the suggestion to return `Promise<E>`.

**Comment by Leokuma** [comment]
I meant instead of having both `msg: string` and `msgIncludes: string`, have only an overloaded `msg: string | RegExp`.

Following your suggestion, if I pass `msg` and `msgIncludes` at the same time, what does the assertion do? The behavior is not explicit or immediately obvious, but maybe that ambiguity already exists today.

**Comment by Leokuma** [comment]
The option names `msg` and `msgIncludes` may look like they refer to the same "message".

Consider renaming:

```diff
interface AssertRejectsOptions<E> {
  // deno-lint-ignore no-explicit-any
  errorClass?: (new (...args: any[]) => E);
-  msgIncludes?: string;
+  errorMsgIncludes?: string;
  msg?: string;
}
```
It's a bit verbose, though.

**Comment by kt3k** [comment]
There was no consensus on this move in the core team. Let's not do this.

**Comment by iuioiua** [comment]
Another reason why I think we should of done this is that it the current signature makes adding extra options more cumbersome for users.

For example, I wanted to add a parameter that checks if an error's `cause` property equals a defined value. Adding this to the current signature means having another positional argument, which means higher cognitive overhead. While this can be done by checking the return value from `assertRejects()`, `assertThrows()` and `assertIsError()`, having this ability be in-built would provide a far better DX.

I wish I thought of this reason before, but it should be noted as another reason behind [this rule](https://docs.deno.com/runtime/manual/references/contributing/style_guide/#exported-functions%3A-max-2-args%2C-put-the-rest-into-an-options-object.) in the Deno Style Guide.
