### ISSUE TITLE
casing inconsistency in varint APIs

### ISSUE THREAD

**Issue by kt3k** [denoland/deno_std#4894]
Some APIs use `VarInt` and some use `Varint`

`Varint`
- decodeVarint
- decodeVarint32
- encodeVarint

`VarInt`
- MaxVarIntLen32
- MaxVarIntLen64

**Comment by iuioiua** [comment]
I think we should go with "Varint".

**Comment by kt3k** [comment]
Varint sounds good to me. Go lang seems using `Varint` consistently https://go.dev/src/encoding/binary/varint.go
