### ISSUE TITLE
issue: `decodeBase32()` throws when length is not a multiple of 8

### ISSUE THREAD

**Issue by iuioiua** [denoland/deno_std#4898]
UUIC, this is a needless constraint that the [spec](https://www.rfc-editor.org/rfc/rfc4648.html#section-6) doesn't specify. Also, other popular base32 implementations ([online decoder](https://emn178.github.io/online-tools/base32_decode.html) and [`npm:base32`](https://npm.runkit.com/base32)), don't enforce this constraint. I think we should remove this behavior.

We use the following test for this behaviour:
https://github.com/denoland/deno_std/blob/079e40296c79d503b3d512896e7c1c18f9232bea/encoding/base32_test.ts#L103-L113

**Comment by kt3k** [comment]
I think this is almost the same issue as #4899 . Correctly padded base32 encoded data should have the length of multiple of 8. The above decoder page seems to auto-pad the missing padding when evaluating, but I think it's more robust behavior to throw in that case.
