### ISSUE TITLE
stop doing deprecation process for 0.x version packages

### ISSUE THREAD

**Issue by kt3k** [denoland/deno_std#4908]
Thanks to the migration to JSR we now follow semver semantics about breaking changes (In 0.x versions we follow the rule suggested in https://github.com/semver/semver/pull/923 (something like `O.MAJOR.MINOR`)).

In previous `/std/` there's no way to expect when the breaking changes happened, and that was why we had to do deprecation process to not break the users program unexpectedly. Now because of the semver semantics, breaking changes can be predicted easily by the version number difference. I think we don't need to do deprecation process for 0.x versions anymore.

**Comment by iuioiua** [comment]
Is anything else needed here?

**Comment by kt3k** [comment]
Let's close
