### ISSUE TITLE
suggestion: stabilize `KeyStack`

### ISSUE THREAD

**Issue by iuioiua** [denoland/deno_std#4909]
It's been unstable for some time now, and we haven't received any complaints. It seems to be a lesser-used API in the Standard Library, but I'm sure it has some cool potential applications. I'm happy to make this stable now.

**Comment by kt3k** [comment]
I'm not in favor stabilizing it. I don't find any usage of this yet.

KeyStack document says:

> This was inspired by {@link https://github.com/crypto-utils/keygrip/ | keygrip}.

But keygrip is now unmaintained 4 years. https://github.com/crypto-utils/keygrip/ (Also there's no recent issue or PRs in that repo). It seems there's no actual users even in the its inspiration.

**Comment by iuioiua** [comment]
Are you suggesting we remove it? Yes, it does seem unused. Its only noteworthy use is in [Oak](https://jsr.io/@oak/oak).

**Comment by iuioiua** [comment]
On second thought, while I like this API and its potential uses, I don't think the amount of use justifies hosting it within the Standard Library. I'm for removing it.
