### ISSUE TITLE
suggestion: remove `GlobToRegExpOptions.os`

### ISSUE THREAD

**Issue by iuioiua** [denoland/deno_std#4910]
Such a setting doesn't exist in any other API within `@std/path`. If a user needs to use one of the platform-dependent variations of the function, they can use [`posix.globToRegExp()`](https://jsr.io/@std/path/doc/posix/~/globToRegExp) for POSIX systems or [`windows.globToRegExp()`](https://jsr.io/@std/path/doc/windows/glob-to-regexp/~/globToRegExp) for Windows systems, like the rest of the functions within `@std/path`.

**Comment by kt3k** [comment]
I'm in favor.

There used to be a plan to make all path APIs taking that option https://github.com/denoland/deno_std/issues/687 , but we decided to go against that design https://github.com/denoland/deno_std/pull/3649

It doesn't make sense to me to keep that option now.

**Comment by iuioiua** [comment]
Completed in #4928.
