### ISSUE TITLE
stabilize `@std/toml`

### ISSUE THREAD

**Issue by kt3k** [denoland/deno_std#4923]
part of #4600 

- [x] fully documented
- [x] fully tested
- [x] no ongoing breaking change discussion
- [x] 1.0.0-rc.1
- [ ] wait 1 month
- [ ] 1.0.0 (stabilization)

**Comment by 0f-0b** [comment]
I suggest renaming `parse` to `parseToml` and `stringify` to `stringifyToml`. Same for other file format modules in std. This allows users to import from multiple of them without [having to alias the names](https://github.com/denoland/deno_std/blob/0ea486854290152c1dffdd81af27d091bf449e95/front_matter/any.ts#L8-L9) and is consistent with `@std/encoding`.

**Comment by kt3k** [comment]
The above is being discussed in https://github.com/denoland/deno_std/issues/4993

**Comment by kt3k** [comment]
@0f-0b We decided not to do that change. See the comment https://github.com/denoland/deno_std/issues/4993#issuecomment-2162108042
