### ISSUE TITLE
Snapshot testing generation is non-deterministic/broken since 1.37.0

### ISSUE THREAD

**Issue by zifeo** [denoland/deno_std#4926]
```ts
import { assertSnapshot } from "https://deno.land/std@0.224.0/testing/snapshot.ts";

console.log(Deno.version);

Deno.test("test", async (t) => {
  assertSnapshot(t, 1, {});
  assertSnapshot(t, 2, {});
  assertSnapshot(t, 3, {});
  assertSnapshot(t, 4, {});

  /* uncomment to work around
  await new Promise((resolve) => {
    setTimeout(resolve, 1000);
  });
  */
});
```

`deno test -A snap_test.ts -- --update` leaves often an empty `.snap` file in 1.44.0, and fails with leaking ops in some versions from 1.37.0. Only 1.36.4 has a consistent and correct behavior waiting having to wait.

**Comment by iuioiua** [comment]
[`assertSnaptshot()`](https://jsr.io/@std/testing/doc/snapshot/~/assertSnapshot) is an asynchronous function. You need to `await` it like so.

```ts
Deno.test("test", async (t) => {
  await assertSnapshot(t, 1, {});
  await assertSnapshot(t, 2, {});
  await assertSnapshot(t, 3, {});
  await assertSnapshot(t, 4, {});
});
```

**Comment by zifeo** [comment]
@iuioiua Thanks for pointing that out. Can you clarify whether that there was a behavior change or we were very unlucky to only see them failing now? We have been having quite a large codebase with those, some with await (so the issue is definitely on us) and some without.

**Comment by iuioiua** [comment]
Yes, there have been several reliability and accuracy improvements to the test runner in the last 6 months. Hence, the potentially false positives before.
