### ISSUE TITLE
suggestion: improve `@std/assert` docs

### ISSUE THREAD

**Issue by iuioiua** [denoland/deno_std#4938]
The Super Doc Linter doesn't evaluate example code snippets in `@std/assert`. We should improve these docs by removing conditions that cause the a failed exit and allowing them to remove their `no-eval` snippet attributes. For example, [`assert/assert_not_equals.ts`](https://github.com/denoland/deno_std/blob/c28c34991f245e81b02837b5edab7364914a0beb/assert/assert_not_equals.ts) can be improved by going from:
````ts
 * ```ts no-eval
 * import { assertNotEquals } from "@std/assert/assert-not-equals";
 *
 * assertNotEquals(1, 2); // Doesn't throw
 * assertNotEquals(1, 1); // Throws
 * ```
````
To:
````ts
 * ```ts
 * import { assertNotEquals } from "@std/assert/assert-not-equals";
 *
 * assertNotEquals(1, 2);
 *
 * try {
 *   assertNotEquals(1, 1);
 * } catch (error) {
 *   console.error(error.message);
 * }
 * ```
````

**Comment by se-u** [comment]
> The Super Doc Linter doesn't evaluate example code snippets in `@std/assert`. We should improve these docs by removing conditions that cause the a failed exit and allowing them to remove their `no-eval` snippet attributes. For example, [`assert/assert_not_equals.ts`](https://github.com/denoland/deno_std/blob/c28c34991f245e81b02837b5edab7364914a0beb/assert/assert_not_equals.ts) can be improved by going from:
> 
> ```ts
>  * ```ts no-eval
>  * import { assertNotEquals } from "@std/assert/assert-not-equals";
>  *
>  * assertNotEquals(1, 2); // Doesn't throw
>  * assertNotEquals(1, 1); // Throws
>  * ```
> ```
> 
> To:
> 
> ```ts
>  * ```ts
>  * import { assertNotEquals } from "@std/assert/assert-not-equals";
>  *
>  * assertNotEquals(1, 2);
>  *
>  * try {
>  *   assertNotEquals(1, 1);
>  * } catch (error) {
>  *   console.error(error.message);
>  * }
>  * ```
> ```

I think it is clearer if we don't use a try-catch block, making the example clearer and more straightforward.

 ```ts
* ```ts no-eval
 * import { assertNotEquals } from "@std/assert/assert-not-equals";
 *
 * assertNotEquals(1, 2);
 * // OK
 *
 * assertNotEquals(1, 1);
 * // AssertionError: Expected actual: 1 not to be: 1
 *
 * ```
```

**Comment by iuioiua** [comment]
Yeah, this isn't a strong opinion of mine, and I see the counterargument. It's possible that docs are fine as-is. Keen to hear more opinions.
