### ISSUE TITLE
Upgrades to installer

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno_std#497]
After initial landing of installer there are still a few things to upgrade:
- support for Windows (#496)
- use `deno fetch` instead of downloading remote file or checking for local file - it will preload dependencies - better than fetching and discarding file
- expose `uninstall` command

**Comment by axetroy** [comment]
How about changing the file directory to something like this?

```
installer/
├── README.md
├── install.ts
├── mod.ts
├── test.ts
└── uninstall.ts
```

**Comment by bartlomieju** [comment]
Yes, that was my plan, `mod.ts` would be entry point that does flag parsing and calls either `install` or `uninstall`

**Comment by axetroy** [comment]
@bartlomieju
That's the problem: Where to parse the uninstall command's flag.

The command `install` and `uninstall` parse flags in `mod.ts` together?

**Comment by bartlomieju** [comment]
> That's the problem: Where to parse the uninstall command's flag.
> 
> The command `install` and `uninstall` parse flags in `mod.ts` together?

Yep:
```sh
// install
$ deno ./installer/mod.ts install file_server https://deno.land/std/http/file_server.ts --allow-net --allow-read
// uninstall
$ deno ./installer/mod.ts uninstall file_server
```

It can be then easily wired in Deno CLI

**Comment by axetroy** [comment]
@bardiarastin

List items 1 and 2 are completed. Do you want to do the third item?

> expose uninstall command

**Comment by bartlomieju** [comment]
@axetroy yes I do, btw you were pinging wrong person 😅

**Comment by bardiarastin** [comment]
Wrong person here 😅🙋🏻‍♂️❤️
just wanted to mention that I was receiving emails entire time but I wanted to act like nothing has happened 😂😬

**Comment by axetroy** [comment]
> use deno fetch instead of downloading remote file or checking for local file - it will preload

Currently using `deno fetch` without --reload.

This may cause the module to not update when reinstall.

**Comment by bartlomieju** [comment]
> > use deno fetch instead of downloading remote file or checking for local file - it will preload
> 
> Currently using `deno fetch` without --reload.
> 
> This may cause the module to not update when reinstall.

This is a good idea, I'll incorporate it tonight.
