### ISSUE TITLE
RC feedback: rename `parse`/`stringify` to `parseToml`/`stringifyToml`

### ISSUE THREAD

**Issue by kt3k** [denoland/deno_std#4993]
Feedback to `@std/toml@1.0.0-rc.1` from @0f-0b.

Should we consider renaming `parse` and `stringify` to `parseToml` and `stringifyToml`?

---
If we do the above, we probably should also consider the below renames for consistency:

- `@std/csv`: `parse`/`stringify` -> `parseCsv`/`stringifyCsv`
- `@std/ini`: `parse`/`stringify` -> `parseIni`/`stringifyIni`
- `@std/jsonc`: `parse` -> `parseJsonc`
- `@std/yaml`: `parse`/`stringify` -> `parseYaml`/`stringifyYaml`

**Comment by Leokuma** [comment]
I'm slightly against it because to be consistent we would probably have to change many other functions all across Std such as `regexp/escape` to `regexp/escapeRegexp`, `html/escape` to `html/escapeHtml`, `msgpack/encode` to `msgpack/encodeMsgpack`, SemVer functions and so on. If we did that to the entire Std, I think it might feel too verbose in the end.

**Comment by andrewthauer** [comment]
I'm a bit indifferent about this, but have a additional considerations:

- There is also `dotenv` & `semver` (possible others) that have similar method names in their respective modules. Does this mean we would also change these to be consistent?
- Of the listed ones, I've found myself aliasing the import name anyways since parse/stringify is not very descriptive or sometimes collides with a function I've written or import.

**Comment by BlackAsLight** [comment]
I'd say yes because one would need to alias the import names if importing from multiple packages.

**Comment by timreichen** [comment]
What would be the reason to do this?
I think putting the mod name into the function name is a slippery slope because one would also need to consider renaming other or even all exported functions of a module to be consistent. Putting the mod name into the function name seems redundant to me. Multiple same name imports can easily be solved with import aliases or global imports.

**Comment by iuioiua** [comment]
I suggest the inverse: keep `stringify()` and `parse()` and remove words from APIs that could be seen as overly verbose. Most APIs within the codebase already adhere to this convention (see list below). However, far more APIs would need to be adjusted to apply the issue's initial suggestion, which would be very disruptive. Using named imports in the appropriate cases is fine and, to me, is a non-issue.

List of all public function names in the codebase:

```
abortable
abortableAsyncIterable
abortablePromise
accepts
acceptsEncodings
acceptsLanguages
afterAll
afterEach
aggregateGroups
ascend
assert
assertAlmostEquals
assertArrayIncludes
assertEquals
assertExists
assertFalse
assertFp
assertGreater
assertGreaterOrEqual
assertInstanceOf
assertIsError
assertLess
assertLessOrEqual
assertMatch
assertNotEquals
assertNotInstanceOf
assertNotMatch
assertNotStrictEquals
assertObjectMatch
assertRejects
assertSnapshot
assertSpyCall
assertSpyCallArg
assertSpyCallArgs
assertSpyCallAsync
assertSpyCalls
assertStrictEquals
assertStringIncludes
assertThrows
assertType
associateBy
associateWith
backTrace
basename
beforeAll
beforeEach
bgBlack
bgBlue
bgBrightBlack
bgBrightBlue
bgBrightCyan
bgBrightGreen
bgBrightMagenta
bgBrightRed
bgBrightWhite
bgBrightYellow
bgCyan
bgGreen
bgMagenta
bgRed
bgRgb24
bgRgb8
bgWhite
bgYellow
black
blue
bold
brightBlack
brightBlue
brightCyan
brightGreen
brightMagenta
brightRed
brightWhite
brightYellow
buildMessage
calculate
canParse
chunk
closestString
common
compare
compareSimilarity
concat
concatReadableStreams
contentType
copy
copyN
copySync
createAssertSnapshot
createCapture
createColor
createCommon
createDetails
createExtractor
createFp
createSign
createTextureWithData
critical
cyan
dayOfYear
dayOfYearUtc
deadline
debounce
debug
decode
decodeAscii85
decodeBase32
decodeBase58
decodeBase64
decodeBase64Url
decodeHex
decodeTime
decodeVarint
decodeVarint32
deepMerge
delay
deleteCookie
descend
describe
describeTextureFormat
detect
diff
diffStr
difference
dim
dirname
distinct
distinctBy
dropLastWhile
dropWhile
earlyZipReadableStreams
emptyDir
emptyDirSync
encode
encodeAscii85
encodeBase32
encodeBase58
encodeBase64
encodeBase64Url
encodeHex
encodeVarint
endsWith
ensureDir
ensureDirSync
ensureFile
ensureFileSync
ensureLink
ensureLinkSync
ensureSymlink
ensureSymlinkSync
equal
equals
error
escape
exists
existsSync
expandGlob
expandGlobSync
expect
extension
extensionsByType
extname
fail
filterEntries
filterKeys
filterValues
findSingle
firstNotNullishOf
fn
format
formatMediaType
formatRange
fromFileUrl
getAvailablePort
getCharset
getColorEnabled
getCookies
getLevelByName
getLevelName
getLogger
getNetworkAddress
getRowPadding
getSetCookies
globToRegExp
gray
greaterOrEqual
greaterThan
greaterThanRange
green
hidden
ifMatch
ifNoneMatch
includesNeedle
includesValue
increment
indexOfNeedle
info
intersect
inverse
invert
invertBy
isAbsolute
isClientErrorStatus
isErrorStatus
isGlob
isInformationalStatus
isLeap
isNil
isRange
isRedirectStatus
isSemVer
isServerErrorStatus
isStatus
isSuccessfulStatus
isUtcLeap
it
italic
iterateReader
iterateReaderSync
join
joinGlobs
joinToString
jsonFormatter
lastIndexOfNeedle
lessOrEqual
lessThan
lessThanRange
levenshteinDistance
load
loadSync
magenta
mapEntries
mapKeys
mapNotNullish
mapValues
maxBy
maxOf
maxSatisfying
maxWith
mergeReadableStreams
minBy
minOf
minSatisfying
minWith
mockSession
mockSessionAsync
monotonicUlid
move
moveSync
normalize
normalizeGlob
notEquals
omit
parse
parseAll
parseArgs
parseMediaType
parseRange
parseSignedCookie
partition
partitionEntries
permutations
pick
pooledMap
printf
promptSecret
rangeIntersects
rangeMax
rangeMin
readAll
readAllSync
readDelim
readInt
readLines
readLong
readRange
readRangeSync
readShort
readStringDelim
readableStreamFromReader
readerFromIterable
readerFromStreamReader
red
reduceGroups
relative
repeat
reset
resliceBufferWithPadding
resolve
resolvesNext
restore
retry
returnsArg
returnsArgs
returnsNext
returnsThis
rgb24
rgb8
runningReduce
sample
satisfies
serialize
serve
serveDir
serveFile
serveListener
serveTls
setColorEnabled
setCookie
setup
signCookie
sliceLongToBytes
slidingWindows
sortBy
sprintf
spy
startsWith
strikethrough
stringify
stripAnsiCode
stripColor
stub
sumOf
takeLastWhile
takeWhile
tee
test
testRange
timingSafeEqual
toArrayBuffer
toBlob
toCamelCase
toFileUrl
toJson
toKebabCase
toNamespacedPath
toPascalCase
toReadableStream
toSnakeCase
toText
toTransformStream
toWritableStream
tokenize
tryParse
tryParseRange
typeByExtension
ulid
underline
unescape
unicodeWidth
unimplemented
union
unreachable
unzip
validate
verifyCookie
version
walk
walkSync
warn
weekOfYear
white
withoutAll
wordSimilaritySort
writableStreamFromWriter
writeAll
writeAllSync
writerFromStreamWriter
yellow
zip
zipReadableStreams
```

**Comment by frou** [comment]
This seems kinda analogous to the Deno philosophy of using actual web platform APIs rather than inventing APIs. In this case, promote the use of the actual JavaScript language feature (import aliases) rather than inventing a workaround.

**Comment by kt3k** [comment]
There seem no consensus on this move.

Also the core team is against this change as the scope of implication of this change is too large and unclear.

Let's not do this.
