### ISSUE TITLE
stabilize `@std/msgpack`

### ISSUE THREAD

**Issue by kt3k** [denoland/deno_std#5000]
part of #4600 

- [x] fully documented
- [ ] fully tested
- [x] no ongoing breaking change discussion
- [ ] 1.0.0-rc.1
- [ ] wait 1 month
- [ ] 1.0.0 (stabilization)

**Comment by lino-levan** [comment]
I plan on tackling https://github.com/denoland/deno_std/issues/3534 in the coming weeks now that I will be having a little bit more free time. I'd ideally like to not stabilize msgpack until people get to play around with those changes.

**Comment by iuioiua** [comment]
We prefer to continue stabilizing packages without postponing. From a quick look, the suggestions in #3534 seem non-breaking. Is this right? If so, it's fine to add them once 1.0.0 is merged.
