### ISSUE TITLE
proposal: drop `std/io` from the first stabilization targets

### ISSUE THREAD

**Issue by kt3k** [denoland/deno_std#5059]
We are still in the middle of process of migrating from Reader/Writer-based IO to Web Streams IO.

We had to undeprecate the part of std/io recently because some of IO operations cannot be replaced by Web Streams IO (ex readSync/writeSync, seek, etc). However we still aim to completely remove Reader/Writer-based IO (and therefore `std/io`) in the future (though it might take long time).

At this point, we can't decide on what should be/shouldn't be included in `std/io`. So I suggest we should drop `std/io` from the first stabilization targets.

**Comment by BlackAsLight** [comment]
> We had to undeprecate the part of std/io recently because...

Wasn't that proposal rejected? https://github.com/denoland/deno_std/issues/5032

**Comment by kt3k** [comment]
> We had to undeprecate the part of std/io recently

This references these PRs: #4128 #4184 #4247 #4343

**Comment by iuioiua** [comment]
I'm for dropping `@std/io` from removal targets for now. But we should review and remove APIs that are worth removing. There are many APIs in `@std/io` that either lack sufficient use cases or overlap in functionality. Having a smaller/simpler API surface is a win for both the user and the maintainer.

**Comment by kt3k** [comment]
`io` has been excluded from the stable in #4600
