### ISSUE TITLE
discuss: disable all "import * as xxx"

### ISSUE THREAD

**Issue by axetroy** [denoland/deno_std#506]
For some reason, we need to disable this syntax in `deno std`

### Why I want to disable it?

Sometimes we only need a function of the module. eg:

```typescript
import * as fs from 'fs/mod.ts';

fs.exists(filepath);
```

In order to use `fs.exists(filepath)`, we need to download all the dependencies under `fs/mod.ts`, which is not worth the candle in the long run.

Especially after the `deno bundle` implementation, it will produce useless extra code.

### What consequences will this have?

1. pack useless code into the bundle.
2. `deno run` will download extra packages, it is slower when running for the first time

So here's a discussion, should we disable it?

It may cause the code to be less readable

**Comment by ry** [comment]
I agree that usually this should be avoided if there's only one function - but I'm not sure about making it illegal in general...

**Comment by kitsonk** [comment]
`deno bundle` does not do tree shaking... an import is an import is an import as far as that is concerned.  We can put tree shaking on the roadmap for `deno bundle`, but it is quite complex logic and most.  I have put some thinking into it and one of the biggest challenges is that all the tree-shakers I am aware of utilise an ESTree type AST format to identify the dependencies.  That would be a reparse of all the code before the emit, where what we would really want to do is analysis on a TypeScript style AST tree and shake that out.  Anyways, is it a big subject that isn't really related to namespace imports.

There is some code in main Deno where we have to use namespace imports to be able to generate the type definitions for Deno properly.  There are certainly legitimate use cases for namespace imports.  So I am with Ry on taking it on a case by case basis.

**Comment by motss** [comment]
Were there any valid reason back then using `import * as xxx` instead of named imports?

**Comment by kitsonk** [comment]
Yes, in Deno code.  Because of the way we have to build the type library and arrive at a single global type definition, when dealing with importing modules, we have to do so via the namepsaces to avoid some collisions and naming problems in the global namespace.

Aside from the technical challenges internal to Deno, there are some use cases where using a module as a namspace makes more sense, like for common words which might be used as methods.  Like:

```ts
import * as foo from "foo.ts";
import * as bar from "bar.ts";

console.log(foo.get());
console.log(bar.get());
```

Is a lot more logical than:

```ts
import { get as fooGet } from "foo.ts";
import { get as barGet } from "bar.ts";

console.log(fooGet());
console.log(barGet());
```

**Comment by motss** [comment]
Yeah. That makes more sense. But for bundling's sake, using named imports with aliases is the way to go for better treeshake.

**Comment by zekth** [comment]
What if you use all the methods of the mod? It seems a bit strict IMO. Having this restriction using some `strict` argument could be better.

**Comment by GrosSacASac** [comment]
Rollup can tree-shake wildcard imports [See this example](http://rollupjs.org/repl/?version=1.18.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMiUyRiolMjBUUkVFLVNIQUtJTkclMjAqJTJGJTVDbmltcG9ydCUyMColMjBhcyUyMGdlb21ldHJ5JTIwZnJvbSUyMCcuJTJGbWF0aHMuanMnJTNCJTVDbiU1Q25jb25zb2xlLmxvZyglMjBnZW9tZXRyeS5jdWJlKCUyMDUlMjApJTIwKSUzQiUyMCUyRiUyRiUyMDEyNSUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMm1hdGhzLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMiUyRiUyRiUyMG1hdGhzLmpzJTVDbiU1Q24lMkYlMkYlMjBUaGlzJTIwZnVuY3Rpb24lMjBpc24ndCUyMHVzZWQlMjBhbnl3aGVyZSUyQyUyMHNvJTVDbiUyRiUyRiUyMFJvbGx1cCUyMGV4Y2x1ZGVzJTIwaXQlMjBmcm9tJTIwdGhlJTIwYnVuZGxlLi4uJTVDbmV4cG9ydCUyMGZ1bmN0aW9uJTIwc3F1YXJlJTIwKCUyMHglMjApJTIwJTdCJTVDbiU1Q3RyZXR1cm4lMjB4JTIwKiUyMHglM0IlNUNuJTdEJTVDbiU1Q24lMkYlMkYlMjBUaGlzJTIwZnVuY3Rpb24lMjBnZXRzJTIwaW5jbHVkZWQlNUNuZXhwb3J0JTIwZnVuY3Rpb24lMjBjdWJlJTIwKCUyMHglMjApJTIwJTdCJTVDbiU1Q3QlMkYlMkYlMjByZXdyaXRlJTIwdGhpcyUyMGFzJTIwJTYwc3F1YXJlKCUyMHglMjApJTIwKiUyMHglNjAlNUNuJTVDdCUyRiUyRiUyMGFuZCUyMHNlZSUyMHdoYXQlMjBoYXBwZW5zISU1Q24lNUN0cmV0dXJuJTIweCUyMColMjB4JTIwKiUyMHglM0IlNUNuJTdEJTIyJTJDJTIyaXNFbnRyeSUyMiUzQWZhbHNlJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmNqcyUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE)
