### ISSUE TITLE
proposal: remove non-default schema support from yaml

### ISSUE THREAD

**Issue by kt3k** [denoland/deno_std#5096]
I doubt anybody uses/needs non-default schema, or custom extended schema. I suggest we should remove the support of these custom schemas and type extension functionality from `yaml`.

**Comment by iuioiua** [comment]
+1

**Comment by kt3k** [comment]
I created an alternative proposal #5117. Closing this one for now.

**Comment by kt3k** [comment]
The reason I cancel this is that the default schema of `std/yaml` is mostly the most complex schema among others. I found that removing other schema doesn't reduce the complexity of package
