### ISSUE TITLE
proposal: do not expose implementation details of yaml schemas

### ISSUE THREAD

**Issue by kt3k** [denoland/deno_std#5117]
Currently YAML package exposes implementation details of schemas as public APIs such as `Schema` class or `Type` class. These seem too much details to be provided as public API. I propose we should make these APIs private.

**Comment by iuioiua** [comment]
Can you please clarify which symbols you'd like to make private and which you'd like to keep public?

**Comment by kt3k** [comment]
Keep public
- stringify
- parse
- parseAll
- StyleVariant
- DumpOption
- ParseOption

Make private
- CORE_SCHEMA
- DEFAULT_SCHEMA
- EXTENDED_SCHEMA
- FAILSAFE_SCHEMA
- JSON_SCHEMA
- KindType
- RepresentFn
- Type

**Comment by iuioiua** [comment]
Nice! Related thoughts:
1. Is it worth keeping [`parseAll()`](https://jsr.io/@std/yaml/doc/~/parseAll)? Is there something special about YAML that justifies having the ability to parse multiple YAML documents within a single body of text? Neither TOML or JSON(C) have this ability. If the answer to these questions is "no", I suggest removing `parseAll()`.
2. Is [`DEFAULT_SCHEMA`](https://jsr.io/@std/yaml/doc/~/DEFAULT_SCHEMA) the correct default schema? According to the [YAML spec](https://yaml.org/spec/1.2.2/#103-core-schema), [`CORE_SCHEMA`](https://jsr.io/@std/yaml/doc/~/CORE_SCHEMA) should be the default schema.
WDYT?

**Comment by kt3k** [comment]
> Is there something special about YAML that justifies having the ability to parse multiple YAML documents within a single body of text?

YAML spec defines the special syntax for storing multiple documents in single file. `parseAll` supports parsing it. ref https://yaml.org/spec/1.2.0/#id2600795

> Is [DEFAULT_SCHEMA](https://jsr.io/@std/yaml/doc/~/DEFAULT_SCHEMA) the correct default schema? According to the [YAML spec](https://yaml.org/spec/1.2.2/#103-core-schema), [CORE_SCHEMA](https://jsr.io/@std/yaml/doc/~/CORE_SCHEMA) should be the default schema.

The default schema is extended from core schema. It seems adding `binary`, `omap`, `pairs`, `set`, `timestamp`, and `merge` types.

I searched the usage of these types in github search, and it seems these types are very common in actual yaml files ([`!!binary`](https://github.com/search?q=language%3Ayaml+%21%21binary&type=code), [`!!set`](https://github.com/search?q=language%3Ayaml+%21%21set&type=code), [`<<`](https://github.com/search?q=language%3Ayaml+%3C%3C&type=code) (merge) ). So I think changing the default schema to CORE_SCHEMA would cause a lot of troubles.

**Comment by iuioiua** [comment]
Ok. Valid points. Thanks for investigating further.

**Comment by devingfx** [comment]
How can we extend / create new schema though?
I would like to add a special YAML tag specific to my program, how can it be done?
( Something like  `!!js/regexp` that produce a real JS RegExp object... )

**Comment by kt3k** [comment]
We added back the capability of adding extra types to unstable versions of `parse` and `stringify`: https://github.com/denoland/std/pull/6841/files

Does that work for your use case? (You can import them from `jsr:@std/yaml/unstable-parse` and `jsr:@std/yaml/unstable-stringify` respectively)

**Comment by devingfx** [comment]
> https://github.com/denoland/std/pull/6841#issuecomment-3491317384

a bit overkill just to gain access to `_schema.ts` types / functions ...

**Comment by devingfx** [comment]
I figured out finally how to extend schemas:

Importing a private file from JSR specifier is forbidden, but not using the resolved URL:
```js
import { SCHEMA_MAP } from 'jsr:@std/yaml@1.0.9/_schema.ts'
```
Errors, but...
```js
import { SCHEMA_MAP } from 'https://jsr.io/@std/yaml/1.0.9/_schema.ts'
```
... is ok.

And the runtime modules are not duplicated:
```js
import * as YAML from 'jsr:@std/yaml@1.0.9'
import { parse } from 'https://jsr.io/@std/yaml/1.0.9/parse.ts'
assertEquals(
	YAML.parse,
	parse
)
```

------------------

So this is working:

```js
import * as YAML from 'jsr:@std/yaml@1.0.9'
import { SCHEMA_MAP } from 'https://jsr.io/@std/yaml/1.0.9/_schema.ts'

SCHEMA_MAP.get( 'extended' ).typeMap
	.scalar.set( 'tag:yaml.org,2002:js/eval', {
		tag: 'tag:yaml.org,2002:js/eval',
		kind: 'scalar',
		resolve() { return true },
		construct( data ){ return eval(data) }
	})

assertEquals(
	YAML.parse('foo: !!js/eval 4*10+2', {schema: 'extended'}),
	{ foo: 42 }
)
```
