### ISSUE TITLE
yaml: Rename negative property names in options

### ISSUE THREAD

**Issue by timreichen** [denoland/deno_std#5124]
I think some properties of function options are poorly named. Options should be formulated positively imo and the default value adjusted accordingly.

https://github.com/denoland/deno_std/blob/3fac8a2e8655150181835acf83fd8a9071d5cd0e/yaml/_dumper/dumper_state.ts#L45
Proposal: Rename to `indentArrays` or something similar.

https://github.com/denoland/deno_std/blob/3fac8a2e8655150181835acf83fd8a9071d5cd0e/yaml/_dumper/dumper_state.ts#L74
The comment states: `if true, don't convert duplicate objects into references (default: false)`. Is it just me or is this confusing?
Proposal: Rename to `createRefs` or something similar.

https://github.com/denoland/deno_std/blob/3fac8a2e8655150181835acf83fd8a9071d5cd0e/yaml/_dumper/dumper_state.ts#L80
Proposal: Rename to `compatMode` or something similar.

WDYT?

**Comment by iuioiua** [comment]
I agree. Negative tenses are far more ripe for confusion. The proposed names seem mostly fine. Happy to take a look at a PR.

**Comment by timreichen** [comment]
How should that be done without breaking changes?

**Comment by iuioiua** [comment]
We'd allow the breaking changes for this one, at this point in time.
