### ISSUE TITLE
suggestion: remove `iterator` argument from `parseAll()` in `@std/yaml`

### ISSUE THREAD

**Issue by iuioiua** [denoland/deno_std#5128]
I suggest removing the [`iterator`](https://jsr.io/@std/yaml/doc/parse/~/parseAll#function_parseAll_0_parameters_iterator) argument from [`parseAll()`](https://jsr.io/@std/yaml/doc/parse/~/parseAll).

It provides no added value to the function as it doesn't affect the return array and is only called on each YAML document (element) once all documents are already loaded onto memory. If a user really needs this functionality, they can use [`Array.prototype.forEach()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach).

https://github.com/denoland/deno_std/blob/a4d4e51cfad1fd79eae5c70bdb8b0d6f92a591d7/yaml/_loader/loader.ts#L1773-L1789

**Comment by kt3k** [comment]
This makes sense to me. The first signature of `parseAll()` (one with iterator) can be easily replaced with the below pattern:

```diff
-parseAll(yaml, iterator, options);
+parseAll(yaml, options).forEach(iterator);
```

There seem no special scenario supported only by the 1st signature. (If there's an error in any of the input, both cases seem throwing at the same point).
