### ISSUE TITLE
media_types: incorrect mime for javascript - does not match mime-db

### ISSUE THREAD

**Issue by FergoTheGreat** [denoland/deno_std#5186]
The documentation for [media_type](https://deno.land/std@0.224.0/media_types/vendor/mime-db.v1.52.0.ts?source) claims the mime database comes from mime-db v1.52, yet in deno ".mjs" and ".js" map to "application/javascript" where as in the actual mime-db v1.52 [db.json](https://github.com/jshttp/mime-db/blob/master/db.json) it appears that they map to the correct "text/javascript".

**Comment by 0f-0b** [comment]
The database does come from mime-db v1.52.0, but there have been [many unreleased changes since](https://github.com/jshttp/mime-db/compare/v1.52.0...master), including [a fix for this issue](https://github.com/jshttp/mime-db/issues/194).
