### ISSUE TITLE
suggestion: make `createExtractor` module private in `@std/front-matter`

### ISSUE THREAD

**Issue by iuioiua** [denoland/deno_std#5265]
This module contains implementation details that are extraneous to most, if not all, users. Doing so would make `@std/front-matter` easier to understand.

**Comment by kt3k** [comment]
I think it's intentionally exported to support any combination of front matter languages. (like YAML + TOML, excluding JSON, etc). https://github.com/denoland/deno_std/pull/2801

I'm not sure it's good idea to remove it

**Comment by iuioiua** [comment]
[`@std/front-matter/any`](https://jsr.io/@std/front-matter/doc/any/~/) does that. Sure, it pulls in an extra dependency, but that seems like a very small tradeoff for a package that's easier to understand. More importantly, `createExtractor()` is barely anywhere (see [here](https://github.com/search?q=%22%40std%2Ffront-matter%22+%22createExtractor%22&type=code)). The two codebases that do use it aren't using `@std/front-matter` correctly (see [here](https://github.com/rodneylab/deno/blob/a11e87c4ad42d85089d80bbbb56f2cad7f28221e/demos/deno-fresh-rss-feed/utility/blog.ts#L5) and [here](https://github.com/kyoh86/denops-zenn_dev.vim/blob/d8468899ec3be9147cf6bfb7cf61e96b381cedcb/denops/zenn_dev/command/list_articles.ts#L2)).

**Comment by kt3k** [comment]
Ok. It doesn't seem well understood. Let's remove.
