### ISSUE TITLE
catj should accept stdin input

### ISSUE THREAD

**Issue by ry** [denoland/deno_std#532]
> curl  https://ci.appveyor.com/api/projects/deno/deno/builds/25856198 | catj

(also can we rename it from catjson to catj ?)

**Comment by bartlomieju** [comment]
Try:
```
curl https://ci.appveyor.com/api/projects/deno/deno/builds/25856198 | catj -
```

There's no easy way to check if there's something to read from stdin in Deno (if there's nothing it will block forever), that's why `-` is needed.

**Comment by ry** [comment]
Oh sorry ! I didn't even see that in the help text. But trying it now, it doesn't seem to work.

```
> cat log.json | catj -
Usage: catjson [-h|--help] [file...]

Examples:

// print file:
   catjson file.json

// print multiple files:
   catjson file1.json file2.json

// print from stdin:
   cat file.json | catjson -
```

**Comment by bartlomieju** [comment]
I just checked and indeed it's not working... I think flag parsing after script name in `v0.11.0` might have broken it. I'll investigate in the evening.
