### ISSUE TITLE
proposal: remove `@std/ini`

### ISSUE THREAD

**Issue by iuioiua** [denoland/deno_std#5330]
Usage of [`@std/ini`](https://jsr.io/@std/ini) is extremely low, according to [this GitHub code search](https://github.com/search?q=%22%40std%2Fini%22+language%3ATypeScript&type=code&l=TypeScript), [dxter's analytics](https://dxter.deno.dev/#submodules), and [JSR's dependents list](https://jsr.io/@std/ini/dependents). As such, such low levels of usage are unlikely to provide sufficient justification to keep the package in the Standard Library. Note: We are still yet to confirm usage data on JSR.

I suggest removing `@std/ini` from the Standard Library. We can complete documentation, then mark as deprecated, then "remove". To be clear, the package will live on, as it's immutable on JSR, but will no longer be maintained.

**Comment by andrewthauer** [comment]
We are using `@std/ini` internally  so I don't feel like basing decisions on GH search should be a strong indicator.

Our usage of Deno to this point is very much around scripting and glue code which it pairs very nice with. This type of code often  involves working with various other tools and some of those can the ini. For example AWS CLI uses ini as there config format.

**Comment by kt3k** [comment]
@andrewthauer Which APIs do you use among `parse`, `stringify`, and `IniMap`?

**Comment by iuioiua** [comment]
> We are using `@std/ini` internally so I don't feel like basing decisions on GH search should be a strong indicator.

I agree - that's why I also mentioned dxter's (based on GA data), JSR's dependents list, and pending usage data on JSR 🙂 

Nevertheless, thanks for weighing-in. We'll definitely take your use case into consideration.

**Comment by iuioiua** [comment]
@andrewthauer, we've decided to stabilize `@std/ini` instead of removing it based on your feedback.

**Comment by andrewthauer** [comment]
> @andrewthauer Which APIs do you use among `parse`, `stringify`, and `IniMap`?

@kt3k - We are currently using just `parse` & `stringify`. However, I could see `IniMap` being useful.

**Comment by kt3k** [comment]
Thanks for your feedback. We currently made `IniMap` private as it seems overly complex and also we didn't find any existing usage in the ecosystem. Let's explore that after stabilizing `ini` with `parse` and `stringify`

**Comment by kt3k** [comment]
I'm closing this issue as we now don't plan to remove `std/ini` anymore.
