### ISSUE TITLE
proposal: drop `std/dotenv` from the first stabilization target

### ISSUE THREAD

**Issue by kt3k** [denoland/deno_std#5331]
`std/dotenv` and an unstable CLI feature `deno run --env` flag overlap largely, and it'll be probably confusing if we have both features. However currently we are not ready to make decision about which one to stabilize or remove.

So I propose to drop `std/dotenv` from the first stabilization target.

**Comment by iuioiua** [comment]
Closing as this change has been reflected in #4600.
