### ISSUE TITLE
propsal: move some modules out of `@std/fmt`

### ISSUE THREAD

**Issue by iuioiua** [denoland/deno_std#5353]
I propose we move the following modules out of `@std/fmt`.
1. `@std/fmt/colors` to `@std/cli/colors`
2. `@std/fmt/duration` to `@std/datetime/duration`
3. `@std/fmt/bytes` to `@std/bytes/format`

The aim of these moves is to have the modules in packages that are more directly oriented to their respective functionalities, and therefore in locations that are more intuitive to newcomers.

**Comment by 0f-0b** [comment]
> 1. `@std/fmt/colors` to `@std/cli/colors`

Should be `@std/cli/styles` as discussed in #4326 and #4676.

**Comment by Leokuma** [comment]
1. I like moving `@std/fmt/colors` to `@std/cli/styles`.
2. While I like it, kt3k raised the point that it's highly likely that the Datetime package will be deprecated once the Temporal API is stabilized. If Temporal is expected to be stabilized soon, I wouldn't bother moving Duration. But I'm not sure if Temporal actually covers the use cases of Duration.
3. I like it. Even though kt3k raised the point that the purpose of the Bytes package is to manipulate Uint8Array, I still think this package is the best place for byte formatting. It's questionable, though.

**Comment by iuioiua** [comment]
> Should be `@std/cli/styles` as discussed in #4326 and #4676.

I agree. Those issues, and a [small poll](https://discord.com/channels/684898665143206084/775393009981849600/1236917916067303497) in Discord points to others being in favor too. However, the Deno internal team is mostly neutral on the idea. In Yoshiya's eyes, this means we shouldn't proceed. I disagree.

Also, I've pushed for these changes a few times now, and it's holding us up a little. If these suggestions don't get enough traction, this issue will expire in ~1 day and we'll proceed with stabilizing `@std/fmt` as is.

**Comment by iuioiua** [comment]
Unfortunately, this suggestion hasn't received the traction I was hoping for. While I disagree with it, we'll proceed with stabilizing `@std/fmt`.

**Comment by Leokuma** [comment]
Regarding 2 and 3, I understand that there are some arguments against them.

As for 1, I haven't seen any argument against it other than being a breaking change. When we first introduced `colors`, we still didn't have `@std/cli`.
