### ISSUE TITLE
suggestion: remove `getAvailablePort()` from `@std/net`

### ISSUE THREAD

**Issue by iuioiua** [denoland/deno_std#5364]
I suggest removing [`getAvailablePort()`](https://jsr.io/@std/net/doc/get-available-port/~/getAvailablePort) from [`@std/net`](https://jsr.io/@std/net).

Since implementation, `Deno.HttpServer.addr.port` became available in [Deno 1.43](https://deno.com/blog/v1.43#simpler-access-to-the-server-address). This satisfies the [original problem](https://github.com/denoland/deno_std/issues/3279#issuecomment-1837205616) that `getAvailablePort()` aimed to solve. Example use:

```ts
// main.ts
export const port = Deno.serve({ port: 0 }, (_req) => new Response("Hello, world")).addr.port;
```
```ts
// test.ts
import { port } from "./main.ts";
// ...
```

Secondly, at least according to [this](https://github.com/search?q=%2Fstd.*%5C%2Fnet%2F+%22getAvailablePort%22+language%3ATypeScript&type=code) GitHub search, it's easily replaced with `port: 0` (documentation to be added in https://github.com/denoland/deno/pull/24475). 
```diff
- import { getAvailablePort } from "@std/net";

Deno.serve({
- port: getAvailablePort(),
+ port: 0,
}, (_req) => new Response("Hello, world"));
```

Lastly, the function is susceptible to a race condition (a port that is deemed available becomes unavailable in between calling `getAvailablePort()` and the following `Deno.serve()`, and introduces a dependency when the same functionality is already built into the runtime.

Happy to hear thoughts.

CC @harrysolovay @jollytoad @bcheidemann @dominiq007 (I found your repos used this function)

**Comment by iuioiua** [comment]
Edit: A reasonable edge was found in the following code. We'll now instead add documentation advising against the use of this function, in favor of using `port: 0`. https://github.com/denoland/deno_std/blob/1f26aa503b083ccdf08113f663a176b98d012d59/http/file_server_test.ts#L991-L1040

**Comment by jollytoad** [comment]
Also the [preferredPort](https://jsr.io/@std/net/doc/get-available-port/~/GetAvailablePortOptions.preferredPort) feature is not available natively in Deno, yet can be quite useful during development.
