### ISSUE TITLE
question(collections): `intersect()` function name differ from Set method name

### ISSUE THREAD

**Issue by timreichen** [denoland/deno_std#5416]
**Is your feature request related to a problem? Please describe.**

`Set` has gotten new methods a while back. The `union()` function behaves the same as `Set.prototype.union()` except for arrays. `intersect()` is the array counterpart to `Set.prototype.intersection()` but the name differs (ref: https://github.com/denoland/deno_std/pull/5417).

**Describe the solution you'd like**
rename `intersect()` to `intersection()` to be consistent with the web `Set` api.

**Describe alternatives you've considered**

Leave as is. I am aware that collections is stable now.
I wonder though what the procedure would be for such a potential change on stable mods.

**Comment by iuioiua** [comment]
Frankly, the benefit in changing the name to align with `Set.prototype.intersection` is negligible, especially given that `@std/collections` is now stable. So we'll have to decline this one.

We have to be much more conservative with breaking changes and only proceed with those which are "worth the breaking change". Also, kind of related, is that these `Set` methods likely nullify the justification for these Standard Library APIs anyway (see #4637).

Either way, thank you for the suggestion, Tim! Always much appreciated.
