### ISSUE TITLE
console.log(headers) doesn't print useful info

### ISSUE THREAD

**Issue by FrediLehmann** [denoland/deno_std#543]
I have problems to read the headers of a `ServerRequest`.
I have updated the dependencies with the `--reload` flag, but the error still exists.
Is this a Bug or am i doing it wrong?

This is the Code i use:
```typescript
import { serve } from "https://deno.land/std/http/server.ts";

const test = async () => {
  const _s = serve('0.0.0.0:8000')

  for await (const req of _s) {
    console.log(req.headers)
    req.respond({ body: new TextEncoder().encode("Hello World\n") })
  }
}

test();

let res = fetch('http://0.0.0.0:8000/test', {
  method: 'POST',
  headers: {
    'Content-Type': 'application/json; charset=UTF-8',
    'test': 'test'
  },
  body: 'test'
}).then(res => res)

res = fetch('http://0.0.0.0:8000/test').then(res => res)

```

This is the console output i get: 
```text
Headers {}
Headers {}
```

**Comment by bartlomieju** [comment]
That's just how console print headers, did you check if there are any values inside with `req.headers.entries()`?

**Comment by FrediLehmann** [comment]
With `console.log(req.headers.entries())` i get 
```text
{}
{}
```

**Comment by FrediLehmann** [comment]
My bad, i was just to stupid:

```javascript
for (let header of req.headers.entries()) console.log(header)
```

**Comment by ry** [comment]
It seems annoying that it's so difficult to display a Headers object. I checked Chrome and it does indeed display `Headers {}`... I wonder if we could do something different.

**Comment by zekth** [comment]
It is due to `Headers` inheritance.
You can debug it using:
`console.log(new Map(request.headers))`
or the iterator
`for (const e of request.headers.entries()) console.log(e);`

Problem is the `Header` class. Another issue like the one described here : https://github.com/denoland/deno/pull/2454

**Comment by kitsonk** [comment]
You could implement `[Deno.customInspect]()` to provide something more meaningful now.

**Comment by j-f1** [comment]
Here’s a possible implementation:

```ts
function renderHeaders(headers: Headers) {
    console.log('Headers {')
    for (const [header, value] of headers.entries()) {
      console.log(`  ${header}: ${value}`)
    }
    console.log('}')
  }
```

Should I open a PR in Deno core?

**Comment by j-f1** [comment]
Here’s an option:

```ts
function renderHeaders(headers) {
  console.log('Headers {')
  for (const [header, value] of headers.entries()) {
    console.log(`  ${header}: ${value}`)
  }
  console.log('}')
}
```

Should I make a PR to the Deno repo?

**Comment by kitsonk** [comment]
Use `[Deno.customInspect]()` and then you won't have to touch core.  See denoland/deno#2791.

**Comment by j-f1** [comment]
It looks like `Headers` is a global type. How could I contribute the custom inspector so it’s used by Deno by default?

**Comment by kitsonk** [comment]
By submitting a PR adding it [to the Headers class](https://github.com/denoland/deno/blob/6cded14bdf313762956d4d5361cfe8115628b535/js/headers.ts#L20).  I think we need to remove most of the case logic in the `inspect()` to this symbol anyways, as it would be tightly coupled to the class it represents than located specifically in the logic of `inspect()`.

In the case of internal Deno code, you would need to `import { customInspect } from "./console";`, but the concept is the same.

**Comment by RoryMalcolm** [comment]
https://github.com/RoryMalcolm/deno/commit/8367894fe8d0af2e093987510eb76a837ff43609 I had a go at fixing this here but cannot get `cargo test` to run on my machine, other people can pick up if they want

**Comment by ry** [comment]
@RoryMalcolm I'd be interested to hear what issue you ran into.

**Comment by RoryMalcolm** [comment]
> @RoryMalcolm I'd be interested to hear what issue you ran into.

When I run `cargo test` I get this error: 

```
thread 'js_unit_tests' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"', src/libcore/result.rs:1084:5
```

I followed the instructions from the build environment setup page on deno.land, no sweat of your back I think its an issue with my setup.

Would've just tested with GitHub Actions but when I try to enable them on my fork I get a 500 😬

**Comment by bartlomieju** [comment]
> Would've just tested with GitHub Actions but when I try to enable them on my fork I get a 500 😬.

Just open a PR in main repo and run CI there :)

**Comment by ry** [comment]
@RoryMalcolm It would be very helpful if you run this:
```
RUST_BACKTRACE=1 cargo test
```
and open an issue in https://github.com/denoland/deno with the output.
