### ISSUE TITLE
ws error 

### ISSUE THREAD

**Issue by runnerSnail** [denoland/deno_std#547]
![image](https://user-images.githubusercontent.com/40654631/62017290-af1db700-b1e8-11e9-986d-0219e4b2ca96.png)

ps: I think our official package is terrible, although the deno is very good

**Comment by ry** [comment]
Yes the ws module really needs some work!

**Comment by ry** [comment]
Can you listen the code that made this error?

**Comment by bartlomieju** [comment]
Looks like problem is in @runnerSnail code not in WS module
