### ISSUE TITLE
Add overloaded form of unit test declaration: test(name, fn) 

### ISSUE THREAD

**Issue by ry** [denoland/deno_std#562]
There are currently two ways to declare a unit test
```javascript
// original form
test(function foo() { assert(true); });
// expanded form
test({ name: "foo", fn: () => { assert(true); });
```
It turns out that many of the tests in deno_std are using the expanded form. We could shorten this significantly by also allowing
```js
test( "foo", () => { assert(true); });
```

Someone has suggested this before and noted that a certain existing test framework uses this form as well.  (I can't find a reference.) So that's another reason to change.

Edit: reportedly Ava.js, Mocha and Jest all support this.

**Comment by sholladay** [comment]
I suggested it in https://github.com/denoland/deno_std/issues/93.

More specifically, I think AVA's API should be adopted, for at least test definitions and assertions.
