### ISSUE TITLE
Test runner file matcher should walk as little as possible

### ISSUE THREAD

**Issue by nayeemrmn** [denoland/deno_std#576]
If I run `deno -A https://deno.land/std/testing/runner.ts projects/deno_std/fmt/sprintf_test.ts`, it walks the whole directory tree from CWD and takes a really long time. Obviously no walking should be done in this case - sound easy enough.

Ideally though, `deno test projects/deno_std/fmt/*_test.ts` would only walk `projects/deno_std/fmt`. At that point you'd want to extract a magical glob expansion utility in `//fs`.

**Comment by bartlomieju** [comment]
Yeah it makes sense. I'll update the test runner

**Comment by bartlomieju** [comment]
I got caught up in other work, if someone wants to tackle that feel free
