### ISSUE TITLE
[testing] deno test does not work on windows

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno_std#593]
The `deno test` command does not work on windows. It always outputs `No matching test files found.` [Here](https://dev.azure.com/denoland/deno_std/_build/results?buildId=2230&view=logs&jobId=2d2b3007-3c5c-5840-9bb0-2b1ea49925f3&taskId=ddeebf02-4eb3-5b9c-39ee-cfd42d31a3cf&lineStart=17&lineEnd=18&colStart=1&colEnd=1) is an example from the `deno_std` CI. I think the file walker/matcher does not work on windows.

**Comment by bartlomieju** [comment]
Yikes, definitely a bug. I guess `test_runner` should return exit code 1 if there are no matching files found, or it will keep on skipping silently.

**Comment by nayeemrmn** [comment]
> I guess `test_runner` should return exit code 1 if there are no matching files found, or it will keep on skipping silently.

With an `--allow-none` option hopefully?

**Comment by bartlomieju** [comment]
@lucacasonato are you working on a fix?

**Comment by lucacasonato** [comment]
Not yet, I can once I'm done with moving deno to GitHub Actions.

**Comment by lucacasonato** [comment]
Fixed by #604
