### ISSUE TITLE
Idea: .env file parser

### ISSUE THREAD

**Issue by sh7dm** [denoland/deno_std#60]
Maybe create `.env` file parser for the std library? I would like to work on it

**Comment by sh7dm** [comment]
We can use [this repo](https://github.com/motdotla/dotenv) as an example

**Comment by bartlomieju** [comment]
There already exists implementation at pietvanzoen/deno-dotenv if you want check it out

**Comment by sh7dm** [comment]
@bartlomieju OK! I'll check it out!
