### ISSUE TITLE
Merge deno_std into deno repo

### ISSUE THREAD

**Issue by ry** [denoland/deno_std#603]
deno_std and deno have circular dependencies between them - and it's increasingly difficult as our codebase grows to keep them in sync.

I plan to merge the deno_std repo into deno in the near future.

I want to complete a few things first
- https://github.com/denoland/deno/issues/2933
- https://github.com/denoland/deno/issues/2852

**Comment by zekth** [comment]
Just a question, deno_std will still not be shipped with the deno runtime right?

**Comment by ry** [comment]
Correct - deno_std will still be available via https://Deno.land/std

This is just about being able to have CI testing both the std modules and internal code.

**Comment by zekth** [comment]
Also this move requires the review of current issues of the repo. Moving the related ones and closing the staling. (just to have it in consideration)

**Comment by sh7dm** [comment]
Won't this cause longer and more frequent builds since CI will run both deno and deno_std tests for anything? So `deno_std` change will cause a CI run for both. Please pay attention to this.

**Comment by ry** [comment]
Yes, this will certainly increase the CI time for deno_std - it won't for deno.

We are moving to Github Actions in Deno - and that should improve the CI time... But yes, expect it to be about 15 minutes to get green.

The trade off is worth it. We need to have better understanding of how changing in core effect std and vise versa. Ultimately I think this merge will increase our agility.

**Comment by zekth** [comment]
> Won't this cause longer and more frequent builds since CI will run both deno and deno_std tests for anything? So `deno_std` change will cause a CI run for both. Please pay attention to this.

Tests of deno_std are really fast so i'm not concerned with that. The only concern is the occurence of builds yes.

**Comment by keroxp** [comment]
Hmm... It must be hard task for contributors. I know there are some difficulties of managing parallel projects. But "all at once" is not good idea imo. On the first step, only modules depended by core repository should be moved, can you? 

E.g. `installer` and `prettier` are pragmatically not part of std as a module. `testing` is special module and it is acceptable to have circular dependencies.  And I think it is enough to run std's tests also in core's CI for checking compatibility of core/std.

**Comment by ry** [comment]
We’ve started the transition 
https://github.com/denoland/deno/pull/3085

**Comment by zekth** [comment]
Also maybe a `std` tag github for the deno issues could be cool. To find if the issue / pr is related to core or std. Don't you think?
