### ISSUE TITLE
Discussion : path.isWindows

### ISSUE THREAD

**Issue by zekth** [denoland/deno_std#629]
I was reviewing a PR and i figured out it's weird to have `path.isWindows`. I mean it would make more sense to ask for `os.isWindows` no? Because in this case iswindow is returning the value in calculation of the context of execution not the path. For example i would imagine:
```
'c:\foo\bar\t.js'.isWindows // true
'/mnt/foo/bar/t.js'.isWindows // false
```
ref:
https://github.com/denoland/deno_std/blob/master/fs/path/constants.ts#L51

**Comment by nayeemrmn** [comment]
See #624, last bullet. If that doesn't get merged I'll make a PR for just the smaller stuff like this.

**Comment by zekth** [comment]
> See #624, last bullet. If that doesn't get merged I'll make a PR for just the smaller stuff like this.

Indeed, it was on that point i was really wondering about the use of it.
