### ISSUE TITLE
[STD/FS] Synchronous copy method doesn't overwrite folder with such option enabled

### ISSUE THREAD

**Issue by ilovewine** [denoland/deno_std#638]
**ENV**: Linux

**Steps to reproduce:**

- create ./foo with a file.txt (with some data X)
- create ./folder with a file2.txt (with some data Y)
- create the script copy.ts:
```
import { copySync } from "https://deno.land/std@0.81.0/fs/mod.ts";
copySync("./foo", "./folder", {overwrite: true});
```
- run deno run --unstable --allow-read --allow-write copy.ts
**Expected result**: folder ./folder contains only file.txt with data X
**Actual result**: folder ./folder contains both file.txt with data X and file2.txt with data Y

**Comment by q1qgames** [comment]
Seems like this is behaving as designed and should perhaps be a documentation addition with a reference to emptyDir (and the sync counterpart) if desired.

**Comment by iuioiua** [comment]
@bartlomieju, this might be able to be closed, seeing as the PR was closed with good reason.

**Comment by kt3k** [comment]
Yes. Let's close this. We recommend the use of `emptyDir` if you prefer to replace the entire directory contents. `overwrite: true` option means it overwrites the contents of a file if the file of the same name exists in the destination.
