### ISSUE TITLE
[std/node] Deno fs errors not being remapped

### ISSUE THREAD

**Issue by guybedford** [denoland/deno_std#640]
Deno throws fs errors with a `name` property like `NotFound`, which need to be converted in the Node.js layer into Node.js errors, something like:

```js
function convertNodeFsError (err) {
  switch (err.name) {
    case 'NotFound':
      err.code = 'ENOENT'; // (or copy instead of mutate?)
      return err;
  }
  return err;
}
```

Such a generic handler for all fs functions (or even more generally for all Node.js callback handling) likely will make sense here.

**Comment by bartlomieju** [comment]
This problem was addressed in https://github.com/denoland/deno/pull/12591 and is now used in https://github.com/denoland/deno_std/pull/1435
