### ISSUE TITLE
Feature request: Add 'only' flag to bench API

### ISSUE THREAD

**Issue by cknight** [denoland/deno_std#644]
Deno's testing API has a very useful `only` option, to only run that one test.  It would be great to have this same option in the bench API allowing a single benchmark test to be run.  My use case is that I have lots of benchmark tests which can take awhile to run and I wish sometimes to just run one of them to examine performance of just that variant.

**Comment by bartlomieju** [comment]
I'm still open to adding this flag, if anyone wants to work on this feel free to open a PR so we can discuss it further. Suggestions made by @littletof make a lot of sense and are a good starting point.

**Comment by iuioiua** [comment]
@bartlomieju, I believe this can be closed. [Benchmark functionality](https://deno.land/manual/tools/benchmarker), while marked as unstable, is now Deno-native and has the `only` option too.
