### ISSUE TITLE
Proposal: std/session

### ISSUE THREAD

**Issue by getspooky** [denoland/deno_std#646]
Hello deno community ,
I think it would be an enrichment to std to have session included by default with several great drivers out of the box
- `cookie` - sessions are stored in secure, encrypted cookies.
- `database` - sessions are stored in a relational database.
- `memcached / redis` - sessions are stored in one of these fast, cache based stores.

What are your thoughts on that?

**Comment by bartlomieju** [comment]
I agree with @kitsonk that this is not something that should belong to `std`. Respectfully declined.
