### ISSUE TITLE
Try to parse error messages to get an accurate error code for std/wasi

### ISSUE THREAD

**Issue by caspervonb** [denoland/deno_std#649]
This bit of a hack but it's what we can do at the moment without changing up the internal errors.

To get more accurate error mappings we can try to parse the errno from error message string which may contain the errno from Rust when it is an std::io::Error before falling back to the current approach of switching on error.name.

This is a good first issue.

**Comment by lino-levan** [comment]
Is this still desirable?

**Comment by iuioiua** [comment]
Closing this as `std/wasi` is now deprecated. If you still need to use WASI in Deno, use [wasmer-js](https://github.com/wasmerio/wasmer-js) instead.
