### ISSUE TITLE
Review the std/hash Hasher interface

### ISSUE THREAD

**Issue by caspervonb** [denoland/deno_std#652]
The Hasher interface defined in std/hash might warrant a review.

First thing I noticed was that Hasher.digest returns an ArrayBuffer, This is more or less the only interface we have that doesn't return an Uint8Array view of the generated ArrayBuffer.

Other concerns, @kitsonk ?

**Comment by jeremyBanks** [comment]
I have proposed an expanded interface:

- https://github.com/denoland/deno_std/discussions/1014
