### ISSUE TITLE
Please document the incredibly useful bufio.ts

### ISSUE THREAD

**Issue by webdev3301** [denoland/deno_std#654]
I simply cannot find ANY documentation on the following extremely useful imports:

```
import { BufReader, BufWriter } from 'https://deno.land/std@0.67.0/io/bufio.ts';
import { TextProtoReader }      from 'https://deno.land/std@0.67.0/textproto/mod.ts';
```

Can these please be documented. I'm a huge fan of Deno but right now I am literally copying & pasting code knowing that's going to break and hours later it eventually works but I have no idea how. It's like coding in the dark.

**Comment by bartlomieju** [comment]
The module was updated and contains doc strings for all exported APIs.
