### ISSUE TITLE
feat(std/node/process): request for stdin, stdout, stderr [$20 bounty]

### ISSUE THREAD

**Issue by balupton** [denoland/deno_std#656]
currently they are missing from https://github.com/denoland/deno/blob/master/std/node/process.ts

My use case is running [make-deno-edition](https://github.com/bevry/make-deno-edition) on [assert-helpers](https://github.com/bevry/assert-helpers) which is failing on https://github.com/bevry/assert-helpers/blob/3f4a9ea8a6c6d606f5cecc3cce96755e1ead3357/source/index.ts#L27-L36 because they are missing, and don't have .isTTY() added for them

Relevant node docs:

- https://nodejs.org/dist/latest-v14.x/docs/api/process.html#process_process_stderr
- https://nodejs.org/dist/latest-v14.x/docs/api/process.html#process_process_stdin
- https://nodejs.org/dist/latest-v14.x/docs/api/process.html#process_process_stdout
- https://nodejs.org/dist/latest-v14.x/docs/api/tty.html#tty_readstream_istty
- https://nodejs.org/dist/latest-v14.x/docs/api/tty.html#tty_writestream_istty
- https://nodejs.org/dist/latest-v14.x/docs/api/tty.html#tty_tty_isatty_fd

Relevant deno docs:

- https://doc.deno.land/builtin/stable#Deno.isatty

Just to make it explicit, these Node.js methods are needed for any substantial compat.

- [x] `*.fd`
- [x] `*.isTTY `
- [ ] `*.on`
- [ ] `stdout.pipe`
- [ ] `stderr.pipe`
- [ ] `stdout.write`
- [ ] `stderr.write`
- [ ] `stdin.read`

**Comment by bartlomieju** [comment]
These APIs are now available in `std/node`.

**Comment by balupton** [comment]
Seems the repo migration has caused bountysource to forget to solve this issue, for whoever solved this, you should be able to claim the $20USD bounty I placed via https://app.bountysource.com/issues/92348869-feat-std-node-process-request-for-stdin-stdout-stderr-20-bounty
