### ISSUE TITLE
Remove JavaScript versions of std/hash

### ISSUE THREAD

**Issue by caspervonb** [denoland/deno_std#658]
Right now we're doubling up on a lot of hashing algorithms.

The WebAssembly implementation is a good first pass but if we're keeping single algorithm imports (e.g std/hash/sha1.ts) then we should probably generate WebAssembly backed classes for these as-well.

**Comment by iuioiua** [comment]
@bartlomieju, is this able to be closed? `std/hash` is deprecated.
