### ISSUE TITLE
Discussion(std/testing/bench): Support asynchronity in benchmarking progress callback 

### ISSUE THREAD

**Issue by littletof** [denoland/deno_std#661]
There is a progress callback in `std/testing/bench`.

I'm making a test/example lib in which I want to test any usecases that i can think of, to make sure the API is capable of doing it. Every `sync` stuff in the callback is working fine.

I want to make sure it works with **`async`** too, because its needed in usecases with eg. GUIs or where you want to publish the progress with http calls.
This is not a big problem, as this can be achived making the callback an async function, then await it when calling it inside benching.
This means benchmarking will halt until the completion of the callback. (as it is doing right now with sync callback)

### But here comes my issue.
If I want to fire-and-forget a Http call, or want to use setTimeout or setInterval (for example spinning a spinner in cmd until the next progressCb arrives) I currently cant use it, because the benches are run in a **`while(true)`**, so everything like this will be executed after all the benchmarking finished, if I understand it correctly. (Or is just my lib implementation bad?)

Is there a nice way to solve this?
Benchmarking on different threads could be good, but would need a bigger refactor I think, and Im currently not so sure how I would do it.

**Comment by bartlomieju** [comment]
I'm still open to this feature, if anyone wants to implement it feel free to open a PR so we can discuss it in detail.

**Comment by littletof** [comment]
Regarding the last lines from the original issue about multiple threads for the benchmarking itself, aka parallel running, I've found that it was considered before, but it was discarded as it can impact the results: https://github.com/denoland/deno_std/pull/203#issuecomment-465164761

With this, I think there could be a way to implement the described functionality the issue asks for, but maybe not with paralell running.

**Comment by bartlomieju** [comment]
@littletof that sounds good to me. If we can get a reliable solution then we can punt on the parallel aspect for now.

**Comment by iuioiua** [comment]
@bartlomieju, is this able to be closed? Benchmarking is now native and has the `parallel` option.
