### ISSUE TITLE
Implement std/node/util isDeepStrictEqual

### ISSUE THREAD

**Issue by pevers** [denoland/deno_std#662]
`isDeepStrictEqual` is not yet supported from Node's util library: https://nodejs.org/dist/latest-v14.x/docs/api/util.html#util_util_isdeepstrictequal_val1_val2

Implementation can be found here and should be added to the Deno std library + tests: https://github.com/nodejs/node/blob/master/lib/internal/util/comparisons.js

I would like to take this task upon me if adding this is fine.

**Comment by standvpmnt** [comment]
@bartlomieju I'd like to take a stab at this, I'll just review the node implementation and come back if I need any help (most likely with the types I think).

**Comment by standvpmnt** [comment]
I have opened a draft PR #1556 as I wasn't very confident while working on this so I thought I'd get some opinions on it to check if I was in the right direction. My concerns with the current code are, (besides the obvious failing tests) :

1. I was unable to figure out where to find how exactly some of the primordials from Nodejs were implemented and hence I am not sure how to implement these, primarily I am referring to: `SafeSet`, `SafeMap`, `TypedArrayPrototypeGetSymbolToStringTag`
2. I couldn't find a good resource to understand what the code and documentation mean when they say "Tag" specifically I am referring to line 128 in the code [here](https://github.com/nodejs/node/blob/master/lib/internal/util/comparisons.js), if anyone could guide me in this regard I can try again on this, as one of the failing test is arising from an implementation of this.
3. Some imports in the node implementation use the internal bindings, I am not sure what exactly these methods do as I was unable to find them, do we have any equivalent for these in Deno api or the standard library. Specifically I am referring to `const {getOwnNonIndexProperties} = internalBinding('util');` and `const { compare } = internalBinding('buffer');`
4. I would definitely need some guidance on figuring out how to create test cases for Buffers and TypedArrays
5. I am not sure what needs to be done with regards to copyrights as a lot this code is borrowed from the node/utils 
6. I use a lot of type-coercion to get things to compile, any suggestions or ideas for this would be a big help.

Also please let me know if I am wayyy off the mark here and I'll be happy to work on it with someone more experienced in this regard.

Overall while working on it I thought that this seems like a good enough function to have in the standard library of Deno, can/are we planning to implement this in the standard library directly as well? (can we try the lodash implementation of isEqual for Deno standard?)

**Comment by kt3k** [comment]
@standvpmnt 
I think premordials are from this file https://github.com/nodejs/node/blob/master/lib/internal/per_context/primordials.js

> I couldn't find a good resource to understand what the code and documentation mean when they say "Tag" specifically I am referring to line 128 in the code here, if anyone could guide me in this regard I can try again on this, as one of the failing test is arising from an implementation of this.

I guess tag means `Symbol.toStringTag`, which controls the string representation of the objects

> I would definitely need some guidance on figuring out how to create test cases for Buffers and TypedArrays

I think their test cases are good resources for that https://github.com/nodejs/node/blob/master/test/parallel/test-util-isDeepStrictEqual.js

BTW we also have an infrastructure for running actual Node.js test cases in std. Please see 'Contributing' section of node/README.md https://github.com/denoland/deno_std/tree/main/node#contributing

> I am not sure what needs to be done with regards to copyrights as a lot this code is borrowed from the node/utils

If you copied something from node.js, please add a license header like `// Copyright Joyent and Node contributors. All rights reserved. MIT license.`

**Comment by standvpmnt** [comment]
Great, @kt3k I'll review these and update the PR with this information. Thanks for the help.

**Comment by standvpmnt** [comment]
I was able to use the Node.js test cases instead of the ones that I was creating and have been able to make progress with the help of these tests now, I however am presently stuck on the Boxed Primitve Cases, specifically I am having a tough time figuring out exactly how the `NumberPrototypeValueOf`, `StringPrototypeValueOf`, `BooleanPrototypeValueOf`, etc. methods work. They all come in from primordials, however I couldn't find them in the primordials file. Upon some looking around, my best guess is that these come in from C++, probably from here. Is there a way that I can find how these functions work so that I can try to replicate their functionality in TS? Thanks for the help and patience.
https://github.com/nodejs/node/blob/a37b9c80ef837de5fc99d750c3597d32ad3814b0/deps/v8/src/init/bootstrapper.cc

**Comment by kt3k** [comment]
hmm I couldn't find where these are defined either, but I guess these are just `Number.prototype.valueOf`, `String.prototype.valueOf`, `Boolean.prototype.valueOf` respectively by the naming convention

**Comment by kt3k** [comment]
Found `NumberPrototypeValueOf` is created here (It uses utilities for creating the name `NumberPrototypeValueOf`)
https://github.com/nodejs/node/blob/e31d1cb55da6ad9d05ed98d22164c01501ca2b39/lib/internal/per_context/primordials.js#L168-L213

(Thanks smorimoto for the help)

**Comment by standvpmnt** [comment]
Ok, I think I may know where I am getting stuck. So right underneath the highlight that you have mentioned above, there is a comment which states
```
// Create copies of intrinsic objects that require a valid `this` to call
// static methods.
// Refs: https://www.ecma-international.org/ecma-262/#sec-promise.all
```
So the issue I am facing now is that in order to use `String.prototype.valueOf.call(arg1)` I need to have the `arg1` be a string, however some of the tests for this method check for "coercion" cases. (I am not sure what the exact word is for this). These test cases are failing since arg1 in those cases is not actually a Boolean with the error
```
AssertionError: Failed assertion: error: Uncaught TypeError: String.prototype.toString requires that 'this' be a String
```
So the issue is with these types of "coercion" test cases
```
const booleanish = new Boolean(true);
Object.defineProperty(booleanish, Symbol.toStringTag, { value: "String" });
Object.setPrototypeOf(booleanish, String.prototype);
notUtilIsDeepStrict(booleanish, new String("true"));
```
NOTE: The above code-block cannot be executed in Deno repl as it throws the following error on the last statement.
```
TypeError: String.prototype.toString requires that 'this' be a String
```

**Comment by kt3k** [comment]
@standvpmnt 
BTW we can merge it with some flaws in the edge cases like the above (many node compat APIs have known bugs in edge  cases). Please comment out test cases with `TODO` comment if it's difficult resolve them at the moment.

See [this PR](https://github.com/denoland/deno_std/pull/1592/files), for example, for reference

**Comment by standvpmnt** [comment]
@kt3k I have done the implementation, however the main disadvantage is that there is a function `getOwnNonIndexProperties` which should return all the properties (including symbols) of any object unless they are index values. This is done in C by node project, and I can't figure out a way to identify whether a property is an index or a symbol, as such I have had to return all properties instead for objects that return a false for `Array.isArray()`.

**Comment by F3n67u** [comment]
@standvpmnt FYI. I have implemented `internalBinding.util`'s `getOwnNonIndexProperties` function in https://github.com/denoland/deno_std/pull/1728 and replace the `getOwnNonIndexProperties` function in `comparison.ts` with `internalBinding.util`'s `getOwnNonIndexProperties` function.

**Comment by standvpmnt** [comment]
@kt3k regarding this, the tests that are keeping this issue pending are the ones wherein a type mimics another type. Specifically, the tests actually have a statement which I believe is not permitted in the Deno runtime whereas it is permitted in the Node runtime. As an example this is one of the [test blocks](https://github.com/denoland/deno_std/blob/main/node/_tools/suites/parallel/test-util-isDeepStrictEqual.js#L553-L556) which seem to be creating the issue.
```
const booleanish = new Boolean(true);
Object.defineProperty(booleanish, Symbol.toStringTag, { value: "String" });
Object.setPrototypeOf(booleanish, String.prototype);
notUtilIsDeepStrict(booleanish, new String("true"));
```
In this block the first 2 statement work in both Node and Deno run-time
```
const booleanish = new Boolean(true);
Object.defineProperty(booleanish, Symbol.toStringTag, { value: "String" });
```
however, this 3rd statement works in Node but not in Deno repl
```
Object.setPrototypeOf(booleanish, String.prototype);
```
this fails with the following error
```
TypeError: String.prototype.toString requires that 'this' be a String
    at Boolean.toString (<anonymous>)
    at inspectStringObject (deno:ext/console/02_console.js:908:30)
    at inspectObject (deno:ext/console/02_console.js:1174:14)
    at _inspectValue (deno:ext/console/02_console.js:630:16)
    at inspectValue (deno:ext/console/02_console.js:645:11)
    at Object.inspectArgs (deno:ext/console/02_console.js:1660:30)
    at <anonymous>:3:40
```
It seems that this specific test is not allowed in Deno, am I understanding this correctly or am I missing something?

**Comment by kt3k** [comment]
@standvpmnt 
hmm the 3rd line itself can be executed in Deno if you don't use repl. (The error seems being thrown when it's printed to the console).

The error in assertion seems caused at this toString call:

https://github.com/denoland/deno_std/blob/33253d60ac181a6298af13546a8b605ab282c141/node/internal/util/comparisons.ts#L91

I guess if we could avoid calling this toString depending on some condition, it would pass in Deno. (i'm not 100% sure though..
