### ISSUE TITLE
test asserts great, but missing a `plan` to the number of assertions expected

### ISSUE THREAD

**Issue by aricart** [denoland/deno_std#665]
The assertion package is missing the ability to specify the number of assertions that should be run in a test. With complex non-unit type tests, it is very useful to specify that a test should be running `n` number of assertions, and fail the test if that number of asserts is not run.

**Comment by bartlomieju** [comment]
This is interesting concept and from my knowledge used heavily in Node world. I don't have a strong opinion about it, but calling @dsherret who worked on recent changes to Deno's testing API.

**Comment by kt3k** [comment]
I think the API like this was only useful when there wasn't promise yet in my view. Modern frameworks like mocha, jest don't have this feature. (Correct me if I'm wrong)

**Comment by bartlomieju** [comment]
That's a good data point @kt3k; @aricart do you still feel strongly about this feature?

**Comment by LionC** [comment]
Just my .02€: Currently you *could* do this by just having a mutable and by defining an assert function that increments that and then passes all args on to the actual assert function, which allows you to run assertions on that variable afterwards:

```typescript
let assertions = 0;

const assertFoo = (...args) => {
  assertions += 1
  return assertFoo(...args)
}

// Lots of assertions

assertEquals(assertions, 2341)
```

It is also posisble to write a utility to wrap a function like that and add a `calls` property to it:

```typescript
function makeCallInspectable(fun) {
  const ret = (...args) => {
    ret.calls = (ret.calls ?? 0) + 1
    return fun(...args)
  }

  return ret
}

const myAssert = makeCallInspectable(assert)

myAssert(something)
myAssert(somethingElse)

assertEquals(myAssert.calls, 2)
```

whether such a utility (which starts to touch the whole spies realm) should be in the testing library might be an interesting discussion, but **if** we would want to support that feature, I would suggest to do it in a generalistic spy-style way like that.

**Comment by aricart** [comment]
@bartlomieju to be honest after using Deno now for over a year - I don't think it is required. The assert count is effectively a crutch, and it simplifies some cases, but there are workarounds like a deferred latch that after N number of calls releases or times out.

**Comment by bartlomieju** [comment]
> @bartlomieju to be honest after using Deno now for over a year - I don't think it is required. The assert count is effectively a crutch, and it simplifies some cases, but there are workarounds like a deferred latch that after N number of calls releases or times out.

Thanks for the feedback @aricart! Since there's not much interest in this feature I'm going to close the issue for now, we can always revisit it in the future, but it seems JS world moves towards other patterns.
