### ISSUE TITLE
[std][testing] equal should check type

### ISSUE THREAD

**Issue by paulsouche** [denoland/deno_std#676]
What is the issue ?

```
Deno.test("it should assert if two variables are equivalent", () => {
  assertEquals({}, {});
  assertNotEquals({}, []); // fails
  assertEquals({}, []); // pass
  // Oups ! These are equals...
  // As far as I went, it "works" in chai, jasmine
  // https://github.com/chaijs/deep-eql/blob/fa5c6042e5c127df12e1f3ee4b9f9b3e2302864c/index.js#L184
  // https://github.com/jasmine/jasmine/blob/master/lib/jasmine-core/jasmine.js#L4624
  // and jest but did not digwhy...
});
```

So I am just wondering if this is an expected behavior ? If so feel free to close this issue. If not, I think that std should have a deep-eql implementation. Should it go to std/testing ? Or to std/util ?. Please let me know about this ! I can surely do a PR on this implementation.

Thank you anyway for the great job !

**Comment by lowlighter** [comment]
I think we should just add a prototype check in `equal()` function just before entering `compare()` function like below:
```diff
export function equal(c: unknown, d: unknown): boolean {
+  if ((typeof c === "object")&&(typeof d === "object")&&(c?.constructor.name !== d?.constructor.name))
+    return false
  const seen = new Map();
```

Even with JavaScript weird typing, the mentioned assertion should be false: 
```
> ({}) == []
false
> [] == ({})
false
```

**Comment by kt3k** [comment]
Now `assertEquals` checks for constructors (ref: #1000). `assertEquals({}, [])` doesn't pass anymore.
