### ISSUE TITLE
std/flags: Arg with `---` parsed as true

### ISSUE THREAD

**Issue by brandonkal** [denoland/deno_std#677]
It makes sense why this is happening but I am not sure if this is desired behavior.

For instance: `deno program.ts "$(cat file.yaml)"` will parse as { "-": true }.
It appears to be assuming a flag of "-" and then because nothing is attached to stdin it just returns true. It would be better if text that starts with "---\n" ends in the "_" array. I can't imagine a situation where one would want an argument named "-".

**Comment by bartlomieju** [comment]
This issue is quite stale and I don't have any strong opinion either way. I'm going to tentatively close it, please comment if this is still a problem for you use cases.
