### ISSUE TITLE
Add sync version of std/io readLines

### ISSUE THREAD

**Issue by luvies** [denoland/deno_std#680]
It would be useful to provide a function that can read a line of input from stdin that has a simple interface. It would probably good to support both async and sync versions, something like

```ts
const name: string = await Deno.readLine('What is your name? ');
const age: string = Deno.readLineSync('What is your age? ');
```

I think `readLine` might be too close to the file functions, so maybe something like `getInput` or `ttyReadLine`

**Comment by bartlomieju** [comment]
I'm still open to this feature, if anyone wants to work on it feel free to open a PR.

**Comment by ccheng** [comment]
@bartlomieju I'd appreciate some feedback or guidance, especially as it relates to this (now old) PR for this issue: denoland/deno#6171.

That PR initially had lots of duplicated code to create a sync version from the async version, but ry wasn't happy with having a bunch of very technical duplicated code .

So I tried a different approach that supported async and sync with no duplicate code.  I think we were [waiting for feedback](https://github.com/denoland/deno/pull/6171#issuecomment-679248003) on this but never heard back.  The PR eventually got outdated and was closed.

It'd be nice to get some feedback on that last approach which had no duplicate code.  If the approach is ok, I might try again with a new PR.

Thanks!

**Comment by kt3k** [comment]
@ccheng 
I saw denoland/deno#6171, but the main type `ReaderMaybeSync = Reader | ReaderSync` looks hard to work with / hard to reason about to my eyes. That requires `as` casting whenever actually do the operations. I think that is an unusual pattern of coding style.

I prefer the first version of denoland/deno#6171 much better https://github.com/denoland/deno/pull/6171/commits/3aa119c7033be9dd9964c809a705905f6f0c6c5b

What do you think? @bartlomieju @ry

**Comment by bartlomieju** [comment]
@kt3k I agree with you, in this case duplicated code is better than trying to get it done in a single function.

**Comment by iuioiua** [comment]
Is this something we'd still like to have? If so, I can give it a crack.

**Comment by kt3k** [comment]
For I/O, we're moving from Reader/Writer interface to [Web Stream](https://developer.mozilla.org/en-US/docs/Web/API/Streams_API) based interface. So, in my view, these `std/io` related issues are half deprecated.

(BTW I think we've never discussed about sync I/O in web stream based world)

@bartlomieju What is your opinion on this?

**Comment by iuioiua** [comment]
> For I/O, we're moving from Reader/Writer interface to [Web Stream](https://developer.mozilla.org/en-US/docs/Web/API/Streams_API) based interface. So, in my view, these `std/io` related issues are half deprecated.

I've seen mention of that. Why's that? Just web compatibility?

**Comment by kt3k** [comment]
> I've seen mention of that. Why's that? Just web compatibility?

Mostly yes. Web Stream is already part of basic builtin Web APIs such as `fetch` (the response body is web stream). So we can't drop Web Stream from Deno. And having two separate I/O system in a single runtime feel confusing and redundant. So we decided to drop Reader/Writer type I/O

**Comment by iuioiua** [comment]
Is sync I/O possible using web streams?

**Comment by crowlKats** [comment]
no, web streams are async

**Comment by kt3k** [comment]
Transition from Reader/Writer to Web Stream was discussed, for example, in this issue https://github.com/denoland/deno/issues/9795

Maybe we were too less concerned about what happens with sync I/O?

**Comment by kt3k** [comment]
Is it possible to extend Web Streams API to have synchronous reader/writer?

**Comment by crowlKats** [comment]
no, as they are promise based on a very deep level; web streams spec adding sync capabilities sounds extremely unlikely

**Comment by iuioiua** [comment]
If sync I/O is still wanted, perhaps Reader/Writer can be repurposed to do that instead of being deprecated.

**Comment by iuioiua** [comment]
It's been over a year since any sentiment in support of this functionality has been expressed. Also, Deno's shifting its focus to streams-based IO.

I think it's safe to say that this feature is longer desired, and this issue can be closed.

**Comment by kt3k** [comment]
I agree. Let's close
