### ISSUE TITLE
Reenable logging test

### ISSUE THREAD

**Issue by ry** [denoland/deno_std#69]
https://github.com/denoland/deno_std/blob/61fdae51a7cc50874b9674c40b1aef3fbf012494/logging/test.ts#L69-L70
https://github.com/denoland/deno_std/commit/5132550c113c7e03081fc64e62f2c1a68ea35a0f

**Comment by bartlomieju** [comment]
Closed with latest improvements to `log` module

**Comment by ry** [comment]
thx
