### ISSUE TITLE
[Bug] Eol crash with multipartform

### ISSUE THREAD

**Issue by darklight9811** [denoland/deno_std#707]
Library module: https://github.com/denoland/deno/blob/std/0.85.0/std/mime/multipart.ts

## What happens
When trying to use the MultipartReader with content, it throws an exception.

## How to reproduce
Send a post request to the server with any formdata
``` typescript
const partReader = new MultipartReader(request.body, decoded);
const data = await partReader.readForm();
```

## Exception
```
error: Uncaught (in promise) UnexpectedEof
        throw new Deno.errors.UnexpectedEof();
              ^
    at MultipartReader.nextPart (multipart.ts:374:15)
    at async MultipartReader.readForm (multipart.ts:285:17)
    at async parseBody (parser.ts:25:16)
    at async Server.getProperties (server.ts:193:14)
    at async Server.run (server.ts:118:23)
error Command failed with exit code 1.
```

**Comment by darklight9811** [comment]
@kitsonk, it wasn't malformed, I actually did two requests to separately get the header and the content. But if you want another example

## content-type
```
multipart/form-data; boundary=--------------------------131205119736745502426837
```

## form-data
```
----------------------------131205119736745502426837
Content-Disposition: form-data; name="key"

test
----------------------------131205119736745502426837--
```

**Comment by bnoordhuis** [comment]
@darklight9811 How are you making the request?

**Comment by darklight9811** [comment]
@bnoordhuis , tried with postman and directly through the browser.

**Comment by darklight9811** [comment]
@kitsonk, any updates? Because you seem to not believe me that this is an issue.

**Comment by bnoordhuis** [comment]
@darklight9811 Your example in https://github.com/denoland/deno_std/issues/707#issuecomment-772471374 has a bug:
```js
	const content 	= await Deno.readAll(request.body);
	const decoded	= await (new TextDecoder()).decode(content);
	const reader 	= new MultipartReader(request.body, decoded);
```
You're reading `request.body` twice but of course the first read consumes it - the second read returns an empty Uint8Array.

Hope that helps, I'll go ahead and close this.
