### ISSUE TITLE
std/node: unable to require "acorn-node"

### ISSUE THREAD

**Issue by kt3k** [denoland/deno_std#723]
The following script throws an error in `acorn-node/index.js`:

```js
import { createRequire } from "https://deno.land/std@0.86.0/node/module.ts";
createRequire(import.meta.url)("acorn-node");
```

```shellsession
$ deno run -A --unstable foo.js
error: Uncaught TypeError: acorn.Parser.extend(...).extend is not a function
  .extend(require('./lib/class-fields'))
   ^
    at Object.<anonymous> (file:///.../node_modules/acorn-node/index.js:6:4)
```

`acorn-node` is depended by tools like [detective](https://www.npmjs.com/package/detective), [tailwindcss](https://www.npmjs.com/package/tailwindcss), [browserify](https://www.npmjs.com/package/browserify), etc

**Comment by Liamolucko** [comment]
It looks like the problem is that `acorn-node` uses `__proto__`:
```js
if ( Parser ) anonymous.__proto__ = Parser;
```

Deno doesn't support `__proto__`, which indirectly causes this issue.

**Comment by kitsonk** [comment]
Yeow...  That feels like an acorn issue that they should address.  `__proto__` is still Annex B (though there is a movement to normailze it, but still allow us to remove it for the security reasons we removed it) and [Annex B states](https://tc39.es/ecma262/):

> This annex describes various legacy features and other characteristics of web browser ECMAScript hosts. All of the language features and behaviours specified in this annex have one or more undesirable characteristics and in the absence of legacy usage would be removed from this specification. However, the usage of these features by large numbers of existing web pages means that web browsers must continue to support them. The specifications in this annex define the requirements for interoperable implementations of these legacy features.
>
> These features are not considered part of the core ECMAScript language. **Programmers should not use or assume the existence of these features and behaviours when writing new ECMAScript code.** ECMAScript implementations are discouraged from implementing these features unless the implementation is part of a web browser or is required to run the same legacy ECMAScript code that web browsers encounter.

_emphasis mine_

**Comment by Liamolucko** [comment]
It looks like it's already fixed on master actually, they just haven't published a new version since then. 

The `__proto__`s were being inserted by `buble`, but they've since switched to `babel` which only uses them as a fallback.

**Comment by kt3k** [comment]
Thank you for the researches and inputs! Based on the above observations, I added a [polyfill](https://github.com/webcarrot/proto-polyfill) of `__proto__` before requiring `acorn-node`, and it worked!

```js
import { createRequire } from "./node/module.ts";
import "https://raw.githubusercontent.com/webcarrot/proto-polyfill/1.7.0/index.js";
console.log(createRequire(import.meta.url)('acorn-node'));
```

The above script successfully printed out the exports of `acorn-node`.
