### ISSUE TITLE
What's the problem of the git history, the commit time is invalid, all setting to 2021-02-01

### ISSUE THREAD

**Issue by lygstate** [denoland/deno_std#725]

**Comment by lucacasonato** [comment]
The git history was migrated from denoland/deno to denoland/deno_std on Feb 1st. That is why the commit time is Feb 1st.

**Comment by lygstate** [comment]
> The git history was migrated from denoland/deno to denoland/deno_std on Feb 1st. That is why the commit time is Feb 1st.

You misunderstnd me, as all date are setting to Feb 1st, that's would cause people hard to blame history, It's better to preserve the orignal commit date rather than a single date

**Comment by Nemo157** [comment]
_Commit date_ should update when history is modified, the _author date_ remains the same

```
> git show 3b352a3e898fe2ec9a5e18211d6436098e696fc4 --format=fuller
commit 3b352a3e898fe2ec9a5e18211d6436098e696fc4
Author:     Yoshiya Hinosawa <stibium121@gmail.com>
AuthorDate: Tue Jan 12 16:51:10 2021 +0900
Commit:     denobot <propelml@gmail.com>
CommitDate: Mon Feb 1 10:46:59 2021 +0000
```

The problem is in GitHub's UI, which only shows the commit date, even when it is significantly different to the author date.
