### ISSUE TITLE
Proposal: Formatting features to create descriptive error messages

### ISSUE THREAD

**Issue by getspooky** [denoland/deno_std#727]
The `Errorf` function lets us use formatting features to create descriptive error messages.

**Comment by bartlomieju** [comment]
Please expand your proposal: what the API would look like? What is the use case? At the moment this issue is non-actionable.

**Comment by lino-levan** [comment]
@getspooky could you elaborate on this proposal?

**Comment by iuioiua** [comment]
Closing as this has gone stale. Please feel free to re-open this if you'd like to elaborate. Thank you.
