### ISSUE TITLE
serveTLS: requests are not completed by the browser and time out

### ISSUE THREAD

**Issue by timonson** [denoland/deno_std#750]
It is impossible to serve a website with `serveTLS` because some subsequent file requests originating from the html file are not completed.

I made a minimal reproduction consisting of an html and a gif file. 

Run it with:

```bash
sudo deno run --allow-net --allow-read https://deno.land/std/http/file_server.ts -p 443 -c /etc/letsencrypt/live/domain.com/fullchain.pem -k /etc/letsencrypt/live/domain.com/privkey.pem
```

It is important to mention that I tested it with different static file servers and the behavior is always the same: The browser will not finish loading the page.

This behavior only happens with deno versions 1.7.1 and higher. When you downgrade deno to 1.7.0 everything works like expected (besides that the server crashes after a few hours but that's another issue).

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" href="data:," />
    <title>Bug</title>
  </head>
  <body tabindex="0">
    <img src="./drawkit-grape-pack-illustration-1-transcode.gif" alt="" />
  </body>
</html>
```

![drawkit-grape-pack-illustration-1-transcode](https://user-images.githubusercontent.com/54777088/108891854-82719180-760f-11eb-8675-0bda42148ac5.gif)

**Comment by kt3k** [comment]
I was able to reproduce this with 1.7.1 and above and also I confirmed this doesn't happen with 1.7.0. (The above gif stops animating in first a few frames in 3 browsers (chrome, firefox, safari). Firefox reports "Image corrupt or truncated.")

ref: The list of commits between 2 versions: https://github.com/denoland/deno/compare/v1.7.0...v1.7.1

**Comment by kt3k** [comment]
works: https://dl.deno.land/canary/c8a5e3c1e485915880bd5ed10438ac87baf4a80b/deno-x86_64-unknown-linux-gnu.zip
doesn't work: https://dl.deno.land/canary/98878bd81231a631c494b6767576097f945eb813/deno-x86_64-unknown-linux-gnu.zip

Seems caused by https://github.com/denoland/deno/pull/9118/files
