### ISSUE TITLE
Collect and upload code coverage from tests

### ISSUE THREAD

**Issue by caspervonb** [denoland/deno_std#753]
The `deno coverage` subcommand with lcov as an output format landed in canary today.

So lets make use of that and integrate code coverage with this repository.

We can use a third party service like codecov.io, they provide checks like these on pull requests:
![image](https://user-images.githubusercontent.com/157787/109018535-2d0eb080-76f3-11eb-8f32-7542d0ed66b4.png)

Their output look like this https://codecov.io/gh/caspervonb/deno_std_codecov/tree/3fe8e7eed5bdadedf51a75181fa4c4f84702745a when rendered on their site.

I looked at a couple of other providers like coveralls.io but codecov.io seems "better".

(I will do this, raising it for visibility and feedback)

**Comment by kt3k** [comment]
I prefer codecov to coveralls. Codecov's report gives better visual idea about which part is covered and which part is not.

Example of coveralls report here. It doesn't show the coverage rate of directory. It only shows the rate for each file.
<img width="1136" alt="スクリーンショット 2021-02-25 0 30 10" src="https://user-images.githubusercontent.com/613956/109024453-22f3ae80-7701-11eb-90c8-cbbedd0d3565.png">

CI integration of codecov is also better than that of coveralls. Codecov only requires single line of bash for the integration, but coveralls seems requiring custom GitHub action, which seems more complex than codecov.
