### ISSUE TITLE
Using Deno's gzip decompression for tar.gz/etc

### ISSUE THREAD

**Issue by heyheyhello** [denoland/deno_std#759]
Is there a way to leverage the internal zlib gzip decompress to be able to read gzip data? I'm trying to do what is done in Go here: https://github.com/gzuidhof/starboard-cli/blob/master/starboard/internal/npm/extract.go which unpacks a tar.gz file, which is a very common format, and deno_std supports tar but not gz.

Relevant issues:
- https://github.com/denoland/deno_std/issues/376 Closed. Offers to use "pako" in JS.
- https://github.com/denoland/deno_std/issues/588 Closed. Mentions that it might be part of deno/core and not deno/std?
- https://github.com/denoland/deno/issues/4071 Open. Possibly hung up waiting for [_Compression/Decompression Streams_](https://chromestatus.com/feature/5855937971617792)

Seems the current best approach is to use:
```ts
import { gzipSync, gunzipSync } from "https://cdn.skypack.dev/fflate";
```

Which adds a lot of overhead considering Deno does this for import and fetch: https://github.com/denoland/deno/blob/main/cli/tests/053_import_compression/main.ts

Is there any way to leverage Deno's internals?

Haven't tested but maybe piping a local tar.gz into fetch (?) could cause it to return the ungzipped tar file. For Deno projects already hosting a webserver it might make sense to serve+request the tar.gz with custom headers to do this?

**Comment by 101arrowz** [comment]
> Haven't tested but maybe piping a local tar.gz into fetch (?) could cause it to return the ungzipped tar file. For Deno projects already hosting a webserver it might make sense to serve+request the tar.gz with custom headers to do this?

The overhead of the HTTP request outweighs the benefit of using the native bindings. However, I implemented this idea, and it does work.

```js
import { serve } from "https://deno.land/std@0.88.0/http/server.ts";

const server = serve({ hostname: "0.0.0.0", port: 8080 });

// Any GZIPped data
const dat = await Deno.readFile('dat.gz');
fetch('http://localhost:8080').then(res => res.arrayBuffer()).then(v => console.log(new Uint8Array(v)))
for await (const req of server) {
  req.respond({
    headers: new Headers({
      'Content-Encoding': 'gzip',
      'Content-Type': 'image/bmp'
    }),
    body: dat
  });
}
```

From my tests, this is 3x slower than `fflate`.

**Comment by heyheyhello** [comment]
Thanks for testing that out! Native is definitely necessary. I'll use JS fflate in the meantime. Much better than dealing with OS specific subprocesses or WASM.

**Comment by heyheyhello** [comment]
Closing because fflate is so small and so fast that I imagine native bindings will bloat the binary more than fflate does (8kb). Luca has a binary size breakdown at https://github.com/denoland/deno/issues/9243

**Comment by jespertheend** [comment]
CompressionStream and DecompressionStream is now supported:
https://github.com/denoland/deno/issues/7113
