### ISSUE TITLE
createHash memory leak

### ISSUE THREAD

**Issue by shamblesides** [denoland/deno_std#786]
Discovered this because pbkdf2 from node/crypto was leaking memory, but the hash module seems to be the source. This script increases in memory at a rate of 50MB/s on my machine, indefinitely (I stopped it at 1GB):

```js
import { createHash } from "https://deno.land/std@0.89.0/hash/mod.ts"

while (1) {
  createHash('sha512')
}
```

It appears to happen with any hash, not just sha512.

Verison info

```
$ deno --version
deno 1.8.0 (release, x86_64-unknown-linux-gnu)
v8 9.0.257.3
typescript 4.2.2
```

**Comment by heyheyhello** [comment]
I think it's because it's instantiated in WASM rather than in JS.
 https://www.github.com/denoland/deno_std/tree/main/hash%2F_wasm%2Fwasm.js

It looks like you can call `free()` manually which should help.

**Comment by shamblesides** [comment]
For my particular use case, I guess that means there will need to be a PR that adds the free() call somewhere around here: https://github.com/denoland/deno_std/blob/main/node/_crypto/pbkdf2.ts#L33

**Comment by heyheyhello** [comment]
Hmm well createHasher returns an anonymous function, so you could add free as a property to the function so it would be available to manually call.

**Comment by shamblesides** [comment]
Actually it looks like this won't work without changes to the hash module itself.

The public module function, createHash:

https://github.com/denoland/deno_std/blob/main/hash/mod.ts#L34

returns a Hash object:

https://github.com/denoland/deno_std/blob/main/hash/_wasm/hash.ts#L19

and the Hash object has a private property called `#hash` which is from a completely different function called createHash which is generated by wasm:

https://github.com/denoland/deno_std/blob/main/hash/_wasm/hash.ts#L24

so if I want to call free() I have to access private properties on a class defined within the _wasm folder, which seems like a hack to me.

**Comment by caspervonb** [comment]
`digest` from `crypto.subtle` should superceede this by 1.9

**Comment by shamblesides** [comment]
Sounds good, then I will wait for `crypto.subtle`

Do you think `deriveKey` will also be available? That's the interface I'm really wanting to use, for PBKDF2

**Comment by caspervonb** [comment]
Probably https://github.com/denoland/deno/pull/9614
