### ISSUE TITLE
Default options for path/glob and fs/expand_glob differ

### ISSUE THREAD

**Issue by dsherret** [denoland/deno_std#794]
Not sure if this was done on purpose, but the defaults for the `extended` and `globstar` options in path/glob/`globToRegExpr`...

https://github.com/denoland/deno_std/blob/27dcc84ae1fdafa32eb77a9ab2caaa768ccea2f6/path/glob.ts#L83

...and fs/expand_glob/`expandGlob`:

https://github.com/denoland/deno_std/blob/27dcc84ae1fdafa32eb77a9ab2caaa768ccea2f6/fs/expand_glob.ts#L79

...are the opposite. Perhaps it would be better to use the same defaults for both?

**Comment by lowlighter** [comment]
Since `expandGlob`, `expandGlobSync` and `joinGlobs` all default to false and `globToRegExp` is the only one to defaults to true, maybe it would be more logical to make the default to false?
