### ISSUE TITLE
Missing encoding/utf-8 ?

### ISSUE THREAD

**Issue by xReveres** [denoland/deno_std#801]
After 1 month ? I decided to upgrade my project to newest deno version, but now I have error:
```
error: Import 'https://deno.land/std@0.90.0/encoding/utf8.ts' failed: 404 Not Found
```
Where is utf8 ? I can't find any information in releases.

**Comment by crowlKats** [comment]
It has been removed a while ago as it was redundant as one can just use TextDecoder/TextEncoder directly
