### ISSUE TITLE
Problem serving large static files over HTTPS

### ISSUE THREAD

**Issue by aegooby** [denoland/deno_std#809]
I am running an HTTPS server using the `http` module from the Deno standard library using `serveTLS()`. Where I am running into trouble is that I am using a fairly large (over 250kB) JavaScript bundle on the client side that I want to serve to visitors of my site. Over plain HTTP, this works perfectly. However, once I try to use HTTPS, files above a certain size will simply fail to load to completion on the client side. I switched to using chunked responses for large files, which allowed them to load a bit more of the file, but still never to completion. This issue happens somewhere in `request.respond()`, although I am unable to figure out why.

I am doing something similar to this:
```
const body = await Deno.open(filePath, { read: true });
const info = await Deno.stat(filePath);

// Clean up file RID
request.done.then(function () { body.close(); });

const headers = new Headers();

if (info.size > 0x4000)
    headers.set("transfer-encoding", "chunked");
else
    headers.set("content-length", info.size.toString());

// Set content-type
// ...
const response: http.Response =
{
    status: status,
    headers: headers,
    body: body,
};

request.respond(response);
```

Is this a bug in Deno, or am I just doing something wrong?

UPDATE: this seems to be linked to #750 as well, confirming my suspicion that it is directly linked to file size somehow.

**Comment by bartlomieju** [comment]
`std/http` implementation was rewritten to leverage native HTTP bindings available in Deno (`Deno.serveHttp`). This error should no longer occur. I'm going to tentatively close this issue, please let me know if the problem persists.
