### ISSUE TITLE
TOML parser's inline/nested tables misaligned with real TOML

### ISSUE THREAD

**Issue by danopia** [denoland/deno_std#823]
I'm comparing this TOML parse with http://toml-online-parser.ovonick.com

First opened here because I'm dumb: https://github.com/denoland/deno/issues/9919

## case 1

This is proper TOML (AFAIK) that parses correctly elsewhere:

```toml
annotation_filter = { "kubernetes.io/ingress.class" = "nginx" }
```

... but Deno's parser tries reading as JSON:

```
> TOML.parse(`annotation_filter = { "kubernetes.io/ingress.class" = "nginx" }`);
error: Uncaught SyntaxError: Unexpected string in JSON at position 31
      return JSON.parse(dataString);
                  ^
    at JSON.parse (<anonymous>)
    at Parser._parseInlineTableOrArray (https://deno.land/std@0.91.0/encoding/toml.ts:322:19)
    at Parser._parseData (https://deno.land/std@0.91.0/encoding/toml.ts:275:21)
    at Parser._processDeclaration (https://deno.land/std@0.91.0/encoding/toml.ts:264:24)
    at Parser._parseLines (https://deno.land/std@0.91.0/encoding/toml.ts:492:25)
    at Parser.parse (https://deno.land/std@0.91.0/encoding/toml.ts:541:10)
    at Module.parse (https://deno.land/std@0.91.0/encoding/toml.ts:735:33)
```

## case 2

As a work around, I tried this non-inline syntax instead:

```toml
[[aaa]]
hi = "hi"
[aaa.bbb]
asdf = "asdf"
```

... but the key just silently gets lost:

```
> TOML.parse(`[[aaa]]\nhi = "hi"\n[aaa.bbb]\nasdf = "asdf"`)
{ aaa: [ { hi: "hi" } ] }
```

I was expecting:

```json
{ "aaa": [ {
            "hi": "hi",
            "bbb": {
                "asdf": "asdf"
            }
} ] }
```

## case 3

This actually works with Deno as of std@0.91.0:
```toml
[[source]]
annotation_filter = { "\"kubernetes.io/ingress.class\"": "nginx" }
 # also this comment is read as a key because of leading spaces = "..."
```

That last line seems to be included because of some parsing bug:

```
> TOML.parse(`[[source]]\nannotation_filter = { "\\"kubernetes.io/ingress.class\\"": "nginx" }\n # also this comment is read as a key because of leading spaces = "..."`)
{
  source: [
    {
      annotation_filter: { "kubernetes.io/ingress.class": "nginx" },
      "# also this comment is read as a key because of leading spaces": "..."
    }
  ]
}
```

**That inline table is not valid TOML** and yet it parses ok so I've been using it anyway 😒

**Comment by wgmyers** [comment]
On the comment issue - lines 45-47 of `encoding/toml.ts` parse full line comments as follows:

```
    function isFullLineComment(line: string) {
      return line.match(/^#/) ? true : false;
    }
```

Only comments without leading whitespace are handled. So this should fix it:

```
    function isFullLineComment(line: string) {
      return line.match(/^\s*#/) ? true : false;
    }
```

On the keys issue - the TOML spec is clear that keys MAY be quoted:

https://toml.io/en/v1.0.0#keys

Inline tables are handled in `_parseInlineTableOrArray` on line 303 of toml.ts, and keys, iiuc, are extracted on line 313 with the following:

```
const reg = /([a-zA-Z0-9-_\.]*) (=)/gi;
```

Rewriting this to handle optional single or double quotes seems tricky but doable.

**Comment by danopia** [comment]
I've built a basic page that makes it easier to compare several javascript TOML parsers: https://cloudydeno.github.io/encoding-playground/toml.html

Several deeplinks:

* [case 1 - inline table with quoted key](https://cloudydeno.github.io/encoding-playground/toml.html#table%20=%20%7B%20%22hello%22%20=%20%22world%22%20%7D%0A); also rejected by toml 0.4.0 impl, accepted by toml 0.5.0 impl
* [case 2 - table nested within table array](https://cloudydeno.github.io/encoding-playground/toml.html#%5Ba%5D%0A%5Ba.c%5D%0Az%20=%20%22z%22%0A%0A%5B%5Bb%5D%5D%0A%5Bb.c%5D%0Az%20=%20%22z%22) shows the array being the breaking point, while both other impls have agreement
* [case 3 - jsony inline table](https://cloudydeno.github.io/encoding-playground/toml.html#annotation_filter%20=%20%7B%20%22%5C%22kubernetes.io/ingress.class%5C%22%22:%20%22nginx%22%20%7D%0A) shows tomls from NPM rejecting the jsony syntax that deno_std accepts. I'm not too sure how/when deno_std accepts json, or why the key needs to be double quoted to be unmangled.
* [case 3b - leading space comment](https://cloudydeno.github.io/encoding-playground/toml.html#%20#%20comment%20=%20%22...%22%0A) pretty straightforward. And the fix as mentioned above is likely pretty clean for this.

I also noticed [case 4 - quoted basic keys](https://cloudydeno.github.io/encoding-playground/toml.html#'__%5Cn__'%20=%204%0A%22__%5Cn__%22%20=%204) getting double-escapes and inner quotes out of deno_std depending on the outer quotes used, both misaligned with the NPM packages.

I haven't submitted code here before; would it make most sense for me to fix one thing at a time in individual PRs?

**Comment by FujiHaruka** [comment]
I'm working on the fix for above cases. I'll create a PR 👻
