### ISSUE TITLE
std/wasi: Allow user to emulate a virtual filesystem without having to provide `preopens`

### ISSUE THREAD

**Issue by KSXGitHub** [denoland/deno_std#827]
## What's wrong with `preopens`?

* It is slow for a large directory (not all items in the directory is going to be read by the WASM program).
* It is inflexible.
* For a trusted WASI program, having to specify `preopens` is unnecessary.

## Suggestions

Allow user to emulate a virtual filesystem by providing necessary `Deno`-like functions (such as `readFile`, `readDir`, `stat`, `lstat`, etc.).

**Comment by bartlomieju** [comment]
CC @caspervonb is this something we should pursue?

**Comment by caspervonb** [comment]
Great thing is that the implementation is pluggable, just instantiate a different adapter so no imo Deno's interface should be tied into system calls with the goal of eventually making them zero overhead fast calls in the runtime.

**Comment by bartlomieju** [comment]
Sounds good. I'm going to close this issue for now; I think it should be left to 3rd party module to integrate it.
