### ISSUE TITLE
Refactor `node/fs`

### ISSUE THREAD

**Issue by majidsajadi** [denoland/deno_std#839]
suggestion for `node/fs` modules.

- either use function overloading or not. some of the modules use this method some don't. I guess consistency in the code makes the library more readable.
- add a reference comment to the node document for each function. (not important)
- strong typing. some of the functions define return type some don't. (should we specify `void` return? )
- some modules don't use `CallbackWithError` type.
- use the same naming convention for parameters. for example use `optionOrCallback` for optional parameters.  
- same format for test names. `[node/fs] async: DESCRIPTION` and `[node/fs] sync: DESCRIPTION`
- use cleaner `Deno.test` API
 
    ```javascript
    Deno.test(message, fn)
    ``` 
    instead of 
    ```javascript
    Deno.test({
      name: message,
      async fn() {
      }
    });
    ```

let me know your opinion.

**Comment by getspooky** [comment]
@majidsajadi 
- `void` and `Promoise<void>` return types are unnecessary boilerplate. Discussion https://github.com/denoland/deno/issues/8832
- Changing `Deno.test API` will cause some breaking changes.

**Comment by majidsajadi** [comment]
@getspooky 
about the void. i agree about the unnecessary `void` return type. but some functions already define `void` as a return type. which i guess we can refactor.

i check most of the tests in `node/_fs` module and i didn't saw any case wich use options other than `fn` and `name` which i guess the clean `Deno.test` api cover that.

**Comment by kt3k** [comment]
Closing as most points are irrelevant now. (We don't provide our own typings anymore. We prefer Node.js native test cases instead of writing our own test cases.)
