### ISSUE TITLE
Proposal: Add Query String module

### ISSUE THREAD

**Issue by getspooky** [denoland/deno_std#844]
`Query string` module will provide utilities for parsing and formatting URL query strings. 
```ts
import { qs } from "https://deno.land/x/querystring/mod.ts";
const query = "a=b&foo=bar";
const json = { a: "b", foo: "bar" };
```

**Comment by crowlKats** [comment]
No need, we have [URLSearchParams](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams).
