### ISSUE TITLE
List of connected WebSocket clients.

### ISSUE THREAD

**Issue by marktyers** [denoland/deno_std#848]
In order to use the Websockets library its vital that the server has access to a list of the connected clients. In NodeJS implementations there is an object called was.clients but there does not appear to be an equivalent in the deno implementation.

**Comment by bartlomieju** [comment]
This issue is no longer relevant since `Deno.upgradeWebSocket` API is available and `ws` module is deprecated and soon to be removed (https://github.com/denoland/deno_std/issues/1544)
