### ISSUE TITLE
circular dependency on std/path

### ISSUE THREAD

**Issue by buttercubz** [denoland/deno_std#857]
I was working with rollup and detected a circular dependency in `path/mod.ts`
![image](https://user-images.githubusercontent.com/47539192/114952279-f23c1580-9e23-11eb-91f2-5bb51d4f01f9.png)

**Comment by wperron** [comment]
Do you have a quick repro? I tried getting the error locally but couldn't. Is it just something with Rollup specifically?

**Comment by buttercubz** [comment]
> Do you have a quick repro? I tried getting the error locally but couldn't. Is it just something with Rollup specifically?

basically i was importing join function from path and using [drollup](https://deno.land/x/drollup) as bundle
