### ISSUE TITLE
Windows CI should use a fixed version of deno

### ISSUE THREAD

**Issue by ry** [denoland/deno_std#86]
https://github.com/denoland/deno_std/blob/2ece847a82bd06eb8810950b3064070135d2d94d/azure-pipelines.yml#L26

cc @srijanreddy98

**Comment by srijanreddy98** [comment]
@ry  This should solve this https://github.com/denoland/deno_install/pull/19

**Comment by ry** [comment]
Fixed in https://github.com/denoland/deno_std/pull/89
