### ISSUE TITLE
`Server.listener.addr.port` is not available

### ISSUE THREAD

**Issue by gamoutatsumi** [denoland/deno_std#868]
I want to get a randomly allocated port.
  
```ts
import { serve } from "https://deno.land/std@0.94.0/http/mod.ts";

const server = serve({ hostname: "127.0.0.1", port: 0 });

console.log(server.listener.addr.port);
```

```bash
$ deno run -A --no-check server.ts
45035
```
  
Got the expected output, but need to use `--no-check` or `@ts-ignore` because `server.listener.addr` only exposes `transport`.
  
The reason seems to be that the constructor `listener` of class `Server` in `http/server.ts` is defined with type `Deno.Listener`.

Why not use `Deno.Listener<Deno.NetAddr>`?

**Comment by morigs** [comment]
As you can see `listener.addr` can be either `NetAddr` or `UnixAddr`. If I'm not wrong Deno doesn't support Unix dockets yet (denoland/deno#4115) , but theoretically it's possible to have HTTP server on Unix socket (Docker exposes its HTTP API on Unix socket for instance, Curl also supports making HTTP requests to Unix sockets). So you cannot be sure which type of socket you are using, you have to check the type of `listener.addr` and the use type-casted value.
But I agree that stronger typing offers better user experience. I think it's possible to make `Listener` interface and `Server` class generic

#1036 kinda related

**Comment by bartlomieju** [comment]
This is now available as `Server.addrs` API.
