### ISSUE TITLE
CI should use a locked version of Deno

### ISSUE THREAD

**Issue by nayeemrmn** [denoland/deno_std#870]
Note for example that the release PR for 0.95.0 (#869) is tested with 1.9.1 which is one behind its supposed companion version of CLI (listed [here](https://github.com/denoland/deno_website2/blob/923ac3cd7335203afcf5c64cdc3373dfbc0e52da/versions.json#L108)). We need to install a specific version of Deno in CI. This should be bumped on an std release, which should wait for its companion CLI version to release and publish first.

---

On a separate note, I've thought more about what purpose the canary tests serve and I don't think they have any business being here. So far what they've done is allow us to see breaking changes in CLI (via random non-deterministic breakages in PRs here) so we can go back and revert them. It's much more sensible to have https://github.com/denoland/deno/pull/9801 for that instead.

What they don't do, is allow us to make adaptive changes in std for intentional breaking changes so std is always compatible with `--canary`. Because when that std change is released to users, there is a fresh CLI release which outdates that `--canary` version and it entirely suffices to adapt when bumping to that.

**Comment by lowlighter** [comment]
To add on canary tests within CI, it seems possible that canary builds are not finished yet when PR is submitted yet resulting in these kinds of errors:

> Looking up latest version
Found latest version 5214acd3d9dec56ee159544f0f6bf9834a62c097
Checking https://dl.deno.land/canary/5214acd3d9dec56ee159544f0f6bf9834a62c097/deno-x86_64-apple-darwin.zip
Download could not be found, aborting
Error: Process completed with exit code 1.

**Comment by kitsonk** [comment]
I would prefer to solve denoland/deno#9801, which means we should fix std _concurrently_ with merges into main.  IMO, std main should run without issues on canary, so CI should continue to use canary.

**Comment by nayeemrmn** [comment]
> IMO, std main should run without issues on canary, so CI should continue to use canary.

This is what I explained, there is no meaning to ensuring that std main runs without issues on Deno canary. The std version that those std changes will be released under are supposed to be compatible with the _next_ Deno version and the canary versions after that.

For example, right now we have Deno 1.9.2 and std 0.95.0. If we discover an incompatibility between Deno 1.9.2+f7c298e and std main which we fix in std, that change is first seen by users in std 0.96.0. What runtime versions will std 0.96.0 be run with? Deno 1.9.3 and canary versions Deno 1.9.3+\<hash>. The current way is nonsensical, and I think this stems from a misunderstanding of the fact that we don't have canary releases for std.

**Comment by lucacasonato** [comment]
> The std version that those std changes will be released under are supposed to be compatible with the next Deno version and the canary versions after that.

Correct. Which proves the point that we _should_ run with canary, as std@main needs to run with deno@main (which is canary).

**Comment by nayeemrmn** [comment]
@kt3k This issue refers to the release checks (which currently use Deno 1.x) and is unrelated to canary checks, it's still very important that we do this.

**Comment by bartlomieju** [comment]
We've been using `canary` version of Deno for over a month and I think it works well. @kt3k @nayeemrmn do you still want to pursue this issue?

**Comment by nayeemrmn** [comment]
With `--compat` we have yet another cyclic dependency between CLI and std (the first being the [version map](https://github.com/denoland/dotland/blob/cd157675e81db0f71adbaa278322bb6b7d7fea2c/versions.json#L151) used for manual rendering) that may become an obstacle for this. I'm not going to push for it. Std is intrinsically a userland library, so it's unfortunate that normal best practices can't be applied and we have non-deterministic CI.
