### ISSUE TITLE
std/encoding/csv.ts - Improve `parse` return type

### ISSUE THREAD

**Issue by dsherret** [denoland/deno_std#881]
Right now it is typed as `unknown[]` (https://github.com/denoland/deno/blob/d199e45ad5dd180a6969abcd528023e173a1e1ff/std/encoding/csv.ts#L392), so in order to figure out what the return type is, I have to either look at the implementation or run it once and check the output. There should be a way to type this properly.

**Comment by lowlighter** [comment]
Would changing function signature to:
```ts
export async function parse<T = unknown>(...): Promise<T[]>
```
Solve your issue?

**Comment by dsherret** [comment]
@lowlighter I'm thinking it could be improved so that it tells the caller what the output is going to be based on the input. `func<T>(): T` is essentially the same as someone having to do `func() as T`

**Comment by lowlighter** [comment]
Maybe I'm missing something but since input is a string like, typing can only be known at runtime no?

**Comment by dsherret** [comment]
@lowlighter right now when `opts.columns` is false and `opts.parse` is false it returns `string[][]`. When `opts.columns` is true it returns `Record<string, unknown>[]`. When `opts.columns` is false and `opts.parse` is true, it returns `unknown[]`.

By the way, one reason this is so complex is because the CSV parsing right now also does data transformation. I feel like it should exclusively do parsing and then someone can apply transformation after using another method. For example, the `parse` option could be removed as it's unnecessary... someone could just take the result and map it...

```ts
// this could be removed in the implementation and instead
// someone can map the result parsing the values
if (opt.parse) {
  return r.map((e: string[]): unknown => {
    assert(opt.parse, "opt.parse must be set");
    return opt.parse(e);
  });
}
```
