### ISSUE TITLE
std/encoding/csv.ts - `stringify` could use improvement and better documentation

### ISSUE THREAD

**Issue by dsherret** [denoland/deno_std#882]
`stringify` in std/encoding/csv.ts takes a lot of reading to figure it out. After looking over the documentation and source code, I've discovered that I need to provide objects then specify what each column is along with how each column should access a property on the objects.

Some suggestions:

1. Unfortunately the property access is not type safe and so it's possible to change a property name and break this code without being notified. The API could be improved if it were type safe between the property names and the objects being provided as this would prevent bugs.
2. It would be nice if there were something analogous to `JSON.stringify(data)` here, where I can just have `data` in memory being `string[][]` and then do `stringify(data)` and get the result. I don't want to bother having to specify column names and property names on an object.
3. It might be easier to understand if there were some examples, but I think examples wouldn't be required if it wasn't so complex.

By the way, a simple API I've found for csv parsing and stringifying is https://www.npmjs.com/package/csv-string -- I almost feel like the csv parsing in std should be really simple then people can map the data in and out to objects if they feel like. There's a lot going on right now in there.

**Comment by luk3skyw4lker** [comment]
I'm taking this issue! I'll take a look and see what can I do.

**Comment by luk3skyw4lker** [comment]
About number 2, I think that the best solution would be to move the columns argument into the options object, this way the user could specify which columns he wants in the output and if no option is provided, then all columns will de present into the output.

**Comment by luk3skyw4lker** [comment]
About 1, would be the case to think about adding a generic parameter to stringify to specify the type of the input object or am I wrong? I didn't fully understand the type safety that this funciton would have, can you clarify it for me?

**Comment by luk3skyw4lker** [comment]
And about 3, I think that the examples would do a good job, but I'll take a look at the code you provided as a simple solution and see if it fits into the case. I gave a quick look and at least for me the deno implementation looks simpler, but would benefit from a better documentation.

**Comment by luk3skyw4lker** [comment]
I took a deeper look at the csv-string implementation and it really looks simpler. I still stand with the idea of passing columns through the options object though which it would add some complexity to deno's implementation. What do you guys think? @bartlomieju  @crowlKats @dsherret

**Comment by ralyodio** [comment]
Columns in json objects don’t guarantee order.  I would assume an array of arrays is the only way or possible a “Map” that does retain order in keys.

**Comment by luk3skyw4lker** [comment]
I didn't specifically thought about order, but your suggestion is good. But in this case a normal array wouldn't do the job? Why a array of arrays? Didn't manage to think this through

**Comment by ralyodio** [comment]
Arrays will maintain order. You would just need to add a header array first. So first array is first row and that contains an array of columns. 

You’ll need to add empty spaces for missing cells. 

I think. Map might be better suited here

**Comment by luk3skyw4lker** [comment]
Nice, I got the idea, thanks for your suggestions! I'll make a PR this week with the modifications

**Comment by kamilogorek** [comment]
Fixed in https://github.com/denoland/deno_std/pull/2168
