### ISSUE TITLE
std/fmt/printf.ts - print incorrect output on the floating number

### ISSUE THREAD

**Issue by vi117** [denoland/deno_std#918]
```typescript
import {printf} from "https://deno.land/std@0.96.0/fmt/printf.ts";
//it print 0.000
printf("%.3f",0.9999);
//it print 0.0
printf("%.1f\n",0.99);
//it print 1.000
printf("%.3f\n",1.9999);
```
In golang
```go
func main() {
    fmt.Printf("%.3f", 0.9999)
    //it print 1.000
} 
```

**Comment by majidsajadi** [comment]
The reason for this behavior is that `roundFractionToPrecision` ignores the carry. 

https://github.com/denoland/deno_std/blob/69245d3dc8c95ec30769f55fd71ee12a9645b88f/fmt/printf.ts#L512

If this behavior is not intended, I can send a PR and fix this issue.
