### ISSUE TITLE
todo: enable `NoUncheckedIndexedAccess` TS compiler option

### ISSUE THREAD

**Issue by AZMCode** [denoland/deno_std#937]
I'm aware this is a controversial topic, however I would find it useful if Deno's std library was compatible with Typescript's new noUncheckedIndexedAccess flag, since I find my projects that use it severely handicapped. I believe dropping some assertions throughout the code (after patching assert itself), or using less indexes should be enough.

**Comment by kitsonk** [comment]
My personal opinion is that I don't mind having `noUncheckedIndexedAccess` "clean" code for `std`, I just wouldn't want to make it the default for the Deno CLI.

**Comment by iuioiua** [comment]
I think we should add this. PRs are welcome!

**Comment by iuioiua** [comment]
Closing this in favour of #4040. Thank you for the input, guys!
