### ISSUE TITLE
Test output hides diff on long strings in objects

### ISSUE THREAD

**Issue by wperron** [denoland/deno_std#939]
When comparing two objects that contain long strings with `assertEquals`, the strings get truncated for readability, but that ends up hiding the Exected / Actual diff in some cases.

[Here](https://gist.github.com/wperron/f4a7bf79172f5c354d5c75850bb7d511) is a quick gist that demonstrates the issue

**Comment by lowlighter** [comment]
I think it's more suited to be deno runtime issue instead

Looking at [Deno.InspectOptions](https://doc.deno.land/builtin/stable#Deno.InspectOptions) and both [NodeJS#util.inspect](https://nodejs.org/api/util.html#util_util_inspect_object_options) features, we're missing `maxStringLength`.

This causes the message to be truncated before entering the actual std `diff()` function:
```
{
  foo: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the ...",
}
```

**Comment by bartlomieju** [comment]
@kt3k any idea how we can tackle this problem?

**Comment by kt3k** [comment]
I think @lowlighter's suggestion is reasonable. We should add `maxStringLength` option to Deno.InspectOptions (in CLI repo) and setting that value to `Infinity` should resolve this issue

**Comment by bartlomieju** [comment]
> I think @lowlighter's suggestion is reasonable. We should add `maxStringLength` option to Deno.InspectOptions (in CLI repo) and setting that value to `Infinity` should resolve this issue

I'm in favor of that.

**Comment by iuioiua** [comment]
Is this different from the [`InspectOptions.breakLength`](https://deno.land/api@v1.38.2?s=Deno.InspectOptions#prop_breakLength) property?
