### ISSUE TITLE
Websocket error (Invalid frame header)

### ISSUE THREAD

**Issue by Peanets** [denoland/deno_std#944]
It looks like sending a WebSocket message of exactly 65535 bytes (0xffff) creates an error in Chrome (invalid frame header) and closes the connection. Here is the line causing the issue : https://deno.land/std@0.97.0/ws/mod.ts#L122

From what I understood, the payload is split in two groups (the second group is empty) and creates the error in the browser ?

**Comment by bartlomieju** [comment]
`std/http` and `std/ws` implementations were rewritten to leverage native HTTP bindings available in Deno (`Deno.serveHttp`). This error should no longer occur. I'm going to tentatively close this issue, please let me know if the problem persists.
