### ISSUE TITLE
No obvious / simple / elegant way to proxy incoming requests?

### ISSUE THREAD

**Issue by mitranim** [denoland/deno_std#950]
Got a Deno app that proxies _some_ of the incoming requests to another server. This seems like a very common use case, and I was surprised being unable to find an existing solution!

As the raison d'être of service workers, web APIs make it easy:

```js
event.respondWith(proxy(event.request))

async function proxy(req) {
  const res = await fetch(req)
  if (res.ok) cache.put(req, res.clone())
  return res
}
```

But right now, we seem to be stuck with `std/http` for _handling_ requests and `fetch` for _making_ requests, where the request/response/stream APIs appear to be incompatible!

This can be worked around, by manually converting request/responses, using `readableStreamFromReader` and `readerFromIterable` to convert between the stream implementations and adapting `req.done` into `AbortController`/`AbortSignal`. There might be other tricky gotchas I haven't thought of yet.

We might be able to agree that this common (?) case should be covered by the standard library.

**Comment by lucacasonato** [comment]
The new unstable native HTTP bindings have a very similar API to service workers, and make use of web standard request and response. See https://deno.land/manual@v1.10.3/runtime/http_server_apis

**Comment by mitranim** [comment]
Yes, thanks for the pointer. I've looked into that, but it seemed either immature or incompatible. For example, for serving files, you'd expect `Deno.open` to give you a `ReadableStream` fit for a `Response` body, but currently Deno files don't implement that interface. Also, `Request` is lacking an abort signal, making it impossible to cancel work when the client disconnects. So, I'm not sure if that's viable yet.

**Comment by mitranim** [comment]
Remembered another incompatibility: for implementing an event stream (one of my actual use cases), you need being able to write to the response stream more than once. Again, appears to be missing from the new "web-aligned" API.

**Comment by mitranim** [comment]
Nice! Thanks for letting me know. 🙂 Will be useful when the other blockers are cleared (mainly `req.signal`).

**Comment by ry** [comment]
@mitranim Please see https://github.com/denoland/deno/issues/7019 for `req.signal` support. We'll see if we can't get it in soon.

**Comment by mitranim** [comment]
Thanks for the tip! Wasn't aware that `fetch` was also lacking abort support. Surprising, you'd think using Rust would make people more attentive to cleanup/cancelation and make it easier. 😅 Very much looking forward to seeing it land!

**Comment by lucacasonato** [comment]
I thought you were talking about abort support in fetch... how would you want abort support in the server to work?

**Comment by kitsonk** [comment]
@mitranim you might also want to look at oak for some inspiration, especially for the SSE events. It works with both the std and native (and Delpoy) APIs. The proxy middleware though isn't what I think it needs to be, but I will be addressing that in the near future.

**Comment by mitranim** [comment]
> I thought you were talking about abort support in fetch... how would you want abort support in the server to work?

Apologies for being unclear. Clarification:

Canceling work in case of client disconnect requires support in multiple places:

* `req.signal` in web-style `Request` (currently throws with a "not implemented" message). I expect this signal to be _always_ aborted when the request is finished for any reason, like in Go. This would help terminate long-running work, like listening for notifications on some external channel. If not, this can be done at the application level for requests that finish successfully, but premature disconnect can only be signaled by the underlying library/runtime.
* Abort signal must be supported by `fetch`.
* Abort signal must be supported by various other APIs that may be invoked while handling a request (database queries, etc).

My current use case requires just `req.signal` and `fetch` because the Deno backend handles HTML rendering and delegates database work to a Go server. That's where proxying came up.

> you might also want to look at oak for some inspiration

Thanks for the pointer. Might check their SSE if necessary, but Luca's advice might be sufficient. 🙂 Got burned enough by big frameworks to lose any appetite. Nothing but trouble.

**Comment by lucacasonato** [comment]
Oh I get it. That indeed makes a lot of sense. I'll open a second issue for that.

**Comment by kitsonk** [comment]
> Got burned enough by big frameworks to lose any appetite.

Nope totally get it. I did mean it as inspiration. I would really consider the new native APIs though. Because they are based around fetch/service workers, you start to get the things you expect. The biggest gap at the moment though is upgrading a request into a web socket.

**Comment by mitranim** [comment]
Getting the impression that everyone's more interested in moving to "native" HTTP which obviates the issue. Just switched all my apps to it, and it seems to be working, thanks to the recent bugfixes. If stdlib HTTP is considered to be in maintenance mode / deprecated, feel free to close the issue.

**Comment by bartlomieju** [comment]
Closing the issue as `http` module migrated to `Deno.serveHttp` API.
