### ISSUE TITLE
feature request: `flags` should export of a parsed `Deno.args`

### ISSUE THREAD

**Issue by apacheli** [denoland/deno_std#953]
As the title says. Imo this would be good for removing overhead. For example, I have a module that uses `Deno.args` which can modify the behavior. However, I don't want to `parse` it again.

**Comment by kt3k** [comment]
`parse` takes options (like `alias`, `boolean`, `string`, etc) as the 2nd argument, and that changes the parse result. So it's unreasonable to cache parsed result because we don't know the parse options for each usage.

**Comment by bartlomieju** [comment]
I agree with @kt3k, this should be left to the user and API shouldn't be too opinionated in this case. Respectfully declined.
