### ISSUE TITLE
TOML incorrectly serializes mixed-type and nested arrays

### ISSUE THREAD

**Issue by Aplet123** [denoland/deno_std#983]
In the stdlib TOML dumper, arrays whose first element is considered "trivially serializable" (numbers, strings, etc.) are considered to be "trivially serializable", and are thus subject to JSON serialization instead of TOML-specific array serialization. However, this incorrectly assumes that the entire array is "trivially serializable," which it doesn't have to be since the TOML spec dictates that mixed-type arrays are allowed. This can lead to invalid TOML being emitted, such as the following code:
```typescript
import * as TOML from "https://deno.land/std@0.99.0/encoding/toml.ts";

const obj = {a: [1, {b: 2}]};
console.log(TOML.stringify(obj));
```
Which will print:
```
a = [1,{"b":2}]
```
which is invalid TOML. This maybe isn't a huge issue, since the stdlib TOML parser is lenient enough to handle it, but it would be nice to conform to the spec and not just the implementation.

**Comment by Aplet123** [comment]
This issue is much worse than I thought. When the first element is an object, the whole array is assumed to consist of objects, which leads to the following code:
```ts
import * as TOML from "https://deno.land/std@0.99.0/encoding/toml.ts";

const obj = {a: [{b: 2}, 1]};
console.log(TOML.stringify(obj));
```
outputting:
```
[[a]]
b = 2

[[a]]
```
which completely discards the numerical value.

**Comment by Aplet123** [comment]
In fact, the array doesn't even need to be mixed-type. Here's a nested array that causes the same issue:
```ts
import * as TOML from "https://deno.land/std@0.99.0/encoding/toml.ts";

const obj = {a: [[{b: 1}]]};
console.log(TOML.stringify(obj));
```
Outputs:
```
a = [[{"b":1}]]
```

**Comment by wperron** [comment]
Hey, thanks for the report! If you could include what the expected output would be for those cases that would be an enormous help :slightly_smiling_face:

**Comment by Aplet123** [comment]
Sure! `{a: [1, {b: 2}]}` should serialize to something like:
```
a = [1, {b = 2}]
```
`{a: [{b: 2}, 1]}` should serialize to something like:
```
a = [{b = 2}, 1]
```
And `{a: [[{b: 1}]]}` should serialize to something like:
```
a = [[{b = 1}]]
```
