### ISSUE TITLE
[ws] Ping can be null as per spec

### ISSUE THREAD

**Issue by Skillz4Killz** [denoland/deno_std#988]
**Describe the bug** A clear and concise description of what the bug is.

Ping payloads are crashing the websocket because it doesn't support empty frames (which are allowed by ws spec).

https://deno.land/std@0.100.0/ws/mod.ts#L152 

Specifically, I'm using https://deno.land/std@0.91.0/ws/mod.ts#L152 0.91.0 but I don't think there was any changes to it to make a difference

**To Reproduce** Steps to reproduce the behavior:

1. Receive an ping without a payload
2. See error

**Expected behavior** A clear and concise description of what you expected to
happen.

No error.

**Screenshots** If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**

- OS: MacOS Catalina
- Version 10.15.6

```
deno 1.11.0 (release, x86_64-unknown-linux-gnu)
v8 9.1.269.35
typescript 4.3.2
```

**Additional context** Add any other context about the problem here.

**Comment by bartlomieju** [comment]
`std/http` and `std/ws` implementation was rewritten to leverage native HTTP bindings available in Deno (`Deno.serveHttp` and `Deno.upgradeWebSocket`). This error should no longer occur. I'm going to tentatively close this issue, please let me know if the problem persists.
